== Letters 1 &#8212; 16

[.letter-heading]
Letter 1.

There is not one among thy sorrowful acquaintance
who hath felt the force of sympathy with thee,
on the present afflicting occasion, with greater tenderness than myself;
although I have not hitherto expressed it--I own,
I seldom choose to meet the painful gust of sorrow with calm advice;
I would rather mingle the tear of sympathy,
and aid the solemn tribute due to those who are no more; religion allows it;
for his friend Jesus wept.
But it is now high time for the violence of sorrow to subside,
and the mind to endeavour after a calm acquiescence in the disposition of unerring wisdom,
which hath numbered the hairs of our head;
and not one of them falls to the ground unnoticed of him.
I know some mournful considerations urged for a place with thee: a beloved brother dead,
on a distant shore, uncertain whether every act of tender assistance was yielded him;
but remember, dear friend, the provision of the highest reached him there,
and that the everlasting arm supports and succours the islands afar off!
I have not a doubt of his being admitted where the wicked cease from troubling,
and the weary are at rest.

Endeavour therefore, to suppress the sigh and the tear which border upon murmuring:
good is the Lord in all his works:
he deals with his family in a wisdom we cannot comprehend:
my heart is too full for language to discharge,
and my feeble hand hardly sustains this labour:
but I wanted to mingle with thee the tear of condolence, on account of the dear deceased;
and to endeavour to lead to a calm resignation, and to a pursuit of riches,
unchangeable in their nature, and everlasting in their duration.

[.signed-section-signature]
Samuel Fothergill.

[.letter-heading]
Letter 2.

[.signed-section-context-open]
10th month 9th, 1771.

Desires for thy welfare have frequently suggested sentiments,
which a variety of engagements, or indisposition, have prevented my intimating to thee;
this consideration hath also prevailed, What can I say to him which he knows not,
either with respect to his present or future well-being?
the opportunities of information, outwardly, and the impressions of essential truths,
inwardly, have foreclosed every plea of ignorance, of duty, or of what makes for peace.
But remember, that happiness consisteth not in knowledge;
the words of our great Lord are, "`If ye know these things, happy are ye if ye do them.`"
My soul seeks earnestly,
that the blessing of faithfulness may accompany the privilege of knowledge;
otherwise the greater will be the condemnation.

Thy lot is changed from the warm bosom of society to a land of drought,
where the distilling of heavenly doctrine outwardly as the dew, is little known,
and with many little desired.
Nevertheless, those who seek wisdom, so as to be made wise unto salvation,
may find in themselves the flowings of that river which makes glad the whole city of God.
Feel after this in thy own heart, to preserve thee,
among the few names in that Sardis who walk in white,
and have not defiled their garments; that so thy peace may be promoted,
and others helped.
Think of this awful query, "`What is a man profited,
if he could gain the whole world and lose his own soul?`"

The climate is often unhealthy; let it put thee upon thy guard, in every respect,
and raise fervent care, that whenever the Master of the house cometh,
he may not find thee sleeping, or worse employed.

I am, with sincere desires for thy present and eternal happiness, thy assured friend,

[.signed-section-signature]
Samuel Fothergill.

[.letter-heading]
Letter 3.

[.signed-section-context-open]
2nd month 18th, 1755.

I received thy awakening epistle, of the 30th of 12th month last;
the more acceptable as it comes from one who seems to have undergone dispensations
of Providence nearly like those which have lately fallen to my share.
I can truly say,
I concur with thee in wishing that our being raised up from
the brink of the grave in this the evening of our day,
may occasion our being more devoted to God, and less to the world, and ourselves.
I have been long of the mind that all our outward concerns should be consecrated to God,
and transacted with a constant view to his will, in the several stations assigned us;
and, that a multiplicity of business is a great enemy to the spiritual life,
and prudentially to be avoided in these our declining days; which, in an especial manner,
should be devoted to a preparation for another life,
by a vigilant introspection into our own hearts;
and submission of our will to the Divine will, in all things!

The inward anatomy, that of the soul, and its passions, with the mental medicine,
blessed be God, begins to gain a degree of ascendency, never known before;
and I humbly hope, for us both, shall end in triumphing over the natural, and corporeal,
to which my endeavours have hitherto been too much devoted.
I congratulate us, and these nations, that the experimental religion,
amidst an almost unexampled depravity of manners, among priests, and people,
is beginning to dawn; I will say, in favour of the doctrine of immediate revelation,
I never was so thoroughly convinced of it as in my late illness:
never had so clear a sensation of a being, distinct from my own mind,
immediately and instantaneously enlightening and enamouring
my soul with the love of eternal truth and justice,
as then! nor ever had I so complete victory over the peculiar
inordinate affections of my mind as then;
a time I cherish the remembrance of, with great delight,
as having shewed me the possibility of a complete victory over sin.
I see now the necessity of deep mortification, as a proper discipline, penance,
and even condition of our being admitted into the
ocean of undisturbed happiness and glory.

Let me now observe, from the regard I have to thy bodily health,
(who art also but lately emerged from the most imminent
danger) that on the principle of self-preservation,
and with very good effect,
I practice great economy and care of the shattered bodily and mental fabric;
avoiding inclemencies of weather, eating and drinking moderately, and sometimes fasting;
reading and writing less; and taking the air, on a favourable day, before dinner.

So wishing us to study peace and tranquillity of body and mind,
I conclude thine affectionately,

[.signed-section-signature]
John Rutty.

[.letter-heading]
Letter 4.

[.signed-section-context-open]
2nd month 14th, 1756.

I now begin, with some degree of zeal and affection,
and according to thy good resolution and exhortation,
to adhere chiefly to subjects of a spiritual nature,
and such as may have a direct tendency to prepare for a better and happier state;
which it behooves us to have frequently in prospect,
and to cultivate the __medicina mentis__^
footnote:[Medicine of the mind]
more, and that of the body less;
an anxious pursuit of business in the medicinal way is very unsuitable to our situation,
on the borders of eternity.
I have been greatly favoured of late with an opportunity
of retiring to the country a night or two in the week,
and thus have shaken off such a share of business as was burdensome,
which some of the younger men get.
I assure thee, I find no danger of over doing it in spirituals by such conduct;
for still natural and medical affairs are too apt to encroach;
divers infirmities of mind still hang about me, and humble me, but are not indulged;
on the other hand, a victory hath been obtained, in some considerable degree,
to the glory of the goodness of that omnipresent, omnipotent, and gracious being,
which is ever present with us!

In the way of reading, I choose rather to digest and apply, than read much;
among the books that have lately fallen in my way,
I much value some of those written by William Law;
but I fear this excellent man has a little blocked
up his way by adhering so much to Jacob Behmen;
and as to his account of the transactions of angels before the fall,
I could wish he had never meddled with it.
Thomas a Kempis is another writer of good estimation,
especially for his treatise of the following of Jesus Christ.

Thus I have exhibited a small sample of a spiritual correspondence;
and shall be glad to receive something of this kind from thee:
but I desire thou mayest not conceive an opinion of me beyond my desert;
I speak rather of my inclination than attainment.
I am thy loving cousin and brother,

[.signed-section-signature]
John Rutty.

[.letter-heading]
Letter 5.

[.signed-section-context-open]
11th month 12th, 1756.

I take notice of thy recommendation of Isaac Penington`'s writings,
to which I am a stranger, but hope I shall not long be so.
I lately received by a friend from America, the life of David Brainard,
a missionary to the Indians; published at Boston in New England, 1749,
being a spiritual diary, or narrative of observations on the state of his own soul.
A sample of spiritual history,
as much preferable to natural (in thy and my view) as soul is to body;
the narrative is solid, weighty, and candid;
he appears to have been divinely qualified for the work;
and that he saved not only his own soul, but the souls of many others,
awakening the dormant sparks of the divinity in them to a flame!
the same tendering power being witnessed as we hear of among ourselves;
and its efficacy demonstrated in a change of heart, affection, life,
and conversation in the hearers.
Great were the conflicts he underwent whilst struggling
with his various weaknesses and sins;
yet a ray of divinity shines through these clouds; and he grows brighter, clearer,
and freer from these impediments as he advances towards eternity; and manifesteth,
at his approaching, solemn, slowly advancing dissolution,
(such as thine and mine) clear and just conceptions
of that temper which renders acceptable to God,
and prepares for a happy translation!

I am desiring to hear from thee, at thy leisure, in this new language of Canaan,
which we are beginning to learn in our old days.

[.signed-section-signature]
John Rutty.

[.letter-heading]
Letter 6.

[.signed-section-context-open]
6th month 13th, 1757.

The similarity of the dispensations of Providence towards us seems
happily to have laid a foundation for a spiritual correspondence,
which I hope will be continued between us, as long as integrity of heart remains.
I profess to thee renewedly,
that afflicting hand did more for me by way of weaning from this world,
and quickening my attention for another, than all outward arguments could have done:
and I desire,
that we may ever be preserved obsequious to the divine leadings
in this respect! weaknesses and temptations still surround,
but I humbly hope do not overwhelm.

I find no cause to retract what I have advanced,
in my history of the rise and progress of friends in Ireland, against the Pope,
as the grand antichrist and great corrupter of Christianity;
and in tracing the steps and gradations of the apostacy, unto the midnight of darkness;
giving some sketches of the emerging of the light of the reformation;
which I am inclined to believe shall rise higher and higher,
notwithstanding all discouragements.
In this view I look upon the book of the Apocalypse,
to be one of the most important of all the New Testament;
for unless the dreadful apostacy and corruptions which have happened had been so foretold,
and also a restitution foretold by the same authority, our faith might have been shaken,
which by this revelation is greatly strengthened and supported;
at the same time it is our proper province to believe in the Supreme Providence,
and humbly adore its impenetrable wisdom!

Thou wilt not suspect me of being visionary on occasions
wherein I have censured other short-sighted honest men;
but it looks to me as if our dear country was well nigh
arrived to its __Ne plus ultra__^
footnote:[The perfect, ultimate, or most extreme example of its kind]
as to dissoluteness of manners:
and without the gift of prophecy, perhaps it may be said,
there never was a period of time more teeming in great events;
but I proceed no further on this subject;
let us join with the church in her progress in coming up out of the wilderness;
and in every instance of the restoration of primitive simplicity and purity!

[.signed-section-signature]
John Rutty.

[.letter-heading]
Letter 7.

[.signed-section-context-open]
12th month 1st, 1759.

I acknowledge kindly thy account of the several editions
of the Bible among those called Catholics;
which book, where it is read,
must undoubtedly represent Christianity in a very different light
to the people than that in which the priests have represented it.
The downfall of the Jesuits in two kingdoms, I would hope bodes good;
we have had of late, in this city, many converts openly renouncing popery;
notwithstanding this, I heartily concur with thee,
that the greatest corruption of manners may be accompanied with the most orthodox opinions:
on the other hand, though I have spoken thus of the Jesuits,
I have lately met with a book wrote by one of this order,
who seems to me to give evidences of a truly Christian spirit;
and under most heterodox opinions (which are the worship of saints,
and transubstantiation) to maintain great purity of heart,
and a lively zeal for the promotion of holiness and moreover under the present
dreary times of great desolation within the narrow limits of our society,
it gives me much comfort that God is here and there,
awakening the same spirit of true Christian simplicity
which animated our ancestors in the beginning;
and I am abundantly satisfied that many shall come from the east and west,
and sit down with Abraham and Isaac.

In the mean time take the following short sketch of Zion in distress, and if thou canst,
send me any word of consolation.
Here is a large congregation, formerly accustomed to plentiful,
and very frequent showers of the doctrine of the kingdom, in purity;
now by the death of those who were as the vehicles of it,
left in a manner destitute of supplies of that kind; insomuch, that we who are left,
are forced either to have recourse to the invisible fountain, at first hand,
or to sit dry and parched; the latter, I fear,
is the state of many! some of these are going off, and others will go: however,
at present, many of us hold together.
In the midst of this, sometimes there starts up an __ignis fatuus,__^
footnote:[Delusion, or false light]
boasting of superior light, but kindled, if I mistake not from below;
reproaching those who remain steady with this language, "`You are dumb,
but I must not be so.`"
Thus provoking some tender ones, who dare not move without the proper qualification; and,
who having much work to do at home, are necessarily kept in that exercise,
and hindered from going abroad.

I give thee a sad picture, but too true: had not some of us a supply of a little faith,
and a little love,
we had perished in this wilderness! the consideration
of the afflicted state of the church in ages past,
and some glimmerings of the hope of the gospel, also bring a little support.

[.signed-section-signature]
John Rutty.

[.letter-heading]
Letter 8.

[.signed-section-context-open]
1st month 8th, 1761.

Thy account of thy brother`'s death, and of my brother`'s state of health,
are both instructive, and I acknowledge them as such.

As to the languishing state of Zion,
I have of late suffered more sensibly than ever in my life before;
at times ready to be deserted by brethren I had an esteem for; however,
blessed be the Lord, I am not left quite disconsolate.
Upon perusing the holy records, I find the church has generally been in trouble;
and often in more calamitous circumstances than any thou or I may have observed,
and yet was never wholly forsaken;
the prophets will furnish thee with numerous instances,
which have yielded me considerable satisfaction.
That we may be preserved from a participation in the general defection and corruption,
is the great spiritual object.
But again, I consider we are perhaps more alarmed at these things than we ought to be,
in expecting too much from exteriors, by a conformity to our refined way;
which really can effect no more than circumcision to the Jew outward.

Thy mentioning a certain writer,
suggests an observation of the too much prevailing neglect of reading the holy scriptures,
even among some of our ministers; I am far from denying, on the contrary,
I commend the imploring divine help;
but at the same time we ought to be diligent in the perusal of these sacred records;
comparing the frequent references and connections of the Old and New Testament.
I need not tell thee that our chapters are, not unfrequently, badly divided,
which if not attended to might prevent our having
a right understanding of what is before us.

Let reason be exercised; not to pride and ostentation of science,
but as God`'s precious gift; and let no man of superior talents and opportunities,
cover his spiritual idleness, under a specious claim to divine inspiration.

[.signed-section-signature]
John Rutty.

[.letter-heading]
Letter 9.

[.signed-section-context-open]
5th month 30th, 1761.

Thy observation of the preference of a suffering state to that of being at ease in Zion,
ministers some comfort to one who knows himself to be one of the least of many brethren.

Shall I mention to thee, in a summary way,
the use I have made of my late reading of the scriptures,
after many and long omissions of this exercise, whilst busy on natural subjects,
with an honest view to the promotion of useful knowledge, morality, and temporals,
which were set up above evangelical righteousness: faith,
and a view to another and better world, being in a great measure absorbed.
At length did a gracious providence lead,
and as it were allure me to reading these sacred writings;
and now I have a far greater veneration for them than I had before,
not only as setting forth the majesty of Christ Jesus,
but I have found them to be a seasonable support to my faith,
in reference to the woful apostacy overspreading the Christian churches,
clearly foretold; and the coming out of it pointed at.
May thou and I be ranked among them that are coming out,
although in some sort with the witnesses that prophesied in sackcloth!

The prophet Jeremiah was a man of sorrows, raised up in the midst of an apostatizing,
idolatrous people; faithful and constant under the severest trials,
he manifested God`'s prescience in the accomplishment of events more remote,
and in those concerning the gospel day, and new covenant.
May a degree of his faithfulness attend thee, and me,
under the present sad state of the society; although we be no prophets,
faithful witnesses we may be.

This prophet has furnished me with a conviction of the harmony,
and connection there is between the Old and New Testament writers,
besides other instructive lessons.

Having thus given thee some hints of my experience
in spiritual concerns as the most important,
I now descend to temporals.

[.signed-section-signature]
John Rutty.

[.letter-heading]
Letter 10.

[.signed-section-context-open]
12th month 11th, 1762.

Thus retired, I sit down to discharge my arrear to thee: and first shall say,
I join thee in discouraging a universal charge upon some of our modern reformers, as if,
by mistaken notions of Christ`'s righteousness,
they encouraged a persisting in immoral lives;
for from a personal knowledge of some of them,
I have the charity to think that their faith is a living operative one,
and such as hath produced an entire change in their manners.
Give me leave further to say, in their behalf, that a mere dry morality,
little better than that of the heathens, has been the general language of the pulpits;
the revival of the doctrine of faith in a Christ, both external and internal,
seems to me to be doing notable service to the drooping cause of Christianity.
Bad men, under the Christian name, may profess belief in Christ, and his doctrine;
but I profess to thee, I do not think they really believe in them; but that unbelief is,
in a great measure, the true source of their wickedness.
Give a man a due share of faith and love, and I will warrant for his obedience.
Legal men, among us, have cried, Do this, and avoid that,
in order that thou mayest be accepted; but, if I mistake not,
God is teaching some better, and enabling them to lay the axe to the root of the tree.
Come to meetings, says the pharisee; but love God, says the evangelical man,
and I will warrant for the consequence; but he also saith, put away thy idols first.

As to our spiritual state here, as a people signally called out of the world,
it is truly poor and languishing;
we have indeed been favoured lately with an instance of divine mercy,
in a visit from the brethren, in consequence of a recommendation of the yearly meeting;
and as far as I have been a witness to the conducting of this visit,
it has been with an honest zeal, love, and Christian prudence; and I humbly hope,
that the word spoken will not return void.

But to conclude and take a review of our analogous spiritual circumstances.
As we have both heard God`'s alarming voice, in restoring us from the jaws of death,
and taking or being about to take our elder brother a little before us,
(and we are riding post on the same road,) let us prepare to meet the bridegroom;
and trim our lamps, in higher degrees of love and zeal for his Cause on earth;
being loosened from every worldly attachment how specious soever;
that we may be ready to enter the chamber.

[.signed-section-signature]
John Rutty.

[.letter-heading]
Letter 11.

[.signed-section-context-open]
10th month 6th, 1763.

As to our religious state in this place, as a society,
great is the desolation! and the awful seat of an elder is fallen to my lot.
But amidst all our backslidings,
a gracious providence has been extended in divers truly acceptable visits of ministers,
and especially by the national visit;
which has had a tendency to improve and establish our discipline;
whilst it has shaken certain lifeless forms which did more hurt than good.

I would gladly hope Providence is watching over us for good,
in putting it into the hearts of some to form a plan for erecting
public schools for educating our youth in a manner entirely select,
and separate from those of other societies (though here we are but poor,
in comparison with you); and if thou knowest of any public spirited friend,
who has money to spare, and would send over ten, twenty, fifty,
or an hundred pounds for this purpose,
I would be answerable for the application to the valuable end of preserving,
and saving some individuals, who without this means would be lost;
for we see the children of those who embrace his way,
are running with a rapid career into the world again; some of whom, by this holy policy,
with the cooperation of the divine blessing, might be preserved.

In conclusion, I would remark,
that the exercise of a wholesome Christian discipline
lies heavy on the shoulders of a few;
although absolutely necessary to preserve the society from open contempt.

[.signed-section-signature]
John Rutty.

[.letter-heading]
Letter 12.

[.signed-section-context-open]
5th month 8th, 1773.

I hope thou wilt excuse my delay of acknowledging the receipt of thine,
when thou shalt have heard how it has been with me.

It is now above a year and a half ago that I was
seized with a paralytic stroke on my right side,
and in my tongue, although not to the highest degree, nor my senses impaired;
but by the indulgence of Providence I have so far slowly recovered
my limbs as to be able to walk a mile without resting;
the use of my tongue is also in a great measure restored.
Now, reckoning my seventy-fifth year, I commence a downright old man.
I am, however, very thankful,
and possess my mind with great tranquillity in this happy
exemption from the anxiety and cares attending practice;
and for the opportunity it gives me to revise, correct, and improve former labours.

I would gladly, at a proper opportunity, be informed of your spiritual state; as to us,
in this city, a day of trial now attends us, being as to ministerial help, in a manner,
wholly stripped; it is true, some attempts have been made by intruders,
but these have been silenced: although for my part,
I would be far from stopping the mouth of the least babe.

Amidst all discouragements in a human way, faith comes in to our aid, even trust in God,
who hath often brought forth events beyond all human comprehension.
Some convincements, are an instance to this purpose,
and the children of unpromising parents raised up to eminent service.

[.signed-section-signature]
John Rutty.

[.letter-heading]
Letter 13.

[.signed-section-context-open]
11th month 20th, 1750.

In Dublin I received a letter from thee.
I rejoice in this, that the Lord of heaven and earth is visiting by his truth,
and working by his power, to beget into his heavenly family;
and bless his people with that which conveys all the happiness mankind ever did,
or ever can taste! too many are insensible of it;
others too careless to be religious as they ought;
but it is our interest to pursue our own peace, and transmit to others examples.
It is an excellent thing to be true subjects of Christ`'s kingdom,
baptized into his nature, and therein to abide.
Great has been his mercy in visiting our souls with his blessed truth,
and it highly behooves us to watch with all diligence.
It is our duty to look to him daily; this comprehends all;
here is our strength and safety; other stays or temporary help will fail,
and leave us destitute, and inwardly lean;
oh! therefore remember often the dew of thy youth,
the tenderness of thy heart when first met with;
cherish in thy soul the fresh instance of regard, and be it thy care inwardly to look,
and live to the Lord, so shall thy hands be made strong,
and thy head be kept above the water.

There is a spirit that is gone forth into the camp, and is splendidly delusive;
it delights in good words but feeds upon them; it cries out help, help,
but principally to the servants, not the master; this spirit leads into notions,
it snuffs up the wind, and lives in commotions itself raises;
all that are led by it are superficial, and know nothing, and must lie down in sorrow.
That holy spirit which was and is the ground of truth forever,
(which I trust has reached thy heart) is a substantial operative principle;
its directions are not imaginary, nor its doctrines loose and indeterminate;
but it is life and light to its possessors, and causes them to inherit substance;
it teaches access in heart to God, whose attributes cannot be defined fully,
but experience teaches them; supplying their wants, supporting their steps,
opening their understanding into those divine truths that are higher than human wisdom,
let this spirit be leaned upon above all: this will help us to stand upright,
and walk steadily in the faith delivered to the saints;
retirement will be pleasant in meetings, and out of meetings;
the inward feelings of the divine power to live and act to God`'s
honour and our own preservation will be dear and precious to us;
and he that delights to hear the language of his children will
not be slack in the performance of his gracious promises;
I found the free salutation of gospel love in my heart to thee,
and earnestly entreat thee to abide stedfast in the truth; feel after it, live in it,
hope for its salvation, and it will never fail.
I salute thee in the love, and affection of Christ our holy and blessed helper,
and remain thy faithful friend,

[.signed-section-signature]
Samuel Fothergill.

[.letter-heading]
Letter 14.

Under a renewed sense of that love and life which hath ever been the preservation
and support of the Lord`'s children as they have kept near unto it,
hath my mind been nearly united in tender love and
sympathy to some of my dear friends at Sheffield;
whose minds have been sensibly wrought upon by the renewed
operations of the Lord`'s forming hand of power,
to prepare them as vessels for his own use,
particularly those few who are lately come forth in the ministry.

Dear friends; who have thus been pointed out by the great Shepherd of Israel,
and brought into the school of Christ, to be trained up under his hand and eye,
that you might thereby come to be prepared to do the Lord`'s work and go his errands,
after you had in some measure improved the gifts and talents of grace,
which he had in mercy bestowed upon you, in order for your salvation and redemption.

You received an additional gift, which was begotten in you,
and under which you travelled many times in tenderness of spirit;
and were often deeply baptized into a feeling sense
of what was likely to be brought forth,
and many were the pangs, and deep searchings of heart that you experienced,
until he that had brought to the birth, gave strength to bring forth;
which was done without your skill or contrivance, for it was the Lord`'s doings,
and it was marvellous in your eyes;
so that you are somewhat like that servant who had received two talents to improve:
and this calls for greater vigilance, circumspection, and care,
than he that had received only one talent; that you may have to say,
be ye followers of us, as ye see we follow Christ;
and as your gifts were not of your own procuring,
but according to the good pleasure of him who hath
the government of his church upon his own shoulders,
he saw meet to intrust you with them,
that they might be occupied to the glory of his great name;
but as they were not of your own procuring, so neither are they at your own command,
but must be waited for in deep humility of mind,
in order to come at a right knowledge of when to speak and when to be silent;
and there need not be much anxiety about it, if the mind is kept in a watchful state,
and careful that nothing, through our unwatchfulness or neglect,
deprive us of the sense of our gifts; but those who are thus brought forth,
may have in their infant state,
(as well as those that are further grown in experience,)
many trying proving dispensations to pass through;
for the dragon, that withstood the woman in order to devour her man-child,
as soon as it was born, will withstand them; and try them many ways,
that he may warp them aside from the holy commandments delivered to them;
and these are sometimes carried to a place prepared for them, as in the wilderness;
where they are secretly fed, and sustained,
though their gifts may be hid as in obscurity for a season;
in which trying time there is much need of patience,
that there is not an attempting to come forth from the wilderness before the right time,
ere the floods be subsided which the dragon cast out of his mouth,
and so be in danger of being carried away with them.
For it may not be one of the least of his temptations,
when it may please the Lord to hide our gifts, for a trial of the love,
faith and patience of his servants,
and for the better qualifying them to know their proper seasons,
to endeavour to draw them out, though the clouds may not be taken off the tabernacle,
and so lead them into confusion; and their offering,
not being seasoned with the salt of the everlasting covenant, it hath not a right savour,
nor is attended with a right evidence; and when he hath effected this,
and the mind comes to be made sensible of it,
(either by the gentle admonitions of some sensible feeling friends,
or by the light of truth, or both,) manifesting their mis-stepings,
then his next work is, if not carefully watched against, to persuade the poor creatures,
that they are upon a wrong foundation, having been running when the Lord never sent them;
and they see that their offerings are not accepted,
and are so led into reasoning and consultations with flesh and blood,
thereby to lose their strength by hearkening to the voice of the enemy;
and it is to be feared that some have been led into a wilderness,
out of which they have never more found their way:
there are also other ways that he works with some, by endeavouring to persuade them,
that their gifts and capacities are so small, and weak,
that it is never likely they should be of any use:
by which means some have been discouraged, not considering,
that it is out of the mouths of babes and sucklings the Lord ordaineth praise;
and that he hath chosen the weak and foolish things of this world,
to confound the wise and strong.

But dear friends,
wait daily to feel after the life and power of truth to gather and settle your minds,
under a sense of its holy influence; and never move but under the necessity,
and in the openings of truth; remember that Aaron, our great type, under the law,
was never permitted to approach to minister before the Lord,
until he was renewedly clothed with the hallowed garment,
on which were placed both the bells and pomegranates which testify both sound and substance,
or nourishment;
and it will tend to your safety not to make additions
to the openings of truth on your minds;
but if there should be only a few sentences that are required, be content;
remember that under the law, when they offered according to their abilities,
those that could only offer a pair of turtle-doves,
or two young pigeons were accepted as well as those that offered their bullocks and rams;
and, as you keep in the simplicity, and near to your gifts,
you will in due time witness an increase, if the Lord see meet.

As these things seemed to spring in my mind with a degree of gospel love,
I have in the same love communicated them,
earnestly desiring your establishment and growth on the everlasting foundation;
for the harvest truly is plenteous, but the faithful labourers are few;
though I am far separated from you, yet in that which neither length of time,
nor distance of place, can diminish, I often remember you,
and these will serve as a pledge of my regard, who remain your affectionate friend.

[.letter-heading]
Letter 15.

[.signed-section-context-open]
5th month 19th, 1758.

When I consider the good company you have providentially been favoured with,
and the advantageous situation you are at present happy in,
it would seem unnecessary to offer any thing by way of caution, or counsel,
respecting your conduct, whilst in this kingdom:
but though you are thus agreeably seated, I take it for granted,
in the course of your stay,
you will make some excursions from the place of your present abode,
to different parts of the kingdom,
which must necessarily subject you to variety of company;
in this case I do not apprehend the worthy friend, in whose house you lodge,
will be deficient in giving you the necessary advice, for your benefit;
yet I do not find this will excuse me from offering to your consideration a few cautions,
respecting one very material part of moral and religious conduct in life,
which is the choice of company.
The saying of the apostle Paul will always remain true,
"`That evil communications corrupt good manners.`"
The experience of many ages has confirmed it: it is also truly said,
a man is known by his company; and that, as his friend, so is he.

Bad company, or vicious examples, are often hurtful to men of years,
and sometimes to those who had formerly been experienced in good,
when they come to be thus exposed:
but youth is more especially a dangerous period of life,
in which we are more liable to embrace things that are inconvenient, as well as unlawful,
and to be drawn aside by the various temptations, crafty allurements,
and unprofitable friendships of the world.
And I know of no place on earth,
where incitements to ungodliness and vanity more abound than in this kingdom in general,
and in this city in particular.

I make this observation as a hint to you, to retire into your own minds,
and consider how necessary it will be to your good, and well being,
that you avoid the conversation of men of corrupt minds,
who you will soon know by their fruits;
whose snares and temptations will steal as insensibly into the affections,
as the venom of a serpent creeps into the veins of the subject it has wounded:
therefore I advise you against making such men your intimates and familiars.

I have sometimes thought, that vicious examples have the same effect upon the soul,
at least the affections of it, that deformed bodies have at the first view of them;
they excite an unpleasant painful idea, but, by customary and familiar converse,
the disagreeable sensation ceases, and we become quite easy, and reconciled to them:
thus vice, in the first appearance, affects a tender innocent mind with horror and dread;
but being hardened by custom, and habit, the painful impression gradually wears off,
and it becomes more easy, and perhaps agreeable; and then the next step is to embrace it.

I would not have it understood as if I thought you would choose to frequent
the company of men of apparent dissolute lives and practices,
who are not afraid to glory in their shame;
but I would caution against associating with the more hidden and secret foes
of Christianity (such young men as outwardly profess the blessed truth,
but hold it in an unrighteous conversation, at clubs, and night-revels,
frequenting places of public diversion, invented by the imagination of sinful men,
some of whom, we have reason to fear, deny or at least call in question,
the sacred truths of the Christian religion); from such men,
though they may call themselves brethren, I counsel you to turn away; and,
as virtue and piety, as well as vice and folly, are communicated by example,
I desire you will take every suitable opportunity of having
the company of solidly religious persons of our own society.

But as it is not sufficient, that we only observe the negative part of our duty,
in abstaining from evil, if we desire to be perfect, we must learn to do well.
Though the man is blessed who walketh not in the counsel of the ungodly,
nor standeth in the way of sinners, nor sitteth in the seat of the scornful,
yet he is not fully so,
till he is found delighting in the law of the Lord after the inner man;
meditating therein day and night,
observing to do according to all that is written therein.

Then these blessed effects will follow,
that he shall be like a tree planted by the rivers of water,
which bringeth forth its fruit in due season.
And, if this holy exercise of mind is continued,
he shall receive of the sap and nourishment from the Fountain of Life,
so that his leaf shall not wither, and whatsoever he doth shall prosper:
"`The steps of a good man are ordered of the Lord; the law of his God is in his heart,
none of his goings shall slide;`" in order therefore to the performance of our duty,
it is necessary we should acquaint ourselves with God,
and seek to know his will concerning us, by believing in,
and adhering to the good principle we profess, of the light of Christ in our consciences:
it is this alone can give us the saving knowledge of God;
and as we are obedient to its teachings, we shall not only deny ungodliness,
but by living a godly life in all holy conversation,
manifest we are loving God above all things, and our neighbour as ourselves.
And if the delight and joy proceeding from love to God,
and an evidence of his love to us, be the only true and real happiness of mankind,
it necessarily follows,
that the sooner we are come to the possession of this inestimable blessing,
the happier it will be for us!
I am one, who have to lament, that I forsook my own mercies,
in that I did not remember my Creator in the days of my youth:
that I neglected to acquaint myself with God in my younger years,
knowing that an early sacrifice, and devotion of heart is acceptable to him:
I have considered how many years I lost in unprofitable pursuits,
delighting in things I am now ashamed of:
many precious moments I might have enjoyed had I been so
wise as to have enquired wherein true happiness consisted;
I have never heard of any who thought they had sought God too soon; but many mourn,
that they knew him too late.

But to return to what chiefly affected my mind, and has drawn from me these cautions,
viz. the consideration of the temptations persons are exposed to, in the time of youth,
(though in no part of our lives we can be said to be in a state
of security free from the attempts of the enemy of souls,
and therefore a state of watchfulness is necessary
to all ages and conditions) it appears to me,
that there is more than ordinary occasion for circumspection
when men are beset with enemies from all quarters,
as is eminently the case in this great city; things, men, and books, as it were,
lie in wait to deceive, and cheat people of true happiness; with regard to books,
if a vain curiosity should be indulged in reading many publications of the present time,
whose chief tendency is to promote an undue liberty from the restraints of religion:
the knowledge acquired by such reading is evil, and will,
by the unsound principles and erroneous doctrine, of one sort, and the profanity,
and licentiousness of the other, bring death to the soul;
as they will prevent the true knowledge of God from taking place in the heart,
and hinder the growth of the seed of immortal life,
by which the soul is raised from earthly to divine and heavenly objects.

I write from a degree of my own experience of the hurt received by means of such writings,
and am the more earnest with you, as you value your peace, to avoid the perusal of them,
as they can administer no real benefit, but on the contrary certain evil.

Having thus enlarged my letter, beyond expectation, I shall only add,
that as you profess no less than the blessed truth, as it is in Jesus, may you,
by its divine assistance, and obedience to its holy dictates,
be made and kept perfectly free from the entanglements of a vain and sinful world,
and be enabled to hold fast the profession of your
faith in a good conscience without wavering;
keep near to the testimony of Jesus, the sure word of prophecy, in your hearts;
whereby you will be able to resist and quench all the fiery darts of Satan,
and his agents.

To God I recommend you, and the word of his grace,
which is able to strengthen and build you up in the most holy faith,
and remain your sincere friend,

[.signed-section-signature]
Sophia Hume.

[.letter-heading]
Letter 16.

It came before me this morning,
with some degree of sweetness to visit you with a line of caution, and encouragement,
in the pure and unfeigned love of the gospel of Christ; to you, the professors of it,
my dear youth, to remind you, who are capable of reflection,
of the great goodness of our God, in visiting you with his salvation,
and affording you the blessed privilege of the knowledge of his unspotted truth,
not only through the teaching and instruction of his blessed spirit;
but you enjoy the advantage of sitting under the doctrine of his called, chosen,
and anointed ministers, whose lips preserve knowledge,
rendered convincing by the strongest argument and proof of faith in Christ,
viz. such an example and conversation as becomes the gospel.
You have this help in a double capacity,
as well from the ministry as in those you are so happy to call father and mother,
who I make no doubt use their endeavours to bring
you up in the nurture and admonition of the Lord.
This is a blessing I once had an opportunity of improving to my eternal advantage,
from the instruction and admonition of my dear mother,
who endeavoured to instil principles of the doctrine of Christianity, to wit,
the indispensable duty of self-denial,
without which we can in no wise lay claim to that glorious
title of being followers of the blessed son of God,
who came to lay self low; to lay the axe of his power to the corrupt root,
from whence proceeds pride, evil thoughts, which when conceived, and joined with,
bring forth sin.
Pride is a sin productive (as I have thought) of every other evil;
having observed that where pride is suffered to predominate, that we see every evil work;
pride excited me to pursue worldly wisdom, and knowledge;
pride put me upon endeavouring after what the world call accomplishments;
pride taught me to emulate any that was superior in pomp, state, or equipage:
pride taught me to deck and adorn my person, to be nice and curious in my apparel,
to carry my person delicately, and walk with mincing steps, and outstretched neck;
pride taught me to be cautious lest I should have burning instead of beauty,
and put me upon wanting washes to improve my complexion.
Pride taught me the genteel carriage, the foolish jesting,
the false cheerfulness (a name now given to laughter, wantonness, and foolish jesting);
pride led me to read unedifying and pernicious books; to sing songs,
to please myself as well as others; in a word,
pride led me to desire the lust of the eye, and pomp of life.

I know not that what I have mentioned is any of your weaknesses; but this I know,
that childhood and youth are vanity; not from a propensity or principle instilled,
or given them, by the wise Creator; but the enemy hath done this, or by his agents,
sown evil seeds of pride.
For though our parents may give us Christian advice, and example,
(as was my case) we are surrounded by evil examples.

My mother was but one, and so I despised her admonition,
and followed the multitude to do evil.

But now it comes before me to mention the goodness of Israel`'s God;
whose tender mercy is over all his works, and will leave all without excuses,
and therefore affords all a day of merciful visitation,
in which he manifests his blessed will, and what he requires of us.
He would have made my dear mother an instrument in his hand of turning me from
darkness unto light! but I would have none of her self-denying counsel,
and cast her words (which I have since thought were from the Lord) behind my back.

And now I will tell you what I suffered in my very youthful days,
in the refusal of the Lord`'s kindness to my soul;
he was pleased to visit me with sore and distressing sickness, which all about me,
as well as myself, thought would be unto death; and in this trying season,
when not only all my delights forsook me,
but the wrath of God was revealed against all unrighteousness,
and my sins set in order before my face;
the veil of obduracy with which the god of this world had blinded my spiritual eye,
was rent: I saw my guilt,
and was greatly condemned in rejecting my dear parent`'s admonition:
but upon promises of amendment, the Lord was so merciful as to spare my life,
and restore me to my usual good state of health.

But let me ever lament what followed; that after this I should turn again to folly.

Yet, (forever renowned and blessed be the name of our God) after a series of years,
he was pleased eminently to visit with his love and offers of grace, and reconciliation;
upon the condition, that if I forsook the foolish, I should live; observe,
this was the second visitations of God`'s love and glory;
who assisted me by his grace to be obedient to the heavenly vision.
He let me not only see him the dread, but beauty of nations.

Then I was ashamed in my own sight, when I saw his purity:
I could not delight to adorn my body, when I saw the nakedness of my soul,
I left caring immoderately for the body,
and was made willing in the day of God`'s power to be stripped of my delights,
that I might be clothed with the righteousness of Christ.

And as I gave up to the divine discoveries, and present manifestations,
the reward of the Lord attended my obedience to his will, even that peace,
which all the enjoyments of this life never did, nor never could afford;
being all as dross and dung in comparison of this transcendent enjoyment,
this approbation of God.

Dear children!
I believe you know the truth, but this will not do for us,
unless we obey the dictates thereof; it will do us no service to hear Christ preached,
and set forth crucified before our view, unless that, as he died for sin,
we also come to die to sin of all kind.

Be sober and watch unto prayer, that the enemy sow not his tares,
and choke the good seed of the kingdom,
and deprive you of the blessed privileges with which you are favoured.
As obedient children,
fashion not yourselves according to the lusts and vanities of the world:
look not out at others, who may profess with you, but look continually to him,
who is able (as you are willing) to keep you from the spots of the world.
Remember if any love the world, the love of God abides not in him:
they cannot subsist together; what nourishes the one, destroys the other.
Therefore as an evidence we are risen with Christ from the earth, or earthly things,
the apostle tells, our affections will be set on heavenly things, or things above,
for where our treasure is, as our dear Lord says, our hearts will be also.

Now my desire for you is that you may be endued with
divine wisdom to choose the better part;
not to cumber yourselves, as you advance in years, too much in serving the body;
but may part with all that stands in your way, to purchase the pearl of price.
I can declare to you, that with all my gettings, for which I been so anxiously concerned,
I never got peace, till I sold all to make this purchase:
and as I am careful to keep what is committed to me,
I rely on the gracious promises of our God, that it will accompany me beyond the grave,
and not me only, but all who love, and obey,
the appearance of our Lord and Saviour Jesus Christ!
to whose blessed teachings I leave you,
dear children, and remain your true friend,

[.signed-section-signature]
Sophia Hume.
