== Letters 25 &mdash; 49

[.letter-heading]
LETTER 25.

[.signed-section-context-open]
4th month 1755.

We should labour to command our own spirits, which not being properly subjected,
I believe, often prevent the spirit of truth from reigning and governing in us:
without whose influence, how can we walk exemplary before our families and neighbours,
or be serviceable in the society.
I have thought that we are compound beings, and as we are a mixture of matter and spirit,
soul and body, so the soul has a mixture of the natural and spiritual,
which have a very close connection.
Neither is this connection between the natural and spiritual part of the soul any more
necessary to be divided for our well being (in some degree) in this life,
than the soul and body.
It is requisite that, in both cases, the natural be subject to the spiritual.
But as the improper usage of the body often stupifies the soul,
so the improper government of our own spirits often hinders
the arising into dominion of the spirit of truth.

Let us then, dear friend,
use all the means in our power to keep our own spirits in subjection,
and regulate our outward affairs as well as we can in order to attain that end;
and Providence, doubtless,
will not be wanting by supernatural aid to assist
us in subduing those enemies of our own house;
that so by degrees body, soul and spirit,
may be brought into a proper rectitude in his sight.
Methinks it is a very useful and essential part of knowledge,
to distinguish between the natural and spiritual both in ourselves and others,
in order to be rightly qualified for the service of this day.
But our own fallen wisdom can never comprehend this knowledge.
This is only to be learned of the word,
which the apostle compares to a sword that can make a division,
as between the joints and marrow, the soul and spirit.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
LETTER 26.

[.signed-section-context-open]
1st month 1761.

Surely some people or other, of honest plain and simple hearts,
will be raised up as witnesses to this life: for,
as to the generality of us now making profession of it, there are numbers,
who seem entirely unacquainted with the influence of it,
and neither to own it in their experience, nor confess it in their lives.
According to my little sense,
a spirit of ease and indifference has taken such strong root among us
that it must be some violent and terrible shock that will loosen it.
A declension is often and justly complained of,
but I wish we would each strictly examine ourselves, how far we are clear of it.
It has of late appeared to me that whoever through want of watchfulness
or faithfulness does not come up in the rank and station allotted to him,
but falls short of the service designed him, comes short of the glory of God,
and contributes individually to this general declension,
though he may have been and still is the visited of the Lord, and a child of the family:
and when I consider the excellence and importance of the cause of true religion,
and what manner of persons those should be who are engaged to be active therein,
I have been ready to say, who is sufficient for these things?
these reflections above hinted seem however to have this good effect on myself,
that measuring what I am by what I ought to be, and perhaps might have been,
if it had not been my own fault,
I am made thoroughly sensible of my own weakness and worthlessness.
I wish I could as effectually get released from my failings, as I plainly see them,
and sometimes heartily lament them.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
LETTER 27.

[.signed-section-context-open]
5th month 1762.

We have been informed of thy embarking in the uncertain
and precarious business of a boarding school.
It may well be termed embarking,
because it seems much to depend on the temper and caprice of others;
tempers fluctuating and changeable.
But as there is one whom the winds and seas obey,
so if we first and principally seek his blessing,
and demean ourselves at all times and in all places
with such a tender regard to his honour,
and fidelity to his testimony,
as will most certainly draw down his notice and favour upon us,
we shall do well in every respect; and if he causes us to be stewards over much,
he will teach us to use it to his honour:
if in his infinite and unsearchable wisdom he sees meet to grant but a little,
the little, with his blessing, will be sufficient and best.
For thy own sake therefore, dear friend,
for the sake of thy own true interest temporal and spiritual,
and for the sake of that most noble and glorious cause,
which blessed are they who (by their precept,
influence and example) contribute to help forward, every one in his rank and station,
even the cause of that religion which we profess, (Christianity in its purity,
undefiled with the mixture of worldly rites,
observations and ceremonies) be humble and steady, be much in retirement,
think nothing of thyself, think nothing of thy person,
nothing of thy parts either natural or improved; if thou be elevated with any of these,
or any other consideration, thou wilt never be truly honourable:
the eye of heaven will view thy lofty dwelling with disapprobation,
for what is the most pompous state of man with respect
to personal accomplishments and acquisitions,
in the view of him, who charges even his angels with folly,
and the very heavens are not pure in his sight?
Consider what manner of person it is whom the sacred scriptures
bear record that the favourable regard of omnipotence is toward,
"`But to this man will I look, even to him that is poor and of a contrite spirit,
and trembleth at my word.`"
But if thou walk in such humility and self-abasement as the true
light will show thee is altogether becoming thy state,
condition and existence, if thou diligently hearken to,
and faithfully obey the dictates of that holy principle of grace,
which is the criterion of our religious profession,
thou wilt be in the favour and under the protection of divine Providence,
and no necessary good thing, spiritual or temporal, will be wanting.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
LETTER 28.

[.signed-section-context-open]
8th month 1762.

That crafty enemy with whom we have to contend,
well knows how to turn the engines of our passions against our own souls,
to batter down the walls and bulwarks of our salvation;
he endeavours to draw out of the way the youth and middle aged,
by the allurements of deceitful pleasures,
or to encumber or retard them in it by the weight of worldly cares;
and if by the special favour and interposition of divine help,
they have escaped the baits laid for that season of life, and have arrived to old age;
neither there are they safe of themselves.
He attacks the old with their own natural infirmities of body and mind,
so nearly connected, that the one often affects the other,
if they have lived from youth to age in serving themselves only,
and in insensibility as to religion, his business is to rock them to sleep still,
till they sleep the sleep of death:
but if in the more active part of life they have been quickened with a sense of good,
and been enabled to do something for this blessed cause,
he would endeavour to turn their view to what they have done;
as though that was some merit and some honour to them,
and as though that was sufficient for them:
he would make use of the heaviness and inaction natural to that
stage of life to prevent them from that lively exercise of spirit,
in which both young and old must witness their minds to be cleansed and renewed,
not only for every day`'s particular service, which it brings along with it,
while we are in the body,
but which is absolutely necessary for the preservation of the life of our own souls.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
LETTER 29.

[.signed-section-context-open]
4th month 1752.

Oh, that I may come to be more and more weaned from the love of the world,
its friendships and its wisdom, and all the wit and devices of my restless enemy, self.
And this has been, and I hope will be, my desire for thee;
that thou may more and more be enamoured with the plainness and simplicity of the truth,
and by keeping low in the light,
mayest see and escape the subtlety of the serpent in all his seemingly glorious transformations,
in all his efforts to puff thee up, and all his splendid enticements to deceive.
Thou knowest far better than I where and how he is best seen and avoided,
and where thy great strength lies; but my unfeigned love for thee,
and not any distrust of thy stability, or information from any one,
prompts and emboldens me to take this freedom with thee.
It is my knowledge of thy good qualities,
which the great giver of all good has (for a purpose of his own glory) endowed thee with,
and not thy bad ones (for such are unknown to me) that makes me so much desire thy preservation,
and that those gifts and graces may be kept pure and chaste without any base alloy:
which I hope and believe they hitherto are.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
LETTER 30.

[.signed-section-context-open]
9th month 1752.

My beloved friend,
how sensible am I of the necessity of a total and absolute
resignation and subjection of our will to the divine will,
if we ever come to be truly profitable to ourselves,
or fit instruments in the Lord`'s hand for carrying on his work effectually in the earth.
I cannot but think that if our wills were thus yoked,
the work would not only go on more prosperously,
but be far easier to the instruments of it,
if our own wills were thoroughly mortified and self of no reputation.

When the opposers of truth raged and struck against the testimony of it,
they might indeed grieve that which bore witness for the truth in the instrument,
but could not gratify their malice in grieving the instrument itself,
because self in it being already quite abased and in the dust,
the arrow would fly ineffectually over its head.
According to my small judgment,
this habitual prostration of self would be an excellent preservative,
not only against being too much affected by the good will and applause,
but also against being so much troubled and afflicted
by the malice and bitterness of men.
It is a kind of balking the devil and his agents; for being already in the valley,
it is impossible for them to cast us from an eminence.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
LETTER 31.

[.signed-section-context-open]
3rd month 1753.

The sorrows and heaviness which the Lord brings over his people immediately,
for his own wise purposes, or which are permitted to befall them by adverse accidents,
or sometimes by means of the wicked, which, (as the psalmist says) are his sword;
these are, or may be, for the preparing of the heart for his service,
or for weaning from this transitory world and the love of it;
and the Lord is pleased often to sweeten such bitter cups;
the troubles which we bring on ourselves, through our own unwatchfulness,
I know by experience, lie with a dead weight upon us;
and from such I heartily pray that both I, and those whom I love, may be delivered.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
LETTER 32.

[.signed-section-context-open]
8th month 1756.

Thou art hear to us,
time nor distance have not obliterated the memory of those
seasons when we have been blended into one spirit by baptism,
and deep has spoken unto deep.
Such is the unity,
such the friendship and intercourse which is among
the children horn again of the spiritual birth,
which the world knows not of.
May this union still grow, my beloved, among us,
and prayer and supplication be more and more put up on one another`'s behalf;
that we may be enabled to do our day`'s work while here,
and hereafter join the assembly of those pure spirits which are ever employed
in celebrating the praise of the author of all our happiness.

My spirit bows within me in admiration of that glorious hand which
raises the human creature that is passive and obedient to his will,
to little less than the dignity of an angel, and crowns it with glory and honour;
anointing it with oil above its fellows,
who indeed have souls capable of the same refinement and exaltation,
but for want of giving up all,
and from being wedded to one little lower delight or another,
move in less exalted orbits.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
LETTER 33.

[.signed-section-context-open]
2nd month 1761.

Go on, my dear friend, in the diligent exercise of thy gift:
keep thy own hands and heart clean, and thou wilt certainly grow stronger and stronger.
Every new faithful discharge of duty will strengthen the root of life in thee,
and will be a means of laying up more treasure in heaven,
which thou wilt enjoy in fulness at last, when a few more battles are fought,
a few more bitter cups are drunk, a few more troubles from the wicked are over.
Have a care of the world, beware of its connections and its prospects;
it is of a sticking nature, it is hard to touch it,
without getting something of it upon us;
if we do not receive the mark (visibly) in our foreheads,
we may be in danger of having it secretly in our right hands,
and how then can we apply them to the work?
will not the savour of the defilement, (though it be but small) be perceived by the wise,
to be upon that which we have handled; how then will it prosper?

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
LETTER 34.

[.signed-section-context-open]
6th Mo 1761.

Thou art now a man of experience,
and shouldest endeavour for such a growth as the apostle witnessed, who once was a child,
but afterwards in all stations learned to be content.
I have thought more than usual of late of the withdrawing
of the glory from the assemblies of our society.
I am jealous that it lamentably increases.
What then must they do,
who are yet in infinite mercy and condescension measurably preserved alive?
what, but increase in the diligence and deepness of private retirement,
wearing sackcloth as within on their flesh?
I desire above all things a capacity for this inward steady waiting frame of spirit,
being well assured that it is the safest state for ourselves,
and most acceptable to the majesty of heaven.
May a sense and dread of his majesty (before whom
we have a great and important work to do,
important to ourselves and important by our example to others,) I say,
may his holy fear be ever so before our eyes, as to preserve us from sinning in thought,
word, or deed, against him.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
LETTER 35.

[.signed-section-context-open]
10th month 1763.

I would have thee (for many reasons) to be exemplarily generous in contributing
to this and all other public expenses relative to the good of the society.
Let us show that we have its welfare at heart, and that we are willing to act,
as well as speak for the cause:
there has been too great deficiency in this respect among some worthies;
it has hurt their service while they were living,
and whose is what they saved now they are dead?

Many individuals of our profession, who are rich in this world, are not so in good works,
nor active in helping a good work forward.
They have not only deviated from the Christian life and manners,
which we are called to hold forth to the view of the world:
but they seem sunk below the human and rational into the brutish nature;
their god is their belly,
and their glory is their shame; their ultimate view
and desire seems to be to accumulate wealth,
and gratify their sensual appetites; and if our society, as some other bodies corporate,
was mainly supported by money,
I believe sooner than be at any considerable expense in supporting it,
they would let the testimony of truth fall to the ground and sink into oblivion,
as they now trample upon and dishonour it by their lives and conversation.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
LETTER 36.

[.signed-section-context-open]
12th month 1763.

I note thy remarks, and acknowledge the justice of them; this wrath of man (of which,
pride, imperiousness,
self-will and caprice are branches) neither wills nor works the righteousness of God;
it does no good: it weakens the reason, lessens the authority,
and exposes the nakedness of all who are possessed by it, and act under its influence;
they are men of low degree,
and (in my opinion) if they will not submit to a proper subordination,
and quietly learn of wisdom and her children,
they had better be passed by as improper to be confederated with;
they will then indulge their own private spleen and rancour:
and they will need no other chastiser,
for the fool makes a rod sufficient for his own back.
Not only in the present case, but in most cases affecting the society,
we find the middling or lower class most willing to bear the burden,
to conform to discipline,
and come into method unitedly for carrying matters into execution;
the rich have money and many of them hardly any other qualification of value;
if some of them had given something considerable towards this work,
perhaps the opposition which they would therefore think they had a right
to make to some salutary schemes for establishing and promoting it,
would do more hurt than their money would do good.
It requires, dear friend, much of that wisdom which dwells with prudence,
to treat with these rich men;-- to petition them (as it were) to give
some of their substance towards the conservation of the society,
when we know their lives are opposite to the true interests of it,
and that they are unfit to communicate with us;-- to seem to want their money,
and to treat with them for that, when it is themselves we want,
and earnestly desire that they themselves may come
into and be cherished by the warm bosom of the church.
So that,
(only that we are all in general so little) I would choose that those who are least,
rather than ambassadors of the first rank from Christ Jesus to his people,
should be put upon the office of soliciting for money
from them for the contingent expenses of society.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
LETTER 37.

[.signed-section-context-open]
3rd month 1766.

I see more and more that I was not cut out to be a man for this world,
not one of the wise ones and the great ones of the earth;
nor since my thoughts took a religious turn, did I ever expect, or desire it.
I can honestly say,
that the greatest delight and satisfaction that I ever have in present possession,
is to feel the baptism of the spirit to wash my heart,
and unite it to the seed in the bitter sense of suffering;
and the most pleasing contemplation that I have in future prospect in this life,
is to see the prosperity of truth,
and to be favoured with liberty and capacity to serve the cause thereof in my generation.
And for the integrity of this declaration I dare appeal to the searcher of all hearts,
who hath even now tendered my spirit in humble prostration before him.
And I am glad to feel a renewal of this sacred baptism,
(which first cemented our early acquaintance,
and I trust will preserve our fellowship unbroken to the end,)
while I thus converse (without any premeditation) with thee.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
LETTER 38.

[.signed-section-context-open]
6th month 1771.

I seem not to have any repository of my own, from whence I might impart any good thing.
So far from it, I am so exceedingly reduced,
so complete a bankrupt in my spiritual circumstances, so poor,
so beset and embarrassed on all sides, that I never knew, heard,
or read of any one like me.
I am, or at least feel to myself, so weak at times,
that I seem as if I could hardly hold together.
Such is the person to whom thou unbosomest thy griefs.
Perhaps this short recital of my own state, compared with thy own feelings,
may administer some species of relief when thou finds that others are afflicted,
tossed with tempests, and not comforted, as well as thyself.
Thou rightly, and I doubt not experimentally, remarkest,
that effectual relief must come from the Father who seeth in secret.
He made us externally and visibly what we are,
and endued us with our several organs of existence and preservation.
It is he who (if we be passive under his hand, forming our minds,
as we were under the same hand fashioning our bodies,
of which we cannot make a single hair white or black,) will construct, unite,
confirm and strengthen in his own time the various parts of our inward man;
and will endue the same with those spiritual senses necessary for its preservation,
and for its ability to act properly in the service of its great Creator.
O my friend, wonderfully are we made.
My spirit, as is I doubt not thine and thy beloved consort`'s,
is often deeply bowed in humble petition,
that Divine Providence may so steer and pilot our
several barks through the dangerous seas of life,
that whatever wind from external circumstances blows, whether high or low,
prosperous or adverse, whether the waves be rough or smooth, whether storms or calms,
betide us, we may, enduring all with patience, waiting with quiet submission,
not without at times, a hope and expectation,
be conducted safe at last into the harbour of eternal rest.
Should everything in the voyage be quiet, easy, commodious and agreeable to our wishes,
we might perhaps grow presumptuous,
and by the interfering of our own carnal wills and wisdom
take our bark as it were out of the hands of the good pilot,
and run it against some rocks, where it might perish forever.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
LETTER 39.

[.signed-section-context-open]
4th month 1787.

Ye have heard no doubt of our dear friend having uncovered his head, his anointed head,
in the religious assemblies in Dublin.
My heart was glad when I heard it.
And the desire of my spirit is,
that many more may in all humility and prostration of self, wait in the deeps;
each keeping to their own peculiar exercise,
till they receive qualification and ability to bring up their stones of memorial,
living stones, polished and fitted in the depths from which they are brought.
I have seen many sweet and promising blossoms fair and fragrant,
from which delicious fruits might have been expected in due season; many hopeful youths,
of both sexes, whom the Lord has been graciously pleased to visit,
and to open an eye in them to see the beauty and excellence which is in the truth,
and to view this world as it really is;--but there has not been
a following on to know the Lord in progressive stages of advancement,
there has not been a sufficiently diligent waiting for the re-baptizing
which purges and makes clean from all defilement of flesh and spirit,
nor for the re-anointing, which keeps the internal eye open,
to see things natural and things spiritual in the proper light: so there is a dwindling,
a decaying, a dwarfishness in stature; a deficiency in measure and weight;
and the vacant seats of the princes and nobles, removing from works to rewards,
are not effectually filled up; so that defect and weakness have overspread,
the dignity of the church is lowered, and her authority,
which stands in the life and in the power of truth, is greatly diminished.
If ye are persuaded that these things are so, my dear+++_________+++,
do thou and some of thy near connections look about you, and see whereabouts you are;
let not the cares of this life supersede your concern in
those things which relate to a better that is to come.
While ye are commendably and moderately diligent in out ward business,
be diligent and fervent in spirit,
serving the Lord and his cause with your best in your generation.
Above all things feel after the dew of heaven;
and as much of the fatness of the earth as is suitable for you will be added.
Let the pure truth and its heavenly wisdom circumscribe
your desires and designs in all things;
you will find its government and direction most profitable,
both as to the life which now is, and that which is to come.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
LETTER 40.

[.signed-section-context-open]
4th month 1769.

It`'s parent`'s affliction for the loss of that dear
departed youth I doubt not has been very considerable:
these events are not without the ordering of an all-wise agent,
who has many a wheel within a wheel in his great economy.
Very likely in mercy he snatched away this youth,
now rescued from the temptations of a dangerous troublesome world:
he loosened one of these ties,
by which some of the survivors were connected perhaps
too closely to present visible enjoyments,
shewed the fallacy and uncertainty of human prospects, and I trust,
effected thereby on some of their minds a more solid thought of, and preparation for,
that awful period which hastens with uninterrupted speed upon us all.
If we be happily preserved to steer well through this state of probation,
we shall go to our beloved friends and acquaintance who are gone well before us,
but they cannot return to us.
This is a strong incitement to watchfulness and care,
and shews the vanity of a redundance of grief.

I did not hear before thy intelligence of the actress thou mentions.
Such tidings are very agreeable: but would be much more so,
if they brought account of an humble, diligent, steady perseverance in the party.
Many no doubt are visited by the power of that gospel
which is preached in every human creature;
and several are animated with good desires and resolutions to be obedient to it:
but when the tempter comes, practising on the inclinations, affections, and passions,
and plying his batteries against that side which is most easily beset,
for want of the creature waiting for the help of the all-sufficient grace,
but dallying with, and listening to the temptation,
instead of growing from strength to strength through faithfulness in the little,
the soul becomes weaker and weaker, loses its hold of the means of its salvation,
and is in danger of perishing forever.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
LETTER 41.

Thou and I, my dear friend,
are blessed with beloved consorts and true help-mates agreeable to our wish:
we have also a tender hopeful progeny.
May we be constantly waiting to feel our spirits seasoned with divine grace,
and keep near that holy life,
by which we may be enabled by example and precept
to answer the just witness in their consciences,
and help them forward in the right road: not only suffering,
but earnestly persuading the little children to come unto Christ,
whose arms are still extended to receive them.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
LETTER 42.

[.signed-section-context-open]
8th month 1775.

Submit we must: our lives, the lives of all we hold dear to us,
and every comfort we extract from everything,
are in the hand of omnipotence and under his control;
how awfully should we then walk before him who is
the source of every blessing to his depending children,
and who on the other hand (as a certain author most beautifully
remarks) can disquiet the soul and vex it in all its faculties.
I have been led very lately to ponder a good deal on the uncertainty of our tranquillity,
and the necessity of the interposition of that great power,
to preserve us alive in every respect.
Doubtless, whatever may be our trials, or from whatever quarter they may come,
if we watch steadily unto prayer, if we keep a conscience void of offence,
if we look to the Lord for succour, we shall be helped through one difficulty,
and one exercise after another, till our measure of suffering is filled up,
and our weary spirits are admitted into that holy rest prepared
for those who through faith have overcome in this dangerous warfare.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
LETTER 43.

[.signed-section-context-open]
1st month 1787.

At present,
there is cause for much gratitude on account of the
day of prosperity which we are favoured with.
By and by no doubt comes, in the revolution of the seasons, a day of adversity,
equally good and profitable for us.
May we all, my dear friend,
so improve the merciful visitations of heavenly regard and notice,
that whether the north or south wind blow upon our gardens,
the Lord`'s plantation in us may flourish and bring forth fruit,
to the praise of the good and gracious husbandman.
I am persuaded that his fatherly intention is to do good to your father`'s house,
and to make it useful and honourable to and among his people.
But many, very many, are the dangers and temptations from within and from without,
which await the necessary cares of this life:
and the pursuit of things lawful from the purest and noblest motives,
if carried to an improper excess, may clog the feet of the inward man,
and prevent his running with alacrity the race which, by divine appointment,
is set before him.
The seeking of great things, the aspiring after this world`'s grandeur,
the imitating and, emulating others who are not devoted in body, soul,
spirit and substance to the cause of truth, hurts the tender plant of renown,
and retards its growth.

But to be diligent in the spirit of our minds, often cultivating seasons of retirement,
watching daily and hourly unto prayer for preservation from evil and for divine acceptance,
witnessing from time to time that baptism which cleanses
from all defilement of flesh and spirit,
doing nothing which we are persuaded in the secret of our own minds is wrong,
and being faithful to every manifestation of active duty;
this I believe is the way to draw down the blessing of heaven,
and perpetuate it among us,

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
LETTER 44.

[.signed-section-context-open]
3rd month 1763.

Infirmities of various kinds are by the appointment
of Infinite Wisdom allotted to our nature,
and one disorder or other, with more or less speed,
will work the decay of the mortal part of us all:
some disorders hurry us with pain and anguish out of life,
as it were with open force and violence,
while others gradually undermine the constitution;
and the absence of much pain causing a flattering hope of longer continuance,
the frail tabernacle is dissolved before we are well aware.
In this, in that, in every circumstance of life or death, there is one, and but one,
sure hope to anchor our tossed tried vessel; to wit,
the earnest of eternal rest and peace.
This has made the deathbed, even when agonizing pain of body has attended,
as a bed of roses,
and the pale messenger has been welcomed as one come
to release the soul from the fetters of mortality,
that it may take its flight into the regions of pure joy,
and unmixed undisturbed felicity.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
LETTER 45.

[.signed-section-context-open]
7th month 1763.

I read thy last, and attended to the contents with a mind impressed with sorrow,
and indeed sorrow and trouble are at times spread before me on
account of the situation of things in our religious society.
What is the reason that many educated amongst us should
be such enemies to the truth which they profess?
yea, the enmity of their spirits (like thick darkness) is to be felt:
What must be opposed to these fiery darts?
for my part,
I know nothing more likely for the honest-hearted to defend
themselves withal and preserve their own spirits,
nor by which they may overcome the agents of the wicked one,
than the power of gospel love.
This, if patiently kept to, will work wonders: this is invincible,
and its armour impenetrable.
But if this be in any measure departed, from,
or adulterated with self-love (which is the parent of resentment)
it causes a breach in the panoply (the whole armour) of God,
who is love, and so leaves some weak part unguarded, to be wounded and hurt.
If any therefore have been injured or hurt,
to a deep search after the healing virtue of this divine love,
I would earnestly recommend them; and as this becomes predominant in the mind,
it will influence to say and do these things, and these only, which make for peace;
and it will bear down all before it, and in due time re-possess the gates of its enemies.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
LETTER 46.

[.signed-section-context-open]
11th month 1766.

I can conceive by past sorrowful experience the trouble your family must be in,
on the distressing occasion which thou mentions;
and more especially such of you as are connected with the testimony of truth,
which is wounded by this affair; but such have always this encouragement,
that those who suffer for, and with, the testimony, are supported inwardly by it,
and in so much greater degree as they are tender of it,
and prefer it before the ties of blood, of natural affection or any other consideration.
It looks to me as if this dispensation would be fruitful of refining baptism to you,
and I heartily wish that you may patiently abide the day (or say the night) of it,
and I believe you will find all work together for good.
But beware of sinking too low in your minds,
keep as attentive as possible to feel after solid comfort,
and to hear the dictates of the small still voice, in following which there is safety.
Methinks the enemy will not be idle at this juncture,
but be apt to whisper that things having gone amiss in your own family,
ye are much disqualified from intermeddling in the families of others,
and that ye are not now proper persons to stand forth
in the cause of our discipline in the church.
This is the whispering of Satan; he is a liar, and believe him not.
Our children and every individual in our families have the
same divine principle and sufficient grace as ourselves,
and in our obedience to it consists our common preservation.
If we be careful to live under its law, and thereby be good examples to them:
if seasoned by this, when fresh capacity is afforded,
we bring forth now and then such meat for our household as we have,
though only fragments;
if we watch unto prayer for the blessing and protection of Providence over them and us,
what more is required, or what more can be done?
When, after all, those that are intimately connected with us by friendship,
or relationship, swerving from the fear of God, and regard to the admonition of man,
violate the law of a good conscience, and the rules established in the society,
let us impartially give our judgment with zeal against them,
and know no man after the flesh.
This is what will conduce to our own peace and strength,
disappoint the expectation of those who may watch over us for evil,
and may be a means of awakening the party that has
offended to ponder more deeply on the offence,
and seek more earnestly a place of repentance and restoration.
Though I write thus, I have no suspicion of any contrary conduct in you,
but believe you will act as those who are sensible that many eyes are over you,
and particularly that eye which penetrates into the deepest recesses of our hearts,
and knows the most secret movements of our thoughts; the eye of a God,
jealous indeed of his honour,
yet full of compassion and merciful regard to his
poor afflicted devoted children and servants,
who faithfully serve and submissively rely upon him.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
LETTER 47.

[.signed-section-context-open]
12th month 1766.

I think I have seen that thy heavenly Father and Merciful Creator,
hath been graciously pleased to visit thee in thy dangerous stage of youth,
and that his intention, if thou dost not frustrate it, is to do thee good.
Suffer then, my dear friend, with humble resignation, the operation of his purging power.
Leave thyself in his hand, and cast thy care upon him.
Be diligent above all things to feel after the stirrings of a divine life in thy soul,
and wait patiently for its tendering, cleansing baptisms.
Oh, this diligent waiting and inward retiredness of spirit! this thou wilt find is the very
source and supply of thy ability and capacity to hold out in a religious growth.
This is what I most earnestly recommend to thee as
the great and principal means of renewing thy strength.
If thou rightly learnest this lesson of retirement,
thou wilt soon be a ripe scholar in religion, and need not that any man teach thee,
but as the holy anointing will teach thee in these seasons of waiting,
and imbue thy mind with an understanding of those things which belong to thy only true,
present, and future everlasting peace.
I am greatly mistaken if the good will of heaven is not towards thee in particular,
and I hope to more of thy father`'s house.
My sincere desire is that ye may be so wise in heart, so true to your own best interest,
as not to reject the offers of such gracious favour and condescension,
but thankfully embrace them as your chiefest good.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
LETTER 48.

[.signed-section-context-open]
2nd month 1767.

Dear cousins, ye are now joined together, I hope, by the ordering hand of Providence;
and are advanced a step higher into a more conspicuous station in life and business.
The author of every good and perfect gift has given
to both of you a good share of natural capacity,
and improved understanding; and the means, through frugality and industry,
with his blessing, of procuring a comfortable subsistence.
He has placed you in a great and populous city,
where you profess his holy and saving truth among
a large number of others of the same profession,
who do not honour it as they ought in their lives and conversations.
Now, my dear cousins, my mind is engaged for your temporal and eternal prosperity,
and I see the path and the only one that leads infallibly to it; which is,
by diligently and faithfully seeking to the Almighty benefactor
for his preservation and blessing to be over and about you,
and all that is under your hand.
Strive not to be, nor to appear great,
nor stretch your wings beyond the circumference of the nest which,
in the ordering of all-wise Providence, is allotted for you.
Rather live under, and appear under your ability than over.
You will experience safety and quietness in it.
The contrary is a temptation and a snare, and an inlet to dangers of various kinds;
and often with new beginners lays the foundation of difficulties, straitness,
and embarrassments, which they are never disencumbered of,
until they are disencumbered of mortality; nor does the perplexity always end here;
their poor bodies indeed rest in the earth,
but the distresses of the parents are entailed upon the children;
and instead of aggrandizement of family, there is debasement;
instead of pomp there is penury; and indigence instead of affluence.
Let us take a little view (my dear friend) of the persons and families
which have been up and down during our short time of observation,
let us contemplate them, not with an evil nor pitiless eye,
but with an eye to the ways of that all-ruling power which resisteth the proud,
but giveth his grace additionally to the humble.
Let us centre down,
and have our dwelling low in a conscious sense of our own
unworthiness and insufficiency to direct our own steps,
or to prosper either as to the things of this or a better life,
without his blessed assistance and protection.
Be truly humble, (my dear ) be frequent, and (as much as possible) constant,
in feeling after a capacity to breathe in secret after an
acquaintance and communion with the author of all goodness.
Be exemplary in your own conduct, conversation, and exterior appearance and deportment,
as becomes the disciples and professors of the religion
established by him who was meek and low in heart,
and whose garment was without seam.
So will ye, in proportion to the purity of your intentions,
and the cleanness of your hands in his sight,
gain the favour and approbation of him who knows the heart,
and hath all power in his hand to bless, or to blast, at his pleasure.
I am unusually concerned and desirous that thy conduct may be such,
now in the setting off in life, as that the good will of heaven may be to and upon it;
and if thou happily obtain this, it must certainly be by being a pattern of humility,
steadiness and plainness, among thy numerous acquaintance in that city.
This may occasion some trials,
in which it will often be proved whether thy attachment to the testimony of truth,
or to the spirit of the world, is more prevalent.
According to the freewill choice which thou wilt be enabled to make,
will thy ability to proceed aright be strengthened or weakened,
and finally the one side or the other get the victory.
The day of small things and of little requirings of duty,
proportioned to the state of the children, is by no means to be despised.
The cross to our own depraved wills is often to be borne, and many old friendships,
connections, habits and propensities, of an hurtful or unprofitable nature,
will be dissolved or decay: in the room of which new desires and affections,
new intimacies and society will gradually be formed.
But in all that he throws down, as well as in all he builds up,
the Lord Almighty (as we rely upon him, and are faithful to his discoveries),
will be found to do everything right, and for our good every manner of way.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
LETTER 49.

[.signed-section-context-open]
2nd month 1769.

I have thought of thee with concern,
knowing by experience the dangers that unexperienced youth is liable to.
The reins have been much left on thy own neck, to run on according to thy own pleasure.
Thou hast girded thyself according to thy own liking, and gone whither thou wouldest.
And it is of the mercy of thy great Creator,
if thou hast been preserved hitherto from falling into the enormities and corruptions,
as I doubt thou hast stepped too much into the vanities
and follies of the world and its spirit.
However, the past is irrecoverable; I would have thee make a stand now,
and in the cool hour of sober reflection ask thyself,
whether thou hast felt more solid satisfaction in the time of dissipation and libertinism,
which has since elapsed, than in those seasons of the earlier part of thy youth,
when thy heart was humbled within thee under a sense of thy own unworthiness,
and thy spirit tendered by the visits of divine grace:
visits which were afforded thee by that same great Creator, in wonderful condescension,
that thy mind might be pre-engaged to love, fear and serve him,
before the heated imagination and growing passions of more advanced youth,
and thy designs and connections on the verge of manhood,
might warp thy conduct from the simplicity and safety which is in the blessed truth.
Thou knowest best whether thou still enjoyest those tendering sensations of divine favour,
or whether thou hast bartered this precious birth-right for foolish, fleeting,
empty gratifications, which will stand thee in no stead in the day of trouble;
which tend only to estrange and set thee at a distance from thy Almightly Benefactor,
who can bless or blast all thy endeavours;
and which preclude thee from that frequency of intercourse with thy best friends,
by whose communion, and good counsel, thou mightest be profited and helped every way.

[.signed-section-signature]
Richard Shackleton.
