== Letters 71 &#8212; 85

[.letter-heading]
Letter 71.

[.signed-section-context-open]
9th month 4th, 1791.

Remembering that I was in thy epistolary debt,
believe I should have written to thee of my being favoured to get well home,
etc. but having been longer in debt to thy sister
+++_______+++ I thought best to pay off that score,
and hope she communicated any intelligence that was worth imparting to thee.
I hope also, that the event of a personal interview is no interruption,
but rather a cement of our correspondence.
I have just been re-perusing thy last kind letter, with renewed satisfaction,
and wish to be preserved in such a humble state as
to keep the unity and much valued amity of such friends:
indeed much depends on being preserved in this state,
so characteristic of the great Master.
A departure from it has proved the ruin of thousands;
and by how much more useful and conspicuous any become in the church,
so much more conspicuous should this spirit appear in them.

This spirit, if kept to, will work wonders; it is the well watered,
well dug and well cultivated soil, in which the Christian virtues grow and nourish.
Alas! for many in our poor society, they have chosen the barren mountains,
a dry and parched soil; their roots have struck into a hard stiff clay,
and they bear neither leaves nor fruit.
But the great Husbandman is not unmindful of his plantation,
he is sending skilful labourers into it; and not only so,
but by his own immediate power he has reached divers, arrested them in their retrograde,
wayward course, and brought them into the way everlasting.
So that,
(according to my sense) there is encouragement for
the faithful devoted servants to persevere;
doing each his own business, and that part of the general labour which is assigned him.
Some individuals may be sent on particular expeditions and services;
but the discipline of the church is a general field of labour,
in which no living member is exempt from a share.

For my part, ever since I became, in some measure, acquainted with the Truth,
and mercifully arrived at some settlement in it, my relative duties in religious society,
and the share in the support of discipline, which I apprehended fell to my lot,
have been among the capital weights and burdens, and exercises, and distresses,
of my life.
As our inward frames differ one from another,
so these things are harder to some dispositions than others.
They have been particularly so to me; so that I could say with Job,
"`The things that my soul refused to touch are as my sorrowful meat.`"
But I have lived to see a termination of many of these conflicts;
I have lived to see captivity led captive; rebellious children become loyal subjects;
and the opposers of truth triumphantly bearing its standard in the sight of its enemies,
their former associates.
Many unfaithful professors also, whom neither gentle expostulations could win,
nor repeated warnings intimidate,
have been summoned before another tribunal to receive
their final sentence and everlasting retribution,
according as their works have been.
O that such as now trouble the church may awake in time,
to a proper sense of their state, ere it be too late, while the day of visitation lasts,
and a place of repentance is yet to be found; for, by reason of frequent resistance,
there may be a cessation of the strivings of grace, and the poor creature,
left to itself in the hour of bitter distress, may seek and ask in vain.

I had the favour of a letter, some time ago, from our mutual dear friend;
he was expecting to sail shortly in the Pigou.
His letter was fraught with a precious cargo of love,
which he commissioned me in a particular manner to distribute;
it would be a valuable commission, if capacity to fulfill it were also added;
like a large cargo of guineas sent from the king`'s mint for circulation,
which enriches the person to whom it is delegated with "`Dust of Gold.`"

Perhaps thou wilt let me know if there be any thing new
respecting our friends on the neighbouring continent,
or any other matters relative to the prosperity of the most interesting cause existing,
or which ever existed, or ever will exist upon earth.

My dear friends at +++_______+++,
I know kindly interest themselves in the welfare of me and mine.
Be so kind as to inform them,
that we are generally favoured with health and tranquillity here.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
Letter 72.

[.signed-section-context-open]
8th month 3rd, 1792.

I doubt not but that our beloved sister acknowledged
for me the receipt of thy acceptable letter;
it conveyed the sorrowful intelligence of the removal of our mutual dear friend+++_________+++,
and this goes charged with an account of the translation
of another precious servant from works to rewards.
Our well-esteemed friend and brother Samuel Neale,
had of late years been rather on the decline,
and these last three or four months grew much worse;
was seized with a mortification in his foot,
and notwithstanding all the medical skill and labour bestowed,
departed this life 27th ult.
His head had been much affected and his thoughts confused
by the opiates which it was judged proper to give him;
but at intervals of recollection and clear understanding,
he put forth the evident sweet and savoury fruits of a sound mind;
of a mind supported by divine effectual help,
which enabled and authorised him feelingly to express triumph over death,
hell and the grave.

His travels in all parts of the world where our religious society was settled,
at one time or other of his life, caused him to be very generally known,
and the sweetness, liveliness, and tenderness which accompanied his gospel labours,
made him very generally beloved; so that it may be said of this Samuel also, "`He died,
and all Israel lamented him.`"
My youngest child, Sarah, had for a long time been attached to him;
with our free consent she was much gratified by an assiduous
attendance on her honoured friend for several weeks past,
and was present with him, to her comfort, at the final close.
Thus "`The righteous perisheth;`" but I hope it cannot
be said that "`No man layeth it to heart.`"
I trust these dispensations to the church, ordered in infinite wisdom,
are laid to heart by many of our youth especially;
and that there will be a succession of fishers, and fowlers, and hunters,
who will diligently seek after, and preserve alive,
the precious prey of the souls of men.

I observe that when thou favoured me with thy last, thou wast on the eve of a journey:
I hope it proved prosperous, that peace was the effect and the reward.
I am glad when I hear of thy excursions in the service of truth:
such exercise strengthens the spiritual constitution,
and the example of those whom Providence has been pleased
not only to endow but to bless with even this world`'s affluence,
hath a powerful influence.
Of how much greater weight and use must it be,
when spiritual gifts are added to temporal loans?
Bear with me, dear friend,
and do not refuse the word of approbation and encouragement
when it comes rightly to thee,
or at least from a well meaning spring: trouble and discouragement are plentiful enough.

You rich men are really to be pitied, and demand the cordial sympathy of your friends.
I am thankful that there are a few of you who bid fair for escaping the woe,
and entering the kingdom,
though it may be through great tribulations and afflictions of divers kinds.
`'Tis but holding out a little longer,
and the scene of probation and conflict will be over with us all;
then our spirits shall center in the mansions prepared for them.
But our example may operate long after our existence here; as is said,
"`He being dead yet speaketh.`"
May the cause therefore of Truth, and its precious testimonies,
ever be dearer and nearer to us than any other consideration; and let us,
like faithful Abraham, (the friend of God) in our heart and will,
sacrifice every natural feeling and affection to that allegiance which
we owe to the supreme command and good pleasure of our great Creator,
manifested to us by the spirit of his Son;
this appears to be the most likely means to draw
down the favour and friendship of heaven upon us,
and to preserve in us a better and happier state; in that in which we have,
under a sense of duty, offered in our hearts a sacrifice to the Lord.

Thy sister favoured my daughter with a letter not long,
advising of her and being outward bound; I heartily wish them good speed;
they are taking the high road to heaven; thus diligently exercising their gifts,
and having it as their meat and drink to do the will of him who sent them.
My best love follows them wherever they go,
and I wish myself and family to be remembered by them for good.

I hope our mutual friend is well; her retreat from was, no doubt, melancholy,
and she has intimately felt the loss of her precious friend and companion; but I trust,
the cup of mourning has been sweetened to her taste
by the union and fellowship which death cannot divide.
I am obliged by thy information respecting friends returned to America, etc.
I shall always be obliged by any new material intelligence concerning the affairs of truth,
on that, or this neighbouring continent.
Remember me affectionately to my dear friends.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
Letter 73.

I feel unity with the meeting`'s renewed labour with +++_______+++. O
what an element is divine love! in this the children of the light,
live, and breathe, and move, and act; there is no infection here, it is clear, pure,
and salutary.
I should be glad that the poor man might be effectually conquered;
thou art dear to me for having so followed, and been so guided in service,
as to be instrumental of good in his case.
Thy prayers and thy alms-deeds, that is, thy secret wrestlings of spirit,
and thy private labours and communications will, no doubt, come up in memorial.

I expect thou knowest that I received thine of the 5th ult.
the contents are such as this state of existence often affords:
we have indeed a cup of mixture to partake of:
but then it is wisely mixed and tempered by the great hand; it is not for us poor, blind,
and ignorant creatures to say, What doest thou?
but patiently to submit and bow in humble submission,
and in a persuasion that the Judge of all the earth doeth right.
It is glad tidings to me that ye are getting on so well, and no doubt,
cause of humiliation and gratitude to you both that the arm of everlasting
strength has been experienced in such renewed and effectual support:
there is great encouragement in this to proceed in the track of revealed duty.
Many have hurt themselves, and become lame and dwarfish all their lives long,
by letting in the reasoner and discourager: consulting human prudence and propriety;
limiting the spirit, which is the Holy One; starting aside from services,
like an affrighted horse on the road; and being in great fear where no fear is.
But thou, beloved friend,
seemest to have got out of the narrow ways and crooked
paths on to the high road for travellers,
leading to the city of the Great King; and by continuing diligent, faithful, and devoted,
thou wilt know more and more distinctly the Master`'s will,
and be strengthened to perform it.
Thus, if it be consistent with infinite wisdom to prolong thy life here,
thou wilt be happy in thyself and useful in the creation of God;
and if a short warning should summon thee from this conflicting state, thou art prepared,
thou hast nothing to do but to die; this mortal to put on immortality;
thy sorrows here to be changed into unmixed everlasting joy;
and thy example and memorial will live and preach to succeeding generations.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
Letter 74.

Alas I am a poor weak creature, much more fit to be ministered to,
than qualified to minister to another:
yet I was quite willing to do what I was made able to do, that is, to pray for thee.
I am glad that thou art on service; it`'s the way for thee to grow strong,
and to get above the little glooms and recurring perplexities which, from various causes,
cast down and disquiet the soul.
By being thus employed and accustomed to exercise, thou wilt become a trained servant,
and be made capable to instruct others, thy fellow servants,
in the duties of their places and stations;
feeding not only the lambs but the sheep of Christ.

Go on then, my dear friend; be not afraid of the face of man,
nor ashamed of the cross of Christ.
I repeat, as I have often said, that nothing more glorious, more dignifying,
more beneficial to mankind,
or more worthy of the dedication of all our faculties to espouse and promote,
was ever let down from heaven to earth.
Not only true civilization of manners and sound morality,
but life and immortality (that is immortal life) and eternal salvation,
are made manifest through the gospel.
A dispensation of which, I doubt not, is committed to thee, in order to advance,
according to thy gift and measure, these glorious ends.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
Letter 75.

I doubt not thou esteemest it a favour from on high to be engaged, in the least degree,
in the Lord`'s service.
Mayest thou always keep here; low, humble,
thankful for any scraps which may fall from the altar, about which thou ministers.
Oh, this humility!
When shall I cease from inculcating the necessity of it
to those I love!--or from praying to be preserved in it myself;
I am sensible, that though I should preach to others, without keeping on this bottom,
I may become a castaway from divine favour.

I note thy general silence in public assemblies; I trust thou art, in a good degree,
a living witness of the sufferings of Christ, who was oppressed, afflicted,
yet opened not his mouth!
To lose our own wills in the will of the Great Master, is the top stone of the building;
then servants are in a state fit to receive orders,
then the master is pleased to instruct them,
and they are ready and willing to go on his errands;
they take the message clearly and deliver it clearly;
it carries conviction along with it, and the work is blessed in their hands.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
Letter 76.

Notwithstanding the reports of the vessel being wrecked,
which conveyed our dear friends and +++_________+++ I
was for entertaining a hope that they were false,
or that our said friends might be the objects of divine preservation;
but further concurring relations have caused that hope to perish.
Yet a well-grounded hope remains, that,
that part in them which is out of the power of the elements of nature, has been,
and forever will be,
the object of divine preservation and everlasting salvation! `'Tis true,
the manner and circumstances of their dissolution, appears dreadful to us! but perhaps,
on the whole,
not attended with greater pain to them than if they had died in the arms of their friends.
Death is generally accompanied with something terrifying to human nature:
a lingering death is also replete with much pain of body;
this our friends were exempt from, though it is very probable,
for some hours they felt the horrors of their dreadful situation.
They have shot the gulf the last pinching agony is over with them!
Now their near relations and the surviving friends are the
subjects of our deep sympathy and tender compassion:
may the Lord comfort and sustain them,
and afford an adequate supply from his inexhaustible treasury!
He has a remedy competent to every evil,
and no depth of distress is out of the reach of his merciful relief.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
Letter 77.

[.signed-section-context-open]
17th of 10th month 1780.

The near affection, esteem and respect, which I bore to thy late father-in-law,
does not permit me to seem inattentive to his family,
nor to be deficient in such visible token of friendship as is in my power to give.
I therefore take this opportunity of expressing my
joint concern with yours for our common loss;
a loss severely felt throughout the borders of our religious society in these nations,
where the report has yet spread, and is attended with peculiar regret.
For as love begets love, that spirit of charity, benevolence,
and brotherly kindness which so conspicuously influenced
the disposition of this good man,
did not fail to produce reciprocal affection towards him in others.
We lament the steady, upright friend; the pleasing, instructive companion;
the lively experienced minister; the diligent, faithful labourer,
removed from amongst us.
His family,
who more particularly partook of the pleasure and profit
arising from such good qualities and qualifications,
must doubtless, deeply feel the privation:
but this sorrow will (I trust) be so tempered with resignation to the divine will,
and so mingled with a comfortable hope of the happy end of the dear deceased,
that there will ensue a quiet composure of mind, and sweet unity with his spirit,
safely centered in its holy rest.--What remains for us is,
so to pass the short uncertain time of our sojourning here, as that we,
at the close of all, may join the spirits of the blessed,
never more to be separated from them.
Human nature recoils with horror at the idea of everlasting
exclusion from heaven and happiness,
in the regions of woe and misery.
And yet, if we would on any reasonable grounds expect to die the death of the righteous,
and that our latter end should be like unto his,
we must use all diligent endeavours to live the life of the righteous,
that we may obtain at last the glorious prize,
and not most unhappily miss so great salvation.
Religious parents, devoted as thy dear father-in-law was to the service of truth,
and indefatigable in his labours for the good of others,
not only purchase a blessed inheritance for themselves, but often for their successors:
their pains, their prayers, their secret offerings, rise in sweet memorial,
and their children and families inherit the benefit thereof; such,
I hope and believe will (through infinite mercy) be the happy experience
of most of the nearest relations of my dear friend;
and some of the branches of this valuable stock, abiding the purging seasons,
and submitting to the forming and turning of the divine hand,
will bear fruit grateful to God and man.
With these my spirit hath unity;
and I earnestly desire their preservation and perseverance in that holy path,
into which the feet of their minds have been turned;
that they in their day may be useful and honourable
living members of the church of Christ,
and that there may be a succession of testimony-bearers to that truth which was first,
and will stand last upon earth.
But should any of the visited children of a visited family,
the offspring of religious parents, who have watched over them with tender attention,
and often admonished them for their good;
should any of these turn from the grace of God into wantonness,
trample upon his witness in their consciences,
reject the calls and invitations of his spirit,
and set at nought their birthright and education, surely dangerous is their situation;
they are running giddily (as it were,) on the edge of a dreadful precipice,
and dallying with their destruction.
With all my heart I wish that the youth amongst us were
properly sensible of the magnitude of the danger of slighting,
and neglecting to cultivate, the merciful visitations of heaven.
That which in mercy was extended as a shepherd`'s crook to draw them,
and help them along, will, if despised and let go, prove as an iron rod;
the same sun which in the visible creation, cheers and invigorates the living,
accelerates the putrefaction of the dead.
"`As they did not like (says the apostle) to retain God in their
knowledge,`" (which implies that they had once known him,
and been visited by him) "`God gave them over to a reprobate mind,
to do those things which are not convenient;`" and then
follows a catalogue disgraceful not only to Christianity,
but to humanity itself.
O! may those children of my honoured friend,
who from their local situation are more exposed to
evil than those hopeful plants of the same house,
who have partaken more of parental care and nurture; may those,
though they may have wandered as into a far country,
and fed on polluted and unsubstantial food,
be favoured with a fresh visitation and recollection where they are,
and whence they have strayed; be minded to return to their heavenly Father`'s house,
and experience the arms of mercy stretched forth in great condescension to receive them,
ere it be too late, and the door be finally shut.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
Letter 78.

[.signed-section-context-open]
19th of 2nd month 1771.

I confess it looks hardly decent in me to make no return of this
sort to two obliging letters which I have had from thee.
Thou enquirest concerning my father`'s health;
he has had several attacks of (what is called) a bilious cholic;
we were much concerned about him,
but (through favour of good Providence) he has recruited finely; however,
his hardly suffering himself to be taken proper care of,
subjects him to the danger of a return of his disorder,
and us to frequent fears respecting him;
manifold indeed is the loss we shall sustain by the translation of my venerable father;
but the loss of his weighty spirit, exemplary life,
and lively services in our poor destitute society, would be most of all to be lamented.
A cause, dear friend, worthy the attachment of the most dignified natures;
a mystery so glorious, that even angels have desired to pry into it.
Christianity in its purity,
undefiled with the mixture of worldly wisdom and superstitious ceremonies,
hath been revealed from heaven to our ancestors.
They nobly stood by it, and faithfully kept that which was committed to their trust:
they have rested from their labours here,
and are now in the full possession of the fruits of these labours, even life eternal.
There still remains the same cause to be supported in our generation;
the same conflict to be maintained with the grand adversary of our happiness,
and the corruptions of our fallen nature; the same and only effectual means of victory;
and the same immortal crown at the end for him that overcometh.
But where are now the combatants?
The multitude professing to walk in the way of truth, are not in the way;
they are not spiritually minded; they mind their own things, not the things of God;
hence a general indifference, as to the life and virtue of religion,
has overspread us as a leprosy;
our minds are not in a state prepared for that intercourse with the divine spirit,
in which consists the happiness both of men and angels.
Those gifts and graces which the Father of Lights and Spirits
would pour out upon the living members of his church,
are withheld, and the shame of our nakedness is visible, even to them that are without.
Think of this, beloved friend, and let sorrow seize thy heart,
because these things are so.
Open thy heart to the convictions and judgments which are the preparatory
dispensation to the reception of pure and unmixed good.
"`Open thy doors, O Lebanon, and let the fire consume thy cedars!`"
If I am not mistaken, thou art not altogether unacquainted with this work.
Thou hast felt something of the corroding smart of judgment for evil;
thou hast felt the gentle drawings and invitations of the spirit,
alluring thee out of the friendship and familiarity of the world,
and offering thee a "`place and a name in the Lord`'s house and within his walls,
better than of sons and of daughters.`"
Thou hast seen and felt the instability and uncertainty
of the nearest and dearest temporal enjoyments;
and the great vacuum, the inanity,
the insufficiency of worldly gratifications to satisfy
the aspirations and longings of an immortal soul,
have at times been opened to thy understanding and view.
Mayest thou, dear friend, ponder deeply where thou art; and whether thou hast,
in a noble, unreserved dedication of all, obeyed the heavenly vision.
Whether we seek great things for ourselves or not, our time passes quickly over,
our places here will soon know us no more,
and the Lord is determined to bring this evil (of death) upon all flesh,
and that wonderful fabric of our bodies, which he hath made, will he break down.
Happy will it then be for those, who,
their lives being spent here in humble circumspect walking,
and the service of the best of masters, will have it said to them individually,
"`Well done, good and faithful servant, enter thou into the joy of thy Lord.`"

Excuse this freedom which I have taken on this solemn subject;
a consciousness of my hearty desires for thy welfare, emboldens me to use it.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
Letter 79.

By a letter I have just now received from thy nephew, I am informed of thy great loss.
Want of earlier information renders it difficult for me to attend the solemnity,
which is to be on that occasion tomorrow, were there not other impediments in my way.
As I could not conveniently pay that mark of friendship,
I therefore thought of sending thee a few lines,
expressive of my condolence and sympathy.

The pleasing disposition and engaging manners of the dear deceased,
endeared her (no doubt) to many others, as well as to my wife and me;
but a secret something united us to her in a close, and intimate, and feeling relation.

We loved her as a near and dear friend.
She is now released from those long infirmities,
which infinite wisdom permitted her to pass through,
for the trial of her faith and patience,
and for her preparation for an admittance into that
holy rest which nothing impure can enter.
Refined and polished while here for the company of blessed spirits,
she is (I doubt not) mingled in their happy society.
We remain a little longer to struggle with the difficulties
and encounter the temptations which belong to this life.
We are not yet putting off our harness, therefore have no reason to boast,
but to dwell in awful fear.
We are, some of us, the heads of families, principal persons in our places;
our precepts and our example therefore must have considerable weight and influence.
How necessary is it for us then to ask wisdom of him,
who giveth liberally and upbraideth not! that by rightly fulfilling
all our several duties in our families and in the church,
we may, as we pass along in our journey, from time to time,
have the answer in our consciences, of "`well done good and faithful servant,
enter thou into the joy of thy Lord,`" as well as that happy
sentence at the close of this visible scene.

My mind, while I am thus engaged,
is turned with tender solicitude towards thy beloved offspring;
I believe that many of them (and most probably all of them)
have felt the gentle touches of the divine hand,
and the invitations of the good Spirit, in the secret of their souls;
drawing them from the spirit of the world, in its manifold appearances and shapes,
and begetting in them desires and aspirations after enduring substance.
May they with all diligence cultivate the renewal of these tendering impressions,
and in all humility submit to the operation of these cleansing baptisms,
which purify the heart, and make it a fit receptacle for unmixed good.
A gracious Providence has not been wanting in his
precious visitations to the youth amongst us;
but there has been a great want in them,
of following on to know the Lord in the renewed experience of his humbling power,
and in the further manifestations of his will concerning them.
Hence the goodness of too many of them is but like the morning cloud and early dew;
it is soon superseded by a relish for the pomps and vanities of this world,
and their baptismal vows are soon forgotten;
and hence a want of succession of testimony-bearers to the noblest cause, which ever did,
or ever will, dignify human nature.
I particularly wish for the elder branches of thy numerous, hopeful stock,
that as now a greater charge devolves upon them,
they may seek and wait for heavenly wisdom to direct their own steps,
and influence every part of their conduct;
that so they may grow in favour with their great Creator,
and in his hand be made a blessing to the younger branches of the family,
assisting to train them up, by example and precept, in the life of religion,
and in that plainness and simplicity which adorn our holy profession.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
Letter 80.

Our meetings of discipline were held this week at Carlow.
There seemed to appear some good fruits of the manifold labours taken lately;
and also sorrowful cause of apprehension, lest, in some, the good seed then sown,
may have, in great measure, been picked out again.
However, these things must be left; those who are sent to plant and water,
faithfully doing their duty, are clear;
the consequential increase is of the Lord of the harvest.
Indeed, in this instrumental labour, there is great need of skill, and we are poor,
blind, fallible creatures.
What must we do then that feel ourselves called to labour in our various departments?
Ask counsel of God, be diligent in his business, and fervent in our spirits;
earnestly desiring that he may keep our feet when we officiate in his house,
lest following (through ignorance and mistake,
not willing intention) the leadings of the imagination, and that which is natural,
we gradually and insensibly lose sight of the spiritual guide, and the grand enemy,
ever restless and on the watch, even among the assemblies of the sons of God,
working in the mystery,
prevail to substitute some mixture of the creature in the place of the true light.
In such case, when the mind of the minister, in the exercise of his gift,
is imprest with some little fear or jealousy,
lest the right guide is disappearing and the imagination, the natural part,
is taking its place, I believe it is best to pause, to recollect,
to endeavour to let the flutter and commotion subside, to be still,
and wait to know what is of God; and accordingly,
as the Holy Evidence speaks peace or otherwise, in this silence of all flesh, proceed,
or desist, always bearing in mind, that too little said, may often be supplied;
but too much can hardly be remedied,

I doubt not, my dear friend,
that thou hast long anticipated me in reflections and observations of this sort,
though I thus indulge an unpremeditated freedom of dropping what unexpectedly occurs.
I shall be sorry to give thee pain or uneasiness, which is far from my intention,
for I have, according to my small measure of feeling, true unity with thee,
and cordial brotherly affection with thee; but,
as we are beset on every side with danger, a hint or caution,
as from one child to another, may at times do no harm;
and I think I know so well thy honest, humble heart,
that thou wilt take this in good part, though from a brother of a lower degree;
for though the whetstone itself cannot cut yet it
is of use to sharpen the iron which can cut.

I suppose thou hast heard long before,
or I would be cautious of being the messenger to thee,
of the decease of our dearly beloved friend and elder brother in the truth, Wm. Hunt,
who departed this life at Newcastle, after his return out of Holland.
The instrument employed for his release, from works to rewards, was the small pox.
His companion, I understand, not having had that disorder,
durst not approach him in his illness, which was short.
Who can but feel for his tender weakly wife and numerous
family of children! so far distant indeed,
but still only on another spot of the Lord`'s footstool, and doubtless,
if the fault be not their own, objects of his peculiar notice and protection.
Thou may remember at the opportunity which was in +++______+++`'s parlour,
at the time of last Province meeting at +++______+++ with what baptizing
power the dear man spoke concerning some then present,
who would soon be released from their deep and bitter baptisms,
and received into a glorious place of reward:
very probably the testimony might in part belong to himself.
The great Controller of events knows what is best for all, and each of us;
and to his ordering we must submit.
A little time numbers us too, that survive, to the silent grave; happy for us,
if by keeping near the appointed means of help (the all-sufficient grace of God),
we may be enabled to fill up our several duties here,
so as to obtain a place of rest and everlasting repose
for our weary tribulated spirits hereafter.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
Letter 81.

I received thy last and attended to the contents with a mind impressed with sorrow;
indeed sorrow and trouble are at times spread before me,
on account of the situation of things in our religious society.
What is the reason that many educated amongst us,
should be such enemies to the truth they profess?
Yea, the bitterness and enmity of their spirits (like thick darkness) is to be felt.
What must be opposed to those fiery darts?
For my part,
I know nothing more likely for the honest-hearted
to defend themselves and preserve their own spirits,
nor to overcome the agents of the wicked one withal, than the power of gospel-love.
This, if deeply and patiently kept to, will work wonders; this is invincible,
and its armour impenetrable.
But if this be in any measure departed from,
or adulterated with self-love (which is the parent of resentment),
it causes a breach in the panoply (the whole armour) of God, who is love,
and so leaves some weak part unguarded to be wounded and hurt.
If any therefore have been injured or hurt in this way,
to a deep and steady search after the healing virtue of divine love,
I would earnestly recommend them: and as this becomes operative,
and predominant in the mind, it will influence to say, and do these things,
and these only, which make for peace; and I am in the belief, that if patiently kept to,
it will bear down all before it, and, in due time possess the gates of its enemies.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
Letter 82.

I am glad that thou meetest with that respect and attention which may, in some measure,
compensate the loss of domestic endearments.
Indeed there was hardly a doubt but this tribute would be paid thee.
People of good breeding and good sense would hardly be deficient in this respect.
On thy part I am persuaded thy faculties are exerted to manifest that
thou art not undeserving of the marks of friendship shewn thee.
A liberal mind is grateful to a high degree;
and this contention between benefits and gratitude has something very noble in it.
Thou strives, my dear friend, I doubt not, to be accomplished in a still superior style,
in order for thy own improvement, and for a capacity to acquit thyself, in thy station,
with greater eclat; for this purpose thou readest, thou writest, thou conversest: but,
here it seems to me that a danger may attend.

Accumulated knowledge is apt to puff up,
and that beautiful simplicity of manners into which truth leads,
may be unhappily departed from.
The world has its own customs, and also its own language and terms; delicacy,
politeness, refinement, sentiment, are capital words in its vocabulary,
but of very equivocal meaning:
the spirit of the world is utterly wrong and in direct
opposition to the spirit of genuine Christianity,
as the new Testament abundantly everywhere testifies.
The possession of the qualities implied in those terms, even in their fairest sense,
the treasure of literary acquisitions and polite accomplishments,
however useful in their places, are not the essential good,
are not the one thing absolutely needful, "`That good part`" which the Master,
who knew the heart, knew that "`Mary had chosen,`"
and was graciously pleased, for her encouragement, to promise,
that "`it should not be taken from her.`"
May thou, my dear friend also, in thy day and sphere of action, surrender thy heart,
so to be mollified and modelled by the Master`'s power, so made clean and right,
that he may view it with acceptance and approbation; thus the fountain being made good,
and kept with all diligence, out of it are witnessed to flow, the issues of life:
the natural and improved qualifications being sanctified,
and the spiritual gifts super-added, human nature arrives at its perfection;
man then is made (but) little lower than the angels, being crowned with glory and honour.
This is what is held out to us, the prize most worthy to be contended for,
the favour of God, infinitely preferable to the favour of vain unstable man.
Well deserving our attention is that saying of our Lord.
"`Ye are they which justify yourselves before men, but God knoweth your hearts;
for that which is highly esteemed amongst men, is abomination in the sight of God.`"

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
Letter 83.

Thou hast been of late so much the companion of my thoughts,
and the subject of my good desires, that it has weighed with me,
whether it be not a kind of duty for me to write to thee.
I hope I am not very forward to write or speak about the most solemn
things in a cursory way (and my own stock is so small,
that I would not, willingly,
be lavish of it unnecessarily,) but where can be the harm
of sometimes communicating one`'s feelings with a friend,
and stirring up the pure mind by way of remembrance of those things,
which the hurry and cumber of this world,
the inattention and distraction of our thoughts, the depravity of our nature,
the allurement of our passions,
and the workings of a potent insidious adversary upon them,
are too apt to detach us from, and cause us too frequently to forget.-- I love thee,
dear friend, and thy father`'s house, with a sincere affection.
I wish you all the blessings and comforts of this life, and a better life;
and from those sensations which, in my hours of retirement, I have found in my own mind.
I believe, that the good will of heaven flows in a strong current towards you:
may nothing in any of you divert or check its progress.
It will qualify your spirits for the enjoyment of
the goods of this life with the most grateful relish;
it will support you to bear the evils of it with the noblest fortitude,
and will finally conduct you (if you leave yourselves to be conducted
by it) into the regions of unmixed and everlasting happiness.
This precious favour is indeed universal in its extent and operation;
but has more powerful effect and more general influence
upon those who receive and believe in it,
who are living witnesses of its virtue and efficacy;
waiting continually for the fresh supplies of it,
to enable them to discharge a conscience void of offence towards God and man.

Among these too, this holy principle of saving grace,
is wont to operate with peculiar force on the minds of such as are, as it were,
in the spring of life.
It is the seed time, which, if well improved,
will be succeeded by the warm beams of divine favour,
and the harvest will be to present advantage, as well as to everlasting life.
As I doubt not, dear friend,
of thy having been thus visited in the early part of thy days,
from an intention of gracious Providence to pre-engage thy
affections to himself and the cause of his blessed truth,
before the world, its spirit and its connections should engross thee in mature age.
I am earnest, that the living sense of good, begotten in thy heart, may not perish,
as in the womb of formation; but nourished by divine virtue, may grow,
and in the fulness of time, be brought forth to the praise of God,
the edification of others, and the great consolation of thy own soul.
But suffer me, dear friend, to say, a little thing hurts that which is young and tender,
the very jots and tittles of the law and the testimony of Jesus are to be maintained,
or the whole bond of his peace is broken.
He that is not faithful in the little, will not be made ruler over much.
That line is to be preserved inviolable, which divides the children of the kingdom,
from the children of this world; their language, their manners, their aspect,
their outward demeanour and habit, as their country, is different.
It hath seemed meet to infinite wisdom to characterize his people by visible marks,
and I am bold to say,
they will never prosper in true religion according
to the extent of his gracious designs upon them,
who violate those marks of distinction and respect.
The Nazarite is known not only by his temperance, but his exterior appearance.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
Letter 84.

[.signed-section-context-open]
8th of 1st month 1787.

I received thy sundry letters,
and gave all the attention which was likely to be paid by
a feeling and interested friendship to their various contents.
I expected to have written from Waterford, to my dear friend, thy afflicted sister,
but I could not compass it, though I repeatedly tried for it; however,
I did you all justice in another way;
I hope sympathy of the best kind was experienced by me while I was there.
That tender sympathy, which, in the mystery of spiritual unity,
helps to bear the infirmities of our beloved friends,
and ministers strength and consolation to them in the hidden life;
that sympathy in which fresh and earnest petitions are secretly put up to Him,
who sees and knows the deep and pungent distress
of his poor creatures from various causes:
and who only can, effectually, relieve them.
Indeed, my dear friend,
many and various are the distresses of our fellow creatures of the human species;
and I love to feel for them and with them,
though I am not at all personally acquainted with them.
Mankind is at all times very near my heart, and I think it alien from humanity,
as well as Christianity, to be insensible to the sufferings of any.
Thy beloved sister`'s trouble is great indeed, her trial is acute and poignant,
but if she compares it with the calamities, the pains, the embarrassments,
the distresses of body and mind, which many labour under,
without experiencing proper care, pity, or assistance; multitudes, like poor Lazarus,
oppressed with want and disease, and numbers like the rich man,
in a still worse condition, living as without God in this world,
and just about entering into the everlasting torments of the next;
if she compares her situation with these,
how great is the balance of gratitude on her side of the account.
Many are the considerations and circumstances which preponderate
in favour of a humble patient resignation to the divine will;
this sweet child was removed in innocence,
she has escaped the dangers and temptations of this stage of existence:
she has escaped the horrors of eternal misery;
her pure spirit (we have cause to believe) is forever centered in uninterrupted joy.
She was taken off,
not by her parents bringing a disorder upon her when in perfect health,
but by the visitation of sickness, brought on, or permitted, by Him,
who bears rule on earth as well as in heaven, and does all things right and well.
If it had been consistent with infinite wisdom,
that the sweet babe should have continued longer in this life,
and that it`'s near connections should not have had this grievous affliction,
Omnipotence, no doubt, would have ordered accordingly,
and the present dispensation would not have been at all allotted to you.
Or if it had been consistent with the same wisdom
that the chastisement should have been less severe,
the same power could have prevented those circumstances from attending,
which embitter the sensations arising from this sorrowful event; so,
on looking every way at it, there appears nothing remaining,
but in a childlike state submissively to kiss the rod,
and patiently resign to the divine will.
And that this may be your happy experience, is my sincere desire;
that whether the Lord Almighty gives, or withholds, or takes away,
his name may be blest and sanctified among you.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
Letter 85.

[.signed-section-context-open]
23rd of 1st month 1763.

When I am led to believe that our forefathers, in the last century,
were called to hold forth again in their lives and principles that most holy faith,
(even Christianity in its purity) which Christ Jesus taught to his immediate followers,
and established on earth, to remain to the end of the world;
when I ponder that we are the successors in the same faith of those dignified ancestors,
and illustrious sons of the morning of our day,
and that the same cause is now committed to us,
to be maintained in the same spirit and by the same power: I say,
when these things are brought under my solid reflection, I am, at times,
weighed down under a sense of the awful station I am placed in by the wisdom of Providence,
even to be a professor of this religion of Christ; so that I am ready to say,
"`How dreadful is this place.`"
If then it is so awful a matter to profess this holy religion,
as a private member of society,
how much more so must it be to be set apart as a chosen
vessel to convey the quickening virtue of it to others?
How great degrees of purity and holiness are requisite here,
not only in a private capacity to be enabled to set an example of performing the will,
but also in public and private to declare the whole counsel of God?
These have not only the temptations to grapple with,
which are incident to all in general;
but as they are of particular use in carrying on this glorious work,
the grand opposer of it plays his engines in a particular manner against them,
and forms schemes deeply laid, in the mysteries of iniquity,
that if he cannot utterly destroy their faith,
he may render them less useful than infinite wisdom intended, and rob them, in some part,
of the weight of their present and future crown,
and the church of the benefits which might accrue from the
perfections of the gifts and graces bestowed upon them.
It is this enemy`'s grand employment, dear friend,
to be constantly endeavouring to defile the vessel,
through which the divine intelligence is at times communicated to the people,
and divine life conveyed; for there is no other excellence required in the instrument,
but that it be clear and clean.
It seems to me as though he had principally three
ways by which he strives to effect this purpose.
First, he would so hurt the vessel, or pipe,
as that none at all of this precious liquor should enter it:
but that which once was a vessel of honour should be laid aside as useless.

Secondly, there, is danger lest the vessel,
though in a good measure clean and free from filth of any kind,
for want of being sufficiently imbued with the savour
of the liquor passing often enough through it,
should impregnate and adulterate the liquor with some quality inherent in,
or accidental to, the vessel itself.
And, lastly, the pipe may be polluted by the sediments of this same precious liquor,
which should be entirely cleansed out, or will be like the manna gathered yesterday,
and loathed by those whose health and appetite is good,
and who can only be satisfied with wine well refined off the lees.
I doubt not, dear friend,
but thou hast anticipated in thy own knowledge and experience
any broken hints which I can offer on this subject,
though I thus indulge an inclination of freely communicating my sentiments to thee.
I own I do, above all things, love this most noble cause, our holy religion;
and I do believe, that thou,
(among many others) hast been called and qualified to bear public testimony to it.
I fear also, that several who have been thus called, have, by one means or other,
been prevented from coming up in that degree of burning
and shining lustre which was intended,
and so our poor society has missed the benefit (which it so greatly wants)
of the full degree and measure of instrumental help designed it,
to its very great and apparent loss.
My heart`'s desire is, that all of us,
who are touched with a sense that those things are so,
may diligently wait at the fountain head of wisdom and strength, that we may,
by fresh supplies, from thence, be enabled to come up nobly in the stations,
severally allotted to us; neither going before, nor staying behind our proper ranks;
not going forth in the arms or habit of another,
nor in the presumption of strength aforetime experienced;
but with the effectual (though to ourselves and others)
seemingly slight and contemptible weapons,
which, for the time being, it shall please divine wisdom to furnish us with.
So shall the Lord`'s strength be made perfect in our weakness:
our own souls comforted and encouraged to go on,
trusting in the sufficiency of every present supply;
and the church be edified by successful labour.
I commit us both to him, who alone can preserve us alive in the root,
and in his own time make fruitful in the branches.
I do very sincerely desire thy preservation,
stability and advancement in thy own particular,
and in a capacity to be more and more serviceable in the general; and am,
in true brotherly affection, thy faithful friend

[.signed-section-signature]
Richard Shackleton.
