== Letters CXIII &mdash; CXXXV

LETTER CXIII.

12th month 1779.

What more is to be expected by any of us in this life,
than an alternative of agreeable and disagreeable occurrences?
Winds and tempests purify the atmosphere; snow and frost fructify the land.
Let us then, in the day of adversity,
adopt the language of the psalmist (57. i.) and in the intervals of tranquility,
with which our merciful Creator is pleased to favour us,
let us make good use of the present quiet and composure allotted, to cultivate, to renew,
to strengthen our acquaintance with the omnipotent Author of all that is good:
so shall prosperity, as well as adversity, be sanctified to us,
and equally contribute to the consolidating of our present peace,
and ensuring of our future happiness.

Richard Shackleton.

LETTER CXIV.

1779.

My mind is, at times, deeply bowed in thankfulness;
but I feel that tranquility and all these lower enjoyments are exceedingly uncertain;
they have also their alloy.
May we be then like-minded with the royal psalmist,
"`One thing have I desired of the Lord, that will I seek after,
that I may dwell in the house of the Lord all the days of my life;
to behold the beauty of the Lord, and to enquire in his temple.
For in the time of trouble, he shall hide me in his pavilion;
in the secret of his tabernacle, shall he hide me; he shall set me upon a rock,`" etc.

Richard Shackleton.

LETTER CXV.

9th month 1770.

Thou knowest, my dear friend,
that religious growth does not consist in writing and speaking on religious subjects:
it consists in the divine life prevailing in our minds.--Poverty of spirit is the plain,
decent, every-day clothing which properly belongs to, and becomes the Christian man.
This clothing makes us appear comely in the sight of the Master and of spiritual men.
When his followers patiently wear this garment, and keep it unspotted from the world,
in his own time (which they will find to be the best)
he will array them with robes of righteousness,
and garments of praise.
But then they must be stripped again of these which are the Lord`'s ornaments,
and possessing their souls in patience, must contentedly put on their old raiments,
the ordinary livery of the master`'s servants.
Hence is seen the propriety of that expression of his to his disciples;
"`The poor ye have always with you, but me ye have not always.`"
Had there not been a word on this solemn subject in thy letter,
it would have been very welcome to me,
because I know thy time to mention that subject is not always ready.
What I was desirous of was, that, whether absent or present,
there might still be kept open a door of free communication
of sentiments on these matters between us,
by which some good might, and I think no evil could, enter.
I can say of a truth,
that fervent and renewed have been my desires and petitions on thy behalf,
since I wrote last, and I trust thy conflicts and besetments,
thy sense of thy own weakness, and of thy lack of best wisdom, thy indisposition of body,
thy feebleness of mind, will all work together for good.
Certainly the good will of the Almighty Benefactor is towards thee,
and good and gracious are his designs upon thee.
Else, why should my poor spirit be so often dipped into sympathy with thee,
and such petitions be formed in travail in the deeps, on thy account?
Oh! be faithful to the discoveries of the light which maketh manifest,
and to the requirings of duty in the day of small things, and great will be thy peace,
and glorious thy reward; such as "`Eye hath not seen, nor ear heard, nor hath it entered,
or can enter, into the heart of the natural man to conceive.`"
Do not be restless, uneasy and impatient,
to quit thy place of probation and present trial;
but rather use the more diligence (in proportion to the dangers and difficulties
of thy situation) in seeking for inward strength and wisdom to be enabled
to acquit thyself acceptably in the sight of heaven.
Remember wherever we are, it is by the appointment, or permission of all-wise Providence,
who sees both us and our engagements.
It is not the way to gather strength of mind, to endeavour to fly in our own wills,
from the field of labour and battle.--Let us stand our ground,
keep close to the standard of Truth; if we cannot put an enemy to flight,
let us however not flinch ourselves, but openly declare and shew on what side we are;
on the side of him who was never foiled in battle.
Thus, dear friend, thou wilt grow stronger and stronger,
and feel "`The peace which passeth all (rational) understanding,`"
to flow as a mighty stream in thy soul,
bearing down before it all the little, trifling, hindering things,
and thou wilt be able (as thou art faithful and obedient)
to encounter things of greater moment and difficulty,
with honour and success.
So, in the love of our Holy Head, I affectionately salute thee, and commit thee,
with my own soul, to his divine protection.

Richard Shackleton

LETTER CXVI.

9th month 1776.

If these means of intercourse between us were not used,
still I trust the root of friendship lives in our minds.
I knew in my best seasons, it produces good desires and petitions for my beloved friend.
Then, when Truth at the same time expands and prostrates the heart,
my prayers are for thee,
that thou mayest submit to the operation of that power which reduces, changes, and forms;
that thou mayest give up all with an unreserved dedication,
and simply be what the Lord would have thee to be.
Long has he continued his favour to thee; frequent and powerful have been his visitations.
Time flies on with unremitting speed; the end of all things approaches.
Happy will it be for those who have here, in all humility,
received the Truth in the love of it, have bowed their necks to it`'s yoke,
and have not been ashamed to confess Christ in his lowly appearances before men;
such will reign with him triumphantly in an eternity of joy.
May that, my dear friend, be thy state and experience now; and this, thy portion forever!

Richard Shackleton.

LETTER CXVII.

10th month 1786.

Man was formed and designed by his Creator for religious, as well as civil society.
The spirits of the well-minded, met together, aid one another,
and a joint labour more readily opens the spring, which is much choked up by formal,
lifeless, lukewarm, as well as libertine, professors in our society.
Besides, it is the will of the common Father of his people, that his children shall,
at stated seasons, present themselves before him in a general way,
though Satan should come also among them; though in this mixed state of things,
the spirit of antichrist in a mystery should bear rule,
and prevail to spread a cloud over the assembly; yet is this enemy often rebuked,
and the cloud known to be dissipated, and the visited children made to rejoice together,
under the precious influence of unmixed good.
Of what use is thy over-much thoughtfulness?
Or thy looking too far before thee?
It would be as well for thee, I believe, if thou wert, in some respects, nearsighted,
like myself.
We are creatures as of a moment,
and should still endeavour to make the best use of the present moment,
which only is ours; doing in prudence and moderation what is in our power,
humbly dependant on the Author of the existence of our souls and bodies,
for his daily supply to both.

Richard Shackleton.

LETTER CXVIII.

I do not wonder at worldly pleasures, worldly profits,
and worldly splendour captivating the minds of youth;
they see objects through a false medium.
Nothing less than a great supernatural power can change our vile affections,
and nothing less than the renewings of the same power can preserve them right,
when so changed.
A sense of this made David cry out, "`Create in me a clean heart,
and renew a right spirit within me.`"
And the apostle Paul most beautifully expresses--"`According to his mercy he saved us,
by the washing of regeneration and renewing of the holy ghost.`"
This renewing then is what we have to wait to experience.
This transformation from the spirit of the world into the divine image,
must be effected and continued by the renewing of the mind.

Richard Shackleton.

LETTER CXIX.

May every feeble effort, and aspiration after the right thing,
grow and gather strength in every one;
that not one grain of the precious seed of the kingdom may be lost, or unimproved;
for surely nothing is of equal value with the visitation of heaven:
it is indeed the breath of life, by which man becomes a living soul.

I am persuaded thou art diligent in improving thy own stock;
though not making any ostentatious display of much trade,
too often the prelude of disreputable failures.
If thou holdest on in this little, low, frugal, industrious way,
I shall expect to find thee rich.

There seems to be many promising youth up and down, many buds and blossoms,
but there is not produced proportionable fruit.
The plants seem wholly of a right seed,
and of the great and good Husbandman`'s right hand planting;
yet many of them miscarry in their growth: they get out of the fertile, penetrable,
yielding soil, and strike their roots into a stiff hard clay: or the branches,
for want of pruning, grow too gross and run into timber;
or perhaps they are suffered to bear too much at once, while they are young.
Their strength is exhausted and they wither away.

Richard Shackleton.

LETTER CXX.

6th month 1789.

I am sensible of many weaknesses and deficiencies attending me, and wish,
for the sake of the most noble cause which ever existed,
that I were a more able advocate for it.
However, if we faithfully do, according to the ability received,
what appears to be our duty,
though it may appear to ourselves and others a very little thing,
we shall not want encouragement and help to go forward.
A little pure gold is far more valuable than a great deal of base metal.
So I wish thee, beloved friend to be strengthened and encouraged,
and to love the littleness, and not think the day of small things long.
Thou hast, I believe under right direction, put thy hand to the gospel-plough;
neither look back, nor too far before thee, nor about thee,
at the spaciousness of the field of labour; but just turn up the furrow thou art,
for the time being, engaged in, according to the present skill and ability afforded.
"`Whatsoever thy hand findeth to do, do it with thy might,`" the present might;
and may the Lord Almighty bless and prosper, and increase that might,
to the honour of his great name, to the edification of his church,
and to thy own solid peace!

I had some agreeable feeling conversation with dear+++_________+++,
who seemed inwardly strengthened and supported under this fresh trial,
which she met with,
on her return home from about three months labour in her Master`'s service.
Let us mark the economy of divine Providence, and his dealing with his faithful servants;
those that leave all for the gospel`'s sake,
shall receive the "`Hundred fold`" (it`'s said) "`now in this time,`"
but "`with persecutions;`" there must be the necessary alloy in this world,
"`in the world to come, eternal life.`"

Richard Shackleton.

LETTER CXXI.

I find +++_________+++ has been, for some time past, very low in his mind:
yet I trust it is of good, and will be for his good.
Great alteration indeed! his soul, which used to be like a well watered garden,
now like a sandy desert; but I believe he neither complains nor murmurs.
Various are the dispensations which some have to pass through;
similar to those which attended the great Master.
He had a long fast, forty days and forty nights, and was sorely tempted;
but the text says, "`He was led up of the spirit`" into that wilderness.
And if we be led by the good spirit, all will be well; rejoicing and suffering,
feasting and fasting are in his hand; his visited children, disciples and followers,
have only patiently to abide under his government, who leads in the way of righteousness,
in the midst of the paths of judgment.

Richard Shackleton.

LETTER CXXII.

As we resign ourselves to the divine protection and ordering, by a wheel,
(as it were) within a wheel, he effects his gracious purposes concerning us,
which the contumacy of our own wills,
or the fallacy of our own contrivances might frustrate; happy would it be for us,
if we could lose our own wills in the will of God.
The flesh profiteth nothing in the work of religion;
religion which by all means should be the chief concern of our lives, the beginning,
the middle, and the end of our pursuits and desires.
Choose that good part, seek that first, and other things necessary will be added.

A little lapse of time furnishes many new subjects of remark,
and many concurring instances of the instability of human prosperity:
conspiring to manifest that in this world we shall all, in rotation, meet with trouble;
and that there is no permanent, substantial happiness, but in the comforts of religion.
Happy for those who lay the foundation of life on this rock,
and who are preserved thereon through all the perils
and changes which await this state of existence.
They too, in this world, will have their portion of trouble:
but that peace which passeth all conception of the natural man,
will be their solace in the midst of outward affliction.
I heartily wish thee, my dear friend, in particular, and your family in general,
to be partakers of this hidden treasure, which I believe divers of you,
both elder and younger, know by past experience, not to be a mere speculative notion,
or product of a heated imagination; but a substantial, sure, and certain principle,
which, when possessed and retained, in renewed experience,
is sufficient to enable us to do and suffer all things as we ought.

Richard Shackleton.

LETTER CXXIII.

4th month 1786.

I am concerned for dear r+++_______+++`'s frequent indisposition,
the case is slight and delicate; may the contents,
the precious contents be preserved in good condition, and not suffer any damage thereby.
Our poor visible fabrics will be battered and hurt, and get out of repair;
they are frail and perishable; but the spirit which is invisible, is eternal.
May we often watch unto prayer,
in order to be helped to commit and commend our own spirits and
the spirits of one another to divine keeping and protection;
that so, when a total wreck shall be made of these bodies, our souls may be safe,
concentered in everlasting happiness.

Dear cousin +++___________+++`'s connections have been tried with afflictions of body;
trouble will take it`'s rounds; they are best off who are most resigned.
+++_________+++ is inured to penance, mortification and the cross;
this is very contrary to the generality of mankind; this is far from sowing to the flesh:
`'tis in reality and in truth sowing to the spirit;
may the cross prove the divine blessing here and hereafter, life everlasting!
The seed time (which is the spring time) is long with some; the winter intrudes upon it,
continues long, and as it were unseasonably;
but let us remember who it is that orders the course of the seasons:
and we have often had to observe, that the most genial summers,
and most fruitful harvests, succeed such seasons as these.
Yet are not the Lord`'s children insensible of those fructifying showers which freshen,
cherish and make prolific in this spring;
and few I believe are more favoured that way than our friend.
I think with me it`'s always winter, frost and rain, short days and long nights;
yet believing that it is by the appointment of him, who is Lord of the seasons,
I am content: nay I wish for no change, but by his ordering.
If I feel his powerful baptising hand upon me, `'tis enough for me; but without this,
I am like an owl in the wilderness, and pelican in the desert, flat, dry, insipid.

This hand of power, I acknowledge, I have at times felt since I saw thee,
not only in season (in some of our public meetings) but as it were out of season,
on the road, on my bed, etc. is a pretty youth; how beautiful, how useful would such be,
if they suffered the great hammer (the omnific word)
to fall upon them and break them in pieces.
Thou hast felt the strokes of this great hammer; it has softened, and is fashioning thee,
I trust, for a vessel of honour: yield thou unto it,
and be passive and pliable under its influence,
till it makes thee what Infinite Wisdom would have thee to be,
exactly both as to form and use.
In a little time all this scene will be closed upon us all,
our places and our acquaintance will know us, and speak of us no more.
In the closing of this scene, when everything else shall fail,
what will it be to us to witness the Lord to be the strength of our hearts,
and our portion forever.

My beloved friend, farewell; be humble, be diligent, be honest;
and may the Lord Almighty delight to bless thee and comfort thee,
and preserve thee in his fear and in his favour, now and forever!

LETTER CXXV.

The conversation of my dear friends, if happily seasoned with good,
the communing together on the way,
if the Master should graciously please to condescend to join the company,
is pleasing and profitable indeed; and in this I delight.
But if no feeling friend should be near, no person who can converse in the Hebrew tongue,
still the children of the kingdom are not at a loss; their teacher, their comforter,
their sure guide, and faithful friend is with them, and in them.

At the select meeting at +++_________+++,
+++_________+++ came out with something so lively and sensible, as quite delighted me;
I care not by what name men might call it,
I was satisfied that it issued from a divine spring;
thanksgiving was not only in my heart, but on my tongue;
and my spirit rejoiced in commemoration of that goodness,
which followeth down from generation to generation: had thou been with us,
I believe thou would also have been made glad.
Well, my dear friend, I am pleased that thou ventured out with thy little remarks.
No doubt thou appeared as a fool,
so did the great Master before the scribes and pharisees and elders;
but this is a shame which I trust thou wilt gradually learn to despise,
and be more and more conformable to this most excellent and perfect pattern,
our Lord and Saviour Jesus Christ; who, though possessed of immortality,
and dwelling in inaccessible light, left the bosom of his Father,
and came down from the heights of his glory,
for the redemption and restoration of fallen man.
And as he hath loved us, so ought we to love one another, and all mankind in general;
not seeking our own things,
and tenacious and studious of our own false delicacy and honour,
but "`Buried with him by baptism into death`" unto these things,
that we may be living witnesses of his resurrection in life and power.

LETTER CXXVI.

I note thy state, my dear friend, poor enough of itself,
but receiving an additional tinge from the poverty of the places,
where thy temporary residence is; I note with satisfaction thy sensible expression.
"`If I be idle I shall be lost.`"
I note thy endeavours to keep up the daily sacrifice,
though the offering may seem but small.
These things I note, and take comfort in them,
believing that thou art an object of divine compassion,
and that his love and tender regard is towards thee.
I have not since wrote, as thou most kindly recommends, nor heard from that quarter.
We are poor, insufficient creatures; without supernatural aid can neither help ourselves,
nor others; and this aid we are patiently to wait for,
and it will come to such in the right and best (which is the Lord`'s) time.
The help intended for thee does not seem likely to come from province meetings,
which thou missed being at; but surer, better, more substantial, even inward,
immediate help, I hope will be thy comfortable portion and happy experience.

LETTER CXXVII.

3rd month 1777.

I think I am neither bigot, nor zealot, but I find that the holy scriptures,
contained in the Old and New Testament, and the records of the experiences, travels,
and sufferings of our ancient faithful friends, do me most good.
My spirit hath unity with them, as I peruse their writings, or hear them read:
they tend to strengthen the root of life,
and are made instrumental to stir up the pure mind.
The writing of others, upon whom this day of the Lord has not so fully risen,
are more in the mixture, and have a strong colouring of the glimmering,
uncertain twilight, under which their authors see religious matters,
ft looks indeed as preposterous for us to go to them for instruction,
as it would be for a man to have recourse to obscurity for more light;
yet to a mind which pants after the coming (i. e.
the advancement) of the reign of Christ upon earth,
it affords an agreeable sensation,
to be made witness of the springing up and spreading of truth among those
who are not yet come to a full perception and confession of it:
this was cause of joy to the prophet, when he could say,
"`The people which sat in darkness saw great light,
and to them which sat in the region and shadow of death, light is sprung up.`"

The genuine inspired writings of holy men we read,
and ought often to read for our edification,
the productions of such as have not attained to so great a degree of Christian perfection;
though religious men, we may also read for our satisfaction,
keeping a diligent watch over our spirits, lest accumulated knowledge should puff us up,
and remembering the pathetic prayer, "`I thank thee, O Father, Lord of heaven and earth,
because thou hast hid these things from the wise and prudent,
and hast revealed them unto babes:`" and the subsequent exhortation,
"`Take my yoke upon you and learn of me; for I am meek and lowly in heart,
and ye shall find rest unto your souls; for my yoke is easy, and my burden is light.`"
Here is the Master him self teaching, who unites knowledge and practice; speculation,
and even right notions of Christianity of themselves, are vain;
"`If ye know these things, happy are ye if ye do them.`"
Such are the precepts of Christ, and such the spirit of Christianity;
by their excellence, sublimity, clearness, simplicity, and comprehensive fulness,
bearing the genuine stamp of their Divine Original, very different from the tedious,
ambiguous mariner of many writers on religious subjects,
who confuse what they pretend to explain,
and obscure what they take upon them to illustrate;
so that though the text is clear and plain, the comment is often dark and unintelligible.

LETTER CXXVIII.

4th month 1780.

I accompanied dear +++_________+++ into the county of +++___________+++. I
believe the prospect of his children`'s agreeable settlement,
has humbled his heart into still lower depths of resignation, dedication, and obedience,
as thinking that he can never do enough for so gracious, so bountiful a Master.
I love to see a growth in the Divine gift, and individuals waxing strong,
taking firm root, increasing in the increase of God,
and bringing forth fruit to his praise.--What is this world?
It is vanity and vexation, and will soon be over; but all things truly great and noble,
are involved in the cause of God and his Christ upon earth.

I have had some thoughts about going to London this year, but am not yet determined.
I hope that at our ensuing meeting of +++_________+++,
I may be favoured with some little sense of what is best to be done.
I should not like to be backward in any little help
which I might be indued with ability to give,
even in the smallest degree, towards carrying on this great and important work;
and at the same time I often fervently desire to be preserved from unnecessary,
forward intrusion, and busy meddling in matters, which,
in the economy of Infinite Wisdom, have been allotted to other men:
I think I am pretty much will-less as to this migration.

LETTER CXXIX.

Thou art but a poor creature of a moment; strive to improve the present moment,
and be not careful about tomorrow: `'tis bad economy, and not the way to grow rich,
to be still employed in speculating about the future,
and neglect laying hold of the present advantages, which, rightly husbanded,
open the way to future prosperity.
I think thou art very like me in thy failings, I mean thy weaknesses:
my poor spirit is too apt to anticipate trouble; it is like a reed shaken by the wind.
May we be both endued with right fortitude, preserved looking and leaning towards him,
who is a present help in every needful time to his humble depending children,
not calling up to ourselves, as out of the earth,
(raising by own imaginations) evil which the Lord never created;
but relying implicitly on his gracious providence, and learning what this meaneth,
"`Sufficient for the day is the evil thereof!`"
The opinion of people respecting our conduct is not to be too minutely minded,
nor wholly neglected.
If they are disposed to find fault, they will do it, let us act as we will;
and however we should act, we need not expect to please all.
Let us keep to the simplicity of truth, watching that we enter not into temptation,
and praying continually that we may stand approved in the sight of heaven,
let the men of the earth judge as they may.

I was a good deal indisposed in with a cold which I took thither, and increased the re;
however I attended (through favour of Providence) all the meetings,
and my ordinary duties there.
Notwithstanding a sense of our being a greatly favoured and greatly depraved people,
I was satisfied as to myself in general, having witnessed at times these humbling,
baptizing seasons; which I suppose being my highest lot, are the lot of my inheritance,
and peculiarly proper for me.

Our amiable friend appeared in the religious line in the
meetings of worship and discipline in +++______+++ yesterday;
I hope well for her, but am not yet favoured to be a witness for her;
I do not therefore pretend to find fault.
Far be it from me to judge with my own judgment in such weighty matters.
If it be of the highest authority, it will not only stand, but grow and make its way,
and possess the gates (the judgments) of those who are at
present perhaps rather enemies through prejudice and partiality.

Farewell--be of good comfort; he that careth for the sparrows doubtless cares for thee;
they are a numerous tribe; we hardly seem to know their use in the creation,
and yet they live by his bounty.
May his merciful regard be ever extended to thee,
and his almighty arm be ever underneath to support and cheer thy spirit!
This is the poor but sincere offering of unaltered friendship,
and believe me thy affectionate faithful friend.

LETTER CXXX.

As religious persons, we may put on a veil of too much delicacy:
there is shame which we ought to despise.
We ought not only to be religious, but to appear so;
not indeed making a pompous display of austerities,
and appearing unto men to fast (which is not bearing the cross,
but riding in an exalted manner upon it) but shewing forth by our conduct, conversation,
outward appearance, and demeanor,
that we are followers of him who gave himself an example for us to follow.
Some of you, the elder branches of that family, my beloved friends, have been visited,
called, and chosen; the bridegroom of souls hath knocked for an entrance,
and wooed you with the most tender solicitations;
let not a false delicacy bolt the door against him who loves you, and is beloved by you,
inciting you to make excuses; such as "`I have put off my coat, how shall I put it on?
I have washed my feet, how shall I defile them?`"
I am sure the watchmen that went about the city have
often found you in the course of their service,
have smitten and wounded you with the artillery of the gospel:
and if now one (though of the meanest) "`of the keepers of the walls`" (the supporters
of the discipline) should be made instrumental to "`take away your veil`" from you,
to strip off that delicacy,
and manifest to others that the beauty and simplicity of truth is next your heart;
be not ye ashamed to confess Christ in his lowly
appearance before your acquaintance and others;
wear no longer any mask, veil or disguise, but rather avow your sentiments,
make a good profession and say, "`I charge you, O daughters of Jerusalem,
if ye find my beloved, that ye tell him I am sick of love.`"

LETTER CXXXI.

I am glad thy last reports thee in pretty good health.
I hope thou continuest to endeavour to preserve that invaluable blessing,
a sound mind in a sound body:
there is a strong analogy between the outward and inward man;
the constitution of each is different in different persons; some have a stronger,
and others a weaker constitution, both naturally and spiritually,
and require a different treatment; but air and exercise, food and physic,
nourishment and abstinence, all in proper season, are certainly good for all.
Repine not then, my dear friend,
if the least pleasing of these dispensations may be ministered to thee,
and according to thy estimation, be long thy portion.
Thou art under a wise government, even the government of him who doth all things right.
Keep there and it will be enough.

I often thought of thee while I was at +++__________+++,
and did not wonder (but was pleased) that thou suffered
with the suffering seed in that place.
There is a wrong spirit dominant there, which is doing much hurt;
but it looks as if its reign would be but short;
a little lapse of time will more fully manifest its falsity and its futility,
and the solid, substantial truth, I hope, will more and more prevail.

LETTER CXXXII.

8th of 9th month 1773.

Since the short conference which we had together,
I have several times thought of writing to thee,
but various necessary engagements much engross my time,
and leave very little leisure for a correspondence with my friends; however,
I thought I would just hint to thee what might, without premeditation,
occur upon the subject of our last conversation.
I am a person of universal good will,
and readily acknowledge that I am in a particular manner
attached to the cause of my religious profession,
therefore I cannot, without some concern,
observe any friend of mine publicly desert and disavow
this same cause which we have jointly professed;
the only reason thou gave me for discontinuing to frequent our religious assemblies,
as far as I understand the reason,
(viz. a private offence taken at some individual) is in itself so unreasonable,
that I cannot but look on it as only some ostensible cause,
whilst the true reason lies deeper, and in the secret labyrinths of the mind.
Search there dear friend, for the original cause,
and I am mistaken if thou wilt not find it to be a disrelish for
the limitations and singularities which our profession requires,
and a propensity to the grandeur, the pleasures, and the vanities of the world,
which lies in ignorance and wickedness.
But suffer me to expostulate with thee;
from what really good and useful enjoyment does our profession debar us?
are we not allowed all the conveniences and satisfactions of life, which the almighty,
beneficent Donor, is pleased to favour us with?
We are only restrained from the excess and abuse
(which are known to destroy the true relish) of them,
and to preclude those sensations of humble gratitude to our great Benefactor,
which accompany a temperate, moderate use of his favours:
and what will any of us get by joining in spirit, in covenant, in familiarity,
with a deceitful, insincere world?
In the first place, we do violence to that which is of God, in our consciences;
we reject and cast behind our backs,
the many visitations and invitations which have been various ways repeated,
and graciously offered: we, tacitly, by our contrasted conduct, reproach our ancestors,
who lived and died in the faith, as deceivers and deceived;
or else we bring reproach on ourselves, whose lives are diametrically opposite to theirs:
we greatly endanger our property and our morals, by an intimate connection with those,
who are not restrained by the fear of their Creator,
from running headlong into various vices,
and whose pleasure and profit it is to allure others that are in affluent circumstances,
into the same excess of riot (which often ends in
the same distress and embarrassment) with themselves;
by renouncing our religious profession, and forsaking our communion,
we abandon that which is truth, and either adopt that which is error in its stead,
or else joining from principle with no religious society,
we become ensamples of irreligion, and settle in a profane course of life,
injurious to our own peace, displeasing to God, and offensive to wise considerate men.

Bear with me, dear friend, it is possibly the last time I may trouble thee on this head:
thou art the father of a pretty numerous flock of children;
thou art the successor of religious ancestors; thou art come into their place,
and some of their possessions;
if thou would walk worthily and acceptably before the great Benefactor,
who sees all thy secrets thoughts, as well as marks thy words and actions,
and will assuredly reward according to our works,
it is (in my sense) highly necessary for thee to come down in thy mind,
and in humility and sincerity seek for divine wisdom and strength,
that thou may be preserved safe through this dangerous and uncertain state of existence;
that thou may fill up the station in which all-wise Providence has placed thee,
with rectitude and propriety, as a man and a Christian;
and that thou may discharge that ponderous duty of a parent to thy offspring,
in such a manner as will redound to thy own solid peace, and their substantial good;
that so when that awful period shall arrive (and how near it may be at hand is
quite uncertain) when inquisition will be made into our lives and conduct,
whether we have walked in the fear of our Creator,
whether we have properly and gratefully received his favours and benefits,
as using and not abusing them;
and whether we have stood uprightly and faithfully in our lots,
spreading and enforcing the genuine principles and
spirit of Christianity by our lives and conversations,
and fulfilling every relative duty appertaining to our station; that at that solemn time,
and before that tremendous Judge, Witness, and Benefactor,
thou may have to give up thy accounts with joy, and not with grief;
that this may be thy happy experience, is the sincere desire of thy affectionate friend.

LETTER CXXXIII.

18th of 4th month 1755.

Had opportunity allowed, I should, long ere this,
have acknowledged the receipt of thy affectionate lines;
though it is not easy to express that uniting virtue which cements the family together,
and brings them suddenly into an acquaintance, and nearness of spirit,
that requires not the ceremonies of the world`'s friendship to introduce,
nor its arts to maintain.

I have often been comforted in times of discouragement,
with this mark of having passed from death unto life, that I love the brethren;
I feel its prevalence at this time, and in it salute thee, thy dear husband and children,
with fervent desires that he who hath been your morning light and help hitherto,
may be your staff to lean upon! beloved ancients in Israel,
in this your decline of natural strength,
so as to fill up the station allotted you in the church of Christ.
Few are the ancients left,
to whom the middle aged and rising youth can look with advantage!
The Lord of heaven and earth hath gathered many to himself; the world,
in its various appearances, hath slain many others; and some, who are not yet dead,
have their garments so covered with dust, and spotted with defiling things,
that they are not fit to be looked upon, nor their footsteps to be enquired after.
But happy is the state of those advanced to old age,
whose conduct proclaims they have not followed cunningly devised fables,
but have been made living witnesses of the power and coming of Christ!
These have been powerful inducements to me, to bow my heart in holy awe,
from my childhood to this day (I mean with respect to outward means) and,
I am thankful to the great preserver of men,
that there are such here and there to be found; and,
though painful baptisms for Zion`'s sake may attend in viewing the backslidings of many,
yet ability is given at times,
to appeal with reverend confidence to the Searcher of hearts.
"`Thou knowest how I have walked before thee!`"
I trust this will be your crown of rejoicing, in an hour approaching,
which I could wish very remote from you,
except that the laws of nature proclaim it to be near!

The same love, and hearty well-wishing,
attend your offspring! may they so acquaint themselves with the God of their parents,
as to stand in their lots,
and be found worthy to have their names appear in the register of the Lamb`'s army!
Beloved young friends,
suffer the advice of one that loves you (though outwardly
a stranger) to have place in your minds:
the experience of many years has taught me, that godliness is profitable to all things,
and that real happiness is known in proportion to the progress of it in our hearts;
if you look round among your contemporaries, you will find it a sealed truth,
and unspeakably comfortable to this wise number, who have sought,
with unwearied diligence, the kingdom of God; first in time, as it is first in value.
How beautiful upon the mountains have been the feet of these! and how strong the voice
with which their conduct has proclaimed good tidings! salvation hath been their portion,
and peace their safe refuge: they have been qualified to maintain their testimony,
and earnestly to contend for the faith once delivered to the saints.
Where began these?
In the immediate operation of the power of Truth in their hearts, in a humble waiting,
and resignation to the Divine will! not making haste from under the refining hand;
all who have known an advancement in true godliness, have begun upon this foundation;
upon this low ground, but sure foundation, your worthy parents began,
and built with success,and now know how precious it is in advanced life.
The dew of the everlasting hills, and a sufficient share of the fatness of the earth,
are the portion of every soul, which, above all other considerations,
seeks the Lord in truth and sincerity.
O! saith my soul, may there be such a heart in you, as to fear the Lord Almighty,
and keep his commandments always; that it may be well with you, and your children.

Thus my spirit salutes you, dear youth, in the spreading of concern for your good,
that you may, by means of heavenly help, be made truly happy in yourselves,
a comfort to your aged parents, and useful to your brethren in the church of Christ.

I have travelled with much diligence, according to the ability given,
and have had my experience enlarged in rejoicing and suffering;
the last has often been my lot, but I dare not repine; to be what I ought is my only aim,
and best wisdom knows the method to make me so; in his will I humbly acquiesce.

Samuel Fothergill.

LETTER CXXXIV.

2nd month 4th, 1757.

That regard which Truth itself raised mutually in our hearts, is by no means impaired:
it has often been revived since I left your land, and more especially so,
upon my receiving the sorrowful tidings of the removal of thy dear husband;
a circumstance, in which the affliction is, like the loss, very extensive!
Thou mournest the loss of a tender husband; his children that of an affectionate father;
the church laments on account of a pillar removed out of the place it filled,
at a time when, to outward appearance, it was greatly wanted!
This sorrow is allowable; for the great example of every virtue, even Jesus,
wept for Lazarus.
Nature demands it, when its connections are broken, and the endearing,
social ties dissolved: but thou well knowest that we are all pilgrims and strangers,
as our fathers were, and are journeying on through this land of affliction,
towards a city which hath foundations.
Why should we grieve too much, when a companion,
with whom we have traversed many dubious, anxious steps,
has an entrance granted him into the holy city, a few moments before us!

Upon all the glory of the earth, with all its enjoyments, upon every visible thing,
one inscription is written,
as the immutable law of him whose name is Most High--they shall perish;
throughout all nature, and natural connections, it has been, and must be verified.
Equally fixed is this truth, the joy and song of many generations, but thou remainest.
On this everlasting husband, father, friend, and succour, mayest thou,
and thine now lean; and know this dispensation sanctified, to all your help,
in renewing diligence so to live and move, that when the great Shepherd shall appear,
and all his faithful servants with him, your portion may be among them forever!

And now I cannot avoid addressing myself to you, the descendants of my honourable friend.
I am convinced the same gracious hand, which was his support and comfort,
has been extended to you, for the like good purpose; but I am jealous,
the want of religious depth, and simplicity God-ward, hath been the cause of halting,
and of a choice rather to embrace the present world, and have a name of eminence in it,
than to have a new name, which is the name of God, and the city of God.
Thus will the tenders of everlasting treasure, be disregarded,
and the vain shadows of things be preferred to those riches,
which none ever sought with too great diligence: or, if they sold them,
got their value in exchange.

A heart sincerely concerned for your help, cannot dictate flattery; I love you,
and therefore I write thus.
I am also persuaded there is a seed and heritage that mourns in secret,
because of its leanness, and honestly seeks relief from whence it hath ever come.
May stability and patience be the girdle of their loins! and,
in the Lord`'s time this poor, suppliant, distressed seed,
will delight itself in fatness.
One hint, from my own experience, I would suggest to you;
let all your conduct demonstrate,
that you remember the worthy deceased with due affection, who,
though he be dead as to the body, yet let him speak; I have found it my duty,
and a great advantage to me, to place in my view my worthy father;
and in matters of importance, or such as were dubious,
to consult what would have pleased him, who was ripe in experience and judgment;
I believe this reverence to the memory of a religious parent,
is an oblation of sweet incense before the everlasting Father.

Farewell, dear +++_________+++, may Israel`'s rock be thy safe abode;
mayest thou be kept fresh in spirit; green and fruitful in old age: united to him,
and to the many generations of the just,
who are entered into the city by the pearl gates.

Farewell, ye descendants of the great and good, imitate their example;
as they have followed Christ, follow ye them; be wise, for it is true happiness;
in wisdom you will fear to offend, and this fear is an excellent defence.

Samuel Fothergill.

LETTER CXXXV.

2nd month 6th, 1761.

I am much indebted to thee for the tokens of thy remembrance of me,
which I have lately received;
there is room for renewed encouragement to seek after
that which maketh fruitful in old age,
even covers with verdure and plenty all the trees of the Lord`'s house,
according to their degrees of growth.
I wish to cultivate my acquaintance with these signal
instances of the mercy and power of Him,
who is the preserver of his people; these have known him through all their day,
from their beginning to advanced years; they can commemorate his kindness in youth,
his strength in the meridian of life,
and his tender regard when the shadows of the evening approach.

I observe with pleasure thy happy experience of his regard;
may it be thy covering through the valley of the shadow of death!
and may the everlasting arms be open to receive thee,
when thy race here is accomplished!
I have strong hopes that the ties of nature, the example of honourable parents,
their solicitude, the weight of filial duty,
the evidence of the beauty and usefulness of religion,
and the importance of divine favour,
will combine to excite thy children to renew their endeavour to walk in that path,
which all the generations of the righteous have had to tread in,
in their way to glory and peace.
Not all the wisdom of the world, nor the fallacious promises of its favour,
are able to direct to this path; the way-faring man, who is on his pilgrimage,
in weakness, besetments, and poverty, shall not err in his seeking,
though he may be accounted simple; it is better to be a fool for Christ`'s sake,
than wise in all the wisdom of this world!

Farewell, dear friend, I love to hear from thee.

Samuel Fothergill.
