== Letters 1 &mdash; 23

[.letter-heading]
LETTER 1.

[.salutation]
Dear Friend,

My mind hath deeply partaken with thee and thy children,
upon the present affecting circumstance, the removal of thy daughter.
The breach of such a tender connection cannot fail of producing deep sorrow
in a mind less susceptible of tender impressions than thine;
and when we reflect upon the amiable endearing qualities of deceased relations,
they are as additional motives to bemoan our loss:
but as they were prepared for a resting place, beyond the limits of sorrow and calamity,
the inducement to grief may be wisely considered as its alleviation.
The debt to nature must be paid:
we are but sojourners in a World of probation and exercise, and ought not to repine,
if it pleaseth the Author of air wisdom and mercy
to bring to a glorious rest by a shorter path,
than a long succession of painful, weary steps,
through weakness and affliction that often rill the cup of advanced years.

I know there are in the present case circumstances that aggravate the loss:
a family of young children stripped of an affectionate mother,
of a prudent Christian to instruct their tender minds in the ways of religion and virtue,
and of a good example to walk before them, and lead them in the road to happiness.
But there is an all sufficient hand of power, able and willing to guard,
and protect them in every state.
And the offspring of the righteous share in its gracious offers, in a particular manner.

I remember, with great warmth,
some of the last expressions of my honourable mother to her afflicted husband,
respecting him, her children, and herself.

"`Thou wilt be blessed, they will be cared for, and there is a place provided for me.
They are not left under the tuition of a father like too many now a days,
who will neglect their true interests; but one, who knowing from whence every good comes,
will seek to the gracious, all-sufficient Father for himself, and for his children.`"

Thou hast largely partook of afflictions; many have been thy bitter cups; and,
this added, in the decline of life, must be exceeding painful.
But I beseech thee, dear friend,
to remember who it was that delivered in the sixth trouble,
and rest in humble hope that he will not forsake in the seventh.
My brother and sisters unite in near sympathy with thee and children.
From thy sincere friend,

[.signed-section-signature]
Samuel Fothergill.

[.letter-heading]
LETTER 2.

[.signed-section-context-open]
Skipton, 19th of 10th month 1748.

[.salutation]
Esteemed Friend,

In the sweet spirit and fellowship of the gospel of peace I hereby salute thee,
and thy dear companion and fellow-labourer in the work thou art engaged in.

Be not discouraged, for I trust thy good Lord and Master, whom thou servest,
will not leave nor forsake thee; who made thee willing to leave thy outward habitation,
and to pass the mighty ocean, as with thy life in thy hand,
as an ambassador in Christ`'s stead, to preach glad tidings of good things to the meek,
to call upon the indolent and careless,
to direct the straying sheep unto the fold of rest, to raise the drooping ones,
that are too low, and endeavour to bring down the lofty ones that are too high,
even into the paths of judgment.

I have unity with thy spirit, gift, and the administration of it.
I intreat thee, dear brother! keep to thy steady course;
the present state of the church loudly calls upon us for the entire resignation, faith,
hope, charity, and patience, of the ministers of the gospel.
The diversities of gifts, and operations from the one spirit,
are beautiful and serviceable;
as the stars in the firmament are not all of one magnitude,
have not all the same station, nor degree of lustre,
but are each ornamental and serviceable, in their respective places and seasons.

As thou servest not an hard master, but the most merciful and bountiful King of kings,
and Lord of lords, who requires not things that are unreasonable;
I desire thee to take due care of thyself, and consider thy constitution;
do not drive on too fast in this cold climate and season of the year.
Consider, nets are not always to be spread and cast into the sea,
but sometimes to be mended and repaired.
Thou finds the good seed lies low, and is under suffering in many places.
Experience teaches thee, that when and where our Master suffers,
we ought to be content to suffer with him, that when he reigns we may reign with him.

There are, thou knowest, times of sitting at the king`'s gate;
a profitable station previous to advancement.
They who are faithful in this low sitting,
in due time receive a call from the king to put on his royal robes,
which is a high dignity, i et these must not expect always to be thus clothed,
or in such honour, but to take their seat again at the king`'s gate.

[.signed-section-closing]
I am thy truly affectionate friend,

[.signed-section-signature]
David Hall.

[.letter-heading]
LETTER 3.

[.signed-section-context-open]
Kilkonnor, 25th of 4th month 1751.

[.salutation]
Dear Cousin,

As I believe both thyself, and several of my friends at Bristol,
will want to know how I get on my journey, I write these to inform thee and them,
that I stayed at Dublin near a month, being confined by great indisposition, but,
through mercy, kept quite easy with respect to my being so distant from home: and,
had it not been for the affliction it would have occasioned to my relations,
it seemed as if I could have cheerfully laid down my body in that city.
But Providence has not seen meet to say It is enough,
and to set me at liberty from this earthly house: instead of this,
he hath restored to me, my former health,
and seems to point out some further trials and services for me, in these lower regions.
O, may I be so happy as to act in such a manner,
that when the stroke of separation is given,
I may be ready to receive it with calmness quitting this scene of confusion,
in assurance of landing on the shore of eternal peace!
O happy period! how da some of us, at times,
long for it! when all fears of staggering and falling will cease,
and a rest be proclaimed which will last forever;
and one eternal song of praise arise to him, who, of his mercy,
has accounted us worthy to be admitted into those blessed abodes.

I may further inform thee, with regard to my journey, that, at Dublin,
I was several times favoured in my public appearances;
though I own there is such contrariety of spirits amongst them,
and so great stupidity in some, that the work is hard,
I left the city however with satisfaction, and travelled on pretty fast,
till I came to this place; the meetings are mostly small,
and in many places to the full as hard work as in England;
yet there are some truly sensible friends,
and here and there some of the youth that truth has laid hold of:
I pray God they may keep their places, and that their number may increase.

I intend to proceed through the county of Wexford into the province of Munster,
where I expect Mary Peisley will join me as a companion.
I want to know how it fares with thee, dear cousin;
let not too much discouragement enter thy mind.
I have faith to believe that if thou waits with patience all will be well.

This from thy affectionate friend, and sister in tribulation.

[.signed-section-signature]
Catherine Payton.

[.letter-heading]
LETTER 4.

[.signed-section-context-open]
Edgend 7th month 15th, 1750.

[.salutation]
Dear Brother,

I Find an inclination to visit thee with a few hues;
being drawn in that love which many waters cannot quench, into a secret sympathy of soul,
and united to thee in what is more firm and durable than any outward bonds.
Let us not be content with giving up a part,
but make an absolute surrender of our whole heart to the Lord, without the least reserve,
aspiring after perfect obedience to his commands.
It was those, in former times, who left all, and followed Christ,
that were his disciples, and the way is still the same;
the sayings of our blessed Saviour retain their full force and energy,
He that will be my disciple must take up his cross and follow me.
If ye love me, keep my commandments.

We shall certainly be enabled to come up in obedience,
if there is a willingness to be stripped of our own excellence,
and become little and low; yea, to be accounted fools for his name`'s sake,
not regarding the caresses of a vain world, but through him,
resisting its most flattering allurements.
It is true, there is a part in us that would fain partake of the pleasures of this world,
being loth to submit to the death of the cross: it struggles hard for the victory,
seeking, by reasoning and false glosses,
to dim the brightness of the arising of the light in our souls,
and thereby prevent our discerning with certainty, what we ought to do, and what to omit,
furnishing with excuses, which may seem plausible,
for the omission of what we are convinced is our duty.
I have suffered deeply, by giving way to this reasoner,
and find it hard to give up to what is manifested.

I crave thy remembrance, for weakness and fear surrounds me,
and was it not that I am sometimes sensible of divine regard,
I should fall a prey to the devourer, who endeavours to cast down,
even to the brink of despair.
But blessed be the Lord, be does not forsake in the greatest trials.
O! he is worthy to be followed, even unto death.
Happy are they who can say, with an upright heart, thy, will O God, be done.

[.signed-section-closing]
I am, with love unfeigned, thine affectionately,

[.signed-section-signature]
Tabitha Ecroyd

[.letter-heading]
LETTER 5.

[.signed-section-context-open]
Edgend, 6th month 28th, 1752.

[.salutation]
My Dear Brother,

Though I have so long delayed to acknowledge the receipt of thy last most welcome letter,
let this inform thee, that neither negligence nor forgetfulness has occasioned it;
for I have intended almost daily to salute thee with a few lines,
but a multiplicity of engagements rendered it difficult.

I now do it, in that love which is of divine original,
in which my spirit has been often drawn into unity and sympathy with thee,
imploring with tears, that the good hand which is the support of the poor and needy,
may be thy safeguard, protector, and the lifter up of thy head.
And truly I am encouraged to hope thou wilt witness springs to be opened in the desert,
and the softly flowing stream of Shiloh run for the refreshment of thy drooping soul;
as thou art enough resigned and patient.

Let the want we have of pillars in our Zion stir thee up
to a willingness to abide under the refining hand.
Though this may seem to be a day of clouds and thick darkness, of gloominess,
and the shadow of death, be not discouraged, but trust in the Lord;
he will preserve through all to the praise of his name.

I own, my dear brother, I am solicitous for thy preservation and safety.
Snares are so thick planted for our feet, and so many the dangers that surround us,
it behooves us to have on our spiritual armour, and to keep near our captain,
who has left us a rule or measure whereby to square our steps:
his holy life remains to be an unerring pattern,
and the promised assistance of his spirit, we know to be fulfilled;
which is the spirit of truth, to lead us into all truth, if we are willing to be led;
casting down at his footstool all our own excellence, and content to obey his commands.
We may remember, for our encouragement, the words of our blessed Lord to his followers,
Be of good cheer, I have overcome the world.
This indeed is the only praise-worthy conquest well deserving all our labour,
and to this we are most certainly called.

Suffer me, in the love of the gospel, to caution thee on thy return, to be watchful,
and zealously engaged in spirit, lest the hurries and commotions of life should,
in any degree, divert thee from the pursuit of the chiefest good.
Thou knowest its value, and the more we experience of the beauty and excellency of truth,
the more we are engaged to follow it; and the more we follow it,
the more we see the emptiness of every other enjoyment.

I use this freedom towards thee,
not that I esteem myself qualified for the office of a director.
Heaven only knows how often, in emptiness, poverty, and distress, I have my dwelling,
having nothing to boast of; indeed, I would desire to be nothing,
but what he is pleased to require.
And blessed be the Lord, he gives strength to those who make his will the way to,
and end of all their actions and cares;
which that thou and I may ever endeavour to be found in the practice of,
is the sincere desire of my soul, who am in much nearness, and true love,
thy affectionate and well-wishing sister,

[.signed-section-signature]
Tabitha Ecroyd.

[.postsript]
P+++.+++ S. I hope ere long to be favoured with thy company here;
and shall I not congratulate thee on the expiration of thy seven years`' absence,
and approaching freedom?
But what do I not wish for my dear brother!
May the All-wise shed plentifully of the dew of heaven on thy future life;
and as much of the fatness of the earth as he sees
convenient! and let this never be forgot,
Seek first the kingdom of heaven, and the righteousness thereof,
and all other things shall be added.

[.signed-section-signature]
T+++.+++ E.

[.letter-heading]
LETTER 6.

[.signed-section-context-open]
Dudley, 1st month 17th, 1753.

[.salutation]
Dear Cousin,

When So fair an opportunity offers, I cannot well omit sending thee a few lines,
to which compassion, as well as affection prompts me;
for indeed I sympathize with thee in thy present afflicting circumstances,
and desire the Almighty may preserve thee in patience,
till he sees meet to open a way for thy deliverance,
which I hope he will be pleased to do ere long, or lighten thy burden;
I know not how better to advise thee than to wait his time and be still.

Dear cousin, it is, as thou observest,
a time of suffering to the living members of our society, in a general way.
I have long felt it, and may I still feel it! for if I do not,
I conclude I must be insensible, or lightly soaring above the pure measure of truth;
a state I fear much more than to bear the Lord`'s burdens.
Nay, I would fain not flinch, but cheerfully accept them,
and be thankful that I am counted worthy, in any sense, to suffer for his name`'s sake.

I am sure there is need for some in the ministry to go deep into Jordan,
for the maintaining a weighty public testimony.
Lord grant that I may go deep enough! that what I offer
may not be the conception of my own understanding,
without the divine illumination! nor yet the experience of others barely,
but proceeding from the weighty sense of truth, and be offered in the power of it!
I doubt not but that thy desires are consonant with this,
and though weakness and fear attend thee, be not discouraged.
Merciful and compassionate is our heavenly Father, or who might stand before him?
passing by the transgressions of his people, as they turn to him with humble penitence;
strengthening the weak to stand for his name, against the despisers of his glorious,
everlasting truth.

Think not, because I write thus, that I dwell as at the fountain-head; for great,
at times, is my poverty; yea, as though I had lost all sense of good.
This sensibility of want, however,
administers a comfortable proof that some life remains;
hunger being a sure indication of it, in a spiritual, as well as natural sense.
I am much alone, as thou knowest, with respect to companions,
with whom I might converse in the freedom and unity of truth,
and heavy exercises attend me various ways, and at this time particularly,
which seems to be hid from my near friends,
and which it may be best for me at present to conceal from them.
Thus it may be seen thou art not alone, but that I, as well as many others,
are thy companions in suffering, in which the world cannot sympathize:
neither can it intermeddle with the joy and consolation
which results from the knowledge that our Redeemer lives,
and the faith that he is on his way to unloose the heavy burdens,
and set the spirits of his servants at liberty to praise and magnify him,
who is forever worthy.

I salute thee in the best of fellowship,
and conclude with desires for our mutual preservation,
and enlargement in the blessed truth, thy affectionate friend,

[.signed-section-signature]
Catherine Payton.

[.letter-heading]
LETTER 7.

[.signed-section-context-open]
From on board the Alexander, 10th Mo, 15th, 1753.

[.salutation]
Dear Cousin,

As I doubt not thou wilt be anxious to hear from us,
and perhaps pleased to be informed of some particulars relating to our voyage,
I take pen in hand for that purpose whilst on ship board,
not knowing but other business may prevent me when on shore.

After taking ship at Spithead on the 25th of 8th month we
were about nine days before we got out of the Channel;
since then we have been favoured with gentle winds: no storm has yet attended us,
nor I hope will, as we now seem to draw near the desired port.
The climate we have passed through was exceeding hot,
which has affected our constitutions, causing profuse sweating and faintness;
but upon the whole,
we have great cause to be thankful to the Almighty for his merciful support,
and the refreshing incomes of his love, which we have been made partakers of;
wherein our souls have been established in peace,
and hope in his future protection and assistance,
though a share of exercises has attended us even here,
as in every place they seem to be my companions;
but as I believe them to be wisely dispensed by Providence, I desire to be content,
and patiently wait his time for their removal.

We have had several meetings in the ship, and I think it may be said,
the testimony of truth gains ground in authority;
for at first it was very hard to speak to the people; but in the last opportunity,
my companion, Mary Peisley, had a pretty open time to clear her spirit.
But I wish it is not too much like the seed sown by the way side,
which the birds of the air devoured: but that must be left by us,
who shall receive a reward in the faithful discharge of our duty,
whether they will hear or forbear.
We are now going, bound in the spirit, among a people to whom we are strangers,
but a secret hope is raised, that he who, we believe, has called us forth,
will open the way for us, and raise up friends for our necessary assistance,
and give us patience to bear and encounter the many
trials and difficulties which may fall to our lot.
May our eye be to him invariably, saith my soul!

My companion joins in the salutation of true love to thee and thy cousin.

[.signed-section-signature]
Catharine Payton.

[.letter-heading]
LETTER 8.

[.signed-section-context-open]
Charles Town, South Carolina, 11th month 8th.

We landed here on the 26th ult.
after being greatly tried with stormy, contrary winds,
which kept us near a week upon this coast, without suffering us to land;
but through infinite goodness we were preserved patient
and resigned in the midst of a scene of distress.
Weakness of body attended at the same time,
which was chiefly occasioned by the hardships we endured in the storm.

The people of this place behave with great civility to us,
and many of them attend our meetings.
My companion has had some good service among them;
but a door of utterance has not been so effectually opened to me,
as at many other places; but I desire to learn in all states to be content,
even if I am brought here only to be a servant of servants.
My dear love to W. F.

[.signed-section-signature]
Catherine Payton.

[.letter-heading]
LETTER 9.

[.signed-section-context-open]
Long Island, 6th month 9th, 1754.

[.salutation]
Dear Cousin,

The contrariety of the wind on which I now wait to carry me to Rhode Island,
affords me leisure to acknowledge the receipt of thine of the 23rd 1st month,
which I got at Philadelphia, and which was truly acceptable to me,
as it evidenced the continuance of that affection
and sympathy which was early produced between us,
by the source and fountain of love; and which nothing will be able to extinguish,
as we abide in him.
I feel its pure cementing virtue to flow towards thee,
as fresh as when we were first united in Christ, in which my spirit rejoiceth,
with hope that in the reading hereof thou wilt be
made to taste of the same heaven-born blessing;
thus we shall, in measure, witness an intercourse of spirit,
being as epistles wrote in one another`'s hearts, known and read.

It has not been without good cause, my dear friend,
that thou hast been led to sympathize with me in a state of suffering;
for many and deep have been my trials and exercises of spirit,
since I came into this country; but I will not complain, seeing I am assisted,
as I have been in times past,
(when my head has been wrapped about as with the weeds of the deep)
so that I could look through these sorrowful dispensations with
humble hope that they would be sanctified to me,
and when Almighty Wisdom saw meet, removed;
and that mine eye should see Jerusalem a quiet habitation,
and my soul have to rejoice in the salvation of God,
and witness a getting the victory through the virtue of his holy word,
over the frailties and wickedness of fallen nature: which I am made to look into,
and from a sense thereof to acknowledge that in my flesh dwells no good thing.
I am also led to admire the wisdom of Providence
in humbling those whom he has seen meet to own,
and, in measure, dignify before the people.
Is it not for this, that no flesh might glory in his presence,
but give to him the praise of his own works?

I feel a freedom to write thus much to thee,
but it seems to be a time in which spiritual truths
are to be pretty much sealed up in my breast;
and it is my desire not to unlock the cabinet in my own will,
or expose that which is to be as a hidden treasure,
till my great Master sees meet it should be exposed to public view,
which in his own time, I have faith to believe will be the case.

I am informed that R. P. has thoughts of settling in Bristol, which gives me some pain.
I have been thoughtful about him of late, but cannot find the way open to write to him;
but have freedom to desire thee to tell him,
to beware of the favour and friendship of the great;
a snare to which I think his natural disposition
will be apt to subject him more than some others,
and which therefore requires a double guard.
I have looked upon him as a hopeful plant,
but perhaps not yet able to bear the caresses of a deceitful world,
nor deep enough in experience to distinguish between real and pretended friendship,
in all, with whom he may be conversant.
I am ready to think the enemy will tempt him with this bait,
from which I desire the Almighty may preserve him; for many have been hurt,
if not ruined by it.
If he does not seek great things, neither spiritual nor temporal, I hope he will do well;
and the Lord, who best knows what our states can bear, will provide for him sufficiently.
My companion joins in the tenders of love to thee.

[.signed-section-closing]
I am, in the fellowship of the gospel, thy affectionate cousin,

[.signed-section-signature]
Catherine Payton.

[.letter-heading]
LETTER 10.

[.signed-section-context-open]
Plymouth,in Pennsylvania, 6th month 27th, 1755.

[.salutation]
Dear Cousin,

Pursuant to thy request I am set down to write thee by this vessel;
though I am considerably unfit for the exercise by illness, occasioned by a great cold,
which I took about ten days ago; and being obliged to travel, as meetings were appointed,
it still remains pretty heavy upon me.
I hope, with a little rest, through Divine favour,
I may soon be restored to such a degree of health
as to be able to finish this painful journey,
which to look at with an outward eye, seems drawing near to a conclusion;
we having now visited nearly all the meetings of Friends on this continent;
but I confess there is yet a veil spread betwixt my spirit and England,
through which I hope not to force my way, but wait until it is removed by Providence,
and then I may joyfully set my face homeward, having this comfortable evidence,
that I have so finished the work he has given me to do here,
as to find acceptance in the Lord`'s great mercy.

With regard to the threatening confusion among the powers of this world,
I am principally concerned on behalf of others, knowing myself, in a good degree,
the fulfilling of that command of our great Lord, "`When ye hear of wars,
and rumours of wars, be not troubled.`"
For considering the present depraved state of mankind, these things will be,
and I find it safest to look but little more at them than is necessary,
in consequence of my duty: the arm of the Lord is my strength,
which I hope will be revealed in every needful time.
I have faith that we shall not be given into the hands of an enemy,
unless it be for some good end, and if the glory of God be advanced among men,
by our being taken captive, I am at present resigned thereto.
I sometimes look sorrowfully towards England, as though some judgment was near it,
and could be glad to be rightly inspired to pray for it;
but it is as though the door of intercession was pretty much shut to me,
save for the Lord`'s servants, and what can be done in such a case,
but to sit down as quietly as possible,
and take refuge under the shadow of the Divine wing until these calamities are overpast.

I have wrote more than I was apprised of when I sat down.
My love to Friends; and accept the same, in a very near manner,
from thy affectionate friend,

[.signed-section-signature]
Catherine Payton.

[.letter-heading]
LETTER 11.

[.signed-section-context-open]
Philadelphia, 1st month 10th, 1756.

[.salutation]
Dear Cousin,

From a principle of affection,
and an apprehension that thou mayst desire to hear from me,
I am prompted to send thee a line, though otherwise much unfurnished for writing,
being rather low and empty, but, through mercy, pretty quiet,
and not without hope of Divine preservation which
is a blessing to be acknowledged with humble thankfulness,
and if favoured with the same through life, we ought to endeavour to be content,
although no great degree of Divine enjoyment be afforded us;
and honestly labour in the ability afforded in the way which is cast up by a kind Providence,
trusting him for our reward, who is faithful,
and will bear up the heads of his depending children in their deepest exercises,
and in the end bless them with the fruition of glory.
And what if our trials through life are great, our temptations abundant,
and our labour and travel difficult and painful to nature?
Will it not furnish us with a more joyful song of praise to him that hath supported,
and assisted to do the work which he required of us,
till he brought us to his everlasting kingdom?
For my part, I see suffering, poverty, etc. to be so consistent with our present state,
and so good for us, that my soul prays to be united to them as my proper portion;
yet to have the eye of my mind directed to him, whose hand is full of blessings,
which he dispenses according to the necessities of his people.
I am ready to say, let him do what he pleases with me,
if I am but in the Lord`'s hand it is enough.
We cannot be unhappy, unless the perverseness of our own will,
and the corruption of our nature make us so;
these I have seen to be the ground of a great part of our afflictions through life;
and that to bring us into order, and reduce us into the obedience of Christ,
we need these bitter baptisms, which we sometimes pass through,
previous to the knowledge of our duty.
This, in my view, demonstrates our imperfection;
the glorified spirits walk continually in the light of the Lord;
and although we must not expect this to be our experience,
whilst inhabiting these tabernacles of clay, yet let us remember,
we are taught to aspire after this state of perfection,
to do the will of God on earth as it is done in heaven; a lesson,
which if we had fully learned,
there would not be so much reasoning and disputing with flesh and blood,
when the knowledge of our duty was clearly made known to us,
nor so much unwillingness to believe in the light.

In writing thus I feel a freedom of spirit, so that I am ready to query,
is there not a cause?
I have thought myself of late like one almost lost to my friends,
yet I hope not so in reality.
Our stay in this country has been prolonged, I suppose, beyond our friends`' expectation,
but I hope not beyond our Master`'s time.
My companion joins in the salutation of dear love to thee.
I am thy affectionate cousin,

[.signed-section-signature]
Catherine Payton.

[.letter-heading]
LETTER 12.

[.signed-section-context-open]
Newhill Grange, 8th month 24th, 1755.

[.salutation]
My Dear Friend,

Thou tells me but little of the satisfaction met with in thy going along,
but I may tell thee, whilst I am thus writing,
that a comfortable hope springs in my mind,
that though difficulties and various afflictions may be thy lot,
besides a sense of the drooping state of things,
and the great declension from that primitive purity of faith and practice,
which dignified our worthy elders, yet that thy labours will not be in vain in the Lord.
Those who go forth weeping, bearing the precious seed,
and handing forth according to their ability of what is given for the help of others,
whether to rebuke, instruct, or confirm,
these will partake of the blessed fruits of obedience,
and witness the sheaves of peace secured on their return,
which they may have sought in vain, because the time was not fully come.
It is necessary to learn to suffer want, as well as to abound; and,
if it should be our experience to be much abased in the sight of the congregation,
it is indeed unpleasant, but perhaps necessary for some to pass through,
in order for their refinement,
and bringing into a willingness to become fools for Christ`'s sake.
I am apprehensive it is sometimes the case, that we think we have acted as fools,
and our appearance been despicable in the view of all present;
at the same time the cause of truth has in no wise suffered,
and we have been in the way of our duty, and rightly engaged.
Yet some diffident minds bring this upon themselves, even at unawares,
by looking too much at their own weakness;
the adversary also seeking to find room to plunge into discouragement
such as he cannot exalt above measure,
nor perhaps remove from their steadfastness, by any other means.

As one who has suffered deeply by listening to his insinuations
(which how plausible soever lead to the chambers of darkness,
where there is no order) I would caution thee to be upon thy guard,
and not weaken thy hands by giving way to his accusations, since the humble,
attentive mind may feel the difference between the
gentle reprehensions of the Prince of Peace,
and the accusations and upbraidings of the grand destroyer.
My brother and sister give their love to thee; accept, dear friend,
a salutation of true love from thy friend,

[.signed-section-signature]
Tabitha Ecroyd.

[.letter-heading]
LETTER 13.

[.signed-section-context-open]
Edgend, 8th month 4th, 1756.

[.salutation]
My Dear Friend,

I Think it is high time to acknowledge the receipt of thy last kind favour,
lest thou should think me indifferent as to cultivating the friendship between us;
this is far from being the case;
I hope it is so well established as not to suffer decay by time,
or any contingencies of life; so long as we abide on the good foundation,
and are not sliding therefrom, though temptations, afflictions,
and various trials attend.
May that good hand that hath hitherto sustained, and been our preservation,
still uphold and conduct both thee, and myself,
and his visited children in all their adversities, the world over!
A sentence thou quoted from a letter of thy worthy cousin, affects me much,
and many times since I read it,
I have had cause to subscribe to the truth of that remark,
"`That the perverseness of our own wills is frequently the ground of our sufferings;
to rectify and reduce which into the obedience of Christ
we need many baptisms previous to the knowledge of our duty.`"

This, I must own, has been my case,
notwithstanding the desire which lives in my heart
to be entirely devoted to the great master.

I need not tell thee that I have for some years had it in my mind to give you a visit,
to which, in its first dawnings, I yielded my assent without hesitation, yea, I may say,
with submission, and reverent hope in the Divine sufficiency;
when this was done I grew not only easy,
but was persuaded in my mind no more at that time was required;
and I had as much satisfaction in dropping the concern
as I had before in giving up to it;
and for many months had cause to believe I was in the way of my duty, in abiding at home.
But since the concern revived, I have found much more reluctance in giving way to it,
and been unwilling to believe the manifestation,
thinking the commission not of sufficient weight to be obeyed;
that labouring under such difficulties and fears,
I could not engage in such a mighty enterprise.
Thus I looked at my own weakness, unfitness, and imperfections,
and would have shut it out, with considerations like these:
"`It is impossible such a thing can be required of me, my heart fails me at the prospect;
if I set forward, my return may be with confusion.`"

Thus, my dear Lucy, I have been for some time past reasoning.
Looking at the first view I had of this journey,
I still thought that if it was really my duty,
it would have worn the same aspect as at first it appeared with, and because it did not,
I was not unwilling to think the revival of it was a delusion,
and that the will had already been taken for the deed.
By listening to these insinuations, which seemed like plausible arguments,
true faith was by degrees in a manner extinct.
Being shut up in poverty and darkness, I mourned greatly, having never, that I remember,
been in such a low condition; for to the distress in my own bosom,
a sense of the declining state of some in our meeting,
who have lately married out of the society, added woe to my sorrows,
and I was ready to conclude my labour had hitherto been in vain,
and that I had spent my strength for nought.

Thus I have been greatly tossed, as with storms and tempests,
and far from being comforted.
I have sate as one amazed, fearing I should be quite overwhelmed.
Yet frequently I had to look towards the holy temple, and endeavour to resolve,
with all my heart, that if infinite mercy would once more condescend to favour me,
and cause his light to shine, I would go wheresoever it might lead.
And, blessed be the name of the Lord,
my Saviour! he has upheld and supported beyond what I dared to hope for;
preserving in patience my weary soul, and teaching to wait till he again appeared.
And with the first dawning of the heavenly light, I was drawn towards you,
and have since been preparing for the journey,
which I would gladly perform with the diligence and faithfulness of a trusty servant.

What I have said is indeed an argument of imperfection;
but my heart does not charge me with wilful disobedience.
I have been solicitous to know the right time to move,
and have great cause to be thankful, because of the evidence I feel that it is not past.
I hope to set forward in a few weeks, accompanied by my friend Mary Slater.

No doubt thou hast heard of the arrival of our valuable friends from America;
many will rejoice that they are safely returned,
after the many perils and difficulties they must have passed through;
may they experience an increase of spiritual blessings,
a rich reward of peace into their bosoms! is what I greatly desire.
And as the subjects of antichrist have been endeavouring
to set them up as marks of reproach,
for their faithful discharge of duty, in labouring to promote the kingdom of peace,
and enforcing the practice of the doctrine of Christ our Lord,
so I hope the designs of these opposers will be frustrated
by him who can restrain the wrath of man,
and give his servants patience in suffering for his name`'s sake.

[.signed-section-closing]
I am, with the tenders of cordial esteem, thine,

[.signed-section-signature]
Tabitha Ecroyd.

[.letter-heading]
LETTER 14.

[.signed-section-context-open]
Dudley, 2nd month 24th 1757.

[.salutation]
Dear Cousin,

I Have received thine of the 16th,
and am glad to find that thou art so freely given up to follow the Lord,
in the way of his leadings, though it may be in paths wherein our faith, patience,
and obedience, will be greatly tried.
I trust he will crown our engagements with an evidence
that we have been in the way of our duty,
as we are concerned to move, step by step, in his light.
My mind has been more than commonly tried in the present concern, yet cannot say,
I repent of one step that I have taken towards the accomplishment of it.
However it may terminate, I have moved according to the best of my understanding;
as I have stood in the resignation, either to go or stay,
I could do no other than hold myself in readiness; hoping that the Almighty,
whom I wish to serve with my body, spirit, and substance, will lead me in his wisdom.

I must own that my mind is so much sunk into a sense of my own imperfections
that I hardly dare look at going forth to instruct others.
Neither can I dare to draw back, for although to me belongs weakness, fear,
and confusion of face, yet as our God is a consuming fire, and can, at his pleasure,
pronounce me clean, through his word, (under the purifying operation of which,
I trust I now am,
and am willing to abide the appointed season;) I
hope he will fit me more and more for his service,
so that I may not preach my own condemnation,
nor while I am endeavouring to keep the the vineyard of the Lord,
neglect the cultivation of my own heart.
I see it to be a great work to become the sons and daughters of God,
without rebuke in the midst of a crooked generation, who are watching for evil,
rather than good, and to lay waste the service of the Lord`'s messengers,
by exposing their defects.
It is difficult to steer our course, so as to give no just occasion to speak evil,
and at the same time give no countenance to their licentious practices;
and inasmuch as they are interspersed through the camp of our Israel,
I see it necessary to be somewhat reserved, especially in mixed companies,
or among such with whom I have had no previous acquaintance;
and if for this I am thought stiff and precise,
I must repose myself in the simplicity of my intentions,
and desire to keep within the limits which divine wisdom prescribes.

It is quite unexpectedly that I am thus led to write;
but it may be no unnecessary caution to thee in the country thou art about to visit,
where thou wilt meet with some who have the appearance of Friends,
but may be found to be enemies to the cross of Christ.
A freedom of behaviour is particularly agreeable
to those whose caresses seem to demand it;
but it is a tribute truth will forbid to pay to many.
And as I much desire thou mayst be preserved from receiving any of the wages of unrighteousness,
allow me to say,
beware of courting the favour of any by abase condescension to a libertine spirit.

[.signed-section-closing]
I am thy affectionate, and well wishing friend and cousin,

[.signed-section-signature]
Catharine Payton.

[.letter-heading]
LETTER 15.

[.signed-section-context-open]
Edgend,6th month 25th, 1757.

[.salutation]
Dear Lucy,

I Have been informed of dear Rebecca Smith`'s illness, which much affected me;
though I have no doubt if she is now removed her change will be glorious,
and the painful pilgrimage succeeded by a happy arrival in the regions of endless day,
to join the general assembly, and church of the first-born; where,
freed from the anxious doubts and fears that attend this weary travel,
and secured from the dangers, snares, and temptations which beset almost continually,
we may meet to part to more.

I own, my dear friend, the enjoyments of this present life,
and the short-lived satisfactions we partake of, are so embittered by disappointments,
and connected with fears, that I cannot but frequently say in secret,
it is better to be dissolved; it is better to be delivered from this tenement of clay,
this house of bondage.
And yet I would wait with patience the appointed time; and as much as in me lies,
fill up the day`'s work before the shadows of the evening approach.
But I am attended with fears of being greatly deficient in my duty.
From thy truly affectionate, and faithful friend,

[.signed-section-signature]
Tabitha Ecroyd.

[.letter-heading]
LETTER 16.

[.signed-section-context-open]
Edgend, 7th month 30th, 1758.

[.salutation]
My Dear Lucy,

Thy acceptable letter came to hand yesterday;
and I am willing to embrace the first vacant hour to acknowledge the favour,
not knowing if it should be now omitted when I may again have leisure,
as I have many things to engross my time and thoughts.
But know, dear friend, whether I write, or am silent,
I put so high a value on thy friendship, that I would willingly cultivate it,
as far as I am able.
And as its original and best supplies proceed from the fountain of all perfection,
I would gladly hope it may subsist when every tender connection in nature is dissolved.

I have near fellowship and sympathy with thee in thy lonely travels,
and the perplexing steps thou hast to tread in,
but was comforted in the perusing thy letter,
with an evidence in my mind of our heavenly Father`'s love.
Though not without a quick sense of thy present sufferings,
I feel that it is a tribulation that worketh patience,
and will be productive not only of experience, but hope,
even that hope which is as an anchor, sure and stedfast, which never makes ashamed.

I am much concerned to hear of the continued illness of our friend L d,
and feel desires for her, that

Divine mercy may be near in every trial, and sanctify every probation; and that she,
and all of us, may submit to that power, which can thoroughly refine from all the dross,
and every selfish view, making us willing to he as nothing, and counted fools,
so that the final issue may be peace, and assurance forever.

When I take a view of the many dangers attending poor mortals in this wilderness passage,
I am ready to say, in humble thankfulness, it is of thy mercy, O Lord,
that we are preserved in the land of the living;
it is of thy unmerited compassion that I am not consumed;
my longings are still continued, and increasing, after a better country;
where being delivered from evil, and freed from temptation,
sorrow and sighing shall be no more.
It is indeed my desire to join thee in fervent prayer,
that every mercy may be so sanctified to us, as to work the greater humiliation.

On this day two weeks I returned from our quarterly meeting at Lancaster.
Lydia Lancaster was so well as to attend some of the meetings;
James Wilson was also there; and it was truly comfortable to have the company,
and sit under the lively testimonies of two such worthy honourable elders.

[.signed-section-closing]
I salute thee, in near affection, and am thy true friend,

[.signed-section-signature]
Tabitha Ecroyd.

[.letter-heading]
LETTER 17.

[.signed-section-context-open]
Clonivoe, 5th month 1st, 1759.

[.salutation]
Dear Friend,

Thy acceptable lines of the 5th of 2nd month, came duly to hand.
I would have wrote to thee sooner,
but that I have been closely engaged on behalf of the society,
in visiting meetings or families;
for it is my desire to perform the little service required,
and I am well assured there will be a reward equal to it.

The state of our society calls for mourning:
the numerous slips of those in exalted stations increases the revolt;
and tends to strengthen those who have taken their flight in this day of outward ease.
When I look round, and take a view of the sorrowful appearance of things,
I am ready to say, Who is sufficient for the work?
who is able to stop the rampant strides that the offspring
of the professors of truth are making into undue liberty?
except the Lord turn them they cannot be turned;
except in the riches of his mercy he pardon them, they cannot be pardoned;
their condemnation will be greater than that of those
who never sat under the teachings of a free ministry,
nor had been taught to believe in the inward manifestations of the spirit of Christ.
With humble desires for our mutual enlargement in Christian experience,

[.signed-section-closing]
I remain thy affectionate friend,

[.signed-section-signature]
Samuel Neale.

[.letter-heading]
LETTER 18.

[.signed-section-context-open]
Dublin, 11th month 10th 1759.

[.salutation]
Dear Cousin,

It has been rather want of leisure than affection and inclination
that has prevented my thus saluting thee,
since thy change of condition, which, I trust,
will not occasion any breach in our friendship.

Though it may now be expected thou hast conferred
the greatest share of thy affection on a particular,
I hope a proper portion is reserved for thy friends; and above all,
that thy love to the church, and devotion to the service of it, in Christ,
will remain unshaken.

I have now well nigh finished the service allotted me in this land,
and am preparing to return to my native country.
I have travelled more than eleven hundred and twenty English miles,
(besides crossing the sea) in about nine weeks.
Thus I have been called to labour abundantly, for what cause infinite Wisdom knows best.
I hope, however, it will be blessed to some individuals,
and that a reward of peace will be mine.
My constitution must suffer, yet I am upheld to the admiration of myself, and others.
If I have but the evidence of acting in the counsel of heaven, I am content;
even if this frail tabernacle should fall in the service.
I need not tell thee that my exercise has been frequently painful,
suited to the states of the people;
but I leave the nation with a comfortable hope of revival of life in some places:
a visitation is extended to the youth, and, I trust, some of them will embrace it,
and become instruments of good in a future day.

I do not intend to seal this till I arrive in England, till when,
I am thy truly affectionate cousin,

[.signed-section-signature]
Catherine Payton.

[.letter-heading]
LETTER 19.

[.signed-section-context-open]
3rd Mo 15th, 1760.

[.salutation]
Dear Cousin,

Previous to the receipt of thy letter,
I had intelligence both of thy illness and recovery.
I am thankful to providence for thy restoration to health.

I never yet could believe that thou wast wrong in entering into the connection;
and therefore I trust, that he who constituted the union, will bless it to you both.
I am glad to find thou canst so readily obey the pointings of the divine hand;
and that thy husband so freely resigns thee to its disposing.
No doubt nature will feel in these separations,
but as your happiness does not consist in the gratification of earthly desires,
but in doing and suffering the will of God, your union in that life which can never end,
will be increased by absence.

Thy concern for my preservation from the snares of an unwearied adversary,
I take notice of, with thankfulness, and hope to join thee therein.
I dare not presume upon my standing; feeling daily my weakness, and having, with sorrow,
to observe the failures of some who have been eminently favoured:
but if a strong desire to be detached from the world,
and fixed in the station which Heaven allots me, recommends to its notice,
I may be allowed to hope I shall be supported in
the midst of discouragements which attend.

After many painful baptisms,
(to some of which thou art no stranger) every prospect of what may be allotted me,
is removed; and I am content to remain blind to the future, until the hour come,
wherein every determination of Providence is revealed.

My constitution seems to be shaken by the many engagements which await me,
both at home and abroad; but I am content, if this assurance remain,
that I am about my heavenly Father`'s business.
Please to remember me affectionately to friend Hammond, and believe me to be,
dear cousin, in the sympathy of the gospel, both in suffering and rejoicing,
thy friend and companion,

[.signed-section-signature]
Catherine Payton.

[.letter-heading]
LETTER 20.

[.signed-section-context-open]
Manchester, 3rd month 16th, 1763.

[.salutation]
Dear Friend, Richard Eckroyd,

My mind is greatly affected with a sense of thy loss
in the sudden death of thy dear wife,
who had long been a comfortable companion and help-meet in life.
But alas! daily experience shews us how transient
and uncertain all temporal blessings are;
which should excite our minds to aspire after enjoyments more sublime and certain,
that will endure when all our painful conflicts are ended.
Thou knows where to apply for succour in this time of trouble; and I trust,
the same holy hand which has many a time stayed thy mind in various exercising moments,
will now be near to clothe with patience and due resignation to
the Lord`'s will who gives and takes away in unsearchable wisdom;
who, though he see meet to administer affliction, and mix our cup with bitters,
yet in great condescension to human weakness,
draws near to support the poor disconsolate mind when desiring to embrace the rod,
and not repine or murmur on account of trouble, but attentively hearken to its language,
in order to be instructed.
It is my desire for thee, and all thine, that your minds may be centered in humble hope,
and trust in him, who is, and ever will be, a God near at hand,
and present help in time of trouble.
And, I doubt not, he will be so to thee; a staff to lean upon in the decline of life,
when deprived of thy best temporal comfort.

I feel my Heavenly Father`'s love to tender my mind in writing these lines,
and affectionately salute thee and all thy children in true sympathy and union of spirit.
My brother joins in dear love with thy friend,

[.signed-section-signature]
Sarah Taylor.

[.letter-heading]
LETTER 21.

[.signed-section-context-open]
Warrington, 2nd month 20th, 1761.

[.salutation]
Dear Friend And Kinswoman,

Among the many wishes of thy friends for thy happiness,
none desires it with more sincerity than myself,
though more silent about it than some others;
and as a testimony of my concern for thy welfare,
I sit down to throw before thee a few hints which may be useful to thee, if attended to;
even to render thy life easy and happy, and thy end honourable and peaceful.

First, and principally, thy duty to the Almighty Lord and maker of all things; by whom,
and through whom, all things visible and invisible consist, the Author of all blessings.

Let him be looked to, and remembered by thee, in this light,
and be humbly engaged to seek his favour.
Let nothing impair thy love to him, He it is that can blast every pleasing prospect,
can wither every hope, and also sanctify every affliction.
Be not ashamed to shew thy trust in him, by humbly walking before him.
It is in vain to expect a total freedom from sorrowful events,
but a great mercy to have the staff of ages to lean upon.

Secondly: The duty to thy husband, who, if I judge right,
from his tenderness and affection to thee,
will be entitled to every degree of a mutual return: study his temper;
accommodate thy own to it; I have seen great inconvenience arise through inattention,
where the wife hesitates at the request of the husband,
and yields at last a reluctant obedience:
this diminishes that tender affection which is the life and comfort of the married state;
gradually creates a distance, and then life may be uncomfortably dragged along,
but not happily enjoyed.
Cultivate in his mind, and in thy own every religious sentiment,
strengthen that part as much as possible:
hereby a twofold cord of divine love and natural affection
will unite you in a covenant never to be broken.

Third: Towards Friends of the meeting into which thou art removing,
let thy conduct be humble, affable, and exemplary, not assuming; preferring others,
that others may prefer thee.
Humility is the surest way to honour: let no emulation to be greater than some,
and equal to the greatest, ever be harboured in thy breast;
for this will raise displeasure, envy,
and other disagreeable affections in the minds of others:
let thy dress be rather beneath, than on the level with thy circumstances;
it will be to thy reputation.

Fourth: Let it become thy constant watch to avoid that ruinous practice of tattling,
tale-bearing, and secret reflection.
These sources of division and mischief are hateful to God and man.
This character sets itself as the object of general contempt;
its hand is against every one,
and every one`'s hand and heart will be against them who merit it.
The concern of one`'s own mind and family are sufficient to employ a prudent mind,
without interfering unnecessarily in the business of others.
Notwithstanding this, sacred reproof, where just, and immediately addressed to the party,
is a beautiful, useful part of friendship.

Fifth: Let thy husband`'s relations become dear to thee.
Cultivate every sentiment of friendship and affection for them,
especially for his mother, with whose anxieties a son must sacredly sympathize.

Excuse, dear cousin, the freedom of these hints;
they proceed not from any painful apprehension of a contrary conduct,
but my affection for thee induces me to wish thou mayst be found in the way to blessing,
even the blessing of Heaven above, and of the earth beneath,
the blessing of the ancient mountains, and everlasting hills.

[.signed-section-closing]
I am thy faithful friend, and affectionate kinsman,

[.signed-section-signature]
Samuel Fothergill.

[.letter-heading]
LETTER 22.

Divers of this age have bent their thoughts and desires too much towards the earth,
to have a clear discovery of the times and seasons, in a spiritual sense;
indeed the sacred purposes of the Almighty are inscrutable
by all the penetration of finite understanding,
uninfluenced by his own Holy Spirit.
Yet some have seen and believed in the visions of light, that the day of gospel light,
which has dawned upon the nations, will rise higher and higher,
though some clouds may at times intercept its brightness,
as hath sorrowfully been the case amongst us as a people:
the earth has got between many of us and the sun, and brought an eclipse,
which has been almost total over their understanding,
and thus they have not been of the use which was intended, to give light to a dark world.

Though I would not derogate from the work of those honourable sons of the morning,
who were made instrumental, in a great degree, to break down the partition wall,
or rather diabolical structure, which selfish man had erected,
as between God and the people; yet I am not afraid to say it was,
and is the design of God that his people, in future times,
should make an improvement on their labours, and carry on the work of reformation,
further than was effected by them.

I am of the judgment that the day hath begun to dawn,
in which the sun of righteousness will rise higher and higher,
and shine with greater lustre than heretofore;
and if those who are called of God to be sons of the morning look back to the night,
by sipping of the golden cup of abomination, which is held out to the nations,
they will frustrate the design of Providence respecting them,
though not in relation to his own work,
for it is his sacred determination to be glorious in heaven, and glorified on earth.

Should it be so that those who are called his Israel be not gathered, I am of the faith,
that when the gospel has been first preached to them, and they neglect to embrace it,
(thereby rendering themselves unworthy of so great salvation)
the feet of the messengers will be turned another way,
even to the highways and hedges, with a power of compulsive love,
which will prevail on the halt, and the maimed, and blind,
to come to the marriage supper of the Lamb: and, by coming, they will be made beautiful,
as a bride adorned for her husband,
who shall not look back to the things that are behind,
but press forward towards the mark for the prize of the high calling of God, in Christ;
following no man`'s example further than they follow him.

What if I say in the faith that is given me,
that God has designed to carry some of this generation higher and
further in righteousness than their forefathers were carried;
even such as were honourable in their day, and are fallen asleep in Christ.
Therefore let them take care that they limit not the Holy One of Israel,
nor circumscribe the leadings of his blessed spirit,
by looking too much at the example of others;
for this has been a means of hindering the progression of many glorious,
well begun reformations; instead of going forward, they have looked back,
and even sunk below the standard of the first reformers.

And those who will be the instruments to labour for a reformation in this degenerate age,
must find a difference in their trials from the sons of the former morning;
they will be of a more severe and piercing kind.
Theirs were from the world, and such as might be expected;
our trials will chiefly arise from those under the same profession,
clothed with the spirit of this world, though under disguise.
God will divide in Jacob, and scatter in Israel,
before that reformation is brought about which he designs.

[.signed-section-signature]
Mary Peisley.

[.letter-heading]
LETTER 23.

[.salutation]
Dear Friend,

I Have received thy letter, with a copy of the application of to friends of L+++_______+++ s,
to be received into membership.
The person under notice hath my sympathy; I believe him joined to the living,
through the quickening virtue of the life-giving word,
and I pray for his complete formation, as a vessel meet for the Master`'s use.
Yet a secret jealousy affects me, that patience hath not as yet had its perfect work,
to lead him into all the depths of the Lord`'s preparing,
nor all the idols cast to the moles and to the bats.
My jealousy ariseth from the activity of disguised self,
which loves the splendid picture;
an easy purchase in comparison of the deep hid pearl of substantial truth.

We sorrowfully know there are amongst us traditional formalists,
having a name only by outward inheritance; yet there remains a worm Jacob, the feeble,
but faithful wrestler, whose life is hid with Christ in God;
who through the virtue of the sacred unction,
have not an absolute need of man`'s teaching,
but are gathered in spirit to the Lord`'s mountain,
where the Lord of Hosts maketh to all people a feast of fat things,
and where he destroys the face of the covering,
and the veil which is spread over all nations.

The testimony given to us, as a people, in various branches,
hath been a stone of stumbling and a rock of offence to many,
who have wished for our crown without our cross,
and have overlooked and despised the peculiarity of our testimony,
or rather the Lord`'s testimony through us.
The language, fashions, and customs of the world, though by many deemed indifferent,
are not so to us, but are a part of the growth of that lofty Lebanon,
which the day of the Lord is to come upon, as well as the cedars;
and when that day come?, it will burn as an oven, with prevailing heat,
and leave them neither root nor branch.
All who have entered into fellowship with us, by the baptism of Christ,
which is the right door of entrance,
have found it to be their duty to attend to these testimonies, not from imitation,
but from conviction of their propriety.
We might have many preachers break in upon us,
were we at liberty to admit them upon the bottom of general speculative truth,
without their coming to the unity of the spirit.

How far the person concerned may have come into this testimony I know not;
but this I have observed,
that many of other societies rather revile than approve this peculiar dispensation,
(which the longer I live, the clearer I see to be from heaven,) against all carnality,
whether in obvious evil, or more concealed in the walks of formality,
or more refined and fallacious in the outward courts of the temple.

I take notice of a passage in the letter of +++_________+++,
expressing "`that the life begins to send up fresh sap into my dead branches,
the blind in me begins to see, the deaf to hear, and the dumb to speak.`"
This appears to me to be the truth, and a strong description of an infantile state,
not grown up into the capacity of preaching the gospel of salvation.
The forty days retreat into the desert, previous to the ministry of the holy Jesus,
seems to me not fully accomplished.
However, I feel much for him, I love him,
and wish to give him the right hand of fellowship in the Lord Jesus:
oh! that he may endure the Lord`'s preparing day,
that he may come out of the house of bondage clear,
and unmixed with any of the things which veil the beauty of the Lord`'s workmanship.

I hope friends will be tender towards him; yet for his own good,
and for the sake of the testimony, that they will be firm and steady,
this will be beneficial to him, if he ever comes in at the right door.
I recommend friends and the person concerned, to the great minister of the sanctuary,
that in his council and wisdom all may move,
and the precious unity of the one eternal spirit may be
known to run down to the nethermost skirts of their garments.

I am thy affectionate friend in deep travail for Zion`'s welfare,
that none who love her may fail of the salvation, which is within her gates.

[.signed-section-signature]
Samuel Fothergill.
