== Preface.

The many pious sentiments contained in these Letters,
(which were not written with any view of their being made public) shew the love
and disinterested friendship which subsisted between our friends in former times,
and which remains with many of the present time,
whose minds are influenced by the same good spirit,
and brought to seek after an heavenly inheritance,
as followers of their great Lord and Master Jesus Christ, in a path of tribulation,
in which all his people have to walk: such are united in a bond,
which neither troubles from without, nor trials and exercises from within,
nor bodily separation, can dissolve.

Though there are not many left who were personally acquainted with some of the writers,
their memory is sweet, on account of their great and good qualifications;
they having been eminently gifted for service in the church.

The Editor is induced to promote the publication of the work,
from a hope it may tend to encourage some poor travellers,
in their passage through the difficult journey of this life.
There is likewise a pleasure in collecting the remains of those whom we loved and esteemed,
that their memory may be preserved from oblivion.

As many of the letters contained in this and a former
volume are of our late valued friend Richard Shackleton,
it is thought not improper to insert some short memoirs relating to him,
taken from the testimony of the meeting to which he belonged in Ireland.
He was also well known and esteemed by many of his friends in England,
from his frequent attendance of the yearly meeting in London; where his service,
as an elder in the church, and one devoted to the service of truth, was very conspicuous.

It appears by the account given of him in this testimony,
that he was the only son of Abraham and Margaret Shackleton, of Ballitore, in Ireland,
where he was born on the 28th of seventh month, 1726.
Discovering early an inclination for learning,
his father had him instructed in what was thought necessary
to qualify him for the business of a schoolmaster.

Some account of the visitations of divine love extended to him,
is found in a letter written by him to a friend, as follows:

"`God Almighty visited me with a sense of his goodness in the early part of my life;
as early as I have any remembrance of.
He graciously renewed the same divine influence upon
my soul at various seasons of my childhood,
and more advanced youth.
This sense and savour was everything needful to me; it was knowledge enough,
strength enough, joy and comfort in abundance;
whilst in possession of this I wanted nothing.
But temptations Suited to my taste and disposition were thrown in my way;
puerile amusements, reading unprofitable vain books were spread before me,
and I was taken in the snare.
When the heart gave its preference to these gratifications, the heavenly guest withdrew,
and would not reside with such rivals: yet good and gracious was the Lord;
who notwithstanding my unfaithfulness visited again;
and as I opened the door of my heart,
(or rather he helped me to open it by his spirit) he came in with the power of his judgments,
by his operative word; and the pain attending burned up the chaffy combustible nature;
so I experienced him to be not only a jealous God, but a consuming fire.
Thus, with alternate visits and conflicts,
I went on till I grew to a more advanced stage of youth;
then the subtile nets of worldly wisdom, and the snares of youthful lusts,
proved too strong for me, and I was carried down the stream of natural inclination.

"`But being arrived at manhood, and about to settle in life,
an high hand arrested me in my course, shewed me my state of alienation,
and the impossibility of making a happy progress without the Divine blessing.
So, in the sincerity of my heart, I obeyed the heavenly vision,
and became as a fool among my companions: I sought retirement,
and the company of them who companied with Jesus.
Many were the baptisms with which I was baptized in that day;
my exercise was also felt by the Lord`'s servants,
and there was a close fellowship between their spirits and mine.

"`Thus I have gone on to this day, with the same hunger and thirst,
not desiring any thing so much as the bread of life, for myself, and my dear friends,
companions in the same travail.`"

Though possessed of great natural abilities,
which were adorned with the gifts and graces of the spirit,
he did not value himself thereon; but steadily advanced in his pilgrimage,
bowed down under a sense of the numerous favours received at the divine hand.
To his most intimate friends he frequently enforced the necessity of humility,
as the only safe situation to be preserved in, fearing greatly lest he,
or those whom he loved, should be drawn from it.

From his cheerful disposition, which Was regulated by best wisdom,
he had much enjoyment of social and domestic comforts, with which he was greatly blessed.
He was a kind husband, a tender and careful father; a good neighbour, liberal,
and generous,
particularly a good example in any thing relating to the wants of our society;
at the same time careful that the concerns of this
life should not too much occupy his thoughts.
Those who had opportunity of observing his conduct, have often perceived him,
retiring from company, to seek in secret, a renewal of spiritual strength: and,
we doubt not,
it was his concern to ask for divine counsel and
wisdom in the management of all his affairs.

He was in the practice of devoting a part of each evening to retirement,
which he recommended to his friends; the effect of such sacrifices were, at times,
obvious in him, his countenance indicating that he had been in the best of company.
The increase of genuine Christianity was the object he had in view;
for this his spirit was exercised; for this he was willing to be employed,
in any way consistent with Infinite Wisdom, in private, or more public labour.

He was exemplary in a diligent attendance of meetings,
appointed for the support of good order in the society;
and frequently attended the yearly meeting at London.
For many years with much propriety, he filled the weighty station of an elder.
As his dwelling was near the spring of divine refreshment,
he was often enabled to draw water for the help of others.
The welfare of his fellow creatures was very near his heart;
so that he would frequently express a deep travail
of spirit for the salvation of all mankind.

He mourned for the departure from ancient simplicity, obvious in our religious society;
yet he was consoled, in hope, that through suffering and patience,
the church would come forth from her wilderness state,
though he did not expect to see it, in his day.

He was often engaged in family visits,
and used to say that he esteemed it an honour to be allowed to tread these courts,
or to be employed in any little errand;
because these was abundance of soul-sustaining nourishment to be met with in this employ.
When broken in spirit among his friends,
and pouring forth the warm`' expressions of gratitude,
he would speak largely of the beauty of the house of God:
how its pavements shone with holiness,
and that the feet which trod therein should be holy.
He was well qualified to be a nursing father to those in the station of ministers,
who wanted a hand of help; such as these he encouraged to an humble, faithful,
diligent occupying with the divine gift.

It was his great concern for his beloved offspring,
that they might be preserved near to the source of all our blessings:
as they walked humbly before him, who is lord of earth as well as heaven,
he had no doubt but a sufficiency of the good things of this life would be granted them,
with a treasure in heaven that faileth not.

Being on a visit to the provincial school meeting at Mountmelick,
he was taken ill at the house of his friend John Gatchell,
which proved to be the conclusion of his time here.
During his illness he discovered no impatience, but lay Calm,
and spoke at times cheerfully to those about him.
He once said, "`I think it a favour that I feel a sympathy with the seed in suffering.`"
At another time he said, "`My friends, pray for me, that my patience fail not.`"

To some taking leave of him,
he recommended faithfulness and dedication to religious duties, which, he said,
would draw down the blessing on them, and their families: and he added,
"`What we profess is the truth, which our worthy predecessors were called to support,
by laying the axe to the root of the corrupt tree.`"

After an illness of about eight days, he quietly departed this life,
in the sixty-sixth year of his age;
and his remains were interred at Ballitore on the 30th of 8th month, 1792.

Much might be said concerning divers other friends,
who were writers of valuable letters in this collection;
but as their characters are sufficiently known from their writings,
which have been published, and otherwise, it is omitted.
It may be observed that the whole of letters which have been handed to the Editor,
from some of his kind friends, are not inserted,
as certain parts of them related to domestic affairs,
and could not be very interesting to the reader.

The letters could not easily be placed so as to succeed each other in the order of time,
but it is hoped no great inconvenience will be met with on this account.
Endeavours have been used not to insert any which have appeared in former publications;
but among so large a number as have been handed to the Editor, in manuscript,
it was found somewhat difficult to be avoided.

It was intended to have this collection of letters
confined to the foregoing or present century,
but as a sufficient number have not come to hand,
the Editor has inserted some valuable letters of former times,
which he hopes will prove acceptable to the reader.
