== Letters 62 &#8212; 70

[.letter-heading]
LETTER 62.

[.signed-section-context-open]
15th of Eighth Month, 1778.

This address may inform my friends at +++_________+++, that their kind hospitality,
when with them in times past, neither is nor will be forgotten,
although a correspondence, both personal and epistolary,
hath been of late much suspended.
My wife and self frequently remember them, and the pleasant town where they reside,
which there is little likelihood of my ever again reviewing, having been, for some years,
much indisposed in health.
Indeed, we are both so reduced,
that the time of our continuance here is not likely to be long,
and although there is a considerable disparity in years,
it is rather doubtful which may be the survivor.

Sojourning so near the valley of the shadow of death,
depression is the frequent companion of our spirits; nevertheless,
an humble enquiry is at times within us, "`Where is the Lord our maker,
who giveth songs in the night; who teacheth us more than the beasts of the earth;
and maketh us wiser than the fowls of heaven?`"

The state of religion among us hereaway, is likewise very low,
almost a daily declension appearing,
although we are generally preserved in a state of outward unity.
Our religious meetings are often very languid,
much more of the form than the power of godliness being prevalent; yet, I humbly hope,
a spiritual solemnity at seasons presides in them.
The shout of Israel`'s king is heard, and the goings forth of Jehovah,
who maketh a way in the sea, and a path in mighty waters, for the poor and afflicted,
are livingly witnessed.
It is very unfrequent that I have freedom to address my friends on this wise,
and often seem incapable of putting two words together properly,
my faculties being much debilitated by bodily infirmities.

I sincerely wish,
that the sufferings of the present time may conduce to our purification,
that having partaken of the cup of trembling, and passed through great tribulations,
our garments may be washed in the blood of the Lamb, who was slain for us;
to whom with the Father, through the eternal spirit, be glory ascribed,
now and forever.^
footnote:[This appears to be the excellent conclusion
of a correspondence of many years`' continuance;
the friends being all removed by death.]
I am, your affectionate friend,

[.signed-section-signature]
Samuel Scott.

[.letter-heading]
LETTER 63.

[.signed-section-context-open]
London, 11th Ninth month 1768

[.salutation]
My Esteemed Friend M. P.

Before I received thy letter thou wast brought to my remembrance,
and I thought that nearness of spirit and dear love that subsisted,
and I hoped was built on a foundation that I earnestly pray
may never be shaken in us (viz. the love of God,
begotten in us,
and shed abroad to all mankind) I say such friendship
demanded some expression of it from me,
but many avocations prevented,
so that thou mayest be assured my silence was not the effect of lessened affection.
And now, to come a little to the subject of thy letter,
in which thou callest on me to mourn thy afflicted situation, I have, as thou desired,
looked at it with some attention, and with a degree of sympathy, but not of mourning,
and cannot help wishing many thousand souls were thus under
the preparing forming hand of a gracious God,
who wills that we should this way come to the knowledge of the truth,
and be saved with an everlasting salvation.
For looking into the book of my little experience,
and indeed into the dealings of our common merciful Father with his children in all ages,
whom he has prepared for his service and glory,
I find they have been as tried vessels in the furnace of afflictions,
and if we look at the two most experienced servants of God, David and Paul,
we may observe none more tempted, tried, tossed, and afflicted,
insomuch that David`'s writings furnish us with very affecting instances of this sort,
to wit, the desertion, for a time, of God`'s spirit and presence;
and we sympathize when we hear his strong cries,
and see his long waiting for the returns of the Divine presence and favour; and Paul,
that eminent servant of the Lord, we find complaining of trials and temptations,
and in deaths oft, without were fightings, and within were fears;
and indeed who are exempt that are resolutely bent to serve the Lord; truly none:
for the Lord`'s servants at this very day, amongst many others,
are tried with deaths oft, as well as frequent temptations, when, as we think,
we are least able to encounter them.
I mean in the absence of our beloved; yet,
when he is pleased thus to try our faith and hope, he in his own time remembers mercy,
and administers a cup of consolation, so that we can say in degree, as the apostle did,
we are cast down, but not forsaken.
This is the hidden manna, that supported; this is the treasure in heaven,
sometimes out of sight, but not out of possession.
In the absence of the bridegroom, who can but mourn?
in such a state, I should not only die, but return again to earth, as David says:
but I remember the years of old,
when I had no solid pleasure in any of its delights and allurements,
and therefore I could not look that way for consolation;
and so have been kept from making other gods in the absence of our spiritual Moses:
in such seasons as these, it has been comfortably presented to my afflicted mind,
that when our Lord relates the parable of a certain man going into a far country,
before he went, he enjoins watchfulness, lest we lose that he left us in possession,
even his love.
Our chief business then is to watch in such seasons,
that no rival be admitted in his absence; but to be ready in a watchful posture,
waiting his return, that as soon as he knocks, we may be ready to let him in.

Keep then, my beloved, that which thou hast received, and let no man take thy crown,
which thou shalt obtain, if thou faintest not; and again remember,
though David was tried deeply, yet he believed,
that he who called him was able to perfect that which concerned him.
He remarks that he had fainted,
but that he believed and hoped to see the Lord in the land of the living.
I write to thee as one that is living and sensible; when thou thinks otherwise,
let me remark, that then thy state is not the state of the spiritually dead.
The dead, says one, know nothing; they have no remembrance of past things;
they forget they were washed; their spiritual faculties cease to act;
they can neither see, hear, fear, love, desire, or pray; whereas, thou dost all these,
otherwise thou couldest not witness what I am sensible
thou dost in this dispensation of trial.
I remember, in such seasons it has been said in my soul,
that I noted and dwelt on all my afflictions, but that I forgot the mercies of God,
which are many to the seed of Jacob.

My dear friend, thou many times mayest and must partake of the cup of affliction;
do not overlook the visits of the love of God, which at times, I will venture to say,
thou dost experience, though they may be like those of a way-faring man,
but for a short season.
Be thankful even for these favours, and let us say with the good old patriarch,
"`I am not worthy of thy mercies;`" and let us remember what the apostle asserts,
that after we have in degree done the manifested will of God,
we have need of patience to wait the fresh discoveries of it, and above all things,
to do it; for I have thought, when we have been helped to add to our faith, temperance,
and self-denial, we shall have need of patience.
I well know thy tried state, and sincerely sympathize with thee, but must desire,
when thou seest where help is laid, use thy degree of sight and faith,
though no more than a seed of mustard: occupy till he come,
who will increase it as thou dost so work.
Remember it will remove mountains.
O let us not fear what the worldly spirit saith, or acts against us;
our dear Lord was buffeted, spit on, hated, and became of no reputation,
taking on him the form of a servant.

I did not expect to write so much, being sensible whose hands thou art under.
If it may in the least contribute to thy encouragement,
and perseverance in the way which is cast up for thee, I shall rejoice: yea,
I do rejoice, in a sense that our gracious God will, in his time, establish, strengthen,
and confirm thee in it, to his praise and glory.
His indeed is the power, and to him, in every dispensation, be the glory.
Amen.

Farewell!
I tenderly salute thee in the tribulation and fellowship of the gospel.

[.signed-section-signature]
Sophia Hume.

[.letter-heading]
LETTER 64.

[.letter-heading]
Thomas Lloyd to John Eccles and wife.

[.signed-section-context-open]
Maesmawr, 12th month 1682.

[.salutation]
Loving Friends,

A Living remembrance of you, is and hath been often in my mind,
and a breathing in my soul for your welfare and prosperity in the riches
of that treasury which makes glad the hearts of the possessors thereof,
and which never perish in the using.
There is nothing here, you know full well,
that affords content and satisfaction to the soul
which hath the breath of immortality in it,
but the refreshment and nourishment which it receives from the Bread of Life,
which is daily administered to those who wait for it.

I have been somewhat indisposed as to my health these three weeks,
and my wife seemed even at her accounts`' end: but, however, do fully purpose,
in a few days, unless prevented by my wife`'s condition, or my own personal inability,
to visit thy afflicted wife, where I want not inclinations of warmth to further me.
In the interim,
wishing her the enjoyment of her soul and spirit in the
meek self-denying resignation and patience of the Holy Truth,
and to thyself increase of virtue in the faith of Jesus,

[.signed-section-closing]
I am your true well-wisher,

[.signed-section-signature]
Thomas Lloyd.

[.letter-heading]
LETTER 65.

[.letter-heading]
Mary Peisley to William Brown.

[.salutation]
My Dear Friend,

As I am not likely, according to thy request, and my inclination,
to have the satisfaction of seeing thee, I take this opportunity of saluting thee,
in that love which nearly united our spirits, at our first seeing each other; yea,
before I beheld thee with my natural eyes, a prayer was begotten in my soul,
that thou might be made an instrument of good to me,
from the sense of the need I had to be brought forward in the way of righteousness;
which petition I have cause to believe was heard and accepted of the great I AM;
for thou wast not only dipped into a sense of my state, and into near sympathy with me,
by which thou wast made a messenger of consolation to my distressed spirit,
but thy exemplary deportment, solid and edifying conversation,
thy sound and pertinent doctrine to the states of
the people I have seen thee labour amongst,
has incited me to use my weak endeavours for coming up faithfully
in the footsteps of the flocks of the companions of Christ;
and resolutions have been formed, which I trust, by the favour of heaven,
will be supported,
to practice greater degrees of mortification and self-denial than I have ever yet done;
for I see great occasion for it.

I write not this to exalt the creature, or flatter my friend,
but to magnify that grace by which thou art, what thou art,
and to contribute my mite to strengthen thy hands in the way of well-doing,
as I am led to believe the strongest have sometimes need of it;
but perhaps I only judge by myself, who am at times ready to faint in my mind,
from a fear that I shall never be made a conqueror
over those potent enemies which oppose my happiness;
for I have compared my immortal spirit to a kind of immaterial fire,
that is continually catching at or fastening upon something celestial or terrestrial;
and which ever it centers in, it may justly be called an inhabitant of,
and as natural a tendency it has to fix on earthly objects,
that are continually assailing it by the organs of my senses, as iron poised in air,
or cast into water, has to sink: but that power,
by which the prophet caused the axe to swim, in its efficacious operations on the soul,
may be compared to the touch of a loadstone on iron, which attracts it upward,
contrary to its nature; and as iron will lose this attraction,
and return to its natural position, so is my soul ready to sink,
when I wait not carefully for the renewings of that power,
by which we are translated from the kingdom of darkness to that of light:
but so painful and frequent are the operations of the sword of the spirit,
when it comes to sever my soul from the kingdom of this world,
for which it has a great aptitude,
and to divide asunder as between the joints and the marrow,
separating my mind from those things which by nature I am most closely attached to,
it makes me weary of this embodied state of imperfection,
wherein I am torn as between two contraries, heaven and earth,
so that I often long to be dissolved, and to be with Christ.

And though this desire seems to carry in it something laudable,
in as much as it shews my union with eternal excellency
to be stronger than all the ties of nature,
yet I am ready to fear this longing takes its rise
in part from the corrupt source of self-love,
which would lead me to seek an exemption from pain and trial,
before I have filled up in my body, that which is behind of the sufferings of Christ,
for myself and others: but I hope it is excusable,
as our holy pattern has left us the example; when he was about to partake of,
or had begun to taste, that bitter cup of sufferings, for the sins of the world,
he prayed earnestly, and repeatedly, that if it were possible it might pass from him,
but came to this noble result, which all his followers, who are so in reality,
must be brought to, "`Not my will, but thine be done.`"

Surely never did grace and nature exert themselves in so powerful a manner,
each striving for mastery, as in that awful hour,
when the salvation of mankind was at stake,
depending on the obedience of the Son to the Father;
when Christ was wounded for our transgressions, bruised for our iniquities,
and the chastisement of our peace was upon him.
Then might he well adopt that emphatic language, "`Now is my soul troubled,
and what shall I say?`"
As if he had been afraid to let that petition escape his lips, which nature,
sinking under the weight of inexpressible affliction, dictated,
as well befitting a son that had never offended his father, he said,
"`Save me from this hour;`" grace immediately recalls the request,
when he remembered the end of his coming, in that prepared body,
which was for our salvation, "`But for this cause came I to this hour.`"

What could be grievous to his manhood that he did not suffer?
At his birth, a manger, a place for beasts, was his receptacle;
nor did the ungrateful world afford him much better
through the course of his painful pilgrimage;
for though the foxes had holes, and the birds of the air had nests,
He had no place where to lay his head; set at nought by the then visible church,
and high professors of religion; a people that had received the oracles of God;
betrayed by one disciple, denied by another; forsaken by all,
and left to tread the wine press alone, in that most trying hour,
when the wonderful bloody sweat was produced, they slept, and were scattered from him,
when he came to suffer the painful ignominious death of the cross, between two thieves,
as a deceiver.
Many followed him crying, Hosannah, when he rode in triumph;
but now none are desirous to be his companions.
All his acquaintance,
even the women (the most tender by nature) that had followed him from Galilee,
stood a far off.
O, my soul, treasure up these things faithfully in thy remembrance,
with this additional consideration, that it was done in part for thy sake,
without which thou must irretrievably have been lost in the realms of woe,
a fugitive and a vagabond, driven from the face of thy God.
Rejoice then in thy tribulation,
and count it all joy when thou falls into divers temptations and trials,
for the refining of thy faith in Christ.

I hope thou wilt excuse my dwelling so long on this subject; of a truth,
it is a favourite theme, which I can never too much ponder; it is therefore needless,
and I recall the expression.
It will be a part of the employment of seraphic spirits, to all eternity,
to admire and celebrate the mysteries of redeeming love; saying with a loud voice,
"`Worthy is the Lamb that was slain, to receive power and wisdom, riches and strength.
Honour and blessing to him that sitteth upon the throne, and to the Lamb forever.`"

1t is time for me to draw towards a conclusion,
which I shall do with hearty desires for thy preservation every way,
and prosperity in the glorious work thou art engaged in,
hoping thou wilt remember me when it fares well with thee.

Please to let me hear from thee, if leisure and freedom permit;
but I shall leave that and all other things of this
kind to the direction of our great and good Master,
not laying thee under any other restraint but love, well knowing thy various engagements.

I am, with love, in which our family joins me, thy friend in the fellowship of the gospel,

[.signed-section-signature]
Mary Peisley.

[.letter-heading]
LETTER 66.

[.letter-heading]
An Epistle by Mary Smith.

[.letter-heading]
To my Brethren of the Ministry in Norfolk, tenderly Greeting.

[.signed-section-context-open]
From the Island of Jersey, 21st of 12th month 1750.

My dear brethren! called and chosen of God, appointed for a good work in your day,
see to your callings, gifts, and talents received, and let none come short of faith,
fully occupying to the glory and honour of him who hath indeed called
and honoured you with the abundant riches and treasure of his house,
viz. a dispensation of his gospel to preach to mankind.
Lift up your voice like trumpets, and be not dismayed,
though the enemy hath roared in your borders,
and the dragon hath cast forth his floods variously,
yet put on strength in the arm of the Lord, and behold your salvation near,
that shall be a bulwark in every trying time.
Oh! my brethren, my spirit hath been in deep travail for you, beloved in the work,
and fellow partakers of the heavenly gifts.
The call of the Lord through me is,
stand fast in the sweet liberty wherewith Christ hath once made you free,
and be not entangled again with the yoke of any bondage.
Suffer not, I beseech you,
the encumbrances and cares of this mutable and perishing life to choke the precious seed,
or in the least to obstruct your holy concern for God and his cause.
Remember, through unfaithfulness, Saul lost his kingdom and crown,
and became as one that had not been anointed with oil; the beauty of Israel was slain,
and fell upon the high places of Gilboa.
Have a care of high things, my brethren,
of accommodating yourselves or your houses to the world`'s inclinations, manners,
or spirit: though this might acquire you much favour, credit, and access with men,
literal carnal professors, or half-turned mongrel ones, yet it never can with God,
since he that is a friend of the world is an enemy to God,
is the express doctrine and testimony of the blessed apostle.
I long to have you men after God`'s own heart, Davids indeed, without blemish,
without re proof; so shall the goodly oil shine,
and the beauty of the Lamb`'s anointing be your excellent adorning.
The light of the Lord God will fill your dwellings,
and his blessing be upon all that appertains to you;
your families and little ones will reap the blessed benefit of your hearty obedience.

It was the complaint of old,
when the summons was sent to the called and chosen guests
who should have had the honour of composing that assembly,
that they made light of it, and went each his own way, one to his farm,
another to his merchandise, or in other words, one had purchased,
and he must see and possess; a second had bought yokes of oxen,
and he must needs prove them: a third had married a wife, and he would be excused.
I pray God, my brethren, it may not be so with you: but on the other hand, your ardour,
your readiness, and obedience to the divine call,
may really answer to that of the centurion`'s servants who needed but to say to one go,
and he goeth; to another come, and he cometh; and to a third do this, and he doeth it.
O! excellent fidelity and submission! no doubt it ingratiated
them in the love and affection of their Master,
and engaged him to their interests, who so much regarded his;
and shall the sons of heaven, the servants of the Lord of the whole earth be less noble,
less vigilant?
Surely nay; the Lord forbid it should be so.
Everlasting life, and the rewards of a blessed eternity,
is the portion and durable inheritance of all them that thus in
the house and service of their heavenly master and captain,
come up in their several calls and duties; but I am afraid some are saying, I go,
and go not.
I know there are good hearts among you, tender and true to the cause,
but fearfulness and diffidence on sundry occasions take hold,
and to favour this weakness, pleadings, and reasonings come in,
till the obstruction be comes as a flood, viz. Some there are who have been too forward,
too hasty, and too heady, and alas, what are they come to;
the name of the Lord is reproached on their account, and I, what shall I do?
the like dangers, the like temptations, may attend me, and I had rather die,
or live my days in obscurity, than hurt the blessed cause in such a manner,
or bring any reproach to Zion, the city of God`'s solemnity,
where the true citizens are pure, solemn, and orderly in their dwellings.
Ah, my mournful brethren, are these some times your pleadings,
are these your solitary cogitations and heart-tendering
moans that weigh you down as into the bottom of Jordan,
with the weight of the call and work upon your shoulders?
Gird up your loins, fear not; lift up your heads and arise;
bring up your grateful memorials, the goodly stones for building,
on which your feet have stood firm.
Now, I know it is agreeable to the apostles`' doctrine,
that the strong should bear with the weak, and if a brother commit a fault,
he that is spiritual should strive in the spirit of meekness to restore such an one,
and I hope-due care is taken in your respective meetings
to put this evangelical precept in practice;
nevertheless not to the prejudice or hazard of the good cause,
but see that your members are sound or safely restored.
Believe not mere formal appearances or literal acknowledgments,
for all is not gold that glitters; but bring offenders upon the proof:
"`The tree is known by its fruits; an evil tree will not bring forth good fruit,
nor a good tree evil fruit.`"

The rule is plain, my brethren, the matter need not be difficult,
only stand upon your guard,
having each "`his sword girt upon his thigh because
of fear in the night;`" you know what I mean,
and in the unalterable love of the covenant I salute you
in your several distinct orders and rule in the church,
and may here remind you of the subtle Gibeonites that deceived
good Joshua and the other ministers and elders:
lay not sudden hands upon any one,
but wait to know all in the light;--that will discover
you all conditions and states without partiality.
And where any poor tender one is found sincere and true, and the birth to be of God,
O nourish it, whether in rich or poor, high or low, bond or free, servant or master;
let due care be taken that no imprudent shyness or reserve be manifested to such,
for in so doing you will make them bleed, wound them in the tenderest part,
and they will mourn as between the porch and the altar.
Learn to know one another, my brethren; let brotherly love continue;
so shall you be shepherds indeed in Israel,
and the memorial of you will be sweet when your day`'s work here is done,
and like Moses and Joshua, you leave the tribes militant.
My heart is tendered, and my spirit contrited,
and in much brokenness and tears have you been brought to my remembrance,
even at seasons when I knew not but my natural life was hastening to its period,
and the days of my weary travail and pilgrimage were near at end;
then my bowels yearned towards you in the Lord,
and I looked over you my brethren with abundance of love and concern,
that you might all work while it is yet day,
while favour continues and some bodily health and strength be given;
before the night cometh and the shadows of the evening approach, favour be removed,
or bodily weakness clothe; ah! then no working.
The remembrance of you was very pleasant to me,
I received some of you deep in your dwellings,
and who I trust are as pillars in the house that shall go no more out.
Oh, methought I saw the holy writing,
the heavenly characters of the new name and of the new Jerusalem, the holy city,
and a motion followed these renewed sensations to tender you these lines.

I make no doubt, my brethren, but some of you, and I hope all,
will accept the love in which my heart was opened and enlarged to you in my weakness,
in which I felt endeared and fervent the love of your and my heavenly Father,
manifested in and through his beloved Son Jesus Christ, to whom be ascribed glory,
salvation and honour.
Amen. Your friend and sister, I hope, in the saints`' travail and tribulation,

[.signed-section-signature]
Mary Smith.

[.letter-heading]
LETTER 67.

[.letter-heading]
Sophia Hume to Hannah Hyam.

[.signed-section-context-open]
Philadelphia, 1st of 6th month 1748.

[.salutation]
My Dear Friend,

It is but a few days since I received thy kind and very acceptable letter,
dated the 13th of 12th month last, which came to hand after a very remarkable manner.
An inhabitant of this place, a friend`'s son, having been to Carolina,
on his return from thence took it up on a bank or shore near Carolina, with some others,
they being, as conjectured, thrown overboard by some vessel pursued by an enemy,
but whether in a conveyance to Carolina, or from thence to this city,
I have not been able to learn; however, I am pleased to have received it,
though in a torn and ragged, yet legible form,
and should gladly have received my daughter`'s also, though in the same condition,
but it is not a little satisfactory to me to hear by thine of her welfare,
as as of thine, and my dear family.

Thou hast, my dear friend,
nearly engaged me to thee on account of thy kind and sympathizing concern
for my protection and preservation by the good hand of our God,
whose mercies extend over all his works,
as well as what I am certain we are both interested in, to wit,
the cause and honour of our great Master,
and the real good and happiness of mankind universally.
The affinity and unity of spirit I witnessed on this
score soon after my happy acquaintance with thee,
and the time now occurs to me wherein after I had
one day made thee a visit (not a ceremonious one,
such as are commonly made by the world) but one wherein
I was edified and consolated in my spirit,
arising from, as I then thought, a sympathy of soul, both seeming to tend one way,
viz. To our great centre, God.
Upon my return home, and revolving in my mind something on this occasion,
I felt a secret joy and pleasure in thy friendship,
and I loved thee not so much for my own sake as for the sake of our dear Lord:
this pleasing reflection caused tears of joy to flow plentifully from my eyes:
this unity of spirit in the bond of peace and love, flowing from essential love itself,
even from God, "`for truly our fellowship is with the Father,
and with his Son Christ Jesus.`"
A stranger neither knows nor can intermeddle with this joy.
It is this commerce and union of souls, thou art sensible, my friend,
that only deserves or can justly claim the tender name and significant title of friendship:
for though Christians indeed love all mankind,
and are so far friends to all as to ardently desire and pray for their eternal happiness,
and would contribute all in their power to promote it,
as well as their temporal felicity,
yet the sacred and expressive name of friendship belongs
only to those whose souls are united by this holy cement,
the love of God;
for though there may be in persons all the requisites to
form and continue a common and selfish affection or friendship,
viz. similitude in natural tempers and dispositions, sympathies and antipathies,
affections and aversions, yet when this holy attraction and bond is wanting,
the friendship is incomplete and insipid.

And now, dear friend, I must tell thee that thy conjecture was not without foundation,
when thou apprehended that a concern superior to worldly interest (which
indeed had little or no share in my voyage) engaged me to quit so desirable
a situation (in such a hazardous and even perilous juncture),
wherein I thought myself happy in the enjoyment of many valuable friends,
with whom I had frequent and glorious opportunities of going
up to the house or into the presence of God,
in sweet company and fellowship,
where the divine and desirable communion of the heavenly bread and new wine of
the kingdom has been often dispensed to my hungering and thirsty soul,
both immediately from the divine hand, from whom every good and perfect gift comes,
and instrumentally from God`'s ministers;
for which kindness and favour of the Lord to my soul,
I have been made often and truly thankful.
Thus happy, exquisitely happy, was I,
as far as one engaged in the Christian warfare can be,
in the enjoyment in some degree of the favour of the Almighty,
which was better to me than life;
when a concern I had often had for the inhabitants of my
native country revived in my soul for their eternal happiness;
whither I was to return and abase myself by declaring what God had done for my soul,
and to call them from those things which I had been
by the great love and power of God redeemed from;
this discovery of the divine will gave me the greatest uneasiness I think I ever felt,
the greatest cross I ever had to bear, and which I long reasoned against,
and implored the Almighty if it was his will to remove the burden.
The time would fail to recount the various consultations of flesh and blood,
the difficulties and dangers laid in my way through this hard and trying dispensation;
at length all obstacles were removed by the Hand of Power,
and nothing now remained in my way but my unwillingness to become a fool,
to go and abase myself in my native country,
where I had long lived in pride and exaltation of mind,
and forgetfulness of God my Creator and preserver.
I fain would have compounded with the Almighty,
and though but a worm pleaded greatly to be excused thus:
Oh! that it might be granted me all my days to live in obscurity,
sequestered from all worldly enjoyments,
to weep day and night for the slain of the daughter of my native land;
I could have been content to have sat in silence,
and gone softly all my days for their sake:
but this was not the divine will concerning me,
the word was gone forth "`Obey my voice,`" and was not to return empty or void.
Here I was shewn that obedience is better than any sacrifice not prepared of God,
and to hearken to the voice of the Lord in this command,
than any offering I could offer in my own will,
for none but those of his own preparing and ordaining can possibly be acceptable to him.
Thus in the day of God`'s power, and by the assistance of his divine hand,
I was enabled to run through a troop of reasonings,
and by the strength of my God I have leaped over a wall of opposition in my own breast,
and as I before informed thee I found it my place and duty
to keep to meetings with those few who professed with me,
and at first met with some rude uncivil treatment,
yet we enjoyed our meetings the remaining time with pretty much quiet;
and some of the inhabitants of the town would now and then come and sit with us,
to whom my mouth was sometimes opened, in rehearsing what God had done for my soul.

In the course of my continuing there a concern was laid upon my mind to
write a short account of the dealings of the Lord to bring me to himself,
with an exhortation to the inhabitants,
and as I could not conveniently get it printed in
Carolina in the time I proposed to stay there,
I have brought it to Philadelphia, where I am told I can have it better done;
and the conveyance from hence being easy, I hope to send it soon.
This affair, and the want of a suitable opportunity, will detain me, I believe,
six weeks longer from my dear children and friends.
I am obliged to thee for thy care in soliciting for a few more books;
if they are not yet sent please to let it be deferred till I arrive.
I have dispersed many in South Carolina,
which were by many acceptably and thankfully received,
as well as those I have distributed in my journey from thence to Pennsylvania,
in a course of between eight and nine hundred miles;
wherein the goodness of the Almighty was very conspicuous in preserving me through many,
and to me unusual difficulties and straits, for which mercy,
as well as for innumerable others,
my soul renders to his protecting goodness unfeigned thanksgiving and high praises.
The particulars I must defer till I am conducted
by the same merciful hand to my friends and family,
when I shall be more at leisure to relate them than I am at present.
I am pleased to hear there is a suspension of arms between the contending powers,
though we fear Spain is not included in the treaty;
so it is possible we may not be quite out of danger from that quarter.
However,
that divine and omnipotent power who has so far kept me by his
mercy from falling into the hands of unreasonable men,
will, I trust, continue to protect me from temporal as well as spiritual enemies,
which are most dangerous, and therefore most to be feared and guarded against.

The time I am limited to, by the vessel`'s sailing this afternoon,
obliges me to draw to a conclusion,
and add no more but my tender love and regard to thee, and all my dear family,
remaining in true gospel love,

[.signed-section-context-open]
Thy real and affectionate friend,

[.signed-section-signature]
Sophia Hume.

[.letter-heading]
LETTER 68.

[.letter-heading]
From Mary Peisley to E. and T. Ecroyd.

[.signed-section-context-open]
Exeter, 26th of 6th month 1749.

[.salutation]
My Dear Friends,

I have been with my dear companion Mary Weston since the
yearly meeting through four of the southern counties;
a fine well cultivated country, whose fields seem to want no improvement,
being richly adorned with plentiful crops;
these with beautifully enamelled and fragrant pastures, with dumb eloquence,
abundantly praise and magnify the great Creator,
setting forth to every intelligent mind the magnificence of his power, wisdom, goodness,
bounty, and long-suffering, to a race of degenerate unworthy mortals,
whose tongues are filled with cursing and profaneness instead of
thanksgiving and praise for the unmerited favours of him,
who maketh his sun to rise on the evil and on the good,
and sendeth rain on the just and on the unjust.

So far as I am capable of discerning,
religion is at a very low ebb in this part of the
world amongst all ranks and societies of people.
Perhaps you will say I want charity, or upbraid me as Joseph did his brethren,
of coming to spy the nakedness of the land.
I tell you nay; but to buy food for the sore famine of the soul by obedience, which,
could I have had at home, I would not have come here.
Though I thus freely write my thoughts as they occur,
I have no doubt but I am known by you, as well as Joseph`'s brethren were by him,
though to many where I come I am unknown, and remain so.

I have far passed the limits of my letter, but feeling my heart enlarged in that love,
which neither length of time nor distance of place can extinguish or impair,
hope you will excuse the freedom,
and accept of salutation in the unchangeable truth in which I greet you with love unfeigned;
also to your father, mother, and family, with any other enquiring friends, as if named,
from your truly affectionate friend,

[.signed-section-signature]
Mary Peisley.

[.letter-heading]
LETTER 69.

[.letter-heading]
From Sophia Hume to Anthony Benezet, which was found unfinished after her decease.

[.salutation]
Beloved Friend,

I believe I may say, and say truly, I am not pleased with myself,
that I have not gratified thy request in that I did not reply earlier to thy last letter,
as I have the same reason thou alleged to me,
lest I should by any means make my friend uneasy;
but so far was thy letter from producing that effect,
that my heart rejoiced to find as heretofore,
thou through grace continues a stedfast and faithful sufferer for Christ and the gospel`'s
sake with the few names who amidst the revolting tribes of our Israel,
have not bowed their knee to Baal, neither kissed his image.
But on the other hand I cannot but mourn, nor remain unmoved,
while our tribes are in the wilderness,
surrounded by their enemies and taken captive at their wills;
for this my spiritual as well as natural bread hath been often mixed with tears.
I further lament to find both here and in the churches abroad,
that "`blindness in part hath happened to our Israel,`"
and the seeming unwillingness to be healed continuing,
makes me fear it will ere long prove both fatal and total;
but if Israel will not be gathered,
the Lord will cause the feet of his messengers to
be turned to such as will answer his call,
and prove more faithful to his laws and precepts,
for he never did nor ever will leave himself without
witnesses to his mighty power and adorable love,
which in his own time will cover the earth in a twofold
sense as the waters cover the sea,
for his determination is, "`He will be glorified on earth, as he is glorious in heaven.`"

Perhaps I am too anxious for this happy and glorious period;
I want to see the time when the mountain of the Lord`'s
house shall be established on the top of every exalted mountain,
which poor unhappy mortals have raised to their own destruction.
I want to see the people take the armour of God,
as it is graciously offered by the captain of our salvation,
and disposed to fight under his banner;
the weapons of salvation are mighty to the pulling down of strong
holds of sin and Satan and bringing into captivity every imagination
that exalts itself against the knowledge of God.
I am fearful I am fretting too much (rather let me say lamenting) because of evil doers;
though I am thankful to the keeper of Israel he preserves
me from being envious at the workers of iniquity;
so far from envying I mourn and lament their state,
and as Paul in the word of the Almighty commanded,
that "`prayer and supplication be made for all men,`" so in my mea sure
I am enabled to address the Father of Mercies with strong cries,
prayers, and many tears, that all men may be blessed with the knowledge of the truth,
and be saved from sin here, and the dreadful penalty due to it hereafter;
and as I have witnessed the terrors of the Lord for sin,
and upon deep repentance and amendment of life,
the peace and consolation of his blessed spirit for
obedience to the light and truth of his dear Son,
I would fain persuade men who have received the same grace by which we are saved,
to embrace his repeated merciful calls, to occupy therewith,
that they may not receive his grace in vain.

[.signed-section-signature]
Sophia Hume.

[.letter-heading]
LETTER 70.

[.letter-heading]
To +++_______+++

[.signed-section-context-open]
Redruth, 11th month 2nd, 1793.

[.salutation]
Dear Friend,

For with that epithet I hope I may address thee in the spiritual relationship,
having felt an affectionate sympathy with and regard for thee,
although our personal acquaintance has not been such
as might induce a very free expression of it.
But one of my chief joys in my debilitated state is,
the hearing or seeing that the children of the elect lady
(which the church of Christ may be styled) walk in the truth;
and a principal evidence of my continuing a living member of that church,
is my retaining a love to the brethren.
Indeed, I hope that this love is increased in my state of weakness,
and my desires are strong that the plantation of God may be so watered, weeded, pruned,
and watched over, as that its plants may flourish and be fruitful,
according to their kind, and the uses he assigns them.
That all the trees and plants in his extensive garden may rejoice together,
because they experience the advantage arising from
their sheltering each other from storms,
and expediting each other`'s growth,
although it may in some instances appear to diminish
the spreading of some plants of large magnitude,
and which also may be deeply rooted.
Such must at times evince their humility and true greatness by a willingness to be lopped,
that room may be made for young valuable plants growing near them, to expand.
Indeed, I see occasion for old trees, in the spiritual plantation, to be pruned,
as well as young ones, if they continue fruitful in the different seasons of life;
if they will not abide it,
barrenness and a contemptible appearance awaits them in the closing stage of life,
though they have been fruitful in the earlier periods of it.
May all the Lord`'s plants desire that he may turn his hand upon
them as often as he sees it needful for their preservation,
that they may produce well flavoured fruit in that
proportion which he knows their roots can bear.
Alas what great occasion is there for this pruning work in our highly favoured society.
How many wild shoots have been suffered to remain and grow,
even to the destruction of some promising trees,
shoots which have plenteously produced the fruits of the first nature,
although they may not have the appearance of the worst kind.
How heavy laden with fruits of worldly mindedness are some,
whose outward appearance is specious.
Pretended self-denial is in many instances self-gratification,
and their zeal is not according to knowledge.
These masked characters among us (it appears to me) do more hurt than open libertines;
they create a distrust of the whole body of our members,
brand us with the stigma of hypocrisy, and sorely wound the living remnant,
who mourn for offences they cannot remedy,
and lament the discouragement administered by them to tender infant plants in our garden.

But what saith the divine inspector to those who
see and lament the state of these burdensome members?
"`Take heed to yourselves,`" and when your hearts and hands are cleansed,
arise and labour in my garden to remove such plants
as will not be restored to beauty and fruitfulness;
and wisely nurse and train up those who are willing to receive instruction;
endeavour to support the weak, to comfort the feeble-minded, reprove, exhort,
rebuke with all long-suffering and meekness.
Thus may you be instrumental to work a reformation,
and your spirits will be replenished with divine peace and love,
which will compensate for all labours, sufferings,
and the loss of every temporal blessing wherewith you may be tried.
It appears clear to me,
that if our living brethren and sisters who are not
called to labour publicly in word and doctrine,
solemnly attended to their share of this rectifying work,
it would tend to an increase of true spiritual unity and sympathy amongst us.
There are indeed but few experienced fathers whose minds are affectionately
exercised for the children`'s growth and preservation,
which is probably one cause why there are not more of the
rebellious children turned to the wisdom of the just.
Private judicious admonition and cautions are not duly administered,
or endeavours used to gather the youthful stragglers
under the sheltering wing of wise elders.
I am thankfully sensible, notwithstanding, that the Lord is at work amongst us,
and I believe he will work powerfully to the reducing of the wills
of some who have been educated in the profession of the truth,
to the obedience of sonship,
and others who have wandered upon the mountains will become inhabitants of the valleys,
and be settled under the government of Israel`'s Shepherd.

But even such as are seeking the way to Zion,
and are earnestly desirous to be everlastingly united to the Lord and his people,
need much attention and help; they have much to leave behind,
and many discouragements to encounter;
and I think I have seen that if Friends watched over
such as are looking towards us in wisdom,
with a desire to be helpers of their faith,
and endeavoured by honest labour to rectify their errors and defects,
more of these might be brought forward, and in time become an additional strength to us.
I had no view of penning the foregoing sentiments when I began to write to thee,
but finding an inclination to reply to thy acceptable letter of the 10th ult.,
I have ventured to communicate them, in hope that if they meet thy own,
it may tend to strengthen thy resolution to attend to thy share
of any part of the work divine wisdom may assign thee in his church.
It has pleased him to deprive thee of one of his most valuable temporal blessings;
may it tend to thy enlargement in spiritual gifts, and increase of the highest enjoyment.

I observe thy remark of the probability of this nation
sharing in a greater degree than it has yet done,
of the cup of trembling, of which a neighbouring one drinks so deeply;
as a religious body called to peace, we should study to promote it,
and how we may edify not only one another,
but those also who may differ from us in religious profession;
exampling them how they ought to demean themselves
consistent with the gospel of the Prince of Peace;
and if suffering be our lot, either for our testimony of a good conscience,
or in sharing the calamities wherewith the nation may be visited,
to seek for strength to bear them consistent with the dignity of our high, holy,
and peaceable profession.

Had thy business led thee this way,
I should have been pleased to have seen thee and
conversed with thee in the love and freedom of truth.
I am visited by some valuable friends,
yet at times conclude myself a solitary afflicted widow,
increasing in bodily infirmities,
and able to do but little to promote the cause of righteousness.
He who judgeth righteously only knows the cause of my late great affliction,
whereto my most affectionate friends were in a great measure blind.
May the dispensation of his mercy and judgment be so sanctified
to my spirit as to prepare it for admittance into his kingdom
when dislodged from this decrepit and much afflicted tabernacle.

[.signed-section-closing]
Thy affectionate friend,

[.signed-section-signature]
Catharine Phillips.
