== Preface.

It is thought that the friendly and familiar letters which are here collected,
would not only be instructive and pleasant to those of the
same religious society with the writers of them,
but might tend to show the disposition and views of this Society,
better than a treatise written purposely in the defence
of the principles professed by it.

The reader will perceive an unfeigned love and affection
to have prevailed in the minds of the writers,
one towards another;
and that their principal view was to promote the best interests of their friends.
It will be seen also, that in thus expressing their sentiments on religious subjects,
without any expectation of having them made public,
they agree in all the essential principles of the
religion of their great Lord and Master Jesus Christ,
in whom alone their hope of salvation was placed.
It is true, they more insist upon the practice of piety and a virtuous conduct,
than upon speculative views of the Truth, or ceremonial institutions;
which may be helpful to those who use them conscientiously,
but are not to be esteemed essential to our happiness.

Though it is not usual with those of the Society of which
the writers of the following letters were members,
to express the names of God and Christ so frequently in their writings and conversations,
as some other religiously disposed persons, it proceeds not from any doubt,
or disbelief in their minds, concerning the great truths of the Christian religion.
They fully believe what is said in the Holy Scriptures
of the miraculous conception of Jesus Christ,
our Lord; his sufferings, and death on the cross, his resurrection and ascension;
as also his mediation, and intercession with the Father for lost man; and,
that there is no salvation but in and through him.
They desire to think upon these awful truths with great reverence,
but are cautious of making them a topic of common conversation,
lest their weight and importance should be lessened;
at the same time they approve of religious conversation,
with a due regard to the subject, and sense of their own weakness,
and of the need they have of wisdom to direct their speech,
lest they should touch sacred things as with unhallowed hands.

It may be remarked that though they do not use those ceremonies which
some professors of the Christian religion seem to think necessary to retain,
esteeming them not essential,
and as being liable to abuse by too great a stress being placed upon them,
to the neglect of the more vital part of religion;
yet they desire to be united to the living body of Christ,
which consists of members distinguished by various names and professions,
and dispersed through different parts of the earth.
These they desire to embrace, as brethren in Christ;
partakers of the same excellent privileges,
of which all the children of the one universal Parent, and the one Saviour partake.

It was found difficult to place the letters in the
order of time in which they were written,
but it may be observed, they are all of the last century,
and some of them of very late date.
Many extracts from letters of our late much esteemed
friends John Rutty and Richard Shackleton,
of Ireland, are introduced, which contain such sentiments on religious subjects, as,
it is thought, will be very acceptable to the reader.
