== Letters XVII &mdash; XXIV

LETTER XVII.

1st month 24th, 1758.

I received your last letter just as I had engaged
to accompany a friend to two adjacent country meetings,
and therefore Could give it but a cursory reading: but after some days interruption,
upon giving it a second review, my heart was comfortably affected,
and my eye filled with tears of joy! as my faith is further strengthened and confirmed,
that though you are cast down, the Lord has not left nor forsaken you,
neither will he leave you to the will of your enemy,
though he is permitted to try you in a near manner:
he shall not prevail against you as you keeps the faith,
though small as a grain of mustard seed, by this you will be enabled to resist,
and be made more than conqueror; for I believe the Lord of compassion will increase it,
as you improves the small degree,
so that it will work powerfully in your soul by love unfeigned,
to the thorough refining of body, soul and spirit; to the bringing into subjection,
and putting all things under his feet,
whose right it is to reign sovereign in our hearts.

I know this work will so reduce our spirits that we shall
indeed be willing to become spectacles to the world,
to angels, and to men, even a derision to those who are called by the name of the Lord;
who nevertheless are eating their own bread, and wearing their own apparel,
gratifying their sensual appetites in whatever their souls lust after.
As this is the lamentable state of many in our society,
I plainly see the faithful in Israel are, and will be engaged to call louder than ever,
and in a more conspicuous mariner to bear witness to the truth, as it really is,
in the humble and lowly Jesus.
The Lord is working in a secret manner, in the hearts of some of his servants:
who are ready to question, why it is thus with me,
why is it necessary that I should be so reduced,
and clothed with so great a degree of humility, and self-denial?
it is in order not only that we may be ensamples to the flock,
and properly prepared and qualified to take the oversight thereof;
but this work of the Lord (which in the eyes of some is marvellous),
is further to disentangle our affections from all visibles,
and that we may serve him without distraction;
and come up more fully to the help of the Lord, in his great work,
which he has put on the wheels; which are clogged at present, for lack of skilful, able,
and clean hands to set them in motion.

Therefore, as you are one of those whom the Lord has chosen and appointed,
to repair the breaches in the walls of our Zion; keep, as much as possible,
in a watching, waiting posture; as you know not how soon your Lord will return and say,
it is enough! release you from your prison house, and reinstate you in your office:
I believe a renewed call will go forth to the willing-hearted in Israel,
to such as are willing to be renewed in the spirit of their minds by deep baptism:
to these, I believe,
there will be a renewed call to visit the seed (which
to our sorrow is the least of all seeds) in prison,
in families;
for in our assemblies too many are unwilling to come under the baptizing power of truth,
will not touch the burden of the Lord, as declared by his servants,
with one of their fingers; but are laying it on the shoulders of their neighbour,
saying this is applicable to such or such.
Some are preparing, by the hand of our God, to be as saviours on Mount Zion!
In several ways, is God working to restore our poor society to its primitive allegiance;
some will be again called to search the camp, not only family by family,
but the husband apart, and the wife apart, the son apart, and the daughter apart,
and in the authority of truth will be enabled to say, You are the man.
When you therefore feel the call renewed to minister, publicly or privately,
do not make excuse, and say I am not yet fit, I am of unclean lips,
for God can suddenly change! in the twinkling of an eye
the corruptible have been helped to put on incorruption,
and the mortal immortality; and the saying has been triumphantly witnessed, "`O Death,
where is your sting?
O Grave, where is your victory?
Blessed be our God, who gives us the victory!`"
Such a sudden and happy change has been known in a meeting,
when the party has gone for a long time,
without witnessing what had been earnestly panted after.
Remember, if the Lord call again to that service, he either sees you fit,
or will make you so as you abide his preparing hand.
And also if the Lord call you not to an outward abstinence, eat then your natural bread,
though it be mingled with tears: and do not strengthen the bands of the enemy,
by weakening your body, through an improper abstinence from your temporal food.
Receive likewise with humble gratitude, that portion of spiritual sustenance, which,
I am sure, the Lord is daily administering to you,
till he is pleased to feed you more plentifully with
the dainties! which sometimes are withheld,
till we have girded ourselves, and served our Lord,
and then he is pleased that we should eat and drink; it being, in the mean time,
our food and drink to do his will.
And now my friend, I would wish you to bear in mind the inexpressible favour of our God,
who affords light to see your needs, and strength to cry mightily to him for relief:
in such a state, my soul has been bowed, and made to worship at his footstool; in that,
he vouchsafed the sense of need, and ability to beg a supply,
and humbly to wait till he saw fit to answer:
I since knew this ability could be no less than the favour of God,
and the way to the Father;
to whom no man can come unless drawn by the spirit of his son Jesus Christ.

Well then, my dear friend, be not cast down above measure,
since so many favourable circumstances attend you;
bear in mind the blessing annexed to such as endure suffering, and temptation:
among many which I have experienced,
that of declining an attendance on the worship of the Supreme Being,
has been often laid in my way by the suggestion of the enemy,
to lead me further out of the way of my duty,
and by persuading me to add one error to another, make the return more difficult,
first tempting, and then upbraiding with the temptation.
But I have considered that however circumstanced our minds may be,
it is no reasonable excuse for declining the attendance of meeting;
if they want to be rectified and stayed,
the greater need of presenting our bodies in the place of outward gathering,
to put ourselves in the way, with our brethren,
of being inwardly gathered to the Shiloh of our God; who, in his mercy,
may remember our low state of poverty, and may prepare an offering in our spirits;
a living sacrifice, acceptable to himself: I say, who knows but this may be the case:
therefore let us not give way to the enemy,
instead of relieving the malady by absenting ourselves
from the place appointed for religious worship,
we shall but increase it, and lead into a greater degree of darkness:
as I was helped to persist in the way of duty in this respect,
I was sometimes favoured with a glimpse of that countenance,
which is more precious and desirable to a few, than the increase of any worldly treasure.
And now I am speaking of temptations, I would beseech you,
when the enemy presents objects of thought which your soul ever abhorred,
do not stop to reason with flesh and blood, or dispute with the tempter, nor,
as I have too much done, dwell upon and brood over the temptation: for when I did,
the more frequently, and with greater strength, were his assaults renewed;
terrifying my spirit, and affecting me with horror and confusion;
and would have persuaded me, I had joined the temptation,
and committed the sins I even should have abhorred, when I was, almost, his vassal,
and taken captive at his will.
But let me not here forget to commemorate the mercies of our God:
who would frequently interpose, and bring many comfortable scriptures to my view, and,
with them, this encouraging reflection, that it was no sin to be tempted;
and notwithstanding the charge of the adversary against me, that I had admitted him,
in this or the other presentation, the Lord was pleased to encourage me still to resist,
by letting me see, though he had approached as far as the door,
he had not gained an entrance;
and even the door-posts should be sprinkled with the blood of the Lamb,
which was slain from the foundation of the world, for returning repenting prodigals.
At length, I was mercifully instructed,
and helped to pass by the temptation or presentation without much notice, deliberation,
or consideration about it, but to depend wholly on the mercy of God,
and look only to him for salvation in the hour and power of darkness; since which,
his temptations have not been so frequent, nor his presentations so terrifying.
Nevertheless, to be wholly exempt from trials and besetments of this sort,
is what we are by no means to expect; while our spirits are connected with these bodies,
and we remain in a state of probation, it must be so;
and according to the nature of the two kingdoms of Christ and Antichrist,
a continual warfare must be maintained against the invasions of the power of darkness;
which, that you and I may be enabled to do, is the earnest petition of my spirit.

To explain a little what I meant by the sin unto death; I apprehend, it is of that sort,
or nature, that the apostle John signifies, is not to be prayed for;
and is the state of one who has made shipwreck of faith, and a good conscience;
who not only rebels against the Spirit of Christ, but sins wilfully and stubbornly;
saying, as the Israelites did of old, when arrived to a high pitch of obduracy,
We will do so, and so: we will bake cakes, burn incense,
and even pour out drink-offerings to the queen of heaven I We will not hear, said they,
when the Lord spoke to them in their prosperity; and as for the words,
which the prophets spoke to them, in the name of the Lord, they say,
We will not hearken unto them; but will certainly do whatsoever goes out of our mouth;
in such a case as this, people are passing on, adding sin to sin,
till they arrive at a state, in which the Lord, in his justice,
leaves them to their own delusions.

But, my dear friend, the Lord has not thus dealt with you and me; because,
he that is omniscient, saw and sees our sliding aside;
our wandering a little out of the way, was not the effect of stubbornness,
nor had we offended willingly, but through inadvertency and unwatchfulness:
in this situation, if any man sin, we have an advocate with the Father,
even Christ Jesus the righteous;
a blessed and glorious privilege! also prayers and intercessions
are made by the brethren to the throne of grace,
according to the will of God: an humbling and comfortable reflection,
that we were not dead in trespasses; but we feel remorse for the same, and are saying,
in deep contrition of soul, to us belong blushing and confusion of face;
but blessed be our God, to him belongs mercy and forgiveness; as he himself declares,
when the sinner forsakes his evil ways,
with a full purpose of heart to cleave close to him,
he will give us our daily spiritual bread.

I say, in the midst of the multitude of my affliction, and perplexing thoughts,
this was a comfort that my disobedience was not wilful.
Yet so sensible was I that I must be again redeemed through judgment,
that I was made willing not only to kiss the rod, but to desire to be fed with it.
I rejoiced to feel the chastising hand of our gracious Father,
which was both rod and staff,
as it afforded me comfortable hopes of a future inheritance,
and that I was not cut off as illegitimate:
but that after I had suffered according to the will of God,
he might again restore me to a place in his house;
if not yet as a son to sit at his table, and partake of his dainties,
at least as a hired servant, to receive food convenient and sufficient for me;
for if we are but favoured to be admitted into his house, and service, it is enough,
the lowest seat and meanest office is worth all we can do and suffer to obtain it.

Sophia Hume.

LETTER XVIII.

In the fellowship of true and unfeigned love,
that unites the hearts of the faithful in a joint communion one with another,
do I dearly salute you; even that communion which begets a sympathy in spirit,
so as to partake, in some degree, of the state of each other, as members of one body,
in the mystery that the world knows not of:
for by this communion the members are not insensible of the state of one another,
that if one member suffers, the others suffer with it: and if one rejoice, or abound,
the rest are rejoiced by a degree of the same abounding love.
Thus help is communicated without partiality,
according to the proportion of that love that is boundless, proceeding from God,
through Jesus Christ, and centering in the same eternal oneness.

If I may be so qualified as to be helpful to you in this, it will give me great pleasure,
and judging also that I have had experience of various
states and conditions in a Christian life,
and the manner of dealing of the Lord with his people, I have learned in the deeps,
and in the silence of all fleshly reasoning, in the stillness and quiet,
where the enemy approaches not, to cry out, in admiration, with the prophet,
How unsearchable are your judgments, O Lord, and your ways,
past finding out! yet there is often a long time of suffering in hunger and thirst,
in nakedness and distress, before we can come here, to stillness;
to the intent that God Almighty, out of his infinite wisdom,
may manifest his own arm of power, and bring deliverance,
sometimes without any means of our own proposing.
For I have often observed, that he reserves entirely to himself the greatest deliverance;
yet not always so, as not to make use of any means at all, but those means appear,
on a just view, to have something in them so extraordinary and providential,
as shows them to be the effect of the first moving cause:
the instrument is in some sort overlooked,
though it is in sincerity acknowledged as the bounty
of heaven in the dispensation of his providence;
yet the acknowledgment does not terminate in the means or instrument,
but arises in pure breathings as a divine flame to the source and fountain of all mercies.
Thus his judgments are to human attainments, unsearchable, and his ways,
though ways that lead to peace, past finding out; when he corrects in his judgments,
it is not in sore displeasure, lest he should bring us to nothing:
but by the chastisements, as of a most merciful Father,
he urges and draws a greater degree of obedience from his children, for it is in love.
Our time then is to be still, to bear all things, to endure all things,
to rejoice in all things that he shall lay upon us,
as knowing that thereby we may procure to ourselves the most lasting peace,
by being restored again to his favour.
And, O how happy are all those that can so quietly submit in all things!
In order thereunto,
let us consider that they are distributed to mankind in his abundant wisdom and counsel.

But there is another sort of affliction, that is as bonds and imprisonments,
as lying nights and days in the deeps; more afflicting than bonds outwardly,
and the cause entirely hid from us; wherein there is striving between life and death,
between hope and despair; longing to be delivered, with short glimpses of,
if at all beholding, the deliverer! at times crying out with the prophet,
"`You have covered yourself with a cloud, that our prayers should not pass through.`"
There appears no mediator, no high priest before the throne of God.
He forever seems to hide his blessed countenance, and his absence is our greatest pain,
for being deprived of his presence all things else yield no relief.
O then how does the soul tremble! how does the heart faint! the tears are dried up,
no vent then seems to ease the anguish of the soul.

We are ready to say, with Job, "`O that my griefs were thoroughly weighed,
and my calamities put in the balance together,
for then would it appear heavier than the sand of the sea,
therefore my words are swallowed up.`"

O that I could feel so much softness in my heart, as might affect my eyes,
then should I have hope! if it were the effect of contrition or consolation,
it would yield me equal joy, that my Redeemer had not quite forsaken me,
nor given me up to the rage of my most cruel enemy, but still has mercy for me in store.
Thus lamenting days and nights; when it is day, we wish for night,
and when it is night we desire day; fear to be alone, fear to be in company;
we can neither read nor hear with attention,
nor meditate on God with any composed devotion.
Yet let me tell you, my friend, from experience, (as having waded through these,
and more afflictions, that are not to be expressed) if such distress is now, or has been,
on you, God is near at hand, to bear up your drooping soul; he is ever underneath,
and round about, though for a while you see him not.

I have always found, that after such times he has appeared with more lustre and glory,
to teach us not to attribute anything to ourselves;
nor fix our thoughts on anything less than his omnipotency.
For he that has made the sea, and prescribed bounds to the waves thereof: saying,
hitherto shall you come and no further, and here shall your proud waves be stayed,
is not to be limited by finite creatures, as the best of men are.

And though the sea may dash against the shore, and threaten an inundation,
it cannot exceed its bounds but by the direction,
or at least high sufferance of Almighty wisdom;
who is not less in regard to his children`'s wellbeing,
than wise in his counsels to frustrate the proudest attempts of the wicked.
Wherefore, by having an eye single to him in all times of tossings,
and fluctuations of the mind, proceeding from what cause they may,
is the most proper method to attain to a settled state and condition.

When the disciples of our Lord were tossed on the sea, their help was near;
though to them Jesus seemed to be asleep and undisturbed,
yet his inward apprehension as God, was awake and ready to help them at their call;
"`Master do you not care that we perish?`"
At which he arose, rebuked the wind, said to the sea, Peace, be still:
and the wind ceased, and there was a great calm;
the admiration of his disciples seemed to be raised more
in that signal deliverance than in any other miracle,
inasmuch as they were, at that time, the immediate objects of his mercy,
and partook of the blessing of his powerful word;
neither did they fail to return their acknowledgments, by saying,
What manner of a man is this, that even the wind and the seas obey him?

Thus is he near, when he seems to be most absent;
ready to help in every needful time of trouble,
as he is called upon in the least degree of faith;
settling and quieting the mind in his own time.
His deliverance conies sometimes entirely unexpected by the creature:
but whether it comes early or late in that deliverance,
there is a looking back with wonder and acknowledgment to God.
As Israel sang on the banks of the sea, saying, The Lord is glorious in holiness,
fearful in praises, doing wonders; or again, These are your wonderful works,
O Lord! my soul has been brought down to the borders of the pit,
and you have delivered it again from the destroyer,
and have once more set my feet in the just man`'s path, in the bright shining light,
that shall shine more and more unto the perfect day.
In those short intervals the soul gathers strength to ascend to its beloved,
and rejoices in her happy deliverance from bondage.

And it is agreeable to the experience of many that there is no
state that produces such convincing proof of the regard of heaven,
as that wherein we are reduced to poverty and want,
in such a manner as that there appears nothing but confusion:
the very brute animals seem in the more desirable condition: they rove idly unemployed,
and have their food prepared in season, and if they are slain,
death is to them an end of all their sorrows.
The trees, shrubs, and all the species of inanimate things,
seem to discover a greater beauty,
and display a livelier texture of their great original than we; these,
though they suffer decay in nature by the scythe of time,
and are soon reduced to the earth from which they sprung, yet suffer an insensible waste;
and as they are not sensible of pain, they neither can, nor need cry out for succour.
But man, the noblest part of God`'s creation,
made to adore and reverence the Supreme Being with sublime intellects,
is taught of God to trust in him, to wait upon him,
to be resigned to his will in all things,
and if at any time he is pleased to hide his face, it is in order to manifest his power,
and bring forth more lasting fruits of praise to himself,
and more honour and dignity to the creature, by virtue of his own prolific word.
For by death, life is perfected.
By staining the glory of this world, the glory of God is rendered conspicuous.
By seeing ourselves really as we are, we have a glimpse of what God is.
By beholding our own emptiness, we desire to partake of his fulness:
by feeling our own poverty, we desire his riches; by being hungry and thirsty,
we have a true relish of the bread and water of life;
by a real sense of our own unworthiness, we dare not murmur, if we receive nothing:
but in all states, with the holy apostle, learn to be content.
Thus God becomes all in all.
And thus it is necessary that we have a spiritual
assistance to distinguish times and seasons,
as they are in the hand of God; when we abound, not to be lifted up, when in poverty,
not to repine too much; when afflicted, that we pray,
and first seek for the spirit of grace and supplication
that we may be directed how and in what manner to pray.

For it is not always right that we should have what we most desire, as creatures,
but that which is most profitable for us as Christians, believers,
and followers of Christ,
who was a most perfect pattern of humility and self-denial while in the flesh.
And when near to offer up his life for the sins of the whole world,
and having an apprehension of the greatest agonies, he breathes, "`O my Father,
if it be possible, let this cup pass from me!`"
But as if he checked himself, added with submission and filial duty, "`Nevertheless,
not as I will, but as you will.`"

We have need to wait in stillness to be renewed with strength,
by virtue of the holy anointing, to know what to ask,
and temper our longings by a perfect submission; sometimes,
to ask no more than to be endued with patience and strength to endure the present affliction,
that it may terminate to our advantage, and acceptance to Almighty God.

At another time, when the days of captivity are ended,
and the seed which has been oppressed is set at liberty,
the soul breathes as in open air, and is enabled to ascend to the divine majesty,
with free supplication, and an earnest is, as it were,
resounding back with heavenly harmony, which gives a firm belief,
that our prayers are heard.

But when the emanations of this divine life are absent,
(which is not to be accounted strange) the enemy of man`'s
peace and happiness who waits all opportunities,
like a restless and indefatigable foe, to besiege,
and if possible to destroy and lay waste the whole city of God;
he is then ready to make his strongest attempts to shake the foundation.
But the foundation of God stands sure, having this seal, the Lord knows them that are his.

The enemy may tempt us,
and raise great disorders and fluctuations in the mind without any cause assigned;
but he that was a liar and murderer from the beginning, is so still;
and as he abode not in the truth,
his envy is raised more particularly against all those who strive to persevere in it.
Let us trust in God, who will not allow us to be tempted above that we are able to bear,
but will with the temptation also make a way to escape it.

My dear friend; though I seem to have exceeded the bounds of a letter,
I am obliged to confine my thoughts,
and can send you only a short abstract of what has presented
itself to my mind with a share of warmth and sweetness.
I shall add, it has been my humble petition to Almighty God,
that he may vouchsafe to draw nigh, with the visitations of his pure light,
and in mercy cause his brightness to appear,
by removing the cloud which hangs over the tabernacle,
and so far favour those who have no might of their own,
as to guard them with his own arm by day and night,
gently leading those that are with young, bearing them in his arms.

LETTER XIX.

Though time and strength seem to fail more fully to visit you in the exercise of that
part of the ministry which the Lord has been pleased graciously to bestow upon me,
yet I am glad and thankful for this opportunity of seeing
and conversing with my dear friends in this kingdom,
who are preserved a tender and zealous people, to the honour of God;
which renders my visit, under the many afflicting circumstances attending,
easy and profitable to me in the best things.
Nevertheless, it comes upon me to make some short remarks to you,
from a tender concern for the church`'s edification and not discouragement; and first,
in general, it is more than a little manifest,
there is a great declension of true love and tenderness among us, towards the Lord,
and one another; and in too many elders, both in respect to their own condition,
and the tuition of their children.
In many of the youth there appears little sense of truth;
but as some have already taken their flight, more seem to be upon the wing;
which in a word,
seems to lie much at the doors of such elders who have not kept their first love.
Is not blindness in part already happened to Israel,
through the subtle workings and aboundings of the mystery of iniquity,
and the prevalence of the god of this world; let us therefore,
as many as have the cause of truth at heart, offer our supplications,
with strong cries to the Lord, (as good Jacob did when the enemy was coming like a flood,
to destroy the heritage and seed of promise,) that he will be graciously pleased,
for his great name`'s sake, to turn the captivity of his people,
by the renewing of his powerful visitation on many;
to the searching and tendering of deceitful, hard and ungrateful hearts,
who cover and hide themselves as Adam did, after he had sinned;
but they cannot hide from the Lord, nor escape his judgments.
O how hard, cold, and unprofitable do our religious meetings often appear to be;
which have formerly been our greatest comfort and joy in the Lord, and in one another,
though at times silent, and attended with difficulty.
This is lamentable to the living, who have known it otherwise,
and sufficient proof there is a great declension among us.

Further, our Christian testimony against tithes,
which has cost us so much spoil of goods, and hard sufferings in person,
even unto the death of some to maintain,
seems now an insupportable burden to many professing the same faith; who,
by treachery and cowardly flight give it up, and surrender it to the enemy,
to the great affliction of many valiants in Israel; both on behalf of their condition,
who so do, and in that the burden lies heavier on the rest.
Such persisting will never prosper, but shall be made manifest, go where they may: yes,
although they should say in their hearts, we will go up to a land of peace and plenty,
where we shall see no war, nor hear the sound of the trumpet,
neither suffer the lack of bread.
How would such, who cannot suffer cheerfully for one branch of the testimony,
have stood in the days of our fathers?
As the prophet Jeremiah says, "`If you have run with the footmen,
and they have overcome you, how can you contend with horses?
and if in the land of peace, wherein you trust, they have wearied you,
then how will you do in the swelling of Jordan?`"

Again,
it is afflicting to consider how our Christian reputation
is stained in matters of meiim and ttium,
while we are the highest professing people.
Surely, the generality of the unhappy failures that have happened among us,
are through unfaithfulness and neglect of the divine principle of light and truth within,
as well as repeated advice and warning of tender concerned friends;
who have at heart the temporal and eternal happiness of the society.
I say, it is for lack of an obedient ear and steady attention thereunto,
which would produce faith in him that feeds the ravens, and clothes the lilies;
and has promised the necessary to his humble depending children,
giving sweet content therein: for he who murmurs at his little,
would be exalted in the enjoyment of much, but they who trust in the Lord,
shall not be confounded; neither shall they fall into disgrace on the one hand,
nor snares on the other.

Now, dear friends, the sense of these things is very afflicting to the faithful,
both ministers and others, who discern the sad signs of this time; are sound in judgment,
steady in love, strong in faith,
and are concerned to run to and fro as upon Zion`'s walls; visiting public meetings,
and private families; rising early,
and testifying faithfully what the counsel of the divine oracle is,
as far as known to them; and that unless there is a laying to heart,
and more fruit of righteousness, love to God,
and tenderness to the praise and glory of God, a sifting time will come,
and not to speak prophetically, is believed to be near, notwithstanding some may say,
"`Every vision fails, and the days are prolonged: but thus says the Lord,
the days are at hand, and the effect of every vision,`" (Ezek.
12.) for the abominations and daily profanations of the people,
and for the great declension of many among us.
For many are the awakening testimonies of this day, which are,
and have been delivered by the afflicted servants and handmaids of the Lord,
who go bowed down in painfulness and weariness.
But some are ready to say, The ministry is not what it has been.
It may be so with respect to particulars: but blessed be the Lord,
there is still a faithful, and free ministry: free from self-seeking,
free from partiality and deceit, in whom there is no straitness, but as says the apostle,
"`the straitness is in your own bowels;`" and considering
how great that straitness is in the hearts of many,
I am thankful that the true ministry is not yet shut up towards Israel,
and the stream of it turned other ways: many love to hear, but not to do,
yet the time is not come, wherein it is said, "`Let them alone.`"

O that this lethargy and sleep of death may be come
out of through speedy repentance and amendment;
else I believe the Lord will not continue long thus to expose his servants:
but the word of the Lord shall be precious, and many will say,
"`Blessed is he that comes in the name of the Lord.`"
A precious seed nevertheless is remaining in both elders and young men,
whom the Lord has blessed, and will preserve as in the hollow of his hand,
until his indignation be over-past: yes and his holy arm of power,
(stretched forth in wrath for the punishment of the
wicked) is also revealed for their salvation,
whose prayers and intercessions with the great and most merciful God,
have prevailed for prolonging his tender visitations, and sparing the nations,
even in a degree, as that of Abraham and Moses did: and I fully believe,
that although the church will suffer, and the nations be afflicted,
and not only the earth but the heavens also will be shaken,
and that there will be many pained hearts, and pale faces, yet afterwards,
the air will be clear, calm and temperate, the earth fruitful,
plenteous the dew of heaven, and great the harvest;
even after Jerusalem is purged and Zion has shaken herself from the dust of the earth,
and has put on her pure, and primitive garments of faith, love, zeal, simplicity,
temperance and moderation.
For I trust to die in the faith of this,
that the Lord will yet make his church an eternal excellency, the beauty of nations,
and the glory of the whole earth: whose foundations stand sure,
(though many slide therefrom,) other than which, believed in by us, shall never be laid:
that is, the light and manifestations of the spirit of Christ,
the true teacher and comforter, the infallible guide unto life and pease,
who promised to be with the faithful to the end of the world.

The sense of the life and virtue of this principle,
wherein stands our sweet communion and heavenly fellowship,
draws me towards you the chosen of the Lord, to bear his name;
notwithstanding I cannot but be thus plain.
To conclude, I declare my belief, the Lord waits to be gracious:
O therefore let all prepare to meet Him, by a diligent improvement of their own gifts:
therein wait with fear and reverence in all your meetings,
for the overshadowing of the pure power and tendering love;
therein act in truth`'s concerns with cheerfulness and success:
for the Lord Almighty will give a blessing,
(whose counsel and secrets are with them that fear him,)
even to the bringing to light the hidden abominations,
and discovering stumbling blocks: and to the comforting the weak, who have been offended,
and turned out of the way: to the reaching and tendering the youth, to the recovery,
at least of some backsliders, and poor lost sheep:
so will the church in general be comforted, her afflicted ministers relieved,
and the Lord over all glorified, who with his Son the Lamb, is worthy forever.

LETTER XX.

In the spring of immortal love I greet you, wishing your soul`'s welfare in Christ Jesus.

Beloved, with whom my soul has often been comforted;
it is in my mind to express to you the sense I have of the work to which we are called,
which is very weighty.
To be as the mouth of the Lord to an assembly;
and to be as the mouth of an assembly to the Lord, is a matter of great importance,
in which we have need to take care to behave ourselves wisely.

Ministers areas the watchmen spoken of in Scripture;
if they warned not the people faithfully in the word of the Lord,
he was to require the blood of the people at their hands.
If ministers are not faithful in the word of reconciliation,
the more will be their condemnation.

Now, as we ought to be faithful in the delivery of our testimony,
or as I may say the word of the Lord through us, so we ought to be watchful,
that we may not give entertainment to what is not the word of the Lord to his people;
we ought to take heed that we go not forth upon openings barely,
although they are witnessed in the life,
which may be designed for our own interest and edification.
As we abide in the wisdom of God, it will be clearly seen what we should join with,
and what refuse: what to communicate to others, and what to apply to ourselves.

And in our testimony let us keep to fresh openings;
even such as have the weight of the living word in them,
and be very careful that we lay not hold of former openings,
neither of our own nor others; lest it be like the manna which was gathered yesterday,
and lest we be guilty of stealing the word from others.

Above all things let us travail for life in meetings;
though there may be a dependance upon, and desire after, words in a meeting;
which we being sensible of are not to go forth with former openings,
and what we have treasured up in our memories of our own, or the openings of others,
thinking thereby to supply the service of a meeting.
This is but will-worship, and an offering which the living God will reject.
I have considered how it fared with Saul, who being pressed with difficulties, namely,
the camp of the Philistines near, and the people of Israel like to scatter,
the prophet Samuel being absent; in this strait Saul offers a sacrifice,
for which he was reproved by the prophet, who told him he had done foolishly,
and that his kingdom should not continue.
Here is an instance of the danger of forward offering,
although there was a seeming necessity for something to be done.
Let us bring the matter home to ourselves; let us not be hasty,
but keep close to the word of life;
and though the dependance of the people may be upon you,
and in all likelihood none to answer the service in a public way but yourself,
yet if the power of the Lord is not witnessed, and his word open not in you, venture not,
but wait in the patient suffering, for it will do no good.
Such reasonings as these may attend: here several have come in that are sober,
and well inclined, perhaps if a testimony was borne, they might receive benefit by it;
surely I may take liberty to tell them my own experience,
and how the Lord visited me in their state; it may have no evil effect,
though I am not constrained to do it; in answer to which I say,
the best of this sort is but will-worship, which finds no acceptance with God,
neither will it in any wise promote the work and service;
for the will of man must come to be laid in the dust,
before the will of God can be done by us.
We may plead excuse that it is done in a zeal for God and his truth;
but that will not do,
while the moving cause of our performance is too much in active self,
and the creaturely will.

Silent, painful, patient suffering in times of desertion,
will be much more acceptable to God and beneficial to the people,
and prove much more to our own peace, and inward strength.
O that we may keep to the power of God in all things; that, being seasoned therewith,
we may preach in our lives and conducts.
This will adorn our doctrine, beautify our souls,
and make us comely in the eyes of our beloved.

Great is the goodness and love of our God,
in that he has condescended to make known the riches of his free love to poor striplings;
choosing the weak, simple, and mean things in man`'s estimation, for his use and service;
O that we may feel the weight of his love herein,
so as to be humbly bowed before him into nothingness of self: that what we are,
we may really be by the power and grace of God.

I fear some rush into things hastily, without considering their weight and importance;
whereby their standing has been dangerous.
It is the life of religion that is a shelter from the heat, and a covert from the storms,
and as the shade of a mighty rock in a weary land.

LETTER XXI.

10th month 1760.

The relation I stand in to one of your little scholars,
binds me in duty to take all possible care, that she may be kept in infant innocence;
and instructed in every moral duty, as well as Christian virtue.
I took early care to instil into her tender mind,
a reverent and awful sense of the Supreme Being; the former,
as well as great legislator of all his creatures.

When amongst the moral and divine laws he enjoined his early church,
the following was not the least commandment (having a special penalty
annexed) "`You shall not take the name of the Lord your God in vain:
for the Lord will not hold him guiltless that takes his name in vain.`"

This injunction remaining in force upon all Christians,
I took care to put her in mind of it;
and whenever I observed her using expressions that in the
least by similitude of sound bordered upon it,
I always chid her for it: so that upon these admonitions, I kept her,
as often as I was with her, innocent of this evil which,
it is to be remarked with sorrow,
too many called Christians are not afraid to be in the daily commission of,
though they so often hear the third command repeated.

And now to come to the occasion of this address to you.
When my grand-daughter went from school sick of the measles, I was with her,
till she recovered.
But to my great surprise, in the course of her illness, the repetition of plain O Lord,
without disguise, came so often from her, that it afflicted me greatly;
as I began to fear my labour would prove in vain,
she being out of the way of my counsel and admonition.
I asked her how she got that habit of speech; she answered, the girls at school said so.

As it cannot be supposed that at your advanced age
the children should be always under your notice,
yet I hope you will give instructions to your assistants
to discountenance such an evil practice among the children.
We may remark it as a common proverb,
"`That manners make the man,`" and consequently the agreeable woman.
I do not mean a civil and becoming behaviour only,
though that is indispensably necessary towards forming either sex,
but a care is due to their morals, by observing and correcting their early passions;
I mean not by whipping children out of their foibles, but, by a proper authority,
subjecting their tempers, humours, and inclinations to pride,
and ill-nature and stubbornness.

I have no intention to give you offence by these remarks,
but am obliged to say thus much in point of duty.

Sophia Hume.

LETTER XXII.

7th month 1757.

It is four years since it pleased the Divine Being
to draw me in a manner (which is wonderful to me,
and which I cannot now comprehend) to draw me, I say, into a consideration of my state,
and repentance for my long backslidings,
and a desire for forgiveness and acceptance again.
In the infancy of those times, many were my sighs and tears,
but many were the promises which encouraged my perseverance in the path of judgment.
As I went on, I found the enemy of all good,
after having in vain assayed to cast me down below measure,
(by adding imaginary fuel to that of godly sorrow which works true repentance,)
endeavouring in the progress of my travel to elevate me too much,
by persuading me that now there was no necessity for so much mortification, self-denial,
and retiredness, as before.
And in this, to my shame, I will confess, he too often prevailed.
But through the tender mercy of the Father of mercies,
notwithstanding the working of the adversary upon a disposition naturally light, vain,
and inconstant, I have been preserved, if not always in the midst of the right path,
yet with my face always set that way.
And though instrumental helps do not affect me so much as formerly,
yet is my spirit often as much contrited as ever,
my heart as much enlarged in prayers and tears, and my desires after invisibles,
as strong as ever.
But, dear friend, here is my strait and difficulty,
that though I have as it were passed from the watchmen, yet still I find not him,
to my comfort, whom my soul loves; but the morning seems to be as far off,
as when I first perceived it was night;
and in this distress I am at times ready to cry out, Oh, will you never,
never appear! surely none have been so dealt with as I!
must I be the only one who seeks your face in vain?

One crumb, the smallest pittance, so it be the divine,
will suffice me! then am I brought into the deepest humiliation,
and ready to make covenant, that I will be anything or nothing,
so that I may be admitted to be one of this family.
O surely it is a matter of great difficulty to be re-admitted,
so that those who are in any degree favoured with an abode here,
had need to use all diligence to obtain a settlement and establishment,
that they may go no more out.

Richard Shackleton.

LETTER XXIII.

7th month 1752.

Though my ability is weak, my understanding and experience very little,
and my stability still less,
so that I am sure I am in a state which needs to receive advice and encouragement,
rather than give it; yet in my poor measure,
I am willing to do any little thing in my power for the good of my dear friends;
whom I sincerely love, for that cause, which more than all things,
I desire should prosper.
And therefore, dear cousin, I would invite you not to dainties,
for I have not for many years had any for myself;
but come along with me to a preparation and a capacity for receiving of them.
We must first be washed in the water of life before we can taste thereof.

The angel,
(the messenger of the covenant,) must be pleased first to descend and trouble the waters,
(our thoughts,
affections and desires,) then the lame must be washed therein before he can be healed.
This, which is the washing of regeneration,
is the first step to be made preparatory to the remission of sins
and witnessing the times of refreshment from before the Lord:
an operation which too many are not willing to undergo.
Like Naaman they think it too mean to wash in the little river of Jordan,
and like him they would have their change brought
about after some more great and powerful manner.
But my poor soul knows by the experience of some years, and by many and deep baptisms,
that the Almighty is indeed various in his operations,
working diversely on various hearts,
and causing the kingdom of Saul to grow weaker and weaker,
and the kingdom of David to grow stronger and stronger,
in a quicker or slower manner according to his own
wisdom in those whom it has pleased him to visit;
but that he is invariable in this, that he requires of each of us to seek unto him alone,
and follow him (not by imitation of others, but by the teachings of his own spirit,
with faithfulness, patience, humility,
and resignation) in that particular way which he has cast up for us to walk in.
And if we be engaged steadily to proceed herein,
we shall experience in our own particulars the fulfilling
of the dispensation antecedent to the coming of Christ,
namely, The voice of one crying in the wilderness, prepare the way of the Lord,
make straight his paths, or make straight in the desert a high way for our God.

Richard Shackleton.

LETTER XXIV.

8th month 1752.
Many are the visited and called of the Lord, but few are his chosen.
The reason I believe is,
because all those who are visited are not faithful
to the little discoveries which are made to them:
some are too stubborn or cowardly to bear the cross, and others are too wise;
and by their reasoning and comparing, instead of obedience to the convictions of grace,
cause the eye which has in measure been opened,
to be closed again by the god of this world, and of the wisdom which is in it.
If you are determined, dear friend, in good earnest to press forward,
and endeavour to persevere to the end,
(for running well for a time will stand us in little
stead) keep nothing alive which should be slain,
give up cheerfully to the fire that chaffy combustible nature which is for the fire;
and let the sword of the Spirit pierce and divide that which is for the sword;
and as you are faithful herein you will know by degrees
judgment to be brought forth into victory,
and you shall in due season feel that peace which passes the understanding.

Richard Shackleton.
