== Letters 50 &#8212; 70

[.letter-heading]
Letter 50.

[.signed-section-context-open]
9th month 1769.

I note what you say of your inward conflicts.
I doubt not your having commenced, and in a good degree successfully carried on that war,
which must subsist (while we are in these bodies) between the flesh and spirit,
from generation to generation.
I wish we may be enabled still to carry it on, till all our enemies be subdued;
the greatest being, I believe, (as you observe) those of our own houses, or hearts.
Let us ever bear in mind, that if we would effectually make war in righteousness,
our weapons must be spiritual, not carnal.
That which is born of the flesh is only flesh: and the flesh profits not in this warfare.
Hence I fear often arise these repeated conflicts and struggles, which leave us weak,
and do not help on the work; when mixing with some certain company,
or engaged in certain hurries and business, we are not watchful enough over our spirits,
to possess (keep) these vessels in sanctification
and in that honour which adorns our high profession,
but suffer more or less defilement.
And then again, when religious company, conversation, and affairs present,
we feel our lack and weakness,
and in our own time and wills would be relieved and eagerly abound.
Then the impatience of our spirits would set us to work,
and tempt to force the (unacceptable) sacrifice;
then we perhaps seek relief and help by complaining to, and conversing with,
the approved servants: who if they be wise in heart, are often shut up from such a state,
and find it their duty to keep their own to themselves.
These voluntary strivings are of the flesh, or too much mixed with it,
so cannot enter the kingdom, which is not to be taken by this kind of violence.
But, dear friend, if we would steadily follow on to know the Lord,
if we would enjoy him to our solid, permanent comfort, and be willing to be anything,
or nothing, in his hand, we must know great stripping and many humble baptisms;
and if we passively and patiently abide under the refining, forming hand,
we shall be dipped into many tribulating dispensations,
which in the course of their operation,
will reduce us and our rational powers as men (which are
only appertaining to us as being also flesh) exceeding low:
so that our sight, with all our other spiritual senses, being purged and clear,
we shall see that truly of ourselves we can do nothing;
we shall be more and more weaned from temporary aids,
and more and more learn this lesson, to cease from man, even the best of men,
and have our sole dependance on the Lord Almighty,
who is the primary source and supply of every substantial good.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
Letter 51.

[.signed-section-context-open]
1st month 1774.

You live in a place distant from the body of friends belonging to the monthly meeting;
and are in more danger, from such a situation,
of being leavened with the spirit and manners of other people,
who though they may be of irreproachable characters among men,
yet are not brought up in a belief of,
nor directed to feel after the quickening virtue
and operation of that saving grace in the heart,
which is the only effectual preservative of men from the corruptions of the world.
You plead for your absence, that you are married, have a prospect of a growing family,
must attend to a provision for it, and therefore that you cannot come,
acknowledge that it is highly proper and commendable
in you to be diligent in your outward business,
and to provide by honest means for a decent livelihood.
Many of us do the same, and yet knowing the uncertain tenure we have of all things here,
and that it is the divine blessing alone which gives
the true relish to the enjoyment of them,
we dare not be so ungrateful to our great benefactor,
so disrespectful to our Lord and master,
and so unfaithful to the common cause of our holy religion,
as frequently to neglect the assembling of ourselves together,
in order to wait for a capacity to perform acceptable worship to the Father of spirits,
and to assist in conducting the discipline established in the society;
and as you would desire that you and yours should be partakers of those
spiritual and temporal blessings which are in the Lord`'s hand to bestow,
as well as others, why should not you as well as others demonstrate your love to him,
and attachment to his cause,
by a humble devotion of your time and talents to the author of your existence?
It is absurd to think, and he well deserves the appellation of fool who imagines,
that his secular affairs will succeed worse,
because leaving them settled in a prudent manner,
he attends his religious duties as a member of Christian society.
Whose are the cattle on a thousand hills?
Whose is the earth and the fulness thereof?
Who lent us for a short uncertain space these conveniences of life?
and, Who can take them from us, or us from them, at his pleasure?

But it is reported,
that you are so far from joining with us in support of the
hedge of discipline which the Lord has planted about us,
that you are for pulling it down:
that so far from making a sacrifice of any little
part of your substance to the support of our testimony,
you are for sacrificing the testimony of truth to a little sordid gain;
and instead of walking in the way of our worthy ancestors, that you are,
in the days of your youth and prosperity,
ready to trample on the testimony which they bore through many afflictions,
and several of them sealed with the loss of their lives,
I mean our testimony against the payment of tithes,
or contributing actively to the support of a hireling ministry.
It would exceed the ordinary limits of a letter,
even to touch upon the numerous arguments which might be brought,
both from right reason and holy scripture, against this anti-christian yoke;
therefore I refer you for satisfaction in this point,
to those writings on this subject which are common in the families of friends;
and at present would just caution you not obstinately,
after repeated advice to the contrary,
to violate so material a branch of our Christian testimony,
which cost our predecessors so dear;
because by persisting in the resolution which I am told you have formed in this respect,
you will, in a great measure, break the bond of fellowship with our religious society,
and I believe it will not prosper with you.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
Letter 52.

[.signed-section-context-open]
6th month 1777.

I note your desire to be acquainted with true religion, and that you have read books,
and cultivated acquaintance with such as might be likely to instruct you in it.
Indeed the generality of people bestow very little solid thought about religious matters:
and if any should be more inquisitive than ordinary,
concerning the way of life and salvation,
they are branded often with the name of Quakers, Methodists, Fanatics, or Enthusiasts.
However, ridicule is by no means the test of truth,
and right and wrong remain irreconcilable things;
the former is worth all the pains of our deep search, and investigation,
the latter it concerns us to avoid with the most cautious circumspection.
It certainly is not consistent with the nobility and excellence of a rational mind,
to adopt the most important principles connected
with our everlasting interest merely upon trust,
and by tradition: the religion of our education while we were children,
should be the religion of our feelings and of our
judgment when we arrive at maturity of understanding,
or it should be changed for that which is so.
Nor is such a change in any degree degrading to the party that makes it,
when it is done purely from conscientious motives; on the contrary,
it is rational and laudable, and has the sanction of apostolical precept,
"`Prove all things; hold fast that which is good.`"
But a change of religious profession, barely, will stand us in little stead;
the unregenerate man or woman must witness a change of nature,
which is a change from nominal to real religion, from shadow to substance,
from the name to the thing; and in effecting this,
true Christianity is learned by experience,
and by experience we know and feel the meaning of the terms,
and the efficacy of the means employed in this great mystery.
People may talk about regeneration, faith, baptism, sanctification, justification,
etc. and may reason concerning the progress of the work of religion in the soul,
but if they do not know and feel it going on in themselves,
they are no more benefited by their head knowledge,
than the man who is languishing for lack of food, is strengthened by talking of eating.
We are to receive these things as little children,
waiting in the simplicity of our hearts, and abstractedness of thought,
to be fed by the Divine Hand, with food convenient for us.
If we trust in the Lord with all our hearts, and lean not to our own understanding,
he will lead us on gradually, feed us according to our growth,
and inform our understanding in the things of his kingdom,
as we shall be able to bear or comprehend them.
I wish you dear friend, to be still in your mind,
to guard against restlessness and impatience,
to employ yourself quietly and cheerfully in your outward occupation (which will
help to prune away a redundance of unprofitable thoughts,) and to be diligent
in waiting for and feeling after that spring of comfort in your own mind,
which is not under your control, nor at your command,
nor can be come at by the working of any artificial tool of our imagination;
but which the great master sends in his own time, "`To revive the spirit of the humble,
and to revive the heart of the contrite ones.`"

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
Letter 53.

[.signed-section-context-open]
12th month 1780.

A personal interview is pleasing,
when it can be enjoyed in a degree of calmness and quiet;
but as many things combine to prevent that,
I wish us to meet often in spirit--"`Absent in body, yet present in spirit.`"
In this, my first acquaintance and fellowship with you was formed,
before I personally knew you; in this it has been renewed and confirmed.

I travail for you, dear children, that Christ may be formed in you,
that you may be complete in him, lacking nothing.
The cry of my heart for you has repeatedly been,
that the Lord would make you such as he would have you to be.
If left to ourselves,
and to model ourselves and our demeanour according to patterns which in
our own judgment we may set down as most excellent and worthy of imitation,
our inward man will be apt to grow feeble and distorted,
and its constitution sickly and unsound;
but leaving ourselves to the Lord Almighty to create in us a clean heart,
and renew a right spirit within us, diligently waiting in nothingness of self,
out of our own willings and strivings,
for the descending of the power of truth to contrite and baptize our spirits,
we shall witness a being melted down and moulded anew into whatever utensil,
form and size, the maker pleases.
Here is the great matter on our parts, even to be passive in the Divine hand,
as clay in the hand of the potter.
The mixture of our own imaginations is what we are carefully to watch against,
being the thing which mars the perfection and sullies the beauty of the Lord`'s work.
All that he makes is unmixedly good;
so the more simply and unreservedly we submit ourselves
to be prepared and fashioned by him,
the more of that unmixed good, will be in our spiritual composition,
and the nearer we shall approach to the highest perfection of our natures,
the fulfilling the precept of Christ, "`Be perfect therefore,
even as your Father who is in heaven is perfect.`"

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
Letter 54.

[.signed-section-context-open]
12th month 1781.

I like that young men should avow their principles,
and range themselves on the right side.
I like that they should engage in such acts as will show they are
not in alliance with the enemies of God`'s true Israel.
There must and will be enmity between the two seeds.

My spirit has waded in the deeps many a time, in travail for the visited youth,
that not one grain of the heavenly seed might be lost, nor unfruitful;
and now my cry is that they may "`go forward.`"
They have many of them been tied up from the further sallies of their own wild nature;
they have known the discipline of the cross; and now the Master has need of them,
(alluding to the passage in Matthew 21)
he calls for their service in the church.
Indeed they can never serve a better master--his service dignifies the meanest talents;
and the brightest, if they tend not to promote it, are but meanly employed.
This world, its bustle, its pursuits, and its highest glory,
will soon be over to every one that is at present in it.
Then the answer of "`Well done! good and faithful servant,`" will be a more joyful sound,
a more substantial reward, than all the favour and friendship, false praise and honour,
which this life can bestow.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
Letter 55.

[.signed-section-context-open]
3rd month 1783.

She is now released from those long infirmities which
infinite wisdom permitted her to pass through,
for the trial of her faith and patience,
and for her preparation for an admittance into that rest,
into which nothing impure can enter.
Refined and polished while here for the company of blessed spirits,
she is (I doubt not) mingled in their happy society.
We remain a little longer to struggle with the difficulties,
and encounter the temptations, which belong to this life.
We are not yet putting off our harness, therefore have no reason to boast,
but to dwell in awful fear.
We are some of us the heads of families, and principal persons in our places:
our precepts and our example therefore must have considerable weight and
influence. How necessary is it for us then to ask wisdom of him,
who gives liberally and upbraids not;
that by rightly fulfilling all our several duties in our families and in the church,
we may, as we pass along in our journey,
have the answer in our consciences of "`Well done!--good and faithful servant,
enter into the joy of your Lord,`" as well as that
happy sentence at the close of this visible scene?

My mind, while I am thus engaged,
is turned with tender solicitude towards your beloved offspring.
I believe that many of them (and most probably all of them)
have felt the gentle touches of the Divine Hand,
and the invitations of the good Spirit in the secret of their souls,
drawing them from the spirit of the world, in its manifold appearances,
and begetting in them desires and aspirations after enduring substance.
May they with all diligence cultivate the renewal of these tendering impressions,
and in all humility submit to the operation of these cleansing baptisms,
which purify the heart, and make it a fit receptacle for unmixed good.
A gracious Providence has not been lacking in his visitations to the youth among us;
but there has been a great lack in them of following on to know
the Lord in the renewed experience of his humbling power,
and in the further manifestations of his will concerning them; hence the goodness
of too many of them is but like the morning cloud and early dew;
it is soon superceded by a relish for the pomps and vanities of this world,
and their baptismal vows are soon forgotten;
and hence a lack of succession of testimony bearers to the noblest cause, which ever did,
or ever will, dignify human nature.
I particularly wish for the elder branches of your numerous hopeful stock,
as now a greater charge devolves upon them,
that they may seek and wait for heavenly wisdom to direct their own steps,
and influence every part of their conduct;
that so they may grow in favour with their great Creator,
and in his hand be made a blessing to the younger branches of the family,
assisting to train them up, by example and precept, in the life of religion,
and in that plainness and simplicity which adorn our holy profession.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
Letter 56.

[.signed-section-context-open]
2nd month 1784.

I have repeatedly heard of your appearances in a few words in public and private opportunities,
and no doubt, in diffidence and fear.
I need not tell you that it is a great and solemn
office to be an ambassador between God and the people.
I am persuaded that you are sensible of it,
and that it is the sincere desire of your heart to be found in the way of your duty.
In your infant state you will very probably have many doubts,
questionings and reasonings: but as the eye is kept single to the one object,
the faithful discharge of duty, the whole inward man,
will be full of light--enlightened and enabled to walk in the right path,
and if fears and jealousies of self should arise,
they are not to be fought against in the will of the creature;
but words and actions are to be brought to the light of Christ,
that they may be there tried whether they have been wrought and spoken in God,
i+++.+++ e. whether they have the seal of his spirit.
Where self is sufficiently abased,
and only to will and to do of the Master`'s good pleasure is the dominant principle,
there is not much danger of an honest mind being long under a deception.
The feeling of one`'s own mind, and the concurrent testimony of the living, will,
like the mouth of two witnesses, establish every word:
and though for wise purposes there may be for a season, as it were, a chaos, and a void,
and darkness upon the face of the deep;
yet as the operation of the spirit of truth in your soul is diligently waited for,
and the turning of his holy hand is patiently borne and submitted to,
he will (I trust) in his own time, "`Bring forth your righteousness as the light,
and your judgment as the noon-day.`"

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
Letter 57.

[.signed-section-context-open]
9th month 1784.

It was very pleasing to hear that it proved consistent
with the Divine will to lengthen out your short span,
to add a few days more to your pilgrimage.
To those engaged in the same warfare it is a matter of gladness and strength
to have their companions continued to them. You know what this world is;
a place of danger, temptation and perplexity;
a place where we exceedingly need Almighty help, protection and direction;
we need the fear of the Lord to be ever before our eyes, that we may be solid, weighty,
steady in the face of our families, and our connections and familiar acquaintance;
we greatly need wisdom, fresh and fresh for every occasion,
that we may fill up our stations in the church with propriety and acceptance.
This is a great family, in which are many servants allotted to many different offices;
various work is to be done, and great care is to be taken by every particular servant,
that he diligently minds his own business,
and does not over officiously meddle with that of another;
and in order that confusion may be prevented,
and the Head of the family may not be dishonoured, some servants,
more intimately acquainted with the Master`'s will and with the order of the house,
hold a diligent watch, not only over themselves, but their fellow servants, for good;
exhorting, reproving, informing, reminding, and all with pure disinterested zeal,
seeking not themselves, their own honour and precedence,
but the honour of the great Master,
and the welfare and happiness of every individual in the family.
`'Tis to this service that I want you, my dear friend,
(if Providence should be pleased to grant a renovation of health) to be still more dedicated.
There is a lack of baptized elders among us;
such as have been companions with Christ in his sufferings among us, and by us,
his chosen people.
You see what a host of messengers is sent, even from far distant parts of the earth,
to awaken us to righteousness and amendment of life.
May we, the objects of their visits and of condescending favour, be willing,
yes desirous to go yet deeper down into the sacred pool,
there to be washed from every defilement of spirit, as well as of flesh; that so,
being happily reduced to the little child`'s state,
we may lose "`the wise and prudent,`" in the reduction of self,
and be in a state fit to receive the glorious mysteries of the kingdom,
"`revealed unto babes`" in Christ.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
Letter 58.

[.signed-section-context-open]
8th month 1791.

You know upon what grounds, convictions and feelings you came, at the first,
to profess the truth; you know what it has since done for you, how you have espoused it,
and with what company you have on various occasions been engaged in the promotion of it:
and I doubt not you still believe it to be the most inestimable treasure,
which the heart of man is capable of enjoying.
Be honest with yourself, as I hope, my dear friend, you will be,
and try whether you have not suffered loss;
whether for some time past there has not been a decay, instead of an increase,
of divine virtue in your soul:
and whether your ability for service in religious society has not been greatly weakened,
if not entirely lost.
This perhaps your candour and integrity will acknowledge; but self, that partial,
pernicious counsellor, self, will probably plead that loss indeed has been sustained,
but that the fault is not all your own; that you have met with hard usage,
improper treatment, and an unchristian spirit, in dealing, from your brethren:
and that though you may be, in some measure, wrong,
it is evident that they are not altogether right.
This reasoning leads to a self-complacence, and retorting;
which will only bewilder and aggravate.
I would therefore, in true good-will, and cordial desires for your restoration and help,
recommend you, dear friend, as much as possible, to turn out this reasoner,
this interested, prejudiced counsellor, self; to look unto Jesus,
the author of your faith; to lay prostrate as at his feet; to bear his chastisements;
and not only bear, but with all your heart to desire them, as being the stripes,
by which you are to be healed: no, farther, submit yourself with a dutiful,
filial submission to your mother the church,
though some of her children may seem not in the spirit of meekness, but angry with you;
be not moved to retaliate, but remember the pattern which the great Master set us:
as says the apostle, "`For even hereunto were you called,
because Christ also suffered for us, leaving us an example,
that you should follow his steps: who did no sin, neither was guile found in his mouth:
who, when he was reviled, reviled not again; when he suffered, he threatened not;
but committed himself to him that judges righteously.`"
How much more then should his followers and disciples,
when they have been overtaken in a fault, confess their frailty, humble themselves,
and make restitution, and satisfaction, and reparation, as far as in their power?
We have seen the danger of persisting in a line of
conduct contrary to the general sense of the brethren,
and of being pertinacious in our own opinions; how it lowers in esteem,
and lays waste the service of those who were gifted and honourable men.
I confess I am afraid lest the enemy of all good should
make use of your present situation and circumstances,
as an engine to batter down any wall of stability and security that is left about you,
and wreak his infernal malice upon you; for "`Hell and destruction are never full.`"
O, may you with full purpose of heart turn to him,
who graciously visited you in early youth,
who gave you a name and inheritance among his people, and who,
if the fault be not your own, will demonstrate that his promises are not yes and no,
but yes and Amen, and that his mercy endures forever.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
Letter 59.

[.signed-section-context-open]
5th month 1786.

The national meeting was, I hope, owned in degree in the several sittings of it;
my poor spirit was favoured with being brought low, and plunged into the deeps,
a state I love, because I love cleanliness; and I desire no other state,
nor any other support or food, than what Infinite Wisdom sees fit to administer to me:
he knows our several frames and textures, and what is necessary and best for us;
he is the wise potter, who knows when and how to use the fire and water, to harden,
to soften, and to let the vessel stand in a preparing state for the appointed time:
he is the wise householder, who at his pleasure occupies the vessel when prepared;
yet even then, when he takes it down, cleanses it afresh for use.
May we, in every stage of the operation of his plastick hand, be submissive,
content to remain as on our mouths, turned upside down,
or standing as on the shelf unoccupied,
as well as using all diligence of spirit to be in
a state of readiness for any little use,
which perhaps the Master may suddenly require!
His tried, experienced,
faithful servants with one voice declare that he is the best of masters;
and I am sure this life seems a poor, insipid, paltry round of care and cumber,
vanity and folly, unless it be sweetened,
animated and renewed by the spirit of Christianity entering into and among our feelings;
so, my beloved, go on and prosper in your own little way,
attentive to please the husband of souls, learning of him at home,
simply and honestly doing whatever he bids you;
not too much looking out and musing on what this or that body will say or think,
but cultivating retiredness of spirit, and attending to the gift which is in you:
so be it.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
Letter 60.

[.signed-section-context-open]
10th month 1786.

Such is the excellent nature of this holy power,
that the more the gift is exercised (under a lively influence) the brighter it shines,
the stronger it grows, and the more the precious anointing accompanies it.
But unfaithfulness, disobedience, spiritual indolence,
will always gradually work its decay; and then uncomfortableness, unpleasantness,
uneasiness, and indeed unhappiness crowd in from all quarters,
from within and from without; a host of foes,
and our best friend and ally alienated from us.
So, my dear friend, let you and I go on quietly and softly, and feelingly,
in our own little line of life; if we get any little good for ourselves,
let us husband it carefully, the times are poor; but if there seems a redundancy,
let it flow, nor fear to waste the ointment;
and indeed if there should be no super-abundance for ourselves,
if a famine should be in our land, yet should we be glad to handle the holy things,
and of being favoured to distribute to others; for so doing,
we shall certainly get enough to keep life and soul together, and as the times go,
we may be very well satisfied with this,
"`You shall not muzzle the ox which treads out the corn.`"

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
Letter 61.

[.signed-section-context-open]
1st month 1788.

Last night we received yours, of the day preceding,
with an account of the final outcome of your anxieties respecting your beloved infant,
and it is the last and worst to be expected concerning her:
no painful fears about her future conduct;
no danger of her entering into temptation of the enemy: no corruption of the heart,
nor any internal defilement to annoy or destroy; no cares, conflicts,
and embarrassments of this world to vex and perplex her,
no more pain and sorrow of body and mind,
but an admittance into that kingdom which is composed of such;
into one of those mansions prepared by the Father for innocent and sanctified spirits,
which, forever happy in a new state of existence, are doubtless glorified by,
and are employed in glorifying forever, the glorious Author of their being.
Well will it be for us if we can but go to them.
In order to which attainment, we that are continued on this stage,
have a sharp and constant warfare to maintain, not only with flesh and blood,
and that which is inherent in them,
but some of us are called to grapple with and encounter
spiritual wickedness in ourselves and in others;
we have an arduous fight to maintain, and great care, caution, and diligence to exercise;
else, instead of overcoming, we maybe overcome of evil,
and even near the end of the race, may fall and lose the prize.

My beloved, you have received a gift for the edification of your brethren and sisters;
do not despise it nor the occupation of it, but diligently wait on your gift,
and exercise it in the simplicity according to the ability received:
so will you not only grow therein,
but grow in favour with the great master and with his faithful servants:
you will find that humility,
fidelity and obedience will make way for you in the hearts of the people,
and make room for extensive service, to the increase of your peace and tranquillity.
Then, when cross occurrences fall out, and external trials beset,
these things will be received with equanimity and patience;
"`Shall we receive good at the hand of God, and shall we not receive evil?`"
But, on the contrary, where there is a desire to save self and its honour,
a reluctance to expose one`'s self and become vile; or a disqualification for service,
of our own bringing on; then we are not only uncomfortable in ourselves,
retard our own growth, accumulate weakness;
but when disagreeable events are permitted to befall us,
they appear to us clothed with terror, and ministers of divine wrath.
In this view,
I contemplate with satisfaction the account which I had
of your faithfulness in your late province women`'s meeting;
had you returned home under the load of conscious disobedience,
what an aggravation would it have been to your severe trial!
But I trust a placid serenity is the covering of your spirit, and that you have blessed,
and will be enabled often to bless, that hand which mercifully gives,
and as mercifully and wisely takes away, at his pleasure.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
Letter 62.

[.signed-section-context-open]
11th month 1788.

Indeed my heart has been made glad in the house of prayer,
on behalf of the visited youth of this generation;
the desire and petition of my soul has been,
that nothing might be permitted to hurt them,
nor to mar the work of formation in and upon them;
but that they may go forward and increase in the
excellency of dignity and the excellency of power;
that so by and through them, under divine protection and direction,
the continued backsliding of a degenerate people may, in a good measure, be stopped,
and the Lord may be graciously pleased to return to the many thousands of Israel.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
Letter 63.

[.signed-section-context-open]
7th month 1790.

I have indeed abundant cause of thankfulness to our Almighty Benefactor,
for his gracious protection still extended,
and his safe conduct of a poor and helpless creature home to my family and friends.
I have also humbly to acknowledge the daily supplies every way afforded,
"`Profitable to me for doctrine, for reproof, for correction,
for instruction in righteousness.`"
Thus the rod and the staff, administered in wisdom, alternately rectify and regulate,
assist and comfort;
and so poor pilgrims move along under repeated convictions
of their own infirmities and insufficiency,
and under a renewed experience of continued mercy and divine aid.
The yearly meeting of London seems like a home, or habitation to my spirit;
I am dipped (I trust) in some degree into the state of the Christian cause,
and engaged in a travail, and secret, silent wrestling,
for a blessing on the endeavours of the faithful in this day for the promotion of it.
This I look upon as my principal business there,
though a good deal of other matter relative to church affairs, falls to my lot besides,
and calls for diligent exertion of my best abilities.
Upon the whole, I do hope this most important cause gains ground,
and that though there still remains some old, fruitless, sapless trees in the wood,
and many towering lofty cedars in our Lebanon,
yet a great number of promising young plants, hopeful saplings,
have taken root downwards, and are shooting vigorously upwards.
Much depends on their preservation from any annoyance, on their upright growth,
and bearing each their own kind of fruit in due season.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
Letter 64.

[.signed-section-context-open]
11th month 1790.

It is often easier to give advice than to take it: it is easy to recommend resignation,
but when the trial comes home to us,
and the exquisitely tender feelings of nature are affected, then to say with the heart,
"`Your will be done!`" is to overcome indeed.
And yet such a victory over humanity may be gained, and is often gained,
by the Lord`'s children in their pilgrimage through this life,
and being strengthened by his love and by his power,
they can in all humility and gratitude kiss the rod which chastises them,
and bless the hand which, in perfect, through unsearchable wisdom,
both gives and takes away.
Our sympathy with you, my dear friend, is strong,
and our hope (I trust) is not of the hypocrite, which perishes; our hope is,
that you will in the Lord`'s time be raised out of these glooms and pits of distress:
and having been made a witness of deliverance out of the depths of tribulation,
and as it were the belly of hell,
will have experimentally to testify to the sufficiency of that arm of everlasting power,
which could deliver in such sort,
as to encourage other travellers in like tribulated paths to hold on their way.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
Letter 65.

[.signed-section-context-open]
3rd month 1791.

People may talk of the weight and influence and respectability of old age;
but if younger persons do not go forth in the service, and exert themselves,
the cause will suffer.
I am not for dragging you, my dear friend, from your domestic concerns,
which are various and important; but if truth gently draws you,
and whispers that a duty is to be done,
I would have you follow its leadings and secret monitions.
He that made us is all-sufficient to preserve;
the kine indeed must be allowed to low as they go;
the natural part to regret the parting with the inexpressibly
tender connections left at home;
but the ark of the testimony must be taken out of the land of the Philistines,
out of the hands of the uncircumcised; and blessed will they be with whom it rests.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
Letter 66.

[.signed-section-context-open]
6th month 1791.

The yearly meeting was large and solemn:
and I hope that it was renewedly felt and experienced, that,
notwithstanding lamentable declension and dimness may be acknowledged,
our religious society is still owned the chosen people,
among whom the lively oracles are deposited,
the gifts and graces of the spirit are bestowed,
and the principles of pure and genuine Christianity are professed.
Declamatory speeches in the yearly meeting I think gradually decrease.
I wish I could say that I think there is much increase of the authority
and weight which ought to accompany the offerings of the tribes,
rulers and princes of the people.
But I trust things will mend: a younger sort will come forward,
who being of clean hands will grow stronger and stronger, who,
having washed their hands in innocence, will encompass the Lord`'s altar with acceptance,
and who, being themselves consecrated by the divine anointing,
will be rightly authorised and influenced to meddle with holy consecrated things.

You know that your poor friend`'s chief joy is,
to see that the children of the Elect Lady walk in the truth.
You have received a heavenly gift, let it be of whatever denomination it may;
what matters the name of it?
Attend upon it; prize it; it is the wisdom, which is more precious than rubies;
exercise it when the great Master bids, when he comes, calls for you, singles you out,
and puts you forth in any little service;
this is the way for the waters of this life`'s afflictions
to be changed into the wine of the kingdom,
and for the sorrows and perplexities of this world to be turned into heavenly joy.
Nothing short of hearkening and obeying will do; but this will do all for you,
and more than you can ask or think.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
Letter 67.

[.signed-section-context-open]
8th month 1791.

This life is the field of battle,
and our most dangerous enemies are those of our own houses.
May the lamp of God in the temple of our hearts,
be kept still renewed and replenished with heavenly oil,
that we may have a clear sight of what is doing within us,
lest we should think otherwise of ourselves than we really are.
Purity of heart is a main qualification for being of any service in the church of Christ.
Let us then use all diligence to obtain and to retain this precious state.
"`Blessed are the pure in heart,
for they shall see God;`" they shall clearly discern
the things which belong to his kingdom;
and when they speak of them,
it will be of what they have seen with their (spiritual) eyes,
and what they have "`Looked upon;`" what has been brought
by the Holy Spirit before their internal view,
as an object of contemplation for themselves,
and a subject which they are authorized to handle with clean hands,
and with hallowed lips to communicate to others.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
Letter 68.

[.signed-section-context-open]
11th month 1791.

I love to see business, the Lord`'s business, going forward,
and the youth stepping into their lots,
experimental witnesses of the power of an endless life, fresh, feeling,
and full of good matter, loving their Master, and willing to give that proof of it,
which he peculiarly requires, that is, to feed his lambs and his sheep.
A little longer time, and we are numbered to the silent grave,
in common with all the generations which have been before us: let us then,
while we are here,
seek for help to do our duty acceptably in the sight of our great Judge;
that so at the awful day of decision, our spirits, disrobed of this mortal clothing,
may hear the blessed sentence with unspeakable joy,
and be mercifully separated to eternal felicity.

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
Letter 69.

[.signed-section-context-open]
7th month 1792.

I think it a pity that he should be so much confined, but perhaps it may be best;
some confinement causes us to enjoy liberty with a keener relish,
to prize it more highly, and to be more grateful for it,
as well as to endeavour to turn it to the best advantage.
Time and opportunity are precious things, but very unstable and fleeting,
and should be diligently improved.
I suppose you are now confined at home, and not at the general assembly at Limerick.
Yet of so excellent a nature is the holy principle which
we profess as the main spring of our religious movements,
that distance does not always disunite; there may be a great travail,
union and communion of spirit, where there is a bodily separation.
"`He that is joined in spirit to the Lord, is joined to all the living.`"

[.signed-section-signature]
Richard Shackleton.

[.letter-heading]
Letter 70.

[.signed-section-context-open]
2nd month 17th 1791.

On my return from +++_______+++ I was saluted with your kind epistle.
It was, and is, very grateful to me,
and I shall esteem it a favour to be thought worthy of the
continued fruits of your friendship and little leisure.
There are many cross occurrences which disquiet the mind,
and if Divine Providence should, on the other hand,
cast up some fresh means of consolation and refreshment,
why should not we avail ourselves of his bounty?
A new correspondence, like a new well opened in the course of pilgrimage and dry travel,
may, under the blessing,
and "`by the direction of the lawgiver,`" prove comfortable
and strengthening for the journey.
I often think of you,
and my cogitations about you are attended with sympathy and compassion;
my mind`'s eye views you in the valley of affliction; be not restless,
but remain there the appointed time,
and the Lord is able to make this "`valley of Achor (which is trouble) a door of hope.`"
He can cause the ground of this same affliction to
be productive of the most salutary increase,
so that not only "`Sharon shall be a fold of flocks,`" but even "`the valley of Achor,
a place for herds to lie down in;`" but this happy experience
is for "`my people that have sought me,`" says the Lord.
May you be strengthened then continually to seek the Lord,
who in inscrutable wisdom orders or permits the close trials which sometimes beset us.
I know nothing we can do more likely to benefit ourselves,
and those whose welfare is nearest to our hearts,
than to keep diligently to a holy travail and wrestling
of spirit on our own and their behalf.
Our own prudence and policy often fail,
and the influence of nature itself loses its sway,
where it has all right to rule and govern;
but even the king`'s heart is in the hand of the Lord,
as "`the rivers of waters he turns it whithersoever he will.`"
I was pleased to hear you were out on church service.
I am persuaded that no worldly business detains you
at home with the consent of your will:
and I doubt not but it is (as it certainly ought
to be) your studious endeavour to get your head,
hands and feet (as I believe your heart is already) loose,
and become more and more the Lord`'s freeman.
Remember the call, "`Shake yourself (not only from the grosser and more defiling part,
but) from the dust, O, Jerusalem;`" and loose yourself "`From the bands of your neck, O,
captive daughter of Zion:`" then will there be a
putting on strength and the beautiful garments;
then will there be a receiving the gift in perfection,
and exercising it to the honour of the Giver,
as well as to consequent sweetness and peace;
then precious virtue is known to go forth from the Holy One,
as through the vehicle of a refined and purified spirit, to others;
and there is a rejoicing together in the great Master`'s name.
Thus will you more and more rise in the dominion of Truth, and get, in your mind,
over all those things which would agitate, and annoy,
and turn aside from the proper centre.
Thus, however useful you may have been in civil and religious life, your last days will,
by the increase of living sap, be your best days; your end will be happy,
and your example live in sweet memorial among future generations.
So be it!--says your truly affectionate faithful friend.

Your letter seemed to congratulate us on the return of our dear friend Sarah Grubb;
but see what state of existence we are in, how transient and uncertain.
She just got to our national meeting to deliver up her certificate,
gave a short simple account of their visit to the continent,
spoke as if herself had been nothing and had done nothing,
magnified her Master`'s cause in several sittings of the meeting; went to her own home,
and saluted her relations and friends there;
proceeded to the quarterly meeting to which she belonged, at Cork,
laboured there in the authority of the gospel, and when it was over,
laid down her head in peace at our friend Samuel Neale`'s house, at Spring Mount,
8th of 12th month last.
Her loss, as a member both of civil and religious society, is very much regretted:
but encomiums are superfluous. If we revere her character,
let us endeavour to follow her example;
if we are attached to the cause which she was so eminently engaged in,
let us wait for qualifications to support it,
according to our several measures and stations.

+++______+++ hears now and then from the neighbouring continent,
and favours us with some account.
We understand the precious seed sown there does not seem to be lost;
we rather hope that it has taken root and is springing up;
perhaps "`The earth is helping the woman:`" the convulsions and revolutions
in that country forwarding the establishment of the church of Christ.

I have now, I see, got near the end of my paper,
and I feel my love to you all abound and spread;
but have not left myself room to write it down:
among others +++_______+++ (if still on this side of heaven)
possesses my affectionate remembrance.

[.signed-section-signature]
Richard Shackleton.
