== Letters LXXXVI &mdash; CXII

LETTER LXXXVI.

The religion of some seems to consist in the remembrance of former experience,
a rational understanding of our principles and the discipline of the church,
a personal communication with some of the foremost rank,
and some faculty for speaking and writing on religious subjects; when in the mean time,
for lack of looking and living at home, for lack of watching unto prayer,
and waiting for renewed ability to offer the daily sacrifice on the fresh raised altar,
insensibility and incapacity gather strength, and leanness enters into our souls.

Richard Shackleton.

LETTER LXXXVII.

16th of 7th month 1782.

I Take very kind, and as a mark of friendship, your advising me of the removal,
as well as the birth of your first born.
We naturally look about for those we love to communicate
with them our joys and our griefs.
Among the many alleviations of the miseries of human life,
a good and beneficent Providence has appointed one, called sympathy, by means of which,
our happiness is increased and our sorrow lessened, in the diffusing and dividing.
Good and gracious and kind indeed is he, with whom we have to do;
he knows the acuteness of our feelings and the sensibility of our hearts:
"`He does not afflict willingly,
nor grieve the children of men;`" and yet he sees fit to prove and try us,
with causing in our minds sensations of exquisite pain.
You are a man of reason and religion;
and it seems superfluous to suggest to you those considerations,
which might with propriety be thrown before many others,
such as that the Almighty Controller of the universe, does all things well;
that he only knows what`'s best for us;
that he afflicts with paternal chastisements for our good;
that these crosses and troubles are often concealed mercies and special favours:
that in any case, it is highly dangerous,
as well as improper to repine at the ordering of infinite wisdom,
and particularly in the case of a youth removed out of a vain, a perilous,
and a troublesome world, in his innocence:
when it is so uncertain how he would escape the temptations,
snares and pollutions which might annoy his longer life,
and endanger his everlasting happiness.
In reflections, such as these, you have (I doubt not) anticipated me;
but after all is said, which can be said, or read, or written,
unless our merciful Creator pours in the wine and the oil to our wounded spirits,
unless he visits with divine consolation, and raises, with divine support,
we shall never know true and solid comfort, help and strength to our poor minds,
under the pressure of the evils and infirmities which flesh is heir to.
May we be favoured to get low enough, conformed to our great pattern,
that so we may more and more closely company with him,
during the remainder of our pilgrimage, witnessing fellowship in his sufferings,
and being more and more baptized and qualified to
fill up our several stations in his church.
If this perishable life be desirable for anything, surely it is for this,
that we may be instrumental in our generations, to propagate, to show forth,
to spread by our conduct, and the gifts and talents which may be bestowed,
the glorious gospel which brings salvation among men.
Time is assuredly short to us all; during this short time we have only to labour.
Retribution is at the end.
As our works, so shall our rewards be.
If we can be termed by the Just Judge,
"`Good and faithful servants,`" we shall enter into the joy of our Lord.
May we set this prize, and keep it steadily in view, my dear friend.

Richard Shackleton.

LETTER LXXXVIII.

8th of 9th month 1780.

The riches of this world, accumulated even by honest industry,
without having the Great Disposer of all things in the view,
and acting above the affairs of this life in bis holy fear,
are often the means of inexpressible perplexity and disquiet,
sometimes of the most dreadful evils.
Whereas, a looking, a leaning, a humble dependence on him that feeds the ravens,
and on the concatenation of the events ordered by his Providence
which caused the ravens to feed his prophet,
is the way to procure the divine blessing to be superadded; and prevents that sorrow,
that uneasiness, that restlessness, that insatiable avidity,
which works death to the innocent, happy, composed life.
But though I thus indulge a freedom of writing, I think I well know both your hearts,
and that they are in that place,
where treasures of a far more noble kind than any which this world can afford,
are laid up for the poor in spirit, the simple and honest hearted,
and for those who think little of themselves, can say little for themselves,
yet are diligent in waiting for ability to walk in that way which leads to life everlasting.
We have each of us our foibles as men and women,
and have each of us occasion to be industrious in watching unto prayer,
that the droppings and distillings of good may fall upon our branches;
strengthening and fructifying the holy plant,
and destroying by its sacred virtue and influence,
or at least correcting those frailties of the flesh, which, like messengers of satan,
are at times sent to buffet even those who are well-minded,
and in a good degree partakers of divine regard and notice.--Man is a complex machine,
composed by the wonderful Architect, of various parts interwoven together; body,
soul and spirit.
The body requires outward food to sustain its outward substance;
the living soul must be kept alive by inward sustenance,
conveyed into it from his fulness; the spirit, or rational thinking part,
should be regulated by that reason which distinguishes
the human capacity from that of other animals;
this reason is also God`'s gift, and by no means to be slighted or rejected.
If we neglect a proper care of our bodies, disorders will hurt them:
if we omit to seek for spiritual nourishment, our souls will be in danger of perishing;
and if we exercise not our reason to cultivate and improve our natural understandings,
to reform and correct wrong habits and propensities,
and to form us and our manners so as to be pleasing and profitable members of society,
our spirits may, in our progress through life, contract dispositions,
which in course of time may be inveterate and hard to be removed;
dispositions which will much disqualify us for filling
our several departments in life with propriety,
and with ease and satisfaction to ourselves and others.

Richard Shackleton.

LETTER LXXXIX.

16th of 4th month 1768.

We lost my dear mother, the day after you and I parted.
I believe she longed to be released from her house of clay, and made a happy exit:
I trust also,
that her righteous spirit is gathered to and united with the innumerable
company of the faithful of the generations that are gone before;
who had, many of them, little name or fame, or visible property among men,
but are now enjoying an eternity of happiness;
while those who had their portion in this life,
and lived in forgetfulness of the Great Giver, have met with a dismal reversion.

My father still keeps his own house, employs himself with the land,
and comes more frequently to us than he used.--He
is a favoured man and knows where best help,
under every difficulty, is to be had.
He is like one of the old patriarchs that dug a well,
and so has water of his own labouring for, to drink of.

Richard Shackleton.

LETTER XC.

4th of 9th month 1768.

My leisure from the duties of necessary business is small, and this leisure is,
(I hope) in a good degree occupied by the weightiest engagements in life.
There is a species of self-love or self-preservation, which it is not only lawful,
but absolutely necessary for us all to be possessed with; that is,
each to take heed to ourselves.
Here is uncertain, and hereafter is everlasting.
We should therefore diligently endeavour to improve
every fleeting opportunity while here,
to secure a hereafter of happiness.
The husband apart and the wife apart,
have each to work out (by diligent faithful labour)
this momentous task of their soul`'s salvation,
and to know it going forward with their day of renewed visitation.

The world is deceitful; its friendship is not to be trusted; its assistance to us,
in the hour of distress, is vain.
Religion (which is no other than acquainting ourselves with God,
and witnessing the peace which results from that
communion) is the help and ornament of life,
the hope in death, and the perpetual reward of its votaries in the world to come.
Let us be roused, my dear friend, by the calls of the spirit,
by the invitations of the church, by the work of the day,
and by the necessity of the times,
more and more to devote ourselves to the cause of Christ,
and his holy undefiled religion and way of worship of God, and of walking before men,
which the blessed Author established on earth by his precepts and visible example;
and which (after a long night of apostacy) our fore-fathers, in the last century,
were raised and enabled by power from on high, most nobly,
firmly and faithfully to revive and maintain.
Great and lamentable is the declension and blindness which has happened in our time,
to the successors of those honourable worthies,
professors of the same everlasting precious faith.
Our city is not only closely besieged by enemies from without,
but there are virulent enemies, hostile confederacies, deceitful allies,
and weak defenders, even within the verge of its walls.
The head (the skill and understanding) is in a great degree sick;
and the heart (the courage and zeal) is faint.
May the consideration of these things sink deep into our souls, and take root there;
let it cover our minds in secret, as sackcloth within upon our flesh.
Being dipped into sympathy with the seed under oppression,
and dwelling in the house of mourning therewith, we shall witness our hearts made better,
our inward man to be strengthened, and an offering prepared in us,
which will be a sacrifice of atonement for past delinquencies,
and an oblation acceptable in the sight of God.
To his holy keeping I heartily commend you,
and to the visits of his quickening grace and good spirit.
May it be the main employment of our lives,
to seek to dwell under the renewed influence of it!

Richard Shackleton.

LETTER XCI.

30th of 10th month 1768.

I Receive, with much satisfaction, the account of the increase of your family.
May there be increase of pure fear and diligent waiting for the sense of divine favour;
so there will be an increase of that blessing which makes rich in faith,
and abounding in good works.
If there be any earnest desire for our own preservation,
if any anxious concern for the Christian cause,
if any humble willingness and care to make some return
for all the favours of our common benefactor,
this day calls for the dedication of all to him who has given us all that is good,
and is over all, blessed in himself, and the source of all our blessings,
now and forever.

Richard Shackleton.

LETTER XCII.

4th of 4th month 1769.

I Note your incertitude about settling, and that your desire is to be directed aright.
Human projects and prospects formed by the best share of mere reason are very fallacious:
and who expects or looks for any better direction in matters of such a nature?
Too few indeed have a right to expect any better; and yet my belief is,
that if we were so happy as to be enabled to be inward enough in our minds,
we should be favoured with a sense of what we ought to do and leave undone,
in affairs which seem (many of them) rather of a temporal than spiritual nature;
as the great apostle says, "`He that is spiritual judges all things.`"
I wish for you, dear friend, and for your brother to grow in this spiritual life;
that as divine Providence has blessed you with the
affluence of the good things of this world,
you may deeply ponder how the residue of the few, fleeting,
uncertain moments may be best employed, so as to possess sweet peace while here,
and insure an eternity of uninterrupted happiness hereafter.
We are not all called to one office; nor placed in one particular station in the body;
but we are all called to that life of simplicity, self-denial, plainness, humility,
and holiness, of which the great Author of Christianity set us and left us an example;
and having felt of the virtue which proceeds from a union with him,
we are called to show forth an example of his nature
by our conduct amongst our brethren and sisters,
the great fraternity of mankind, where ever we converse among them.
The greatest part (I suppose) of your juvenile days has been spent
among a numerous acquaintance in your good sense and active natural
understanding have doubtless influenced you to remark the beginnings,
the lives, and the ends of many of them, and you have said in your heart,
the religious man alone is happy.
According to my best sense +++_______+++ is the place for you, or its neighbourhood,
to spend the most of your future days in;
and may our common gracious Parent so reduce you by his power, so fit you by his wisdom,
so furnish you by his strength, that your latter days, as well as mine,
may be better than the former part of our lives, more steadily feeling after good,
more plentifully enjoying it, and more diffusely spreading the influence of it!

Richard Shackleton.

LETTER XCIII.

7th month 1769.

By good education and good example they may become very valuable members of society,
and reflect honour upon us all.
But if the seeds of pride and vanity,
if indifference and insensibility about the most important matters be cherished,
instead of being carefully watched and picked out,
they may miscarry in the primary and essential points,
as 'tis to be feared others have done before them; and then,
what signify all the riches and grandeur of this fading, transitory life?
"`What will it profit a man if he gain the whole world and lose his own soul?`"
Children in general,
(and children of such promising parts in particular) are a very important,
arduous charge: the subjects of solicitous, weighty care;
a forcible memento to us to be living, powerful lessons of example to them; coinciding,
and cooperating with the precepts, cautions and restraints,
which as we steadily and singly wait for it,
the Author of all our right abilities may be pleased to furnish us with wisdom to administer,
in their place and season.
Even the heathen poet was sensible of the forcible effect of example on children,
when he says, "`Maxima debetur pueris reverentia.`"

Richard Shackleton.

LETTER XCIV.

8th month 1769.

I have many warm wishes for some of `'s children; they are near and dear to me.
Indeed I cannot help rejoicing at times,
at the beautiful prospect there is even among my own acquaintance,
and within that (comparatively) narrow circle, of a number of devoted youth,
who are caught in the gospel-net,
whose eyes growing dim as to the splendour and gaiety of this world,
who have been happily enamoured of sovereign beauty and excellence,
and have in their hearts chosen that good pari,
which I heartily pray may never be taken (by the adversary or his agents) from them.

Richard Shackleton.

LETTER XCV.

9th month 1769.

I make no doubt but you have had your head, heart,
and hands much engaged about our friend`'s troubles.
We could not be unconcerned in a matter so affecting to a family,
for whom we entertain a particular regard.
We owe him the sympathy of our spirits;
and for ourselves we may extract instruction and caution from his misfortune.
There is teaching in it.
This world is fluctuating and unstable, and its riches uncertain and perishing.
It is but a passage for us to another country, which is unchangeable,
and where our lot will be fixed and permanent.--Great then certainly should be our care,
that we travel steadily in the right road, which leads to perpetual happiness;
and that we lay up for ourselves treasures which wax not old,
and riches which admit not of fortuitous diminution, or decay.
These, or such like, I doubt not,
are the solid reflections which you have often had occasion to make,
on observing many events of this kind.
May they all work together for good to our afflicted friends,
and to us who bear a part in their affliction.

Richard Shackleton.

LETTER XCVI.

2nd month 1770.

How my poor mind delights to see the children of the heavenly
Father coming forward in the experience of his love;
bowing under his refining, purging power,
and submitting their necks to the yoke of Christ!--
Some such I think we have in this village,
to my great consolation in the midst of a variety of distress which I have to pass through,
and with these I have near unity and fellowship; indeed, my dear friend,
where there is not something of this savour to be felt,
conversation and company is to me often very insipid.
When I had the pleasure of being under your hospitable roof,
there did not open much way for converse of this sort; nevertheless, I could not but,
with particular satisfaction,
observe your willingness to dedicate your abilities to the service of the church there.
I am glad thereat, because I believe it to be an acceptable sacrifice,
when we offer and render up our best, though the best seems to us of little value.
Let us continue, dear friend,
to hold ourselves ready to do any little service which may be required of us:
let us diligently wait, and fervently pray for wisdom, that we may ever be preserved,
doing all we can, in our little sphere of action, for the truth, and nothing against it:
that so we may obtain the blessing, which alone can sweeten the cup of life,
and even takes away the bitter from the cup of death.

Richard Shackleton.

LETTER XCVII.

3rd month 1770.

I don`'t love dealing in hyperboles when I am about writing sober sense in prose;
and besides I know that it is not politic to be too lavish in commendation.
+++_________+++ is near my heart in my best seasons: she bends to the root of life,
and is engaged to make a sacrifice of one little thing after another,
sacrifices which do not cost her nought;
but which are made in the cross to the natural inclination,
and however trivial or unnecessary they may seem to some,
are accepted of him by whom our actions are weighed.
O these little foxes; what prejudice they do the tender vines!
Be it our care, my dear friend, to take them,
to lay our hand upon them when we see them in ourselves and families;
for they have done much hurt in the vineyard.
We see none of those who allow and indulge them,
come forward in strength and goodly stature,
bearing fruit to the praise of the good Husbandman,
and the help and edification of others:
but as empty vines bringing forth fruit to themselves,
to whom cannot be applied that encouraging expression of the apostle,
you have your fruit unto holiness, and the end everlasting life.

Richard Shackleton.

LETTER XCVIII.

5th month 1770.

People are too apt to dwell upon the disagreeable part of a character;
they do not make sufficient allowance for difference of humour, temper, opinion,
etc.-- Too many are not satisfied with feeding on this serpent`'s food themselves,
but they hand of it to others: the wife often, for lack of better conversation,
gives of it to the husband; he to his associates;
and so the sweet harmony of good neighbourhood is spoiled;
there is no cordiality of affection; and the friendship is only nominal,
(concordia discors).
The precious truth, which is the panacea of human life,
is the only effectual remedy for this evil; as it prevails in the mind,
it teaches (and qualifies too) to love as brethren.
May this root of life eternal, my dear friend,
more and more fasten in the ground of our hearts.
We shall now in the meridian, and if we live to the decline of life,
we shall still find this our best and surest support.
Our ever swerving from it was the original cause of our past errors,
and the troublesome consequences which attended them.
On our regaining it depends our present, and the earnest of our future, real happiness.

Richard Shackleton.

LETTER XCIX.

6th month 1770.

I Was glad to hear that you got something done with those litigious people
at +++________+++. Perhaps if the root of bitterness be not entirely eradicated,
yet what is left may die in the ground.
Cut a thing often down when it springs up, and it weakens its very root,
and at last it decays.
However the less thanks to them who will not help themselves;
who bind heavy burdens upon others, and will not lend a finger to remove them;
the less they will feel in themselves of the blessing which attends peace,
and the conciliators of peace.
Indeed I think it a happy circumstance, that there is no more litigation than there is,
among those who profess with us;
so few have about them the healing virtue which is most efficacious in these disorders;
because so few press through the crowd of opposing things,
with humility and faith to touch the lowest skirt of his garment,
from whom virtue proceeds.
I lament, dear friend, that a cause of the greatest importance to mankind,
should be so voluntarily deserted by many to whom
the Almighty has been manifold in his liberality,
whose situation and whose talents, properly disciplined and sanctified,
might render them serviceable in the church of Christ,
while they are vilely prostituted to the world;
at the same time that a multitude sit down contented
with a bare profession of belonging to a society,
whose principles they are very little acquainted with,
and to whose fame and character(which should be bright and
illustrious among the nations) they add very little,
if they take not away very much from it by their visible conduct.
Yet, thanks to the merciful Creator! who has not wholly repudiated his people,
though they have in the general allowed themselves to be defiled by other lovers;
there are to my certain knowledge (and I rejoice
in the prospect of it) several up and down,
whose names are respectable among men,
who yet have given up these names to serve as volunteers on the side,
and under the banner of Christ.
I know upon what ground I speak it.
Though separated in body from some of them, I am not so in spirit.
In my hours of retirement I have repeatedly found them, and you also, my dear friend,
among them.
I speak not only of past, but of late feelings.
Some indeed have not advanced with that steady pace
which becomes those who rank with the Lord`'s host,
and wear his eternal badge: they have received of his bounty,
and said they would enlist in his service;
but not being frequent enough among their fellow-soldiers,
nor sufficiently observing their Captain, and keeping near the standard,
they have halted (as between two opinions) fallen back, and lost ground:
so came not forward in the service which was designed,
for lack of learning the exercise and discipline at home,
and meeting frequently with their fellows in rank abroad.
"`Felix quern faciunt aliena pericula cautum.`"

Richard Shackleton.

LETTER C.

9th month 1770.

I Feel a nearness which words cannot fully set forth,
and which I believe would not be felt,
if we were not in measure preserved to be near the truth.
The Lord grant that it may ever be the bond of our fellowship,
and then our friendship will not be only nominal and worldly,
but we may be of use and strength to each other in
some of the conflicts which belong to this difficult,
dangerous state of existence;
and many indeed are the conflicts and besetments which appertain to it.
Our own safe stepping, and the preservation of our families,
much depend upon keeping near their chiefest good; then a wider circle,
the welfare of the Christian society, of which we are members;
and a farther anxious concern for the happiness of our brethren and sisters,
the whole race of mankind the world over, to whom we are very closely allied;
being all made of one blood by the same great hand.
Too many spend little thought about these arduous engagements and relative duties;
but for my part,
I think it is highly becoming a rational mind to look forwards towards a future existence,
and labour diligently after obtaining an evidence,
an earnest of an inheritance everlasting, incorruptible, and full of glory;
seeing that our stay here is so short, so uncertain, and attended with manifold troubles.

Richard Shackleton.

LETTER CL

10th month 1770.
Health is an invaluable blessing; yet even the lack of it has its use.
By that (or rather for that) we are deeply bound in gratitude
to the Giver of every good and perfect gift:
by this we are deeply humbled under a sense of the
weakness and misery to which our nature is liable,
and we feel a necessity to prostrate ourselves in humble application to him,
in whom is all-sufficient help.
I hear since your last, that poor +++________+++ has made his exit.
These documents (as you justly remark) should quicken our attention to a timely preparation.
Indeed there is manifold wisdom in the frequent contemplation of this great event:
it helps to humble, to rescind the too great luxuriance of a sportive imagination,
to form in us a right comparative estimation of the present and the future,
to wean our attachment from a place,
where we are to have so short and uncertain a residence,
and incite us diligently to seek for an earnest, a well grounded hope,
an assurance of an inheritance among the saints in light.

Richard Shackleton.

LETTER CII.

11th month 1770.

Since I received yours, I have attended the national meeting,
and from what I experienced in sundry of the sittings thereof,
am still more confirmed in sentiment, that the glory, life, power,
(or by whatever name we may call that which formerly overshadowed
the assemblies of our predecessors) has greatly departed from us,
collectively considered in this day.
It is a reflection which should cover our spirits with mourning; for no nation,
or people, or individual person, can suffer a more intimate loss,
than the loss of divine favour.
It should also deeply engage such of us as have been mercifully preserved,
yet to feel some little stirrings of life, to cherish, with all diligence,
this precious sense, that it may more and more increase in our hearts;
and by its spreading, expanding nature, catch hold of our nearest connections,
and kindle still more widely the sacred flame.
As long as we are a church militant, there will be, as there have been,
wrong spirits with which to conflict.
It needs must be, that offences come.
But by these encounters many virtues and ornaments of the
Christian church (the Lamb`'s wife) are manifestly exercised,
wisdom, temperance, meekness, patience, long-suffering, etc.
Oh, 'tis much to be lamented, that there is such a declension from the spirit,
and life and power of Christianity, in those called to revive the profession of it,
in life, and spirit and power.
My soul mourns deeply over the cause, because it is the cause of Christ Jesus;
a cause which rightly adhered to and rightly propagated among mankind,
would pull down the kingdom of satan, release from his unmerciful yoke,
which deluded mortals foolishly and servilely wear, and make them inexpressibly happy,
both in this world, and that which is to come.
It is with pleasure, my dear friend,
that I find my mind free to converse with you on these subjects.
It is a demonstration to me,
that your heart is in a good measure offered willingly to the service of the day.
If there have been too many years of inattention, let the time past be sufficient:
and by diligent waiting and frequent retirement, let the latter growth be strong,
vigorous, and lasting.
Feeling, from time to time, after that power which causes a fresh dedication of all,
you will not only witness a getting dominion over these
weaknesses and foibles which have too easily beset,
and a growing in the saving experience of good,
but your inward peace and domestic happiness will be also increased
by seeing the spreading of the same divine virtue in your family;
and those who by the ties of nature and blood are near,
will be made still nearer and dearer by the bond of a spiritual relationship.

Richard Shackleton.

LETTER CHI.

6th month 1771.

He lies composed at present, often lifts up his hands,
and waits the appointed time 'till the great change comes.
Indeed the angel of death seems near his couch,
but the angel of the divine presence attends likewise in this last and sharpest trial.
'Tis good to be near him, because divine goodness is near him also.
How long it may please the great Creator,
that his excellent spirit shall continue in his poor emaciated body, I know not,
but it looks as if it would not be many days.

Richard Shackleton.

LETTER CIV.

11th month 1771.

I Hope this will find you safe arrived at home,
and that home has an agreeable relish after your long peregrination;
it is one of the advantages that accrues from travelling,
that we return with a renovation of keen appetite for our domestic satisfactions.
Indeed it is great cause of thankfulness to him that sits the solitary in families,
that some of us enjoy these satisfactions in so great a degree.
I wish we may be enabled more and more to devote ourselves,
and all that appertains to us, to the service of the cause of Truth in our generation,
remembering, every now and then, the station to which the church has appointed us,
and allowing this remembrance to be as a stay to our natural vivacity;
that by the inwardness of our spirits we may at the same time witness a growth in wisdom,
strength, and experience,
and live and walk lively examples and savoury documents to others.
This will make much for our peace in the midst of
the troubles which we must expect to meet with here,
and for our preparation to have admission some where, any where,
within the gates of that kingdom where the wicked cease from troubling,
and the weary are at rest.

Richard Shackleton.

LETTER CV.

12th month 1771.

Alas! my friend, this is a day of weakness and distress, a day of stripping and famine.
It greatly behooves us to gird up the loins of our minds and be sober:
that if the Master shall please to bid us do anything in his house,
we may be ready to do it, and thereby obtain his approbation,
which is of more value than the smiles and favour of unstable men.
For my part, I think it is disreputable (humanly speaking) to be indifferent in,
or desert, or betray a good cause,
which we have avowed and confederated with others to support and maintain;
there is something very mean and ignoble in being false to one`'s trust,
and deceiving one`'s associates with whom we have
been linked together by sacred and solemn ties.
But when this cause is no less than that of Christianity itself,
the showing it forth by its fruits in our lives and conduct,
and the spreading of it among men, through the qualifications of the spirit;
as it is of the highest importance to be faithful to it,
for our own sake and the sakes of others,
so it is of the most dangerous consequence to act against it.
"`For, verily I say unto you, till heaven and earth pass,
one jot or one tittle shall in no way pass from the law till all be fulfilled.
Whosoever, therefore, shall break one of these least commandments,
and shall teach men so, he shall be called the least in the kingdom of heaven;
but whosoever shall do and teach them (here is conduct and preaching
united) the same shall be called great in the kingdom of heaven.`"

Richard Shackleton.

LETTER CVI.

Thus one after another we are overtaken by some messenger
sent to summon us from time to eternity! happy those who,
keeping straight accounts with their Maker,
witnessing daily the debt incurred by their trespasses, to be cancelled by his mercy,
in and through his beloved son, and his judgments, are in readiness to obey the summons.
Pain of body surely is enough for the poor creature to struggle with.
May we in that hour, dear friend, feel peace of mind,
that peace which results from the consciousness of
a life devoted not to serve ourselves only,
but principally to the cause of religion,
which in the end will be found to stand all her votaries
in best and most effectual stead.
A friend in need, is a friend indeed.

Richard Shackleton.

LETTER CVII.

10th month 1772.

Indeed we are on manifold accounts debtors to our great Benefactor,
and this query we should often know to pass through us,
"`Say what shall we render to him for all his benefits?`"
and as this inquiry is made in sincerity,
we shall be likely to see and feel what he calls for in return at our hands: and this,
my dear friends, will be found to be no less than our all.
Our very existence;
that this existence is not wretched and miserable with pain and trouble here;
that we have comfortable and endearing connection of natural and spiritual fellowship;
that we have the means of decent and reputable support for ourselves and families,
and that if happily we are favoured to feel and feed
upon anything of a divine and supernatural kind,
which enables us to rub through the dangers and difficulties
of this troublesome uncertain life,
and gives a gladdening hope of a joyful eternity;
all these are owing to the special grace and mere unmerited favour of our Creator,
upon whose providence as we entirely depend,
so it is our duty and true interest to resign and dedicate all, body, soul and spirit,
time and talents, to him and his service, as in the course of his wisdom,
and holy counsel, he shall call for them from us.
There is (in the confirmed apprehension of several) a visitation,
an invitation to the youth.
Some seem to have embraced it,
and to seek after the renewings of it upon their minds (without which they are not likely
to retain it savingly in their knowledge:) others bow down their heads as a bull-rush,
under the forcible weight of the copious gospel shower descending
from the instrumental vehicles of the clouds,
and anon raise them again to look about at the states of others,
or at the delusive splendours of a vain, deceitful world, to their hurt and hindrance:
and there are (it`'s to be feared) of such visited youth,
who have in their hearts departed from the sense of it,
and returned like the dog to his vomit,
or the sow that had been washed to wallow in the mire.
While I thus write, it has been repeatedly shown me, how carefully we,
who have arrived at the summit of the stage of conspicuous action,
and are seen in our several spheres, ought to handle the law and the testimony:
how careful we should be to let our conduct and conversation
shine instructively before all,
that we may not by any lightness (to which a constitutional
vivacity may bias us) give a kind of sanction,
or encouragement to such as are unsteadily sliding off the foundation
of inward conviction and chastening judgment in their own minds:
for indeed in my apprehension,
the failure to patiently learn these first rudiments of religion,
is the grand cause we have so few good scholars in the school of Christ.

Richard Shackleton,

LETTER CVIII.

1st month 1771.

Tis true his (+++_________+++`'s father) uniformly well-spent
life must afford him on the retrospection,
a conscious satisfaction; and I believe he has the purest and best consolations,
in as great degree and frequency as most men, yet he finds pain of body hard to bear,
and when the strength and flesh fail, and the gloomy path is begun to be trod,
nature shrinks at the approach of the final destruction of all that is visible,
and the best have occasion for all their best support to stand the shock, undaunted.
What then must the loose, the vain, the libertines,
who have given the lie by their conduct and conversation to a high and holy profession,
feel in that day and hour, when they have no oil in their lamps,
on treasure in store against that pinching time?

Richard Shackleton.

LETTER CIX.

7th month 1771.

He ( +++_______+++`'s father) lived in watchful fear and circumspection:
he died in a holy confidence, triumphing over death and hell,
and yielding only that which was mortal and perishable to the grave.
The last words which he was heard to utter (and that only a short time before his departure)
were expressive of the help and comfort which he felt in the last extremity.
And when nature could not produce intelligible words,
his motion and gesture (well known to his intimates) were such as he would
often use when his spirit was raised in the dominion of the seed of life.
Since his translation, I feel to myself exceedingly weak,
sometimes greatly affected at this final separation, at other times more cheerful,
and thankful for the many domestic comforts remaining.

Richard Shackleton.

LETTER CX.

6th month 1772.

I doubt not but some of you wish for his return; but am also of opinion,
that besides the good accruing to them with whom he is present, by his presence,
advantages may also accrue to you, from whom he is absent, by his absence.
If you do not feel your strength, you feel your weakness,
and from this sense of necessity, and the uncertainty of instrumental aid,
I trust you look with anxious solicitude to him who sees in secret,
and is the only sure effectual help and supply of his people.

Richard Shackleton.

LETTER CXI.

12th month 1771.

Change is the condition of our nature and place;
and the support and consolation which is alone sufficient to give firmness to our spirits,
and bear them up through and over all the changes which may await us,
is the blessed and unchangeable Truth; which whoever in honest simplicity adheres unto,
he or she may pass through good report, or evil report, may be cried up, or cried down,
may please or displease, in the estimation of changeable mortals;
but the present and future reward of such, is and will be sure:
even that substantial peace which the world is not able to give,
by all its gratifications and smiles; nor to take away by its persecutions and frowns.
And whoever departs, in heart, from this blessed principle of truth,
and makes flesh (or these reasonings and schemes which belong to flesh,) his confidence,
however he may be censured or commended by short sighted men,
who judge from outward appearances, and see not the heart;
yet such in that state are not under the divine approbation, but displeasure;
and their end, without repentance, will be miserable.
I wish you all may be disposed to make choice of the good part;
I am persuaded if that was generally the case with you,
a fountain would be opened in your family, to wash and to bathe in,
to drink and to be refreshed at, to your general joy and gladness;
for the good-will of heaven has, I believe hovered over you,
with blessings ready to be poured into your hearts, if prepared to receive them.
And as to you the elder children of so highly-favoured a family,
on whose account my solemn offerings have been often made, what can I say to you,
which you do not know?
You have not lacked clear discoveries of duty;
you have been favoured both with instruction and correction:
by the same powerful touch of a divine finger,
you have conceived a disrelish for the vain, unsubstantial gratifications of the world,
and a relish for those solid comforts which are in the precious Truth.
For the sake of your own standing and growth in that which is good:
for the sake of the powerful efficacy and influence
of good example within your sphere of action,
I beseech you, my beloved friends, above all things, cultivate, the gracious visitations,
which you have before experienced by frequent retirement,
and therein diligently seek after a renewal thereof upon your spirits.
Avoid, as much as in you lies,
every thing which you find to unfit you for this holy commerce,
and let it be your principle watch and care to keep the vessel
clean (no matter how empty) which receives (when it pleases infinite
wisdom to communicate it) that most excellent treasure,
the joy of God`'s salvation.

Richard Shackleton.

LETTER CXII.

2nd month 1779.

Many changes happen in the course of time.
Nature in every part of it, within us and without us, is subject to change.
There is one principle of a spiritual kind, which changes not, neither waxes old,
nor decays.
Our spirits would do well to lay hold on it, to be leavened, regulated and guided by it.
We shall find no friend, no helper, no counsellor like it here, to steer us,
to sustain us through the perils and difficulties of this life;
pilot us safe through the dreadful gulf, terrible to human nature,
and launch us into that illimitable ocean of happiness which knows no shores.

Richard Shackleton.
