== Letters 136 &#8212; 138

[.letter-heading]
LETTER 136.

[.signed-section-context-open]
6th month 27th, 1760.

In a sense of that sympathy and union which renders the Church
of Christ a compact body I affectionately salute you.
I cannot doubt of the propriety of your mission to that part of the Lord`'s vineyard,^
footnote:[America]
and it is my desire,
that the wisdom and power of Truth may seal its own evidence on all your labours.
Though I apprehend myself a younger brother,
and now addressing myself to one who was in Christ before me,
permit me to offer to your consideration a few sentiments,
which have made impression usefully on my heart.

It is an awful thing to assume the name of the Lord`'s ambassador;
and I believe you consider it so:
from hence appear the obligations we are under to receive from him,
not only his instruction, but our credentials.
These will not be withheld, if we wait our Master`'s time; his sound will be certain,
and his discoveries clear; we shall not say, with Ahimaaz, when I ran there was a tumult,
but shall distinctly receive, and deliver our Master`'s message,
in his own wisdom and spirit.

In all our service, let us remember our Lord`'s dignity, and endeavour to maintain it,
according to the proportion of strength vouchsafed, in purity of life,
and singleness to him in our ministerial capacity, being empty without him,
and only filled with his fulness.

Let us learn to try the spirits, whether they be of God;
I have seen a danger of being taken by the passions;
the passionate preacher has affected the passionate hearer, both have been in raptures,
and neither of them profited.
This is a place I would endeavour to guard you in,
as I am apprehensive the emotions of your mind are sometimes strong and animated;
mistake not the warmth of passion for gospel authority;
the first is like the rattling thunder, which frights, but never hurts;
the last is like the lightning from the east, which illuminates, and, at times,
breaks through all opposition, and melts away every obstruction.
I know the integrity of your heart, and therefore, with unreserved freedom,
I remind you of these things.
May your Urim and Thummim be with the holy One! look carefully to him in all your goings,
so shall you dip your foot in oil when you tread on high places,
and the arms of your hands be strengthened by the mighty God of Jacob.
If deep poverty be your lot, be not disquieted,
neither pour forth your complaints to any mortal: have no confident but everlasting help;
I found it safe to wear my sackcloth on my loins,
and my best garments honestly and sparingly.

In the course of your passage, be courteous to all,
unless restrained by secret direction as to any particular; which has been my experience,
in some parts.
Let not affability enervate your mind,
nor lead from a steady superiority attending the faithful minister;
yet guard against a spirit which leads zealous people sometimes to say,
there is none righteous, no not one, and therein to overlook the hidden suffering seed.
Let your eye be in your head, so shall your goings be ordered of the Lord,
and be attended with peace to yourself, comfort to the living,
and general usefulness to the church.

Farewell!
May the Lord of all consolation be with you in every trial, support you by his arm,
enrich you by his grace, replenish you by his wisdom,
and comfort you by his rod and staff!

[.signed-section-signature]
Samuel Fothergill.

[.letter-heading]
LETTER 137.

[.signed-section-context-open]
2nd month 1st, 1678.

Our worthy friend and kinsman, who had been in a declining state for some time,
finished his course last sixth day night, and is to be interred tomorrow.
I have often been with him, to my humbling instruction.
His journeying for some time before his departure, was in the region and shadow of death.
I have sat by him, and accompanied his spirit, when the heavens were as brass,
he was seemingly excluded from good: this led to deep searching of heart, even,
as he said, into holes and corners he had not suspected.
He saw he had been short in the performance of that
service which Truth would have led him into,
had he been fully dedicated in heart, to know and do his Master`'s will.
But in adorable condescension he was visited afresh, and fed with a little bread,
when ready to faint; a degree of hope was revived;
a part of that crystal stream which is the sanctification
and consolation of the whole city of God,
arose in his soul; and increased from time to time,
until it became like the waters Ezekiel saw, issuing from the threshold,
a river pt swim in, a river that can never be passed!
The holy canopy was often over our spirits when I visited him, to my comfort;
but I never so fully understood the force of this remark,
"`if the righteous be scarcely saved...`"

The applause and esteem of the judicious and injudicious, regularity of conduct,
his arrival at Bethel, and the remembrance of many bedewing seasons,
all proved insufficient for his repose, and were among the heavens which might be shaken,
that that which cannot be shaken may remain.
He languished long in great pain previous to the separation of body and soul;
in which time it feelingly opened to my mind,
that had his spirit been more disentangled from the love of lawful things,
his warfare would have been more easily accomplished,
the fetters of mortality more easily broken,
and his spirit sooner have risen triumphant over death, hell, and the grave,
and on the wings of seraphic love have ascended to the realms of purity and peace.
But all is well.
He is admitted to a mansion of rest; and through his deep wadings,
we are instructed with all diligence to fill up the measure of revealed duty,
waiting for further discoveries of what may be the
will of the Lord our God concerning us.

[.signed-section-signature]
Samuel Fothergill.

[.letter-heading]
LETTER 138.

[.signed-section-context-open]
18th of 6th month 1768.

I am inclined to make use of an opportunity now presenting,
to send you the salutation of my most sincere love,
not without a sense of our heavenly Father`'s love,
with which I hope you are often comforted now in your declining years;
and favoured with the evidence in yourself, of having in your measure,
through Divine assistance, walked with God.
I need not attempt to express to you, the importance of such an evidence,
when the soul draws nigh her flight to the land from which there is no return.
It has been the mark for the prize in your view,
and I am thankful to feel my heart stirred up to follow such examples;
animated by their success, and the importance of the subject,
to use all diligence to fill up my duty, that I may finish my course with joy.

My shattered constitution often gives me instruction, and intimates the graves are ready:
yet it has been consistent with Divine mercy and wisdom, to raise me up again,
beyond my expectation: and I hope I am bettered by my affliction,
not only in what belongs to me, as an individual,
but also in that wherein I am joined by all the living,
in the view of the state of the church in most places;
the use I would have us make of this view, is to gird up the loins of our minds,
that our example may be a strong reproof to the unfaithful, and,
thus collected in spirit,
we may deeply feel after the putting forth of the Divine hand in service;
for though it can work effectually without instruments, yet it will also work by them;
and if the visited of God were enough devoted in heart to his service,
in all the manifestations of duty, we should have more useful instruments in the church.
But alas, for many, who, if they have followed to Bethel, content themselves there,
and attain not a double portion of that spirit, which those who steadily follow on,
even through Jordan, are favoured with.

This imperfect work bears undoubted traces of the Creator`'s hand,
but like half baked cakes,
they seem to me to be no inconsiderable eclipse to Zion`'s beauty,
and are often great obstructions in the way of others,
as such who neither enter the kingdom of God themselves, nor permits others.
Nevertheless, the God of the whole earth is mindful of his family,
and eminently favoured us in our last Yearly Meeting at London,
from which I returned much recruited in bodily strength,
and having my mind replenished with precious dew.

Salute, in my name, your son and daughter;
may those who are of the younger class look to the business of
the day! the building up of the Lord`'s house more than their own;
unto him all our utmost dedication of spirit, time and labour, is due.
My dear love attends you all.

[.signed-section-signature]
Samuel Fothergill.

[.the-end]
End of Volume I.
