== Letters XXIV &mdash; XXXVII

LETTER XXIV.

Esteemed Friend,

I am concerned that it so falls out I cannot be at home personally to bid you farewell,
and wish you a good journey.
However, the travail of my soul is for the help, strength,
and safety of all our heavenly Father`'s children,
that they may be so wisely conducted in all things, as to know the returns of peace,
and feel the unity of the spirit, and of the body.

If we are little enough in our own eyes, we shall know divine strength in our weakness;
but when any apprehension of our strength and wisdom possesses the mind, weakness,
and loss in every respect ensue.
You have my good wishes in the present concern;^
footnote:[A visit to Friends in America.]
it is indeed a weighty undertaking,
and requires a double portion of the spirit to go through.
Let your dependance be upon the renewings of divine help,
and all your movement in the gospel spirit.
Seek after the simplicity of truth, and its littleness: you are going among a people,
many of whom have understanding hearts, and can discern wisely between spirit and Spirit,
between sound and substance; this I mention for your encouragement,
if you are single-hearted.

May best wisdom direct you in all your steps, preserve you solid in your spirit,
lively in your ministry, wise and discerning in your conduct towards all,
and upright and exemplary in your conversation!
I am your sincere friend,

Samuel Fothergill.

LETTER XXV.

12th month 1769.

When I was informed of your draft towards New England at this season of the year,
I felt a near sympathy with you, as also with your new companion;
looking over the stages and wide waters,
and thinking on the hard frost and high winds which are usual in the winter,
the journey has appeared difficult;
but my mind was turned to him who made and commands the winds and the waters;
whose Providence is over the ravens and the sparrows;
I believe you understand his language, and I trust your ear will be attentive to him,
and in this there is safety in the greatest difficulties.

"`He that believes makes not haste,`" is a portion of doctrine
which I am inclined to recommend to you in this journey;
should frozen rivers, or storms,
sometimes prevent your going forward so fast as you could desire,
it may be that you will find a service in tarrying among a people,
whose company may not be, in all respects, agreeable.
I remember the way in which Paul made a visit to the island of Malta,
was contrary to his own mind, and yet by means of it,
the father of Publius was healed of his fever, and many cured of their infirmities.

Farewell, my dear friend, from

John Woolman.

LETTER XXVI.

Philadelphia, 26th Second month 1761

Dear Friend,

Friends here enquire after you with great respect, and,
I believe many sympathize with you,
both in your inward and outward travels and conflicts,
with a comfortable hope of your preservation.
Your anxiety to accomplish the journey speedily may give you pain in future,
unless you carefully watch, that your movements be not faster than true wisdom dictates.
It is also necessary to consider that we have bodies as well as souls,
and that there is a care due to them.
I wish not by this to encourage your moving too slowly, for,
I believe diligence is commendable;
and those who have performed their duty with watchfulness, and care, and not loitered,
have left as sweet impression on the minds of their friends as some who have acted otherwise;
and I expect your observations in your travels, have convinced you of this.
I am your affectionate friend,

John Pemberton.

LETTER XXVII.

London, 18th Fifth month 1761.

Dear Friend,

Upon my coming up here to attend the service of the yearly meeting,
I was not a little rejoiced to find that your getting to
London was just in time to save your passage to America,
in the vessel proposed, with such agreeable company, and that the voyage was prosperous.

When I have looked back at these and other circumstances which I forbear to mention,
I have been confirmed in my mind that your concern was right in this great undertaking,
and rightly timed;
and I doubt not this has been your experience since you crossed the great ocean.
Now dear friend,
may your steppings along in service be with a single eye to him who has called you forth,
even Christ the great head of the church,
who is able to furnish with wisdom and strength in every
exercise which you may find yourself drawn into.
Thus you will come to discharge the trust reposed in you,
in a manner that will tend to stir up the lukewarm and indolent,
and comfort the feeble-minded; as also procure the reward of peace in your own bosom,
which, in due time, may accompany you across the mighty waters to your habitation.

Friends in this city are generally well:
it is true there are many under our name who do not trouble themselves much about religion;
yet a number are preserved who prefer the cause of truth above every consideration;
and that this concern may spread and increase to
the enlargement of the borders of our Zion,
is the desire of him who, with the salutation of brotherly affection,
remains your sincere friend,

Isaac Wilson.

LETTER XXVIII.

To A Friend In England, +++[+++Translated from the Dutch.]

7th 3rd month 1769.

Dear Friend,

I received yours of the 15th 11th month, last which was as a precious medicine to me,
after the great loss,
with which the Lord has visited me in the removal of my dear companion,
who was my help in old age, my comforter in oppression, my partner in adversity: yes,
should I attempt to say, what help, comfort, and strength we mutually had, in each other,
both inwardly and outwardly, my heart would be overcome with grief,
in considering the loss of her company.

I shall therefore only say, in the words of king Solomon,
"`The price of a virtuous woman is far above rubies,
the heart of her husband does safely trust in her: she will do him good, and not evil,
all the days of her life.`"

After a sickness of about three weeks, my beloved wife rested sweetly in the Lord,
in the sixty-fourth year of her age, and forty-second of our marriage.
She was very still and retired in her illness, and till the last day of her life,
the doctors thought she mended, from time to time;
but on that day they observed the contrary, which affected us so much the more:
and when she felt death approaching, she said, "`I have done,
O Father!`" thus cheerfully resigning her spirit to her Creator,
from whom it was received.

In her life she was of a grave disposition,
and her greatest delight was to meditate on the law of the Lord,
and to declare it to others,
bringing forth from the good treasures of her heart
that which was edifying to her friends and neighbours;
she manifested herself to be a true pillar in the temple of the Lord;
not decking herself with outward array,
but her adorning consisted in the incorruptible ornament of meekness,
wherewith the hidden man of the heart was filled.
In chastity, temperance, and good works, even as the holy women of old,
being established in the fear of the Lord.

Her ministry was not with words beautiful, according to the wisdom of man, nevertheless,
they were weighty, penetrating, and pleasant to the upright-minded,
flowing from the power of God,
to the refreshment of the mournful travellers towards Zion.
She frequently recommended to the inward operation of the saving word,
the light of Christ, in order to walking therein.
And, in this labour of the gospel she continued many years.
The wild, unruly people, who attended our meetings,
were often restrained by the divine power, in her speaking.

At length it has pleased the Lord to release her from her charge,
that she might rest from her labour, leaving to us, a savour of sweetness behind her;
yet it cannot be otherwise than a heavy stroke,
because the Lord had bestowed her upon me in his love and fatherly kindness,
in the early part of our time; it becomes us to say, Lord,
your will be done in humble submission to the dispensations of his providence:
he is pleased to take that from us which we love most besides him,
that we should be more weaned from the love of the world,
and come to have our love fixed on him.

It was pleasant to me to perceive your brotherly concern, and sympathy with us,
in our loss, as well on my account, as for our little society; I say loss, for so it is,
having lost two friends who appeared among us in the ministry, in one year; namely,
my dear wife, and Abram Harmens, whose wife is likewise deceased.
Thus the number of friends here is greatly lessened; yet, through divine favour,
we often have very comfortable, though silent meetings; and we trust in that arm,
which has hitherto been our defender.

I rest in true brotherly love and hearty well-wishing, your affectionate friend,

John Vander Wert.

LETTER XXIX.

My Dear Friend,

With desires for your advancement in the way of self-denial,
I shall speak a little of the dealings of the Almighty with me,
in the circumstances you have hinted at, namely, That when my spirit has been tendered,
and humbled, and brought into true contrition, I know it is of the Lord`'s goodness.
This operation in the soul, can be the effect of no other power,
because it lifts the soul to God, at whose presence the hills melt like wax,
the mountains of opposition are laid low, and the valleys exalted;
the rough ways are made smooth, bitter cups are sweetened,
the bread of life is dispensed to our souls,
and we are helped to draw water as from the wells of salvation.
These seasons of the love of God, I have thought,
are intended to excite our love and obedience to him,
and we are hereby made willing to submit to every dispensation, which he, in his wisdom,
is pleased to allot us: we can then say, "`Not my will, but your will be done, O God.`"
We are helped to draw near to the throne of grace,
craving still to obtain mercy and help in time of need.

But let us remember times and seasons are in the hand of the Lord,
and he orders all things as he sees best for us; there are times of mourning,
as well as rejoicing: of want, as well as plenty;
of withdrawing his good presence to try our love and obedience:
and this has been the experience of all God`'s children.
We are subject to changes, and have need to be prepared for them;
in times of prosperity we are apt to take up our rest, and forget the dangers of the way.
But, as it was with Israel of old, we are not to rest in the wilderness,
though fed with food from heaven, but to be making advances in our spiritual journey;
still striving for the victory over enemies,
which oppose our progress to the land of rest; where may we happily meet,
ever more to praise and adore our gracious God,
and the Lamb who has washed us in his precious blood.
So prays your affectionate friend,

Sophia Hume.

LETTER XXX.

Bromley, 2nd Twelfth month 1736.

Dear Friend,

When I was last in the north, I heard of you in several places,
as one who had turned your face Zionwards;
having seen the emptiness of earthly enjoyments.

The prayer of my mind is to the Almighty on your account,
that he would be pleased to favour you with such a degree of his love,
as might enable you to take up a holy resolution to follow
your Lord and Saviour in singleness of heart,
according to his leading; though it may be in the way of affliction and sorrow, yet,
as this good resolution is kepi to, still to follow him,
who in his great love has visited your soul; he will set before you an open door,
which no man can shut, by which your poor soul may enter in, and find rest in him,
who is the true rest of his people.
And the nearer you dwell to him, in spirit,
the more will you be made to partake of that sweet
peace which he gives to his obedient followers;
and the more will you come to be acquainted with his heavenly teachings,
in which there is spirit, and life, whereby the soul is put into a capacity,
both to know and do those things which belong to its everlasting peace:
not regarding the world, or the vanities of it,
but looking forward towards that which is durable and excellent in glory.

It is my desire for you, that your eye may be more and more fixed on heavenly things,
and that you may daily know a drinking of the well of salvation,
which Christ has opened in the hearts of true believers;
that thus you might be wholly weaned from the breast of this world,
and might drink abundantly of that joy which flows from the breasts
of Divine consolation in Christ our bishop and true shepherd.

To his protection I commit you, with my own soul, and remain your companion and sister,
as you follow the Lamb in patience and tribulation,

Deborah Bell.

P+++.+++ S.--I hear your freedom, as to the outward, is enlarged; may your freedom,
and liberty of soul,
daily increase through the power of him that is come to set his
children free to serve him in simplicity and singleness of heart.

LETTER XXXI.

Balby, near Doncaster.

Dear Friend,

The reading your letter gave me great satisfaction,
as it informs me you are treated with less severity than heretofore.

Though your education has been among those who, for lack of knowing our principles,
may have imbibed wrong notions of us, yet charity induces me to hope,
your relations endeavours to prevent your joining in society with us,
are merely the effect of their good-will and esteem for you:
this should lead them to think, that no one`'s conscience ought to be forced;
and that it is necessary, in matters of religion, we should choose for ourselves;
and be left to act according to our own judgment.
Our Saviour Jesus Christ did not seek to plant bis church by force,
or use violence towards the Jews, to cause them to submit to his doctrine.

If you keep your mind fixed upon God,
and in humility call upon him to lead you in the way of the cross,
he will more and more make known his mind and will,
and give you to see what he is pleased with, and what offends him.
He knows your needs; and as you hunger and thirst after him,
and long to be fed by the bread which he gives,
he will in due time satisfy the desires of your soul,
and make you a sharer with his people of the good things of his house.
Be obedient to his call, give up your heart to God, without reserve,
save nothing alive in you, which he has appointed for death.
Be as passive clay in the hand of the potter;
then he will reconcile and make all things easy, and form you as a vessel to his praise.

This, from your real friend,

Thomas Smith.

LETTER XXXII.

I have had a deep fellow-feeling with you in your late affliction, and a secret hope,
that it might please the Father of mercies to raise you up,
and sanctify your troubles to you:
that being more fully acquainted with that way which the world calls foolishness,
you may obtain the clothing of divine fortitude,
and be strengthened to resist the spirit which leads from the simplicity of the truth.

We may find ourselves crippled,
and halting from a strong bias to things which are pleasant and easy to be come at,
so that it is to appearance impossible to advance forward;
but things impossible with man, are possible with God;
and our wills being subjected to the divine will, all temptations are surmountable.
This work of refinement is compared to the mineral in the furnace, which,
through fervent heat, is reduced from its original state,
and a separation made between the precious and the vile: it is declared of Christ,
that by the operation of his spirit, he shall sit as a refiner and purifier of silver,
and shall purify the sons of Levi, and purge them as gold and silver,
that they may offer unto the Lord an offering in righteousness.
(Mal.
iii.)

By these comparisons we are instructed in the necessity
of the operation of the hand of God upon us,
to prepare our hearts truly to submit to him, and to manifest our submission,
by turning away from that spirit, in all its workings, which is not of him.

To forward this work, the all-wise God is pleased sometimes, by outward distress,
to bring us near the gates of death; that life being made painful and afflicting,
and the prospect of eternity before us, all earthly hands may be loosened;
and the mind prepared for that deep and sacred instruction,
which otherwise would not be received.
As kind parents love their children, and delight in their happiness, so he,
who is perfect goodness, in sending abroad mortal contagions,
does assuredly direct their use.
Are the righteous removed by them?
Their change is happy.
Are the wicked taken away in their wickedness?
The Almighty is clear.
Do we pass through great bitterness, and suffering, and yet recover?
It is intended that we should be more purged from dross, and our ear opened to discipline.

And now, after your sore affliction, and doubts of recovery, as you are again restored,
forget not him who has helped you, but in humble gratitude, hold fast his instruction;
by which you are shown the bypaths that lead from the firm foundation.
I am sensible of the dangers to which you are exposed, from a variety of company,
in transacting your business; having painfully felt the force of interaction with men,
deeply rooted in an earthly mind, I can sympathize with you and others in such conflicts,
in that much weakness still attends me.

I find, that to be a fool, as to worldly wisdom, and to commit my cause unto God,
not fearing to displease men, who take offence at the simplicity of truth,
is the way to remain unmoved.
The fear of man brings a snare; by halting in our duty,
and giving back in times of trial, our hands grow weaker;
our spirits get mingled with the people; our ears grow dull,
as to hearing the language of the true shepherd, so that,
when we look at the way of the sincere followers of Christ,
it seems as if it was not for us to walk in their footsteps.

There is a love clothes my mind, while I am writing this,
which is superior to all expression;
and my heart is open to encourage you to a holy emulation,
to advance forward in Christian firmness.

Humility is a strong bulwark, and as we enter into it we find safety.
Being unclothed of our own wisdom, and knowing the abasement of the creature,
therein we find that life to arise, which gives health and vigour to us.

John Woolman.

LETTER XXXIII.

Exeter, 14th 8th month 1747.

Dear Friend,

I have often had you, and several other friends of Leominster, in my remembrance,
since I was at your yearly meeting;
and the sense I had concerning the state of some young friends there, was,
that the Lord`'s hand has been upon you for good; to regulate your conduct,
so that you may shine as lights in your several departments; and show forth his praise,
who has called you out of darkness, into his marvellous light;
and has set on your countenances the self-denying
impressions of the image of Jesus Christ.
May you also evidence to the world,
by blessed degrees of the meekness of the Lamb of God, that you belong to his fold;
and are encompassed about with the pale of his salvation, where neither wolf, nor lion,
or any other beast of prey, can ever destroy.
For this know, that no destroyer can hurl the sheep and lambs of Christ,
as they abide in God`'s holy mount, where true safety is.
Happy are those who gather to this, and dwell therein; the Lord is their refuge,
and strength, their present help in trouble;
even though the powers of the earth may be removed,
and all the force established by human policy, should be dashed in pieces,
and brought to nought by the confusion of national, unstable powers;
yet the meek inhabitants of God`'s Mount Zion shall endure the shock,
how terrible soever it may be to the workers of iniquity.
They shall have recourse to that celestial river,
the streams whereof make glad the city of our God;
and this shall be the seed which the Lord will bless, as his generation, born from above,
raised up through the Lord`'s power to replenish the earth with the righteousness,
holiness and purity of the saints, restored to them through faith in the Son of God.

The sense of God`'s lovingkindness and regard to his sheep and lambs,
who hear his voice, and follow him,
bows all the faculties of my soul into reverent thankfulness and praise,
to him who is over all worthy forever and ever.

As the design of the Father of Mercies is to dignify the church of the
New Testament with such precious gifts and graces of his beloved Son,
as may demonstrate the virtue of his power to the gathering the scattered in Israel,
and dispersed in Judah, to his light and truth in themselves,
until the fulness of the Gentiles be come in; it behooves you, and me,
and all the Lord`'s visited people, to see that we walk in this light;
that we live in subjection and obedience to the present discoveries thereof,
both in doing and in suffering,
without postponing our obedience to any time beyond the present requirings of his spirit.

When the waters of life move inwardly in our Christian assemblies to our refreshment,
we are made glad; if they rest there,
the refreshment and comfort is only for our own growth, and establishment in the truth,
for which we have cause to be thankful and circumspect.
Yet if the divine virtue with which the soul is replenished is
accompanied with a concern for the refreshment of others also,
then the doctrine contained in this special visitation of God,
under the direction of heavenly wisdom, (for which we have need to ask,
that all may be done to the praise of God,
and edification of his church) belongs to the brethren and sisters then present;
and is like bread, to be broken, and dispensed to others, at the divine command,
that they may feed with us, and be satisfied with the present provision of our God;
and may be enabled to gather up the fragments, and keep them in memory,
till such times as these remains may be renewedly blessed to them.

I sate down to salute you in a spring of love,
but in such poverty as teaches the soul to look to the Lord, that he may be our helper.
In this love I freely impart to you what has been received,
leaving it to the divine blessing to be disposed of for your advantage.

I bid you farewell, remaining a well wisher to all,

Lawford Godfrey.

LETTER.
XXXIV.

The Lord is the all-wise disposer of events.
He makes rich, and makes poor.
He exalts, and abases, at his pleasure.
Though I most firmly believe,
that God does not willingly afflict or grieve the children of men;
that he is a God of mercy, and knows all our needs,
and will add all which his wisdom sees best to those who first seek his kingdom,
and the righteousness thereof; yet I am obliged to confess with respect to his outward,
as well as inward administrations of prosperity and adversity,
his judgments are unsearchable, and his ways past finding out.

It is obvious, that trouble is often the result of our own perverseness,
and arises from the determination of an unsanctified will;
the imprudence of our undertakings, and folly of our choice;
but then it is equally evident, that it sometimes arises from a different source,
and must necessarily be resolved into the wise and inscrutable providence of God.
What shall we say of Job, that perfect man`'s condition?
Of the hunger, thirst, and nakedness of the apostles?
Of those who wandered about in sheep-skins, and goat-skins, destitute and afflicted,
of whom the world was not worthy; and of the Holy Jesus,
who had not where to lay his head?

The condition of Christians in the early ages was straight, and since,
of many of the first reformers, who have been true successors of the apostles;
treated as the offscouring of all things; to whom indeed the earth has been as iron,
though the heavens have not been as brass.
Far be it from me to conclude these to be unhappy, or think they had cause to complain;
surely they were blessed, and received in this life, recompense, a thousand fold,
for all their sufferings.
But I instance them to show, that even the favourites of heaven,
as well as those who through disobedience frustrate the designs of God`'s mercy, may be,
and sometimes are, tried with a scarcity of the outward accommodations of this life.

Riches are not certain marks of divine favour,
nor prosperity an evidence that our ways please God.
Does he not sometimes give men their hearts desire,
and withal send leanness into their souls?
We are apt to call providences by wrong names.
Afflictions we call evils, and riches we call blessings, when for once they prove so,
it is to be feared they are a thousand times more often to the possessors a judgment.
The distresses and troubles of outward Israel, were often permitted in mercy,
when the people, in fulness, and prosperity, had revolted from God,
in order to bring them back again to him, so as to trust in him,
and have their dependence upon him.
And if this be the gracious design of the Almighty now, in the administration of crosses,
and adversity to us, they deserve to be considered as evidences of his merciful regard;
who, in this severe, yet more intelligible language to earthly hearts,
is seeking to convince us of our dependence upon him, and that it is he who can bless,
or blast, all our endeavours.

I have often thought that if we were more attentive
to the secret intimations of the great counsellor,
who speaks from heaven in our hearts,
we should make it less necessary for the Lord to
speak to us so frequently in the language of affliction.
By attending to this good guide, we should avoid every snare,
and be enabled to go forward in the line of duty,
and be contented in the lot of our appointment;
though our dwelling might be with the lowly: yet, divested of anxious care,
we should rest secure in his providence, who numbers the hairs of our head,
clothes the lilies with transcending beauty, and hears the young ravens when the cry.

If we are concerned to worship the Lord our God,
to bless him in the lot which he has assigned us, he will bless our bread, and our water;
and, if consistent with the designs of his wisdom, he can increase our corn and oil,
and multiply our gold and silver.
It is true, that cross occurrences, and afflictions,
have not always their desired or intended effects.
The Lord complained of a people formerly, saying, "`I sent unto them blasting and mildew,
and yet they will not heed me.
I have smitten them, and they refused to receive instruction.`"

There is an aptness in the human mind,
(which looks not beyond things that are natural) to rest in second causes,
and blind to the discriminating providence of the Most High,
to fix the blame on secondary agents; but surely affliction comes not from the dust,
neither does trouble spring out of the ground.
Oh, that in the medium of divine light we might look up to God:
therein we should discover the secret turnings of the holy hand in these things;
for I am persuaded, that whatever is permitted to try us, whether inwardly, or outwardly,
it is from the dispensation of unerring wisdom and goodness, and the best for us,
in our present state of mind, and consistent with our chiefest good.

What cause have we therefore to commit ourselves wholly to him, and to bless his name,
in every dispensation; who is the sole arbitrator of heaven, and earth;
who superintends the universe; whose goodness and power are equal;
who knows all situations, and is graciously administering to every one of us,
in uniform mercy, what is most suitable to our states;
and all for this most desirable purpose, to gather us to himself,
who is the fullness of blessing and of life.

LETTER XXXV.

12th Twelfth month 1776.

Dear Friend,

In a degree of that love, which neither time nor outward distance,
nor death can dissolve: wherein such sympathy is felt,
that we can rejoice with those who rejoice, and weep with those who weep:
in the renewings of this love, you have been often brought to my remembrance of late,
and there has been presented to my mind some remarks,
which I have liberty to offer to your consideration.

When that deeply humbled and tried servant of the Lord, David,
was favoured to partake of the refreshing streams of that river,
whose source is the ocean of everlasting love;
when his feet were set on a rock that was higher than he;
and the new song was put into his mouth;
at these seasons he thought his mountain stood strong,
and was ready to say in his prosperity, that he should never be moved.
Yet afterwards he was so far tried as to be almost ready to conclude he was forsaken,
making use of this humble plaintive language,
"`Will the Lord cast off forever I will he be favourable no more?
Are his mercies clean gone forever?
Has God forgotten to be gracious?
Has he in anger shut up his tender mercies?`"
Thus, this righteous man,
having experienced preservation and deliverances in the heights and in the depths,
was instructed to serve the Lord with fear, and to rejoice with trembling.

When the Lord saw fit to hide his face from him, and to suffer fresh trials to attend,
we find him availing himself of the mercy by which he had been often delivered and restored;
and though he was at times much dejected, yet his faith was so remaining,
and strengthened in that power by which he had been raised from the sheep-cote,
to be the Lord`'s servant, that he could thus address himself: "`Why are you cast down,
O my soul?
Why are you disquieted within me?
Hope in God, for I shall yet praise him, who is the health of my countenance,
and my God.`"

Alas, why should that wholesome discipline,
which consummate wisdom and goodness has ever exercised upon those whom
he has made willing to bear the refining operation of his holy hand,
seem strange to any of us?
"`Gold is tried in the fire, and acceptable men in the furnace of affliction.`"
If it thus became him, for whom are all things, and by whom are all things,
in bringing many sons unto glory,
to make the captain of our salvation perfect through suffering;
if he was a man of sorrow, and acquainted with grief;
is it not enough for the disciple that he be as his Master, and the servant as his Lord.

As there are various causes of suffering, so there are various baptisms and trials.
Our different conditions require a different discipline, and the designs of God upon us,
make it necessary for us to be brought under a variety of operations.
All the faithful in former times were not brought under those particular,
and for the present, grievous exercises, which the prophets were,
in order to prepare them for the work whereunto they were called.
It is true the judgments of the Lord are unsearchable, and his ways past finding out:
"`Who,`" says the apostle, "`has known his mind, or been his counsellor?`"
Secret things belong to him, and things which are revealed, to us and to our children.

If all the holy patriarchs, prophets, apostles, martyrs, and confessors of Jesus,
have like their blessed Lord, been men of sorrows, and acquainted with grief,
and had to enter the kingdom through many tribulations, can we doubt,
whether these trials, which God, only wise, permitted, or appointed to them,
were mercies in disguise!
Is there not room to think they were made the means of preservation in his fear,
and of bringing them nearer to him; so as to rely more firmly upon him,
who is the only sure refuge in times of trouble,

Have not all the afflictions of the righteous been thus sanctified to them?
And will not the endless hallelujah which they shall have to sing,
be unto him who has redeemed their souls out of all adversity,
and made their garments white in the blood of the Lamb?
Our troubles of every kind are all known to God, who cares for us,
with the most fatherly affection.
Why then should Zion say, or why should the watchers on her walls say,
"`The Lord has forsaken me, and my God has forgotten me.`"

However unmindful he may seem to be of the distresses and dangers which threaten us,
when the tempest arises and the enemy breaks in as a flood;
yet in his own time he will arise, and rebuke the wind and the waves, for their sake;
and, by the effective word of his power, once more say: "`Peace, be still.`"
But if it should seem best to him, who is wonderful in council,
and does all things right,
to lead any of his people in the line of the glorious process of his dear Son;
should the final cup and baptism be the most trying and bitter;
should our dying words under these painful feelings be expressed
in that moving language of the Son of God,
"`Eloi, Eloi, lama sabacthani,`" I should have no doubt of the righteous souls,
thus tried, ascending from this cross, and apparent dereliction,
to an immortal crown of righteousness, and mansion of eternal glory;
no more doubt of the happiness of these,
than if I saw them ascending in the fiery chariot of sensible, soul-rejoicing,
celestial fervor!
I know not how sufficiently to inculcate this most certain truth,
That the children of God are never more under his notice, and tender regard,
than in seasons of their deepest humiliations; directing, blessing,
and sanctifying every dispensation to humbled souls.
Thus is he carrying on his work, though we see it not.

O, that you may not be discouraged, nor sink under the present exercise,
nor murmur as some of old murmured,
but endeavour to enter in perfect resignation to the will of God;
and then all things will work together for your good;
and for your additional preparation to glorify his holy name, in time and in eternity.
Amen.

From your real friend,

John Thorp.

LETTER XXXVI.

17th Seventh month 1777.

My Dear and Much Esteemed Friend,

You have been often brought to my remembrance, in much nearness;
and the sense and judgment with which my mind is impressed concerning you is,
that the dispensation you are now under is the effect of unsearchable love and wisdom;
and that the arms of mercy are underneath for your support.
My greatest concern and prayer is,
that the present painful baptism may be sanctified to your own advantage,
and the benefit and edification of the church:
for these excellent purposes what can be too much to do or to suffer,
according to the will of God?
It was for this that Jesus Christ our Lord vouchsafed
to descend from the heights of immortality,
and take upon him the form of a servant, to bear the contradiction of sinners,
the temptation of the enemy, and offer up himself upon the cross,
an everlasting sacrifice to God for the sins of the whole world.
It was for this that he, who alone was able, trod the wine-press alone,
stained all his garments, and drank the cup of trembling,
and was baptized with the baptism of suffering, even unto death.
Oh, that all of us, who are desirous of being found in him,
may be at least content to walk, as he walked,
in the depths of abasement and humiliation, wherein he may be pleased to lead us,
until he shall say, It is enough.

Strait and narrow the way to the kingdom has always been, attended with difficulties,
and entered into through many tribulations;
yet the commandments of the Lord are not grievous;
in keeping his law there is great delight; there is a recompense a thousand fold,
even in this life, for all our sufferings,
in the enjoyment of that peace which passes the human understanding;
as the earnest of that great and eternal weight of glory,
with which our sufferings in this world are not to be compared.

Without controversy great is the mystery of godliness,
far surpassing the comprehension of man;
and those parts of it in which we are deeply interested, we can only see into,
and understand as he who has the key of David, the lion of the tribe of Judah,
is pleased to unloose the seals, and open unto us.
How necessary is it then for us to take heed to the advice of the apostle,
not to judge before the time: he even says, "`I judge not myself.`"
Our duty, and interest, our advancement in the divine life,
consists not in our comprehending in theory, but following in obedience,
and in the simplicity of children.
Be not then, my friend, anxious about the cause, the duration,
or the effects of your present humiliation,
but endeavour to cast all your care upon him who cares for you; put your trust in God,
without whose permission not a hair of your head shall perish.
He sees every circumstance of your mournful condition;
when the enemy is permitted to buffet you, and you are tossed as with a tempest,
and not comforted, he knows these things, who is omnipotent,
who has set bars and doors to the sea,
and ascertained the point whereto its proud waves shall arise,
and they can go mo further.

These things, I am persuaded, you know, and are endeavouring to practise;
yet permit me to say something which may tend to strengthen and encourage your perseverance
in a total resignation of yourself to the disposal of Almighty power and goodness;
to God, your Saviour, who does not willingly afflict the children of men.

Though you may seem to yourself to lie as among the pots, and to be as a broken vessel,
yet it is my belief,
you will be brought forth as the dove whose wings are covered with silver,
and her feathers with yellow gold.
If it will avail anything to your comfort, I can assure you,
you are far from being alone in tribulation: I mean not as to outward troubles,
but those which result from the concern we have in the impending
judgments of the Lord on a backsliding generation.
And the general state of the church among ourselves,
wherein the prevalence of the nature and spirit of the world,
and the famine of that word whose entrance gives life,
furnish abundant cause to the living for mourning, yes for unspeakable distress.
We are however favoured at seasons in the vision of divine light,
with a prospect of better times,
wherein the Lord will in mercy turn again our captivity as the streams of the south.

My faith, as an individual,
is strengthened to believe that the time will come
when the gospel shall be preached in all nations,
and the Lord`'s name come to be great among the Gentiles; and that in every place,
from the rising of the sun unto the going down thereof,
incense shall be offered to his name, and a pure offering.
Upon the whole, I cannot forbear to add,
that I wish myself more worthy of the sufferings of the present day,
and that I was more worthy to express these things in this manner to you.

With much affection I subscribe myself, your brother in Christ Jesus,

John Thorp.

LETTER XXXVII.

23rd Eighth month 1778.

My Dear Friend,

I may tell you I feel much concern for you in your present suffering state,
yet I have to believe all will work together for your good,
and that in the Lord`'s time your soul shall be set
at liberty and filled forever with his praise.
The Lord`'s ways are not our ways; his thoughts are not our thoughts;
one day is with him as a thousand years, and a thousand years as one day.
The designs, the concealed mercy, in his varied dispensations,
are beyond our comprehension.
This we know, that with him there is no variableness, neither shadow of turning:
that having loved his own, he loves them to the end;
that through whatever tribulations or conflicts he may lead them,
it is his good pleasure to give them the kingdom.

Be not then discouraged when the enemy is permitted to buffet you;
endeavour to stand still in these times of trial,
and in the Lord`'s time you will have to experience his complete salvation.
The most dignified of the children of God have been led in paths of unutterable humiliation,
and abasement, in the course of their purification:
yet none that trusted in the Lora and abode in his fear, ever were confounded.
When have there been any whom he prepared for a habitation with him in glory,
that have not drunk of his cup, and been baptized with his baptism, in a certain degree?

The language in which all the redeemed of our God have been instructed,
in a lesser or greater degree, is, "`I am a worm, and no man;
I am like a broken vessel.`"
It was the question proposed by our blessed Lord to the two apostles,
who were emulous to sit at bis right and left hand in glory:
"`Are you able to drink of the cup that I drink of,
and to be baptized with the baptism wherewith I am baptized?`"
Now what was this cup, and what was this baptism,
which it was needful they should in degree partake oil It was a cup of agonizing distress,
a baptism into the deepest suffering, even unto death:
the depth of which is awfully set forth in that expostulation,
"`Why have you forsaken me?`"
This was the baptism, through which the Holy Jesus had to pass.
This was the cup which, though intolerable to human nature, he was desirous to drink of,
according to the will of God: in humble resignation thus expressing himself, "`Father,
if this cup may not pass from me, except I drink it, your will be done.`"

This is the acceptable state wherein no choice is found,
no desire arises but what is circumscribed by, and centers in, "`Not my will, but yours,
be done.`"
It is to reduce us to this state that all the varied turnings of the holy hand,
and dispensations of God`'s providences are directed; in this state,
whether we are called to unite in the hosanna to our adorable Redeemer,
or go with him over the brook Cedron, we are equally acceptable to him:
it is to this state all things are sanctified, whether it be to reign,
or suffer with Christ: whether the north, or the south wind blows upon it,
the spices equally flow out, and ascend as incense acceptable unto the God of heaven,
and of the whole earth.
Attend not therefore to the discouragements which the enemy may cast before you;
for I believe you were never more under the divine notice than in this season of trouble.
Though you feel not the uniform prevalence of that power,
unto which the devils are subject, yet in this rejoice,
said our holy Redeemer to his people, that your names are written in heaven.

Should your present state be a painful, dark, and imprisoned state, yet permit me to say,
Fear not: the Lord is on your side, and in his own time he will open the prison doors,
and say to the prisoner, Go forth; and to them that are in darkness,
show yourselves in the light.
How can you think at any time, that you are finally forsaken of God:
though he see fit to hide his face from you at seasons, does his compassions ever fail?
Are not his promises sure?
Has he not delivered you out of six troubles,
and is his arm shortened that it cannot still save?
Has he vouchsafed, in unspeakable love, to draw your soul after him, in infant years,
and to reveal himself to you, as the stay of your youth, and will he now forsake you?
No, it is not so;
he is the same as he was when your soul was first enamoured with his love.
His regard is as much towards you as ever; and as he has Seen your morning light,
and the stay of your youth, so he will be your evening song,
and the staff of your old age.
Let your hope and trust be in him,
and in his own time he will give you the desire of your heart;
and you shall have to praise him as on the banks of deliverance;
and tell of his wonders in the deep: who is a God infinite in power and wisdom,
whose mercy endures forever, and of whose lovingkindness there is no end.

I desire the increase and establishment of your health,
and in order to it wish you to take as much exercise
within and without doors as you are capable of,
without weariness.

I am, with love unfeigned, your friend,

John Thorp.
