== Letters 38 &#8212; 50

[.letter-heading]
Letter 38.

[.signed-section-context-open]
17th 6th month 1779.

[.salutation]
My Dear Friend,

I cannot with ease omit this opportunity of acknowledging the receipt of your letter:
be assured, no lack of friendship towards you, or of attention to the subject,
has been the cause that I have not answered it sooner;
but chiefly because I have had nothing to say, which has not, at least in substance,
been said before: my faith, and hope, and all my feelings concerning you,
when clothed with a right mind, being invariably the same.

I am abundantly persuaded,
that however in your own apprehension you may stand in need
of compassion and help from the least of your friends,
yet, I know, that he who made and supports all worlds,
with whom are all the treasures of wisdom and knowledge, who has all power in heaven,
and on earth, is your Saviour, your shield, and your exceeding great reward.

With regard to the distressing probations of your present state, I pray, in faith,
that you may be supported under and to the end of them all;
that the gracious design of the Almighty may he fully answered concerning you.
What I feel of trouble for you is, on account of your suffering,
for I have no fear or doubt respecting the issue of your present conflicts.
When I have read your letters,
those which have been most replete with lamentation and fear,
I have been so far from feeling any degree of discouragement on
your account that my faith has been raised to a degree of assurance,
that no one is in a safer state.
Is the cause of your grief a painful uncertainty,
whether your suffering originates in mind or body?
Whether on your account, as an evil doer,
or in a state of union with the holy suffering seed;
filling up what remains of the afflictions of Christ, for his body`'s sake,
which is the church;
whether purely a dispensation of the Almighty for your more perfect purification;
or whether arising only from the natural causes, in the constitution of the human frame?
Is the clear knowledge of these things veiled, or hid from yourself or others?
And why is it so?
Does not Infinite Wisdom deal with us in this manner,
because he knows it is best it should be concealed, just in the manner and degree it is?

Oh that you could but cast all your caring and anxious solicitude
about these things upon him who cares for you;
and think of nothing but how you might come to the most
perfect submission and resignation to the will of God.
I believe this is your desire and concern, therefore I have to believe,
that however your present trial may be permitted, to continue or increase;
though the furnace should be heated to a greater degree than it has been;
yet that you will be brought forth with so much the greater brightness and purity,
without so much as the smell of tire having passed on your garments.
Great is the safety of this resigned humble depending state; and truly,
the fitness and necessity of it are equal to its safety, for what are we,
and what have we to boast of but our abundant infirmities: beset as we are,
in this state of probation, from within and without,
what can the willings and runnings of the creature avail?
Or what have we to trust in or depend upon but God, who shows mercy,
and that mercy is Christ Jesus.

I commend you, then, dear friend, with myself, into the arms of this everlasting mercy,
for safety and preservation;
for he is that salvation which God has appointed for walls and bulwarks;
and the more you are reduced, as to a dependance on your own strength,
the more will his strength be manifested in your salvation:
the deeper you descend in suffering and humiliation,
the higher shall you rise in dominion with your suffering glorified Redeemer: for,
as said the apostle, "`If we be dead with Christ, we shall also live with him.`"
It is therefore in my heart to say, Be careful for nothing, but in everything,
by prayer and supplication, let your needs be made known unto God.
Cast all your care upon him, both with regard to body and soul,
and he will be everything to you which you stand in need of,
according to the riches of his mercy, in Christ Jesus.

A degree of sympathy with you has been raised in my heart,
that your present humiliation and comparative uselessness
in your own apprehension in respect to former service,
affects you with generous concern, on the church`'s account, wherein, indeed,
the labourers are but few.
But remember, my dear friend, that the work and the power too, are the Lord`'s,
that he can work by many, or by few, with, or without instruments;
to him then let us commit his own cause, desiring nothing for for ourselves,
but that his will may be done in us, and by us, as it is done in heaven.

I have only to add, that to do anything to injure our health,
or which may tend to shorten our days, is certainly wrong;
the blessing of natural life and health,
deserves our grateful acknowledgment and attention; and I consider it to be offensive,
either to hurt or destroy it, from a lack of due resignation.
In the fellowship of the gospel, I subscribe myself your affectionate friend,

[.signed-section-signature]
John Thorp.

[.letter-heading]
Letter 39.

[.signed-section-context-open]
Redruth, 29th Twelfth month 1792.

[.salutation]
Dear Friend,

Your affectionate remembrance of me is salutary:
and your remarks respecting our endeavours,
(though enfeebled by age and infirmity) to fill up our days
work so as to be favoured with peace in the close of it,
are weighty.
May the Almighty strengthen my weak mind to believe,
and assist me in the performance of his will, in the few remaining hours allotted me.

I am quite a cripple, but can still write,
though my friends admire I can do it so legibly.
I esteem it a great favour that I can bear to be carried to our meeting,
which is held just at our back door.
When yourself and wife were in our county it was far otherwise;
even to see my friends was then difficult.
I was for several years the Lord`'s prisoner;
I never arraigned his justice or wisdom in his dealing with me;
my reasoning faculties were not lost,
although the enemy was permitted to cause me to believe strange things;
so far as my deliverance is wrought, the Lord`'s hand has done it.
Man could do nothing,
though I doubt not but that the prayers of my friends were heard with acceptance.

I note what you say of your intended visit to Pyrmont;
if the concern is removed from you, I wish it may rest upon some other servant.
To visit the convinced, who inhabit dark countries, is a truly charitable labour.
Since my residence in this county I have for some books on religious subjects,
in the Danish, and High Dutch, into the hands of some who could read them.

Your account of the state of the society in your county is truly acceptable;
I hope I may say it is the same in this corner of the nation;
indeed it appears to be so in many parts of it;
so that although our numbers may be small, I hope we are yet as lights in the world,
and that the time will come,
when an increase of faithful testimony-bearers to the truth professed by us,
will be apparent.

I now conclude with the salutation of true love to yourself, and your valuable wife.
My dear love is also to S. B. and to other friends of my acquaintance,
to whom my spirit has been nearly united.
May the Lord have us all in his keeping to the end of time,
is the desire of your affectionate friend,

[.signed-section-signature]
Catherine Phillips.

[.letter-heading]
Letter 40. Extracts From An Epistle Of Stephen Crisp.

It lies upon me to warn you, my dear friends, to watch against the spirit of this world,
lest it drink up your spirits too much,
in an eager pursuit after the things of this world, which happens to several,
in various ways, to their great hurt, and damage; and the snare lies deep and hidden,
under a subtle covering.
For whereas it is the duty of every man to take care for his family,
and to be diligent in the calling God has placed him in,
and to improve such opportunities as are put into his hands;
yet here the enemy works to make the care immoderate; to turn the diligence to slavery,
and the improving opportunities to a searching out for them, sometimes by indirect means,
to the prejudice of their neighbour:
and all to satisfy a greedy desire after heaping up treasure in this world;
and through earnestness of the affection, that kindles more and more,
a man comes to have the increase,
or decrease of these things to be the objects of his joy or sorrow;
and then he is miserable, for joy or sorrow are the highest faculties of the mind,
and ought to be placed on the highest objects, and not upon transitory things.

But, alas! how many are cast down at losses, and lifted up at profits and gains?
Oh! my friends, take heed of this fickle and uncertain state;
for while some have set their minds upon the things of this world,
and placed their trust in uncertain riches, they have erred from the faith;
and if at any time they have taken their wings and fled away,
their hope has gone with them; therefore be cautious of having your spirits sharpened,
and set on edge about these outward things:
take heed not to enlarge your trades and business beyond your ability or capacity,
for both these evils have been the ruin of some;
as every one that has ability has not capacity, for great things,
and every one that has capacity, has not ability; and where either of these are lacking,
such ought to be content with low and mean things, such as they are capable to manage,
and able to reach; not to lean too much upon the one, and then seek, by indirect means,
to make the other answerable; for no man knows the issue beforehand,
and therefore ought to wait to know the guidance of the Lord,
and to be subject unto his will, though in the cross to their own.

As the apostle has noticed, concerning those who said, We will go to yonder city,
and will buy and sell, and get gain, which were lawful things in themselves,
yet for this they ought to have said, "`If the Lord will.`"
So he that intends to increase his trade, and enlarge his adventures,
so that his gains may be enlarged, even in this, he ought to say, "`If the Lord will.`"

O friends, wait to feel the governing hand of God in these things,
to direct and govern you in your affairs: that so he may be really acknowledged by you,
the Lord of the earth, as well as heaven; the ruler of your tradings and dealings,
as well as of your religion and profession.

[.signed-section-signature]
Stephen Crisp

[.letter-heading]
Letter 41.

[.signed-section-context-open]
Chard, 13th Tenth month 1718.

[.salutation]
Dearly Beloved Friend,

Yours of the 15th of ninth month is before me,
with which I was so affected in the feeling of that love from which it proceeded,
that I thought to return a speedy answer; but through frailty of memory,
and other infirmities, it has been deferred until now.
I observe you take notice of my making no reply to what you say
concerning the burial of our good friend William Penn;
I hope you will readily believe, it was not for lack of love; I can truly say,
that I never loved any man better on a religious or civil account.
Although we have had many other valuable friends, to me,
dear William Penn exceeded them all.
The reading his works has been more profitable to me than that of many others,
especially his book, entitled, No Cross, No Crown; In short, I can say,
with a sincere desire to the Lord, my soul be with his.

I hope, dear friend, you will accept of this scribble; I am become weak,
through the infirmities of age; and such deafness is attending,
that they are frequently obliged to write, to make me understand.
But I can look back with comfort, and remember the Lord`'s great love,
in calling me to work in his vineyard, in which he has also strengthened me,
and given me a plentiful reward, blessed be his name forever.

My honest wife, (as dear William Penn used to call her) is indifferent well,
considering her age, which I prize as a great mercy.
Mine, and her dear love is to you, and your wife, and to my loving friend Henry Gouldney,
with any other friends in your freedom. So remain your sincere, and for many kindnesses,
much obliged friend,

[.signed-section-signature]
Elias Osborne.

[.letter-heading]
Letter 42.

[.signed-section-context-open]
London Ninth Month 14th, 1706.

[.salutation]
My Dear Friend,

What I have heard from individuals was so great a surprise,
that my love questioned the integrity of those who related the sad story to me.
Has not your soul felt immortality brought to light among us, with all our weaknesses,
beyond what you ever felt among any other sort of people?
What strange eclipse is this?
It is like an apoplectic upon the mind.
Dear Thomas, look back, and look inward,
remember the days wherein we enjoyed sweet fellowship together in the heavenly power,
that has often filled the gospel temple, and been an agreeable odour among us.
I wish myself with you, if but for a short time,
and if you desire the company of any other friends to accompany me, I will let them know.

Our fear, our love, our grief, weigh us down on your account.
Dear Thomas, return by the door at which you went out; and be a fool, a little child,
delighting your soul in simplicity, meekness, and humility,
which the feeling of divine life brings into; wherein all doubts are resolved,
all fears are dispersed, and an entire sweetness, and content remains.
O what of this world is like unto this?
Our greatest joys take wings on a sudden,
and fly away, but the inward mental joys and comforts of the Holy Spirit,
they keep us company through this world to that which
is out of the reach of all earthly troubles,
and this is the reward of the righteous.

Be afraid of proceeding, and by this stumble you will at last get ground to help others;
yes, the godly sorrow that may follow this hour and power of darkness,
in which you are rather tried than overcome,
may produce a deeper sense and travail than ever; and restore, quicken,
and augment your gift and service.
May it be so, says my soul.
I write this in the innocency of my heart; make a right use of it,
and let me hear from you, directed to H. G. With true love to you, and your honest wife,
I rest your truly loving friend in the Lord,

[.signed-section-signature]
William Penn.

[.letter-heading]
From a letter of John Fothergill, to his Son, the late Dr. Fothergill, of London.

I am preserved in usual health,
and attended with peace and comfort in our heavenly Father`'s goodness:
though in the appearance of a severe threatening time of distress, in several respects,
to this nation: and if we be not excited hereby to diligence,
in seeking to lay hold of eternal treasure,
which is the love and favour of the fountain of all good,
we shall be more inexcusable than many others of mankind, who know not so well,
and clearly, where to seek for happiness, and a refuge indeed.

After this hint of what is much in mind,
I shall take notice of your remarks on your late journey into Holland and Germany;
and first say, your account of several people in those countries,
exactly agrees with my idea of them; for I believe they have had, in some measure,
their eyes opened, but they set man to work to form and imitate religion,
building without being enough concerned to find the rock.
Many, from their pious intentions, make a show for a time, and some good may come of it:
but it is a matter to be lamented, that there should be, as it were,
a general propensity among the Germans to run away with speculation,
and thereby so many valuable springings, and glimpses of the heavenly day,
should have yet produced no more durable fruits,
as to the experiencing salvation in reality.
But it ever will be true,
that there is no following Christ acceptably without submitting to the cross.
Here seems to be the place at which the people of that country in particular,
as almost all nations in general, have suffered loss.
May the plough of God take more effectual hold among them, is my heart`'s desire;
and may this consideration strengthen you in fearing to live and delight therein,
or be at ease in barren speculation, even of the best things or principles;
but be more and more animated to seek for daily bread
from the everlasting Father`'s hand,
who will hear and answer in due time, the patient, though hidden enquirers for it;
and thereby such will grow in the living root, and bear fruit to the Father`'s praise.

[.letter-heading]
Letter 43.

[.signed-section-context-open]
29th of Twelfth month 1783.

[.salutation]
To +++_________+++,

Yesterday I received yours,
and found immediately so much sympathy with the state you have described,
and so much liberty to write you, that I readily now undertake it,
though as I have already told you, I have no correspondence of this kind;
but when permitted by the common Father of us all, we may then, if ever,
converse in this manner.

The state of poverty you have complained of has, alas, been my own many a long winter,
and that too attended with the most severe conflicts which
a stubborn nature and implacable enemy have made very bitter,
and even dangerous; but in times of the greatest peril, when on the brink of a precipice,
Infinite Mercy has condescended to interpose, and snatch the brand as out of the burning.

Thus much being premised may convince you that your case is by no means singular,
it being, I apprehend, the common lot of all those who undertake the spiritual travel,
to pass through deserts and suffer hunger and thirst,
till brought through into a land of plenty.
Your state is now probably emerging from that of childhood,
in which the great and good Shepherd, who carries his lambs in his arms,
feeds them with divine spiritual food, even the milk of the word,
strengthening them to bear the cross he requires them to take up; but,
however pleasing this happy state may be, there must be a going forward,
even into the state of young men; witnessing some degree of strength,
and putting on armour, to resist the enemy of all good; and here it is,
when found faithful to the measure received,
we are favoured with some degree of stability,
so as to pass through the exercises allotted us with safety and comfort,
and to press still forward.

I need not now describe the dangers, the conflicts, and the assaults of the enemy,
who makes our own passions his tools to work with: sufficient it is to say,
that help is never lacking to those who depend on the source of all good,
in every trying season.

And now, my dear friend,
let me just point out the advantages of the state which seems hovering over you.
In the first place it gives us to see clearly from where come the several comforts,
deliverances, and mercies, which have attended us in our travel from the land of bondage,
in the wilderness state, and through the river Jordan (the river of judgment),
into the promised land,
where we have just begun perhaps to fight the inhabitants of the land (our own passions);
and having brought with us our memorials in our hands,
have been able to worship as at Bethel, the house of God.
Secondly,
it from hence teaches us where to apply for continual
help as we are in continual need of it,
some of the inhabitants having chariots of iron.
Thirdly, it teaches us that we have no strength of our own.
Fourthly,
it is a most evident means of humbling us under the
consideration that we have nothing that is good.
Fifthly,
we are hence led to value the more every instance of the Lord`'s goodness towards us,
thereby increasing our love and obedience,
and implicitly trusting to him by an increase of faith and
confidence that he will never leave nor forsake us.
Sixthly, this state may be compared to that of a tree, which in winter,
though it bear no fruit, gathers strength in taking deeper root;
so that in time of fruit, it may bear greater plenty,
and more pleasing to the good husbandman, as well as the beholders.
Lastly, the blessing is pronounced on those who hunger and thirst after righteousness,
that they shall be filled: but whether this filling may be in time,
or when divested of the cumber of mortality, is known only to Him,
whose promises are Yes and Amen.
I am apt to think both here as well as hereafter to some --for, alas,
the lot of some is cast in a very barren land,
so that when one sees others favoured with the heavenly dew, one is ready to cry out,
that "`the gleaning of the grapes of Ephraim is better than the vintage of Abiezer.`"
And yet one of the poor Abiezerites was made by the
Lord`'s power a notable deliverer of his people.
Thus, in every station, Omnipotence can raise up instruments to effect his purpose,
which is ever the good of his people, both generally as well as individually.
I might have added above, to the advantages of poverty,
that it greatly tends to bring down pride and self-conceit,
which must be laid in the dust.
There is also another advantage I have found in a very eminent degree,
and that is when plunged into the deepest poverty,
"`when the earth and its bars were about me,
so that not a glimpse of divine comfort was obtained for a long season,`" (I
hope this will not be your case) the divine light so shone on all occasions,
that I never lacked directions for my conduct, even in ordinary affairs;
and so great was its lustre, that though I seemed confined to a very narrow path,
it was impossible to mistake without disobedience; which, alas,
was but too often the case, either through weakness, inattention, or sudden attacks;
and though sometimes I could not but fear, I was really dead: yet I concluded,
that dead men do not know it, consequently that was not my case; but poor,
very poor indeed, insomuch that I question if there ever was one more so.
Again, I was also convinced there was life,
because being favoured with light it evidently proved that the light came from the life,
for death always is attended with darkness.
And now, dear +++_________+++, do not be discouraged; be sure hold fast that you have,
never doubting that help is always near,
and that the Giver of every good and perfect gift,
knows and administers what is best for us; dwell, therefore, in the patience,
and let it have its perfect work.
If you can conveniently keep your hour of retirement, it will be best,
and perhaps as near the same time of the day, for then the mind will look for it;
but if business of the family prevent, take it when you can.

I have written in haste, and in much love, in which I conclude

[.signed-section-closing]
Your very affectionate friend,

[.signed-section-signature]
W+++.+++ P.

[.letter-heading]
Letter 44.

[.signed-section-context-open]
22nd of Third month 1788.

Being, contrary to my expectation and endeavours,
prevented from attending the ensuing monthly meeting at +++_________+++,
of which I was the more desirous,
for the same reason that I hoped and still hope you will be there; I find freedom,
and that I trust after having maturely considered it with a desire to do right,
to communicate to you what passed in my mind long
before I knew or expected that would have happened,
which prevents me.

It has not been usual with me to think beforehand
of the affairs likely to come before such a meeting,
but the mention made by the friends of +++_________+++,
of the application of a certain person to be admitted a member of our Society,
occurred again and again to my mind,
and connected with it the parable of the leaven which
a woman hid in three measures of meal,
till the whole was leavened.
It was '` hidden,`' but its operation, though secret, was gradual and progressive,
till there was a total assimilation;
'`till the whole was leavened,`' the process was from within to without;
the exterior part was the last affected, the last whose appearance was altered;
but though the last, it was as completely changed as the rest, the '`whole`' was leavened.

This seemed to convey instruction to my own mind,
as setting forth the prior necessity of an inward change,
for the proper regulation of the outward deportment: I thought too,
it might be applied not improperly to the case, nor, perhaps,
unprofitably to the consideration of the party alluded to.
I do not doubt his having been sensible of the secret
influence of the divine principle in his own conscience,
or that his judgment has been measurably convinced
by the testimonies he has heard borne to the truth,
as professed by us as a people.
I as Utile doubt the sincerity of his desire to be
considered as one believing in the same principle,
and desirous to walk by the same rule.
But whether there is yet that thorough conviction,
that perfect harmony of faith and practice,
as would justify a conclusion that '`the whole`' is leavened,
I hope he will not be offended if I recommend to his serious consideration,
rather than he should desire a premature admission;
for as he that believes will not make haste, so a waiting for the right time,
when perfect unity will be experienced, will not retard his growth in the truth;
nor lessen the tender regard of his friends toward him, or the peace of his own mind.

I desire to be as brief as possible.
I have nothing but good-will in my heart towards him;
and if under the influence of that wisdom which alone, in such cases,
is profitable to direct, friends shall admit him a member of the society,
I shall freely give him the right hand of fellowship,
and desire to be his companion in the regeneration and in newness of life.

[.signed-section-signature]
John Thorp.

[.letter-heading]
Letter 45.

[.signed-section-context-open]
8th of Seventh month 1787.

I think I do as seldom as any man who wishes well to the cause of religion and virtue,
endeavour to recommend it by books,
though I do believe if people would read such as deserve reading, as you say,
with a desire to profit, they would always reap some benefit by it.
My reading now, not only from necessity but judgment,
is pretty much confined with respect to all the forbidden
productions of the tree of knowledge.
I have seen a beauty and safety in that state of mind expressed by the Psalmist,
and earnestly have I desired to dwell in it:
"`Lord I do not exercise myself in things that are too high for me;
my soul is even as a weaned child.`"
The Scriptures without, and the law written in the heart,
are the most profitable of all books,
and in meditating on the divine precepts written there, with a desire to obey,
the most blessed knowledge is obtained.

[.signed-section-signature]
John Thorp.

[.letter-heading]
Letter 46.

[.signed-section-context-open]
15th of Eighth month 1787.

Do not think, dear friend, I am recommending books too highly;
everything is good in its place; but I wish for you as for myself,
and I believe it is so, that we may have in our possession the truth itself,
and that we may wait (that best of exercises) to feel,
(when it shall please him to replenish our hearts
with that light and virtue which comes from him),
the mysteries of his kingdom opened in ourselves.
The Lord Almighty is in great mercy, by various means, endeavouring to prepare us for,
and engage us to seek after these divine communications from the fountain itself,
wherein are hid all the treasures of wisdom and knowledge.
Thus we should experience another sort of teaching and another kind of knowledge,
than that which books and outward instruction can furnish us with.
I long my dear friend,
that we may grow and increase in the knowledge and experience of that divine communication,
from the fountain of divine intelligence, and with one another in him,
which stands in no need of the medium of words or writing.

[.signed-section-signature]
John Thorp.

[.letter-heading]
Letter 47.

[.signed-section-context-open]
22nd of Eleventh month 1787.

Honest Thomas a Kempis pleases me much.
I have always been pleased with it in any dress,
but I think this of Payne the most complete.
I know not that I have anything to add,
perhaps it may convince you you are not the poorest man,
but of poverty I am not accustomed to complain.
I believe all the dispensations of Providence are right,
and so that we are but honest and faithful stewards of what we have received,
we shall not fail to be accepted; and this too, is the way to witness an increase:
let us then, dear friend, aspire after this, and rest satisfied with our own lot,
and with every allotment of Providence, doing every day whatever our hands find to do,
according to the present ability, with which let us ever be content.
Let us seek nothing for ourselves,
but that our blessed Master may be glorified in our obedience,
though it may be oftentimes through our own humiliation.

[.signed-section-signature]
John Thorp.

[.letter-heading]
Letter 48.

[.signed-section-context-open]
15th of Eleventh month 1794.

Having the opportunity of conveying a few lines to you, I was unwilling to let it slip,
and though I should have nothing to write worthy of much regard,
yet you will at least be convinced of my good will,
and that if I had anything better I should as freely have offered it.
I am not much in the practice of boasting of my infirmities,
and truly I have nothing else to boast of,
(I often think there is too much of this among us) and
yet lest you should think of me above what I am,
I am free to tell you that weakness and poverty are often my companions,
that jealousy and fear both night and day, do frequently attend me,
lest I should not be so improving my time and the talents committed to me,
as I ought to do;
lest I should not be so steadily preferring the things which are most excellent,
not enough setting my affections on things which are above,
and looking towards the mark for the prize of the high calling of God in Christ Jesus;
lest obedience should not keep pace with knowledge, and the day`'s work with the day;
because I do see so clearly that the end of all things is at hand,
that the summer will soon be over, and the harvest ended.
Now if anything like this should be also your experience, I am not sorry for it;
but I do pray that this poverty, this weakness, this jealousy and fear may,
to both of us, be sanctified to our complete redemption.
Oh this great work,
redemption! if this be but happily accomplished in our experience
it matters very little what else is gained or lost.
I thought so through adorable mercy in my early youth,
when through the visitation of the day-spring from on high
a prospect was opened into things which are invisible,
the transcendent beauty of holiness was disclosed, and the glory of this world,
was stained in my view.
With what zeal and fervency was I then engaged to labour to obtain
an inheritance eternal in the heavens that fades not away;
and oh, the solicitude that I have and do now feel since I am advanced more in years,
that I might not survive the greenness of my youth, that I might not become more relaxed,
lukewarm, and indifferent, than I was in the day of my espousals;
and indeed I can say to the glory of his name who lives forever,
that my love to God and to my brethren has not been on the decrease;
my soul was never more ravished with one of his looks,
with one chain of his neck whom my soul increasingly esteems the chiefest of ten thousand,
and altogether lovely; never, never had religion so many charms;
that I do many a time think when the vision of light is a little opened in my view,
that if never had before, I should not then, hesitate a moment,
but endeavour to give up all for eternal life.

Now, my dear friend,
that what I have wrote here is likewise descriptive of your
religious situation I feel strongly disposed to believe,
and therefore it is in my heart to say, let us thank God and take courage;
let us lift up our heads in hope,
that he who has been our morning light will be our evening song:
and though in our progress through this wilderness we should meet with tribulation,
(for I have been instructed to believe) there is no outward situation exempt from trials;
but it is the privilege of the dependant children of our
heavenly Father that they know him to be their sanctuary.
This state of things is a compound of good and evil;
gall and worm-wood are deeply mingled in the cup we all have to drink,
though not perhaps in like proportion; but let us receive our respective portions,
as coming from his hand, who will make it a cup of blessing to his children.
We have the authority of holy writ to say, in all their afflictions he is afflicted,
and the angel of his presence is with them.
O what condescending language is this:
"`When you pass through the waters I will be with you,
and through the rivers they shall not overflow you;
when you walk through the fire you shall not be burned,
neither shall the flame kindle upon you.`"

Thus, whatever be the permitted dispensation of suffering
of any who love the Lord Jesus in sincerity,
however such may at seasons be divested of strength and clothed with sackcloth,
though such should have to pass through deep and fiery trials,
yet shall they be preserved; the Lord in whom they trust will be with all these,
will sanctify the dispensations, and in his own time bring deliverance;
will clothe with the strength of salvation,
will take off the sackcloth and clothe these with gladness,
so that for the encouragement of the upright and sincere,
whose hands I know are many times ready to hang down, yes to the whole Israel of God,
it may be said as formerly, "`There is none like unto the God of Jeshurun,
who rides upon the heavens in your help, and in his excellency on the sky;
the eternal God is your refuge, and underneath are the everlasting arms.`"
I have written a longer letter than I expected,
in much freedom and more about myself than I ever did before that I remember,
but I will not pretend to make any apology for it,
some little instruction may at some time be derived from it.

[.signed-section-signature]
John Thorp.

[.letter-heading]
Letter 49.

[.signed-section-context-open]
15th of First month 1791.

There is, I believe, an obligation to duty above the fear of punishment,
or expectation of reward; and because I wish you the most perfect state,
I wish you this experience;
a state wherein all selfishness both in spiritual and temporal things is lost,
or swallowed up of divine universal disinterested love, as a drop of water in the ocean:
and though I do most assuredly believe that virtue is its own reward,
that a cup of cold water given to a disciple, in the name of a disciple,
shall not go without a reward;
yet I have often thought it a subject worth the consideration
of those who are stewards and desire to be faithful,
that this is neither the time nor place of rewards or punishments,
although the earnest of both are frequently felt.
I apprehend that many, even of the wise in heart, have been ready to stumble here,
thinking that their faithfulness and piety should have engaged the divine
interposition to exempt them from the sufferings of this present life;
so thought it is likely, the Roman Brutus, when,
overcome by Anthony in a cause wherein he thought virtue had engaged him,
with his latest breath he is said to have uttered this desponding exclamation,
"`Oh virtue, I have followed or worshipped you as a substantial good,
but I find you only an empty name.`"
How much of this sort appears in the book of Job,
whose trials were as singular and great as his conduct had been upright and approved!
And David tells us that his foot had well nigh slipped,
because he envied the prosperity of the wicked;
when he saw how they flourished as the green bay tree,
he was tempted to conclude that he had cleansed his
hands and washed himself in innocency in vain.

Time would fail to recount the sufferings, the trials,
and probations that have attended the peculiar heritage of God in all generations;
that their great privilege, it is plain,
has ever been divine support and preservation under trials,
and not an exemption from them:
how great and various were the trials that attended the good old patriarchs,
and how singular and proving those that were experienced
by the man after God`'s own heart,
whose son even conspired to take away his life;
but he who is a God keeping covenant and mercy,
vouchsafed his protection and sure support, and was to him in all his troubles a rock,
a refuge, and a sure hiding place.
I feel beyond all that can be expressed in words for you while I am writing,
that this may be your happy experience, if trials of any sort be permitted to attend you;
for though I know not how applicable or otherwise
anything of this kind may be to your present state,
yet this I know,
that there is no combination of outward circumstances can exempt us from trouble;
though we tread upon the high places of the earth, and dip our feet in oil:
but in the most proving situations, though some encouragement,
instruction and consolation may be derived from considering what has been the lot,
and what the support of many elder brethren in the family,
who through many tribulations have entered the kingdom,
yet the most sovereign help and comfort is obtained by looking unto Jesus,
who was a man of sorrows and acquainted with grief;
whose visage was more marred than any man, and his form more than the sons of men;
who being touched with a feeling of our infirmities, and having been tempted,
knows how to succour them who are tempted.
Let us then, my dear friend, in our varied allotments, lay aside every weight and burden,
and run with patience the race that is set before us,
looking unto Jesus the author and finisher of our faith,
who for the joy that was set before him endured the cross, and despised the shame,
and is set down at the right hand of the throne of God.
I would not make any unnecessary addition,
but I am so fully satisfied that it is not the will of our Father who is in heaven,
that any of his children should be discouraged under whatever
disadvantage in their own apprehension they may be placed,
or whatever cup they may have to drink, or baptism they may have to pass through;
but that they should be encouraged to put their trust in him,
to cast their care upon him; none who ever did so, ever were, or ever will be confounded.
Let nothing move us from this foundation, and we shall be safe.
Oh, how memorable is that saying of David, "`The Lord is my shepherd,
therefore I shall not lack;`" and again, "`Your rod and your staff, they comfort me,
and you are with me.`"
Thus in heights and depths, in seasons of trial and of rejoicing,
let our whole dependance,
our humble trust and confidence be in and upon the sure mercy of God in Christ Jesus,
and then I am sure that he will sanctify to you all his dispensations;
that he will bless you indeed,
and that as it has pleased him to appoint your lot as in a south land,
so he will continue as he has in mercy hitherto at seasons done,
also to give you springs of water, yes,
the sure inexhaustible springs of consolation that flow from his presence;
and this I wish for you with as much sincerity, as for your affectionate and true friend,

[.signed-section-signature]
John Thorp.

[.letter-heading]
Letter 50.

[.signed-section-context-open]
22nd of First month 1793.

I have often of late felt something like the salutation
of love moving in my mind towards you,
in which I wish you both natural and spiritual health,
and as there is no medicine that can be prescribed or taken equal
to wholesome food and exercise for the preservation of bodily health,
so I believe that by this means our spiritual health also, is best preserved;
but we may observe some people as to the outward, whose constitution is not bad,
yet feeling some slight indisposition would rather have recourse to medicine,
or give themselves up to the feelings of their infirmities,
than employ the strength they have in necessary exercise,
and content themselves with such food as would be most profitable for them.
Something like this I apprehend to be the case with some religious persons,
who attending too much to every little feeling of weakness,
and comparing themselves with others,
whose gifts and callings may be very different from
theirs (though not at all more acceptable to God,
or according to his will) are ready to be discouraged,
and count themselves fit for nothing,
whereas the Lord is only glorified by our obedience
in that station in which he has placed us,
so that let the sphere of our activity be what it may,
let the orbs in which we are placed be high or low, in human estimation,
let our gifts and callings be more or less conspicuous and admired by our fellow pilgrims,
those who are faithful and honest in their varied allotments,
seeking nothing for themselves,
but to bring glory unto God by a life of humble dedication to him; these,
however they may have been regarded among men,
or however at times they may be ready to judge of themselves,
will finally meet with an equal welcome from the blessed Master,
as approved good and faithful servants.
Oh, how wisely then do they act, who taking no anxious thought for tomorrow,
are attentive according to present ability, to the duties of the present day;
who satisfied with their own allotment of suffering, of exercise, of consolation,
and labour, cheerfully comply with the divine appointment;
these neither desire more or fewer talents than what they have received,
but wisely occupying with these, experience an improvement.

I hardly know how to put into words what I have in view to recommend,
and what I am favoured at seasons to see is the most excellent way, though possibly,
my dear friend, you are much more advanced in this way than I am.
It is to be careful for nothing,
but in everything by prayer and supplication let our needs be made known unto God,
casting all our care upon him who cares for us, to cast off every weight and burden,
and run with patience the race that is set before us,
doing with our might whatever our hands find to do;
but what means this language we so often hear, and so often feel?
I can do nothing,--I have no ability,--I have neither strength nor understanding;
and in whose heart has this language been raised more feelingly than in my own,
for who is so deaf,
or so blind as the servants or messengers of the
Most High when his light is not with them?
But when he who increases strength to them who have no might of their own,
who speaks to things that are not, as though they were, and they obey him;
when in gracious condescension he is pleased to call,
to move to any little service among our brethren,
let us not then complain of lack of ability, nor reason upon our unfitness:
remember it was through faith the walls of Jericho fell down,
but the ram`'s-horns were employed as instruments.
Oh this faith to which all things are possible, which removes mountains,
and in which we should walk; without which it is impossible to please God;
let us contend for it, let us watch unto prayer that it may be increased,
for by this shall all the fiery darts of the enemy be quenched.
I know that Jesus is the author of this faith;
I know it is the faith of the operation of God;
but yet I am verily persuaded that by standing open,
and willingly yielding to this operation,
or turning away and shutting our minds against it,
we shall experience an increase or diminution of it.
Abraham believed God (against all human probability) and it was counted to him,
said the apostle, for righteousness.
Lord, be it unto me, according to your word, said the holy virgin Mary:
thus prepared she conceived the Redeemer of mankind.
Have faith in God, said the ever blessed Jesus to his disciples; and to Thomas,
be not faithless, but believing:--said I not unto you,
was the answer of our blessed Lord unto Martha,
that if you would believe you should see the glory of God?

It is not in my heart, very far from it,
to put any upon moving in the Lord`'s service in their own will, or their own time,
but I want to recommend to you, my dear friend, what I feel to be necessary for myself,
an unreserved dedication of heart to God,
a careful abiding with and attention to the blessed Master;
it is in my heart to say to you, whatsoever he says unto you do it;
no man by taking thought can add one cubit unto his stature.
I would have you, said the apostle, to be without carefulness;
let us leave everything to him who has all power; let us commit ourselves and our all,
our children, who are dear to us as our own lives, unto the Bishop of Souls,
who loves and cares for them more than we do; who, blessed be his holy name,
says all that is within me, has not only died for us, but for our children.
Oh, that they also may be made willing to die to themselves, that they might live to him!

In the fresh feeling of the heavenly Father`'s love, of which I am no ways worthy,
I salute you as a brother in Christ, and commend us both unto his holy keeping.

Remember me affectionately to your wife, whose dwelling is, I trust,
secure in the valley of humility.

[.signed-section-signature]
John Thorp.
