== Extracts from Letters of Richard Shackleton.

[.signed-section-context-open]
11th month 1755.

It looks as if we must labour hard for our bread through the course of the meetings.
Perhaps it may be best so, for what is hardly gotten is oftentimes carefully kept.
And indeed,
I think I have seen great loss accrue to some of honourable rank in this respect,
that when good Providence, in unmerited condescension,
has favoured them with the bedewings of his goodness,
in order for leavening and seasoning their spirits
for his service which is so much lacking,
they have, for lack of knowing a settlement and abiding in the life,
let these favours pass transiently over,
and not be productive of the fruits intended by them.
And with sorrow it may be too often said of them, "`Their goodness is as a morning cloud,
and as the early dew it goes away.`"

[.signed-section-context-open]
5th month 1769.

It is true my present situation is among the pots: yet I am a prisoner of hope.
I am indeed a powerless man; nor is there in me, nor in the powers of my nature,
any capacity to crawl near the salutary waters; much less to impart of them to others.
I can say of a truth, I am glad to see my equals, my familiar friends and acquaintance,
become my guides,
take the lead and grow from strength to strength in the great Master`'s cause.
It is my earnest desire that I may never injure it;
but having waded here through many deeps (unknown to mortals,)
I may be so preserved in my sorrowful pilgrimage,
as that I may at last lay down my weary head in peace,
and be admitted anywhere within the door of perpetual rest.

[.signed-section-context-open]
5th month 1770.

The several dispensations which we are under in our religious pilgrimage,
may be compared, I think, to the various turns, roads, and lanes in a journey.
I am at present, and have been for many years in one long lane;
when I shall get out of it, I know not.
The believer is not to make haste.
The great point is, to make strait steps, and keep steadily,
right on our way in the right road, without loitering, looking unnecessarily behind,
or in the impatience of our own spirits pressing too hastily forward.--Indeed,
I find the road of this life so bestrewed with difficulties and dangers,
and myself so exceedingly weak,
and unable by my own powers to preserve alive my own soul,
or even to succeed in my temporal transactions, by reason of my peculiar incapacity,
that under this sense I cannot but commit me and mine with great
earnestness to the protection and help of Divine Providence.

[.signed-section-context-open]
11th month 1770.

The warfare between the spirit which is not of the world, and the spirit which is of it,
is great and difficult: the situation of some makes it more so to them.
And the Being who is the source of all our happiness in time and eternity,
is a jealous Creator, demanding (as is his just right) the whole heart,
and will not accept of a partial sacrifice: he requires the prime, the best,
a whole burnt-offering.
May you, my dear child,
steadily resign yourself in all humility to be guided in his wisdom,
so will you be preserved an exceeding great comfort
to me your poor inwardly-distressed father,
a blessing to the family, a way-mark, a good example,
and an ordinance of help to your near and dear friends, whom you love,
and by whom you are beloved.
Thus, my beloved child, you will be preserved out of the evils, which are in the world,
and the perplexities, perturbations and troubles consequent to them:
you will grow from stature to stature in the experience of good;
and though in taking this cup of life, which is a cup of mixture,
you may expect to meet with trouble,
yet you will still find and feel the reward of your diligence,
faithfulness and obedience, to be peace.

[.signed-section-context-open]
1st month 1773.

I have often compared myself to a reed shaken by the wind.
May you dear child, be preserved in simplicity and nothingness of self, in humility,
and lowliness of mind.
Seeking diligently after and waiting steadily for the inward
experience of that which is unmixedly good.
This is the way to be helped along from day to day,
through one difficulty and proving after another, to the end of our wearisome pilgrimage,
having recourse, like the hunted hart, to the brook by the way,
when pressed by our spiritual enemies.
By this, my dear child, your predecessors in our family, who lived in the truth,
were enabled to wade through their afflictions,
and know that overcoming which entitles to the glorious, eternal rewards.
Many are the favours which you, my dear daughter,
have received at the hand of the Great Giver.
What need I enumerate any of them?
Your grateful heart is sensible of them.
May your branches, weighed down with humility, gratitude,
and all fruits of the spirit bend towards the root which sustains every tree of righteousness,
and from which its sap and life is supplied, and derived.
By humility and lowliness of mind, many temptations are avoided, and encumbrances escaped.
It is a safe and quiet habitation, into which the devil cannot enter,
and his emissaries view the dwelling with derision, and turn from it in contempt.
So the heavenly guest has more free admittance, and uninterrupted abode;
and the bread eaten in secret administers invisible, but effectual, support.

[.signed-section-context-open]
8th month 1773.

The meetings are large, and instrumental help afforded in them: but what shall I say?
--a people professing the inward spiritual life and spiritual worship,
and holding the same forth to the world must be spiritually minded,
and dig deep down to the nether spring, the source,
the fresh supply of all right religious ability:
otherwise there will be a withering at the root, and decay at the heart;
although from the temporary showers which may fall from the clouds,
and the favourable aspect in which they are planted, there may be a fair semblance,
and enduring for a while.
My dear child, my spirit has often near unity with you,
and I often and fervently desire your stability in righteousness,
that you may not cut and carve, and seek anything for yourself, nor seek to be anything;
but when that which quickens and animates and refreshes a little is withdrawn,
then be like ashes, reduced to nothing, cold, inanimate as to religion.
So, patiently abiding in this low state,
the Lord will give beauty for (or instead of those) ashes, the oil of joy for mourning,
and the garment of praise for the spirit of heaviness.
My children are indeed near my heart;
and their steady wise walking in all humility along the perilous path of life,
as it will be their own great interest, so it would be my exceeding comfort;
for in this world they as well as I must meet with trouble.
This is not the place of rest and respite and safety, but the field of battle;
in which if we be foiled, there is no second place of combat;
we are ruined irretrievably.
But if by keeping close to the captain of our salvation,
and obeying his orders and directions, we happily obtain the victory,
the conquest is unspeakably glorious.

[.signed-section-context-open]
11th month 1773.

The business of the meeting is now over: the concluding meeting to be tomorrow.
This has been to me a particular day of dryness and insensibility.
I almost wonder at myself, how it is with me.
But we cannot always sacrifice.
We must learn to bear nakedness and famine, to be in prison and in deaths often.
Such is the state of us poor creatures while probationers here.
My dear children are often the subject of my prostrate petition,
that they may be preserved, by such means as Almighty Wisdom may appoint,
from the delusions of an insidious busy adversary,
that they may be entirely dedicated in body, soul and spirit to their great Creator,
and that he may graciously accept of them to be his
true and faithful servants in their generations.
This is what I wish and desire for my children:
not that they may be sons and daughters of the earth,
and have a name and fame among unregenerate men, receiving their consolations while here,
and alienated and separated hereafter from blessed and refined spirits forever.

[.signed-section-context-open]
6th month 1777.

I am in sentiment with you that this trial may have been permitted for good purposes:
we may see thereby, and by numberless instances,
how uncertain is the state of human prosperity;
and how soon the fairest buildings of our imagination, our schemes and our hopes,
may be dashed to pieces.
We live in a world where, from a multitude of various causes,
we may be made most wretched and miserable, and miss of a place of rest hereafter.
What need have we then of walking awfully in humble thankfulness
when we enjoy all the necessaries and conveniences of life;
and when this life is rendered by our Almighty Benefactor not only tolerable but comfortable:
yes, when, in the infinity of his condescending goodness,
he is graciously pleased to superadd to his temporal
favours the visitations of his holy spirit,
to prepare us for, and afford us an earnest of eternal salvation.
May you, my dear children, keep your vessels (your hearts) clean, and empty,
waiting in abstractedness of thought and nothingness of self,
that those vessels may receive some of the blessed infusion,
which will preserve you sweet and savoury,
will strengthen you to go through the duties of this life with alacrity,
and qualify you to be of some service in the church in your day.
I have unity with you both in your baptisms, in your dedications,
and in your quickened resolutions, that you will choose the Lord and his service,
and not the world and its spirit, for the lot of your inheritance:
and the petition of my heart is for your growth and
establishment in the most precious truth.
Amen.

[.signed-section-context-open]
3rd month 1778.

We are short sighted, and of ourselves know not what is best for us,
or will in the end turn out most satisfactory to us, as to such matters.
One thing we may be assured of, that purity of heart,
and the cultivation of a fellowship between our spirits and the author of all our blessings,
is our real, true, substantial, and permanent interest.
Uncertainty and disappointment are the natural growth of this country,
but unmixed enduring happiness is a plant of heaven: of the fruit of which tree,
my dear child, the saints on earth are at times permitted to feed;
and by this earnest are enabled to press through the difficulties of this life,
aspiring after the full fruition thereof in the life which is to come.

[.signed-section-context-open]
8th month 1778.

But we are grown such an outward instead of an inward people,
so carnal instead of spiritual, we lust so for words,
and for Moses (the servants) to speak, that some great revolution, some general calamity,
or at least some dreadful apprehension from the view of an uplifted rod,
seems not unlikely to be employed for our rousing and reformation.
My mind is at times much plunged in deep baptism under a sense of our degenerate state,
earnestly desirous that this most precious,
excellent and holy thing which was sent among mankind may prevail and spread,
and rule and reign, whose undoubted right it is.

[.signed-section-context-open]
9th month 1780.

I may therefore mention that our province meeting seemed to partake somewhat
of the poverty of the place and people where and among whom it was held.
Nevertheless, a degree of life attended,
and your poor father was favoured with capacity to
have access to the place where prayer can be made,
and there to offer his humble, earnest, tender petition for himself and others;
but almost a total imbecility for any active service in discipline attended me;
and I thought a reproof for my folly rather than any encouragement succeeded
a few words thrown out in the course of transacting some affairs of discipline,
which I hope to heap up to myself,
and hide in my heart for my better government another time: live and learn.
Thus is verified the proverb, The rod and reproof give wisdom,
but a child left to himself, brings his mother to shame.
The rebukes of the Divine Spirit correct and amend our spiritual defects,
and cultivate our spiritual understanding in enlargement of service;
but he that is left and deserted of that guide, and waits not for its direction,
but leans to his own understanding, is in danger of disgracing the cause,
which his ignorant zeal wants to promote,
and of bringing his mother (the church) to shame.

[.signed-section-context-open]
6th month 1781.

Yesterday I wasted in the world;
at my return home in the evening I got your sweet memorial,
which was acceptable and comfortable;
Let us not be anxious about branching and spreading:
but take root downwards in the hidden life;
so shall we stand against the dangers which attend both from sun and wind;
from popular favour, and popular dislike.
I greatly love the littleness;
a grain of gold is of greater value than a deal of base metal.
Remember the bow, which hangs on the pin, unbent, till by command it is taken down,
and used; thus it preserves its force and elasticity.
May your bow abide in strength, and the arms of your hand be made strong.
I cannot express the love I have felt and feel for you; again, keep low and humble,
and let self be of no reputation.
Those who covet the applause of men, and have an ear out for it, like listeners,
seldom hear good of themselves;
but those feel most of the inward strength and unity of the brethren,
who seek that honour which comes from God only.

[.signed-section-context-open]
10th month 1781.

I am obliged to you for your letter, for the openness and familiarity of it,
and for the friendship and freedom which it breathes.
I feel somewhat like a father, or rather a grandfather,
who likes very well to hear his child prattle to himself,
yet rebukes it when he fears it makes too free with another.
To branch out too diffusively in the epistolary way has a snare in it.
A multitude of correspondents is troublesome,
and there is a danger of there being more leaves than fruit.
We are variously appointed:
some perhaps may be allowed to indulge their inventive faculty,
and a vein of imagination, which others would be inwardly hurt by attempting.
Each of us should keep within the limits of our own tether.
We are each of us expressly told,
(as our first parents were) what is the fruit forbidden to us severally,
and death in a greater or lesser degree follows, if we touch it.
I believe some anointed servants have been hurt by allowing
their imaginations to wander upon unprofitable subjects,
as well as reading unprofitable books, and writing to an unprofitable degree.
A great deal depends on such keeping their vessels clean: there is a defilement,
which though it be not gross,
yet renders the vessel unfit for the reception of the heavenly virtue; or,
if it be infused, it loses of its fine quality, and is adulterated.
But, says the apostle, the will of God is, that you should abstain from fornication,
and that every one of you should know how to possess
his vessel in sanctification and honour.
May it be your care, my dear child, diligently to wait for the renewal of that baptism,
which keeps the vessel clean,
that so when the master of the house shall think fit to take it off the shelf,
(where it may have been stood for some time,
with the mouth downward) it may be ready for immediate use.

[.signed-section-context-open]
2nd month 1782.

I am not so solicitous about the permanence of our epistolary correspondence,
as I am about the permanence of pure love and real friendship between us.
Epistles, like testimonies and declarations, may cease, having had their day,
but fervent charity should abide undiminished.
When I was last in England,
I happened somewhere to hear that you had a propensity to write much:
I thought there was a danger in it,
and I knew not how to act more consistently with that friendship which I felt and expressed,
than to warn you of the danger.
I threw my then present thoughts together on the subject, and spread them before you.
I know not how I expressed them,
but I know I did not mean thereby to preclude the freedom of a fellowship between us,
which may be limited and enlarged according to our best feelings.

I kept no copy of my letter; if any word or expression in it escaped me,
which was capable of giving you offence,
I request you will be so kind as to quote it with the context; and I shall I hope,
either explain to your satisfaction or condemn it.
You speakers ought to be very ready to hear.
I have seen some very sensible seasonable reprehensions of yours,
which as they were well meant were also well taken.
Little cautionary hints often make up the most profitable,
though perhaps not the most pleasing part of a letter.
I thought it prettily expressed by Catherine Payton
long ago in a letter to a correspondent of hers;
"`I would not have you think that I write this to please the natural part; no,
far be it from me to offer the incense of flattery,
or even pain my friends with a recital of their excellencies:
true friendship needs no such weak supports;
but is rather pleased with judicious reproofs.`"

As to my ever going again to your land, or any of my children,
it is quite a matter of uncertainty, enveloped in the cloud of futurity.
I have earnestly desired, and especially of late,
that I might not be permitted to go here and there lightly and foolishly;
but that divine wisdom might be graciously pleased to order my way and guide my steps.
I am blind and weak and ignorant, I think in a great degree;
and if merciful help does not interpose,
I am sure I shall be able neither to stand nor go.
Some of superior abilities and strength may trust in one thing or another; but as for me,
I have nothing to trust to for the preservation and welfare of me and mine,
but the mercy and condescending notice of the Lord Almighty.

[.signed-section-context-open]
12th month 1782.

I remembered as I lay in bed that I was in debt to a long, instructive, affectionate,
obliging epistle of yours,
to which I have no sort of expectation of making anything like an adequate return;
neither have I, that I know of, such emulation about me.
Honest friends, in entertaining one another, should not vie in elegance and superfluity,
but simply and cordially bring out the best they
happen to have in the house for their guests:
and though the fare may seem mean, yet if it be sound and savoury,
and served up by clean hands, there is no reason to be ashamed of it.
It is the affecting to appear something above our abilities that renders us contemptible,
and which if persisted in will be in danger of making us bankrupts.
But why these strictures?
They have no pointed meaning, my dear cousin; they are general observations.
I hope and believe we are both pretty clear of affectation, and superfluity,
and ostentation, though unintentionally I fell on this subject.
Love and unity, I trust, subsists between us;
and if admonition was necessary to be imparted,
I also trust we should receive it from each other
without having a recourse to any oblique insinuation.

They call our dwelling the Retreat.
It is indeed so in some respect; but annoyances of one sort or other will break in.
Flies are most troublesome in the shade.
To keep low and humble, to step cautiously and feelingly,
to watch diligently over the movements in our minds,
to wait for that baptising virtue which makes and preserves sweet and clean,
to be as good servants ready for every occasional duty which may be unexpectedly required;
this is the state we desire to be found in, and wish it was more our experience.
But we are poor,
and desire the prayers and sympathy of our dear friends
to whom we are united in the fellowship of suffering.

[.signed-section-context-open]
Twelfth month 1789.

When we prescribe for such as you are, we must also take in the mind,
which often affects and is affected by the organs of the body.
Be an obedient child.
Now a child does not reason a great deal,
nor puzzle itself with a consideration of probable consequences;
its duty and its praise are simply to do as it is bid.
This is acceptable to the great father of the family in heaven and on earth;
this is uniting in the chorus, in the blest harmony; this is not interrupting, confusing,
or retarding the great work of glory to God, and good will to men,
but it is promoting and forwarding it according to the divine will.
The stars in their courses fought against Sisera: not only those of the first magnitude,
but we may believe the lesser stars also, seeing they fought in their courses.
Of whatever degree in the heavenly host, my beloved friend,
you may esteem yourself to be,
(and I am sure I care not how little that is in your own eyes) be encouraged
to persevere in unreserved dedication of all to the cause of Christ.
The kingdoms of this world seem in an unusual ferment,
and the bottom on which the false religions of it are founded, is altogether slight,
precarious, and uncertain.
Who knows how near the hour may be when it shall please the Omnipotent to rend the veil,
which obscures the spiritual sight of mankind,
and to reveal himself to the human species in a more general way, saying,
as at the beginning of creation, "`Let there be light, and there was light.`"
May you, who are called and chosen, and instructed, and fitted,
and furnished for the Master`'s service, be disencumbered and ready,
willingly to run on his errands with "`Here am I:
send me;`" diligently attending to the fresh and fresh pointings
and directions of wisdom in the course of your service:
so will the great and glorious work be likely to prosper in your hands,
and your peace will run down as a river through the present life,
bearing and supporting your spirits till you are conveyed
to the ocean and fullness of everlasting peace and joy.

[.signed-section-context-open]
Eleventh month 1790.

As I lay awake in bed this morning, you occurred to me; and no wonder,
as you are the frequent companion of my thoughts.
You seemed to me rather poor and low, like myself;
and I thought I would try if I could converse with you in this manner.
I do not want to cut a flourish in praise of poverty; as some people,
instead of bowing down under and bearing the cross,
appear to me to ride exultingly and ostentatiously upon it:
but I want just to manifest by this little token of my sensibility
and affectionate sympathy with you:
neither do I need to give you advice on the occasion.
I am not so vain and foolish as to think you stand in need of my advice.
You are a trained servant, and are acquainted by this time with your Master`'s ways,
and manner: you have, though young in years, been long under his holy discipline,
and know that much exercise, conflict and probation,
is continually to be gone through within; in order to be made perfect,
thoroughly furnished unto all good works, as was said of the Master himself.
Though he were a son, yet learned he obedience by the things which he suffered.
You have drank deeply of divine consolation,
and you have known a walking in the light of the Lord;
yes your path has been for a season as the shining light.
No wonder then that in turn you should not only be stripped of your priestly robes,
but like Joshua be clothed even with filthy garments, compassed with the troubles,
and perplexities, which belong to us as being also flesh.
I believe indeed that those, who ascend to the greatest heights of the holy hill,
and as instruments, are made most eminently useful:
I believe that those have to descend proportionably into the lower parts of the earth,
and have the greatest need to experience a being
buried with Christ by baptism unto death.
Such is the frailty and fallibility of our compound natures;
that the great author of them knows there is a necessity for our
undergoing repeated humiliations and abasements of self,
that we may repeatedly know and feel,
and be made thoroughly sensible of this important essential truth;
"`That we are not sufficient of ourselves even to think any good things as of ourselves:
but our sufficiency is of God.`"

[.letter-heading]
To +++_________+++

O what an element is divine love! in this the children of the light live, and breathe,
and move, and act: there is no infection here; it is clear, pure, and salutary.
I would be glad that that poor man was effectually conquered.
You are dear to me for having so followed, and been so guided in service,
as to be instrumental of good in his case.

Your prayers and your alms-deeds, your secret wrestlings of spirit,
and your private labours and communications will, no doubt, come up in memorial.

I believe you know that I received yours of the 5th of last month,
the contents are such as this state of existence often affords:
it is indeed a cup of mixture;
but then it is wisely mixed and tempered by the great hand.
It it not for us poor, blind, and ignorant creatures to say, What are you doing?
--but patiently to submit and reverently to bow in humble
persuasion that the judge of all the earth does right.
Well, it is glad tidings to me, that you are getting on so bravely;
and no doubt cause of deep humiliation and gratitude to you both,
that the arm of everlasting strength has been experienced
in such renewed and such effectual support.
This is great encouragement to proceed in the track of revealed duty.
I believe many have greatly hurt themselves,
and become lame and dwarfish all their lives long,
by letting in the reasoner and the discourager,
consulting too much human prudence and propriety, limiting the spirit,
which is the Holy One, starting aside from services like an affrighted horse on the road,
and being in great fear where no fear is.
But you, beloved friend, seem to have got out of the byways and crooked paths,
on to the high road for travellers, leading to the city of the great King;
and by continuing thus diligent, faithful, and devoted,
you will (I trust) know more and more distinctly the Master`'s will,
and be more and more strengthened to perform it.
So if it be consistent with Infinite Wisdom to prolong your life here,
you will be happy in yourself, and useful in the creation of God;
and if a short warning should summon you from this stage and conflict,
this mortal will put on immortality;
your sorrows here be changed into unmixed everlasting joy;
and your example and memorial will live, and teach, and preach to succeeding generations.

But alas, I am a poor weak, tottering creature, a much fitter object to be ministered to,
than qualified to minister to another.
You know where are hid your effectual supplies, and in whom are all your fresh springs.
Yet what I was made able to do, you may be sure I was quite willing and glad to do,
to travail, to beg and to pray for you.
I am glad that you are out on service: it is the way for you to grow strong,
and to get above the little glooms and recurring perplexities and despondencies,
which from various causes cast down and disquiet the soul.
By being thus employed, you will through exercise become a trained servant,
and be made capable to instruct others, your fellow servants,
in the duties of their places and stations, feeding not only the lambs,
but the sheep of Christ.
Go on then, my dear friend; be not afraid of the face of man,
nor ashamed of the cross of Christ.
I repeat, (I have often repeated it) for I seem to have little new to say,
--no matter if fresh life be on the offering,--I repeat, that nothing more glorious,
more dignifying, more beneficial to mankind,
and more worthy of the dedication of all our faculties to espouse and promote,
ever was let down from heaven to earth.
Not only true civilization of manners, and sound morality,
but life and immortality (i. e. immortal life) and
eternal salvation are brought to light,
are made manifest through the gospel:
a dispensation of which (I doubt not) is committed to you,
in order to advance according to your gift and measure, these great and glorious ends.
