== Letters 52 &#8212; 63

[.letter-heading]
Letter 52.

[.signed-section-context-open]
26th of Fourth month 1796.

It is now more than twelve months since I received your kind letter,
though there has not passed one month, perhaps not one day,
in which I have not affectionately remembered you;
and you would long since have had a reply to it,
if I had thought you had stood in need of any instruction, or help from me.
If the enemy has gained any advantage by my silence, either against you or me,
I am sorry for it;
but I believe you have been too long acquainted with
his devices to be in much danger from that quarter.

The very poor account you condescended to write me of your own situation,
did not at all surprise me; it was just such a one as I should have expected from you;
the happy humble state of your mind,
added to its great sensibility under the humiliating gradual process of regeneration,
disposes to such feelings and such fears.
I believe there are many of us,
were it not that we are sometimes favoured for the sake of others,
should have much the same account to give of ourselves.
You may be sure enough my dear friend,
that if Providence sees fit to make any other use
of you than that which he has long done,
as a preacher of righteousness in life and conduct, as a father to the poor,
and a succourer of many,
when the right time shall come you will not be left in any doubt about it;
but if otherwise, it is all right,
it is enough if we are found faithful stewards in
the station which the Master has appointed us,
whether as stewards of grace, or of the things of this life.
What cause have we not only to be satisfied with, but thankful for our lots?
Our outward circumstances, our mental powers, and spiritual gifts,
are diversified by him who only is wise,
and it is deeply fixed as a sentiment in my mind, that the allotment,
or gifts of each individual of us, if we act well our part,
and are faithful in the improvement,
will conduce more completely to fill up the measure of our happiness through all eternity,
than any varied portion could possibly do.
The great point by which glory, honour, and peace, both here and forever,
would certainly be gained, is, for each of us to stand in our own lots,
resigned to the will of God in all the varied dispensations of his providence,
seeking no more of either prosperity or adversity, of poverty or riches,
of suffering or rejoicing, in things spiritual or temporal,
than he knows to be best for us.

I note all that you have hinted of some circumstances, which as a parent,
do furnish for you some degree of affliction; experience has taught me to sympathize,
in a case which, though somewhat dissimilar, has been to me exceedingly distressing; but,
my dear friend, what can we do for them?
Nothing of ourselves, to be sure, that will do any good, but, through divine help,
we can love, pity, and pray for them; and indeed with some,
this is the last and only resource; and O, the fear that I have felt,
lest I should be deficient here.

The fervent prayer of a righteous man avails much;
let us be found diligent in this holy exercise:
the example of Job is worthy our imitation,
and with what fervency did the father of the faithful
address the Most high with this petition:
"`O that Ishmael might live before you!`"
God forbid, said the prophet Samuel, concerning the rebellious house of Israel,
that I should sin against the Lord, in ceasing to pray for you.
O that both you and I may be found fervent enough, and frequent, in this great duty,
often retiring to the closet of our hearts, the temple which God has chosen,
and there to pour forth our supplications to our Father who is in heaven,
that he would take our children under his care.
Much benefit would arise from this practice.

I am very far from thinking you a stranger to this Christian exercise;
for anything I know you may have gone far beyond me in the practice; if so,
permit me to recommend it to you to persevere,
and for your encouragement let us remember the example of the woman who came to Christ,
and would not be denied, Matt. 15:22, and likewise the parable of our blessed Lord,
by which he taught that men should always pray, and not faint.
Luke 18.
O,
the consolation and support we also should derive
from thus spreading our cause before the Lord,
and committing ourselves, our children, and our all into his hands,
who is the Shepherd and Bishop of soul.

Wishing you every comfort, and every blessing, consistent with the Divine will,

[.signed-section-closing]
I remain your affectionate and sincere friend,

[.signed-section-signature]
John Thorp.

[.letter-heading]
Letter 53.

[.signed-section-context-open]
2nd of Second month 1798.

Though I have not written to you now of a long time,
it would be great injustice to suppose I had forgot you;
I do not even suspect you on the same account, and I am not willing to be suspected,
I remember you often, my dear friend, I believe in the manner you would wish me,
according to ability and strength afforded,
and I have the comfort also to believe you are graciously remembered of God; yet,
like a wise and tender father,
he knows how to preserve his people humble and in a state of deep abasement before him,
because he knows, who knows all things, that it is best and safest for us.
I have, indeed, often observed with humble admiration,
the unfailing wisdom of his discipline in this respect;
always increasing with all his gifts and favours, our humble abasement before him.
Seeing in the light the necessity of this, I have often fervently petitioned for it,
and though painful apprehensions and many fears do
generally attend a state of spiritual desertion,
as if it was some way or other our own fault,
and the consequence of some impropriety of conduct, yet,
as the eye is kept single to him in submission,
and the hunger and thirst after his righteousness maintained, such shall at seasons,
when it pleases him,
and most certainly when their days of mourning and conflict here are over,
be forever filled and clothed with it;
so that I believe the Lord would have us to be encouraged to press forward,
keeping the mark in view: "`Be not weary in well-doing,
in due season you shall reap if you faint not.`"
Nothing has happened to us, but such things as are common to our fellow pilgrims;
though I know the enemy tells a clean contrary story, and would have us to believe,
that our case and lot is harder and worse than has fallen to the share of any other;
but no credit must be given to him, who was a liar from the beginning,
and who always seeks to cast down those whom he cannot exalt
above measure.--But you are not ignorant of his devices;
the good soldier, you know, must endure hardness;
and let us always remember him of whom the prophet spoke, that he was a man of sorrows,
and acquainted with grief;
and can we expect to get to heaven without passing through a similar process?

You and I have now been long engaged in the Christian warfare,
I humbly trust not altogether unsuccessfully,
we can be at no great distance from the end of the Christian race;
the crown is at the end of it,
laid up for and shall be given to those who love the appearing of the Lord,
the righteous judge; which I have no doubt is your case;
I pray that it may evermore be mine.

Give my love to your wife,
who I believe has made great progress in that way that will end in peace.
O how I long,
how I wish to encourage all my fellow pilgrims to persevere in the high way to the kingdom,
and in an especial manner such at have been long on their journey,
and are at no great distance from the heavenly country,
that the strength of all such may be so renewed, that they may run without being weary,
that they may walk and not faint.

[.signed-section-signature]
John Thorp.

[.letter-heading]
Letter 54.

[.signed-section-context-open]
28th of Tenth month 1799.

Many a time of late have I thought I would write to you,
and I certainly should before now,
if I had not felt myself so almost constantly unfit for any sort of communication,
through somewhat of an uncommon degree of what we call spiritual poverty.
I do not say this in a way of complaint, I have no doubt it is all in wisdom.
I do not even wish the dispensation to be changed before the time.
I have no cause to believe I am alone in this condition,
though as to the degree I am sometimes ready to think so;
I do not only feel so destitute of spiritual enjoyments,
but of ability to do anything to help myself,
so that although I have been endeavouring after spiritual attainments,
now for more than forty years, yet, when I sit down in meetings,
in a stripped state to a degree of nakedness, I know no more how to help myself,
than when I was a little child; sometimes as my mind sinks into submission,
I am permitted to possess a little quietness and peace, and sometimes,
for causes that I do not so clearly know, I experience considerable conflict;
but as I said before, I have no doubt but this is all in mercy.
I know him in whom I have I have believed,
and my soul desires to bow in submission to all his dispensations.

It is very unusual for me to speak or write so much about myself,
and I do not know how I came to do it now, unless it be to convince you,
if you also should sometimes pass through seasons of deep humiliation and abasement,
that you are not indeed the poorest of the spiritual family; no,
if you were to think your case was not at all to be compared to others,
I myself have thought so too; how often have I been ready to say, Yes,
these good people may have to pass through these baptisms,
perhaps for their further purification,
or it may be to enable them to speak more feelingly to others; but what is that to me?
I have reason to fear mine is rather a state than a baptism,
and proceeds from the unregenerate condition of my own heart:
what else can be the reason why I am so insensible of good,
and sit meeting after meeting as the parched heath in the desert; no,
even when testimonies are borne I am like the deaf adder.
Thus many a time, in years that are now past,
has my poor mind been tossed as with a tempest, and not comforted,
and thus at seasons am I permitted in measure to be exercised to this day:
many a time have I said in my heart, Lord,
if these dispensations are intended to make me feel what I am without you,
and that of myself I can do nothing; that there is none good but one,
and that is God--if to convince me of this be your gracious purpose, surely it is enough;
I am full of this conviction;
notwithstanding when I consider what the ever blessed Master suffered for us,
when he trod the wine-press alone, and gave his life a ransom for many,
I am even ashamed to think anything of what we meet with, of the nature of suffering,
in our daily Christian warfare.
No, my dear friend, let us rather glory in tribulations also:
inasmuch as we are made thereby the more conformable to his blessed example,
who was a man of sorrow, and acquainted with grief.

I have just now, since writing the above, given your last kind Christian letter,
dated 9th month, 1798, a fresh reading,
of which I do not know that I have much to remark,
except that you think too ill of yourself, and too well of me;
in both respects perhaps this letter may help to set you right.
Of the subject of human infirmities,
I once heard (and I thought it did me good) a truly
living humble minister of the gospel say,
that though he could not say he loved the Lord his God with all his heart,
and his neighbour as himself; he could, or dared say this,
that he had not left off striving to arrive at that attainment.
Let us then keep up the warfare as good soldiers of Christ: and O,
let us be careful and diligent in this important business:
do not let the world have too much of our time, or attention;
we at our time of life must very soon leave it.
Be encouraged, my dear friend, to persevere in the Christian warfare against the world,
the flesh, and the devil: occupy with the talents received; attend to your stewardship,
both of grace and the things of this life;
do all the good the blessed Master bids you do, both to the souls and bodies of men:
and then, never fear, when the day of reckoning shall come,
you shall receive the answer of "`Well done, good and faithful servant,
enter into the joy of your Lord.`"
Let us number our mercies, and commemorate the many favours, preservations,
and deliverances that have been hitherto vouchsafed unto us;
and bless the name of him who lives forever,
for what he has given and for all he has denied;
and when his fatherly corrections and chastisements may be exercised upon us,
those certain evidences of filiation, O, that we may be enabled, in feeling submission,
to kiss the rod;
thus would all the gracious designs of our heavenly Father be accomplished,
and all his dispensations would be sanctified unto us.

[.signed-section-closing]
I am your affectionate friend,

[.signed-section-signature]
John Thorp.

[.letter-heading]
Letter 55.

[.signed-section-context-open]
Plymouth, 22nd of First month 1747.

[.salutation]
Dear Friend, M. W.

In a measure of the divine life and fellowship of the Gospel I tenderly salute you,
and I choose the present time as you are brought very fresh to my remembrance,
as you have indeed many times been,
especially about the close of my last Cornish journey; for as in the course of it,
and in the services to which I was called,
I witnessed the Lord`'s supporting arm to be near me,
so was my mind frequently tendered and raised into a living sense of the unbounded
goodness and wonderful condescension of our great master to his poor servants,
who are labouring to be nothing in themselves; empty vessels; that He may be all,
and they what he pleases to make them.
The exaltation they are seeking after is the being raised
from death to fulness of life by virtue of his divine power,
and that in and by its mighty working in them,
that they may be made instruments effectual to extend
its dominion in the hearts of their fellow mortals.
In a sense of these things I am engaged to call encouragingly to you.
What signifies all the opposition that men can make to the work of God?
They may endeavour to the utmost of their power and the depth of
their craft either to suppress or undermine this work,
but all in vain; for he that sits in heaven shall laugh them to scorn,
and when he sees fit shall scatter them as the driven stubble,
and pour contempt upon them.
In the mean time it is our prudence to be still, having our eye only to our Leader,
and not fret too much because of evil doers;
for as we are in the discharge of our duty all will be well with us;
and though there may be baptizing times of deep suffering with the oppressed seed,
as well as hard work to get into our services through the opposition of dark spirits,
yet as we are kept in innocence and uprightness toward God, and so out of condemnation,
I think all this may be cheerfully borne for the sake of that peace and divine
sweetness wherewith he is often pleased to season and overshadow our spirits;
for which cause my advice to you is to move strait forward,
without looking behind or about you,
having found much thoughtfulness is very weakening and frequently
made use of by the enemy to hurry and deject us,
whereas were we cheerfully to undergo the suffering we are called to,
it would be much easier to be gone through than when the
difficulty is increased by our own uneasy reflections.
Let me therefore once more speak encouragingly to you, and say, never mind the opposers,
but follow your engagements simply and fear no consequences,
for nothing but good can be the consequence of sincere obedience.

And in regard to the sense we have of our own weakness and unworthiness as creatures,
let us consider how much we have already seen of the all sufficiency of his powerful arm,
which we have had a full evidence has been stretched out for our help.
Have we not seen his wonders in the deep?
And why then should we doubt his love towards us?
He can use what instruments he pleases, and as it has pleased him to make use of us,
let us not permit the enemy to perplex our minds about our own unworthiness and unfitness;
it is his power and holy unction that is the only qualification for his work,
and as he is pleased to dispense this,
let us be satisfied and never mind how mean we ourselves are;
for let us be low as we may,
the highest among mortals is as low in his eye before whom all nations
are as the drop of the bucket or the small dust of the balance.

I am sensible that at times we are in great poverty, and leanness comes over us;
but I have found that as our eye is to the Lord (though he may see fit to try
us with lack of bread) he supports under the hunger to which the blessing is,
helping us through the dark stormy days and times of famine;
blessing the little he is pleased to give, and making it sufficient for our support,
and to keep us alive till he sends rain on the land;
and thus is this (though the sorest of all exercises) made tolerable,
as we keep in the faith and patience of the saints;
and nothing embitters it so much as letting in consultations and reasonings.

Thus, my dear friend, have I found things, and thus do I
with much simplicity mention them: your experience I am sensible, in many things,
far exceeds mine, yet perhaps you may catch a little light from some part of this letter,
which is written from no other motive but love.

[.signed-section-signature]
W+++.+++ C.

[.letter-heading]
Letter 56.

I have thus far, as your sympathizing friend,
suggested everything that occurs to me which might be of use in your disorder;
but the great medicine from above, the sacred balm, the Almighty,
and unerring hand of divine mercy,
is the only certain cure or alleviation of the sufferings and ills
attending poor pilgrims in their travel through this vale of tears.
What happiness is it to be in possession of this knowledge?
Long have you been in possession of it;
long have you looked to the God of Jacob as your strength,
and he has owned you in your own heart by lifting
up the light of his countenance upon you,
and by being your present help in every needful time,
and to those of your acquaintance who know and love him,
have you been truly near and honourable.

My heart embraces you while I write,
in the love which stretches beyond the narrow bounds of time,
and is immortal in the root; and claims kindred with every child of the family of God.
Many such claims has my soul in particular on eternity, or life would be an insipid way,
a bitter thing to me.

Genuine friendship is a plant from heaven;
it bears the most pleasant fruit we taste below;
but it is eternity must exalt this fruit to its highest flavour.
Love, the badge, the employment,
and delight of the real disciple and true child of Christ, is, and must be,
its own everlasting reward.

I lost a father very young, but he who has been a tender father to me,
left me to honour his memory.
Dear sisters, of good dispositions, have been removed.
A loving, worthy and dearly beloved wife, the desire of my eyes,
was taken from me by a stroke.
My very dear friend, your brother, was called home in the strength of life.
My tender mother, dear to me by the natural tie, but inexpressibly so as a friend,
her too have I lost in the language of men.
But are all these souls lost?
I trust not.
For I cannot bear the thought:
let me but continue to labour to know him "`Who is the resurrection and the life,`"
to preserve and cultivate that life which he in infinite mercy has raised in me,
and I have no doubt, but I shall rejoin them and never be separated from them, more;
for well am I assured, that true friendship survives the grave.

You will from what I have written, judge of my mind in regard to you.
Grave advices to one who has endeavoured to live by supreme direction,
would be nauseously impertinent, and consolation unnecessary,
further than the overflowings of a friendly heart,
ready to join him who sucks at the everlasting breasts.
Calmly therefore, warm at heart, with brotherly love,
with hopes full of immortality for you, and for myself,
I dearly salute you and your spouse, remaining,

[.signed-section-closing]
Your affectionate friend,

[.signed-section-signature]
W+++.+++ C

[.letter-heading]
Letter 57.

[.letter-heading]
To S. Taylor, of Manchester.

[.signed-section-context-open]
Dudley, 4th of Second month 1753.

[.salutation]
Dear Friend,

Considering the contents of your last acceptable favour,
I think you might reasonably have expected a return before now;
but you well know everybody has not the command of their pens at all times,
so I hope you have suspended passing judgment on my long silence.
I am conscious to myself of my friendship for you, as well as convinced of yours for me,
which I hope will be lasting as our lives, nor will not terminate with time;
for as it is constituted by the unchangeable truth,
we must one of us depart from that before the fellowship can be broken,
which I earnestly pray may never be our unhappy lots;
for it had been better for us never to have been
made partakers of the power of the world to come,
than for us to fall from the knowledge and grace received;
but I have no fears on this hand on your account,
although I well know temptations and dangers attend you, as well as poor me; but you,
by a longer experience, are, I believe, better armed against them,
and more quick in discerning the secret attacks of the enemy.

Do not think I flatter, for I speak truly when I say, I am but a child, a mere infant,
in the experimental part of religion;
however favoured at times in the sight of the people,
all which I think I would cheerfully resign to witness
a growth in the root of eternal life;
it being that only which will gain the approbation
of him who judges not by outward appearances,
but looks at the heart.

O the necessity of a continual watchfulness, and holy awe, to walk before him blameless:
my soul is distressed under the consideration of it,
lest those who set out later should get before me in this heavenly race:
you would perhaps tell me my fears were groundless, but, my dear friend,
could you discern the fluctuations of my mind, the various turns of the passions,
the barrenness of my spirit, and how it wanders from the centre of its strength,
you would acknowledge there was cause to fear and tremble;
for my standing seems to be very precarious.

O talk no more, I beseech you, of my stability, watchfulness, and readiness,
to perform the duties required.
If I have been assisted to do any little service for my God, to him belongs the glory.
I wish I was more worthy of his favours;
but am too sensible of my deficiencies to receive any part of the praise.
However,
I hope to press forward towards the mark of the prize
of the high calling in Christ Jesus:
which I apprehend to be a constant and entire submission
to the will of our heavenly Father,
whether it be in doing or suffering: this is the happy, humble,
yet exalted state my soul at times pants after,
and longs to make a sacrifice of the esteem of those who are in the spirit of the world,
to whom let me be unknown and had in derision,
so that I may but enjoy that fellowship with the
saints which stands in communion with the Father,
Son, and Holy Spirit.

My dear friend, I hope your excuse for these incorrect hints: you may observe, by them,
the labour of my soul, which I am unexpectedly led to communicate;
(though I do it but seldom) but I know to whom I am writing, and give liberty to my pen.
I am much better in health than when I wrote you last.
I then was ready to conclude myself like a ship that stood fair for the harbour,
but am now tossed back on the dangerous ocean of life,
destined to endure a longer contest with the storms, etc. attending the passage over it.

Well be it so, I will not say it was an adverse wind that blew me back;
doubtless my vessel was not richly enough laden to enter the celestial port,
and its being continued longer at sea, was intended that I might add to its burden.
O that this grace may not be bestowed in vain:
but may I use all diligence to make good the voyage,
that I may happily land safe at last on the shore of endless felicity.

My mother is brave and well, and with my sister unites in dear love to you;
in the same I desire to be remembered to your brother and friends at Manchester:
it is late, and time to bid you farewell, which I do as much as I am capable,
in the gospel, and with great sincerity, subscribe myself, your affectionate friend,

[.signed-section-signature]
Catherine Payton.

[.letter-heading]
Letter 58.

[.signed-section-context-open]
Bury, (Suffolk) 30th of First month 1768.

[.salutation]
Dear Friend,

It is with great nearness and satisfaction that I
remember my particular friends in Pennsylvania,
among whom you are often brought to my remembrance,
and if strength of desire could have sympathetically affected your heart,
I should have had some little stream through your quill,
which when in hand is not slow to move on pleasing subjects.
I consider your situation at present, and make no doubt but you are often deeply bowed,
and tenderly engaged,
to implore strength and clear understanding to discharge yourself honestly,
and to keep a conscience void of offence both towards God and man.
I have often thought that such men, who see themselves in the true light,
and are careful to dwell therein, their eye being single to the glory of God,
their whole body is full of light,
every sense and faculty being thereby quickened and enlivened: such men, I say,
see their gifts, and know to use them both in church and state,
and are thereto constrained for the Lord`'s sake,
which is the true spring that gives perfect motion to every duty,
and preserves the whole in harmonious order.

When we, under proper influence, have discharged ourselves,
sometimes applause will shine on us, and self (with the unstable multitude),
will tempt us to take a view with the help of his spectacles,
that gifts and qualifications may be admired.
This snare, seen and avoided, perhaps self will turn, to discourage from duty,
and breathe such a carping mist, that it will seem to darken the very air round about,
and then we cannot judge perfectly.
We are all servants, and it is good for us to dispatch the business,
do our Master`'s errand, and return home quickly,
not to play in the sunshine of applause.
Neither tarry from home in the night.
Our Master tabernacles in the clean heart: if we dwell there,
we shall see our business by his light; and when he is pleased to move or send,
the light goes before, and will last, until the errand be performed.
Dear friend, I am thankful on your behalf,
because I fully believe you well know the meaning of the above hints,
and that in the Lord alone is our peace, rest, and refreshment.

Oh!--the value of deep retirement, and even sometimes a cessation of all thinking,
that we may be renewed in a right way of thinking,
and our enfeebled spirits strengthened and enabled to run the Christian race,
hold out to the end in well doing, and obtain the reward of eternal life;
which that we may receive is the earnest breathing of my soul.

I had to look on Pennsylvania, and was made to admire her goodly situation,
the privileges that her inhabitants enjoy.
May the people humble themselves, and walk worthy the blessings of heaven,
even respecting the state: which if they do, I make no doubt but the Lord will raise up,
and qualify men to take on them the care and concern for the whole,
with which some worthies were clothed, that are now removed.
And, in remembering the church,
when I have beheld the ruinous plight of her walls and discipline in this nation,
I have been ready to say, her King is in the midst,
and the law is received from his mouth.

May the aged bow their heads, and worship before the Lord;
the middle aged keep humble under his fear, observing his teaching;
that the places of the elders may be filled, who are removed from among us;
and that the Lord may continue to pour forth of his spirit and anointing on our offspring,
to the latest generation.

I did intend to have written historically, but must refer you to your dear brother,
who still continues with me an agreeable companion; shall therefore, with dear love,
conclude your real friend,

[.signed-section-signature]
John Churchman.

[.letter-heading]
Letter 59.

[.signed-section-context-open]
Ware, 23rd of 2nd month, 1747.

[.salutation]
My Dear Friend,

Herewith I send you a few sheets intended to prove, that scripture knowledge,
without Divine aid, is insufficient to conduct a Christian safely on his way;
for mankind since the fall, and the consequent degeneracy,
have for the most part centered in a wretched neglect
and ignorance of their real duty to the Creator.
And although no duty is more emphatically pressed upon those who profess
to own and revere the mission and messiahship of the Son of God,
than that of loving the Divinity with the most pure and generous affection (even
in that which they deem their rule) yet that being of itself a dead letter,
and unable without fresh participations of life and virtue,
from a living and energetic principle,
to inspire or furnish the creature either with sensations of,
or faculties for the perception or performance of so sublime a duty,
and so opposite to their natural tastes,
they have generally beheld the precepts relative
thereto with superficial and fallacious views;
so that although they have gathered from the letter apprehensions of other duties,
as worship, etc. yet that of Divine love has remained too much discarded,
or at least disregarded by them.

Yet blessed be the Father and fountain of love and consolations,
through the several series of time,
he has been graciously pleased to discover himself to a remnant,
who by the lively influence and manifestation of
divine favour have been led to love him again.
And although perhaps they may not have a distinct
discursive and explicit knowledge of some truths,
yet the sincerity of their love and affection, the product of the Divine principle,
has ever been acceptable.
And He, who ever remains diffusive and bountiful in communications to his creatures,
is now, through the emanations of his divine light and life,
imparting to his little ones, his waiting, dependent, and debased children,
glorious discoveries of himself,
and granting to reveal those mysteries which have
been hid for ages from the wise and prudent,
even to babes and sucklings; no doubt for this great and glorious purpose, that by them,
in his own time and way, his praise may be perfected.

The doctrine of the internal and immediate revelation of Divine light and life,
(which we profess) operating by love (and productive in the soul resigned
to its influence and guidance of a proper love to the Creator,
and to the creature for his sake) is the most noble and
beneficent sentiment that ever mankind was blest with.
It is this, as it comes to have a rightful preeminence in the world,
and prevalence over the mind, which alone would regulate all disorders,
by subjecting all to the will and order of the Creator.
It would demonstrate to the devoted soul, the impossibility of loving God too much,
or of denying ourselves of too much for his sake,
who denied himself of so much for our sake,
by humbling himself and becoming subject to the shame and death of the cross;
condescending to dignify the meanest of mortals with invaluable blessings.
It would teach us to renounce the most secret acts
of infidelity and dishonesty towards Him,
and to abandon the most harmless gratifications of self and nature,
when they tended to obstruct and retard that state of abstraction and purification,
necessary to the discipleship of love.
It would perfect in us, the divine and moral virtues,
and qualify to answer every purpose of civil and religious society,
of which it would make us bright and useful members, and lead into every particular duty,
which either convictions in ourselves,
or the precept and example of good and faithful men,
might show to be agreeable to the divine will.
It would renew the face of the church; array Zion in beautiful garments,
render her fair as Jerusalem, "`comely as Tirzah,
terrible (for her power and strength) as an army with banners.`"
It would invest hoary heads with crowns of glory,
and induce our youth to a strict and religious emulation of the virtues of their ancestors,
and in our faithfulness, replenish each particular with that sensation and enjoyment,
which infinitely surpasses the conception of natural powers.

This alone can support in the most depressing and calamitous of human circumstances,
by favouring with the hope,
that nothing (however trying) shall ever be able to separate us
from the principal object of the soul`'s desire and affection;
a fear which awaits and frequently allays the most
joyous and delectable of human prospects and grandeurs.
That this Divine principle may have its proper scope and influence,
in your tender and favoured breast, is my sincere desire,
and the design of my submitting these mean and unpolished papers to your perusal;
and may your breathings, as you find access, be on my behalf,
that while I am led to press these truths on others,
I myself may not become a cast away therefrom; but in holy travail,
and united exercise of spirit, may we approach the house of God,
and ascend his holy mountain Zion, his sanctuary, from which "`his law shall go forth,
and his blessing be commanded, even life forevermore.`"

[.signed-section-closing]
I am your friend, with true regard,

[.signed-section-signature]
Samuel Scott.

[.letter-heading]
Letter 60.

[.signed-section-context-open]
Ware, 3rd of Second month 1750.

[.salutation]
Esteemed Friend,

Thankfulness attends my mind at this time,
that I am sensible there is a love infinitely stronger than all the powers of death and hell,
and a divine fellowship which no mutable accidents can impair,
neither time nor space interrupt:
for as it subsists alone by the power of an endless commandment,
so it is only maintained in the circulation of the blood of an everlasting covenant,
and enjoyed in its greatest strength and glory,
in the absence and deprivation of all visible and external objects;
in the entire silence of mental representations and introversion
of spirit towards the Fountain of life and blessedness.

O, my friend, let us labour more and more to cease from all that is visible and external,
and gather to the life of Jesus, the unchangeable foundation,
the standard lifted up to all nations, and the day-spring which has visited our souls;
for herein the quickened travelling exercised members of the church,
when under a total incapacity of personal communion
are one another`'s strength and joy in the Lord.
Here they receive the efficacy of the atonement made
by their holy head in the day of his humiliation;
the evidences of divine approbation, and a holy consolation.
And now, my friend, I may just signify,
that since I have been prevented having personal interaction with you,
I have been favoured at times to have you in living remembrance,
and have rejoiced to feel your soul (in a secret, invisible,
but very lively manner) in a holy travel towards the Father of life.
As to my own particular, since we last met,
I have not only experienced the close besiegings and bondage of the spirit of darkness,
and the contumelies and reproach of some of my fellow mortals,
who are taking their repose in external peace and affluence, unacquainted with the pangs,
pressures, and probations of an afflicted seed;
but likewise the kind interpositions of Almighty help and preservation.
O, we are some of us the monuments of an unspeakable and inconceivable mercy; and,
although it has been a day of inward and outward reproach and darkness,
yet I may say for your encouragement, that of late, at times,
the light of Zion has shined upon me in brightness.

A degree of gratitude at this time fills my heart, and in that I would just say, O come,
let us walk in the light.
I request your company and help of your spirit in
a close engagement in the way and work of the Lord;
and conclude your sincere friend,

[.signed-section-signature]
Samuel Scott.

[.postscript]
====

P+++.+++ S. The poetical pieces you will receive herewith, are the productions of one, who,
notwithstanding the soothing allurements of youth,
and a competent share of natural and acquired endowments,
is led to behold the wretched vanity and emptiness of all created beings,
to look upon Zion, and desire her beauty.
He reposes so great a confidence in you, as to submit them to your perusal,
with this restriction, that no copies may be taken therefrom.

====

[.letter-heading]
Letter 61.

[.signed-section-context-open]
16th of Second month 1753.

[.salutation]
Esteemed Friend,

I was sorry that I had not an opportunity of once more personally taking my leave of you:
but the floods of death, as mighty waters, seem to have overflowed my soul,
and rendered me incapable of performing those acts of religion
and friendship due to my Creator and my fellow creatures.
The usual assignment of the dead, is to be cast forth from among the living,
because of the inutility and obnoxiousness of their condition.
The countenance and presence of the Divinity alone,
imparts life and beauty to the creature, and how can one cut off therefrom,
covet the notice and observation of mortals,
but rather a lodging place in the wilderness, or a retreat in the desert?
I am clothed with sackcloth,
I have pitched my tent for a season at the gates of mourning;
expecting at times an invisible archer will before
long separate me forever from the living.
But while I bemoan the bitterness of such a state,
I think I see the generality of those around me
replete with sentiments of peace and gaiety,
though subjected to the same captivity.
All the children of Adam are, by the decree of Omnipotence,
separated from the life and favour of the Holy One,
and eternally barred from access thereto by any means,
but the influence and spirit of the Mediator, and as they abide in him,
who is their peace and atonement.
This light shines and enlightens every man; but O,
how few endure the fire of the sanctuary,
which he ordains to burn with a perpetual flame,
or persevere steadfastly in the paths which he prepares in strait places!
Was such a submission experienced, how would our woes cease,
our captivity be swallowed up of life,
and the garments of mourning be exchanged for praise!
The children of light would then rejoice together,
and the church, militant and triumphant, unite in adoration of Him,
who is perfect in beauty, and infinite in goodness.
Hereto have we been called with a call from heaven;
but when we consider how we have swerved therefrom, tears fill our eyes,
and heaviness our hearts.
In the absence of the bridegroom, the children of the bride chamber cannot but mourn;
nevertheless, dear friend, though we sorrow, let it not be without hope; and if we mourn,
let it be with the utmost privacy, and discretion.
The bridegroom of souls is the resurrection and the life; He can breathe on bones,
whose energy is departed from them; give beauty for ashes,
and fill the dust of the grave with the fragrance of the morning.

These broken and unconnected expressions I have penned in haste,
and send to you as some representation of my state, and a salutation of that respect,
which I desire always to bear towards those who have tasted that the Lord is gracious.

[.signed-section-signature]
Samuel Scott.

[.letter-heading]
Letter 62.

Although the apprehension of being soon personally separated from
one to whom I have been so nearly united in the bond of the gospel,
whom I have loved with the most unshaken affection,
and whose friendship and converse I have esteemed one of the greatest blessings of mutability,
had overspread my mind with the shades of anxiety: yet I have at this time to signify,
that he who makes the clouds his chariot,
has been pleased in some degree to console my spirit,
by favouring with some views of his all-sufficiency,
and the plenitude and superior excellence of those enjoyments which are in his presence,
and which flow from his holy throne,
and by representing a state of the deepest prostration
and self abasement at the footstool of the Lamb,
to transcend in glory the highest elevations of humanity,
and the most pleasing prospects and dignities of a transient world.

O, my friend, may we, out-soaring all the scenes of sense,
approach with humbled hearts the habitation of the Holiest,
that the skirts of his throne may be our pavilion,
and that in the sympathetic streams of love, we may enjoy a fellowship,
which not distance nor all the strength of men or
devils may ever be able to withhold from us.

It was by such an inseparable covenant, and bond of love,
Jonathan and David not only became of one soul,
but when subjected to an unpleasing separation,
they maintained the most strict and intimate union,
and demonstrated by the most convincing proofs an unshaken attachment.
I think I view at this time Jonathan relinquishing in spirit the
grandeur and employments of a sumptuous and brilliant court,
to embrace poor David, when covered with obloquy,
hunted as a partridge upon the mountains,
and secreted in the solitary retreat of Adullam.

May the same divine and inviolable friendship attend us through
the various intricacies and vicissitudes of a mortal sojournment.
A felicity which nothing can frustrate but a defection
in fidelity from the Father of spirits,
whereby the soul comes to forfeit the privileges of immortality,
and to be deprived of those delicate sensations requisite
for the perception of things unseen,
and the enjoyment of things hoped for,
and to be unhappily confined to the objects of sense;
the possession of which may yield a present satisfaction,
but their deprivation a torment forever.

And now my dear friend,
although I believe strong and many will be the efforts of an unwearied
adversary to divert you from following the Lord,
and to fill your soul with creatures and amusements,
yet be not discouraged even though he appear to encompass your paths with mountains,
and enclose you in fenced cities: for, behold your beloved comes upon the mountains,
causing your feet to tread upon the high places of the earth.

As these sentiments arose immediately and almost instantaneously in my mind,
at a season when infinite goodness was pleased to relieve my soul in the deepest misery,
I was willing to communicate them, leave them as bread upon the waters,
and therewith salute you, and bid you dearly farewell.

[.signed-section-signature]
Samuel Scott.

[.letter-heading]
Letter 63.

[.signed-section-context-open]
Ware, 14th of Third month 1752.

A concern has been upon me to invite you, with my own soul,
to labour in the vineyard of the Lord.
The vineyard of the Lord of hosts, is the heart of man, where he manifests his power,
and displays his almighty operations, for the salvation of his creatures;
and without an admittance thereto, by a divine power,
man is but an intruder into the garden of the Lord,
and all his efforts to labour therein, and to reform his heart and conduct, are vain.

But in that divine visitation, which has been upon our spirits from year to year,
there has been a door opened into the vineyard of the Lord,
and a call extended to labour therein.
And now, my friend, if we did but abide in this divine light,
which shows us our own nothingness and misery,
our understanding would be directed to the vision of Infinite fullness,
and our souls brought to rest under the shadow of the Almighty.

In the midst of interruptions and impediments,
we should experience peace and perseverance;
we should then have cause no longer to be fearful of famine,
or terrified at the alarm of war, because the Lord, who had visited us,
would sustain us with bread, and be our defence in the day of adversity.
Even in the extremity of hunger and thirst,
we should taste of the divine all-sufficiency,
and behold the openings of all the treasuries of Jehovah: and when we were nothing,
and had nothing of our own to live or depend upon, the Lord would be our all.
In this path of deep inward poverty and nothingness
has my spirit been much exercised of late,
even from meeting to meeting, and day to day;
and as I have been made willing thus to remain empty, poor, and naked,
destitute of the sensibility of spiritual enjoyments,
and every consolation not consistent with the Divine will,
I have been favoured with somewhat of the administration of an invisible life,
and a consolation unattainable by the utmost industry and application of man;
and when my soul has seemed in itself as a dry tree, and as a parched land,
I have tasted angels`' food; the Lord has been my pasture,
and my springs in the Most High.

To a joint engagement in the guidance and leadings of this divine life,
would I invite you, my friend, that we may labour together in the garden of the Lord,
and work in his vineyard: then, however concealed we may be from the notice of mortals,
and absent from external aids and assistances,
we shall be ever under the regard of a compassionate Father;
the accomplishment of whose will will be our delight and salvation forever.

In these lines I have not aimed at elegance of style, or point of expression;
as my design was sincerely the unfolding some Christian experiences and desires,
I thought my theme abundantly above such considerations.
Simple and honest as they are,
I request they may be secreted from the observation of any but yourself,
and my friend +++_________+++.

As heretofore,
I would again recommend you to a frequent perusal of the writings of the Old and New
Testament those great records of truth and testimonies to the way of life and salvation.
True love and the apprehension of duty induced me to this freedom.

[.signed-section-closing]
I remain your sincere friend,

[.signed-section-signature]
Samuel Scott
