== Letters LXI &mdash; LXXII

LETTER LXI.

1776+++.+++

Dear Friend,

I Had your letter in answer to mine, which gave me pleasure in various respects.
Your commemoration of the favour and blessings of
heaven dispensed to you in your infant state,
when like Jacob you went from your father`'s house only with your staff,
and now you are become two bands, by the shedding of the blessings on your head,
which as lived under will increase and multiply still to greater degrees of dominion.
Be attentive therefore to the motion of light,
allow yourself to be girded by the holy girdle,
and your back will be strengthened for work,
your standing will be pronounced sure by your stability,
and your head will be covered in the day of battle.
I am not insensible how men are attacked by the grand enemy;
if he fails when he has them in one position,
he attempts to draw them from it by another with a view of better success.
If the banner be over us,
in the limitation assigned by the guardian angel of preservation,
let ns keep under it and we shall be secure;
the enemy will not be able to prevail against us,
when we have the glorious fence of the Lord`'s appointment.
There are seasons when the affectionate part is up in men,
and they propose things agreeable to nature in ourselves,
that we are ready to comply with; this makes the way intricate to ourselves,
for when we bring it to the standard it is deficient in weight and purity,
and will not pass the trial before the judge.
I have missed it in this respect, and therefore drop the caution to my friend,
to beware of giving expectation, before it is tried in the balance of the sanctuary.
King`'s children should always preserve their dignity,
by taking heed how they mix amongst the people,
and their associations and alliances ought to be with the royal lineage;
in this the King of kings is honoured, and our own dignity preserved;
I do not mean this with regard to your present undertaking in England,
I mean with respect to others whom we converse with, and are sometimes amongst,
both male and female, though it may hold good in both.

There are many more talkers of the truth than walkers in it, whose mouths flatter,
and whose tongues are their own and ought to be stopped,
though they appear to be something in word and show when they come
in their ranks and appear amongst the disciplined army;
they are not noticed nor sent forth against the Goliaths of the day;
it is only those who are anointed and appointed,
armed and accoutred that can face the battle.
May we, dear friend, dwell with the consuming virtue of the word, that as we are used,
we may still be refined.

I would just say with regard to the present depending affair, do not be too precipitate;
weigh it, and remember that he that believes makes not haste;
there are many things to be looked at, your place, your friend`'s place.
Things with a fair face of prospect may be shaded with a gloom;
sweet things in enjoyment may change to bitter; I would not cast anything out,
to embarrass, or overwhelm, but simply speak my feelings; relinquishing for the cause,
in our affections, enriches after in a spiritual and temporal sense,
and it is often tenfold restored.
It was said in the recapitulation of the many blessings dispensed to David,
after showing him what he was,
"`and if this had not been enough I would have done much more.`"
This was when he was taken off his watch,
and allowed his affections to sport with a beauteous object,
which in the end made him flee before his enemy;
this you may think not similar to your present state: but yet it points the obedience,
the dedication that ought to attend a being raised
to eminence by the interposition of a supreme Power,
in order to show forth his power in him.

The satisfaction resulting from your letter on this subject was great,
because with respect to a removal, in looking at it I think you tell me,
you never saw light shine upon it.
This satisfaction arises from my being of the same sentiment, and one in judgment,
when most capable to judge and feel for myself, and for my friend.
Let this affair be hewn and squared in the mount before it is adopted,
and let there be no sound of an artificial tool in bringing it about,
that the substituting a member from one part of the body to another,
may be the Lord`'s work, and then it will be useful,
and to the edification and comfort of the body, the church.
I sympathize with you and your friend, I love you both in the truth, and my desire is,
that you may be conducted in wisdom in bringing it forward,
or in finally letting it drop,
and for every sacrifice thus made it will be amply made up,
by the replacing one in its stead in which your acceptance will stand,
your faith be confirmed, and your righteousness be proved, as was faithful Abraham`'s.

I am now, my dear friend, on the eve of my departure;
I stole this little season from hurry to converse with you, and tell you how I felt.
My things are all gone aboard, and on the morrow I expect to embark.
A letter from John Oxley informed his brother was
expected to get clear of the land about the 5th instant,
by a letter received, so that we may have some expectation to meet, if at all,
soon in the western world.
A correspondence with you will be agreeable, as a little intelligence in a strange land,
is very pleasing to pilgrims.
I should have been pleased to have heard what you intend,
and how you feel with respect to going over the water soon.
Keep your integrity, and put your self in the hands of a faithful Creator,
that sleeps not by day, nor slumbers by night.
Consider yourself at his disposal, not man`'s of any kind, neither R. D.`'s,
nor any other man`'s that is but flesh, and consequently frail.
Farewell, may wisdom and knowledge be the stability of your time while on earth,
and may the fear of the Lord prove your glory, in which desire:
joined by my wife in near love and affection, I remain your truly loving friend,

Samuel Neale.

LETTER LXII.

From Doctor Fothergill to the Meeting for Sufferings.

Near Middlewick, Cheshire, 20th 8th month 1770.

Dear Friends,

As you are frequently in my thoughts when absent from you,
an inclination seemed to arise in my mind,
just to express the cordial regard I feel for you, both as a body, and as individuals;
often have I been filled with thankfulness that my lot has been cast amongst you;
much benefit have I received from the wisdom that
has been manifested in the conduct of your affairs;
and I often consider you as an assembly of the most favoured people in the whole city,
may I not say in the whole society.
It seldom escapes me, when I sit down with you,
fervently to desire that we may always when we meet feel a degree of that solemn awe,
which I am sure is often felt among us,
and that none may go away without being the better for their meeting:
and I esteem it a signal mercy that in the midst of so many unavoidable engagements,
and in the increase of which I think my heart has no delight,
a desire is kept alive to be united nearer if possible to every tender mind amongst you,
to profit by their example,
and to be divested of every thing that might not contribute to the help of individuals,
or advantage to the whole.
May I just say,
that I fervently wish an awful reverence may clothe
every mind when you are collected together;
the more closely and steadily we can unite here,
the better we shall be enabled to judge properly, and act wisely,
concerning the things that are brought before us.

It is not in my thoughts to esteem myself proper
to give advice to such a body of sensible friends,
whom I honour in the truth;
but it seemed pleasingly to arise in my mind to testify
my brotherly remembrance by these few lines,
and to be a kind of prompter, though at a distance,
to consider your importance in regard to the well-being of the society,
as instruments in the hand of Providence for much good;
and to consider what frame of mind such meetings should be held in.
I know from experience that many of you come together with such dispositions,
and that I may do so likewise, and that others who may even be behind me,
may come up in the same earnest endeavour to be what they should be, is now,
and often has been, my desire.

It is not boastingly, but with a degree of humble gratitude that I can mention,
though absent from you, my heart is with you often.
This favourable recess is not granted, that it may be spent in dissipation or indolence:
wish to renew my strength both of body and mind,
and to seek after that which can renew it properly.
I salute you in much affection, and am,

Your friend and brother,

John Fothergill.

LETTER LXIII.

It is worthy of consideration that when our society was under sore and cruel persecution,
it greatly flourished both as to number and the addition of excellent men:
for notwithstanding their sufferings were great,
the best of them were enabled patiently to bear them,
although they sometimes suffered the loss of all things;
but the worst who could not suffer for the truth were swept away,
and thereby the society was so refined,
that all impartial sensible men who observed the lives of our forefathers,
and impartially examined their principles, began more or less to lean towards them,
and many of the best of other societies joined them.
But persecution has in a great measure ceased, and we are become drossy.
What is to refine us now?
If we refine, or are refined, we shall certainly grow again.
These I take to be truths substantially founded; therefore I say again,
what is to refine us as a people considered in connection with each other,
as a community?
Nothing now surely but our excellent discipline, administered by men of truth,
men fearing God, hating covetousness; men gifted,
fitted and qualified by the head of the church for the service thereof;
men of clean hands and upright hearts, whose concern it is to keep the church clean,
well knowing her prosperity depends on her purity,
and that her holy head will never enlarge a church but in the way of righteousness,
and by a real reformation.
Now nothing is more manifest than this,
that our forefathers separated from the established
religion of this country on a ground of reformation,
and we both believe that a separation on any other ground is not justifiable:
but on this principle and bottom quite commendable.
Now it seems reasonable to suppose a society so founded,
and often recurring to its foundation,
must be the best and most disinterested in the world,
and low as our society is fallen for lack of such recurring,
yet I know of none in which we can see so much devotion of time and talents,
and-generous labour to social service, as in ours.
The present visit to the monthly and quarterly meetings
of Friends in this nation and in Ireland,
is a fresh instance of this sort,
which I hope will be performed by such as have not only
a strong affection rightly founded for the society,
but who have also well considered, that as a people,
according to the words of our Saviour,
we are "`as a city set on a hill:`" i. e. as I understand it,
made most obvious by our singularities,
and therefore we ought to take good heed to the reasonable command that follows;
to let our light so shine before men, that they seeing our good works,
may glorify the Father which is in heaven.
Doubtless,
the best part of the society have well retained and considered this excellent precept,
and have had great care to adorn the doctrine preached
among us by a suitable life and conduct;
and I am fully persuaded,
had we all been as careful in this respect as we ought to have been,
where there is one now under our name there would have been hundreds, if not thousands;
but instead of the ignorance of foolish men being put to silence, by our well-doing,
of which the apostle says, "`for so is the will of God;`" their mouths have,
by our evil doings, been opened, not only to reproach us,
but to speak evil of the truth professed by us.

It is justly to be feared that many seeking souls, under divine visitations,
inclining to us, have been stumbled by our stumbling blocks.
These are sorrowful things, and what is to be done?
Surely the camp must be searched, or to speak in more familiar language,
a stricter hand must be kept on scandalous reproachful things;
things which are a shame to any people, but abominable in us,
more especially where the phylacteries are broad, the appearance plain,
the garb and heart at variance.

You have, doubtless, looked on virtue and vice as great things, and considered families,
societies, and nations as happy or miserable, sooner or later,
in proportion as one or the other prevails; and if so,
what has this empire to expect but desolation, confusion, and distress,
because wickedness abounds, of which I fear there is too much among us,
the love of many waxing cold in the cause of virtue, truth, and righteousness.

In short, nothing is plainer than this, that a general reformation is needed,
and nothing ought to be more earnestly sought for
by us than that we as a people may lead the way,
remembering where judgment must begin,
and Were the unrighteous things purged from us by our discipline,
I have no doubt but we should flourish again.
The principle we profess is still the same,
and would make us as illustrious as were our fathers,
if we attended to it in the same manner they did, and as readily obeyed it.
Their hope of glory was rationally founded on their belief,
that their Saviour made himself manifest within.
This was what they were convinced of, to him they retired,
and became an inward and spiritually minded people;
and this enabled them to bring forth the excellent
fruits of the spirit enumerated by the apostle,
in which they excelled all others who were not so turned.
Their peculiar exhortation, as I may term it, was, Turn your mind inward.
They themselves had found the benefit of so doing,
and being in their ministry under the constraint of divine love to the souls of men,
they were desirous that others might reap the same advantage.
And indeed this is so much the one thing needful,
that no man can be substantial in religion without it; without it,
'tis an everlasting truth, he will be either no Christian, or a poor superficial one,
perhaps washing the outside of the cup and the platter,
but neglecting the most essential cleansing of the inside.
It was turning inward turned me from deism to Christianity;
and for the truth of Christianity I have found there are evidences enough within,
evidences sufficient to convince any honest enquiring rational soul,
who will turn inward and compare the spiritual things made manifest within,
with the spiritual things written without in the Holy Scriptures.
And surely there cannot be a better or fairer way of dealing
with unbelievers than referring them to their own feelings,
that is, to what they have felt and what they may feel in their own bosoms.
This is surely the rational way to conviction, and introductory to that of conversion,
which no wise man will be content without experiencing,
and which the wiser we are the more we desire.
Our merciful and kind Creator has wifely and impartially
linked our duty and our interest together,
and doubtless has unalterably determined,
that the one shall forever bear a proportion to the other.
One is a proof of his kindness, the other of his justice,
which shows he is fit to be as he is "`the judge of all the earth,`"
determined to reward every man according to his works;
now if these things are so,
what enemies are we to ourselves when we do anything that is evil,
and how untrue to our interest when we omit doing
that good for which we might be forever rewarded.
This shows how wise we are for ourselves, and how beneficent to others when well employed.

I am well assured that he who is the head of the church is not unmindful of it,
but very tender of its welfare,
and still ready to bless us with gifts and qualifications necessary to this good end.
But this is proper to be remembered, that all who are qualified are humble men,
men who have been humbled under the mighty hand of God,
for there are none but such truly humble.
They that are, as the beloved disciple expresses it,
"`passed from death unto life,`" and that way are become lovers of their brethren,
are humble men.
To these condescending to others is not so hard as it is to other men,
who still remain unmortified, unsanctified;
the last are not fit for the service of the church of Christ,
nor are any fit for it but such as are endowed with that wisdom which is from above,
because that only makes first pure, then peaceable, gentle, and easy to be entreated,
full of mercy, and full of good fruits, without partiality and without hypocrisy;
that this wisdom may be often asked for,
and liberally given to my friends in +++________+++ is my sincere desire.

T+++.+++ F.

LETTER LXIV.

l1h month 7th, 1800.

Esteemed Friend,

The ingenious manner in which I found the hints I lately ventured to give you were received,
induces me to throw before you some thoughts which have at times
struck me respecting the dangers that await ministers in our society,
more especially the young, and shall I add, those of your sex.
I think it possible, at least,
in the first place that an honest and grateful desire to bear testimony
to the Lord`'s goodness in his tender and fatherly dealings with
his poor children in this state of probation,
may carry some forward into an office unto which,
in its more solemn and important services, they were never called or qualified;
and this is more peculiarly likely,
when a fresh sense of mercies received may raise this language in the soul,
"`what shall I render unto the Lord for all his benefits?
Surely I will take the cup of salvation, graciously handed me,
and call upon the name of the Lord.`"
Having thus stepped forward on motives of gratitude and obedience;
the fear of looking back after putting our hand to the plough,
may rather tend to push forward, while tenderness in the minds of some friends,
and lack of judgment in others, may have precluded all plain dealing,
and the wholesome advice of true eldership.
Thus, where only a little incense from "`the fields of offering,`"
when the dews of Hermon have refreshed the breathing plants,
might be looked for, the works of an apostle may be attempted, and the result is evident.
The sacred cause is not promoted, no worse, it is injured,
and those who love it above all things, are wounded:
wounded too in the house of their friends, where wounds are most deeply felt.
To those also who may have been rightly called,
there is great need of suspecting the possibility of deception,
especially if of sanguine temperament,
and the mind apt to take lofty excursions in the dangerous regions of imagination.
There is a judicious remark of some unknown writer on this head, of which I took a copy,
and it is at your service-- "`There is no faculty of the
soul more exposed to the attacks of our ever active enemy,
at least more liable to be injured by them than the imagination;
its nature is so restless and ungovernable,
that the utmost vigilance of a well regulated mind,
and the assiduous use of all the weapons of our warfare,
are scarcely sufficient for keeping it in that degree of subordination,
which is necessary for repelling the enemy`'s assaults.
And when, in addition to this disadvantage, the mind is much unfurnished with knowledge,
the judgment weak, and the temper sanguine,
it is no wonder that the father of lies should rule in the imagination.`"
But by all this I am not desiring to discourage what is right,
and am fully persuaded that there is a way yet cast up, wherein the wayfaring man,
though a fool to the wisdom of this world, shall not err; and that if the eye be single,
and the heart attentive to the simple path of duty,
the whole body will be filled with light sufficient for the duties required.
What I wish to enforce is, that in teachers, as fully (if not more so) as in hearers,
great watchfulness, care, and fear, with great simplicity of soul, are required;
and let me add, all obscure expressions and allusions to scripture passages,
familiar chiefly to religious people, should be avoided when addressing others,
or even a mixed multitude.

I have feared that many have heard scripture doctrines
so expressed as not to know it was such,
but apprehended it was some peculiar notions of our own.
It were better in such cases to refer to the sacred writer, whether prophet or apostle;
to say we do not know which to refer to,
savours of idleness in those who minister at the altar,
and who may reasonably be expected to know how to
handle the tools appointed for their use,
and to execute the business before them as those that must give an account.
With nothing but good-will to the best and most glorious cause do I thus write:
I hope you will not misconceive me,
for truly do I desire that Zion`'s light may go forth as brightness,
and her salvation as a lamp that burns;
that the beneficial light thus handed to the weary traveller,
may lead him safely on his journey, and to the city of the great king.

I am your real Friend,

R+++.+++ G.

LETTER LXV.

Brentford, 6th month 11th, 1770.

Dear Friend,

My earnest desire for your welfare will hardly allow me to rest,
because of your imminent danger.
I consider you as one mercifully favoured with another divine visitation:
that you may reap the advantage of it is my concern,
but that you are in the way to lose it is my greatest fear;
as I purpose to satisfy your mind the right way, and not offend you,
I shall endeavour to give you sufficient reasons why I thus write.
When it pleases God in his great mercy first to favour our minds in a particular manner,
it is expected, and justly, because really necessary,
that our minds should be steadily and strongly turned
to that good with which we are so visited:
consequently turned inwards, much inwards, and again as much from all other things,
not only from things without, which as it were press upon or into our notice,
but also from the workings of our own mind about
such things as may be naturally agreeable to us,
from the cast or natural turn of our minds, or the present state we may be in.
Now as we have been thus graciously regarded by the best of all beings,
to bring us to embrace that which is undeniably good, and to redeem us from all evil,
in order to our happiness, so we have a dreadful enemy who is ever endeavouring our ruin,
by drawing our minds from good and so into evil; of this evil spirit we have, I presume,
had proper notice in holy writ.
Now as this apollyon or destroyer is not allowed
in our present probationary state to act by force,
his way of working our destruction is by subtlety.
Of this we have had forewarning in the account given us
of his deceiving her who was the mother of all living;
and his subtlety is so great, that John in the Revelation tells us,
"`He deceived the whole world.`"

Has my friend thought enough of these things as warnings to us?
I say as warnings to us.
Is my friend brought to be enough on his guard against this mighty enemy of ours?
An adversary who, when poor man in his fallen state is visited,
that he might obtain a higher and happier station,
is ever endeavouring to keep him down in sin and misery,
and from rising into the redeemed state.
And when by joining in with divine visitations,
men are raised and stationed to be as the stars of heaven,
(but not fixed ones) how alarming is our enemy described,
and represented to us as a great red dragon, having seven heads and ten horns,
and seven crowns upon his heads, and as drawing such down from heaven,
and casting them to the earth again, and this by his tail,
when perhaps he was thought gone by, by such.
He may make it his business to busy us about the final lot of men,
in the matter hinted in the last page of the pamphlet you desired my opinion of:
and this certainly suits his purpose better than our attending
to that power that would bruise his head,
and bring him shortly under our feet.
I am sure my friend will allow me to ask a few questions; and first,
What good can it do to weaken the awful sanctions of religion?
In the second place, who, besides this deceiver,
will undertake to remove the great gulf which God has so fixed,
that there is no passing from state to state? Luke 16:26.


"`I pray you therefore, Father, that you would send him to my father`'s house,
for I have five brethren, that he may testify unto them,
lest they also come into this place of torment.`"
Verse 27 and 28. Upon which I observe this last request on behalf of his brethren,
seems manifestly grounded on all hopes for himself being cut off;
and if his request had been granted,
I am persuaded that the fixedness of this great gulf would not have been forgotten,
but have been testified of to his brethren.

"`You shall not be punished eternally for your sins`" here:
"`You shall not surely die,`" manifestly was and is designed
to lessen our dread of breaking the divine command,
and therefore by whom we may easily judge.
As I believe the scriptures that say, "`No man knowes the Father but the Son,
and he to whom the Son reveales him,`" you will I trust approve
my preferring the knowledge of God through Jesus Christ,
before any ideas that I can merely as a man form of him.
I have thought sometimes that the perfect purity of the divine Being,
and his knowing "`who are his,`" is our security
in point of happiness on observance of his law:
and on this bottom it is,
that the righteous have reason to "`rejoice at the remembrance of his holiness.`"
Take away the holiness of the divine Being, and all our security for happiness is lost:
for upon that supposition, he might say one thing to us, and do another by us.
We must then in the first place, for our own security,
establish the perfect purity of the divine Being;
and must not his love of that which is good, and hatred of that which is evil,
infinitely exceed ours?
Shall we then measure his rewards and punishments by our little love of good, and I fear,
greatly fear, too little hatred of evil,
and especially of that evil to which we may be most inclined;
and here I cannot but endeavour to lay open the old and still grand deceiver.
I have often thought men magnify the mercy of God in the wrong place,
(if I may so express myself) for can anything be a plainer snare of the enemy of man
than to set him to magnify the mercy of God in some future portion of eternity.
Thinking of his mercy to be extended then, naturally lessens our fear now;
and this is obtaining a point the enemy has ever aimed at,
and how much and how often he works this way, few men have well considered.

But there is mercy with the Lord now, that he may be feared, that is,
he still has mercy on us, that we may learn to fear him.
Thinking of his mercy now, is good, because it has a good effect upon us;
when the serpent began to tempt Eve,
it is observable his first attempt was to lessen
her fear of breaking the command of God to her.
As I am principally concerned to put you very strictly
on your guard against your enemy and mine,
I must say he will, I know he will,
use every infernal endeavour to keep you from a close attention
of soul to the quickening spirit which has visited us,
to redeem and quicken out of the fall; mind, my beloved friend, oh, mind, I beseech you,
this quickening redeeming spirit.
I am sure, (though in common I do not love to be positive) yet, in this point,
I must say I am sure your everlasting happiness depends upon it;
and this your adversary knows, and will, if possible, prevent,
by drawing away your attention from the Lord`'s good spirit,
which you have at times felt, and known also what he has appeared inwardly for.

Now in the course of what I have had to say to my friend,
being brought to speak of the quickening spirit, if I am not greatly mistaken,
here we are brought to the very foundation of religion, in point of experience; for,
according to the best authority, "`the spirit of truth is to be our guide,
into all truth;`" and as I am fully convinced in my own mind,
that religion cannot be understood but by experience,
so it seems proper for all who read of the spirit of truth in the holy scriptures,
rightly to consider what they do feel or experience in their own
hearts of those operations of the holy spirit described therein.
I must not stay now to enumerate these descriptions; but say here every man is,
in the first place,
referred to his own feelings of the principle we
profess--then reason comes in its proper place,
and loudly and strongly pronounces,
as surely as the mind of man is favoured with so excellent a principle,
"`it must be minded, it must be kept to,
it must in religious things be preferred to every thing.`"
And he that is firmly brought to believe in this divine principle of truth,
and properly to regard it,
is brought to practise what long ago was a truth delivered to the world,
"`He that believes makes not haste;`" and I may add,
but waits for his guide in whom he has believed,
being properly apprehensive of the danger of going without him.
This keeps a man much at home, and to the great business of inward deep experience,
and makes him cautious, exceedingly cautious, of rambling abroad into speculations,
where there are labyrinths, which must perplex,
and in which it is easy for the human mind, without the divine guide, to be lost,
utterly lost.

T+++.+++ F.

LETTER LXVI.

Warrington, 20th 1st. month 1752.

Dear Friend,

I Doubt not but the same conveyance that brings this
will bring some account of your dear and worthy father,
whom I saw at Liverpool on his way to Ireland, a few weeks ago, in pretty good health,
and alive and cheerful in his labour in which he has been closely concerned,
and I hope to good service in various respects; doubtless to his own great peace,
and uniting him in heart to the faithful.

In the freedom we had to each other,
he imparted to me one or two of your affectionate letters to him,
which seemed to breathe strongly of the language of tender affection to him,
and an awful regard to the heavenly Father;
and has been the means of your being often in my very near remembrance,
and some desire attended,
to send you the salutation of true love in Christ Jesus our holy Head,
in whom stands the fellowship of the family the world over.
Great has been your advantage, dear friend, in being descended from worthy parents, who,
by example and precept, have sought your nurture and growth in the things of God;
the visitation of heavenly light and life has also been extended,
and I hope in a great and good degree embraced, and has pointed out the means of help,
or the terms of happiness, and inclined your heart to seek it.

Many are the besetments and probations of a mind
awakened to seek an inheritance among the blessed,
and of various kinds they are; but the mighty arm is revealed and made bare,
for all those that refuse to be comforted without it.
Many are the low places the righteous tread,
and in the line of their experience deep answers deep;
some are brought upon us through our inadvertency and negligence;
let us then enquire the cause and remove it;
sometimes the heavens are made like brass to us, to teach us how to be in want,
and like winter seasons, to strengthen our roots, that we grow not top heavy,
but in all things our heavenly Father deals with us tenderly, and for our good.

Let therefore your attention be steady to him for counsel and guidance,
and he will not forsake you in the time of your secret bewailings,
but spread a table for you in the desert.
Oh! that our youth might thus awfully bow under the operation of the Lord`'s hand,
that their minds might be subject to him whose we are,
and whom we ought to serve in the spirit of our minds.
I feel in my mind the sympathy of the blessed covenant,
and the spreading of the Father`'s wing theewards,
and crave of the Almighty one to have you in his keeping,
and of you never to forfeit it by any means.
He is all sufficient to abide with you continually.
He is often with his people when they perceive it not: he dwells in thick darkness often,
and was as certainly the mighty help of Israel,
when they groaned in anguish in the land of Egypt,
as when the glory of the Lord filled the temple at the feast of dedication.
I commend you to him, seek him diligently, serve him honestly,
and follow on to know his requirings, with full purpose of heart to be faithful thereto;
and no weapon formed against you will prosper,
nor any place be allotted so low in which the omnipotent arm will not sustain.

My dear love attends your mother and yourself, though personally unknown.
I salute you with gospel affection; and remain,

Your faithful friend,

Samuel Fothergill.

LETTER LXVII.

Shipton, 1762.

Dear Cousin,

It is now several years since the correspondence between you and me was dropped,
but notwithstanding that, I have often thought of you, particularly of late;
I think few days have gone over my head, but I have had you in remembrance;
many and various are the scenes I have passed through since I wrote last to you;
and though I am but young in years, I have met with a great deal of trouble,
part of which I confess is of my own bringing on,
a consideration tending rather to aggravate than alleviate them.
I have been near six years married to a young man with whom
I contracted an acquaintance when I was but a girl;
but knowing how disagreeable the match would be to my father,
I dared not consent to it in his life-time, but engaged myself to marry him,
if I survived my father, who was suddenly removed from us by death;
soon after the affair got out, and reached the knowledge of Friends,
who took unwearied pains to prevent it; and laboured with me in much love to desist,
and refrain his company, but all to no purpose.
I cannot express, though I believe I shall never forget the conflicts I had,
between known duty and a foolish inclination; the last prevailed,
and I fled from the faces of my best friends (I thought them so
even then) to rid myself of their kind well-meant importunities.
I was greatly dissatisfied with the step I took even at the time I was taking it,
and after my marriage, was for three years in a kind of gloomy lethargic disposition,
though I regretted my unhappy state, and the cause of it;
but afterwards growing more and more uneasy under it,
I became desirous of making public confession of my error,
and begged to be reconciled to my friends,
for whom I had all along entertained a loving regard;
accordingly I wrote a paper in much sincerity of heart,
and I hope some degree of repentance, to the monthly meeting,
desiring and hoping it might have been accepted without my personal appearance;
but friends thinking that necessary,
two months after the monthly meeting I had notice of it given me,
and that Friends expected me there.
I went into the mens`' meeting, I may truly say, in much awe, fear, and trembling;
the paper being read, questions agreeable and necessary to the occasion were asked me,
by which I was too much affected to return any other
but broken and almost unintelligible answers.
Friends compassioned my case, and in much love and charity granted my petition,
since which time I have been favoured with their tender care, regard, and notice;
and though I cannot get to meetings so often as I could wish,
yet my husband has no aversion to friends, but is not willing I should go,
when I am likely to be needed at home,
which on week-days especially is frequently the case, as we keep a little shop,
and my husband often works at his trade;
and notwithstanding my heart in some respects is more at ease than before,
yet I have still many difficulties to encounter.
I have three children living, the eldest a fine girl,
who was taken from us before she could go alone,
and has continued ever since at my husband`'s mother`'s,
who was unwilling to part with the child,
and the poor little creature is already often distressed
to know how to behave between us.
She would go to meeting with me, and use the plain language, but tells me,
dares not for fear of offending her grandmother, of whom the child is very fond.
I long to have her at home,
but my husband will not so much as allow me to hint my desire to his mother; yet I hope,
if I live, to gain that point.
My little boy and girl at home, if I do not live to see them brought up,
or probably if I do, may fall into improper hands, and under the tuition of people,
who for lack of a proper care over them, may expose them to temptations and difficulties,
which they might have been exempt from, had mine been a more prudent choice.

And now dear cousin, I have in some degree informed you how things have been with me,
though I am pretty much a stranger to the particulars of your situation.
I heard some time ago, that you enjoyed but poor health,
and was under great depression of spirits, a state I have been little tried with,
though many who have not been so faulty as I have,
many good and worthy people have known it; I believe it is a painful trying time,
and though Providence is all-sufficient, yet the company and regard of good friends,
may be of great service,
the means of pouring the balm of comfort and consolation into an afflicted humbled heart.
It is far from my design to give any offence, or take upon me to advise,
knowing myself a very improper person so to do,
neither do I value myself upon my own recommendation with Friends:
every time I think of it, though it is a comfort to me,
it rather serves to humble than exalt me, in my own opinion.
I shall be very glad of a line or two from you when it is convenient,
and should be pleased if you would write to me with
the same freedom and confidence I have used to you,
and should rejoice to hear you were perfectly reconciled
and reunited to your friends and parents,
and that your worthy father and mother might yet live to have comfort in you,
and you in them.
My good wishes attend your husband and children.

From your affectionate kinswoman,

Elizabeth Dale.

LETTER LXVIII.

Richard Shackleton to E. D.

Ballitore, 10th month 1762.

Dear Cousin,

I Perused your letter to my sister Rayton, and a secret sympathy,
strengthened by the affection of natural relation,
induces me to commence a correspondence with you.
I have lamented, dear cousin, that a person blest with a good natural understanding,
improved by a good education, descended from religious ancestors,
who were honoured with bearing a testimony to, and suffering for the cause of truth;
and who was doubtless as it were by birthright,
made sensible of the essence of true religion: I say,
I have lamented that such a one as you should,
through the subtlety of the serpent that beguiled Eve,
have been instrumental through the strong influence of your example,
to lay waste our Christian testimony relative to mixed marriages;
and which is a consideration still more grievous, long observation has proved this truth,
that few who have been overtaken in this great fault,
though favoured with the gift of sincere repentance, and it is hoped,
accepted in themselves, have ever after been of much service in the Society.

They have walked mournfully on their way,
through a path of inward and outward affliction,
and have been made as living monuments for others to take warning at, and beware;
thus you know, I believe, dear cousin, it has been with many,
and the opinion I have of your good sense makes me not fear
to give offence by this plain manner of writing,
at the same time that my sincere regard for your welfare and happy restoration,
makes me willing to drop any hint, which improved by your own reflection,
etc. may contribute in any little degree to that desirable end: but neither, dear cousin,
would I discourage you in the least from that good
resolution which you seem to have happily taken up,
of returning like the prodigal son to the Father`'s house.

I mention the evil of your transgression,
not because I believe you insensible of it yourself,
nor that I would increase the affliction of the afflicted, and add grief to your sorrow;
but as this offence has long appeared to me, to be of a grievous and complicated nature,
a stain, though not of the deepest dye, as some gross pollutions,
yet not easily worn out, you may with more humble prostration,
with more deep contrition of spirit, and with more steady attention of mind seek to him,
whose law you have transgressed, and taught others so to do, by the most cogent precept,
your own example.
And if this, dear cousin, be your constant, uniform, inward travail, and exercise,
to witness from day to day this baptism which alone can wash and make clean,
though your transgression has been of a nature which I think
I have repeatedly felt to be displeasing to the Almighty,
yet I hope by this means not only as you very sensibly writes,
you may be outwardly reinstated in the union of Our society, but will in his time,
perhaps in the deeps of trouble, witness that secret union and reconciliation with him,
which will be your present support to bear up your drooping head,
and be the joyful earnest and assurance of a rest in that kingdom where the evil one,
and his agents, cease from troubling, which in sincere affection is my desire for you.

Our family`'s love, etc.

Richard Shackleton.

LETTER LXIX.

E+++.+++ D. in answer to the foregoing.

Shipton, 2nd month 1763.

Dear Cousin,

Your very acceptable letter came safe to hand.
I cannot fully express how much I think myself obliged
to you for your tender regard to a poor creature,
sunk in my own opinion below your notice;
it was obliging condescension in you to propose commencing a correspondence with me,
and will always be gratefully remembered.
Sorry indeed should I have been,
if you had entertained a thought that I should have
been displeased with any part of your letter;
those parts which strike most home to the course of my thoughts,
I mean my own misconduct, were not unwelcome,
and by painful experience can I witness to the truth of your just remarks.
To walk in a path of inward, as well as outward affliction, has long been my lot,
nor have I any expectation of much alteration for the better in this life,
bereft at times, even of the flatterer, hope;
my inward situation is perfectly unknown to any person;
I am obliged to appear serene when my poor heart is torn with conflicting passions;
I have not a sufficient foundation to support myself under my daily trials,
and my attention is too much taken up, and engrossed with the cares of the world.
I seldom go to meeting, my husband being unwilling any business, though ever so trivial,
should be neglected on that account.
I have involved my poor children too in many troubles and perplexities;
may the Lord have mercy and compassion on them, who are innocent of my transgression,
and direct their feet in the right path, that I have missed and turned aside from,
which has cost me my peace of mind.
You are a father of children, daughters too;
it is my sincere desire they may be preserved from falling into like errors,
and take warning by me,
who have not had I believe one hour`'s solid satisfaction since I married.
I once thought no person on earth capable of drawing me so far aside;
secure and confident in my own imaginary strength,
I dared at first to dally with the temptation, and was convinced, by sad experience,
that the most trifling digression from our known duty,
is a very great advance to the contrary; I take notice of your observation,
that few who have been guilty of my error, are ever after of much service to the Society.
It is not likely they should, the very nature of the offence,
and consequence attending it, exclude from a moral possibility of it:
and what right have we to expect miracles to be wrought
in favour of the disobedient who have knowingly acted so,
and have neither ignorance nor a negligent education to plead for excuse.

Dear cousin, in perusing what I have written,
I cannot but think it may appear a little particular,
that I should use such freedom in my first letter to a person I have never seen;
but I am encouraged,
and as it were called upon to an almost unlimited frankness by yours,
which shows you to be a sincerely well-wishing and sympathizing friend,
and in some measure sensible of my condition.
Permit me to request the continuance of your tender regard for me.
My husband, children, and self, are mercifully favoured with good health,
though it is a sickly time here with many.
William Longman, of Leeds, died lately, his death was in last week`'s paper,
which was the first account we had of it.
My dear love attends you, your wife, and children, from

Your affectionate kinswoman,

Elizabeth Dale.

LETTER LXX.

Dear Friend,

My dear and tender love salutes you, in that love from which I had my being,
and from which sprang all my Father`'s children, who are born from above,
heirs of an everlasting inheritance.
Oh! how sweet and pleasant are the pastures which
my Father causes all his sheep to feed in;
there is variety of plenty in his pastures, milk for babes,
and strong meat for them of riper age, and wine to refresh those that are ready to faint,
even the wine of the kingdom, that makes glad the heart, when it is ready to faint,
by reason of the infirmities.
Sure I am, none can be so weary, but he takes care of them; nor none so nigh fainting,
but he puts his arm under their heads;
nor none can be so beset with enemies on every side, but he will arise and scatter;
nor none so heavy laden and big with young, but he takes notice of them,
and gently leads them, and will not leave them behind unto the merciless wolf,
because they are his own, and his life is the price of their redemption,
and his blood of their ransom; and if they be so young that they cannot go,
he carries them in his arms; and when they can feel nothing stirring after him,
his bowels yearn after them; so tender is this good shepherd after his flock.
I can tell, for I was as one that once went astray,
and wandered upon the barren mountains; and when I had wearied myself with wandering,
I went into the wilderness, and there I was torn as with briars,
and pricked as with thorns, sometimes thinking this was the way,
and sometimes concluding that was the way,
and by and by concluding all was out of the way; and then bitter mourning came upon me,
and weeping for lack of the interpreter; for when I sought to know what was the matter,
and where I was, it was too hard for me.
Then I thought I would venture on some way where it was most likely to find a lost God,
and I would pray with them that prayed, and fast with them that fasted,
and mourn with them that mourned, if by any means I might come to rest, but found it not,
until I came to see the candle lighted in my own house,
and my heart swept from those thoughts and imaginations, and willings, and runnings,
and to die unto them all, not heeding of them, but watching against them,
lest I should let my mind go a whoring after them.
And here I dwelt for a time as in a desolate land uninhabited,
where I sat alone as a sparrow upon the house-top,
and was hunted up and down like a partridge upon the mountains, and could rest nowhere,
but some lust or thought or other followed me at the heels,
and disquieted me night and day, until I came to know him in whom was rest,
and no occasion of stumbling, in whom the devil has no part,
and he became unto me as a hiding-place from the storms, and from the tempests.
Then came my eyes to see my Saviour, and my sorrow fled away,
and he became made unto me all in all, my wisdom, my righteousness,
and my sanctification; in whom I was and am complete,
to the praise of the riches of his grace and goodness, that endures forever.

Therefore be not discouraged, O you tossed as with tempests! nor dismayed in yourself;
because you see such mighty hosts of enemies rising up against you,
and besetting you on every side: for none was so beset and tried, and tempted,
as the true seed was, who was a man of sorrows, and acquainted with grief.
But be still in your mind, and let the billows pass over, and wave upon wave;
and fret not yourself because of them, neither be cast down,
as if it should never be otherwise with you; sorrow comes at night,
but joy in the morning: and the days of your mourning shall be over,
and the accuser will God cast out forever.
For therefore was I afflict ed, and not comforted, and tempted, and tried, for this end,
that I might know how to speak a word in due season,
unto those who are tempted and afflicted as I once was;
as it was said unto me in that day when sorrow lay heavy upon me.

Therefore be not disconsolate,
neither give heed unto the reasonings and disputings of your own heart;
nor the fears that rise therefrom, but be strong in the faith,
believing in the light which lets you see them,
and his grace you will know to be sufficient for you,
and his strength to be made perfect in your weakness.
And so will you rather glory in your infirmities, that his power may rest upon you,
than in your earnest desires to be rid of them;
for by these things you will come to live in the life of God, and joy in God,
and glory in tribulation, when you have learned in all conditions to be contented:
and through trials, and deep exercises, is the way to learn this lesson.
These things in dear love to you I have written,
being somewhat sensible of your condition, and the many snares you are daily liable unto;
therefore watch that you fall not into temptation,
and my God and Father keep you in the arms of eternal love, over all, unto the end,
unto his praise.
Amen.

John Crooke.

LETTER LXXI.

Samuel Fothergill to the Monthly Meeting he belonged to.

Dear Friends,

It has for some time lain heavy upon me to write a few lines to you,
upon the following account.
The Lord in his everlasting kindness (that long strove with my soul) has
been pleased to unstop my deaf ears that I might hear him,
the Shepherd of his flock,
and to open my blind eyes and let me see my state as it really was,
very desperate and lamentable.
He has shown me the dreadful precipice I was on the brink of,
and has breathed into me the breath of life,
in order that I might arise from the dead and live;
he has set my sins in order before me, and shown how far I had estranged myself from him,
and raised strong desires in me to return to him, the Redeemer of my soul.
The consideration of his kindness has raised in my
soul a just abhorrence of my former practices,
which induces me to make this public declaration of them in a few words;
I know my sins are so many and obvious that it is impossible
and needless to recount and remark upon them,
for I was then in the bond of iniquity,
though it has pleased the Father of mercies to bring
me since into the very gall of bitterness,
and into anxiety of soul inexpressible, yes,
not to be apprehended by any but those who have trod the same path,
and drank of the same cup; yet, blessed be the name of God,
he that has kindled breathings in my soul after him, would sometimes break in upon me,
and though the waves of Jordan have gone over my head, his supporting arm was underneath,
that I should not be discouraged.
He in his infinite love has given me to understand,
that the things which belong to my peace are not utterly hid from my eyes;
that though I had drank up iniquity as the ox drinks up water;
although I had exceeded others in sin, and long done despite to him,
yet there was mercy with him that he might be feared.

Now would I address myself to the youth amongst you,
and in a certain sense of the divine extendings of that love wherewith he has loved us,
do I salute you with sincere desires, that that God which visited our fathers,
while aliens and strangers to him, may be our God;
that we may embrace the day of our visitation,
and not turn our backs on so great a mercy as he, I am sensible, is daily extending.
Oh!
I have tasted of his love, I have had to celebrate his name,
and though unfit for the work, I cannot be easy, or discharge my known duty,
without calling upon you to forsake the vanities of the world,
for the end thereof is unavoidable sorrow and endless torment: but happy are they who,
by a timely application, are earnestly seeking the Lord,
who will (I speak by blessed experience) be found
of those who early and diligently seek him;
for he has appeared to me when I was afraid I was forgotten, as a morning without clouds,
to my exceeding great encouragement and consolation,
and strengthened me in my resolutions to follow him who has done so much for my soul.
Bear with me yet a little, for I write not my own words;
that blessed Saviour has lain it upon me, who is willing that all should be saved,
and come to him; let him, I intreat you, have his perfect work in you; he will wash you,
or else you can have no share in him; I can truly say,
that during the time of my first conviction, my lips quivered, and my belly trembled,
that my soul might have rest in the day of trouble.
I choose not to write this, but I cannot be easy,
unless I call others to the like enjoyment;
in bowels of tender love I again salute and take my leave of you, with strong desires,
that you who are advanced in years, and favoured with the Lord`'s goodness,
may remember me when it is well with you, that I may be preserved,
though beset with temptations on every hand.
The Lord in mercy be with you, says my soul.
Farewell.

Samuel Fothergill.

LETTER LXXII.

Anthony Benezet to John Pemberton, (then in England) written a little before his death.

Philadelphia, 5th month 29th, 1783.

It is amazing what an influence the love of the world, its esteem and friendships,
and the desire of amassing wealth, living (themselves and children) in delicacy and show,
in conformity to the world, has upon so many in our society, who in other respects,
appear under some impressions of good;
notwithstanding they cannot but be sensible of its woeful
effect upon the religious welfare of their offspring,
who thereby (as mentioned by the apostle) fall into snares and hurtful lusts,
often to their perdition; notwithstanding the nature of our profession,
and a conformity to the example and precepts of our Lord,
lay such an absolute prohibition on such a state:
"`Lay not up treasures for yourselves on earth,`" says our blessed Saviour;
"`How hardly shall those who have riches enter,`" etc.
"`Woe to you that are rich.`"--Be not conformed but be transformed,
that you may be the belter qualified to follow him who has called
you in the way of the cross to be soldiers in his holy warfare,
but learn of him who was meek and low; who, though he was Lord of all,
chose to come in the form of a servant, walked on foot, fed on barley loaves, etc.
Some injunctions more doubtful and less likely to affect the heart,
we take according to the full force of the expressions, as with respect to an oath,
while others whose hurtful nature is more apparent,
and as positively prohibited by our Saviour, as that of laying up treasures,
we make nothing of, to that degree that even acknowledged ministers,
persons favoured with excellent gifts,
have so much degraded their noble calling as to engage
in entangling and dangerous worldly affairs,
or in seeking rich wives, sometimes in other respects unsuitable for them;
which is a stumbling block to sober enquirers,
who feel the strength of the gospel injunction, not to love the world,
nor seek high things, but trust in God.
When they see those of note amongst Quakers thus labour to lay up wealth in abundance,
though they cannot but see its direful effects on their offspring,
who are thereby induced to fly above truth, and even disregard their parents.
Well, I trust, the woe attending this disposition, as well to the individuals,
as to the reputation of truth, and hindrance of its prevalence amongst the people,
will become so apparent that endeavours will be used in a society capacity,
to put a check upon this disposition which is so much for laying heap upon heap,
land to land, etc. by requiring of their members,
that when they have got a sufficiency to carry on their respective business,
they shall not suffer wealth to heap up in their hands,
but shall apply the overplus to the relief of the necessitous, and other good works,
which the industry and frugality, which our principles lead to, will naturally produce.

An instance, which not long since occurred,
caused me to make some painful reflections upon this most weighty subject,
which I find my mind inclined to communicate to you, my dear friend;
perhaps you may make a profitable use of it in some places where your lot may be cast.
A friend died,
reputed to have left 60 to 70,000  to a number of children and grandchildren,
already so elevated by the fortunes they were possessed of,
as to be ready to take wing and fly above truth, in conformity to the world,
its friendships, fashions, etc.
This happened in the depth of winter,
one of those intense cold days which we all have felt to be very trying,
even to those who are best provided with fuel, suitable clothing, etc.
As I passed along, I observed aged people, and other weakly persons,
tottering about the streets, or standing in the cold,
in pursuit of a few pence towards a scanty subsistence,
many of those doubtless poorly provided with fuel or bedding,
both of which articles were then exceeding scarce and dear.
I compared the situation and necessity of these aged people,
with the superfluous wealth and delicate living of
the children of the rich man lately deceased,
and could not but be astonished at the selfishness and caprice of the human heart.
I queried with myself, are both these children of the same Father,
equally under his notice?
Are they enjoined (and do they profess) to love each other as they love themselves?
Why is not at least three quarters of the wealth of a number
of the rich Quakers laid out in procuring a place of refuge,
comfort, and moderate provision for such weak and aged people, that they may,
in the decline of life, be put into the most suitable situation,
to think and prepare for their latter end, and enjoy a moderate state of comfort?
Is it honest to God or man?
Is it doing justly as stewards of the wealth committed to our care?
la it loving our neighbour as ourselves?
If mankind are indeed brethren,
can it be agreeable to the good Father of the family of mankind,
that one should engross so much, and employ it to feed the corruptions of his offspring,
while others are under such manifest disadvantages for lack of the necessaries of life?
Many such strange inconsistencies you will meet with, in which, I trust,
you will be led to act in truth without partiality,
and to enforce the doctrine of the rich man and Lazarus.

Anthony Benezet.

End of Volume II.
