== Preface.

The intention of making public the following short memoirs,
is to commemorate the Lord`'s tender dealings with the author,
from the times of youth to a far advanced age,
as an encouragement to those who may be disposed to walk in the path of self-denial,
which hath always been attended with peace.
He wishes also that what is here related,
may tend to promote endeavours in the religiously disposed,
to come up in the faithful discharge of their duty towards God,
and to do what they can towards promoting the welfare of their neighbours,
and of the society of which they are members.
He is convinced, from the experience of many years,
that in order to be prepared for this good service,
there is occasion for the exercise of much patience,
till we have learned to endure hardness as good soldiers of Jesus Christ.

The advancements he hath made in religious knowledge and experience have been gradual,
so as hardly to be perceived by himself.--His mistakes and failures are remembered,
as warnings to be more careful in the future part of his life;
and he considers it among the greatest favours of heaven that they have not been greater:
some of them would have been avoided, if he had exercised patience,
and sought more earnestly for Divine wisdom,
instead of moving in that wisdom which is earthly and sensual,
with a desire of having that speedily accomplished,
which requires a long time to be brought to perfection.
He hath often experienced the truth of this declaration,
that "`The will of man worketh not the righteousness of God,`" and that all our movements,
both in a religious and civil capacity,
must be under the government of a peaceable and gentle spirit: not discontented,
if what we may be concerned to promote should not take place,
or the judgment of our friends should not agree with our apprehension of things:
the kingdom of righteousness is not established by the work of men`'s hands,
but by the power of God`'s spirit,
by which his servants are qualified to act to his glory.

The advantages of patience in all our concerns are great and extensive.--The
author recommends it as a principal good:
as especially necessary in our religious engagements,
when we are apt to proceed too hastily, without knowing the ground we stand upon,
which may prove not to have sufficient strength to support us in the day of adversity.
When we are disposed to bring into practice this excellent virtue,
in a humble dependence on the Lord our God for help, the troubles we meet with subside,
and the emptiness of earthly joys is seen,
so that we no longer wish to have our wills accomplished,
but the will of our heavenly Father.

Having said thus much by way of preface, he will add, that if the Christian experiences,
herein expressed,
should tend to encourage any poor traveller in his journey towards the celestial city,
it will fully answer what is intended: being convinced,
that the religion which will prove of advantage to
us does not consist in forms and ceremonies,
but is in the heart and mind, by which a change is produced from a state of nature,
and all the evil propensities of it, to a peaceable, gentle, harmless disposition:
in which the beneficent purposes of our holy religion appear,
to the praise of the great Author of it, and to our everlasting advantage.
It is therefore to be desired,
that no improper stress may be placed on the form
of religion which we may have received from our forefathers,
as though it would bring us to heaven without a personal
knowledge of the work of Divine grace in our hearts.

It is easy to perceive, that the religion of our Lord and Master, Jesus Christ,
is a spiritual religion; and only those who are spiritually minded can understand it,
and be benefited by it.
No wonder if those excellent doctrines and precepts,
which have been preserved to us in the Holy Scriptures, should not be approved of,
nor understood,
by those who have no other guide or instructor than what
human reason and their natural understanding impart.
The apostle truly describes our state when he thus expresses himself,
"`What man knoweth the things of a man, save the spirit of man which is in him?
even so the things of God knoweth no man, but the Spirit of God.`"
All the knowledge we have of Divine things comes from this illumination,
which we are to seek to obtain.
