== Chapter 1

[.blurb]
=== A certain writer says, "`A considerable part of the comfort and usefulness of our lives ariseth from Epistolary correspondence with our relations and friends, who live at a distance from us.`"

[.salutation]
Dear Parents,

I gladly embrace the opportunity which now offers, to inform you that I am,
through mercy, in good health; having borne the fatigue of travelling beyond expectation.
The ship sailed from Yarmouth on seventh-day morning,
and we arrived at Rotterdam on First-day, about one o`'clock in the afternoon.
After seeing some under our profession here, we went, by way of Delft and Leyden,
to Haarlem, where we met with Pieter Leendaars, a religious man, of good repute,
and a minister in our society, who went with us to Amsterdam.
The number of Friends in this city is small: but we are informed,
that the meetinghouse on the First-day is generally very full of strangers.

I can judge but little from what is at present seen, of my service in this land;
it must be left to the Lord, who I trust, drew my mind towards these parts.
With respect to you,
my dear and tender parents! my heart is deeply affected in the remembrance of you,
and my prayer is, that I may be so directed as to be no cause of sorrow to you.
By what I feel of the love of our heavenly Father,
I am ready to conclude his regard is towards you,
and that he still waits to bestow his blessings upon you, as you abide in his fear.

With remembrance of dear love to brothers, and other relations,
I remain your dutiful and affectionate son,

[.signed-section-signature]
John Kendall.

[.signed-section-context-open]
Amsterdam, 18th 7 Mo. 1752.

[.salutation]
Dear Mother,

Thou art fresh in my remembrance, and so I trust,
wilt continue to be--imprinted in characters which cannot easily be erased!
It is even hard to express the love and esteem which spreads in my mind towards thee,
whose memory is so sweet.

Thy trials and exercises I do not expect are at an end;
yet in faith that thou witnessed the arm of Divine power underneath to support,
I am comforted,
and made to hope that the enemy of our peace shall not be able to prevail.
Be not thoughtful concerning me, but rather commit into the Lord`'s hand,
who can preserve.
Though I have nothing to boast of, yet I may say, a degree of solid peace hath,
at times been witnessed, which makes amends for the difficulties attending.
We have been in this city ten or eleven days, in which time have had divers meetings,
and visited some families to our mutual comfort.
We intend to set out soon for Osnabrug, and return to Amsterdam in about two weeks;
our friend, J. Vanderwerf, is to accompany us, as an interpreter.

When way opens for my returning home, I hope I shall embrace it; in the mean time,
I desire to resign myself, with thee, and all my dear relations,
into the hands of a merciful Father, and Saviour; the dispensations of whose providence,
it becomes us to receive with patience; contented with the portion allotted to us,
in the time of our sojourning here.

[.signed-section-closing]
I am thy affectionate and dutiful son,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Amsterdam, 1752.

[.salutation]
Dear Parents,

Both your letters I received upon our return from Germany,
to my great comfort and satisfaction.
Have now to inform you, that we came to this city again on the 31st of last month,
and intend in a few days to go into North Holland, to visit the Friends there:
after which I expect we shall be on our return into England.
We have met with a hearty and kind reception where we have been,
and found a number worthy to be visited, which is matter of great satisfaction,
and gives room to hope our journey will not be entirely fruitless.

Though there are not many circumstances to mention,
I am still desirous you should hear from me.
I feel my mind impressed with fresh marks of love and esteem, and duty to you,
my honoured parents! whom I hope the Lord will yet more closely unite,
in the bond of everlasting peace, against which nothing can prevail, so as to divide.

[.signed-section-closing]
I remain your affectionate and dutiful son,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Norwich, 7th 5 Mo.

[.salutation]
Dear Mother,

I did not expect when I came here to make such a long stay,
but I hope my absence will be made easy to thee;
if I am so far favoured as to be preserved in my place,
the conclusion will be crowned with peace.
The enemy is indeed permitted to buffet; and I have to wade through low seasons,
finding almost a continual opposition to what appears
right and likely to be profitable to me;
so that I am obliged to exercise patience,
and be constant in my application for Divine help,
by which I have hitherto witnessed preservation.

Thou mayst wonder I should make my religious experience so much the subject of my letters.
I must own, I think myself led in a path somewhat different from many of my friends;
who appear to allow their religious concerns a suitable place,
and at the same time give much attention to their outward affairs,
whilst I can think or speak of little but what relates to my spiritual improvement;
which is more in my mind than any outward profits or advantages.
And my desire is, that we may obtain, in due time,
a settlement in the unchangeable truth, so as to be set above all changeable enjoyments,
and to have a well grounded hope in the possession of that treasure which is everlasting.

[.signed-section-closing]
I remain thy affectionate and dutiful son,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Amsterdam, 21st 7 Mo.

[.salutation]
Dear Mother,

Through mercy, I have enjoyed better health than when at home, which I esteem a favour:
I have cause likewise to be thankful for a degree of inward help and support,
from that good hand and arm by which I have been preserved in times past.
We may truly say, the Lord is worthy to be trusted in;
He is able and willing to help his people.
Though their exercises and afflictions are great in this life,
there is benefit attending them, as we abide in the patience.
Thou hast had experience of the Lord`'s goodness,
and I doubt not the same will be continued to thee to the end.
Let us put our trust in him, and not in anything which this life affords.
Then if we have not some outward comforts that are desirable,
the disappointment will be the less.
He knows what is best for us, and does not afflict willingly.
He can sweeten every bitter; even a glimpse of his favour revives our drooping minds.
It may well be said, "`One hour in the presence of God is better than a thousand.`"
It is no wonder that our forefathers,
and those who suffered in the cause of truth in all ages,
should rejoice in the midst of outward affliction, even unto death,
feeling the Divine presence to support.
No words can express the comfort it affords to the Christian traveller!

My companions desire their kind love to thee.
We have travelled together in great unity, and nearness to each other:
the effect of our labour must be left to the blessing of the Almighty,
in whose service I trust we are engaged for the promotion of his cause.
If we find peace from him, it will be a sufficient reward.

[.signed-section-closing]
I am, with great affection, thy dutiful son,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Northampton, 13th 7 Mo.

I remember the discouragements which are apt to attend thy mind:
it will be best for thee to endeavour to leave things which thou seest amiss in others;
if thou art not the cause of them,
it is not necessary for thee to take the weight upon thee,
but rather leave it for such to bear to whom it belongs.
I am afraid, if we look so much at the failings and misconduct of others,
we shall be in danger of omitting our own duty, through discouragement.
The enemy of our peace hath many ways to disturb us, and may prevail by outward means,
(if we are not careful,) when he is frustrated in his endeavours to hurt us more inwardly:
may it therefore be our concern to wait on the Lord
for the renewings of his comfortable presence,
in order to our being preserved in quietness and patience
in the midst of afflictions which are permitted to attend.
There is no room to expect we shall be free from troubles in this life;
that which tends to sweeten them is best for us to follow.
I know thou art apt to think thy troubles greater than are commonly met with;
but if I was to inform thee what we have seen in some families,
where we have been in this little journey, thou would perhaps allow,
there are afflictions greater than thine.

It will afford thee pleasure to hear our journey thus far hath been attended with peace;
we have been helped to discharge ourselves in what seemed incumbent on us,
to our relief and comfort.
It is my desire to be making grateful returns for the many favours received,
by faithfulness and obedience to the Divine requirings,
that my little stock of heavenly treasure may be increased, to my own comfort,
and the benefit of my friends.

[.signed-section-closing]
I remain thine affectionately,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 11th 9 Mo. 1753

[.salutation]
Dear Friends,

Since I heard of your having left England,
my remembrance of you hath been such as to incline me to
take the liberty of writing a few lines to you;
as one not wholly unconcerned in the Lord`'s work, and the prosperity of his cause,
in the land where your lot is now cast.
My prayer is, that God may bless his work in your hands,
and make you instrumental to the confirming and strengthening the few that remain,
who are in a weak state.

I am sensible you meet with difficulties,
for want of understanding the language of the country;
yet I hope you will meet with assistance in this respect,
particularly from J. Vanderwerf, junior who understands the English,
and is in a good degree qualified for the service of an interpreter;
following the example of his worthy predecessors,
who counted nothing too dear to part with for the testimony of truth,
and furtherance of the blessed gospel tidings of salvation;
among whom I may mention John Claus, who,
in the account he gives of some transactions of his life, says,

"`Soon after having altered my intention of removing to England,
I found myself engaged to travel, as interpreter, with the ministering Friends,
and endured in those journeys many hardships: my love to the cause,
nevertheless was such, that I always held myself prepared thereto,
and with diligence endeavoured to qualify myself for this service,
by a more perfect knowledge of the proper sense and meaning of English phrases,
and of the Low Dutch translation of the Scriptures.`"

Having thus expressed my wishes for your good success in the present weighty undertaking,
I remain your affectionate friend, in the fellowship of the gospel,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 9th 3 Mo. 1755.

[.salutation]
Dear Friend,

I can truly say thy salutation and expression of love met with free reception in my mind.
Thou canst sympathize with me in the trying dispensation
which the Divine goodness permits to attend:
it is my desire that a suitable degree of patience may possess my mind;
that so I may wait the Lord`'s time for deliverance.
He can lift up the hands which hang down, and strengthen the feeble knees;
blessed be his name forever!

I have no reason to complain, though among the least of his afflicted people;
his goodness hath reached to me,
(so that I can speak well of his name,) if he hath called
and appointed me to bear testimony to his truth and cause;
may I then labour, with unwearied diligence, to approve myself faithful to him; that so,
as he hath given a little strength, he may be pleased to add more;
and an advancement in understanding and knowledge may be experienced.
But oh! how great is the weight of the Lord`'s work! and
what need there is of continual application to him for help!
He is first, and principally to be regarded;
though many things combine to draw us from a proper dependance on him: on one hand,
the cares of this life are apt to fill the mind;
and the deceitful satisfaction of riches: on another hand,
the friendship of the world presents itself to our view,
with a pleasing aspect and show of reason, but is enmity with God!

Thus I express my experience,
from a sense of the dangers surrounding us in this state of probation.
Without the help of Divine truth, inwardly witnessed,
we are destitute of strength sufficient to support us in the trials attending;
and what if I say it is for want of dwelling near the fountain of all good,
that so many are gone from the ancient path of Truth and primitive simplicity.
May a strict watchfulness be continued in us,
as indeed is necessary for all the sincere-hearted,
in order to keep a conscience void of offence.

[.signed-section-closing]
I remain thy affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 27th 2 Mo. 1757.

[.salutation]
Dear Friend,

Since I last heard of thee thou hast been frequently in my remembrance,
and I am still desirous that the correspondence between us may be continued.

I often think of the few remaining Friends in the part where thy lot is cast;
and it is a comfort to me that I have to believe there are those among you,
who are careful to show forth in their conversation a firm belief
in the good principle which we are making profession of.
As these continue steadfast they will be a means of
supporting the cause and testimony of Truth,
and be a comfort to their relations and friends.

Since my writing the above I have heard of thy taking
some steps towards changing thy condition,
by marriage;
in a proceeding of such importance I hope thou wilt have the approbation of thy parents,
and proceed cautiously.
It is better for us to remain in our present state than to be unequally yoked.

[.signed-section-closing]
I am thy affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Amsterdam, 13th 8 Mo. 1757.

[.salutation]
Dear Friend,

Thy testimony of friendship is always agreeable to me, and in return I can say,
my love and affection towards thee remains unaltered:
with desires for thy welfare and increase of those riches which are everlasting.
With regard to our journey, we have witnessed, in a good degree preservation,
and are thinking to be on our return in about a week;
we have met with several seeking people in this city, who have a love for truth,
and are not contented with the forms and ceremonies of religion,
to whom our visit was acceptable.

With salutation of dear love I remain thy affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 6th 11 Mo. 1757.

[.salutation]
Dear Friend,

Thou art not insensible of what need there is of faith and patience,
in the baptisms of a mind sensible of its want and insufficiency;
and at the same time not feeling the wished for degree of divine support.
This dispensation it hath been my lot to be tried in, perhaps beyond many of my brethren;
and had not the arm of divine power been underneath,
how was it possible for me to be supported in the perils and sufferings which have attended.

May they but have the tendency to draw my mind from a confidence in any human support;
to put my trust only in the Lord,
who is sufficient to carry on his own work to the praise of his name.
I find however occasion to double my diligence, and to be still more watchful:
there are so many places in which the enemy of our peace is seeking to gain an entrance.
Some may go on smoothly, and to appearance are making a swift progress; for my part,
I find, and always have found, the advances in religious experience to be very gradual.
And, if I am not mistaken, the Lord is making use of such, in this day,
to build up the waste places in our Zion, as have witnessed his delivering arm near,
in great trials, and brought up stones of memorial, as from the bottom of Jordan.
These shall enter the promised land, and under their great leader overcome their enemies,
meaning in a spiritual sense.
But oh! what loss ensues, when with Achan the accursed thing is secretly embraced!
May all the Lord`'s people be preserved, clean, and in their tents,
clothed with that strength and authority, which their gainsayers cannot withstand.

Though the discouragements and difficulties are great which
are met with in repairing the walls of our Zion,
so that the city may again be inhabited,
yet there is a prospect of success attending the labour of the right-minded.
And if we are now only employed in removing the rubbish,
occasioned by former desolations, there will be a reward for all the faithful labourers,
answerable to the work they are employed in.

I am joined by my mother and brothers in kind love to thee,
and remain thy affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
1757.

[.salutation]
Respected Friend,

The little conversation we had together,
when there was not opportunity of making reply to what thou said, occasioned, soon after,
my considering the subject more fully,
and as it may be a satisfaction to thee to know what
are our sentiments concerning this weighty point,
I have extracted something from a small piece wrote in vindication of our principles,
which is as follows.

"`We have been cautious in expressing our faith concerning that great mystery,
especially in such school terms,
and philosophical distinctions as are unscriptural if not unsound;
the tendency whereof hath been to raise frivolous controversies,
and animosities among men.
And though for this reason, by those who desire to lessen our Christian reputation,
we have been represented as deniers of the Trinity at large, we ever believed,
and as constantly maintained, the truth of that blessed Holy Scripture Three,
that bear Record in Heaven, the Father, the Word, and the Spirit,
and that these three are One; the which we sincerely and reverently believe,
according to 1 John 5:7. And this is sufficient for us to believe and know,
and hath a tendency to edification and holiness;
when the contrary centers only in imaginations, and strife,
(and persecution where it runs high) and in parties,
as may be read in bloody characters in Ecclesiastical histories.`"

I hope this will give thee satisfaction with regard to this great article of our faith.
As to public controversy on such points,
it does not appear to me likely to be productive of good,
but rather hurtful to the cause of religion and virtue,
as having a tendency to lead from the practical part of religion into speculation.
Instead of this,
it seems necessary to remind each other of the insufficiency of
an outward knowledge and comprehension of the truths of the gospel,
to effect our salvation,
and if possible to rouse up such as are contenting themselves in a profession;
strangers to the work of that grace in their hearts, which, when given way to,
produces a change from sensual to spiritual; but is of such a nature that,
where room is not allowed for its growth, the good fruits will not appear.

I cannot but lament the loss which is sustained by the professors of Christianity,
in this nation, and other parts of the world,
through the want of the life and power of that religion which they profess:
thus a shadow is embraced for the substance.
Nothing would more promote a reformation than a faithful
adherence to the dictates of Truth in our minds;
this is the unction from the Father, which teaches as never man taught;
a swift witness against the unfruitful works of darkness: with this all are favoured,
and it is the greatest blessing we enjoy.
But whilst I speak in favour of it, I do not forget how it is slighted, and overlooked,
so that many are strangers to the privilege they enjoy;
it is the business of those who are concerned for
the good of others to direct to this guide.
Divers names may be given to it, but it is no less than Christ within, the hope of glory.
If there was a listening to the instructions of this guide,
and proper advancements made under the leadings of it,
more able defenders of the cause of Truth, would be produced:
for men are directed to place their confidence in the redeeming power of truth,
and to look from the creature to the Creator,
considering his instruments only as employed to remind of our state,
and to warn of our impending danger.

[.signed-section-context-open]
Colchester, 12 Mo. 1757.

[.salutation]
Dear Friend, J. V.

My prayer on thy behalf is, that thou mayst be preserved from hurtful engagements.
Let me entreat thee to have an eye to Providence in all thy concerns,
and as thy expectation is towards him he will care for thee.
Keep thyself disengaged from that which would render thee unfit for the service of Truth;
thou wilt never have cause to repent of having been serviceable thereto;
but on the contrary wilt have the reward of peace.
Although what we do seems to be very small in our view, yet it brings a blessing,
and tends to our prosperity, both outwardly and inwardly.
As we have many things to strive against,
so may we ever continue to be engaged in the holy warfare,
using the utmost diligence through Divine help,
to oppose the hurtful inclinations of our corrupt nature,
the indulgence of which is always attended with sorrow.

Keep thyself unpolluted,
(which through the grace of God thou wilt be able to do)
from that spirit which exalts itself above the holy gift;
and thou wilt enjoy a freedom, that will bring more joy,
than the greatest of earthly blessings.
This, though so necessary for a Christian,
is a mystery to many who make a high profession.
But the condition of others will not affect us, as we take heed to our way.
And as the day calls for diligence, let us be attentive to the concerns of our minds,
lest we should not be prepared for that great change to which we are fast advancing,
which is the last of all the changes we shall have to meet with in this transitory life.

I remain, in the love of our first friendship, thy affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 3rd 4 Mo. 1758.

[.salutation]
Dear Aunt,

I have been more than once or twice about to write to thee,
but for want of sufficient matter, as often declined it;
yet lest my silence should be thought to proceed from forgetfulness,
and want of affection, could not be easy any longer to omit it.
I can assure thee the friendship of such as I esteem is very valuable to me;
and I have as much need as ever of their remembrance;
and desire not to be forgotten by them, though at times dipped into so great poverty,
that I am ready to think myself undeserving regard, and to call in question my sincerity.

I compare myself to a ship, which after a long voyage, and enduring many storms,
is found nevertheless, through the help of a good pilot, in its right course,
and approaching the desired port; but on a sudden interrupted again by contrary winds,
and made to pass in unknown ways.
Such a vessel had need be strongly built, lest by the long tossing,
and violent beating of the waves, it prove leaky, and be lost in the sea.
Thou canst understand my meaning from thy own experience.

In the midst of these trials my prayer is put up to the Lord for preservation,
and his arm is felt underneath to support, which is cause of thankfulness.
However difficult the path may be in which we have to tread,
it is good for us to be contented in our station; and, as we remain steadfast,
all will work together for good.
We are placed in a state of continual dependency,
and likely to be favoured with divine help,
in submissiveness under the various trials attending.

Not as citizens of this world, but strangers and pilgrims,
we must expect to be treated roughly;
and it may be well for us to find such entertainment,
lest one or other of these alluring objects which are presented,
should so attract and draw our attention,
as to make us forget the proper object of our love.
When we meet with troubles,
nothing more happens to us than what Christ signified should be the lot of his disciples:
may we then have our hope fixed on him, who gives rest and peace.

[.signed-section-closing]
I remain thy affectionate cousin,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
8th Mo. 1758.

[.salutation]
Dear Aunt,

Since we had some conversation together, I have perused this small treatise;
and with so much satisfaction that I soon found an inclination to recommend it to thee;
with my request that thou wilt allow the weighty
arguments therein used to have place in the mind.
And if thou art convinced of the truth of what is said,
and seest there is occasion for a different conduct to that which hath appeared,
do not act any longer contrary to conviction; for however we may now plead excuses,
a reckoning day is approaching, and hastens upon us,
when an account must be given of our stewardship,
and those who have been most industrious will have the greatest share of Divine approbation:
on the contrary, such who have not made a proper improvement of the talents given,
will have to reflect with sorrow on the misspent time, which cannot be recalled.
Nor can we tell what a long course of disobedience may bring us to;
how insensible we may become to the things which belong to our peace,
or to what a degree of weakness reduced; so that the enemy of our peace, prevailing,
may lead us captive.
Then do many false arguments appear, suiting a fleshly liberty,
which we are more fond of than the easy yoke of Christ, which his true disciples bear,
not with reluctance, but cheerfully.

If thou submitted to bear this yoke with a sincere desire rather to please God than man,
then I have no doubt there would be a concern to assemble with thy friends,
to acknowledge the regard thou owes to Almighty God,
by whose permission and providence we have thus long had continued to us a being here:
not with intent we should live only to ourselves, but that we should lead others,
by our good example, to the excellent principle which we profess to be led by.

But alas! how is the glory of some eclipsed,
who might have shone as bright stars in the firmament
of God`'s power! let us beware of others harms;
if the loss they have sustained is evident to us, shall we tread in their steps,
as if regardless of the consequences?
I have viewed with astonishment, the unhappy situation of some,
who it is to be feared have made shipwreck of faith and a good conscience,
by their too easy compliance with wrong things;
the love which they once had to the truth, being in a great degree lost.
Well would it be for such to recollect the time which hath passed over,
with little profit to themselves, or good to their fellow creatures,
as to their spiritual interest; asking, with penitential hearts,
forgiveness for what is past; and instead of persisting in a course of disobedience,
stopping to enquire strictly into the state of their minds.

This is the disposition, I am ready to wish, thou and I might be found in,
if we should miss our way, and not among them who are hardened against instruction; who,
having entered into a wrong path, show by their conduct a resolution to persist in it,
though the end will be shame and confusion, instead of peace and Divine approbation;
which we even now stand in need of, to make our lives truly comfortable,
and will hereafter be a source of joy, when all earthly things are done with.
But what room is there to sooth ourselves with vain
hopes of that becoming our portion in eternity,
which, in time, we have lost, and deprived ourselves of.

These few lines I entreat thee to accept kindly from thy well-wishing friend,
and affectionate kinsman,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 16th 3 Mo. 1759.

[.salutation]
Dear Friend, J. P.

It hath not been through want of affection that I have omitted writing to thee thus long,
but some more than common engagements have fallen to my lot since I saw thee last;
the likeness of our condition, makes me a little compare myself with thee,
I mean with regard to the share of work fallen to
our lot in the society to which we belong,
thus in the early part of my life.
May the arm of Divine power, by which we have hitherto been supported,
still be extended for our support, is the prayer of my mind:
that so we may not be discouraged by any of the hardships
and trials we meet with for the cause`'s sake,
but by faithfulness to the little required of us,
become more and more fitted for the work we are called to.
So will the increase of peace be greater in proportion to our sufferings.

What we meet with calls for the sympathy of our friends,
yet patient waiting helps us along, and to this I recommend thee, as a principal good;
the Lord knows what we stand in need of,
and will plead the cause of those who put their trust in him.
Though we are now poor and low,
the help we have formerly experienced may strengthen our faith in Divine power,
which remains the same, and is worthy to be trusted in.

Let us endeavour to be more fully devoted to the service of our great master,
who hath called us early to labour in his vineyard, and we shall not miss of a reward.
One cause of the halting, and dwarfishness, so apparent among us,
is the want of industry and care to improve the talents received;
it is not through any deficiency in the giver of every good and perfect gift,
that many are not become instruments of good in the Lord`'s hand,
but through unfaithfulness to what is received,
they obtain not that which might have been added.
The continual assaults of an unwearied enemy threaten our overthrow,
but let us not faint in the warfare.
He that hath begun a good work in us, will carry it on to his own praise,
as we are obedient to him, and still waiting for his direction and help.

I remain in the love of our first acquaintance, thy affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 17th 1 Mo. 1760.

[.salutation]
Dear Friend,

Thou hast been often in my remembrance since I received thy acceptable letter;
and though I have thus long delayed to answer it, there is no want of love and respect,
on my part; nor will anything we may have to meet with, be able to disunite us,
whilst we are preserved still walking in the truth,
and are kept near to him who is the friend and father of his people,
as also their Saviour and never failing helper.

It is my desire for us that we may remain steadfast
in our obedience to the captain of our salvation,
as good soldiers of Jesus Christ, learning to endure hardship;
not discouraged by evil spies,
whose report is according to fleshly weakness and reasoning,
and not like the good tidings brought by Caleb and Joshua,
for the encouragement of the people: such faithful servants are wanted in our day,
who are concerned to promote the welfare of their brethren.
Indeed it may be said, that as that love prevails in our hearts which is of God,
and is boundless, we cannot but desire the good of all.
Let us pray that we may be enabled, in the strength of it, to act,
to the comfort of each other, that no evil fruits may appear,
but the fruits of the Spirit, which the apostle describes to be love, joy, peace,
long-suffering, gentleness, faith, meekness, temperance.
These are the fruits which are wished for, to be seen among the professors of Truth:
that the good reputation of the society may be maintained,
and the name of Christ our Saviour honoured.
The friendship and love I feel in my mind towards thee,
would admit of saying more on these subjects;
but what I have written may serve to show thee the disposition of my mind.

[.signed-section-closing]
I am thy affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 7th 10 Mo. 1760.

[.salutation]
Dear Relation,

Thou hast been often in my remembrance since I saw thee last,
and nothing but want of ability hath prevented my writing to thee.
I believe thou art not without troubles, and such as tend exceedingly to humble,
and keep thee low; and it may be without discerning the cause, thou art ready to say,
"`Why is it thus with me?
Lord! in what have I offended thee,
that thou should permit such a variety of afflictions to attend,
and so withdraw thy comfortable presence?
without which, nothing that I enjoy is satisfactory.
My way is so straightened that I know not how to proceed; the objections are so powerful,
that I begin to fear that the protection, which I have known in times past, is withdrawn;
O the baptisms that my soul witnesses, the mourning in secret for want of my beloved,
who hides himself from me, and I am left, as it were, surrounded with enemies.
Though my prayer ascends to thee morning and evening, and more often the day,
yet thou art not pleased to manifest thyself to me, in the degree I wish for.
I sit solitary, as the dove which hath lost its mate;
having but little to afford me comfort, save an assurance that thou hearest my complaint;
and canst give me relief when it pleaseth thee.`"

If this is thy state, dear fellow traveller, I can sympathize with thee,
because it is the path I have had to tread in; be not discouraged;
whom God loves he chastises; not in displeasure,
but that we might become obedient children:
as we know not what degree of correction is necessary for us,
there is occasion to submit ourselves to the fashioning of that hand,
which hath begun to prepare us for its use: there may be more dross than we perceive,
wanting to be purged off by the furnace of affliction.
We are short sighted, and incapable to judge of what is best for us:
let us therefore humble ourselves under the mighty hand of God,
and seek for resignedness to every dispensation which he sees meet we should pass through:
there are many things met with which we can by no means account for:
yea such changes are felt in our hearts as make us wonder what shall follow.
In this condition we must not lean on any thing less than the Lord`'s arm of power:
no arm of flesh, nor outward support is sufficient to uphold in the provings,
great strippings, and deep baptisms of the Lord`'s children:
they experience no relief but from his favour;
nor is there any balm administered to their wounded spirits,
but as the good Samaritan hath compassion on them.
Look to him then, in all thy troubles, and be contented to wait till he comes;
the more desolate our condition, and the more we are deprived of outward comforts,
the more we become conformable to the sufferings of our great master;
and the greater is our consolation when it pleaseth him to open the prison doors,
and set the prisoner of hope at liberty.
Thus we shall be set free indeed,
and become witnesses to that Divine power which raiseth from death to life.
O blessed power! may it be witnessed to set us free from every earthly tie,
and help us to assert our liberty from every yoke of bondage;
that we may serve and worship the Lord our God in the liberty of his Spirit.

This is wanted to prevail in the hearts of the people, but is not enough sought after;
which is the cause of so much deadness as is felt in our assemblies,
and so much barrenness as appears amongst the professors of truth:
let us desire that we may be favoured with strength
to wait for the renewing of this good,
that our hearts being enlarged in it,
we may be enabled to accomplish what will prove to our everlasting advantage.
This will make us as epistles written in one another`'s
hearts which cannot easily be erased:
neither time nor absence can wear out an affection
which hath its ground in that which is everlasting.

I conclude with the tenders of dear love to thee, and the rest of our relations,
(as there is opportunity of mentioning it,) thy affectionate kinsman,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 13th 11 Mo. 1760.

[.salutation]
Respected Friend,

My mother received thy letter, which was very acceptable to her.
She desires me to acquaint thee, on her behalf,
that since thou left Colchester she hath often remembered thee,
with desires for thy welfare and prosperity, in the best sense:
that the good work which is begun in thy mind may succeed to thy comfort,
and further settlement in the blessed, unchangeable Truth.
No earthly treasure is to be compared with that good which
is offered to us in the visitations of Divine mercy;
well may we prize it above all which this present life affords,
and more earnestly seek after the renewing of it, than the increase of outward comforts;
which are of short duration, and uncertain to us;
but this is an everlasting stay to the soul, which may be safely trusted in.

It may be said concerning this heavenly guest, as was said to Zaccheus,
when at the call of our blessed Lord he came down and received him:
"`This day is salvation come to this house.`"
It will prove of unspeakable advantage to thee if thou in like manner
receives him who is sent to thy house as a messenger of peace:
though thy situation in life subjects thee to many troubles and afflictions,
remember they have been the lot of good people in all ages; and that it becomes us,
rather to desire to be helped to bear them patiently, than to have them removed.

I desire thee to accept these few lines as a token of our love, to which I may add,
it will be pleasant to hear from thee when convenient;
in the mean time I remain thy sincere friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 28th 3 Mo. 1761.

[.salutation]
Dear Friend, J. A.

Thou hast been frequently in my remembrance since I was at thy house,
and such sympathy felt,
that I have been more than once ready to express it in this manner.
It is desirable to witness an increase of that love which unites the Lord`'s people,
and makes them dear to each other, in which there is a bearing one another`'s burdens,
and helping to forgive offences, as we would be forgiven.
When it prevails among the professors of truth, excellent fruits appear; innocency,
patience, long-suffering, gentleness, goodness,
by which the church is edified in the most effectual manner.
We lament the want of this love among our brethren; yet we must not be discouraged,
but use our endeavours to promote it in ourselves and others.
The apostle thus further describeth it: Charity vaunteth not itself, is not puffed up,
doth not behave itself unseemly, seeketh not her own, is not easily provoked,
thinketh no evil, rejoiceth not in iniquity, but rejoiceth in the Truth,
beareth all things, hopeth all things, endureth all things.
These are the fruits, which a remnant long to see clothe the professors of Truth,
as containing the sum and substance of religion, without which, it may be said,
we are but as sounding brass, and a tinkling cymbal:
to have our hearts enlarged in this love, is what we have need to desire,
that we may be in a capacity to worship the great Author of our being,
and promote the welfare of our fellow creatures:
without it we shall soon lose all relish for spiritual things, and center in the earth,
and in the love of earthly things.

If I am not mistaken, this is a trying time to the right-minded,
in which great industry is required to gather up daily that which keeps alive to God;
so much indifferency and coolness appears among those who
are our brethren and sisters by an outward profession.
Now lest, in this time of suffering, the enemy of our peace should get entrance,
and the seeds of discontent should arise, we must be careful how we look out for help.
We are sensible that nothing less than the power of Divine
Truth experienced by the work of grace in our hearts,
can raise us up from the dead forms in which many are resting contented,
and would draw others into the same self-pleasing condition.
Let us remember there is no safety for us, but whilst we are kept in a humble,
waking frame of mind, following the example of our Lord and Saviour Jesus Christ.
What is necessary to bring us to this, we know not;
we have therefore reason to be contented, if a large share of suffering should attend us,
and frequent baptisms, that self may be reduced, and become of no reputation,
that being stripped of our own righteousness,
we may be clothed with a better righteousness, which is of Christ.
So will our advancement in religious experience,
and knowledge of the redeeming power of Truth come to be real.
However gradual the steps may be, which we have to take, it is better to go on slowly,
and with difficulty in a right way, than to go on smoothly, and with delight,
in a way the end of which is in trouble.
Our blessed Lord signified to his disciples that they should have trouble;
and this indeed is found true, but not without partaking of that peace,
which he promised they should find in him.
I have always found it best to be contented,
and bear the dispensations of Providence with as much cheerfulness
as my weak condition of body and mind would admit of:
still hoping for a time of relief, which hath come, as I was patient;
and will continue to be experienced by the honest mind.
Our Heavenly Father is not withdrawing his care over us,
though he permits trouble to attend; he heareth the complaints of his afflicted seed,
which crieth to him for relief, and sets free from the hand of the oppressor,
in his own time; blessed be the name of the Lord our God!
He is the same to his people as he was in times past;
and his arm is often made bare for their deliverance;
so that they have to sing a song of praise to him, as on the banks of deliverance.
May we trust in his power, and wait for the manifestation of it in our hearts.
I would have none question the continuance of the same fatherly care,
which was extended in the early times of their visitation from heaven,
when they entered into covenant with the Lord:
if he should see meet to hide himself for a time,
it is in order to fit for more extensive service,
or to teach us to endure hardship as good soldiers of Jesus Christ.

I would not willingly be tedious, but the love I feel towards thee,
with thy dear relations,
makes me desire to say something which may be useful to
you in the lonely pilgrimage as from earth to heaven,
wherein but few travellers are met with.
Oh! my dear friends,
let it become your concern to avoid everything which hath a tendency to obstruct,
in this journey, that so your comfort may be continued and increase,
and in the end you may obtain a crown of everlasting peace!

Unto the direction and guidance of that good hand which
hath been mercifully reached forth for your deliverance,
I desire to commit thee, with the rest of the family, as if named,
and remain your affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 1st 6 Mo. 1761.

[.salutation]
Dear Friend J. P.

It will be pleasant to hear from thee,
as a means of renewing that friendship and love which was experienced in times past,
when there was opportunity of personal conversation.
Amidst the many changes we meet with, as well as dangers which attend us,
in the time of our sojourning here,
it will be no small advantage to retain our integrity,
and feel our hearts enlarged in love to our brethren.
I must own it is an occasion of comfort to me to find strength
to perform acts of benevolence towards my friends and neighbours;
and the intercourse we have by thus communicating our thoughts to each other by writing,
I consider not among the least of the privileges we enjoy.
Yet it may be said,
when no signs of the friendship subsisting between us appear in this way,
that we are as epistles wrote in one another`'s hearts,
which neither time nor absence can easily erase.
Thus hath my mind been disposed towards thee, though separated by so great a distance,
both of sea and land, and such a long time hath passed since our meeting,
as is sufficient to draw into oblivion many common occurrences,
of which few are more forgetful than myself.
But a fellowship in spirit, once felt, makes deeper impression;
so that I find the memory of my friends revived with sweetness,
in the springing of such love as, is not easily expressed.
This, I apprehend,
will become more strong and engaging as our access
to the fountain of all goodness is continued.
Love to the brethren will increase.
Not but that there are times of great weakness; which I have largely experienced,
and must expect to experience.
But by continuing steadfast in the patience, these will prove of advantage,
and yield such peaceable fruits,
as will make amends for the pain and exercise we have endured.
If nothing but what is pleasant was met with, where would be the exercise of our faith?
we serve a good master, who rewards bountifully;
though his favours are dispensed in a way and time hid from our view:
He knows what is best for us; the way our inclination plans out may not be best;
so that nothing is more desirable than to witness a state of resignation,
and contentedness, in whatever condition our minds are:
whether we go on smoothly or with difficulty, find liberty, or are straightened,
there is still occasion to look up to our Heavenly Father,
who is our stay both in the heights and depths.

In considering the favours we have received,
I trust thou canst join me in returns of thankfulness.
Let us still trust in him that is our Saviour and Redeemer, and wait for his appearance,
which comforts and enlivens our drooping minds.
I shall add no more, but remain with tenders of dear love, thy affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 18th 9th Mo. 1761.

[.salutation]
Dear Relation,

When we feel the circulation of love in our minds towards God,
we are made to long to communicate a part of that goodness to our brethren,
who stand in need of our assistance;
and we are made instrumental at times to help one another,
through the prevalence of this love.
Who that feels its virtue can forbear to wish that all might partake of it?
I speak this, not because I think thee a stranger to it,
but a little to commemorate the kindness of our Heavenly Father toward us,
in favouring with a measure of his good Spirit:
he is affording comfort according to the state of every mind;
so that none have cause to complain.
Difficulties are made easy, and burdens light; what hath obstructed is removed,
and the way so opened before us, that we can go on our journey heavenward with freedom.
If we are deprived of some outward comforts, which we have been used to partake of,
there is that remaining from the Lord`'s good presence
which can abundantly make up the loss.
It will be well to remember that all outward comforts are uncertain to us,
and of short continuance;
but the peace and comfort to be obtained in Christ our Saviour is certain and everlasting.
No wonder that the servants of God in times past, having this consolation,
did rejoice in the midst of trouble, and cheerfully suffered,
even to the laying down of their lives.
What they enjoyed here was of small estimation compared
with the favour of Christ their Lord,
with whom they had entered into covenant.

Their path was a path of self-denial, not of fleshly indulgence;
a share of the sufferings of their great Master attended them,
and does now attend the faithful followers of Christ, which is not to be wondered at,
considering our condition as sojourners in this life; of whom it may be said,
we have no continuing city here:
our great business is to seek for help to commit ourselves, and all that we have,
into the hands of the all-wise disposer,
whose care over us is continued through the various
exercises that are permitted to attend.

Though things are not with us as we could wish, yet,
that we are in the land of the living,
and in some degree set at liberty from the hand of our oppressor,
are favours we can hardly be sufficiently thankful for.
May it always be our concern to walk humbly before the Lord our God,
who hath raised us up from a low condition to praise him.
Much more might be said,
but these few hints offering themselves in the springing of dear love,
I freely transmit them to thee,
with desires that thou mayest witness a renewal of
strength to persevere in the path of peace,
by looking to the Lord for help, who is the never-failing helper of his people.

I remain in near affection, thy loving cousin,

[.signed-section-signature]
J+++.+++ K.
