== Chapter 3

My dear Friends,

To whom the visitations of Truth have been extended, for your redemption from the world,
and all earthly dependencies:
this is the caution and advice which springs in my mind to you, I trust,
from the movings of that good will, which desires your welfare every way.
Let not human accomplishments, whether natural or acquired, be depended on;
but lay all at the feet of Jesus, and wait for his grace to sanctify,
and make them useful.
It is not knowledge, but obedience, that will be the means, through the Divine blessing,
of rendering acceptable.
We have gifts bestowed upon us, but are not capable by our natural understanding,
to use them to our own advantage, or the good of others; wait therefore,
at the porch of wisdom, and that continually, for wisdom to order all,
to the honour of God, and promotion of your everlasting welfare.
Many are the snares laid for us, by an unwearied enemy,
and many dangers are attending in our earthly pilgrimage;
the more sensible we are of our own weakness, the safer it is for us:
and we are never more in danger than when, in self confidence,
we depend upon our own capacity.
That knowledge which is conceived in the natural part,
is too superficial to be depended on; the knowledge which will be of real advantage,
is come at through great self-denial,
and experience of the humbling operation of divine Truth in the mind;
the increase of which I desire we may experience, as essential to our happiness,
both here and hereafter.

In that love which changes not, I remain your friend,

J+++.+++ K.

2nd Mo. 1772.

Esteemed Friend,

I hope thou wilt not be over thoughtful with regard to the particular exercise attending;
it hath been the lot of many good men to be evil spoken of, and unkindly treated,
who have overcome all the displeasure of their enemies by patiently bearing and forbearing,
till prejudices are removed.
Our religion teaches us to make returns of kindness for evil treatment;
having weaknesses ourselves, there is room to be favourable to the frailties of others;
it is a good disposition which leads us to put the most favourable construction
on the mistakes of such as are offended without a just cause:
not but that I think it allowable to vindicate ourselves when unjustly blamed;
but if our endeavours have not the desired effect,
being conscious of our good intentions,
we must leave the evil to them who have evil thoughts.
I shall only add, that I am with much esteem, thy affectionate friend,

J+++.+++ K.

Colchester, 4th 9 Mo. 1772.

Friend A.

The last time of my being at the place of thy residence
I was desirous of having some conversation with thee,
but missed the opportunity.
Upon considering the nature of thy employ,
I have thought it will require great attention to
avoid doing what may be contrary injustice or equity,
in the many different cases which may come under thy notice.
If we could gain riches almost beyond human calculation by our acting unjustly,
and taking from others what we have no right to,
we might be still accounted as among the poorest of mankind:
for however anxious men are to accumulate wealth,
a time approaches when one hour of the peace and favour of God will be
of more value than all we can gain of the things of this present life;
whether riches, or honour, or pleasure.
These will terminate; but the favour of him that made us, if once obtained,
will last beyond the confines of time.

This is the treasure which men are too little thoughtful about,
though it is of inestimable worth; whilst the other which is so uncertain and transitory,
hath the chief place in their minds,
so as to occasion such endeavours to obtain it as
are not consistent with truth and righteousness,
or that good rule of doing as we would be done by,
and consequently must be without the divine approbation.

I wish we may fill up this little space of time in our several stations,
so as it may be said we lived not in vain;
that the great name of God may be honoured by us,
and the good of our fellow creatures promoted,
by doing them every good which may be in our power,
and not the least injury either in person or property.

I remain thy sincere friend,

J+++.+++ K.

Colchester, 7th 10 Mo. 1772.

Dear Friend E. G.

I sympathize with thee in the present trying dispensation,
through the illness of thy dear wife.
May it please the Lord to support her mind by his good presence,
that submission my take place in all things to his holy will.
He is worthy to be trusted in.
When outward comforts fail, the comforts of his love fails not.

We find by experience that nothing here below is of long continuance,
nor can be long in our possession, whether it be health, or riches, relations,
or friends.
Nor can they afford us unmixed comfort whilst we have them.
Let us endeavour for such temperance in the love of earthly things,
as not to be over much disturbed when they are taken from us.
Yet the ties of nature and affection, and the many infirmities of our own,
keep us from that state of devotedness which we desire to experience.
I hope however we shall be supported by that power
which is never failing to those who confide in it.
I am thy affectionate friend,

J+++.+++ K.

To the Printer of the Ipswich Journal.

The straitened condition of the poor in the present time,
calls for the pity and help of every one that is of ability to afford them relief;
and the disposition which appears in this respect among us is truly commendable.

But whilst we are endeavouring to supply the wants
of our fellow creatures in what relates to the body,
it is to be wished there was more concern to afford them help in things of greater importance,
which are those relating to the welfare of their souls.

There is room to think that the distresses of many, as to outward circumstances,
are occasioned by the improper indulgence of vicious inclinations:
and if they could be persuaded to greater circumspection
and regard to the dictates of piety and virtue,
their happiness and comfort would be more effectually promoted
than by any bodily relief which might be given.

How can it be otherwise than that we should be moved
with compassion for our neighbours and friends,
in whatever condition of life they may be,
when we see the harms attending them by means of self-gratification; that is,
going into the practice of things which suit their inclination,
but which religion forbids.
Many are thus involved in distress, without any prospect of relief,
but through an alteration in conduct.
Can we forbear to call on these and entreat them, before it is too late,
to consider how much their welfare depends on an endeavour to please God,
who takes notice of our ways, and gives to virtue the reward of peace,
as a course displeasing to him is always attended with trouble,
which none of the sons of men can remove;
as also frequently brings upon us disgrace and poverty.

I have observed with concern the great resort there is to houses of public entertainment,
both in town and country, especially of people in low circumstances,
for the sake of liquor and company: here they lay aside both religion and reason,
and proceed to excesses which waste the little stock they have procured by their labour,
bring difficulties on themselves and families,
and at the same time leave such reflections in their
minds as disturb the comforts of life,
and take away the prospect of a happy eternity,
which such only can partake of who live in the fear of God.

What good would come from it,
if magistrates were concerned to discourage such conduct by their personal interference,
as well as by means of the civil officers:
and if those who are in the station of instructors of the
people were to watch over them with Christian care,
and not let their misconduct pass by unnoticed,
but call upon all with the zeal of true pastors,
the lowest as well as those who are high, as to their condition in this life,
without regard to name or profession, as to religion.
God`'s love to mankind is universal,
and such whose minds are under the influence of it
rejoice at every opportunity of doing good;
nor will they think any beneath their notice, or unworthy of their love;
but according to the degree of misery attending their fellow creatures,
be concerned to help them.

J+++.+++ K.

Kelvedon, 27th 7 Mo. 1773.

Dear Aunt,

Though many changes have happened, and many trials and exercises attended us,
since the time of our first acquaintance, I hope they have had this good effect;
to fix our dependance on that power, which first reached to and visited our minds,
in order to gather us to himself,
and make us partakers of a more excellent inheritance than
is to be obtained in the transitory enjoyments of this life.

Surely we have cause to be thankful,
having been thus favoured through the Lord`'s goodness; and I trust he will not leave us,
as it continues to be our care to keep near to him.
Though our troubles are not at an end, as they are sanctified to us,
we shall have to say with one formerly, in a sense of divine help, "`Thou art with me,
thy rod and thy staff comfort me.`"
In what the Lord permits to attend, let us seek for patience, and contentedness.
We want to be more weighty, more refined, and cleansed from impurity of flesh and spirit;
which perhaps is not to be effected without our often enduring the fire.
It cannot be said we are already complete, but are passing on towards perfection;
and whatever tends to promote this work may be accounted a blessing.

I write thus that we may take comfort in our affliction, and not be over much dismayed:
if we obtain stability to our minds it is more than the world can give.
Small disappointments and crosses which frequently occur,
we have need to pass by almost unnoticed, and not be much affected by them,
considering how many things of importance we are called upon to attend to,
as well relating to ourselves as to our dear relations and friends,
in which wisdom is necessary to direct.
I remain thy affectionate kinsman,

J+++.+++ K.

Kelvedon, 30th 10 Mo. 1773.

Dear Friend,

I received thy kind letter of the 25th instant,
which had a tendency to strengthen the friendship subsisting between us:
what thou observest concerning the trials and exercises
we have to meet with in our different allotments,
agrees with my experience: they may prove to our advantage beyond what we can discern.

What is not in our power to remedy, either with regard to ourselves, or others,
is best for us to leave, with this consideration, that greater things are not required,
than there is ability to perform; yet we may be enabled,
through the Divine blessing on our endeavours,
to do much good to our neighbours and friends.
The love which we feel to flow in our hearts, towards mankind in general,
is without doubt, of Divine original; from God the fountain of love,
who always desires the welfare and good of his creatures: and, if any are unhappy,
it is not of him, but because they abide not in him, nor are in him,
in whom is life and happiness.

Such as have tasted of the Lord`'s goodness,
are led to desire others may partake with them;
they feel compassion and pity towards all, let their outward condition, or profession,
as to religion be what it may:
the continuance and increase of this love from which there is a
disposition and ability to help one another is much to be desired.

I am thy affectionate friend,

J+++.+++ K.

26th of 11 Mo. 1773.

Dear Friend,

Being lately in the company of our friend J. F. and
enquiring of him concerning thy welfare,
he informed me, that thou had met with such losses in trade,
by means of the failure of some great merchants,
as to render thee incapable to carry on thy business as usual;
and that thou had intimated to him an intention to remove into England.
I do not undertake to determine what may be best,
but am doubtful whether it is proper for thee, at this time,
to leave the place where thy company is so much wanted towards the support of the society;
which is in so low a state, both as to number and otherwise,
that the removal of one must be sensibly felt.
I desire thou wilt consider this matter deliberately, before thou puts it in execution;
and have the advice of thy friends, which, in a matter of such importance,
may be of great use.

If the difficulty of procuring a livelihood where thou art, is the principal motive;
I hope, in time, some employ will offer, sufficient for the support of thy family,
if not so beneficial as might be wished.
Remember,
it is not the abundance of this world`'s goods that can give us happiness and peace;
but a pious disposition, and the fear of God taking place in our minds, will,
in every condition, be a source of comfort to us,
and sweeten every bitter cup that we have to drink of.

I write thus to thee by way of encouragement: if thy endeavours in times past,
have not succeeded to thy wish, be not over much cast down,
but let it be an inducement to a more close walking with the Lord;
and an endeavour to improve the talents bestowed on thee to the praise of his great name.
Thus his blessing will attend thee; as it always hath such as kept in his fear,
and attended to his requirings: and nothing short of this, is sufficient.

I remain, joined by my wife in kind love to thee, thy wife, and children, with father,
thy affectionate friend,

J+++.+++ K.

1st of 2 Mo. 1774.

Dear Friend,

Thou hast been frequently in my remembrance, with desires for thy welfare;
and an inclination to express the sympathy I have with thee, in thy trials.
Be not discontented with what thou meets with,
but remember we are in a probationary state; not arrived to a state of perfection,
in which there is no room for further exercise.
There may be more in us, which wants to be removed, than we are aware of;
which occasions those painful crosses, which are permitted to attend:
yet if we keep in patience, and humble dependence on the Lord for help,
all will work together for good.
And if we should turn aside, or take too hasty steps, through want of experience,
and not by design to do wrong;
the Father of mercies sees the sincerity of our hearts and pities our weakness;
calling us from the danger, into a path of safety;
sometimes by his corrections in the secret of our minds,
and sometimes by the means of others, whom he indues with wisdom to discern our state.
The Lord`'s dealing with us is for our lasting good,
not in the way which human wisdom points out,
but in a way that brings to nought our wisdom, and knowledge, and strength, as men;
so as to leave us nothing of our own to depend upon.
That this may be our experience, is more to be desired than to be great in this world,
or high in the estimation of men; which all comes to an end:
whereas to witness a growth in the Truth, though the progress we make is slow,
and through many tribulations we enter the kingdom, is laying a foundation of happiness,
which no storms of time can destroy.

But O, the need there is of watchfulness on our part,
in order to steer our course with safety, and avoid the dangers attending, from within,
and without.
That which is intended for our good may prove hurtful to us,
for want of proper application; and what we meet with of seeming evil,
may be of great advantage to us, through a constant desire to be improving in goodness.
There is great occasion for the disciples of Christ,
to keep near to their great Lord and master, and follow his example; who was meek,
and lowly of heart, and overcame by suffering.

These remarks are from a motive of brotherly love,
in which I remain thy affectionate and well-wishing friend,

J+++.+++ K.

Colchester 17th of 2 Mo. 1755.

Dear Friend,

It would afford me pleasure to have any thing to
communicate which might be worth thy acceptance;
but, alas! it hath been my lot to experience such poverty of spirit,
that I have wanted the remembrance and help of my friends,
instead of being fit to help others.
And though this is no new thing with me,
yet I find it hard to bear the absence of Divine favour, and withdrawing of my beloved,
whose presence is the chief cause of comfort to my mind.
It is good for us, however, to be patient in this dispensation,
and in every other trial which may be permitted; we know not what is best for us:
there may be occasion for further refinement,
or we may not be come to that stability in the truth,
which is needful for the condition of favour which the Divine goodness would bring us to.
Though the path we have to walk in is unpleasant to the natural part,
if we submit to the forming of the Lord`'s hand, all will be productive of good.

Thus I mention my experience to thee, in the freedom which true friendship gives;
sometimes there is encouragement afforded,
when it appears we are not alone in those deep probations which are met with,
for the trial of our faith.

I remain thy affectionate friend,

J+++.+++ K.

Colchester, 2nd of 5 Mo. 1775.

Dear Friend,

The account thou gives of thy journey was pleasing to me;
the help we have hitherto experienced in our little services may
be an encouragement to us to persevere in the way of duty,
remembering that it is those who are faithful in
the little that shall be made rulers over much.

If the Lord`'s goodness was not continued to us,
even when we are ready to think ourselves greatly undeserving his regard,
what would become of us?
What cause have we therefore to be thankful, that after all the neglect,
and omission of duty, on our part, the Lord hath not forsaken,
or left us destitute of his mercy!
If he permits affliction to attend, it is for our good, as being what our state requires.
I have often thought so;
and desire to be contented in the various dispensations of his providence;
that all which is contrary to his pure mind may be removed,
and a further degree of holiness experienced; and fitness for his service,
and for an inheritance in that kingdom, into which nothing that is unclean can enter.

As fellow travellers Zionward, let us go on steadily, and not lessen our care,
lest we should be turned aside from the right way,
and lose what hath been obtained by Divine favour;
which through unfaithfulness hath happened to many.

With tenders of kind love, I remain thy affectionate friend,

J+++.+++ K.

Colchester, 27th 5 Mo. 1775.

Dear Cousin,

I would not have thee discouraged because of the afflictions and trials attending:
we all have a share of them, though not in the same way.
If it is not in our power to remove the difficulties, yet by means of prudence,
and a steady conduct, they are made easier.
This, I desire may be our experience, that we may profit by what we meet with,
and become loosened from the love of earthly things, which are of short duration.

It appears to me a great advantage to be preserved in a quiet frame of mind,
in which we can bear contradiction, and not be moved to unsuitable expressions,
or conduct; nor be offended with any who may treat us unkindly.
This is not to be come at by our own strength, but is experienced through Divine help,
by them who seek for it, with a suitable degree of concern.

When we consider how much the good of others depends upon our example and conduct,
it should be an excitement to watchfulness;
lest by any means we hurt them who are depending upon us,
and be as stumbling blocks in the way.
I do not mention this, because I have to charge thee with neglect,
but as an encouragement to perseverance in the way of duty.

I am thy affectionate cousin,

J+++.+++ K.

Colchester 18th 10 Mo. 1775.

Dear Friend, S. E. (of Philadelphia.)

I received thine of the 8th of 7th mo.
last; and can truly say, I sympathize with thee, and the rest of my dear friends,
in the troubles attending.
It will be a great advantage to us, in such times, to experience resignedness,
and to put our trust in the Lord, who never forsakes those who keep near to him,
and cast their care upon him.
When great commotions are in the earth, they are kept in quietness;
and should their trials increase, they are still supported;
and as a rock which is assaulted by winds and waves, still remain unmoved.

In the love of our first acquaintance, I am thy sincere friend,

J+++.+++ K.

Colchester, 12th 12 Mo. 1775.

Dear Friend,

It is not to be wondered at, that many, who attend our religious meetings,
are offended at the simplicity which appears among us; nothing of that show,
and ornament, which is so pleasing to the natural disposition: we must not however,
be discouraged, but still persevere in the practice of what is profitable to us;
it is now, as it hath been formerly,
that those who are concerned to walk in the straight way, which leads to life,
have but few companions.
Not that we conclude all are wrong whose practice is not like ours,
as to the performance of public worship; we doubt not there are many pious persons,
(both men and women,) of other societies,
who are serving God in the sincerity of their minds,
and will be accepted of him according to the light and knowledge they have received.

It is pleasing to hear of thy father, his love is acceptable to us;
having seen many years, and not without a mixture of trouble; I doubt not he is waiting,
with contentedness, for his change.

I remain thy affectionate friend,

J+++.+++ K.

Colchester, 25th 12 Mo. 1775.

Dear Friend,

Though I have not opportunity of seeing thee often, thou art continued in my remembrance;
with an increase of that love, which hath been long subsisting between us,
and I hope will remain to the conclusion of our time here;
and that we shall be favoured to meet,
(when this mortal state is ended) in the realms of undisturbed rest,
where the friendship we have enjoyed in time may be continued world without end.

This helps to alleviate our present affliction,
in an assurance that our great preserver and Saviour,
who hath been with us in six troubles, will not leave us in the seventh,
but still support in affliction of body, which is permitted to attend,
as he hath in affliction of mind; when we have been concerned in our measure,
to labour for the promotion of Truth, and righteousness in the earth.
And what we now experience of the Divine favour, is, without doubt,
a foretaste of those everlasting rewards of obedience and faithfulness,
which are prepared for those who hold fast their integrity to the end.

I salute thee in much affection, and rest thy sincere friend,

J+++.+++ K.

Colchester, 12th of 9 Mo. 1776.

Esteemed Friend H. S.

I take this opportunity to acknowledge the receipt of thy friendly letter,
which was acceptable to me;
and it is my desire we may so witness preservation
in the Truth as to be a comfort to each other.

I am brought to conclude, from what I have tasted of the Lord`'s mercy and goodness,
that it is not limited, as we are apt to think,
but is extended beyond the reach of human understanding,
to those in every tongue and nation who love and fear him; and,
that nothing but his love of righteousness hinders the emanations of his goodness to us.
If this is true, how watchful and circumspect had we need to be in all our conduct,
lest we should miss of his favourable presence, in which there is life,
and at his right hand rivers of pleasure;
and how faithful to all the dictates of his Holy Spirit,
in doing what may be proper for us, and refraining from what is contrary to his will.

Experience shows us, and we are confirmed in it, from the testimony of Holy Scripture,
that a life of self-denial and holiness is called for,
and that it is not he that cries Lord!
Lord! who will be accepted, but those who do his will:
that we may have this in view beyond our outward profession,
is the desire of thy affectionate friend,

J+++.+++ K.

Colchester, 17th 12 Mo. 1776.

To my much esteemed Friend M. B.

To be deprived of our near relations and friends by death
is among the greatest afflictions we have to meet with,
yet we may consider, they are gone but a short time before us;
and that it pleases the Divine wisdom and goodness thus to order,
which shows we have no continuing city here, nor any outward comforts in this life,
fit to be trusted in.
The great concern of our minds, I hope is,
that the good presence of our Saviour may accompany us,
and be our protection in the various exercises and trials attending,
that all may be sanctified to us.

It must be acknowledged that our condition is lonely,
and that the precious cause of Truth, which, according to our measure,
we have been concerned to promote, hath too little place in the minds of some among us;
other concerns which relate to this present life, having prevailed.
Yet we have no room to be discouraged;
there is a rich reward to be experienced by those who labour faithfully,
and make a suitable improvement of the grace bestowed;
these have to partake of the Lord`'s goodness, and can speak well of his name.

I doubt not it is a cause of comfort to thee, in thy declining years,
that thou wast made willing to devote thyself, and all thou had to his service,
who called thee in his mercy, from the sin pleasing pleasures of this life,
to partake of an inheritance that is everlasting.
And now the time may not be far distant,
in which it may please thy good Master to bring to a conclusion of all thy labours;
how pleasant will it be to look back,
and consider the preservation witnessed in many dangers,
and what cause of thankfulness for innumerable mercies bestowed.

I remain thy real friend in the fellowship of the gospel,

J+++.+++ K.

Colchester, 28th 1 Mo. 1777.

Esteemed Friend,

I shall be pleased to hear of thy continued health,
and that thy present undertaking is attended with good success.
There is but little room to expect we shall be free from troubles and difficulties,
in any employ we may undertake: nor will there be any safety for us,
but whilst we are concerned to keep low and humble in our minds,
under a sense of our weakness, seeking for supplies of Divine aid;
which are no less necessary for our preservation in the way of life and peace,
than outward food is necessary for the support of our bodies.

Many dangers attend us in this state of trial: harms, which are thought little of,
nor can be provided against, but as Divine wisdom is our protection and guide:
and never was more occasion for those whose faces are turned towards Zion,
to keep stedfast in their love and obedience to him
that hath visited with his light and truth.
This I desire may be thy experience; that in all thou undertakest,
it may be thy concern to act in such a manner,
as to have the peace of thy mind preserved.
We need not be thoughtful how to please one or another,
when kept in the way of duty to our great Lord and master;
but there is occasion to remember,
that we cannot have his favour in our own way and time;
he is wont to lead his people in a path wherein faith and patience are much exercised.

Perhaps these remarks may be useful to prepare thee
for the new trials which may attend thy condition,
among persons whose converse is not profitable, in a religious sense.
I desire it may be thy endeavour to have no further connection or intimacy with them,
than business requires; nor to engage in any business or employ, however gainful,
which tends to draw from an attendance to the duty of waiting upon God,
whose favour and blessing we constantly stand in need of;
and it if required of us that we seek for it.

I remain thy affectionate friend,

J+++.+++ K.

23rd of 9 Mo. 1777.

Esteemed Friend,

I received thy letter, with the poem, and present of a small book,
for which I am obliged to thee.

As to the passage in C. G--'`s address,
where he recommends "`an attention to the witness of God within, which reproves for evil;
which witness of God is the word of his grace, even the word of life,
which is able to save the soul.`"
This I understand not to mean the scriptures, but that light and truth,
which the Scriptures so largely testify of; even the word of eternal life,
which is the light of men, and shineth in darkness,
and the darkness comprehendeth it not.
This is not the natural conscience, as it is called,
but is that which enlighteneth the conscience; "`Christ in us, the hope of glory.`"
To exalt this is no lessening to the Holy Scriptures,
which may be called the oracles of the Spirit of the most high.
It is proper to regard the streams which flow from the spring,
but let us be mindful of the spring from which they are supplied:
the grace of God through Jesus Christ is to us in our measure,
as it was to the saints of old, the source of good,
in which all terminates which can do us good, in time and eternity:
if we receive benefit from the sacred records,
it is because a blessing from above is experienced, agreeably to the apostles doctrine,
when he says, "`I have planted, and Apollos watered, but God gave the increase.`"
I could wish the attention of the people might be turned to the gift of God,
which is through Jesus Christ our Lord;
then greater improvement would be made in the ways of holiness:
for though we have this treasure in us,
it may do us no more good than the talent bestowed on the unprofitable servant,
spoken of by our Lord.

As we attend to this gift, we shall be led to regard the Holy Scriptures,
which contain the words of holy men, spoken by divine inspiration;
and admire the goodness of the Almighty in bestowing so great a benefit upon us,
whilst many of our fellow creatures are without this advantage:
yet we are not to suppose they are in such darkness
as to have no knowledge of their duty.
God is impartial in his dealings with men; where he bestows much, he requires much.
I doubt not many are in a state of salvation and happiness,
where the outward declaration of the gospel never reached;
and will have to enter the kingdom,
when those who are favoured in a more eminent degree with opportunities of improvement,
for want of faithfulness, will be excluded: our privileges will be of no advantage to us,
but rather tend to increase our condemnation,
if we are not excelling in holiness and every Christian virtue.
The name of a Christian will not secure to us a place in God`'s kingdom,
as the apostle says, "`He is not a Jew that is one outwardly,
neither is that circumcision which is outward, in the flesh,
but he is a Jew which is one inwardly, and circumcision is that of the heart,
in the Spirit, and not in the letter; whose praise is not of men, but of God.`"

Thus we are directed not to place a confidence in outward profession or outward performances,
but still to attend to our great concern, which is, through Divine assistance,
to keep a conscience void of offence towards God, and towards men.
Believe me to be thy real friend,

J+++.+++ K.

Colchester, 18th 2 Mo. 1778.

Dear Friend J. R.

I have no intention to concern myself in the difference subsisting between thee,
and thy formerly intimate friend, which hath been more than once mentioned in my hearing;
but my respect for thee induces me to say,
I am sorry there should be any contending about earthly matters,
(which will soon come to an end with us all) between such who have in view,
and are seeking after, a more lasting inheritance than this life affords.
I remember the counsel of our great Lord is, "`If any man will sue thee at the law,
and take away thy coat, let him have thy cloak also.`"
This advice is to be noticed as a caution not to contend with any,
much less with my friend, (whom I love), about outward property,
rather choosing to suffer loss than strive to get what he aims to take from me.
This will be a means of promoting peace, and obtaining that which will remain with us,
and be our comfort when all strife and contention comes to an end:
this is what I wish for an increase of,
that the Prince of Peace may establish his kingdom in us,
and whatever tends to disturb his government may be removed.

Whilst some are striving to get the mastery,
let us be overcoming in a more excellent way, by returning good for evil,
love for hatred, blessing for reviling; and the peace of him,
in whose hand are all outward blessings and comforts, and all inward consolations,
will be our reward, and make up to us all we part with or lose, for his name`'s sake;
that is, for the sake of peace,
and that his kingdom of love may be exalted in our hearts, and in the hearts of others.

I aim not to say much on the subject; but my advice is, not to be wanting on thy part,
to terminate a difference which may be hurtful to thyself, and thy friend;
as likewise disturb the peace of the society.
There is a short way of ending disputes between brethren, which I would recommend,
and hope always to take, which is, to submit to what is insisted on,
though apparently to my loss, rather than to contend.
It is better to have it said of us, that we are sufferers for peace sake,
than that strife is continued because we will not be contented to suffer;
when we consider how much our Redeemer suffered for us,
it should reconcile (to us) the sufferings we have to meet with.

Having given these hints, which have been as a concern on my mind,
I remain thy affectionate friend,

J+++.+++ K.

My dear Friend W. J.

The frequent remembrance I have of thee,
and sympathy which attends my mind in thy present affliction, occasion these few lines,
to express my concern that thou mayst be supported and helped
to an humble acquiescence in the Divine will.

Experience shows there is but little of what we enjoy in this present life,
that is at our disposal; wife or children, father or mother, brother or sister:
even the most precious outward gifts are only lent us for our use and comfort,
till it pleases the Divine goodness to permit a change.
It is therefore to be desired,
that we may have our minds redeemed from earthly dependencies,
enjoying what is bestowed upon us, with thankfulness to the giver,
and submission to the dispensations of his Providence
whenever he sees meet to take it from us.
When outward comforts are removed, we are brought to seek our comfort in the Lord,
who is our chiefest good.

But it is a great matter to come to a state of resignation,
being disengaged from the concerns of time,
and yet discharging the offices of love to our families and friends,
and all with whom we are connected: to have this effected,
we must not depend on natural ability or wisdom,
nor anything less than renewed Divine assistance,
which is obtained through obedience to the discoveries of duty.

I am with much affection, in the bond of true friendship, thy real friend,

J+++.+++ K.

Colchester, 24th of 4th mo.
1778.

Dear Friend,

It is comfortable to remember how we were preserved in unity during our late engagement.
I hope it may be said, without boasting,
the Lord`'s good presence was often manifested for our strength and enlargement;
in which we experienced an harmony of spirit,
and were made fellow-labourers in the gospel of our Lord Jesus Christ.
May this remain without any diminution.
Yea, it will remain, as we abide in the Truth,
and our love increase in that which is above all the changeable things of this life.
But we find there is need of a steady attention to duty;
our comfort in each other being increased or lessened,
as we are stedfast in our obedience to the call of our great Master,
or deviate from his way, and commands: all the outward rules which may be formed by man,
will prove ineffectual to procure, or preserve this unity,
if there is a departure in heart from the love of God,
which is the bond of true fellowship.

It is always necessary that we should seek to promote this love in ourselves and others,
through the operation of the Spirit of Christ;
then there will be an agreement in outward circumstances on a good bottom, being,
(to use the apostle`'s words) "`No more strangers and foreigners,
but fellow citizens with the saints, and of the household of God;
built upon the foundation of the apostles and prophets,
Jesus Christ himself being the chief corner stone; in whom all the building,
fitly framed together, groweth unto a holy temple in the Lord,
in whom you are also builded together for an habitation of God, through the Spirit.`"

No greater good can attend us as a society, or individuals,
than an increase of unity from this principle,
and nothing short of it can preserve us living to the Lord`'s praise.
With desires for our mutual welfare, I remain thy affectionate friend,

J+++.+++ K.

Colchester, 21st 7th mo.
1779

Esteemed Friend W. P.

Thy remarks on some past occurrences in life,
as also the present favourable situation in which thou art placed,
through a gracious Providence, are very suitable.
It calls for thankfulness,
that we are measurably preserved from the evils that are in the world,
and provided with a plenty of outward accommodations,
so that we can pass our time free from the cares which attend straitened circumstances.

It is true, we are not without our troubles and exercises,
nor have any room to expect we shall be free from them in this militant state;
if we are preserved so as to fill up our stations in life with propriety,
and have the peace of our minds preserved, there will be no room to complain.
Though our names, as to a religious profession, may be different,
there is but one way to the kingdom of rest and peace, which is the fear of God.
This makes of one church all who are dispersed through this habitable earth,
of whatever tongue or country.

And there are many in distant lands, concerning whom we have but little knowledge,
who are of Christ`'s church, and will be admitted into his kingdom.

Thy friendly disposition leads me to say thus much, and that I am in sincerity,
thy affectionate friend,

J+++.+++ K.
