== Chapter 4

[.signed-section-context-open]
1779.

[.salutation]
Dear Friend,

Thy letters have always been acceptable to my cousin;
and are at this time a comfort to her in her lonesome condition;
being deprived of her most affectionate companion.

I am inclined to add to what was said in my former letter.
If the religion which is of Christ, hath place in our minds,
we cannot but love one another; not only our friends and those who love us,
but our enemies.
So far from destroying or hurting each other,
we shall wait for an opportunity of promoting the welfare of all,
who are within our reach;
and be sorry it is not in our power to do more good both to the souls
and bodies of those who are in the same state of being with ourselves.

This is the nature of that religion which we have
to learn from the example of our great Lord,
and the operation of his Spirit in our minds;
that brings out of all contention and strife, into the peaceable kingdom,
where there is no hurting or destroying.
Who can but wish for the coming of those times, spoken of by the Prophet,
by way of metaphor, when "`the wolf shall dwell with the lamb,
and the leopard lie down with the kid.
They shall not hurt nor destroy in all my holy mountain,
for the earth shall be full of the knowledge of the Lord, as the waters cover the sea.`"

How great would be the advantages to us if this disposition prevailed;
but alas! there hath another spirit gone forth, and hath prevailed,
to the disturbance of the peace of mankind,
which hath been the cause of strife and contention in families and societies,
and led to acts of great violence; when one nation riseth up against another,
to the destruction of many who were not engaged in the contest.
Sad to think of! that beings, whose state is such,
as requires all the assistance they can give to each other
towards fitting for a kingdom of purity and holiness,
which they are called to partake of, when time here shall be no more,
should be angry one with another, and contend for the enjoyment of earthly things,
which they cannot long be in possession of.

I shall only say further that I am, with due respect, thy affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 8th 10 Mo. 1779.

[.salutation]
Dear Friend,

My regard for thee is such,
that it would give me trouble to hear of thy doing otherwise than well,
I mean in a religious sense.
Of the harms we are liable to receive, when an uneasy dissatisfied temper prevails;
we shall be apt to think ourselves unkindly used, and be offended,
when no real cause is given.
It hath been the occasion of great disturbance in the church,
and hurt many religiously disposed persons; I have seen instances of it,
and lamented the loss some of my acquaintance have sustained,
without having it in my power to help them;
because by long indulgence of a discontented mind,
they have lost sight of their right guide;
and are less and less able to bear contradiction,
or to have anything go in a way that meets not with their approbation.
But when I say this, I am led to hope for better things for my friend,
and that the harms which, have attended others will be as cautions to him and me:
that we shall learn more and more to bear disappointments and contradictions,
and prefer the peace of the church to our own claims, giving them up without hesitation,
rather than have any disturbance on our account.

I would not be tedious by repeating the same advice,
which my desire for thy good might occasion; thou wilt perceive what I have in view;
that it is, to have thee give up what may appear to thee reasonable,
for the sake of peace; and, not in this or any other matter,
to admit of self-will to prevail, in which nothing good is to be effected,
either to ourselves or others.

[.signed-section-closing]
I conclude thy affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 26th 8 Mo. 1780.

[.salutation]
Respected Friend,

I am inclined to mention to thee, from a motive of friendship,
that thy present situation appears to me to be attended with great danger.
The nature of the business thou art engaged in being
such as exposes thee to a variety of company;
it seems impossible for thee to avoid being hurt, unless thou behaves, in all respects,
agreeable to the character of a religious person;
which requires a greater share of piety to support, in such a place,
than I fear thou or I are endued with.
I wish therefore, thou mayst not venture on things which are above thy strength,
nor place thyself in a difficult situation from choice,
in which others have been of necessity, and were not able to stand.

If all the advantages which are in prospect might be obtained,
and thou should miss of a portion in the blessed Truth, who can make thee amends?
When I say this, I consider others of my dear friends in the place of thy residence,
whose prosperity I am desirous of.
I mean not as to wordly advantages, or by an increase of outward riches,
but in those things which tend to promote their everlasting welfare.
A low condition in this world is frequently attended with safety,
when those who are favoured with affluence suffer loss,
and lose their share in the happiness of a better world.

I would further say,
that as our own partial judgment cannot inform us what situation we are fit for,
nor what trials we are likely to endure,
there is need of great caution in our proceeding;
always requesting we may be favoured with direction from above,
lest we should take that for our good which may prove hurtful to us.

[.signed-section-closing]
I remain thy affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 28th 9 Mo. 1780.

[.salutation]
Dear Cousin E. G.

Though we have to meet with trials and exercises which are hard to bear,
yet they may be of greater advantage to us than we can at present conceive.
I desire therefore we may endeavour to be contented,
and still wait for the renewing of that help to our
minds which hath been our support in times past.

When we have deviated from the law of our Divine Master,
and not attended to his direction and call, as we ought,
in great mercy he hath forgiven our offences,
and restored to us the joy of his salvation.
And though these times of favour are not frequent,
yet if we can but hope he hath not forsaken us, it will be safe to wait upon him,
not seeking for great things,
nor desiring more than to be preserved in obedience to the Lord`'s requirings,
and walking in the way of his commandments.

I fear thou hast too good an opinion of me.
If I have made some little progress in the way of life, it is well:
I cannot be sufficiently thankful that I was persuaded
to accept of the offers of Divine love:
but this I may say, that I find as much occasion as ever to be upon my guard,
and watchful against the enemy of my peace.
Let us consider ourselves as fellow travellers, who have left their native country,
and must be contented with the difficulties of the way,
if we would have the crown which is prepared for those who faint not.

[.signed-section-closing]
I remain thy affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 15th 5 Mo. 1781.

[.salutation]
Esteemed Friend,

I could be glad to say something which might be acceptable to thee,
but we are not always alike fit to write upon common occasions,
much less on subjects of religion, which are the most interesting.
I shall therefore only express my concurrence with
what is said in the forepart of thy letter,
of the unsuitableness of violence or compulsion in matters of religion.

It hath been usual for such who have had the power in their hands,
to endeavour to force others to conform to what they thought to be right,
as to an outward profession of religion, or acts of religious worship,
and under a pretence of zeal for the truth.
But this is certain, at least in my apprehension,
that there is no force or compulsion in the religion of Christ.
We are not compelled to do right by any inward force of truth upon our minds,
nor is it proper for us to use any force upon others.
Persuasion only is in our province, and even by this,
no good can be done without the Divine blessing attends our endeavours;
it is God only who can persuade Japheth to dwell in the tents of Shem.

There is nothing but love in the holy religion of Jesus Christ, which we profess:
the fruits of the spirit, as the apostle says, are "`love, joy, peace, long suffering,
gentleness, goodness.`"
Those who dwell in God, dwell in love, which never hurts.
What we read of the unkind treatment which some in this nation, and in others,
have met with,
only because they did not agree in their religious
sentiments with those who were in power,
should be a caution to us not to suffer the same disposition to prevail, in any degree.
It was not Christ`'s spirit which led to this, nor will it ever lead to such conduct.
When we endeavour to force to a compliance with what we think is right,
then it may be said the wrath of man appears,
which never worketh the righteousness of God.

When I consider the hurt which comes from what may be called persecution,
I am led to desire we may be preserved from it, in whatever shape it may appear;
but we are men, and liable to the same frailties which have attended others,
and may err in this way, if we are not endued with a better mind than our own:
the infallibility is not in us, but in God alone;
who always directs right as far as we are directed by him.

As thou observes,
it would be well if people were disposed to use their
endeavours to practise the truths of religion,
instead of disputing about them: this would be the way to bring to an agreement;
for it is not by a consent of the judgment only, that we become truly united in Christ,
but by doing what be commands, by which we manifest our love to him.
And after all the high profession which is made,
those only are his disciples who walk in obedience to the dictates of his blessed Spirit,
in a path of self-denial and holiness; without which none can see the Lord.

Having made these remarks in the freedom of friendship, as they occurred to me,
I subscribe myself thy affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 27th of 7 Mo. 1781.

[.salutation]
Esteemed Friend W. P.

It is true,
there are no hopes nor joys like those which the true Christian hath at times to experience,
as the reward of a sincere endeavour to please him,
who hath promised not to leave his people without comfort
even in times of greatest weakness and infirmity.

We are come thus far on our journey,
with a degree of safety beyond many of our fellow creatures,
for which we have cause to be humbly thankful.
It hath not been our own arm which hath saved us,
nor our own wisdom which hath directed us, but an invisible Almighty power,
and all-wise Providence, which hath led us along,
and guided our feet in the way of life and salvation;
and not only provided for the safety of our minds, and saved us from harms,
which our own imprudence was apt to lead us into,
but bestowed upon us a sufficiency of outward accommodations,
by which we are relieved from cares that are met
with by those who are in straitened circumstances.
What have we so much to desire,
as that the remaining part of our time may be as prosperous as that which is past:
that the fruit of our past labour may not be lost by any wrong course we may take:
that though our progress in the heavenly journey is slow, it may be safe:
and if we should at any time be out of the right course (through weakness,
or want of attention) we may happily return into it again, and be restored?

As to the small present of Barclay`'s Apology,
I desire no other return than that it is acceptable to thee;
we approve of the account he gives of our principles:
it would be well for us as a society,
if our conduct in general agreed with the profession we make;
and would be the most effectual way to convince others of the truth of them.
But alas! what will the best principles and the best profession do for us,
if we do not experience them to actuate our minds, so as to produce good conduct?
It is true, as the apostle says, "`Faith without works is dead.`"
The most certain sign of a right faith are good works;
these are looked for by our fellow creatures, and, which is more material,
by our great Creator; who after the favours bestowed upon us,
is expecting the returns of love and obedience,
which can be no way so fully manifested as by keeping his commandments; as he hath said,
"`If ye know these things, happy are ye if ye do them.`"

I am with true esteem and affection, thy friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 11th of 10 Mo. 1781.

[.salutation]
Esteemed Friend,

Thy kind letter of the 31st 8 mo.
hath not been unnoticed by our cousin;
it is a comfort to her to be remembered by her friends, and she desires to remember them;
indeed it may be said, we stand in need of the mutual assistance of each other;
especially in a time when the infirmities of age are come upon us.
And whilst a right disposition prevails,
we shall be willing to assist in every way that we are capable of,
and rejoice to have it in our power to contribute to the welfare of our friends,
not only as to earthly accommodations,
but in those things which relate to the comfort and peace of our minds,
which are the most deserving our notice:
not but there are cares of the present life which must be attended to,
and are conducive to our good;
yet they should be in subordination to the most important business of all,
which is to prepare for our great change,
by having such dispositions increased in our minds, as may bring nearer to him,
who is the fountain of all joy and happiness;
from whose favour (if we are so happy as to attain it in
this life) we shall not be separated in the life to come.
On the contrary, if our joy should be in that which separates from him, here,
how can we expect to be admitted into his presence hereafter;
when no alteration is made but what comes from putting off this tenement of clay?
A state of alienation from God and Christ in this life,
is like to be a state of alienation from him forever.

When this is considered, how watchful over our conduct had we need to be;
lest by any means we should render ourselves unfit
for an acquaintance with him whilst here,
and an admittance into the assembly of the just, in the realms of bliss,
to enjoy his favour hereafter.

It is true, we are apt to deviate from the path of peace,
and to have our comfort interrupted by unfaithfulness to him,
who admits no misconduct in us to pass unreproved;
nor is there any room for us to wish to be free from his reproofs,
who wounds that he may heal, and corrects with tenderness,
that we may be restored to his favour.
When the good effects of his chastisements are considered, we may well say,
"`Let not thy hand spare, O Lord, nor thine eye pity,
till that which thou hast a controversy with is removed.`"

I conclude with kind respect to thee and thy niece, in which my wife joins,
thy affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 27th 11 Mo. 1781.

[.salutation]
Esteemed Friend,

Thy sentiments with regard to choosing members of parliament, are like mine;
I think the present mode is attended with inconvenience,
and hurtful to the morals of the people in a great degree;
which makes me cautious of being much concerned in it.

[.signed-section-closing]
I remain thy affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
1781.

[.salutation]
Esteemed Friend,

I am desirous thou mayst be preserved from complying with
that which might not afford thee comfort in future.

It is but little we can do towards promoting the
cause of truth and righteousness in the earth;
and if this little should be omitted,
we shall not have that peace which is more to be desired than all worldly enjoyments.
I would not be understood from what I said on the subject of tithes,
that I place so much stress upon our refusal to pay them,
as to suppose it will be productive of peace, and a means of obtaining the Divine favour,
if at the same time,
our conduct in other respects is not becoming the profession we make:
it will be so far otherwise, that a discredit will come from it, both to ourselves,
and to the society of which we profess to be members.
But I wish we may be coming up, every way, in the faithful discharge of our duty:
and if it is proper in the present time,
for us to bear a testimony to the freedom and purity of a gospel ministry,
which we wish to see promoted, let us do it in simplicity:
our being unanimous will add weight to the testimony we have to bear.
Yet I do not think it proper to use any means which may be considered as compulsory,
to bring my friends to act as I may think is right;
their joining with me should be from a convincement
in their minds of the propriety of the testimony;
and then, neither the fear of losing the esteem of men, nor of any outward loss,
will occasion an active compliance (with such demands);
we shall be afraid of withholding that light which is given us, not only for our benefit,
but to help others.

We are not the only people who have been concerned to bear
testimony to the excellency of the gospel dispensation,
above the legal; in this respect,
there have been those in former times who appeared as witnesses to the Truth;
and I make no doubt there will be some in future times who
will be made as standard bearers to the nations,
and a means of promoting that reformation which is
wanted among the professors of the Christian name.

There is a reformation in the church of England from many
of the gross superstitions and errors of the Romish church,
(which is no small favour to this nation):
but we must see there is occasion for a further reformation,
and that many things remain which are unsuitable to the Christian dispensation:
this in particular, of tithes, which were appointed among the Jews,
and of Divine institution;
but we believe Christ is come to introduce a more spiritual religion,
and to lead from the ceremonies of it to the substance.

These few hints I find freedom to make,
which the friendship between us I trust will admit of:
as it is our intention to do right, let us be willing to help one another;
that after passing a few days in this state of trial we
may be received into the favour of our great master,
and become partakers in a kingdom,
where no such cares as we now experience will be known.

In the desire of this, for thee, and all my friends, I remain thy affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 22nd of 1 Mo. 1782.

[.salutation]
Esteemed Friend,

The remarks in thy letter meet with my approbation,
especially those which relate to Christian charity;
dealing with others as we would be dealt with ourselves;
giving the same liberty to our neighbour and friend,
to satisfy his conscience towards God, that we desire to have ourselves;
however much we may prefer the way we have been brought up in,
we must think charitably of one another.
In every religious society, if people have only the outward form,
it is to be feared they will be in no better state
than the foolish virgins mentioned in the parable,
who had lamps without oil.

The consideration of this may shew us how little
dependence is to be had upon rites and ceremonies;
and how improper it is to praise any for the observance of them,
when the life and conversation is not answerable to the profession;
or to think amiss of such who do not practise them,
when their behaviour shows they are influenced by that good spirit,
which is the substance of types and forms; and whenever ceremonies are useful,
it is to lead us to this.
I would not have us think hardly one of another,
on account of the use or disuse of these things:
such as use them should be cautious of laying an improper stress upon them;
and such who do not think it necessary to continue the use of them,
should endeavour to show, by lives of piety and holiness,
that they are partakers of the spiritual religion which they profess.

This I may further add concerning toleration,
and the liberty we should give to those who dissent from us:
it is contrary to our principles, as a religious society, to persecute,
or trouble others who may differ from us in their sentiments:
we wish to give the same liberty that we desire to have.
I hope nothing like persecution will appear among ourselves,
or towards those who may not be of the same profession with us:
no good proselytes are made by force; if we gain any to the way we approve,
it must be by the strength of love,
and the good works which we are enabled to perform by Divine assistance.

But when I write thus, I am not insensible of the weakness of human nature;
and considering how some good men have erred in the warmth
of zeal for the promotion of what they thought to be right,
having proceeded to acts of violence and force against those who differed from them,
I am led to fear least anything of this kind should appear in me, or any of my friends,
towards such as we may think are out of the way.

I conclude in much respect and esteem, thy affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
28th 1 Mo. 1782;

My friend may not expect to be remembered in this manner by one, whose advice,
in times past, he hath too much passed by unnoticed;
but where there is a real friendship,
we are not easily prevented from using endeavours to help those who stand in need of it.
This is my motive in writing to thee;
not to propose a method of removing the difficulties which at present attend,
as to thy outward affairs,
but to remind thee of the way to be restored to the
favour of him who is greater than man;
which thou hast lost by manifold and grievous offences; and wilt forever lose,
unless there should be a sincere repentance for thy outgoings, and an amendment of life.

There is a Power on high which governs his creation,
and hath affixed rewards to those who fear him,
and punishments to those who violate his precepts: many have experienced this,
whose lives were made comfortable and honourable,
whilst they preferred the favour of the Almighty; and others,
who chose to please themselves, and walked in forbidden paths,
reaped the fruit of their doings, which was sorrow and trouble in this life;
and what is more than all to be dreaded, a separation hereafter from him,
whose continual controversy is with evil, and all the workers of iniquity.

Oh! how well will it be, if thou should come to a sense of thy loss; and seek,
with unfeigned sorrow, to recover the path which thou hast so far strayed from,
that hardly any remains of it are to be discovered.
Yet, through the mercy of a gracious Saviour,
I believe it is possible to have it restored;
and as thou turns to him with a penitent heart, he will receive thee as a prodigal son,
who hath wandered far from his house;
and give thee a portion with those who love and fear him.

I would not have thee slight what I say; they are words of soberness and truth,
and deserve thy notice.
Yet unless there is a sense in thy mind of the impropriety of thy past conduct,
and a sorrow, which the Lord only gives; all that I may say, or any other of thy friends,
will prove ineffectual for thy reformation:
but I wish and pray that these endeavours may prove beneficial to thee;
and a means of helping to bring back from the paths of vice and destruction,
to the paths of virtue and peace.

[.signed-section-closing]
I am thy well-wishing friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 10th 5 Mo. 1782.

[.salutation]
Esteemed Friend,

As thou observest, there is hardly any people, even in the most distant lands,
who are destitute of religious apprehensions of a supreme power;
and whose minds are not so far enlightened as to distinguish between good and evil;
but in many, it is to be feared, the impressions of Truth are very faint,
if not wholly obliterated, by a long course of wicked practices.
As the tendency of wrong conduct is to darken the mind,
so good conduct tends to enlighten it;
and in this way we may account for that darkness and insensibility which is so prevalent
in the minds of many in this and other nations professing the name of Christ;
as well as among those who have not yet heard of him.

Of what advantage will it be to hear of Christ,
and to make an outward profession of belief in him,
if we do not experience his love and fear to prevail in our hearts,
so as to regulate our conduct) and change our dispositions?
If our knowledge and apprehension is only literal,
and we live in the gratification of sensual appetites,
it cannot be said that we receive the benefit of the Christian dispensation;
nor shall we be in a better state than those whose privileges are far inferior.
The religion which will be of real advantage to us, is that of the heart,
which leads to the practice of whatever is good and praise worthy,
in our thoughts and words, in our life and conversation.
And as this is not from human ability, but from the help of the Spirit of Christ,
we have no room to claim any merit to ourselves, but should attribute all to him,
who is the beginner and finisher of our faith.

It is an unspeakable benefit to have the use of the Holy Scriptures;
and that we can discern the excellency of the truths contained in them,
and taste the sweetness of their doctrine.
And this comes to pass,
as we are measurably enlightened by the same spirit which gave them forth; that is,
the inward revelation of God`'s Spirit, which is not ceased,
but remains as the blessing of the Lord`'s people through all generations.
And the more it is waited for and expected,
the larger share of it we may hope to experience.

[.signed-section-closing]
Thy affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 7th Mo. 20th 1782.

[.salutation]
Dear Aunt,

If it should be our lot to meet with that which may grieve and afflict us,
let us not be discouraged:
it hath been the experience of the right-minded in former times,
and will be their experience in times to come.

We have a high priest who can be touched with the feeling of our infirmities,
who hath compassion on the ignorant, and them that are out of the way.
Let us endeavour to please him, that he may be our friend and comfort in declining age;
as he hath been in the more early part of our days,
when the gracious visitation of heaven was towards us.
How were our hearts engaged by this love!
What shall we render for the benefits then received,
and for all the benefits since received, to the present time?
None have greater cause to be thankful than we.
It must be allowed we have not been so stedfast in our love and obedience,
as we should have been; which hath caused at times,
a separation between us and the beloved of our souls.
But O! that we may be concerned to renew our acquaintance with him;
and may not be contented in any deviation from what we see to be right,
however small it may be, until we have obtained reconciliation with him.

If I am not mistaken, our exercises in the Christian warfare are not unlike:
we do not find, nor have ever found, the path to happiness so easy,
as to be passed along without obstructions: we meet with many,
from our own weakness and frailty, as also from the frailties of others.
But why should we complain?
Here is the trial of our patience, and other Christian virtues:
if we did not meet with troubles, how would these virtues appear in us?
The greater our trials are,
(as we are enabled to bear the chastisements of the Lord) the more we shall be refined,
and fitted to join with those who have trod the path before us,
and through tribulation entered the kingdom.

Affliction tends to promote our happiness; I desire we may be reconciled to it,
and take the cup we have to drink of with cheerfulness,
as members of Christ`'s mystical body, whose fellowship consists in suffering,
(as well as in enjoyment, 1 Cor. 12:26)

[.signed-section-closing]
I remain thy affectionate nephew,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 8th of 10 Mo. 1782.

[.salutation]
Esteemed Friend,

When we consider the condition of many of our fellow creatures and countrymen,
who are now engaged in the tumults of war by sea and land,
destroying one another for the sake of gaining that
which will be of no advantage to the soul,
it must occasion mourning for their sake:
at the same time there is cause of thankfulness,
that we are so far favoured as to be exempt from it, in a calm retreat;
having our minds better disposed than to attempt the destruction, or even hurt,
of our enemies, whom we wish to overcome by kindness, rather than to injure them.
This is suitable to the religion of Christ,
and is the great privilege of the Christian dispensation,
of which the more we come ta partake, the more peaceable we shall be in our disposition;
and experience to be fulfilled what is spoken of
by the prophet concerning the times of peace,
when nation should not lift up sword against nation, nor should they learn war any more.

Though we may not live to see this prevail among men universally,
it is a comfort to be sensible of such a spirit breathing love and good will to all;
and let us pray for the increase of it.
With regard to those who are acting differently from
that which I think is right in this respect,
I am not disposed to be uncharitable.
Till we come to receive that peaceable spirit, which, in the extent of it,
bring to the end of wars, it is not likely we should be principled against them:
the great judge of the earth will deal with us righteously,
according to the knowledge we have received, and light imparted.

The Christian name will not give us the privileges of the Christian religion.
Till we come to experience the work of religion in our minds,
we shall be strangers to the nature of it; and until then,
no wonder if our conduct is like that of those who know not, nor never heard of Christ.

I shall only add, that I am with much esteem, thy affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 25th 11 Mo. 1782.

[.salutation]
Much esteemed Friend,

Our cousin is now arrived at a greater age than either her father or mother,
and much beyond the age of her brothers, who were taken away in the prime of life:
how uncertain to us is the period of our lives! we may wonder that we,
have lived to this time, such is the tenderness of our frame.
I approve of what a certain writer says,
"`That there is some other hand which twines the thread of life, than that of nature;
and we do not err, if we say it is the hand of God.`"
It will be an advantage to us to have our dependence on him,
beyond all the supports of nature or constitution;
and to ask for his help to spend our time so as we may please him:
thus our death will not be premature whenever it happens.
Such who have lived but a short time,
by virtuous lives may be said to have fulfilled a long time:
and though the righteous be prevented by death, yet shall he be in rest;
for honourable age is not that which standeth in length of time,
nor that is measured by number of years; but wisdom is the grey hair unto men,
and an unspotted life is old age.

Thy suitable remarks have led me to say thus much in reply;
there is a pleasure to religious minds in conversing together on such matters.
As travellers we may tell one another what we have met with in our journey;
and sometimes give such cautions as may serve to warn of dangers.
I wish there was more of this sort of conversation among people, with proper seriousness;
but, I fear, instead of it,
they are chiefly conversing about their earthly possessions and temporal gratifications,
which last but a short time;
and are not enough concerned to enquire after an heavenly inheritance,
which lasts forever; of which, the less we enjoy here,
the less fit we are likely to be to enjoy it hereafter,
I do not mean that the concerns of this life should be wholly neglected;
our state is such as requires some attention to what
relates to the accommodation of our bodies,
as likewise charity leads us to assist others;
but all should be under a suitable subordination to the principal concern,
which is the welfare of our minds; so that, whilst we are employed in outward affairs,
we have need to consider, that this is not the main business,
though necessary and allowable in its place.
Thus, through Divine assistance,
we may be kept from all improper solicitude concerning outward events,
and have our minds still attending to the most important event; which is,
to pass our time here,
so as it may be ended with a well-grounded hope of a happy futurity.

I would not be tedious, but shall add,
that I much desire the good opinion thou hast conceived of our Society may be continued:
there are many religious persons among us who are of exemplary conduct,
but we have too many of another sort, which is an occasion of grief to their friends.
It is not however to be wondered at if some are taking undue liberties,
from the influence of example, for want of a religious disposition; without this,
our profession will do no more for us,
than the profession of other religious societies will do for them.
The church of Christ is not confined to societies or nations,
but is constituted of those in every society and nation who fear God and work righteousness.

I conclude with true regard and esteem, thy affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
12th of 9 Mo. 1782.

As I frequently miss of seeing my respected friend W. J. at the quarterly meeting,
the love there is between us, I think, will admit of my saying;
it gives me concern to find,
that he is so circumstanced as not to be at liberty
to meet with his friends on these occasions,
when his company is much wanted.

I consider our stay in this life is short and uncertain!
that we are not different in this respect from our forefathers,
who had their time, and are now no longer in mutability.
We have Our time, and are passing away likewise, and shall be succeeded by others:
there is nothing so much to be desired as that we may fill up our stations in the church,
and in our families, with propriety; so as to promote, in our small measure,
the Cause of truth and righteousness,
and leave a good example to those who may succeed us.
We have lived to see great vacancies made by the removal of elders from among us;
and those who remain are chiefly of the rising generation, who want to be watched over;
and if neglected may sustain great loss.
Such who are in the station of overseers in the church will be liable to rebuke,
if they should be careless of their charge, and more mindful of their own affairs,
and how they may build up their own houses,
than for the religious welfare of their friends.

I speak this by way of caution to my dear friend, who I believe would be made useful,
if he was willing to be devoted to his great master`'s service.
I must own it is a time of painful exercise to the true-hearted
labourers in the Lord`'s vineyard but they must not be discouraged,
nor be impatient, when things do not succeed as they may wish:
great advantage comes from contradiction, and being tried with inward poverty;
it is thus we learn to be contented, in the changes to which we are subject,
as good soldiers of Jesus Christ.
And there is great occasion for such in the present time;
who are not concerned to please themselves, but to please him who hath called them,
and are contented to be in the lowest station,
so that they may be of use to promote their master`'s cause.

No advantage can be obtained like that of being preserved in the faithful discharge
of our duty to him who hath mercifully visited us with his light and truth,
when we were strangers to him.
This hath been our call to service; without which,
what inducement should we have had to forsake the love of this world?
and with it,
what encouragement do we want to make us willing to use our endeavours to serve him,
who is such a rich rewarder?

Having said thus much, from a motive of true love, I remain thy affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 19th 2 Mo. 1783.

If I remember right,
I mentioned in my former letter receiving thy kind
present of the American Farmer`'s Letters.
I have read it, and am pleased with some of the remarks on our society,
which are not unsuitable: his account of the country,
and inhabitants of America in general, may likewise be proper.
This I am assured of, the better people are in that or any other country,
and the more the fear of God prevails among them to regulate their lives,
and preserve them from the many wicked practices to which mankind is liable,
the more happy and peaceable they will be in this life,
and the more happy in the life to come.

I am of opinion that our welfare more depends upon good conduct,
which is produced through the work of God`'s spirit in our minds,
than upon the increase of earthly riches or greatness, or outward liberty; which,
if not made a right use of, proves hurtful to individuals and nations:
it is now as true as ever, that "`Righteousness exalteth a nation,
but sin is a shame to any people.`"

Those who are true friends to their country, will rejoice to see a revival of piety,
and with it a reformation of manners; by which means the favour of Heaven,
which we have so largely experienced, may be continued to us,
and his chastisement averted.

[.signed-section-closing]
I am thy sincere friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 25th 2 Mo. 1783.

[.salutation]
Esteemed Friend,

I do not think, with some whom thou mentionest, that we are capable,
by the strength of human wisdom, without the assistance of God`'s holy spirit,
to steer our course with safety through the paths of this life, so as to please God,
and be prepared for an everlasting inheritance with him in glory.
If my own experience informs me right, it is far otherwise:
without the Divine assistance, we shall soon miss our way, stumble and fall,
let our knowledge or abilities, as men, be ever so great.
Men and women are made good, and kept so, by a Divine influence;
which is no less than the Spirit of Christ, which all of us must experience,
whether we will own it or not.
This is more essential to our happiness than the learning of schools,
and will fit us for the duties of our calling beyond human arts and sciences.
Not that I disapprove of schools for the instruction of youth;
I think them of great use when properly conducted;
but I have known some excellent persons who had very little advantage from education,
yet were conspicuous for their good understanding and good conduct;
having been instructed in a school which is above
the schools and universities of this world,
where all must learn who become true Christians.

I was acquainted with Dr. John Fothergill, and had a great respect for him,
as a useful member of our society, and a pious man.
He was a great promoter of the school at Ackworth, in Yorkshire,
which is intended for the use of the poor: the children are instructed in reading,
writing, and arithmetic, and great regard is had to their morals:
the number at this time is about three hundred.

[.signed-section-closing]
I am thy affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 23rd 4 Mo. 1783.

[.salutation]
Respected Friend,

I herewith send thee some short memoirs of William Sewel,
which I have collected at thy request.
Other circumstances might be added by those who knew him in his native country,
but what I have inserted may be depended upon, and if they are of use to thee,
it will give me pleasure, as a means, in some degree,
of preserving the memory of a valuable person.

[.signed-section-closing]
From thy Friend,

[.signed-section-signature]
J+++.+++ K.

William Sewel, for his great industry in publishing several valuable works of his own,
and translating others of good account into the low Dutch tongue,
may be placed among the most useful men of his time.
He was born in Holland about the year 1654, of reputable parents: his father,
Jacob Williamson Sewel, was a surgeon in Amsterdam, descended from an English family:
both his father and mother joined in society with the people called Quakers,
and their son was educated in this way, and remained among them to the time of his death.

He was a man of learning, having considerable knowledge of several European languages,
as well as of the Latin: two of his works are,
A History of the Rise and Progress of the People called Quakers,
which he compiled in the low Dutch, and published at Amsterdam in one vol.
folio, 1717.
Soon after, having translated it into English, it was printed in London,
in the same form, and is in good esteem,
as one of the best and most authentic accounts of this people which hath been published.

His other principal performance is a Dictionary of English and low Dutch, in quarto.

He also published a Grammar of the Dutch tongue, and a Grammar of the Dutch and English,
both printed in 12mo.

He was employed in translating several pretty large works into the low Dutch,
as Josephus`'s History of the Jews; Kennet`'s Antiquities of Rome; Penn`'s No Cross,
No Crown; Burnet`'s History of the Reformation in England, abridged: besides others,
probably which are not come to my knowledge.
It appears by a collection of his letters, in Latin,
(which are copied in a book of his own hand writing) that
he corresponded with several persons of note in England;
as William Penn, John Penington, Theo.
Eccleston, etc. as likewise some learned persons in his own country.

His style was clear and solid, such as shewed him to be a man of good understanding.
He died in Amsterdam in 1720, aged 66.

[.signed-section-context-open]
Colchester, 2nd of 5 Mo. 1783.

[.salutation]
Esteemed Friend,

I meet with several things in thy letter which afford me pleasure.
When the sentiments of friends are so much alike, to express them to each other,
is a means of renewing our friendship,
besides the satisfaction it gives to meet with those who are convinced of the truth:
but we have need to remember, that to think right will not be sufficient,
if we do not act accordingly: the servant who knows his master`'s will and does it not,
(as our Saviour hath declared) shall be beaten with many stripes;
it will therefore be a great advantage to us to continue
our endeavours to walk answerably to the light received;
that so, we may be Christians in nature as well as by name.

The character of a Christian, as thou observes, is so engaging,
that many would possess it, if it was to be obtained with a wish;
but it is so far otherwise,
that those who obtain it must seek it with unwearied diligence,
and consider it as a privilege which may be come at, and may be lost again;
not that we are sufficient of ourselves for this great work:
"`For by Grace ye are saved,`" (the apostle saith) "`through Faith,
and that not of yourselves, it is the Gift of God.`"
Yet we are not to remain idle, expecting all to be done for us without our concurrence;
if so, where would there be room for any reward of such who are faithful,
or punishment of the disobedient?
I remain thy affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
13th of 11 Mo. 1783.

[.salutation]
Respected Friend,

I have to request thou wilt be so kind as to deliver the enclosed book to thy neighbour,
and at the same time present my kind love to him;
his civil behaviour when we were at your town is not forgotten.
It gives us pleasure to meet with sober people, of whatever society they may be,
though our profession, and way of public worship, be somewhat different;
the way to heaven and happiness is one in all professions,
and the more closely we keep to this way, which is a way of holiness,
the more we shall be united, and have fellowship one with another.
There is occasion to look beyond outward forms,
(which are only useful as they bring us to the substance) and to
seek chiefly to have our minds made conformable to the Divine image,
by being renewed in righteousness and holiness.

It is the saying of the apostle,
that "`In Jesus Christ neither circumcision availeth anything, nor uncircumcision,
but faith, which worketh by love.`"
And if this was aimed at by the professors of Christianity,
they would be brought to love one another: there is no room for unkindness or animosity,
whilst we are under the influence of God`'s spirit!
nor shall we have high thoughts of ourselves,
or despise others, who may appear to be below us; but love and pity all men,
and do them good, as far as in our power, our enemies as well as our friends.

This is the nature of true Christianity; and I may add,
the more it hath place in our minds,
the more we shall be drawn from a dependence on our own works,
and come to place our trust in the grace and favour of Jesus Christ our Saviour,
through whom all our works that are acceptable must be performed.

With tenders of kind love, I remain thy sincere friend,

[.signed-section-signature]
J+++.+++ K.
