== Chapter 5

[.signed-section-context-open]
Colchester 11th of 11 Mo. 1783.

[.salutation]
Dear Friend,

Though we have had to meet with many buffetings from the enemy of our peace,
and our faith and hope hath been greatly tried, yet we have not been forsaken,
so as to fall a prey to him; but in the exercise of patience,
and humble waiting on the Lord for his help, we gained experience; and thus,
afflictions have brought forth the peaceable fruits of righteousness,
and proved to our advantage.

I desire it may be our concern to keep near the truth, and abide in it,
where the destroyer cannot come!
Here is our safety, and the safety of all the Lord`'s people,
in this day of mourning for the deviations and falling away,
in the society of which we are members--deviations,
which no human power is able to restore; nor can we remedy the loss sustained,
either in ourselves or others,
but as we are strengthened through the operation of the
same spirit which first gathered us to be a people.
No rules which we may have will be effectual without this to help us.--How necessary
it is for us to continue our care to wait for this help in our lonely situations.

And though we do not experience such good effects of our labour,
for the help of our friends, as might be wished, let us not be discouraged;
we shall reap in due time, if we faint not.

[.signed-section-closing]
I am thy affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.salutation]
Dear Friend,

It will not be long before all the troubles of this life will be past,
and that which was a cause of grief will no longer disturb our quiet:
let us therefore endeavour to be contented in the dispensations of Divine goodness,
and unerring wisdom; having this belief, that all is permitted for wise ends;
and that what is painful may not be without advantages, though hid from our view.
With these considerations I am sometimes comforted;
and should be glad if I was able to say something that might be comfortable to my friends.
If things are not as we could wish, I consider they might be worse;
and though the power which prevails in the world, is great, bringing ruin upon many,
it is not unlimited,
nor can it hurt those who are kept in the love and fear of the Almighty;
as the apostle declares, "`Greater is he that is in you, than he that is in the world.`"
There is room to think, that for want of keeping near to his power many miss their way,
and sustain great loss; for whom I mourn in secret,
and at the same time have to remember my weakness,
and the danger I am in of receiving hurt, either from my own frailty,
or from the force of example.

I conclude with the tenders of true love and esteem, thy affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.letter-heading]
To the Printers of the Chelmsford Chronicle.

[.salutation]
Respected Friends,

It is not from a desire to busy myself in other people`'s concerns,
but from a motive of friendship, that I take the liberty to mention,
it hath given me pain to see pieces of poetry inserted in your paper,
which have a tendency to promote a licentiousness to which
people are too much disposed in the present time,
to their own hurt, as well as that of their families, and the community in general.

There is rather occasion to put them in mind of what relates to their duty,
as Christians, that each may fill up his station with propriety in the fear of God,
than to awaken such sentiments as tend to lessen
the esteem we ought to have for what is honourable,
of good report, and praiseworthy.
Whilst you endeavour to suit the taste of readers, who are disposed to levity,
there should be care taken not to hurt the great interests of religion and virtue,
which are valuable above all other concerns; and I may venture to say,
that those who regard them in all parts of their conduct, are the most happy people;
and generally speaking, succeed the best in the things of this world.

Though I use this freedom in speaking my thoughts, I am your real friend and well-wisher,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 1st of 1 Mo. 1784.

[.salutation]
Dear Friend J. V.

We have with us several friends from America upon a religious visit to these parts;
as John Pemberton, William Matthews, Robert Valentine, Nicholas Walne.
It is a satisfaction that the intercourse between us and that country
is more open than it had been for some time past;
I wish the friendship may long continue:
strife and discord is very hurtful in families and societies.
If people were under the government of that peaceable
religion which Christ is the author of,
it may be safely said,
there would not be such contests as are now apparent in many nations;
instead of violence, and injurious treatment of our neighbours and friends,
we should be distinguished by acts of benevolence
and kindness towards all with whom we might be concerned.

Though we can do but little to promote this happy disposition among the people,
let us seek for the increase of it in ourselves,
which will tend to promote our own comfort,
and we shall not be accessory towards the hurt which comes from
the unchristian like proceedings of many in the present time.

[.signed-section-closing]
I am thy sincere friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 30th 4 Mo. 1784.

[.salutation]
Esteemed Friend,

We are not always alike qualified to express sentiments
which a religious disposition might dictate,
and yet our love is not lessened towards each other.
I must own it is a comfortable experience to ourselves,
and frequently a benefit to others,
when we can speak with a proper apprehension of the wonderful works of Almighty goodness,
which appear in the earth we inhabit:
it may lead to a more earnest endeavour to serve him who deals thus bountifully with us;
to whom we can make no returns so acceptable as those of obedience
to the laws of righteousness and holiness impressed upon our minds;
by which we come to be formed to his image, to glorify him whilst here,
and to be admitted into his presence hereafter.

For want of this, that part which should be the most beautiful,
and reflect the greatest praise to its maker, is the most defaced,
and without that beauty and harmony which adorns every other part of creation.
I mean poor unhappy man, who deviates from the path of truth,
and brings many evils upon himself by irregular conduct, is a trouble to himself,
and other parts of the creation placed in subjection to him.
This is not the intention of boundless Goodness and Mercy;
which would have all men to be happy.
But as disorders come by our absence from God,
so they will remain until we return to him, in whom our happiness consists.
It may be said of too many, they have left him who is the fountain of living waters;
and hewn to themselves broken cisterns, which will hold no water.

With regard to the troubles we have met with; if properly applied,
they would make us better; but if not regarded as they ought,
by producing a greater moderation and temperance,
other troubles may succeed greater than we have known;
as was experienced formerly by a backsliding people, who grew worse,
though they were often corrected and smitten, until the time of their recovery was past.

The productions of nature, as thou observest,
begin to show themselves again in the fields and woods, after a long time of winter.
They will be the more acceptable and received with the more gratitude,
by considerate minds.
When the favours of the Almighty are renewed to us,
we have occasion to say with one formerly,
"`What shall I render to the Lord for all his benefits?`"

These acknowledgements are acceptable as they proceed from true devotion,
and are accompanied with a concern to serve God in a life of piety and virtue;
but without this,
they avail but little before him who sees the heart and knows our most secret thoughts,
as well as takes notice of our conduct.

The works of Providence are wonderful, and often to be admired in silence,
when we can go but a little way as to the knowledge of them;
it is enough for us to see the outlines of them,
and to be assured they are all made in wisdom,
and will be productive of good to them who love and fear God.

In concluding these few lines, I subscribe myself thy affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 26th 7 Mo. 1784.

[.salutation]
Esteemed Friend,

We join with thee in acknowledgments to the great author of our being,
for many favours received, of which we are sensible.
But I have thought, there are still greater favours which we know not so much of;
even those dispensations which are painful to us, may be accounted blessings,
when the salutary effects are considered.
It may be owing to the troubles and disappointments we have met with in different ways,
that we have obtained some good qualities which are the occasion of comfort to us:
and we can see there is need of further improvement,
which some further exercise may produce;
therefore it is best to be contented in what is permitted to attend us.
A religious mind will however always be thankful for blessings received,
and not think lightly of them, nor make a wrong use of them.

The beautiful appearance of nature will raise our admiration;
and if what we see of the outward creation is so wonderful,
what must be the Maker of these things?
How far beyond our knowledge and praise!
Yet he is pleased to accept the grateful tributes of his poor weak creatures,
who are placed in the midst of these stupendous works,
and intended to partake of a glory and happiness suitable
to the state of spirits which are to live forever,
in the enjoyment of more excellent pleasures than this world can afford.
What an advantage it will be to us to be prepared, by suitable discipline,
for the enjoyment of this good, in a future state.

As thou observest, agreement in sentiment is the strength of friendship;
and it is pleasing to meet with a friend to whom we can
impart our thoughts without fear of contradiction.
Yet there is sometimes a disagreement, even between good men,
which my be without any hurt, as there is a proper condescension to each other.
A benefit may come from it, by the exercise of some Christian virtues,
which could not appear without it.

With regard to the liberty of our minds;
what we experience in ourselves and see in others, confirms to us,
that the great author of our being hath thought fit to give freedom to the human mind,
so that we are not compelled to do evil, any more than to do good.
The course we take is not by force, but persuasion;
though it must be allowed that education and example will
have great influence upon us to determine our conduct.
By long continuance in a good way, it will become more easy;
as it will be difficult if not impossible, humanly speaking,
for such as have been long in an evil course, to leave it.
Habits may be contracted which are not without great difficulty laid aside; it is true,
the evil which comes upon us is from the misuse of the liberty we enjoy;
but it is not possible to avoid making a wrong use of this liberty,
unless we are assisted by a supernatural power.
We are frail creatures, more apt to do wrong than right,
and have occasion often to pray for his help who is the promised Saviour of his people.
The more we are concerned to seek for this in the secret of our minds,
(where it is to be found) the better we shall succeed in our choice of what is right,
and be enabled to shun what is wrong.
For want of an application to this help, so many do amiss,
as not having power without it to do right.
It is therefore an unspeakable benefit to us to be sensible of our weakness,
and from whom our help comes.

To correct our passions, so that they may not carry us to any excess,
and to keep our inclinations within due bounds,
is the most important business we have to be concerned in,
but this requires constant watchfulness, and continual help from above.

Having said thus much on a serious subject, and increased the length of my letter,
I shall conclude with tenders of kind love, thy sincere friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 7th 9 Mo. 1784.

[.salutation]
Dear Friend,

We spent about three weeks in Holland; were two first days at Amsterdam;
and had two meetings at Rotterdam.
A pretty many sober people attended,
and the meetings at both places were to our satisfaction.

The number of friends in Amsterdam is now very small, about six persons,
who may be reckoned of the society, with a few children.
None remain in Rotterdam; but there is a meetinghouse, which we found useful.
Some English merchants were at the meetings, and several preachers,
of different societies; who understanding the English,
there was not occasion for our being assisted by an interpreter, as in Amsterdam;
and having some knowledge of the Dutch,
I endeavoured to express myself to the people in their own language,
and found improvement in it, during the little time of our stay.

We met with religious persons in divers places, whom we visited in their houses;
and had our journey been further extended, should have found more,
to whom our message would have been acceptable.
If I am not mistaken, there are many seeking people in divers parts of this country,
and likewise in Germany,
who have a good understanding of what is essential to their everlasting welfare,
and are not contented with the bare form and ceremonies of religion.

After giving thee this short account of my journey, I have not more to add,
except kind love, in which I remain thy affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 1st of 11 Mo. 1784.

[.salutation]
Esteemed Friend,

I fear it will happen to the Dutch, as it hath happened,
to kingdoms and states before them,
who had obtained great riches by means of commerce and trade;
that they will forget their former condition,
and whilst they are complaining of other nations, for being too assuming and high,
will be too much exalted themselves, which may occasion great troubles.
I only mention this as my opinion; I have great love for them,
and it will give me pleasure to hear of their welfare; but I consider,
it is with nations as with families and individuals,
when they deviate from rules of temperance and moderation,
and are not kept in the fear of the Almighty, that a declension comes,
and finally a fall from that state which they had not made a proper use of.

[.signed-section-closing]
I remain thy sincere friend,

[.signed-section-signature]
J+++.+++ K.

[.salutation]
My esteemed Friend S. T.

I have frequently had to remember the comfortable opportunities we had together,
through the Lord`'s goodness; wherein a harmony of spirit was experienced,
which tended to promote the cause in which we were engaged.
Though a laborious exercise was required at times on our own account,
as well as of others, I trust it was not without its advantage.
Such is the state of things in the present time that the sensible mind cannot
be without mourning for the great falling away which appears among us as a society.

Our petition had need to be to him who is able to help,
even our Lord and Saviour Jesus Christ,
that he would be with us to help and preserve in this day of tidal,
so that we may not lose our integrity, nor be less concerned for our own good,
nor for the good of others than we have been in times past.
If we should see one fall on the right hand, and another on the left;
and great alterations happen in families and meetings; Truth is unchangeable,
and wilt be a means of preservation to those who abide in it.
It is for want of "`keeping near the Truth, and walking in it as obedient children,
that loss hath been sustained,
and not because the Truth is less efficacious than in times past.

I make these remarks in the same freedom wherein we conversed together,
when our sentiments were so much alike,
as to bring us near to each other in that love which many waters cannot quench,
nor time nor space diminish: in this we find comfort, whether we are together,
or it is ordered, in the Lord`'s good providence, that we are far separated.
It is well to be contented in all the dispensations
of unerring goodness who knows what is best for us:
and, as we have often found,
that which is contrary to our inclination hath proved to our advantage,
beyond the more pleasing circumstances of our lives;
and if we had not met with frequent trials, and close exercises,
we should not have had the experience, nor stability,
which is needful for our support in the fresh conflicts and painful occurrences of life.
There is no room to complain of the long continuance, nor sharpness of trials,
which are for our refinement, and to make us fit to help others,
who may be in danger of sustaining loss for want of the like experience.

If we should be so happy as to fill up our stations in the church,
consistent with the Divine will,
and continue our course steadfastly in the fear of the Lord,
there will be a reward for us, with all the Lord`'s faithful people,
which will abundantly make amends.

In the hope of this I remain thy true friend, and fellow-labourer,
and companion in the service of the Truth,
which is more precious to us than worldly considerations.

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 11th of 1 Mo. 1785.

[.salutation]
Dear Friend G. D.

Thou hast been frequently in my remembrance, with an increasing regard and esteem;
which makes me desire to hear from thee again, when thy leisure will admit:
Though we cannot remove difficulties, which attend us in our various stations,
we may encourage one another by a friendly intercourse,
which makes me value the correspondence of my friends;
it affords me comfort to hear from them, and to be informed of their welfare;
especially in these times of difficulty and danger.
As we have room to hope through the Lord`'s goodness,
our feet have been turned into a path of safety.
What is there so much to be desired, as that we may be helped to persevere in it?
Because we know the crown is to be received at the end of the race,
and that all the labour of former times may be lost,
if we are sot concerned to hold fast our integrity,
and approve ourselves faithful to him who hath called us.

It may be a comfort to remember, in every dispensation,
that what we meet with always tends to our good, when rightly improved.
If it was not for repeated exercises,
we should not be prepared to fill our stations in the house,
nor be qualified to speak a word of comfort to such as mourn, or, by good counsel,
direct the feet of those who are ready to stray.
Our trials are not in vain;
the fruits of them will be profitable beyond what we at present can discern,
and an excellent reward received when they shall all be over.

I am with the tenders of true love,
thy affectionate friend and companion in the labour and fellowship of the gospel,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 20th 1 Mo. 1785.

[.salutation]
Respected Cousin,

It is pleasant to hear of thy cousin being so well recovered of his hurt;
we are liable to meet with hurts to our bodies, which are a trial of patience;
we are likewise in danger of receiving hurts to our minds,
by the prevalence of evil inclinations, which we have more occasion to be afraid of,
than of outward hurt: bodily harms we may desire to be preserved from,
yet we see they are permitted to attend the best as well as the worst of men:
but the harms which come to our minds are from our own misconduct;
for want of a due attention to that grace which is given for our instruction and preservation;
so that when we do amiss, we acknowledge our faults, and say, we should not have done so.
The hurt which comes from sin, is the greatest of all hurt which can attend us.

What thou sayest on the present new taxes is agreeable to my judgment;
it becomes us to meet them in a spirit of patience;
considering the loss we may sustain by this means, as a slight correction,
compared with what is deserved for manifold transgression.
And if the troubles which are permitted to come upon us have not the desired effect,
there is room to expect some greater will attend, in a different way.

The state of religious societies, not excepting our own, is to be lamented;
I fear there is a great decay of Christian piety, for want of which,
people are taking undue liberties, to their great hurt,
and the loss of that strength and stability which
comes from a humble walking in the fear of the Lord.

[.signed-section-closing]
I am thy affectionate cousin,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 29th 1 Mo.

[.salutation]
Much esteemed Friend,

If we may form an idea of God`'s love from what is felt in our minds,
we may conclude that nothing but love can proceed from him to his creation;
and that all the unhappiness attending us, comes from counteracting his laws,
and being estranged from him by wicked works.
To say that a certain number of his rational creatures
are ordained by him to everlasting misery,
and a certain number chosen to be happy, without any regard to their conduct,
is contrary to the Divine attributes, and the whole tenour of the Holy Scriptures;
though some things are met with which exceed the human understanding,
they do not contradict our sense of Truth, and of what is lovely and excellent.
I therefore do not approve of this doctrine; but rather wish to feel my heart enlarged,
so as to be always willing to help my friends and all mankind,
as far as may lie in my power; considering them as the objects of Divine compassion,
and by no means ordained to be lost.

It is true, though we experience this love to all,
we cannot be united with such who act inconsistent with their own peace and happiness;
but are sorrowful on their account, and reserve our friendship,
and more close connection, for those who are better disposed.

Much hath been said to lessen, and bring into disesteem, the Christian religion,
and the excellent writings which inform us of it;
but it stands upon a better foundation than to be
hurt by what evil men may urge against it;
and would be a great benefit to mankind,
was there a disposition to listen to its dictates, and obey its laws.

This I am certain of, we should use no violence towards others,
because they differ from us in sentiment,
or their mode of worship is not the same with ours;
but be willing to allow to others the liberty we desire to have ourselves.
There have been too many instances of intolerance among Christians:
even those who professed to be reformed from the errors of an apostate church,
have been unkind to such as differed from them in some outward circumstances,
endeavouring to compel them to a uniformity.
I hope it will not be in our society: whenever it is, we shall go from our principles,
and not be actuated by that benevolent mind, which is the cause or harmony among us,
by which we are united beyond what outward creeds and confessions could effect.

Having made these remarks, in reply to what I met with in thy letter,
I shall mention my thoughts on the favourable condition as to outward circumstances,
in which we are placed.
I consider it as no small benefit in the decline of life,
to have sufficient for our accommodation,
and something to spare for the relief of our friends and neighbours,
who are in straightened circumstances.
Whom shall we thank for this favour but our Almighty friend and benefactor,
by whose providence we have been protected from our earliest time;
and by the assistance of whose grace we have been enabled to choose the
path which tends to promote our comfort and happiness in this world,
as also in that which is to come.
There is nothing we have more to desire,
than that we may be preserved to the end of our time in this way.

As we have found occasion for watchfulness in time past,
we shall still find it to be necessary; our youth hath had its trials,
as likewise our middle age; and now we are further advanced in years,
there will be trials attending us; so that it may be said,
our life is filled with exercises and trials,
and that we always stand in need of the Divine assistance
to be joined with our feeble endeavours.

[.signed-section-closing]
I remain thy affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 17th 4 Mo. 1785

[.salutation]
Esteemed Friend,

The long continued cold weather we had in the winter
puts me in mind of the privileges we enjoy,
above many of our fellow creatures;
which I hope will tend to excite grateful acknowledgments to the providence of the Almighty,
who hath thus furnished us with accommodations,
so that we have been screened from the inclemency of the weather,
and were not under the necessity of exposing ourselves, early and late,
for the sake of a maintenance.

It was a pinching time to many poor people,
and had it not been for the kind assistance of some humane persons,
their distress must have been greater.
We have room to think there hath always been poor, and that there always will be:
some made so by their own misconduct and want of care;
others through the pressure of sickness and age:
these are indeed the greatest objects (of compassion),
though the other sort are not to be excluded from our notice and help.

The present temperate weather is very acceptable, and is what we have wished for,
as a comfort to our weak frame; but to have the mind preserved in a temperate condition,
free from storms which come from the indulgence of irregular desires,
is a still greater advantage, and what we have occasion to pray for.
We may leave the disposal of events, as to outward circumstances,
to the great author of nature,
and endeavour to be contented in what is permitted to attend,
knowing that outward suffering cannot hurt the mind, which is depending upon God,
and preserved in his fear.
There are few, if any, who have known the benefit of a peaceful mind,
but would rather lose all the comforts of this life, than be deprived of it.
The case of David, when great sorrows were upon him for his transgressions,
was harder than that of Job; who was under the afflicting hand of the Almighty,
as a trial upon him, in which he had not the rebukes of a wounded conscience,
but was preserved in patience.
It helps to reconcile troubles to us,
when we can consider they are not come by means of our own wilful neglect or disobedience,
but in the permission of a Providence,
which frequently brings forth good out of temporal evil.

I am inclined to say further,
concerning that pernicious doctrine of election and reprobation which some have imbibed.
It is matter of wonder that there should be in the human mind such a sentiment,
concerning the great Sovereign of the universe, and Saviour of men,
as that he hath ordained a certain number of his rational creatures to everlasting punishment,
without any fault of theirs, by which they might deserve it.
Not having a liberty to do right, I see not how they can be punished for doing wrong:
but as this is not to be reconciled with the attributes of justice, goodness, and love,
it is no principle for us to approve of.
Let us wish to feel our hearts more enlarged in love,
which we think comes from God towards our brethren,
considering them as objects of his compassion;
and if any are in a reprobate state it is not by any ordination of God,
but through a resistance of his grace, which was offered to them, but rejected,
till hardness followed.

As to the disposition of forgiving such as injure us,
which Christ our Lord recommended both by his example and doctrine,
it may be placed among the choicest of Christian virtues;
it brings peace where it prevails, and prevents mischief to, families and societies:
when we see the contrary prevailing,
it is because the Christian spirit is not enough prevailing
among those who make profession of this excellent religion.
We know no outward profession, either among those who are called Roman Catholics,
or Protestants, will entitle to the character of true Christians;
it is only as the spirit of Christ influences our minds,
and effects a change of our dispositions, that we become his true followers.

Thus I am apt to express my thoughts; if I have said the same in former letters,
I hope it will be excused.
I am thy affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
19th 7th Mo. 1785.

[.salutation]
Esteemed Friend,

What thou sayest concerning the writer of certain poems is remarkable.
I am apt to think it only means, that he uses no outward forms of prayer;
it is not possible that any pious person can be without
a disposition to ask for the Divine assistance:
though it is not always necessary to make use of words to express our wants,
we shall not be without secret petitions, which will be available with the Almighty,
and more efficacious than the most excellent forms that can be used,
without a due sense of want.

A religious person is so far from not using prayer,
that his life is very much filled up with it; as breathing is the support of the body,
so prayer is the support of the mind: the soul cannot live to God without prayer,
any more than we can live in this world without breathing.
I allow there may be some singular cases:
but even where but little or no devotion appears,
these may not be so much without prayer as we apprehend.
However, we are under the notice of a good and gracious Benefactor,
who sees the frame of our minds,
and requires not more of us than he will enable to perform.

I conclude with the tenders of kind love, thy sincere friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 10th 12 Mo. 1785.

[.salutation]
Dear Cousin J. M.

When I heard of thy being returned from thy late journey, and of thy continued weakness,
I was inclined to write a few lines,
wishing to be further informed concerning thy health: as likewise to express my desire,
that this affliction may be so sanctified to thee,
as to bring to a nearer acquaintance with that good
which is the comfort of the sincere-hearted,
even the fellowship of our Lord and Saviour Jesus Christ.

It helps to reconcile bodily weakness and ailments, when we consider,
thus it pleaseth the Divine goodness to deal with us;
and that afflictions are permitted to attend for wise purposes,
which we cannot comprehend; it maybe for our refinement,
and making more fit for an heavenly inheritance.
If we experience help to cast our care upon the Lord, it will be a great favour:
though his hand should be heavy upon us, there is room to trust in his goodness,
because he always hears the petitions of his people, that put their trust in him:
these have to say,
it is good to wait the Lord`'s time for help and deliverance in affliction,
from which none are free however privileged, as to earthly accommodations.

Those whose minds are softened by frequent exercises,
and made sensible of their weakness, are disposed to sympathize with the afflicted,
whether in body or mind.
And this, I trust, is the motive of my writing at this time to my respected cousin,
of whose recovery I shall be glad to hear, if consistent with the Divine will.

[.signed-section-closing]
I am thy affectionate cousin,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester.

[.salutation]
Respected Friend,

When the meeting`'s conclusion upon any business which may be under consideration,
is not as we might wish, there must be the exercise of patience;
we must not be offended with our friends because
they do not wholly agree with us in sentiment.
I have no doubt it is best for us to bear with each other in this state of weakness,
and sacrifice our own ease and pleasure to the good of the society,
in which we shall have a reward from him, who hath taught us by his example,
not to make returns of unkindness to such as may displease us.

I join thee in thy desire for the continuance of peace and harmony;
but we should consider, this is not to be maintained effectually,
but by our attending to the practice of what we know to be right:
our fellowship does not wholly depend on a conformity to outward rules
and orders which may be established for the government of our society,
but upon obedience to the laws of truth in our minds; as the apostle says,
"`If we walk in the light, as God is in the light, we have fellowship one with another,
and the blood of Jesus Christ, his Son, cleanseth us from all sin.`"
It is of great consequence to us to walk in the way which
tends to promote our interest in the Divine favour,
as well as to preserve the harmony which should be among brethren.
I am inclined to add, that if the late proceeding is not such as thou approves of, yet,
if the intention is good (as I hope it is) let us judge favourably of it.

I remain with true regard, thy affectionate well-wishing friend,

[.signed-section-signature]
J+++.+++ K.

[.salutation]
Dear Friend,

I am inclined to send thee my cordial salutation in the love of Christ,
which I feel at times to enlarge my heart towards my friends and neighbours,
and all mankind; and this I wish for an increase of,
more than for an increase of earthly riches.

Though we are far separated,
it is not any space of sea or land that can terminate
a friendship which hath taken its rise,
and is continued, in harmony of spirit, without views of outward advantage:
the remarks in thy letter meet with my concurrence; I am ready to say, What remains,
but that we endeavour, with the help of Divine grace,
to live up to the light and knowledge received?
It is a great blessing to know the truth,
but to live up to that knowledge is a benefit so necessary,
that without it we may still be as unprofitable servants, who knowing the master`'s will,
have not prepared ourselves to do it.

[.signed-section-closing]
From thy true friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 3rd 10 Mo. 1785.

[.salutation]
Esteemed Friend,

It gives us pleasure to be informed of thy late journey; whenever we take such journeys,
or even if they are much shorter,
and are favoured to return in safety to our habitations,
there is cause of thankfulness to the good Providence
by which we have been preserved and protected.
It is also to be considered as an additional blessing
to have a comfortable dwelling to return to,
and a family preserved, in a good degree, from the disturbances of irregular conduct.
This, I trust, is our experience; yet we have no room to expect to be free from troubles,
which are the attendants of all, even the best of men, often for the sake of others,
in whose sorrows they partake.

It is found true that there are no joys here, free from a mixture of grief;
when all we meet with becomes sweetened to us,
so that we can humbly submit to the Divine will,
and take the cup allotted us without complaint, it will be a happy experience.

I subscribe myself as formerly, thy affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 30th 11 Mo. 1785.

[.salutation]
Dear Friend J. R.

Though we have to meet with many changes, and are often in afflictions,
inward and outward, let us put our trust in the Lord our God, who is unchangeable.
It is a comfort to consider that the power from whence our troubles come, is limited;
but the power by which we are preserved is unlimited.
And, as the prophet had to declare, the Lord will be with us whilst we be with him,
if we seek him he will be found of us; it is only as we forsake him,
that he will forsake us: so that there is room for all to be encouraged,
who are disposed to serve him, let their circumstance or condition be as it may.
None are so high as not to stand in need of the Divine regard,
nor any so low as to be unnoticed by him, who is the father of the fatherless,
and as a husband to the widow.
My writing thus is contrary to my expectation,
though on a subject which often employs my thoughts, and I desire it may be so;
but after all,
I am afraid lest the cares and concerns of this life (if not on my own account,
yet on the account of others) should take up my attention too much.
This concern is also attending thy mind, when a variety of engagements are met with,
relating to the provision of outward things,
as well as thy care for the good of those to whom thou art allied.
There is need of this, in order to wait for supplies of Divine aid,
and not to depend upon our own strength.
It is seen, by the hurt some have received, how liable we are to miss our way;
even the best are liable to fall from a good state, unless a watchfulness is continued:
the loss which may be sustained comes gradually; little harms make way for great harms,
till at length some have come to make shipwreck of faith, and a good conscience.

With desires for thy welfare and preservation,
and that true comfort may attend thee in times of affliction,
from the giver of all comfort, I remain thy affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 27th 3 Mo. 1786.

[.salutation]
Esteemed Friend,

Thy reflections often occasion thoughts which are useful,
as well as afford encouragement in concerns which lie heavy upon me,
whilst I am using endeavours to serve some of my friends,
who appear to be in want of assistance:
I find myself not able to bear great encumbrances, and therefore must use prudence,
and act according to my strength.

I approve of thy intention to withdraw from business;
some employ is necessary for the sake of health, both of body and mind;
but in the concluding part of life it is proper to have a time of recess,
as much as can well be, from the cares of this world, which must soon be left altogether.
I doubt not there will be some useful employ to fill up thy vacant time,
to thy own satisfaction, and the benefit of thy friends.

There is comfort in reflecting on past deliverances,
and commemorating in our minds the merciful dealings of a gracious Saviour;
who hath been with us from the early part of life, and supported to a peaceful retreat.
If we are not without our troubles, let us remember they are good for us.
It is to be desired that we may take the cup of affliction, and say with the good man,
the Lord gave, and he hath taken away; blessed be the name of the Lord!

[.signed-section-closing]
I am thy sincere friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 27th 10 Mo. 1786.

[.salutation]
Dear Aunt,

We wish thy son comfort in his change of condition; I have no doubt it will be so,
as he is preserved in the Lord`'s fear and counsel;
without this there is no true comfort to be known in any condition,
and with it every state, whether married or unmarried, is sanctified to us.
He is now entering into new concerns, which call for attention:
his good example will have an influence towards promoting
the peace and welfare of his near connection,
and as they walk together with care,
the discharge of religious duty being their principal concern,
that blessing will attend which maketh truly rich, and adds no sorrow with it,
which is my desire for them more than for an increase of earthly treasure.

[.signed-section-closing]
I remain thy affectionate kinsman,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 15th of 11 Mo. 1786.

[.salutation]
Esteemed Friend W. P.

As thou observest, health of body is a great blessing,
it requires some care and skill to make a right use of it:
I think they act unwisely who indulge themselves in a luxurious way of living,
which may drive from their thoughts the shortness and uncertainty of their time,
but can never give true happiness to the mind:
health and strength are given for a better purpose.
We shall fill up our ranks in society in a far more consistent manner,
when we endeavour to promote the happiness of our
fellow creatures at the expense of our own ease;
not supposing we live for ourselves only, but for the good of others,
who are in such a condition as to want help.
If people were thus disposed there would not be so many foolish diversions contrived;
which are below the dignity of man; other ways of spending our time (which is precious,
and of great importance) more rational, and more conducive to health of body and mind,
would be adopted.
But many things are not as we could wish; we can see what is wrong, but to regulate this,
and keep all in due order, is the work which of ourselves we are not able to accomplish.
Let us be earnest in our petitions to the Father of Mercies, and God of all Grace;
that he would help us through the intercession of his beloved son, Jesus Christ,
our great high Priest and Mediator,
to steer our course with safety in the midst of dangers and difficulties,
which attend us in this probationary state; so that we may have to say, in our measure,
with the apostle, "`I have fought a good fight, I have finished my course,
I have kept the faith, henceforth there is laid up for me a crown of righteousness,
which the Lord, the righteous Judge, shall give me in that day.`"

This is a most desirable experience,
to be preferred before all the riches and greatness of a transitory world,
but not to be expected from our nature, which seeks for comfort in earthly things,
and is confined to sensual gratifications.
When we are disposed to look beyond the confines of time,
and seek to lay up treasure in heaven, it is from a Divine visitation and call; which,
though not always attended to,
I doubt not is extended in a way and manner beyond the reach of human comprehension:
upon which is founded our belief of the doctrine of rewards and punishments.

I observe what thou sayest concerning wars, which are met with in all places:
why they are thus taking place is beyond the reach of our understanding,
further than this,
that we have no doubt they proceed from the depravity of the human mind,
and not from the good Spirit of God, which proclaims, "`Peace on earth,
and good will to men:`" but there is another spirit, which is of a destroying nature,
both to body and mind, too much prevailing among men.
I am ready to say, how can Christians fight, in whose minds the Spirit of Christ prevails?
Will they not be more ready to do good to each other than hurt?
Taking away the lives one of another is not reconcilable
with the peaceable religion of the Saviour of men.
But we have to consider, that the name or title of Christian,
will not make us Christians; as the apostle says, "`He is not a Jew,
that is one outwardly, neither is that circumcision which is outward in the flesh,
but he is a Jew who is one inwardly, and circumcision is that of the heart,
in the spirit and not in the letter, whose praise is net of men, but of God.`"

The religion of Christ, no doubt, is a spiritual religion;
and actuates the mind to whatever is praise-worthy and excellent,
when it is embraced in its full extent:
but the outward form of it is only like the shadow to the substance.

Though war is not compatible with the religion of a crucified Saviour,
I do not think that every one who is engaged in war,
is excluded from a state of salvation: the grace of God is universal,
and appears to all men, teaching us, that denying ungodliness and worldly lusts,
we should live soberly, righteously, and godly, in this present world.

Many pious men have been in the condition of soldiers,
who were not convinced of the unlawfulness of bearing arms:
it becomes us to be cautious in forming our judgment concerning the state of these.

Having now exceeded the usual bounds of a letter,
I shall conclude with subscribing myself thy affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 1 Mo. 19th, 1787.

[.salutation]
Dear Friend J. V--f.

We see friendship formed with views of outward advantage,
terminates when the cause of it no longer subsists;
but the love between those who truly fear God, is not depending on earthly changes,
but continues the same in adversity and prosperity; and is not lost by absence.
It may truly be said,
the comfort we have to experience in each other comes
from our obedient walking in the Truth;
and not from an outward profession, or agreement in sentiment, barely.

My desire for thee is, that thou mayst happily come to embrace the Truth,
in the love of it, which no change of circumstance can deprive thee of;
and by this thou wilt not be rendered unfit to fill up thy place in society,
or discharge thy duty in a civil capacity towards thy relations and friends,
but be made more useful to them.

[.signed-section-closing]
I remain thy affectionate friend,

[.signed-section-signature]
J+++.+++ K
