== Chapter 6

Colchester, 14th 4 Mo. 1787.

Esteemed Friend,

As our love of this world is lessened,
our hope and confidence in the happiness of a future will increase;
by which means we may pass the evening of life in a state of submission,
and humble waiting till our great change comes: but if storms should rise,
when we are near the port,
(as we are not secure from them in any part of our
passage) it will be well to have him with us,
who governs all; under whose conduct we need not fear harms which may threaten us.

I take notice of what thou sayest concerning the schools instituted of late years,
for the instruction of youth, called Sunday schools;
they seem likely to tend to the general good, and therefore should be promoted.
Our society not being likely to want the help of them,
(as we make it a rule to provide for the education of poor Friends children)
should be no reason for our not contributing towards the support of these schools.
Our love is not confined to our own society;
it is a pleasure to us to see the increase of peace and happiness among our fellow creatures,
whatever name they bear among men.

I hope this institution will not be dropped for want of persons concerned for its support,
nor be hurt, by introducing things foreign to the design: great good may come from it,
if rightly attended to; but it is likely there will be discouragements met with,
as there always are to what is likely to be useful.

Thy affectionate friend,

J+++.+++ K.

Colchester, 23rd of 6th Mo. 1787.

To John Vanderwerf, of Amsterdam.

It will give me pleasure to hear that the quiet of your country is restored.
We cannot be active in affairs of government,
but we wish for the return of peace and harmony whenever it is interrupted.

I may inform thee concerning our Yearly Meeting in London, that it was large this year.
Many friends attended from the counties, and some from Ireland,
with seven or eight from America;
the meeting was held by adjournments for more than a week,
and was concluded in much harmony,
under the influence of that love which is the strength of society,
and foundation that stands sure in times of adversity.
I wish it may always remain among us, to show we are the disciples of Christ.

At the last meeting I suppose there might be about a thousand present;
it broke up under a sense of the Lord`'s goodness;
which it is desired may be thought of with gratitude,
and occasion thankfulness in our minds to the Author of all good.

With tenders of kind love to thee and thy sons, I remain thy affectionate friend,

J+++.+++ K.

Colchester, 14th 7 Mo. 1787.

Esteemed Friend,

I am not desirous of saying much concerning state affairs,
which cannot afford pleasure to serious minds,
especially those which relate to some neighbouring countries,
where fresh disturbances appear, threatening the return of war;
but I can inform thee of that which will be pleasant to hear, with regard to our society,
that there are signs of a revival of religion among us.
As our welfare depends upon the prevalence of that good principle
which took place in the minds of our friends in early times,
it is cause of rejoicing to see a religious disposition prevailing in the present time.

To have the fear of God accompanying us, in all parts of our conduct,
is an excellent thing: such who are preserved in it,
can never give just cause of offence,
though they may vary from others in matters of small importance.
A departure from God is the cause of declension in every society,
and when his fear takes place again, there is a revival.

I conclude these remarks with assuring thee of the continued regard of thy sincere friend,

J+++.+++ K.

To the Printers of the Ipswich Journal.

It is grievous to a tender mind, and occasions sad apprehensions,
to observe the great resort there is to inns and public houses in country towns,
on the first day of the week, (called Sunday) for the sake of reading newspapers,
and conversation on public affairs;
as also to indulge themselves in drinking liquors which have a tendency to intoxicate.

This seems so far deserving the notice of magistrates as to appoint officers,
who are sober, conscientious men, to visit these houses,
to prevent people from spending their time improperly in them, to their own hurt,
and the hurt of their families,
especially of those who are not in plentiful circumstances,
by spending so much of what they have procured on other clays, as cannot well be spared;
by which means some in the decline of life, have become chargeable to others.

If it is considered,
what may procure a comfortable subsistence during our stay in this life,
and what may be likely to obstruct it,
the practice of frequenting public houses without just occasion,
will be found to be highly imprudent;
but when we consider the harm which comes from it to our minds,
it may make us the more afraid of such indulgence.
As there is occasion for our making advances in the knowledge of God,
by means of a self-denying life,
that we may be more fit for an inheritance with him in a future state,
how can we with safety spend our time in this manner?
Engaged as many are, for six days in the week, in conducting their worldly affairs,
one day ought to be set apart for religious services,
in order that the desire of an heavenly inheritance, to be had hereafter,
may be kept alive in us.
Not but that every day should be spent as a sabbath, by abstaining from all excess:
and where the fear of offending God in any part of our conduct,
or of neglecting our duty to him, prevails,
there will be at all times great order and peace;
and consequently health of body and mind promoted.

I take the liberty to express my thoughts on another subject which hath claimed my attention;
it hath grieved me to see so much said in your paper concerning the fighters,
and fighting matches, now in vogue: I consider them as a disgrace to the nation,
and a practice which ought not to be countenanced,
therefore not proper to be mentioned in the public prints,
unless to show the inconsistency of them with the Christian character.
Among the Romans we read of gladiators, who were persons trained for fighting,
as a public diversion, and many lost their lives in it; till at length,
as the people became more civilized, and the Christian religion prevailed,
(the intent of which is to remove all such things,
and introduce peace and harmony,) the practice was abolished by authority of the emperors.
Shall this, or a custom very similar to it, be revived again,
in a day of so much light and knowledge?
If so, sober men among the heathen in former times, will rise up in judgment against us.

There is another habit,
which I apprehend is very hurtful to those who indulge themselves in it;
that is reading a certain species of books called novels and romances,
which are now dispersed in abundance in most towns in the nation.
If neither printer nor bookseller are scrupulous in the matter,
the nation is likely to be poisoned by means of such writings,
which tend to infuse libertine sentiments and principles.

I would therefore advise such who may see these remarks,
and especially the youth of the female sex,
to be cautious not to indulge their inclination this way,
lest they should be drawn insensibly from a liking to all books on serious subjects,
and especially the Holy Scriptures, which will be a loss not easily repaired.

It will be accounted a favour if the printers will insert the foregoing in their paper.

1788.

Colchester, 16th 2 Mo. 1788.

Esteemed Friend,

It gives us pleasure to hear of thy health being so favourably continued,
at such an advanced time of life;
and we desire the same favour may be continued to a later period; though,
as thou observest, we are in a state of dependence,
and know not the day nor the hour of our departure: it is well to expect it,
that we may not be greatly surprised when it comes.
The best preparation for this awful change is to
attend to the practice of our religious duty,
as far as we are convinced is required of us; and to restrain every inordinate desire,
or inclination which would lead us beyond the limits of moderation and temperance;
but this is not to be attained without the help of Divine grace;
which we have occasion to pray for every day of our lives:
that as it hath been our help and preservation in times past,
it may continue to be so to the end of our time here.
It is to this we owe, not only the comforts of our minds,
which come from a consciousness of right conduct,
but many of the outward blessings which we now partake of;
for how might our health have been impaired by intemperate living,
and our substance wasted, instead of being increased for our support in old age,
if we had not been assisted with wisdom to direct in the management of our affairs;
and strength to resist the secret enticements of our own hearts,
and the evil example of many, with whom we conversed.
Yet, if we have succeeded better than many of our fellow creatures,
there is no room for boasting, but rather occasion to be humbled,
in a sense of our unworthiness.

My wife joins me in kind love to thee and thy niece, from thy affectionate friend,

J+++.+++ K.

Colchester, 20th 4 Mo. 1788.

It is true, many things are going on among us,
which are not agreeable to the Christian character; yet there are many, I hope,
in all the different societies,
that are disposed from the best motives to walk answerable to it; whose care it is,
through Divine assistance, to adorn their profession by lives of holiness and piety:
and from hence arises that disposition in many,
to remove the oppression of their fellow creatures, and supply their wants.
I wish this may continue:
and that our hearts may be more enlarged in love to serve one another,
not only by supplying the necessitous with outward accommodations,
but by good instruction and example,
helping them into a way which may promote the happiness of their minds,
and render them fit for a heavenly inheritance in mansions of glory.

If we have a desire for the welfare of those, who are of the same nature with ourselves,
and have souls to be saved, I do not see how we can be regardless of their conduct,
or of what improvement they make in religious knowledge, and the habits of virtue,
upon which their happiness in a future state depends.
It is often seen that the indulgence of wrong inclination,
which leads to vicious practices, both in private and public,
brings distress and misery in this life,
as also tends to shorten the time of our continuance here:
and if we leave this world in the midst of our sins, and with much evil unrepented of,
in a state of darkness and alienation from God by means of wicked works,
what will be the condition of these, when the house of clay is broken down,
and the mind hath no longer any comfort or support from it?
Is there not room to fear the state of these will be unhappy;
as they are not fit companions for those who are
admitted into the favour and presence of God:
the calls of heaven, which are extended to all men, to bring us into the way of life,
never come in a compulsive way, so as to take away our liberty of choosing,
as reasonable creatures.

Thy affectionate friend,

J+++.+++ K.

Colchester, 11th of 8 Mo. 1788.

Dear Friend H. M.

After I had left you, and since my return home,
I have frequently thought of Friends in E--r,
with desires for their preservation in the Truth,
and further experience of the benefits of it.
There is a danger of some among them sitting down at ease, in an outward profession;
being called the people of God,
without a desire after that which can alone preserve us a people to his praise.
Alas! what are we without this concern?
A people, the most of any without form.
I desire it may not be said, we are the most of any without the substance.
When I consider what diligent attention is necessary to obtain this,
and observe the inattention of many,
I am ready to fear we are in a great degree destitute of
that life and power which is the crown of our assemblies.

When there is opportunity,
please to mention our love to thy cousin H. M. In considering his lonely situation,
I have to observe, there is no state in this life, either of rich or poor, high or low,
free from its difficulties and dangers:
it is not our being separated from the converse and society of men,
that will give us peace; but having our minds centered in Him,
who is the support of his people in every condition;
as well when we are in the discharge of our duty towards each other, in offices of love,
as when we are withdrawn from outward concerns;
our comfort still depends upon having our minds stayed on the Lord;
not desiring that our will, but his will may be done in us.

As to retirement, or being conversant with our neighbours, among whom we reside,
the great thing is, to fill up our stations with propriety;
neither to omit doing what is proper for us to do,
nor to undertake what is not required of us.
I would have my dear friend consider,
whether he hath not too much absented himself from the company and meetings of his friends,
from an apprehension of weakness;
and because things have not been in all respects as he could wish:
what we meet with of contradiction will do us good, if properly applied;
we must not expect to have things exactly in the order which we think best;
there is much disorder in the world, amongst men, which is suffered,
though not approved off by an all-wise Goodness; and,
as the love of God prevails in our minds,
it will help us to bear with patience many things that we see amiss: at the same time,
neither by word nor deed showing our approbation.

With tenders of kind love, I remain thy affectionate friend,

J+++.+++ K.

Colchester, 2nd 9 Mo. 1788.

Much esteemed Friend,

I am pleased to find my letter from Plymouth was acceptable to thee:
after making a short stay there, we proceeded to Exeter,
and from thence to several places, as Wellington, Taunton, Bridgwater, Glastonbury,
Wells, Bristol, Bradford, Melksham, Devizes, Marlborough, etc. in our way to London,
where we arrived on the 26th 1 mo.
and on 31st reached home in safety;
for which additional favour I can hardly forbear
to express my thankfulness to the Author of all good.

I desire it may be my endeavour to conduct myself so as not to displease him,
who hath thus,: favoured with his protection and guidance, in times of difficulty.
Here I might conclude, but remembering thy remark on the advantages I have,
so that thou seest no room for addition, I am inclined to say,
that I am so far from being come to a state which admits of no improvement,
that I find occasion every day to desire an increase of good qualities,
and am not satisfied with what I have known,
nor do expect ever to experience a state beyond that of a watchful, humble state;
sensible of my own weakness,
and continual dependence on the Almighty for help and strength.
All comes from him, whether mental or bodily faculties;
or outward comforts and accommodations.
When it is considered what obligations we are under,
there is occasion to say with one formerly,
What shall I render to the Lord for all his benefits to me?

I conclude with tenders of true love to thee and thy niece,
(in which my wife joins) thy affectionate friend,

J+++.+++ K.

Colchester 10th of 11 Mo. 1788.

Dear Cousin S. T.

It should be acknowledged as an especial favour to be preserved in bodily health;
yet the health of the mind is still more important,
as the consequences are more extensive:
it is a good thing to be patient under bodily affliction,
and cross occurrences which attend us; they will certainly tend to our improvement,
and bring an increase of good qualities, if we look to the hand from whence they come,
and are helped to say with Job, (in the time of his trouble) The Lord gave,
and hath taken away, blessed be the name of the Lord!

I consider thou hast the charge of a numerous offspring,
besides the weight of thy office, which calls for close attention:
I have also my cares on the account of others, which lie heavy upon me.
Let us seek for help from our great master, Jesus Christ,
to fill up our stations with propriety, in the church and in our families,
and to finish our course well.
It may be said, there is no condition in this life without difficulties and dangers;
to be sensible of the harms to which we are liable,
and at the same time feel a desire in our minds, that we may be preserved in safety,
is an unspeakable favour.
Though all men speak well of us, and we have not the approbation of our Saviour,
we shall want that which is essential to our happiness.

If we are placed in stations somewhat more eminent than others, let us think of Joseph,
David, Daniel, and others mentioned in the Holy Scriptures,
who by their care to preserve a conscience void of offence towards God,
were esteemed and beloved of men; not for their greatness or riches,
or nobility of birth; but for the wisdom which was in them,
and the good qualifications they had obtained,
through a humble walking in the fear of God.

Such are the excellent persons of the present time,
who being prepared by many trials of their fidelity,
show they place no higher value on the favour of men,
than as it may be conducive to promote their true happiness,
and help them to persevere in a virtuous conduct.

The regard I have for my friend makes me write thus,
wishing he might partake of those blessings,
which come from the choice of that one thing needful,
which the humble disciple of Jesus had chosen, that could not be taken from her.

I remain thy affectionate cousin,

J+++.+++ K.

Colchester, 13th 11 Mo. 1788,

Esteemed Friends,

Before I left your country, in returning homeward,
I felt a salutation of love in my mind towards divers of my friends,
with whom I had been comforted in the enlargements of the blessed Truth,
with which we were measurably favoured in our converse together; and since my return,
the same hath been renewed towards them in a more general way, and in particular,
I can say, you have had a considerable share of my remembrance,
with desires for your preservation in the way of Truth and Righteousness,
through a steady attention to duty,
and humble waiting for further discoveries of what may relate to your peace;
and that the comfort you experience may be as a voice to you, saying, "`This is the way,
walk in it.`"

We shall not be without afflictions and sore exercises, on our own account,
(for we are frail creatures) and on the account of others,
for whose welfare we cannot be unconcerned:
yet we had need to be careful not to grieve over much for the failings of others,
nor be discouraged by the difficulty of the way we have to walk in for want of companions.
Who knows what advantage may come from our constancy in labour,
for our own good and the good of others, if we can happily say, "`Follow us,
as we follow Christ?`"

Such success hath attended the endeavours of some in times of great declension,
that it might be said of them, as of Deborah, in her day, "`The highways were unoccupied,
and travellers walked through byways; the inhabitants of the villages ceased, until I,
Deborah, arose, a Mother in Israel.`"

There is need of such in the present time,
who are concerned at heart for their own welfare, and for the welfare of the society:
and if the Lord hath visited us with his light and truth,
and hath called us to work in his vineyard,
let us be faithful to the smallest discoveries of this light,
and endeavour to do with our might what we see fit to be done; at the same time desiring,
we may be preserved in humility and fear, having no high thoughts of ourselves,
nor of any thing we may be enabled to do; for there is nothing in us that is good.
Whatever good qualities we may have, they are from the truth;
and it is as we are preserved in it that we can be useful.
If any thing otherwise than well is seen in our conduct,
let us take the blame to ourselves; and when any thing appears that is praiseworthy,
let it be attributed to the Truth, by which we are what we are.

Thus, as we advance in age, we may come to see more clearly our state of dependence,
and seek for the renewal of Divine assistance, by which we can be preserved to the end.
I conclude, with a salutation of love, and remain your affectionate friend,

J+++.+++ K.

To Friends of the Counties of Devon and Cornwall.

As we experience that love to influence our minds, which hath more than earthly motives,
though we are far separated, and may never meet again in this present life,
we shall remember, and

pray for each other; that we may be preserved from harms,
to which we are liable in our various conditions; and may be helped to finish our course,
so as to become heirs of that kingdom of rest and peace, which hath no end.

And this is the cause of my present concern and writing,
that nothing might prevent your going forward in this good way,
which hath great privileges attending it, whilst we are going on;
but the crown of our labour is at the end of the race.

I speak to a number among you who are disposed to seek after heavenly treasure.
Dear friends! be not discouraged by what you meet with, from within or without;
the Lord`'s people have always been an afflicted, exercised people:
there is no occasion to wonder, as though something new happened to us,
when we are in trouble; for these are the means of our refinement,
and fitting for further degrees of religious understanding,
that we may come to make a right estimate of things,
and that nothing earthly may have an undue influence upon our minds.

Let us not desire an increase of outward comfort,
which we may not be able to bear without an abatement of love to God,
our great benefactor!
It is better to be as pilgrims and strangers in the world,
than to be walking in the smooth path of self-gratification, as citizens of this world,
whose prospects are confined to transitory objects.

The dealings of the Almighty are in unsearchable wisdom;
all his dispensations will tend to our profit, as we submit to him,
and are desirous that his will may be done, and not our own:
in due time he will effect that in us which shall be to his praise and our comfort.
But who shall abide the day of his coming,
(as the prophet hath said) and who "`shall stand when he appeareth?
for he is like a refiner`'s fire, and like fuller`'s soap.
He shall sit as a refiner and purifier of silver, and purge them as gold and silver;
that they may offer unto the Lord an offering in righteousness.`"

This is consonant to the doctrine of our great Lord, when he says,
"`Every branch in me which beareth fruit, my Father purgeth it,
that it may bring forth more fruit.`"
When we are in a state of weakness and poverty, as to our spiritual feeling,
so that we can see nothing comely in any of our performances, it is best to be contented;
and of how long continuance this shall be, is not for us to determine.
We are to wait upon the Lord for relief from him, who hath said, "`I am the Lord,
I change not, therefore ye sons of Jacob are not consumed.`"

Those who have experienced the Lord`'s goodness can speak well of his name:
they desire not to be without these exercises, which are conducive to their good,
nor would have any smoother path to walk in,
than that which leads to the kingdom of rest and peace.
They consider the way which suits our inclination, and is easily obtained--is broad;
and the gate by which we enter into the ways and customs of the world is wide,
and open for our admission, with the many that go in thereat, to their unspeakable hurt:
but the way of peace, which ends in true liberty, is strait and narrow,
having nothing in it desirable to us, in a state of nature.
If we would walk in this way, there must be force used upon ourselves,
and we must be like those who are ascending a hill that is difficult.
We must be willing to lay aside many things that are likely to encumber us in our journey,
and make use of all the means which are afforded for our help.
Among others, I would recommend a diligent attendance of religious meetings,
as well those on the week days as on first days.
I may safely say, none ever were in the practice of this from a conscientious concern,
but they received a benefit from it, and found it attended with good consequences,
by helping them, from time to time, to persevere in a religious conduct;
as it is also a means of promoting their worldly interest,
by the better capacity they receive to transact their business with prudence,
and in the fear of the Lord.

On the contrary, those who neglect this duty, or grow careless in it,
are sure to suffer loss.
The strength of the society in general, and of individuals, in a great measure,
depends upon the continuance of this practice among us.
I say the more on this head, because I wish to have you continue your care,
not to omit that which may prove so much to your advantage.
Let us consider the intent of our thus meeting together;
that it is to wait upon him that we call our great Lord and Master,
who will not let us go unrewarded, as we serve him diligently.

Though your meetings should often be held in silence,
they will not be unprofitable to the right-minded, nor hinder their attendance.
As all are exercised in the gift of grace received, there will be a harmony of spirit,
and nothing will be wanting, even outwardly,
which is necessary for your help in the Lord`'s time, as you wait upon him:
the same power remains, which qualified for services in the church formerly;
and many will be qualified,
and made instrumental in the Lord`'s hand to help forward the good work of reformation,
as there is a seeking for his help and strength.
And the ministry which comes this way will be truly acceptable,
and have its own evidence; whereas that which comes from the wit and contrivance of man,
will not edify nor tend to your comfort:
so that it is better to be without an outward ministry in our religious meetings,
than to have that among us which is not sanctified.

Whilst I am writing this,
there is something in my mind to communicate to my dear friends and fellow-labourers,
in the gospel of Christ; who are concerned to speak, in the ability received,
in our public meetings, not to please themselves, or for any earthly gain,
but from a motive of love, and to discharge their duty to God,
whose peace is more to them than the gain of silver or gold.
Having had some experience of the difficulties attending this concern,
I would drop a caution to those who are at times ready to faint in their minds,
from a sense of their weakness, and the many low times they have to experience,
with the little apparent good effect of their labour.
In all this, let us remember, it is good for us to be humble and lowly-minded;
if we are not favoured to obtain what may be desired, yet the hardship we have to endure,
and the disappointments met with in our concern,
will make us more fit for the Lord`'s use.

There are great deviations in many places from the
testimonies our predecessors had to bear,
especially as to a compliance with the customs, ways, and fashions of the times.
This occasions painful thoughts to those who watch for the good of their brethren: and,
on account of the danger they are in, themselves,
of being leavened into the same disposition, and by frequent intercourse,
infected with the same disorder, there is occasion for a continued exercise,
and many deep baptisms of spirit, to prepare them for fresh trials,
and wean from the love of this world,
as also to keep from a dependence on earthly supports;
it will be better to lose outward comforts than by
means of too near alliance with worldly-minded persons,
miss of the more intimate acquaintance and fellowship of our everlasting friend:
we are to love all,
but join with none in a conduct inconsistent with
what hath a tendency to procure true peace.
When we remind others of the harm which comes from
an inordinate pursuit after the things of this life,
and too great love of the world,
we should take great care to keep ourselves so disengaged from earthly concerns,
as to shew, by our example, we are seeking after that for ourselves,
which we recommend to others:
thus will our weak endeavours to promote the cause of truth be blessed with good success;
and whilst we are made instrumental to save others, we shall also save ourselves.

I would say to those who are concerned in the exercise
of the discipline established in the society,
that, as a Christian spirit prevails,
we shall bear one with another in some weakness which may appear;
we shall not be offended when things occur, as likely to take place,
which are contrary to our sentiments,
but seek for that clothing of meekness and gentleness, by which we may cover a fault,
and prevent further harm coming from it:
thus the enemy of our peace will be disappointed in his intention to separate us,
and occasion a breach of unity; and that which might prove very injurious,
by being improperly treated, may be useful, by means of the exercise of those virtues,
which all have need to experience an increase of.

In thus writing to my friends,
I remember those who are coming into an active part in the concerns of this life,
by whose conduct the society will be affected, either to its advantage or disreputation,
as also their own best interest will be promoted or hurt,
according to the choice they may make; I mean the youth among us, of both sexes,
towards whom I feel much good will: if they should happily choose the fear of God,
and be more concerned to please him, in a life of self denial,
than to gratify their inclination, by a conformity to the world, in its ways and customs,
who can tell the advantages which will come from it?
As the apostle says, "`Godliness is profitable unto all things,
having the promise of the life that now is, and of that which is to come.`"

It it also declared, that "`the Lord God is a sun and shield:
the Lord will give grace and glory;
no good thing will he withhold from them that walk uprightly.`"
Eye hath not seen, nor ear heard,
neither have entered into the heart of man the things
which God hath prepared for them that love him.

I would fain persuade you to dedicate the prime of life to his service,
who will reward with peace here, and a crown that fades not away hereafter.
As the Lord in mercy hath visited your minds, and raised desires after him,
in a sense of goodness and heart tendering love,
O be persuaded to join in with his call! and let it be your desire,
that he will renew them from time to time, and never forsake you,
till he hath gained the preeminence in your minds; that you may say, with one formerly,
"`Speak, Lord, for thy servant heareth:`" and when informed of your duty,
let it be in little or much, that is required to be done or to be omitted,
pray to the Lord that he would strengthen you to perform his will:
thus will your peace increase, and usefulness in the society; that,
as the elders are removed,
you may come up in a godly concern for the support of those testimonies,
which our forefathers had to bear in former times,
and which are worthy to be supported in the present day.

Not that we are to suppose,
a bare conformity to these practices will procure the Divine favour,
without the heart is devoted to his service, who looks beyond all outward acts.
God is not pleased with the most exact observance of what he hath required of his people,
unless it is from a motive of love to him;
and at the same time taking heed to the dictates of Truth in the mind,
which leads to all purity and holiness in life and conversation.
Every sacrifice must be seasoned with undissembled piety, from a desire to please God.

In conclusion, I feel a desire that all my dear friends, in whatever station they may be,
who have been favoured with a Divine visitation to their minds,
and informed of their duty,
may still be disposed to seek for heavenly wisdom and strength;
without which we are no more able to steer our course with safety, now,
than when we were in the beginning, let our age or experience be what it may.
Many have suffered loss, for want of the same concern remaining with them,
which they experienced in the early times of their convincement;
forgetful of their state of dependance,
they have too much trusted to their own understanding.
There is room to be afraid of that liberty which is so pleasant to us,
lest we should abuse it, to our hurt, in the time of ease and plenty;
forgetting him who hath given us all that we enjoy, and is our preserver in every state,
even the Lord our Saviour.

Let me add a caution to my friends, to watch against the harms to which they are liable,
from the increasing cares and concerns of this life;
which claim a large share of their time,
and will hinder from a suitable attention to concerns of greater importance,
if there is not a holy resolution renewed in the mind,
still to be devoted to the service of their great benefactor.
As we have been favoured to find the treasure,
to which the kingdom of Heaven is compared by our Saviour, let us be willing to sell all,
to purchase the field in which it is hid.

Having thus expressed the concern which hath accompanied my mind,
on behalf of my friends in these distant parts of the nation,
who are but few in number in divers places, and, as to an outward ministry,
like sheep without a shepherd; (yet they are not forsaken of him,
who hath said concerning his church--`"Lo,
I am with you always to the end of the world;`" nor will any, even the least among you,
want the needful comfort in times of adversity, as your dependence is upon the Lord,
our mighty God and Saviour, who cares for them that seek him in sincerity,
and fails not to administer what is needful for the help of his people,
in his own way and time;) with desires for your establishment in the Truth,
through obedience to its dictates, and the increase of peace,
which is the reward of faithfulness, I subscribe myself, your affectionate friend,

J+++.+++ K.

Colchester, 11 Mo. 1788.
