== Chapter 7

Colchester, 27th 11 Mo. 1788.

Esteemed Friend,

I take notice of several things in thy letter which are pleasing to me,
particularly what is said concerning the slave trade.
The endeavours used by the dissenters,
as also the continued care of the society in London,
instituted to procure the abolition of the trade, I hope will prove successful;
but whatever may be the result,
it will afford relief to tender minds to have endeavoured to help this oppressed people.

I have seen the tract of John Newton:
it may be considered as a concurring testimony against this inhuman traffic,
as he was at one time of his life concerned in it.
As thou observest, there is a benevolent disposition prevailing in several societies,
which gives room to hope something may be produced, through the Divine blessing,
more extensively useful:
when men of right principles are united in their
endeavours to promote the cause of Truth,
great things may be effected, the moving cause of their labour being the love of God,
which is not confined to narrow limits, but reaches over sea and land:
first to our relations and friends, and those with whom we are in most strict society;
then to every one of all societies, and to all mankind, wherever their habitation may be,
or whatever name they may bear.
Having tasted of this love,
we may have room to desire it may increase in our minds whilst we are here,
till we come to the more full enjoyment of it in a better state.

There is cause of thankfulness,
that the good providence of the Almighty hath continued thy life to such an advanced age.
I desire it may please him to support thee in thy weakness, by his good presence,
till he shall remove thee from this state of trial to thy everlasting rest!

I am thy affectionate friend,

J+++.+++ K.

Respected Friend,

I much approve of thy disposition,
not to be offended at the conduct of thy friend C--.
From the experience of many years I have found,
that the most effectual way of prevailing with such as are unkindly disposed towards us,
is to forgive them heartily, and do them good, if it should be in our power:
thus the weapons which are raised up against us, are taken out of their hands,
and they become our friends.
It is wholly agreeable to the excellent religion which we profess, to forgive injuries,
even the greatest we may receive;
and our reward is with him who weighs all the actions of men,
and often produces good from the disappointments, and painful occurrences,
we have to meet with.

Considering the variety of interests,
and the different sentiments which attend the human mind,
and the want of a due share of that religion which
can regulate our conduct towards each other,
it is no wonder that there are such oppositions and contests in the world:
but let us have in view that kingdom of peace, and wish to meet in it,
where there is no striving for high places;
but each contented with the place assigned him in the heavenly mansions,
where harmony and peace forever reigns,
without any of the interruptions which are common to us here.

With due respect I subscribe myself, thy sincere friend,

J+++.+++ K.

To my much esteemed Friend S. N.

When I consider how we became united,
by means of that living principle which was awakened in our minds,
through the visitations of Divine light and Truth, in the days of our youth,
it makes me desirous of sending thee a small token,
by which it may be revived in our declining age;
and when we are far separated from each other, both by sea and land,
attended with infirmities, as those who are waiting for their great change.

It must be allowed, these are times of difficulty and danger;
we have not only the same enemies remaining,
which the Lord`'s people in every age had to contend with,
but some trials peculiar to the day in which our lot is cast.
I am aware that this was the complaint of our predecessors;
so that we are apt to have a less favourable opinion of our own times,
than of those which are past.
As we have been thus far preserved,
let us hope that our good guide will go with us in the remaining part of our days,
as one well acquainted with the perils of our journey, who is able to help us.

I wish what I now write may meet with thy acceptance,
and that it may be pleasing to thee to hear from an old friend,
who hath this to comfort him, that he can remember his friends,
and is not wholly separated from them, because of that love of our heavenly Father,
which no length of time can dissolve; in this we are united to those who have left us;
though we have not their bodily presence, we are not separated in spirit.

With true regard and affection I am thy sincere friend and brother in the truth,

J+++.+++ K.

To the Captain of a Ship, about entering on his Voyage to the East Indies.

J+++.+++ K. requests Capt. W`'s. acceptance of the enclosed books;
one of which he may present to his friend W. C. and the others make use of,
as he thinks proper.
It is hoped they will come to his hands in due time,
as a small return for the civility shown to J. K. and his wife at Harwich.

He hath also their best wishes, that good success may attend his undertaking,
through the blessing of the Almighty,
and that he may return in safety to his native land.
It is a concern of no small importance to pass the mighty ocean into foreign lands,
let the occasion be what it may; and those who have the charge of others,
especially of so many, had need to be men fearing God:
that their example may tend to promote good order and regularity,
as well as their advice, and the discipline kept up, tend to discourage,
and expel vice and immorality,
which produce the greatest harms to societies and families,
and are the most offensive to him who beholds all our actions,
as well when we are in our more safe dwellings upon land,
as when we are travelling on the seas, or in very distant lands: the Lord,
our Almighty protector, goes with us as the witness of all we do or say,
and is a faithful rewarder of those who love and fear him.

In this life he is often pleased to discriminate between the righteous and the wicked;
but if the same should happen to both, as to outward circumstances,
in his inscrutable wisdom, yet he will certainly reward our obedience to his holy laws,
in a future state.

Colchester, 4th 8 Mo. 1789.

Colchester, 4th 10 Mo. 1789.

Dear Friend E. G.

Many changes happen in earthly affairs, which thou and I have experienced,
so that we are convinced there is no dependence to be had on the comforts of this life;
but the Truth, which I hope we have been helped to make choice of,
remains the same as in the beginning, unchangeable and everlasting.
As we have not come at it without taking pains, there is occasion to value it the more;
and, as there is a further knowledge of it wanted, let us be contented,
if we have to experience fresh conflicts and trials.
The dealings of the Almighty are in great wisdom.
He knows what is for our good, and does not afflict willingly,
but often by a lesser evil, prevents a greater; and,
by means of disappointments and crosses, rectifies our own weak judgment,
so that we are better prepared for what is permitted to attend us.

Thus in the freedom of friendship, I mention my thoughts to thee,
and remain thy affectionate friend,

J+++.+++ K.

Colchester, 6th 10 Mo. 1789.

Esteemed Friend W. P.

Many of the poor have been assisted from the funds
of the society to which thou kindly contributed;
eight persons are appointed as stewards, in different parts of the town;
whose business it is to visit and relieve the necessitous, as they see occasion,
and enter the names, and places of abode of such as are assisted, with the sums given,
in a book for that purpose; and once in every month the treasurer repays them:
the sick and aged are particular objects of this charity.

How much better is it to allow a part of our time, for the enquiry after,
and visiting the poor and distressed;
and to bestow a part of the riches that Providence hath favoured us with for their relief,
than wasting both time and money in such sumptuous entertainments as thou mentions,
where as much is expended at one dinner as would support
many poor families in a comfortable way for some months.
We may safely say, if people were rightly disposed, it would not be so;
it shows how little a bare outward profession of religion will do for us:
and that there may be the same disposition prevailing, and the same practices,
among those who bear the Christian name,
as among those who never heard the name of Christ.

The end of Christ`'s coming was not to excuse us from the obligations to piety,
and a good and virtuous life and conversation;
but to assist us in our endeavours after holiness.
He came not to save us in our sins, and from the punishment of them only,
by his righteousness and holiness being imputed to us, whether his spirit actuates us,
so as to produce good fruits, or not;
but the end of his coming is to save us from our sins, and that we may be helped,
in this present life, to avoid everything which tends to dishonour him,
and to do what he commands, which may prove to our everlasting advantage and his praise.

This is the salvation we have need of, in my apprehension of the nature of true religion,
and it will be a great unhappiness to depend upon anything short of it.
I am thinking there would be a great change in the lives of many people,
and many harms would be avoided, if religion influenced their hearts,
and they were more concerned how they might appear before God, and have his approbation,
than how they may please men.

I am thy affectionate friend,

J+++.+++ K.

Colchester, 16th 2 Mo. 1790.

It hath not been for want of respect that I have omitted to acknowledge
the favours of my friend J. T. It is pleasing to be informed of
the liberty granted to Protestants in France;
I wish it may be made a good use of.
Though it is desirable, and a great privilege,
to have opportunity of serving God in the way we approve, without any outward restraint;
yet how have we seen great coolness of love and zeal overtake the churches of Protestants,
in a day of ease and tranquility; so that the sufferings of our forefathers,
who by their faithfulness procured the liberty we enjoy, are forgotten,
and the form of religion, which we have been led into from their example,
too much rested in, without the life and spirit of true religion,
and God`'s holy fear influencing our minds.
This is the state of many bearing the Christian name,
even among those who profess to be reformed from
the errors and superstition of the Romish church.
Yet we hope there is a revival of concern in the minds of many; who,
with the prophets of old, mourn for the declension of the people; and,
with good Nehemiah, endeavour to promote the necessary reformation,
that the walls of the city may be rebuilt, and the gates restored,
so as to be more secure from the inroads of enemies.
I mean not the outward prosperity of the church,
but that defence and security which is obtained in
our obedience to the captain of our salvation;
whose kingdom is spiritual, and built up, and established in righteousness and holiness;
and consists not in meats and drinks, but in peace and joy in the Holy Ghost.
Alas! what will a show and profession, as to religion, do for us:
if the living principle of truth, which is Christ,
the substance of all the shadows and figures,
by whom we can alone offer sacrifices acceptable to God, does not influence our minds?
What we do without this, will be but our own righteousness,
which the apostle compares to filthy rags.

To speak my mind freely, I often fear for myself and others,
lest the forms of religion which we have adopted, and a constant round of duties,
should lead us from a due attention to this principle,
which can only make us true worshippers in the inward court, and acceptable to God,
through the Spirit of his beloved Son.
I write thus to one who hath had long experience in the way of the Lord,
and known with increasing years, an increase of love to God; which,
as it was a preservation in youth, is as the balm of old age.
What comfort can we find in this world,
that is to be compared with the enlargements of love which is in Christ, our Lord?
Let it flow and overflow in our hearts, towards our great Benefactor, and all mankind;
that we may be enabled, by the strength of it,
to break through the limits of human institutions,
and meet in that which hath no bounds in its extension
towards the workmanship of his hands.

I remain thy affectionate friend,

J+++.+++ K.

Colchester, 27th 2 Mo. 1790.

Esteemed Friend William P+++______+++y.

Though the weather hath been milder than usual this winter,
it appears not to have been more conducive to health than colder weather,
at this time of the year; but it is not for us to direct,
nor does it become us to complain: what is permitted in this respect,
we ought to acquiesce in, and acknowledge with thankful hearts,
the mercies we receive from a gracious Providence.
If we have not all things to our wish, we partake of many favours,
in the remembrance of which we are ready to say, "`What shall I render to the Lord,
for all his benefits towards me?`"
It will be a great advantage to us to be looking to him,
who hath been our keeper from the early part of life; and helped us,
so that we have avoided the harms attending many of bur fellow creatures;
and moreover provided us with outward accommodations, sufficient for our use,
and put it in our power to help others.
If he should please to mix some bitters in our cup,
it will be no more than happens to those who partake of the same nature with us;
we may concur with Job, in saying, that though affliction does not rise out of the dust,
nor trouble spring out of the ground, (but are permitted for wise and good purposes,
which we know but little of,) yet man is born to trouble, as the sparks fly upward.

This servant of God had large experience of the uncertainty of earthly comforts;
he did not murmur at the Lord`'s dealings with him,
but humbly submitted to the severe strokes of his hand:
the apostle mentions him as an example of patience.
We are also more effectually encouraged and comforted in our affliction,
by the example of our great Lord; who bore many griefs for us,
and patiently submitted himself to death, even the death of the cross:
showing us that the way to his kingdom is not filled with sensual gratifications,
and fleshly indulgences, but hath much of self-denial; without which, he hath said,
none can be his disciples.
And our own experience confirms the truth of this doctrine,
beyond all the arguments of human understanding.

I remain, in hopes of hearing from thee before long, thy affectionate friend,

J+++.+++ K.

Colchester, 2nd of 4th Mo. 1790.

Dear Uncle,

In true esteem and love, which is renewed in my mind,
I wish to say something which might afford comfort in the present trying dispensation.
I consider it is the lot of all to meet with troubles,
and that they are as wholesome medicines, which tend to restore our health,
when too much prosperity might make us forgetful of Him from whom our blessings come.

Our heavenly Father sees meet to try our faith and patience,
by various afflicting circumstances, some of which are seen, others more private,
and hid from the knowledge of our nearest friends;
yet he will not forsake his poor depending children, who put their trust in him.
As he hath been with us in six troubles, he will also be with us in the seventh,
to help and support; so that our afflictions will be sanctified to us,
and tend to prepare for an heavenly inheritance.

When the time shall come that we must leave all these earthly enjoyments,
it will be an unspeakable comfort to have this humble hope,
that we shall join the assembly of the righteous of all generations.
This is the good land, which we have been favoured to have a prospect of;
where many of our dear relations and friends are gone before us,
whose return to us we cannot desire.
It hath pleased the Lord to spare us a little longer in this state of trial:
we have to pray to him,
that he would preserve us to the end of our time in his holy fear,
being still concerned to serve him, who hath led us through many conflicts,
both inward and outward, wherein nothing less than his power could have supported:
and having had such experience of his goodness,
let us not be afraid to cast our care upon him.

That we may be brought nearer to him and near one to another,
by means of the exercises we have to meet with, is the desire of thy affectionate nephew,

J+++.+++ K.

Colchester, 22nd 4 Mo. 1790.

Esteemed Friend W. P.

There is nothing more to be desired than that when we put off these
mortal bodies we may meet in the abodes of the blessed,
where none of these cares which now oppress our minds will be met with;
but unmixed happiness, according to what our state will bear,
in the disposal of unerring wisdom and goodness.

It is not proper to allow of anxious thoughts concerning our future destination;
having passed our days in the fear of God,
and in obedience to the dictates of his good spirit,
we may trust him for a reward of our labours, according to his mercy,
through the merits and intercession of his beloved Son.
Not by our own works have we to expect to be saved, but, as the apostle says,
according to God`'s mercy he hath saved us,
by the washing of regeneration and renewing of the Holy Spirit.
Happy for us will it be to know this work begun and carried on,
in order to our more perfect redemption from earthly cares,
and all unsuitable dependance on earthly comforts,
which are of short duration and uncertain.

That thy days are lengthened to such an advanced period,
may be accounted a special Providence,
when so many of thy acquaintance and friends have been removed by death much earlier.
No doubt it calls for thankfulness from a grateful heart,
in commemoration of many mercies received,
from the early part of life to the present time.
Having had experience of the Lord`'s goodness, according to my measure,
I can join thee in returning thanks to him, who hath thus long spared us:
also in prayer to him,
that he will help us to walk in his fear all the days of our appointed time,
till he is pleased to remove us from this probationary state.

I need not make an apology to my friend for writing so frequently on these subjects,
after he hath said they are welcome to him.

I conclude with tenders of kind love, thy sincere friend,

J+++.+++ K.

Colchester, 9th 10 Mo. 1790.

Respected Friend,

I hope nothing will be met with, in the conduct of any of our society,
which may give occasion to alter thy sentiments, as to the benevolent,
friendly disposition thou apprehends is prevalent among us;
but if any thing contrary to it should appear,
thou wilt be more candid than to judge the whole society for the failings of a few.

It is consistent with our principles to be kind to all men;
not to be offended with those who differ from us.
Even if we are unkindly treated, not to make returns in the same way,
but endeavour to overcome evil with good.
We are led to act thus, from the peace we find attending it to our own minds:
we are also confirmed in the propriety of it,
by the example and doctrine of our great Lord,
whose precepts tend to promote peace and love, universally.
And we cannot help thinking,
if this good spirit was to have place in the minds of people,
it would prevent many contests in families and places; as also the dismal effects of war.

But if we cannot prevent the harms which come to others,
by an unfriendly disposition prevailing,
let us seek for an increase of love and good will in our own minds,
that so we may in our conduct, as well as by words,
bear witness to the power of the religion we make profession of.

The poor among us are much distressed, notwithstanding the relief from parishes,
which is not sufficient to supply their wants.
The assistance from the Benevolent Society hath been very useful; and care is taken,
not to do any thing which might excuse the parishes from extending the necessary relief.

I conclude with subscribing myself thy affectionate friend,

J+++.+++ K.

Colchester, 10th Mo. 1790.

Friend --,

I was much grieved at the profane speeches and dismal
imprecations which thou made use of,
in my hearing, yesterday.
It occasioned my enquiry after thee; and being informed thy name and place of abode,
I take the liberty to send thee a book, which I request thee to read,
or get one of thy family to read to thee.
And I hope thou wilt not despise the advice contained in it, but lay it to heart,
and endeavour to break off the habits of swearing and drunkenness,
which have brought many to their graves with disgrace and sorrow,
and made true the saying, that the wicked live not out half their days.

If there was no state of being hereafter, it would be unwise in any to live an irregular,
disorderly life, inconsistent with the fear of God; because the health is injured,
and the peace of families disturbed by it.
But when we consider,
there is a part in us which lives after the body is laid in the grave,
and that we shall be called to an account for our words and actions, by a just God,
who hath placed us in this world as rational creatures, and accountable to him,
it is enough to alarm us, and put us upon thinking what we are about;
and endeavouring to break off our sins by a timely repentance,
lest we should be suddenly snatched away, and conveyed to the grave,
where there is no repentance.

My writing this is from a motive of true friendship,
and I would have thee consider it as a warning,
to turn out of the way which leadeth to destruction, into the path of peace.

From thy real friend,

J+++.+++ K.

Colchester, 21st 1st Mo. 1791.

Esteemed Friend,

Considering thy advanced age, weakness and bodily infirmities are likely to attend,
which I doubt not, thou endeavourest to bear with patience, as the lot of human nature,
and which all are liable to.
It is to be desired that this and all we have to meet with,
may be sanctified to us so as to make us more fit for our removal from this frail state,
to partake of a heavenly inheritance.

If such as are in the enjoyment of perfect health, and in the prime of life,
had need to be ready for the approach of that awful messenger,
which is sent to the houses of young and old, those, especially, have room to expect him,
who, from the course of nature, are fast approaching towards the end of all things here.
It will be good for us to have our expectation towards our great Master,
submitting to his dispensations, and waiting for his call,
and if he is pleased to spare us a little longer,
to be thankful for his goodness in times past, and in the present time;
not asking for the extension of our days to a very distant period,
so much as that we may be preserved in the fear of the Lord,
and endued with wisdom to steer our course with safety.

Though we do not meddle with affairs of government,
we cannot but be thankful for peace restored,
and that the threatenings of war are subsided,
like a storm which seemed likely to break upon us!
May it become our concern to make a right use of this favour,
with others bestowed upon us, in a national and individual capacity.
The great Lord will call to account for his gifts, and of those who have received much,
much will be required.

My wife joins in kind love to thee and thy niece, from thy sincere friend,

J+++.+++ K.

Colchester, 24th 1st Mo. 1791.

Dear Cousin,

The account of thy illness is matter of concern to us.
Afflictions are permitted to attend, for wise and good purposes; though hard to bear,
they are as messengers of peace, and productive of good,
as we are helped by gracious Goodness to bear them properly.

I much desire this may be thy experience in all the troubles thou hast to meet with,
whether from thy own bodily infirmities,
or disappointments in thy endeavours to provide for thy children.
It is a comfort to thee that they are religiously disposed.
There is no room to doubt of their being provided for (as to an
outward support) as it becomes their concern to seek for his favour,
who feeds the ravens and clothes the lilies;
it is promised that he will not leave nor forsake those who put their trust in him;
yet whilst we depend upon the Lord our God for his blessing,
we are to endeavour to provide for our support,
by ways which are proper for us to make use of, and not to remain in an inactive state,
as though we were to obtain all we want without taking pains to come at it.

I remain thy affectionate cousin, J. K.

22nd 9th Mo. 1791.

To J. and M. K.

I hope my dear cousins will be supported in the present trying dispensation.^
footnote:[In the loss of their only child.]
It may be well to remember how the good man expressed himself when he had lost his children,
and was reduced to great poverty: "`The Lord gave, and the Lord hath taken away,
blessed be the name of the Lord.`"
He bore with patience the dispensations of Providence;
and thus it becomes us to endeavour to submit to all the
troubles and disappointments we have to meet with;
there is this advantage in them, that they tend to wean us from the love of this world,
and to make us more willing to leave it,
when it pleaseth the great disposer of events to
send the messenger of death to our houses.

My present weakness will not admit of saying much, nor of making you a personal visit;
yet I am inclined to mention, that you are frequently in my remembrance,
with desires for your welfare,
that what you meet with may be a means of bringing you nearer to him,
who is the Comforter of the afflicted, and forsakes not those who put their trust in him.

These few lines are in much love and sympathy, from your affectionate cousin,

J+++.+++ K.

To those who fear the Lord,
and are concerned to seek after a more perfect knowledge of his way;
who reside at Pyrmont and parts adjacent in Germany,
we send the salutation of unfeigned love.

Dear Friends,

Having been hindered from making you a personal visit,
as was intended after we had spent some time in Holland,
it is become our concern to write these few lines,
to express the good-will we have towards you, and desire for your welfare.
We are sensible of many difficulties attending your situation,
and that you stand in need of the Divine protection,
in order to a safe proceeding in the way of life and salvation.
Let us remember, it is not enough to have known the Truth, and the benefits of it:
if we do not continue to walk in it, as faithful servants,
all the fruit of our past labours may be lost.
Vigilance is required, lest our enemy should deprive us of the crown,
which is prepared for those who continue stedfast in well-doing,
and persevere to the end.

It is comfortable to us to hear you continue to hold your religious meetings;
though but few in number, and wondered at by your acquaintance,
we hope it will not discourage you from continuing this good practice,
which may be a means of increasing your number,
especially if there is a conduct in all respects agreeing with the Truth.
If you have not the privilege of much outward ministry, be not discouraged:
our increase in Divine knowledge, and a right experience of the things of God`'s kingdom,
does not depend upon this alone, but on a humble waiting, in patience,
for the renewed help and instruction of him who is the Minister of ministers,
who hath promised to be with those who are gathered in his name.

We apprehend a waiting in silence is required in our public assemblies,
as well as in opportunities of more private retirement,
and it is to be desired that our knowledge of the benefit of silence might be increased.
Though many are strangers to this way, and offended with it, yet we may inform you,
that there is an increasing concern in the minds of some in this land,
thus to seek to renew their acquaintance with their Lord and Saviour,
which occasions our meetings to be better attended than heretofore.
This we consider as a sign of revival, as to the life of religion,
and is a cause of rejoicing to the right-minded;
may it increase among us till our goings come to
be established in the way of truth and righteousness,
to our everlasting comfort and peace.

In a sense of our heavenly Father`'s love, and regard to his poor depending children,
in the present time, as in ages past, we affectionately salute you,
and remain your friends and brethren,

J+++.+++ K., J. A.

Colchester, 16th of 12th Mo. 1791.

Colchester, 28th 4 Mo. 1792.

Dear Relations,

The love and regard I have for you makes me take the liberty to mention my concern,
lest you should suffer loss in what is most essential
to the peace and happiness of your minds,
through an over anxious care about the things of this life,
and a neglect of improving the precious time allotted you here.

This concern hath been increased in my mind since I returned home, from information,
that you are often absent from meetings, both on the first day and week day.
I cannot forbear to say, that I have never known any to prosper, in a religious sense,
nor often in their outward concerns, who have been negligent in this part of their duty.
I am confirmed in my sentiments, as to the obligation upon us to show to all,
to whom we are known,
that we do not forget to make public acknowledgment
to the Author of all the good we enjoy,
by frequently meeting together in the love and fear of God, to wait upon him.
Not being prevented by any reasonings of our own minds,
nor by any thing we may meet with from men; who cannot answer for us,
any more than we can for them;
but we shall each be rewarded according to the endeavours
we have used to improve the gifts bestowed upon us;
let us therefore be attentive to what promotes our everlasting good,
and we shall lose nothing by it, as to our temporal interest.

There is this encouragement,
that as we endeavour to improve what God hath been pleased to give us,
more is added to our stock of substantial good: on the contrary,
these who are not faithful to the heavenly gift, instead of an increase,
what they have is taken from them.
I am desirous that this may not be your state,
but that through faithfulness to the discoveries of duty,
you may be going forward towards further stability;
and may be more and more prepared for the changes to which all things here are subject,
and for the awful change which will attend us all, by death; when, nor how, we know not,
but it will be as the great disposer of events shall appoint.

I have wrote thus to you from motives of love and true affection,
and am your sincere friend,

J+++.+++ K.

Colchester, 10th of 5 Mo. 1792.

Esteemed Friend,

We received thine of yesterday,
with the sorrowful intelligence of the decease of thy uncle:
though he was arrived at such an age,
as made it not likely we should be favoured much longer with his company,
yet we cannot but mourn for the loss of one who was so much esteemed: however,
these are losses we must submit to, as the attendants of human nature;
they should lead us to cultivate his friendship,
who remains to be the Comforter of his people, when outward comforts fail.

When we meet with troubles of this kind, or any other,
if they tend to wean us from the love of this world,
and an unsuitable dependence upon it, it may be said, they are sanctified to us,
and have their proper effect:
we are but as travellers passing through this little space of time,
into a state that will never end, where all the generations of men must finally center.

I have before me thy uncle`'s last letter,
which I was about to answer when I received the account of his death;
I consider it as the last token of his friendship, and value it accordingly.
From thy sincere friend,

J+++.+++ K.

Colchester, 24th 6 Mo. 1792.

Dear Friend J. P.

One hindrance to my writing to thee, and some others of my friends, hath been illness,
which attended me upon my return from the little journey I took last summer into Holland,
in the company of my friend J. A. We had a view of going into Germany, as far as Pyrmont,
and some places adjacent, to visit a people who are convinced of our principles,
and hold meetings in the manner of friends.
But when we had been in Amsterdam about a week,
my friend received a letter from his wife,
informing him that she was in such a weak state, as to bodily health,
that it did not seem likely he would see her living if he did not return soon.
This, together with my illness, made us conclude to return,
and soon as could be conveniently; and we were favoured to arrive at our habitations,
my companion in time to see his wife before her death,
(which was soon after his return,) and I before my illness came to a great height.

These were trying dispensations, yet I trust they have not been without advantage to us;
as tending to wean from earthly dependencies,
and bring to a nearer fellowship with the true believers and followers of Christ,
in a suffering state.
When it is considered how much is wanted,
to remove the imperfections and weakness which we are sensible of,
it helps to reconcile the troubles we meet with;
perhaps the few good qualities we have are owing to the
afflictions it hath been our lot to pass through.

As it is our desire to be more prepared for our great Master`'s use,
and an inheritance with him in glory; if this is the way to it,
let us endeavour to be contented.
Whilst I write thus,
I can salute thee as a fellow traveller through the thorny paths of time,
towards a land of rest;
if our way should be more difficult than some others of our dear friends,
what will it signify?
A little more or a little less suffering, in so short a time as this,
is of no consequence,
if we are helped so as not to turn aside into paths which are unsafe for us:
it is better to suffer affliction with the people of God,
than to enjoy the pleasures of sin, which are but for a season.

But whilst I mention these troubles, it is with pleasure I have to inform thee,
that in divers parts of the nation there is the appearance
of a religious disposition prevailing,
especially among the youth of both sexes,
so that meetings are better attended than in former times,
and many have opened their mouths in a public testimony for truth;
this gives us a hopeful prospect of the approach of better times.
Though it must be allowed there is a great declension in many among us,
from the simplicity of truth, who have little more than an outward profession:
endeavours have been used to show them their danger,
and awaken to a serious attention to the things which belong to their peace; but,
in appearance with little effect.
Yet we must not be discouraged; the work is the Lord`'s,
and he can give success to the labours of his people: they will not be without a reward,
however much their message is slighted.

Divers friends in the ministry have attended our yearly meeting in Colchester;
it was observed to be large, with friends from most parts of the county.
I shall conclude with tenders of dear love to thee,
and friends of my acquaintance in your parts: though we are separated by a great water,
and have not much expectation of meeting again in this frail state,
yet the love which hath been raised in our minds towards each other,
is of such a nature as not to be easily lost.
Let us look forward to the happy time,
when we may meet in the realms of uninterrupted felicity;
no more to experience the troubles to which we are now subjected,
but may rejoice in having reached the peaceful abodes
prepared for those who have feared God,
and served him in their day and generation.

From thy affectionate friend,

J+++.+++ K.

Colchester, 30th 6 Mo. 1792.

Dear Cousin,

To hear of the health and outward prosperity of our friends is comfortable;
but to have some good hope concerning them and ourselves,
that the health of our minds is preserved through the Divine Messing,
and a careful attention to what is right on our parts,
will afford still greater occasion of thankfulness to the Author of all good:
may we be disposed to cast our care on the Lord,
having our dependence upon his all-wise Providence,
by which means we shall not be over-much cast down when troubles come,
nor lifted up when favoured with times of ease and liberty;
remembering that all comes from the Lord`'s hand,
whether it be mixed with bitter or sweet,
and will prove to our benefit if made a right use of.

I herewith send thee one of the printed epistle to friends of our society;
it appears by accounts received from different parts,
that the peace of the society is in a good degree preserved;
and a religious disposition appears in many;
though it is to be feared there are some among us,
who have not much more than an outward profession, yet of good reputation among men,
as to their moral conduct.
We are sensible it is not an outward profession of religion,
which will produce the good qualities that are wanted to adorn the true Christian,
and are obtained only by the work of grace upon the heart,
to cleanse and purify from defilement.
If this was experienced generally by the professors of the Christian name,
it might be called a golden age; however,
let us be thankful for the hope we have of the revival of religion in many places,
and pray that the work may go on to a further reformation.

We hear of great commotions and changes in the kingdoms of men,
but these will not make any changes in the kingdom of Christ; which is neither built up,
nor can be destroyed by human efforts; seeing,
(as the great Master hath said,) it is not of this world.

I am thy loving cousin,

J+++.+++ K.

Colchester, 29th 9 Mo. 1792.

Dear Friend C. P.

Though we are deprived of the opportunity of personal conversation,
there is an intercourse in spirit which no distance of time or space can deprive us of:
this I have felt in time past,
when thou hast been brought to my remembrance in that love and true esteem,
which I trust had its rise from a similarity of disposition and concern,
through the visitation of Divine goodness to our minds, and now in an advanced period,
is renewed to us from the Father of mercies, and God of all comfort;
which gives room to hope,
that after having passed through many storms in our passage over the sea of this life,
hitherto in a degree of safety, we shall be preserved to the end,
by the help of that arm which was our defence in the morning of our day.

When we look back on the varied scenes of life from youth to age, which we have known,
and find ourselves yet in the land of the living,
our days being lengthened beyond those of many of our relations and friends,
shall we not be thankful for this unmerited favour,
that a little more time is allowed us to prepare for that state which admits of no change?
And as we are sensible of a want of greater fitness
for an admittance into habitations of joy and peace,
after we leave this world, may it become the concern of our minds to walk in holiness,
of life and conversation, so as to please him who hath dealt thus graciously with us.

Though we may not come up, as advocates for the cause of truth and righteousness,
in the degree which might be wished,
yet it is a comfort to consider that we serve a kind master,
who requires not more of his servants than he gives ability to perform,
and accepts their offerings, if but like the widow`'s mite.
It is not by mighty gifts that the Lord`'s work is performed,
but through faithfulness in the little committed to our trust;
then it is productive of good.
All therefore have room to be encouraged to occupy their gifts, whether great or small,
like David, who went forth against Goliath with a stone and a sling,
and a great deliverance was wrought through faith in the Lord`'s power.
And thus it will be in the present time as we act in the ability received,
not trusting in our own strength,
but seeking for divine assistance in all our undertakings.

I mention this for the encouragement of my dear friend
and fellow-labourer in the gospel of Christ,
who hath had experience of the advantages of faithfulness,
and is waiting to fill up what remains of the portion of service allotted,
till it pleases the great Master to remove from works to reward.
I could inform thee of many changes which have occurred since thou wast in these parts,
by the decease of friends and otherwise; but it would not be of much use,
except to show the uncertainty of all earthly comforts,
and the instability of human affairs.

As to the state of our meeting, and the county in general,
I hope it may be said there is a revival of concern in the minds of many.
Our monthly and quarterly meetings are better attended than in former years;
and the good order of the Society preserved, to the comfort of the right-minded.
Though it must be allowed,
there is a want of religious concern in the minds of too many of the professed members,
which makes the weight of the work still to be heavy,
on those who are willing to do what they can towards promoting the good of the Society.
I trust we have been of this number, according to our measure; and if,
through want of bodily strength, and increasing years,
we are now less able to engage in service, our good-will remains to the cause;
and it will rejoice us to see others engaged in the same work,
that it may be continued from one generation to another,
by instruments whom the Lord may raise up,
to succeed those who shall be removed from a state of labour to everlasting rest.

These are with tenders of kind love, in which my wife joins, from thy affectionate friend,

J+++.+++ K.

Colchester, 8th 10 Mo. 1792

Dear Friend O. H.

My present writing to thee is from a motive of true respect.
Thy station in life and circumstance as a member of our Society,
have often been subjects of my consideration.
When many who are in affluent circumstances withdraw
from the profession in which they have been educated,
on account of the straitness of the path and singularities peculiar to it,
I have wished the same trial might not have the same effect upon thee;
but that whatever hath a tendency to weaken the connection
between thee and thy friends might be removed,
on account of the advantages likely to come from this connection,
first to thyself in the peace and comfort likely to be experienced,
and next to the Society,
from the honourable conduct which is produced by
attendance to the good principle in our minds.
The conditions of men are various, by the ordering of an all-wise Providence;
some are placed in eminent stations,
and have it in their power to do much good or hurt by their example; whilst others,
who are the greatest number, from their low condition,
cannot do so much towards promoting the good of society,
but want to be helped by the example and direction of those who have greater qualifications.
This is found true in families as well as societies and nations:
some are to be directors and helpers, and others want to be directed and helped:
and when there is ability and a disposition to help our fellow creatures,
we often see much good done.
I have thought that such as the rulers of the people are, such are the people.
This makes me wish that those whose outward circumstances
have placed them above many of their neighbours and friends,
may be disposed to promote the happiness of all within their reach,
by administering to the wants of such as are visited by illness and reduced to poverty;
as also to watch over their moral conduct,
from which much good or harm may come to themselves and families.

I write thus in freedom to my respected friend,
to encourage him to come forward as a useful member of the society,
in which he received his education, as also a promoter of the general good,
as far as his influence may reach.
I have observed of those who have been useful members of their own society,
that they have also been useful to other societies;
that our good-will is not confined to our own families and friends,
but we are willing to join in undertakings which
have a tendency to promote the general good.
And it becomes a cause of thankfulness when we can, in any degree,
be helpful to check the torrent of vice and immorality
which is spreading in town and country,
so as to threaten distress, if not ruin to the land.
Licentiousness and dissipation of life and manners,
have brought heavy rebukes from the great Ruler of
the earth on cities and nations in times past;
and they will undoubtedly have the same effect in future times.
Though the Almighty is long-forbearing, and does not afflict willingly,
yet if men go on to rebel against his righteous law,
and will not be reformed by gentle warnings and admonitions,
he permits heavier strokes to come upon them.

Let us be willing to do what we can to avert the judgments of the Lord,
by walking in his fear, who is the dread of nations,
and takes notice of the ways of the sons and daughters of men;
it is comfortable to think that we shall not suffer with them that do evil,
if we join not with them in their ways.
As the prophet declares, the Lord will spare those who fear him, and think upon his name,
as a man spareth his only son,
and they shall be his in the day when he makes up his jewels.

There is room to be encouraged to walk in the way of virtue,
and therein to persevere all the days of our life.
Though discouragements are met with, from reasonings and doubts in our own minds,
and from many things difficult to account for, which we see in others,
yet we may remember, that Truth is the same: and when any inconsistencies appear in us,
or in others, it is not to be placed to the account of the good principle we profess,
but to the propensity to wrong, which is in every mind,
and which would draw us all aside if given way to.

We must also expect changes in the state of our minds,
which are not easily accounted for; and here is the need of patience.
If we always went on smoothly, without any adverse circumstances,
where would be the exercise of Christian virtues?
Or how should we be prepared to bear afflictions which may come upon us?
It is truly said, that as gold is tried in the fire,
so are acceptable men in the furnace of adversity:--and
that those whom God loves he rebukes.

My writing thus upon religious subjects I hope will not be displeasing,
as it is from a good intention to recommend that which I consider as the greatest good.

I ask likewise thy companion to accept my best wishes,
for her further experience of the advantages of an
humble walking in the fear of the Lord:
thus she will become an ornament to the Society, and a blessing to her husband,
and be fitted for a removal from earthly enjoyments,
which will sooner or later take place, in the ordering of an all-wise Providence,
who hath given us life, and continued it to the present time,
with many accommodations and comforts, for which we have cause to be thankful:
and when it pleases him he can take them away,
having entrusted us with his gifts only as stewards,
who are to be called to account when the Lord shall see meet.

I subscribe myself thy affectionate and well-wishing friend,

J+++.+++ K.

Colchester 31st 11 Mo. 1792.

Dear Cousin,

In writing to thee at this time,
I satisfy a concern which hath attended my mind for some time past,
from motives of true respect and desires for thy welfare.

As it give me pleasure to hear of the welfare of
my friends in what relates to their everlasting interest,
so I also rejoice (though with fear) to hear of their outward prosperity,
and that their affairs are conducted with good reputation;
but in this there is a snare and danger:
we may forget the hand which hath conducted us thus
far and too much lean to our own understanding,
not remembering the need we still have of heavenly wisdom to direct our steps with safety.

As prospects of increasing advantage present themselves,
we may engage in that which will bring trouble,
and terminate in great loss as to our outward circumstances.
I write thus to my respected Cousin, whom I know not to be in want of these cautions,
but they may be of use in some future time, when fresh trials attend,
such as are not at present thought of.
I have known something of the hurt which comes from hastily proceeding,
in what hath been presented to my view with a specious appearance.
I did not look on both sides of the subject,
nor examine it sufficiently before I approved it,
and thus a foundation was laid for repentance.
We are weak short-sighted creatures, and have need to take our steps with caution,
asking for the direction and help of the Lord our Saviour,
to pass over the sea of this life,
in which there are many hidden rocks and dangerous sands,
not to be avoided but by the help of this good Pilot,
who offers himself to us for our preservation:
and well it is for those who are sensible of their want,
and desirous of taking him with them in the voyage!
Redirects us not to be careless when the sea is calm, and we go on, to appearance,
with a prosperous gale; but to have all things prepared for a change.
Nor is there need to be discouraged when storms are met with,
at the same time using the means he favours us with for our preservation.

I remain thy affectionate cousin,

J+++.+++ K.

Colchester, 16th 4 Mo. 1793.

Respected Friend J. T.

We are pleased to hear of thy family being restored to better health:
it hath been a sickly time with us, and many have been removed by death;
especially of those advanced in years.
The calls of mortality are frequent from abroad, and the infirmities attending us,
in our own particular, are intimations of our approaching change!
May we experience the Lord to be with us,
in the various afflicting circumstances which are permitted to attend us;
that as we have been helped in time past, from youth to age, we may be helped to the end;
not by means of our own wisdom or strength, in a natural state,
but through the sanctifying influence of Divine grace, which comes by Jesus Christ.
If we should trust in human help, it will be like a broken staff,
which will fail us in time of need; but if we trust in the Lord,
and expect our supplies from him, we shall have a powerful support,
sufficient in every exigency.
It is above all things necessary to keep near to him for direction and protection;
our Saviour will not forsake us if we do not forsake him;
but he does not compel us to walk with him.
He hath shown us the value of his friendship,
and invited us to partake of the privileges of his kingdom,
without taking away our liberty as rational beings; and when we are tried,
as every son will be whom he receiveth,
it should be our concern to approve ourselves faithful to him.

Thus I express my thoughts to a friend who, I trust, can understand me,
and agrees with me in the line of experience.
I shall only add, that I am thy affectionate friend,

J+++.+++ K.
