== Chapter 9

[.signed-section-context-open]
Colchester, 24th 2 Mo. 1795.

[.salutation]
Esteemed Friend,

The few lines last received from thee were acceptable.
An intercourse between friends on religious subjects is not without its use.
It will be good for us often to think of what relates to our best interest,
that we may be endeavouring to prepare for a better inheritance than this life affords,
which is, an heavenly.

I am requested to inform thee of the death of thy old friend Jane, of Bristol:
many of my friends and oldest acquaintance have likewise
been removed by death within a short time.
The voice of mortality is frequently heard, as though it was said to us that remain,
"`Be ye ready.`"
Let us desire above all things that we may be fitted for our great change,
that when the cry is heard, "`Behold the Bridegroom cometh,
go ye forth to meet him,`" we may have oil in our vessels, and our lamps trimmed.

I trust it is thy concern to seek for an interest in the favour of thy great Lord,
and in this I desire to join thee, with all the servants of Christ,
it the various names and professions.
We are apt to bring the number of those who constitute Christ`'s
church militant on earth into too narrow a compass.
I doubt not there are pious men and women, such who fear God and work righteousness,
among nations far separated from us, and unknown to us by name and language;
with whom we shall have to join in one song of praise and thanksgiving,
in realms of uninterrupted felicity when we lay down these mortal bodies;
as we are found among the Lord`'s faithful servants,
who have made improvement of the talent or talents given them, by the help afforded.

I remain thy affectionate friend and fellow-labourer in the gospel of Christ,
willing to do what we can to promote the happiness of our fellow creatures,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 28th 6th Mo. 1795.

[.salutation]
Dear Friend J. V.

Since thy last letter, which informed me of the death of our friend John Pemberton,
I have often wished to hear from thee, and to be informed of thy welfare:
it is not improperly said, that as "`iron sharpeneth iron,
so a man sharpeneth the countenance of his friend;`" but when outward
circumstances in life do not admit of a personal intercourse,
the frequent transmitting our thoughts in this way to each other,
helps to make up the deficiency,
and shows we are not unmindful of the connection of former times,
which came not from earthly motives, but I trust was formed in the Truth.

I hope the troubles which at present attend, by means of the war,
have not proved very hurtful to thee, as to thy business;
it is much to be desired that the contending nations were disposed for peace,
and instead of hurting and destroying, to do all the good they can to each other.
It had need to be so,
considering the mischiefs we are liable to from the frailty of our own hearts,
and the snares of a delusive world.
Our being of different nations, and of a different language,
should not hinder our loving each other; nor will it hinder,
as a Christian disposition prevails.
We shall wish for peace to be restored where it hath been interrupted,
not barely from views of outward gain, or fear of suffering in our outward concerns,
but from the sympathy we have with our fellow creatures;
many of whom are exposed to great difficulties,
and often deprived of their lives suddenly,
and it is to be feared in a state not prepared for such a change.

Some information concerning Alexander Wilson,
who accompanied J. Pemberton in his journey to Pyrmont, will be acceptable.
It must have been a great affliction to him to lose his friend in a distant land.

I was at the yearly meeting in London, held, as usual, in the fifth month;
it was continued by adjournment nine days;
many matters relating to the society came under consideration,
which were conducted in brotherly love.
At the same time,
we are apprehensive there is a want of Christian
piety in the minds of many of the present time,
who have received the form of religion from their fathers, and rest contented in it.

Yet in some places we see a revival of concern, especially among the youth,
which gives hope that the society will still be supported on its ancient bottom,
without a mixture of earthly views and self performances.

[.signed-section-closing]
I am thy sincere friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 28th 9 Mo. 1796.

[.salutation]
Dear Friend,

Thou hast been often in my remembrance since I heard of the difficulties attending thee;
and though it is not in my power to help thee, as to the settling thy affairs,
I sympathize with thee, in thy great troubles:
it was very unexpected to me to hear of thy being thus circumstanced;
as I had always considered thee as a man who had sufficient, in a plentiful way,
for thy own use, and much to spare for the help of others:
how it hath happened that thy circumstances are so altered, is best known to thyself;
if it hath been through mismanagement, I doubt not thou art sorry for it;
and if by losses, there is room to pity thee: but which ever way it comes,
it must have occasioned great distress to thy mind,
which I am not disposed to increase by anything I may say,
nor would I be instrumental to heal up the wound in a manner
which might not be consistent with thy true interest.

My affection for thee would lead me to speak in the
most tender manner on this sorrowful occasion;
but I consider, it is not all we can say to each other,
will satisfy our minds in trouble,
unless we can in some measure find access to His presence, who is the healer of breaches,
and restorer of paths to walk in.
I sincerely desire this may be thy experience; and, that what hath befallen thee,
may have its proper effect, to draw thee from a dependence on earthly enjoyments.

I take the liberty to say, that,
as thy conduct on the present occasion will be much observed,
I am desirous thou mayst do nothing that is dishonourable,
or inconsistent with truth and justice, towards those who have any claim on thy effects;
endeavour to get thy affairs settled,
so as there may be an equal distribution among thy creditors of what there is,
which will prevent reflections,
as if thou had made a reserve for thy own advantage to the injury of others.

An openness towards thy friends, and willingness to take their advice,
will also be an advantage.
I am with true regard and sympathy, thy affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 8th 11 Mo. 1796.

[.salutation]
Respected Friend,

Though I am cautious of meddling with affairs of government, as being out of my province,
yet I think the friendship between us will admit of mentioning to thee,
that it hath given me some concern to hear, it is proposed to direct,
in the new militia bill,
that the soldiers shall be exercised on the first day of the week, called Sunday,
in the same manner as on other days.
I am apprehensive, if this should take place,
it will tend to lessen the regard which is due to religious institutions;
and encourage that liberty which is already taken by many to slight the day,
and the duties of it.

Though there is no morality in observing one day more than another,
yet it is moral to show our regard to the God who made us,
by whose goodness we enjoy all we have,
by setting apart a certain portion of time for religious worship;
and this time should be fixed, for the use of all, lest if people are left at liberty,
some should be following their business and trades;
others their diversions and exercises;
to the great interruption of those who wish for retirement
from the cares of this uncertain transitory life.

These considerations, with others, which might be mentioned,
confirm to me the suitableness of having one day in the week allowed for public worship.
And I have observed, that those who endeavour to lessen the obligation of it,
by their practice, do not often prosper in their outward concerns,
much less in those which relate to the welfare of their minds.
And, if it is thus with individuals, it is likely to be the same in a more general way,
with societies and nations, who lay aside the obligations of religion and virtue.

I would not say more than is suitable on the subject,
as I have room to think thy sentiments upon it are agreeing with mine;
and I am not without hope, that there are many members in the house, who are disposed,
with thee, to countenance every endeavour which may be used to promote good order,
and regularity of conduct among the people,
and to discourage what is likely to have a contrary tendency.
That a blessing from above may attend their endeavours,
is the prayer of thy sincere friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 7th 1 Mo. 1797.

[.salutation]
Esteemed Friend P. H.

I have not yet had opportunity of reading the vol.
of J. Scharp, relating to the young man who was executed for theft.
I wish his untimely end, and the sad consequences of his principles,
may be a warning to all those who hear of it.

As thou observes, we live in sad times; such as the apostle speaks of;
which are full of danger, not only of receiving hurt to our bodies, and outward estates,
but to our minds, from the evil example of those with whom we converse;
in whose hearts it is to be feared, there is but little of that true sense of religion,
and fear of the Almighty, which is the preservation of men and women,
and a means of their departing from sin and evil.
Yet we have this to comfort us, that there are some, and I hope, not a few,
in the different societies professing the Christian name,
as likewise among the people of all languages and countries,
in whose hearts the fear of God hath taken place,
through the principle of Light and Truth which comes by Jesus Christ.
Let us pray that the number of these may be increased,
to the praise of our gracious Redeemer, and the welfare and peace of mankind;
that the time may hasten to come, which the prophet speaks of,
when the earth shall be full of the knowledge of the Lord, as the waters cover the sea;
and when he shall "`judge among the nations; and rebuke many people,
so that they shall beat their swords into ploughshares,
and their spears into pruning-hooks; and, nation shall not lift up sword against nation,
nor shall they learn war any more.`"

Every benevolent mind must wish for the time of this promise being fulfilled;
and though it may not be in our power to forward it in others,
let us desire to experience it in ourselves.

My wife and I accept thy good wishes for our prosperity, and in return, we may say,
thou hast the same from us, and that I am thy sincere friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 14th 1 Mo. 1797.

[.salutation]
Dear Cousin,

We must expect to meet with things which are unpleasant,
either from want of care in our own conduct, or from the misconduct of others;
but in all there will be instruction, as we exercise patience,
and are preserved in that disposition which keeps us humble.

Dear cousin, I am apt to express myself in this way,
when I write to such as have a large share of my love.
I find much occasion for the exercise of those virtues
which are the support of a Christian mind,
which makes me desire they may be continued, and increase; that as we advance in years,
we may grow in grace, and in the saving knowledge of the Truth;
and this I am convinced of, that as we happily experience preservation,
we shall be a means of helping our friends, if not by advice, yet by our good example.
There is a two-fold inducement to our being attentive
to the things which concern the peace of our minds;
that we first may partake of the privileges of religious conduct ourselves,
and then may be instrumental to communicate them to others:
and this is not effected by what we may say for the Truth,
so much as by our exemplary conduct,
which hath an influence on the minds of those we converse with,
and will do much towards promoting their good.
And considering the many deviations there are among us in the present time,
from the upright and honourable path in which our forefathers walked,
there is great need of those, both of the youth and aged,
who may show from a good conversation, that the Truth we profess,
and the principles of it, are the same as in time past;
and that it is sufficient to preserve those who adhere to it:
but we have occasion to remember, that when any good qualities appear in us,
they come from the Truth, and that there is no room to think well of ourselves,
because of them;
we have always occasion to be humbled in the sense of our weakness and frailty.

I do not mention these things because I think thou art not acquainted with them,
but by way of encouragement, that thou might put thy trust in the Lord our Saviour,
by whose mercy we have been saved, and delivered from a land of darkness,
and brought to see his marvellous light.

[.signed-section-closing]
I am thy affectionate cousin,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 17th 2 Mo. 1797.

[.salutation]
Dear Cousins J. and E. A--r.

Unpleasant thoughts concerning each other have no place,
when we feel that love to prevail in our minds,
which is said to hide a multitude of faults.
Such who have failings which are to be seen and felt, we pity and sympathize with,
considering them as wanting help, instead of being offended with them:
and those who are preserved, by means of watchfulness and prayer, from hurtful things,
we always have fellowship with, as we ourselves are walking in the Truth.

This, I hope, will be the experience of my dear cousins;
though we have to endure some hardship,
and to meet with what may be compared to stormy weather; and our days of sunshine,
speaking spiritually, may not be many;
yet having our expectation of help from the Lord alone,
we shall not be suffered to sink below what will prove for our good.
Let us endeavour to be contented in a humble low condition,
without those marks of distinction which some are fond of;
not that I would discourage from using endeavours to improve the gift bestowed upon us,
by a diligent practice of what we see to be right.
It is however, in spiritual things, as in the works of nature, what is slowest in growth,
and requires the longest time to bring to perfection, is most substantial.
But whether our experience is that of many years, or but few,
we are no longer safe from harms, but whilst we are under the Divine protection;
we want the same hand to help us to the end,
that was our help and preservation in the beginning.

As the apostle hath said, it is by grace we are saved, through faith,
and that not of ourselves; it is the gift of God.
Not by works of righteousness which we have done, but according to his mercy he saved us,
by the washing of regeneration, and renewing of the Holy Spirit.

We must not place a dependence on our own strength, or wisdom,
as though we were sufficient of ourselves,
but our trust must be in our gracious Redeemer; who, as he hath begun a good work in us,
will carry it on to our advantage, and the praise of his great name,
as we continue stedfast in our love to him, and are obedient to his requirings.

Having said thus much in the freedom which Truth gives, I remain your affectionate cousin,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 20th 9 Mo. 1797.

[.salutation]
Dear Relation,

Since I was at thy house thou hast been frequently in my remembrance, with thy children;
and though I am unwilling to introduce my advice,
I cannot well forbear to say something in regard to thy disposal of them; which,
if it should not meet with thy approbation, I hope will be harmless.

As to thy youngest son, I would advise thee to send him to some suitable school;
if he remains at home, he is likely to be hurt by thy indulgence,
and having too much liberty.
If it should cost thee a few pounds more than thou likest, consider it is for his good;
and if he should not make a proper use of it, thou wilt be the easier,
as having bestowed it with a good intention.
How canst thou spend thy money better than in the education of thy children?
Even if thou shouldst leave but small part of thy income for thy own use,
it will be prudent to do it.

As to thy eldest, I observe he is but poorly in his health,
which may in part be occasioned by too great indulgence.
He tells me, the doctor advises his drinking wine; this, I think,
is likely to hurt his health, instead of restoring it, unless taken very sparingly,
and with great moderation: I fear, some,
by the frequent use of wine and other strong liquors, in their young time,
have contracted a habit of it, which hath increased as they grew up,
to their unspeakable hurt.
Thus I take the liberty to give thee my thoughts, and am thy affectionate relative,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 1797.

[.salutation]
Dear Cousin,

The loss which thy brother and sister have met with, in the death of their son, is,
no doubt, a great affliction to them; but troubles are not without their benefits,
if rightly improved: it is of our frailty,
that when disappointments and losses have loosened our hold on earthly objects,
we are soon apt to forget ourselves, and the instability of all things here below:
so that repeated sorrows are necessary to keep us in our places,
and bring us to look to him who is the source of true comfort,
and only support of his people.

Thy expressions of thankfulness for mercies received,
give room to hope a religious disposition hath taken place in thy mind;
than which no greater good can attend us, in youth or age:
I much desire it may remain with thee,
as thy preserver from harms to which thou art exposed, with others of thy friends.

Many things are said in the Holy Scriptures concerning the benefits of religion,
that is the fear of God;
but nothing more than is found true in the experience
of those who are happily preserved in it.
We must take care not to lay an improper stress upon notions of religion,
which are obtained by means of education;
they will not do much for us towards subjecting our irregular passions;
but we may expect great good to come from this Holy fear.
As it was the preservation of Joseph, in the severe trial which attended him,
and the means of his advancement, so it hath been of thousands and tens of thousands,
in different ages of the world:
it is like a star to direct us to the place where the Saviour lies, and when he is found,
there will be more joy experienced,
than all the treasures and pleasures of this world can afford.

I am led to say thus much, from a desire to encourage thee in thy exercise,
wishing thy way may be made prosperous to thee,
by the blessing and help of our gracious Redeemer; that thou mayst hold on,
in well-doing, and have to receive the rewards of faithfulness,
when the labours and exercises of this state of trial are over.

[.signed-section-closing]
I am thy affectionate cousin,

[.signed-section-signature]
J+++.+++ K.

[.salutation]
Dear Friends,

You hare been often in my remembrance,
with desires that if we are favoured to meet again in this uncertain state,
it may be in the same love which hath subsisted between us in time past.
That after having passed through some storms, and escaped the dangers attending,
we may commemorate the Lord`'s goodness to us,
and renew our endeavours to serve him more faithfully,
who is worthy of obedience and praise!

We must expect it will happen to us, that as age increases,
we shall be less able to act in that: good cause, which I trust we wish to promote,
than in days that are past; but we do not serve a hard master,
who requires more than we are able to perform.
With his assistance, if we are willing to join in the work,
no doubt it will be accepted by our great and good Master!
Though we should have some difficulties to wade through,
I would have us trust in the good providence of the Almighty,
which hath hitherto been our support.
Considering the favours we have received,
and how we have been helped along from time to time,
there is room to take courage and say with David, "`In thee, O Lord, do I put my trust,
let me not be ashamed, for I have called upon thee.
O how great is thy goodness, which thou hast laid up for them that fear thee,
which thou hast wrought for them that trust in thee, before the sons of men.
Be of good courage, and he shall strengthen your heart, all ye that hope in the Lord.`"

Thus I endeavour to comfort my friends,
with the words of one who had known great troubles and great deliverances:
and we shall know the same power to help us, as we depend upon it.
We are sorry to hear of your son`'s illness:
in all our afflictions we have need to desire they may be sanctified to us,
so as to promote the welfare of our minds,
and tend to fit us for a better inheritance than is to be
obtained in the perishable enjoyments of this life.

In the bond of true friendship I remain your affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 5th 10 Mo. 1797.

[.salutation]
Dear Friend J. A.

I have not lately heard of the friends at Pyrmont and parts adjacent.
I hope they remain steadfast in that love which hath
been raised in their minds towards the truth.
After having been visited by the Lord`'s servants,
and receiving comfort and encouragement in their exercise,
there will be occasion to retire to the gift in themselves,
and in that wait for strength to persevere in the path of safety:
for want of this many have grown weary and faint in their minds,
when the help of their friends hath been withdrawn.
The welfare of this people, and of all who have been convinced of the truth,
and had their feet turned into the way of holiness,
depends upon their minds being withdrawn from support which may come from without,
by instrumental means, to that great and never-failing strength and support,
which is found in a humble waiting upon him,
who hath promised to be with his people to the end of the world,
which is our Lord and Saviour Jesus Christ.
The more they are acquainted with this, the better it will be for them.
Indeed it may be said, that unless this becomes their concern,
however promising their first movements may be, a declension will follow,
and their latter end will not be like their beginning.

[.signed-section-closing]
I remain thy affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 13th 11 Mo. 1797.

[.salutation]
Much respected Friend,

I have not been contented with once reading thy valuable treatise,
in which are many remarks that meet with my approbation.
Neither can I be satisfied without expressing the good esteem I have for the author,
and that I wish he may be encouraged to persevere in such offices of love.

It is a sad truth, that many of the professors of the Christian religion,
in all the different societies in this and other countries,
have little more than the name, which they come at by means of their education,
and being born of parents who made the same outward profession.
Alas! what will this do towards making us Christians?
When we are brought to a sense of our state, by nature,
there will be no dependence on the name we may bear among men;
but seeking for that renovation of heart, by which we can be made acceptable to God,
through his Son Jesus Christ.

In the present time of great unconcernedness as to religion,
it is to be considered as a favour and blessing to a society or nation,
when some are awakened to see their state, and the need they have of a Saviour:
these are not contented to partake of their privileges alone,
but in that love which hath filled their hearts, are ready to say to others, "`Come,
taste and see how good the Lord is.`"
And such as these have often been instrumental in the hand of God to promote his cause;
and their labour hath been blessed with success to the good of souls.
Thus I hope it will be with thy well-intended work.
It would be a good thing if all who take upon themselves
the instruction of the people were thus disposed;
but how can they instruct others in what they are ignorant of themselves?

I have to consider that the ministers of Christ must
have their qualification and ability from him,
after all the ordination and appointment of men: and the good of the people,
in a great measure,
depends on the example and right disposition of those who are in the station of ministers.
It is not likely that any church or people should be in a prosperous state,
as to the life of religion, whose teachers are unrenewed in their minds,
and without the saving knowledge of Christ; formal professors, and nominal Christians,
such as are described in thy work.
If the blind lead the blind,
it will not be difficult to know what will be the consequence.
We have occasion to pray to the Lord of the harvest,
that he would send forth faithful labourers into his harvest,
that souls might be gathered to him by the work of grace in their hearts,
and the necessary reformation be begun and carried on, to the praise of his great name.

I would further remark, as my apprehension of what constitutes our real good;
that nothing hath so great a tendency to unite the
people and those who are appointed to be their teachers,
as being united in their hearts to God by the work of his spirit,
as the apostle expresses it; "`If we walk in the light, as he is in the light,
we have fellowship one with another,
and the blood of Jesus Christ his Son cleanses us from all sin.`"
In this consists the true fellowship of believers,
not in being joined in outward fellowship by a formal profession.
This may serve in a political sense; but the religion of Christ is of a different nature;
there can be no true union with him, nor one with another,
but through the work of his grace in the heart, bringing into a conformity to him,
and humble walking before him in watchfulness and prayer.

I am not writing thus,
because I think my valued friend wants to be informed concerning these truths;
but it is by expressing our thoughts one to another
that minds religiously disposed receive comfort,
and are encouraged to persevere in the safe, though difficult,
path of obedience and devotedness of mind to their great Master.

Fellow soldiers in the Christian warfare, +++[+++we]
are endeavouring to promote the good cause: and I hope there are many such,
who are personally unknown to each other,
distinguished by different names as to religious profession,
but who will be joined together, as members of Christ`'s church, in that society,
where names and distinctions, like those among men, will come to an end,
and be no longer a cause of separation.

I shall only add, that as my writing is from a motive of respect,
and to express my unity with thy concern, I am the less afraid of giving thee offence.
Wishing good success to all thy endeavours,
and that the same spirit which influences and animates to
come forward in whatever tends to promote the public good,
may be thy support,
so as to have thy mind at liberty for the great and principal business,
which is to preserve an intercourse with Him whose
favour is beyond all the favour of men,
I remain thy sincere friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 13th 4th Mo. 1798.

[.salutation]
Dear Friend R. R.

I have before me thy kind letter of the 28th 2nd mo.
which afforded me pleasure.
I know not of any one whose remembrance of me would have been more acceptable,
as I have had a true respect and love for thee,
from the short personal intercourse between us, from time to time, for years past.
When there is a likeness of disposition, it requires not a long time,
nor the use of many words, to form a true friendship: thus it hath been with me; so that,
when we have met, the same love hath been renewed in my mind,
though I might not have opportunity to express it.

These are times of much exercise and pain to the Christian traveller,
in which he hath but few companions;
it is therefore matter of comfort to meet with those who are disposed to join with him,
and take a share of the difficulties of the way.
And thy concurrence with my concern is comfortable to me;
it is like holding up the hands which are ready to hang down,
and strengthening the feeble knees,
as a messenger of peace from my great and good Master, whom I have endeavoured to serve,
though in much weakness, and have cause to be thankful in his service,
and to say he is good to them that serve him.
A remnant have to speak well of his name.

I am thy affectionate, and nearly united friend in the truth,

[.signed-section-signature]
J+++.+++ K.

[.letter-heading]
To the Editor of the Gentleman`'s Magazine.

It will be considered as a favour,
if the editor of the Gentleman`'s Magazine will insert the following short hints,
by way of caution to the writers of a new biographical dictionary, about to be published.

In the various biographical works which I have seen in the English language,
we have no account of divers eminent persons, both men and women;
so that a work of this kind will admit of further additions from various authors.
And I could wish it might be free from unkind reflections on religious societies,
taken from the writings of adversaries; which, when strictly inquired into,
will be found groundless,
and a misrepresentation of the matter of fact and true state of things,
particularly in what is said in most writers concerning the people called Quakers.

The compilers had need be cautious of depending on the accounts given, in many works,
relating to this society,
as I apprehend the state of it is not so well known as it ought to be,
in order to do justice to its character:
what hath been said having no better authority than the
writings of those who were prejudiced against them.

It is true there have not been many learned men among them--that is,
such as have had the knowledge of many different languages; but there have been,
and still are in this society many excellent persons,
who are distinguished by their probity and honourable conduct as citizens,
as well as by their religious endeavours to promote the cause of piety and virtue,
in the places where their lot is cast;
not confining their good-will and regard to those of their own persuasion,
but ready to do good to all of every different society or persuasion.

[.signed-section-context-open]
Colchester, 9th 5 Mo. 1798.

[.salutation]
My esteemed friend and old acquaintance,

It afforded us pleasure to hear of thy being as well as usual in health,
with thy wife and daughter, of whom we have a respectful remembrance.
Thy two poems on religious subjects were acceptable to us;
we value them the more on account of thy great age, which, if I am rightly informed,
is near to ninety.
They show thy thoughts are employed on subjects,
which help to prepare for the society and company of those,
who are no longer interrupted by the cares and concerns of this life,
but are now at rest with their great Lord and Master,
whom they endeavoured to serve in their generation.

My desire is, that we may be so preserved in the love and fear of the Lord,
as to meet in those happy regions, where the wicked cease from troubling,
and the weary are at rest.
This from thy sincere friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 23rd 8th Mo. 1798.

[.salutation]
My much respected Friend G. D.

What changes have we seen in the few years which have passed since we first met with
each other! and what may we yet see if our lives should be prolonged! but that Truth,
in which we most certainly believe, remains unchangeable,
and may be depended on as a support, in all changes, which are permitted to attend.
I have thought there is nothing better for us,
than to commit our concerns into the hands of our heavenly Father,
whose mercy hath been extended to us, so that we have not fainted,
nor been weary of putting our trust in him.
There is this advantage to us, that when outward help fails,
we are turned towards that help which never fails to those who put their trust in it.

The disappointments we meet with may be necessary,
in order to wean us from all confidence in man,
and to bring us to a more full dependence upon our principal good.
I write thus in a sense of the low state of things, as to religion,
in many parts of the society,
and the danger we are in of being leavened into the same worldly spirit,
which too much prevails among the professors of Truth.
Let it be the request of our minds,
that we may be preserved in this time of danger from harms, in this and every other way;
that we may faithfully serve our good Master,
and please him who is graciously pleased to employ us, as instruments in his hand,
to promote his cause.

[.signed-section-closing]
I remain thy affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 21st 9 Mo. 1793.

[.salutation]
Dear Friend W. P. of Haarlem,

Though we are far separated, and have not much room to expect we shall ever meet again,
in this mortal life, yet we may remember one another in that love,
which is not to be dissolved by distance of time or space:
in this love I often have to remember my friends, and, among others,
thou hast a share of my friendship and love, with thy wife and sisters,
which I request thee to mention to them.

I herewith send thee a small book in English,
containing extracts from the writings of Fenelon,
which I think will afford thee pleasure.

I shall like to be informed, concerning the state of things in Holland,
whether there appears to be a revival of religion
among the professors of the Christian name?
When troubles are met with, they have a tendency to waken us to enquire after something,
more substantial than bare outward form, to rest upon.
I hope they have had this effect,
in the minds of many of the different religious societies with us,
which hath occasioned many advocates for the Truth, as it is in Christ, to appear,
both by writing and otherwise: yet there is cause of mourning,
for the desolations occasioned by the prevalence of a worldly spirit;
and it is to be feared,
the displeasure of the Almighty will break forth upon us for our wickedness,
if there is not a timely repentance, and forsaking the evil of our ways.
Let us pray for an increase of that love and faith,
which produceth the fruits of righteousness,
that we may contradict the aspersions of unbelievers and wicked men;
and show that our religion hath power to regulate the disorders of nature,
and to introduce that peace and harmony in which the welfare and happiness of men consists.

I am not inclined to say much concerning national affairs.
I consider it to be consistent with Christian principles,
for us to submit to the government under which we are placed by the permission of Providence;
having no animosity in our minds against any because
they are of different sentiments from us,
or of different nations, still aiming at their good,
even if they are disposed to hurt us.

It is likely thou hast heard of some of our friends being now in Germany,
upon a visit to a little society of persons, who make profession with us, at Pyrmont,
and some places adjacent.
We have been informed of their arrival there by way of Hamburg and Hanover,
but not of their further proceeding.
It hath been much the concern of our ministers, of late, to visit distant parts,
and have meetings for the purpose of religious instruction with people not of our society;
not so much with a view of bringing them into our way,
as to excite in their minds a concern to seek after that which
is the substance of religion in which their true happiness consists.

I shall only add,
that it will he pleasing to me to have the correspondence between us continued,
whilst our lives are spared and health admits.

With tenders of kind love I rest thy sincere friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 4th 5 Mo. 1799.

[.salutation]
Dear Friend W. P.

Though the intercourse between us is much obstructed by means of the war,
that love which is founded in true friendship will still remain;
the contest of nations will not be able to disunite the followers of Christ,
or occasion a breach of friendship between them, as they keep near to him,
who is the promoter of peace: but as we are separated from him, in our hearts,
there is a danger of falling a prey to the enemy of mankind,
who is the destroyer of peace.

Happy is it for those who are influenced by a Christian spirit,
so as to bear with patience the injuries they receive,
instead of contending one with another, and making returns of evil for evil;
by which means breaches are enlarged, instead of being healed and restored.
I can say, from the love I bear to both countries,
it grieves me much that they should be at variance with each other: and my prayer is,
that the hearts of the rulers may be disposed to seek for peace!

In the space between my writing to thee, and my receiving thy letter,
I was informed of the death of our friend John Vander Werf, of Amsterdam.
This I consider as a loss to the society, especially in the place of his residence,
where few, if any, are left to support the testimonies we, as a people, have to bear:
but as they are upon a good foundation, and not barely the contrivance of men,
let us hope they will not fall to the ground,
but that others will be raised up to bear testimony to the same truths,
which we have believed; and that the substantial part of the religion of Christ,
which we are professing, will be preserved in the churches, to his praise,
and the benefit of nations.

What the present troubles may produce it greatly hid from us; it is to be hoped,
with regard to many, that when the judgments of the Lord are in the earth,
the people will learn righteousness.

As thou observes, there hath been a concern in several societies with us,
especially among the dissenters, to send missionaries to distant parts of the world,
where the name of Christ hath not been known, with a view to civilize the inhabitants,
and bring them to the knowledge of the Saviour.
I hear another society is likely to be formed for the same purpose,
by those of the national church.

[.signed-section-closing]
I am thy affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.postscript]
====

P+++.+++ S. If thou writes to me in answer, please to let it be in the Dutch,
which I can very well understand.

====

[.signed-section-context-open]
Colchester, 14th 6 Mo. 1799.

[.salutation]
Dear Friend,

It affected me to hear of the sudden death of thy sister,
with whom I had spoken but a few days before, when she was, to appearance,
in good health.
This is a fresh instance of the uncertainty of life, and confirms the saying,
that "`The old must go, and the young may.`"
We often hear of young persons being taken from their earthly habitations
(of which they have an uncertain tenure) to their long home;
and of many sudden deaths of both young and old;
which are like calls upon us to be prepared, through Divine assistance,
for this awful change.
And as we know there are rewards of our obedience,
and punishments for our unfaithfulness, in a future state,
these should be an additional excitement to watchfulness and care.
To be deprived of some good,
which by a proper conduct might have been obtained and secured,
if the loss is attended with sorrow and regret, is certainly a punishment;
and if it always lasts, is an eternal punishment.
Thus we are called upon, by all that is desirable in this life and the life to come,
to be religious and virtuous; to live in the fear of God,
and deny ourselves the gratification of any desire,
which is contrary to the dictates of truth in the secret of our minds.
It is truly said, "`Peace is sown for the righteous,
joy and gladness for the upright in heart.`"

If we have some pain in parting with our criminal pleasures,
we have that in return which far surpasses the value of gold, that is, peace of mind,
the good man`'s treasure!
This will be our reward, if we hold on our way in well doing;
but we have need to remember, there must be the exercise of faith and patience.
What is valuable and worth our having is come at by degrees, and with difficulty;
and without watchfulness, in the fear of the Lord,
we may lose all the advantages which have been obtained.

Thus I express my thoughts; the reading of which I hope will not be unpleasant to thee.
Next to my own good, there is nothing I more desire,
than to excite in the minds of my friends the love of God,
which is the love of virtue and holiness; and this I desire may be thy happy experience.

[.signed-section-closing]
In much affection, I am thy sincere friend,

[.signed-section-signature]
J+++.+++ K.
