== Chapter 11

Colchester, 1st 11 Mo. 1804.

Dear Cousin,

It is a cause of comfort to receive tokens of each other`'s love by a correspondence;
which makes me willing to acknowledge the receipt of thine of the 8th and 9th mo.;
both which were acceptable to me, as I wanted to be informed concerning thy health,
as also of our dear friend M. P. I do not recollect any thing in particular
to mention concerning friends of thy acquaintance this way;
we have had no friends upon religious visits since I saw thee;
indeed there is a great alteration in this respect, so that,
instead of having friends frequently travelling in the work of the ministry, many weeks,
if not months, pass over without our being visited by any, from far or near.
We are ready to think the help of those who are concerned for our good is wanted,
in the present state of the society;
but it will be best for us to endeavour to be contented,
and instead of having our dependence upon help from without,
to look to him who is the great helper of his people; whose promise is,
that he will not forsake those who put their trust in him.

It will not be without advantage to us, when we have to suffer want in a spiritual sense,
if our attention is turned the right way.
We have need to know how to want, as also how to abound, and in all states to be content.
The request of our minds should be, that we may be helped so to steer our course,
as to give no just cause of offence to any with whom we may converse,
nor lose the favour of him who hath called us to be his servants.

I consider the people among whom thou hast taken up thy residence,
to be high in profession, having a favourable opinion of their own way,
so as to think meanly of our appearance, which is different from it.
They will be observing thy conduct, some from a friendly motive, and others,
it is to be feared, from an unkind disposition; ready to wonder at our proceeding,
which is so contrary to the way in which they have been educated;
but whatever they may say or think concerning us, this we know,
that the good principle we make profession of, is sufficient to preserve us,
as we adhere to it, and walk according to its dictates.

I say not this from an apprehension of dangers attending thy situation beyond many others,
but by way of caution;
and that thou mayst not be discouraged by unexpected trials which may be met with.
We shall have to meet with that which is unpleasant in every condition of life,
as a trial of those good qualities which we have occasion to know an increase of,
even if we should happily make further advances in
religious experience than we have yet made:
there will still be occasion to say with the apostle,
"`Not as though I had already attained, but I follow on to know.`"
The lower thoughts we have of our present attainments, the better it will be for us,
because there is something left to make us fit for
an admission into those mansions of rest and peace,
into which nothing that is unclean can enter.
We have nothing to speak of but our infirmities,
nor anything to place our dependence upon, but the mercies of God,
through our Lord and Saviour Jesus Christ.
May we still look to him for help and direction in all our concerns,
whether small or great.

I have thus enlarged my writing beyond what I had expected, and shall not add any more,
that I am joined by my wife and cousin A. D. in kind love to thee,
and our mutual friend with whom thou resides.

From thy affectionate cousin,

J+++.+++ K.

Colchester, 13th 2 Mo. 1805.

Dear Nephew,

The loss I have met with in the decease of my dear wife, is indeed great;
the want of her good company and sweet conversation, which I am now deprived of,
in my far advanced years, often occasion tears of sorrow to fall from my eyes;
at the same time,
the well-grounded hope which I have of her being admitted
into those mansions of everlasting rest and peace,
where all troubles are at an end, is a cause of comfort and consolation to my mind.
In humble submission to the dispensations of Providence,
in this and many other afflictions which have been
permitted to attend in my passage through life,
I am helped measurably to say, "`the Lord gave, and the Lord hath taken away,
blessed be the name of the Lord.`"

I observe what is said in thy letter concerning the
alteration likely to be made in thy temporal affairs,
which may occasion an increase of property.
All concerns of importance I have found to be attended with trouble,
and to require prudence in conducting them,
lest in one way or other they should be hurtful to us.
We are liable to many harms as to our spiritual condition,
from which nothing less than Almighty Power,
which is in and through our Saviour Jesus Christ can protect us.
Let us therefore pray, that we may be still disposed to look to him,
and put our trust in him, who is the only sure defence of his people.

I approve of thy remark, that if we should not agree in some circumstances,
as to the ceremonials of religion, this need not set us at a distance from each other,
as disciples of a crucified Saviour.
If his love does not take place in our minds, no ceremonies which we may make use of,
will supply the deficiency.
The rule which our great Lord hath given, by which it may be known we are his disciples,
is, that we love one another; and this follows, that as we love him,
we shall love one another.
The outward separations among us,
which are occasioned by different apprehensions of things,
and the prejudices of education,
will not prevent a harmony of spirit between the lovers of Truth.

This my late dear companion had to experience,
in which her heart was enlarged towards her relations and friends, and all mankind.
The remembrance of it is sweet beyond what I can easily express,
and the hope of being again united with her in this love,
and in the more full fruition of it, in a future period,
is a principal cause of comfort to my mind.

Nothing further occurring to mention but my kind love to thee and thy wife and children,
I subscribe myself thy affectionate uncle,

J+++.+++ K.

The removal of my dear wife was very sudden, being affected with a palsy,
by which she soon lost her speech.
She had room to expect what would be the event of it,
from what she had met with about three years before,
when a disorder of the like kind attended her, from which, in a good degree,
she recovered.
Many circumstances then attended which showed the comfortable state of her mind,
and resignedness to the will of her heavenly Father.
Some of her expressions were preserved, which I much value,
and intend to preserve as a sweet memorial of one whom I greatly loved and esteemed,
as a disciple of her Lord and Master,
and for her good understanding both in a natural and religious sense.

Colchester, 27th 8 Mo. 1805.

Dear --,

Since I received thy letter,
the contents of it have been a frequent subject of my consideration.
I sympathize with thee in thy affliction,
and wish to advise thee to that which may be to thy real advantage.
The want of unity with thy public appearances, as a minister,
in a friend whom thou esteemest, is hard for thee to bear,
and must be a great discouragement to thee, if not prevent thy further proceeding.
I may tell thee how I should desire to be helped to conduct myself towards a friend
who takes the liberty to express his disapprobation in the way thou hast mentioned.
First I should be careful not to admit any displeasure in my mind,
so as to obstruct the intercourse there had been between us,
and endeavour to show I was not offended.
If his judgment concerning me was well founded,
it might be a means of keeping me in that order which tends
to promote my own good and the peace of the church.
If he is dissatisfied without any just cause,
I would desire to say in the words of David, "`Let the righteous smite me,
it shall be a kindness; and let him reprove me,
it shall be as excellent oil which shall not break my head,
for yet my prayer shall be in their calamities.`"

We have great occasion to be prepared for trials such as thou hast met with,
and others which may be permitted to attend.
I wish thou mayst be enabled to bear them all with Christian patience.
As our conduct is answerable to the advice we may give,
it is a sign we are fit for the station of ministers.
And nothing will tend more to remove doubts concerning us,
than when we show a Christian spirit one towards another,
by taking all we meet with in good part.

If thou findest the way obstructed, for want of the full concurrence of thy friends,
I would advise thee to be cautious; as to thy public appearance, exercise patience,
and be not over much disturbed at it; if thy concern is right,
I doubt not the way will be opened, to thy comfort and the edification of thy friends.
There is more wanted for our refinement than we are aware of.
None of us will come to be what we ought to be, without renewed conflicts,
and fresh crosses and disappointments.

Having thus given thee my thoughts on the subject mentioned, I remain thy sincere friend,

J+++.+++ K.

To my dear Friends of the Quarterly Meeting of Ministers and Elders,
to be held at Chelmsford.

Being prevented by weakness and bodily infirmity from attending the meeting as usual,
I am inclined to express, by a few lines,
the regard and esteem which is in my mind towards my friends who constitute this meeting;
with desires that a blessing may attend their endeavours
to promote the welfare of the society.

When it is considered how much depends upon the conduct of those
who are placed in the station of ministers and elders,
it may well occasion desires in our minds that we may be preserved walking in the truth,
as good examples in our families and in the society;
that so we may be instrumental in the Lord`'s hand, according to our several degrees,
to promote his cause.

I send this as a salutation of true love from your affectionate friend,

J+++.+++ K.

Colchester, 11 Mo. 1805.

Dear Friends J. and A. H.

You have been frequently in my remembrance, both before and since I was at your house,
with desires for your welfare, as likewise your dear children;
which I am inclined to express by a few lines as a brotherly salutation.

I consider your situation to be attended with some difficulty and danger,
among a people who will be forming favourable or unfavourable
sentiments of you and the society of which you are members,
from what they may see in your conduct.
Experience shows,
that when we are placed in a situation which exposes us to the notice of our neighbours,
who are of different sentiments as to religious profession,
there is need of much circumspection, lest we should give any just cause of offence:
whilst we cannot, with safety, conform to many of their customs and ways of behaviour,
we may show them we are disposed to promote whatever hath a tendency to their good,
and are friends to them beyond all those forms and ceremonies which
we are led to decline from a tender scruple in our minds,
lest we should deviate from that plainness and simplicity
in outward deportment which becomes a Christian profession.

I would not have you discouraged on account of the smallness of your number.
If you are willing to assist one another in all the offices of friendship and love,
it will compensate for the want of numbers.

These are as a token of true regard and esteem from your affectionate friend, J. K.

Colchester, 23rd 11 Mo. 1805

Dear Cousin J. B.

I would not have it thought I slight thy correspondence
because thy letters are sometimes long unanswered.
Since thy last letter came to hand,
various engagements have prevented my paying so much attention
to these offices of friendship as I wish for,
besides being absent from home on account of my health.
As age increases I find weakness beyond what had been usual in former times;
yet there is cause to be thankful that I am able to get abroad and attend,
in a good degree, to my usual concerns, of helping the necessitous,
of whom there is a large number in the place of my residence.

It always gives me pleasure to hear of thine and thy husband`'s welfare,
with thy respected mother and relations in Cornwall,
to whom I request thee to mention my kind love.
I have met with a great loss in the removal of my dear and greatly valued wife!
Her memory is precious to me beyond what words can express.
The earthly ties are broken, but those ties which were formed in the Truth,
I trust will remain beyond all the confines of time, in the regions of everlasting peace,
where all the infirmities of these earthly tabernacles will be no more!
Thus I am apt to write concerning one I so much loved; not to exalt her character,
but that we may be excited to follow her example,
till the days of our pilgrimage here are ended.

I remain thy affectionate cousin,

J+++.+++ K.

Colchester, 28th 1st Mo. 1806.

Dear Friend D. B.

I received thy letter of the 9th mo.
last, which was very acceptable as a mark of continued friendship.
I am desirous of having the correspondence with thee
and others of my dear friends kept up,
whilst strength admits, in my far advanced years (being entered into my eightieth year);
it is a comfort to me to be informed of their welfare,
and to express a little my thoughts by writing,
when no opportunity is afforded of personal conversation.

Though we have to experience weakness and bodily infirmities,
with other trials which attend,
it is to be considered as a favour that we are not wholly confined to our apartments,
nor prevented from having the company of our friends.
It is true we cannot bear any great exertion of body or mind,
without being affected so as to deprive us of the comfort we may wish for,
and interrupt that peace and rest which I trust we are desirous
to partake of before our removal from this frail state of being,
in which we have had our share of troubles, intermixed with blessings and favours.
I unite with thee in considering it a favour to us, after the losses we have met with,
by the removal of our dear and much valued companions
and partners in a religious and social capacity,
that we have religiously disposed persons to help
us in the management of our domestic affairs,
as well as to advise with occasionally in matters which require our notice.
It will be pleasant to hear from thee when convenient.

I am thy affectionate friend,

J+++.+++ K.

Colchester, 25th 3rd Mo. 1806.

Dear Friends,

In the same love which first united us,
and was the ground of our acquaintance in years that are past,
I very affectionately salute you.
Though we are far separated from each other,
and have but little room to expect we shall ever meet again in this transitory state,
there is a friendship formed in the Truth, that will remain after many days,
which "`many waters cannot quench,
nor the floods drown;`" this will be revived when
we have no opportunity of personal conversation.

I expect you have been informed of divers changes
which have occurred since your leaving this land,
by the decease of friends with whom you were acquainted,
and among others my dear and much valued wife;
concerning whose illness and decease I am inclined to give you a few circumstances,
as follows.
On the 15th of 3rd mo.
1802, she was suddenly affected with a palsy, which for a time deprived her of speech,
and other faculties, except her recollection and memory, which appeared to be clear;
and it might be seen she was in a quiet state of mind.
The next morning, her speech being a little restored, she said to her cousin,
"`What a poor creature I am to be thus favoured: all is favour.`"
She wrote a few lines to a relation, sweetly expressive of the good state of her mind.
Her cousin, who slept with her the next night, says, in a short account of her illness,
"`It is pleasant to wait upon her, she is so satisfied with the little I can do for her;
indeed she is so with all about her, so that it is truly instructive to be with her.`"

In the night of the 21st she thus expressed herself to one present,
"`The Lord is good to Israel, to all those who are of a perfect heart; ah,
perfect! but I am perfected by Him!
What a poor creature I am to be thus favoured; many,
who have lived more in the fear of the Lord,
are not so favoured.`' At another time she said, '`To go is desirable,
but I feel no anxiety as to the event: patience is a great favour;
I wish I may be preserved in it to the end.`'

On the 24th she was remarkably cheerful, and satisfied with what was done for her;
no complaining, all acquiescence in the Divine will:
in the evening her husband coming into the room she said,
"`Here comes my dear husband;`" and upon his saying, "`My dear,
thou mightest have said thy old husband,`" she replied, "`Ah, new and old.`"

On the 26th she took the air in a sedan, and was cheerful and serene all the day.
Some gruel being brought to her in the evening, she observed it was too salt, but added,
"`salt is a good thing, it is of a cleansing nature; have salt in yourselves,
the salt of the kingdom,--this is an excellent thing.`"

On a friend, with his sister, calling upon her for a few minutes, she said,
"`this short interview hath been very refreshing to me.`"
As she was sorting some small books on religious subjects,
to be handed to her friends and neighbours occasionally, as she had been used to do,
one present said, "`perhaps they will never be read;`" she replied,
in the words of Solomon, '`Cast thy bread upon the waters,
for thou shalt find it after many days.`' We know not into whose hands they may come,
and they cannot do hurt.`"

She once said to her cousin, that in case of her removal,
it was her desire to have a quiet, well ordered burial;
that her remains might be wrapped in a shroud of flannel, not of the finest sort,
and that her coffin might be plain, not highly polished;
that there should be no invitation beyond near relations,
nor any great attendance at the house before or after the burial,
but if any friends should have a desire to sit with the relations in the afternoon,
she had no objection.

To the foregoing account of the illness of my dear wife I may add,
that she so far recovered from it as to associate
with her friends as usual in former times,
and was a diligent attender of religious meetings.

In the years 1803 and 1804 she was at the Yearly Meeting in London,
to her own comfort and the edification of her friends.
She remained in a good state of health,
more and more endeared to her friends and neighbours by her exemplary conduct,
till the 5th of 1st Mo. 1805,
when she was suddenly affected with the same disorder
which had attended her about three years before;
by this she was soon deprived of speech, except saying to her cousin who was near,
"`Be not disturbed, I am quite easy;`" meaning, I have no doubt, as to her mind.

About ten o`'clock the same night she departed this life in great quietness,
in or near the seventieth year of her age,
and we have to believe is safely landed on that peaceful
shore which no storms of adversity can reach,
and is joined to that multitude which no man can number,
of the righteous of all generations.

I have this testimony to give concerning my dear wife,
that she was a woman of great humility, never aiming at high things,
nor to be thought highly of; her natural understanding exceeded that of many; one,
who from her youth upwards was preserved walking in the fear of the Lord.

Having thus given some account of the illness and close of my valued companion,
I am inclined to add further concerning her,
that there is room to think her pious example, and sweetness of disposition,
had a considerable influence on the minds of divers of her near relations;
which is in some degree confirmed by what her niece`'s husband says to me,
in a letter as follows.

My wife is much affected with the loss of her dear aunt,
a tender and affectionate relation,
to whom she was much attached from a very early period of her life; and from whom,
as she tells me this evening,
she might probably be indebted for the first serious thoughts
she had ever entertained on the subject of religion.

After having thus enlarged my letter, I shall only mention concerning myself,
that my health is favourably continued, so that I can at times visit my friends,
and enjoy their company with pleasure and comfort in my far advanced years.
As the time of my change may not be far distant,
I hope it will be my principal concern to be prepared for it,
by a circumspect walking in the fear of the Lord;
that whenever it pleaseth the great disposer of events
to remove me from this state of trial,
I may submit to his will without complaining or discontent.

In much affection, and with true regard, I remain your sincere friend,

J+++.+++ K.

Colchester, 19th 6 Mo. 1806.

Dear Nephew,

The love and regard expressed in thy letter is acceptable to me;
though we are deprived of the opportunity of a frequent personal intercourse,
the friendship formed between us, I trust,
is on Such a bottom as not to be lost by an outward separation:
as we are preserved in the Truth, and walk in obedience to its dictates,
we shall always love and respect one another.

Our neighbour S. C. remains in a weak state, confined to his house by a paralytic stroke,
his faculties much impaired:
several of my old acquaintance are deceased since thou was in Colchester,
and there is room to expect further changes in this way before the year expires;
however it is a comfort to consider our lives are in the hands of a kind Providence,
who orders all for our good, as we live in his fear: when troubles come,
we have to look to him, who is our Saviour, for help;
and when our state is more prosperous, we still have occasion to ask for his assistance,
lest we should forget the danger we are in of trusting to our own strength.
We are shewn there is no safety, but in a humble, watchful state, out of all security,
or self-dependence; and this we have occasion to think of,
that our having been preserved in a good degree of safety,
in the midst of trials which have been permitted to attend,
will not secure us from harms in the future part of our lives.
We want fresh supplies of Divine aid to help in fresh trials.

I am pleased to find that what our friends have done in America,
towards civilizing the native Indians, meets with thy approbation;
friends in England are about to raise a sum of money to assist in this undertaking.

I remain thy affectionate uncle,

J+++.+++ K.

Colchester, 3rd 10 Mo. 1806

Dear Cousin,

Several circumstances have occurred,--among them is the decease of my brother William,
after an illness of about one month, occasioned by a fall met with in his garden,
whilst gathering some fruit.
Both his sons were with him, and showed much kindness to him,
in endeavouring to alleviate his affliction;
which was pleasant to observer at different times when I visited him;
it was also pleasant to me to perceive an increase
of love and good-will towards his friends;
so that I am not without hope this affliction was sanctified to him,
and made a means of preparing him for his great change.
He more than once expressed to me his desire that I would pray for him, saying,
"`Dear brother, pray for me.`"

J+++.+++ K.

Colchester, 27th 11 Mo. 1806.

Dear Nephew,

I have now before me thy kind letter of 4th 8 mo.
last, which hath been read more than once, with pleasure and satisfaction:
the increase of thy family will occasion renewed desires that thou mayst be enabled
(with thy dear wife) to conduct yourselves so as to promote the welfare of your children,
both as to their bodies and minds.
I am of those who think there is much depending on the education of children;
though it is not in the power of parents to give them a religious disposition,
such impressions may be made on their tender minds, through the Divine blessing,
and such habits introduced, as may not easily be erased,
by all the trials which they may be exposed to in the future part of their lives;
the maxim of Solomon is not to be slighted,
because the best endeavours of parents do not always succeed:
no means should be omitted to strengthen their minds
against the allurements of an inconsiderate world.
I have seen such harm come to young people,
from being exposed to the company and conversation of worldly-minded people,
whose principal care is to provide for the body,
and how they may gratify their sensual appetites,
that I am more and more convinced of the necessity of a guarded education:
some who have exposed their children to the company
and conversation of irreligious and wicked servants,
or the rude, uncivilized boys and girls, have had cause to mourn;
when it hath not been in their power to remove the habits and customs they have contracted.

These are thoughts which have occurred to me unexpectedly in writing to my relation,
of whose welfare it always gives me pleasure to hear.
I have no doubt of its being his concern to put in
practice what I have thus spoken in favour of,
with regard to his children;
and that he is joined by her whom he hath made choice of as his companion and help-meet.
My best wishes attend you as relations and friends:
if we should not be favoured to meet again in this transient state,
as we are preserved in the Truth,
there will be the remembrance of each other in the love and friendship
which was produced in times of our first acquaintance.

With tenders of kind love, I remain thy affectionate uncle,

J+++.+++ K.

Colchester, 29th 12 Mo. 1806.

Dear Relation,

I received thy letter,
informing me of thy being returned to the place of thy former residence,
which was pleasing to me:
I hope thou wilt consider it as a privilege to be in such a sober family,
and under the care of such a valuable friend,
whose kindness to thee I consider as a mark of true friendship.
I doubt not he will instruct thee in what may be for thy good,
and in return I hope thou wilt endeavour to serve him faithfully,
and do all in thy power to promote his interest.

When I consider the danger young men, of the present time, are exposed to,
I cannot well forbear to advise thee to be very cautious, as to thy acquaintance:
be contented with thy master`'s house, whenever business does not require thy absence.

As to associating with the farmers at inns on the market days, or at any other time,
I desire thee to avoid it, as thou regards thy own welfare;
much hurt hath come to some young men from this practice:
if thou hast business to transact in the market,
let it be done with as much expedition as can well be,
without the custom of drinking unnecessarily.

If these cautions should not be wanting in the present time,
they may be useful in some future time, and I would not have thee forget them.
I desire thee to mention my kind love to thy master,
as likewise to my friends J. B. and S. W. with their wives;
they are friends for whom I have a true regard and esteem:
I wish thee to cultivate their acquaintance,
and with other sober reputable friends among whom thou resides.

I am thy affectionate relation,

J+++.+++ K.

Colchester, 22nd 1 Mo. 1807.

Dear Friend,

Thou hast been often in my remembrance since I made thee a visit;
and it will be pleasant to see thee in Colchester, whenever thy health admits of it;
but when we are prevented from doing what we may wish for, in this respect,
and many others, it will be best for us to be contented,
and still put our trust in Him whose dispensations towards
his depending children are all in unerring Wisdom.
He takes notice of our afflictions, and gives relief and comfort when he sees meet;
though it is not in the way and time which may be desirable:
when we consider the blessings and favours received in former times of our lives,
it may help to reconcile to us what we have now to meet with.

It must be allowed thou hast had a large share of trouble,
from the loss of thy dear wife;
also the want of health to conduct thy business in the usual way;
in which I can sympathise with thee, having met with troubles in different ways,
besides the removal by death of many of my dear friends,
with whom I used to advise in times of difficulty,
whose friendship and help was among the principal comforts of my life.
But let us not be discouraged:
amidst all the changes we have to partake of in this transitory life,
there is a friend remaining, who is everlasting and unchangeable,
even our Father in heaven; whose friendship and favour will be increased to us,
when we are deprived of outward comforts, as it becomes our care to keep near to him,
and walk in his fear.
This is the good I am led to desire for us, in the remaining part of our time;
and thus hard things will be made easy, and bitter things sweet,
in submission to the Divine will.

It may be well to remember,
we have never had any promise that the blessings
of Providence to us should be of long continuance;
as to wife and children, or friend, they are to be used as comforts,
which may be taken from us, or we from them;
let us therefore desire we may be helped to say with Job, in our losses, however great,
"`The Lord gave, and the Lord hath taken away, blessed be the name of the Lord.`"

Having said thus much, with a view to help to reconcile to thee what thou hast met with,
I would say a little by way of advice to thee, as to thy bodily health.
I am thinking it will be likely to help thee, if thou was to take some gentle exercise,
in the air, at least once in the day, when the weather admits;
and I would advise thee not to let the expense which it may be attended with prevent.

I am thy affectionate friend,

J+++.+++ K.

Colchester, 10th 4 Mo. 1807.

Dear Nephew,

Though I have thus long deferred to acknowledge the receipt of thy kind letter,
it hath not been laid by unnoticed.
What is said, with regard to the education of thy children, is pleasant,
as it agrees with my sentiments on the subject:
if there should be occasion to place them out for the purpose of education,
as they arrive at a suitable age, it will be safer,
and more likely to promote their best interest,
to make the place of their residence for a time,
in a family where simplicity and plainness in behaviour and apparel, in the fear of God,
is encouraged and promoted; rather than in what is called a genteel school,
where show and fashion is aimed at,
to make children what are called fine gentlemen and ladies.

To have them instructed in what may be useful in some future part of their lives,
I approve of; but to place them in seminaries,
where they will be in danger of receiving hurt as to their morals,
for the sake of making them great scholars, appears to me an unsafe way of proceeding:
what may be gained, as to learning,
will not compensate for the loss sustained from the intercourse
with those who have but a small degree of the fear of God;
whose aim is, principally, to render the children who are under their care,
acceptable and pleasing to worldly-minded persons.

I can speak from experience, of hurt received in my very young time,
from being placed in a school were great liberties were taken;
and had it not been for a religious disposition taking place in my mind,
and the good example and care of a near relation,
there is room to think great harm to me would have ensued.

I remain thy affectionate uncle,

J+++.+++ K.

Colchester, 5th 5 Mo. 1807.

Dear Friend,

I doubt not it will afford thee pleasure to be informed
that my health is continued in a usual degree,
so that I am not without thoughts of being at the yearly meeting,
where I shall be pleased to meet with thee; but this we can only propose,
as what might afford us comfort.
If we should not be favoured to meet there, nor elsewhere,
in the pilgrimage of this life, it may be a comfort to our minds,
that we are not without hope of meeting in those happier regions,
where no earthly concerns will disturb us.
Let us not, therefore, be discouraged by what we meet with in this world of changes.
There is room to think that many of the painful steps we
have to take are leading to a city of rest and peace;
and that there is no better way to it, in the present time, than there was in times past,
which is through much tribulation.

As we know not what is necessary for our refinement, we cannot, with safety,
choose what should be the mixture in the cup we have to drink of.
A larger portion of bitter may be required for some than
is necessary for others (I mean as to their spiritual health);
it is best, therefore, to be contented in all the dispensations of Providence to us.

These are thoughts which occur to me, in writing to a friend whom I much esteem.
In the same love, which hath long subsisted between us, I remain thy affectionate friend,

J+++.+++ K.

Colchester, 5th 6th Mo. 1807.

Dear Friend,

Thou hast had a large share of affliction,
from the loss of thy dear wife and from thy own bodily weakness;
but when it is considered that what we meet with is by permission of our Heavenly Father,
who deals with us in great wisdom,
(and often for our good,) in ways which tend to promote our best interest,
it may help to reconcile our troubles in submission to the Divine will.
There is this good in the afflictions of the Lord`'s people,
that they tend to bring them near to each other, as fellow travellers,
who can speak from experience of the difficulties of the way.
This I desire may be our experience,
and that we may be encouraged to persevere in the path of safety,
into which our feet have been turned,
and happily receive the crown which is prepared for
those who remain stedfast to the end of their race.

I was favoured to bear my late journey to London beyond what could be expected,
considering my age and weakness, and returned in safety;
this may be added to the many blessings received from youth to age.

Though I see great deviations in many of my dear friends,
from the simplicity of manners which distinguished us in the early times of our society,
yet I am comforted in a hope there are many who are concerned to
seek for a better inheritance than this present life affords:
from these (as they are preserved in the Truth) we
have to expect the good testimonies we have to bear,
will be rightly supported.

I am, with tenders of kind love to thee and thy children, thy affectionate friend,

J+++.+++ K.

Colchester, 20th 8 Mo. 1807.

Dear Friend,

Thy letter of the 14th 7 mo.
came to hand, and was very acceptable:
the same comfort which it afforded me on the first perusal,
was repeated upon my reading it again,
so as to leave me less at liberty to defer making some acknowledgment of it,
though I find it more difficult to keep up the correspondence
with my dear friends than in former years.
It is, however,
no small privilege that sight and strength will admit of giving them some token of the
love and regard which (I hope it may be said,) remains undiminished toward them,
in the remembrance of times past, when we were favoured to take sweet counsel together,
and could intermix our joys and sorrows, in beholding each others countenances,
even when no words were made use of to express it.

I find thou art still disposed to promote the best interest of thy friends,
by useful publications.

I see nothing in the small work, entitled "`Early Christian Instruction,
for the Use of Children,`" but what is suitable.
I am for having parents begin early to instruct their children
in the knowledge of what is contained in the scriptures,
that it may be imprinted on their memory.

With tenders of kind love to thee and thy dear wife, I remain thy affectionate friend,

J+++.+++ K.

Colchester, 4th 6 Mo. 1811.

Dear Friend W. S.

Yesterday, upon my return from making a few visits to my friends in the town,
it was matter of concern to find thou had been at my house with
a view of spending a little time with me in thy way from London.
Though I had not the pleasure of seeing thee, I consider it as a mark of thy friendship,
which is very acceptable to me in my weak state.
Among the principal comforts I have to partake of is the kind remembrance of my friends;
especially those of my old acquaintance, to whom I am united in the Truth.
To supply this want of thy company,
I am inclined to acknowledge thy kindness by a few lines,
and at the same time express the true regard and
friendship there is in my mind towards thee,
with thy dear wife and children; who are like a small number remaining,
to support the good testimonies you have to bear in the place of your residence.
It is much to be desired,
that you may be preserved in safety in the midst
of many trials which are permitted to attend;
that you may still be disposed to make choice of that good part,
which no adversities of this life shall be able to deprive you of; that,
through obedience to the dictates of Truth in your minds,
you may experience increase of strength,
so that the ways of religion may become pleasant and easy, which before were difficult,
and not easy to tread in.
Though many years are past,
and almost a new generation hath succeeded that of my dear friends with whom I was acquainted,
I do not forget certain circumstances which attended their situation,
and which may attend those who remain in the present time,
from the want of instrumental help,
and from those who have had long experience in the ways of religion and virtue:
yet this may encourage them to consider, that the Truth, in all the changes of this life,
and in all the failures of help from without, remains the same,
--sufficient to support all those who put their trust in it,
and make it their great concern to obtain a portion in it.

Thus I am led, on occasion of missing thy good company,
(though it might have been but for a little time,)
to express my good wishes for thee and thy family,
with the rest of my friends in Y--, with few of whom I am personally acquainted;
and yet as members of the same religious society,
I consider we are interested in the welfare one of another.

With tenders of true love, I remain thy affectionate friend,

J+++.+++ K.

Colchester, 9th 7 Mo. 1814.

My Dear Friend J. G. B.

In the love and true friendship which took place
in our minds in the early times of our acquaintance,
I am inclined (by means of the help I receive) once more to salute thee,
though in bodily weakness, and without having much to say which is very interesting;
yet I am apt to think it will be pleasant to thee to find,
that I have not wholly forgotten the sincere regard which once subsisted between us,
and that there is hardly a day passes without thy being in my remembrance;
and it rejoices me to hear of thy welfare,
And that thou art still able to visit and converse with thy friends,
and to afford thy assistance at in former times:
I much desire this may be continued to thee, and increased to thy own comfort,
and that of others.
I am still confined very much to my chamber,
yet am able to walk (by being supported,) from one room to another.
It is a great comfort to me that I can do thus much, and bear this change,
for about two hours.
I often hear of the good success of my dear friend in their labours of love,
and have been informed that our late yearly meeting was held to satisfaction,
and that it was well attended;
and though I have not lately been able to give my attendance,
it hath afforded me comfort to believe, that the precious cause is still supported,
and that many are raised up as testimony bearers to it.
Considering thy infirmity,
I do not expect that thou wilt be able to support
the correspondence which hath been between us,
in the usual way; but it will be pleasant to me to receive a few lines,
as a token of thy love to thy old acquaintance and friend,
whose life hath been extended beyond what he had any expectation of,
as a monument of mercy, being now in the 89th year of his life.
If these few lines should come to thy hands, consider them as an effort of true love,
in which I remain thy affectionate friend,

J+++.+++ K.

Stoke Newington, 7th Mo. 11, 1814.

My Dear Friend John Kendall,

Thy letter of 9th is very pleasant to me,
though I apprehend thou hast not been informed of
the rapid declension of my health since yearly meeting.
I was then able to attend most of the sittings, though many of them only in part,
and scarcely ever any of the committees: since that time my disorders,
which appear to be of the asthmatic kind, have came on to a degree that, I think,
hath been the means of enfeebling me more than ever
I was reduced in the course of my life;
and I have often been induced to question,
whether they may not prove the means of removing me from this state of probation.
I feel it a serious thing to remain under this humiliating view,
and do not find that I have anything to trust in but Divine mercy,
the hope of which is an anchor which I am not wholly deprived of,
though I am made renewedly to feel my own unworthiness.
I have generally very broken rest, though in consequence of a better night the last,
and a visit from our dear friend Sarah Grubb, whom I believe thou knowest,
I feel myself somewhat better than common today.
I frequently heard of thee, during the yearly meeting, by one friend or another,
and had a full intention of writing to thee long before this,
in token of my continued love; but I have again found the truth of the proverb, that,
when our friendly purposes are not executed with dispatch, they are apt to languish,
and sometimes not to be executed at all.
I quite approve of thy daily excursions to the dining room, while ability lasts,
believing it to be a pleasant and profitable change of scene.
But I have no doubt that neither change of scene, nor other outward circumstances,
are wanting for thy support.
Thou knowest in whom thou hast believed; and now, green in thy very advanced age,
art witnessing the blessed effects of a long life of faith in the Redeemer of men,
(may I be allowed to name him,) the Lord Jesus Christ.
Farewell, my dear ancient friend; continue to believe me to be,
with all the ability with which my feeble mind is invented, thine affectionately,

J+++.+++ G. Bevan

The End

[.asterism]
'''
