[short="Considerations on the Value of Time"]
== A Friendly Address to My Neighbors of the Town of Colchester, and Others Whom It May Concern. Occasioned by Considerations of the Value of Time, and the Advantage of a Right Improvement of It.

[quote.section-epigraph]
____
For you know perfectly, that the day of the Lord so comes as a theif in the night.
____

[quote.section-epigraph]
____
Therefore let us watch, and be sober.
____

[quote.section-epigraph]
____
Let us who are of the day, be sober, putting on the breast-plate of Faith and Love,
and for a helmet, the Hope of Salvation. --1 Thess. 5.
____

[.offset]
Printed first in the Year 1790.

=== A Friendly Address, etc.

The custom which prevails among my neighbours of meeting at inns and public-houses,
on the First day of the week, called Sunday; to read the newspapers,
and converse upon national affairs, as also about their business,
and other temporal concerns; hath often grieved me to think of:
and having no better way to express my concern,
I take the liberty to address them in these few lines,
from a motive of love and true regard; not from a desire to obtrude my opinion,
or de-deprive any of a liberty which may be useful to them; but that we may be kept,
during the short time of our continuance in this mode of being, from every hurtful way,
and steer our course so as to be admitted into that City
whose inhabitants are employed in the praise of God,
and contemplation of his goodness.

The certainty of our removal from this life,
and the uncertainty of the time and way of it,
often occasions serious considerations in my mind,
which make me wish to spend the few moments allotted me here,
in the fear of Almighty God,
so as I may be in a prepared state whenever the messenger of death is sent to my house;
and this same good I am led to desire for my friends and neighbours,
whose welfare hath no small place in my mind;
without any regard to the difference of our religious profession.
I consider all of every society as objects of the Divine notice;
and that we have One God, the Father of all, and One Lord Jesus Christ,
as the Saviour of all, to redeem and sanctify and finally save us, if ever we are saved;
and that no outward profession of religion will be sufficient for any,
without the living principle of truth and righteousness,
to actuate our minds so as to produce fruits of holiness in us, to the praise of God.
Why should we therefore think slightly of each other,
on account of some variety in sentiment which yet remains among us, concerning Religion?
If we are united in the one great concern, which is to love and fear God,
and are seeking His favour, by obedience to His law in our minds,
we shall be accepted of Him:
and those of every society and of all nations will be finally
joined together to constitute the body of Christ,
and make one Church, of which He is head; agreeable to the testimony of the apostle,
that in every nation, such who fear God and work righteousness are accepted of Him.

Shall we not desire to be of this happy number?
That when we leave the fading inheritances of this life,
we may be admitted into the company of the righteous of all generations;
and have to join with these, and the angels in heaven,
to celebrate the praises of Him who hath redeemed us, and made us acceptable to Him,
through his beloved Son!
But when I speak of this good, I would have us remember, we must be made meet for it;
by a change in our disposition, and by good qualities being produced in us:
for if we are estranged from God, by means of wrong conduct whilst here,
how can we expect to be admitted into His presence in a future state,
or to have any pleasure in the company of the blessed spirits?
As sin makes a separation between us and the Almighty here,
so if we live and die in our sins, it will be a cause of separation from Him hereafter;
which must be unhappiness to the soul.

I would fain have my neighbours and friends excited to prize
the opportunity of improvement which is given them;
and the same I wish for myself,
that we may spend the few remaining moments in "`the fear of God,`" which
is said to be "`wisdom,`" and to "`depart from evil a good understanding.`"

And as I express my disapprobation of the custom of attending clubs or meetings,
for the purposes before mentioned, on the First-day of the week,
I would propose the introducing a custom more christian-like,
and consistent with the real interest of families; which is,
to have some parts of the Holy Scripture read in the family; and also other books,
which recommend the practice of Religion.
This may help to strengthen the right determinations of our minds,
and store our memories with the sayings, and experiences of excellent persons;
which may be a comfort to us in times of adversity, when outward help shall fail,
and we are separated from the company of those we used to converse with,
by bodily indisposition.

It will be a relief to my mind,
to add further my sentiments concerning a custom that prevails in many places,
and also in the place of my residence, from which great inconvenience hath arisen;
I mean that of entertainments at inns and public houses,
on account of new magistrates being chosen, or the election of members of parliament,
especially if there is a contest on the occasion:
the great intemperance which is seen at these times,
especially among the lower ranks of people, partly at their own expense,
and partly at the expense of the candidates, is affecting to serious persons,
who consider that the choice of rulers and governors, in the land,
is a business of importance, and ought to be conducted with great moderation,
and in the fear of God; instead of proceeding to an improper indulgence of appetite,
in eating or drinking;
by which means they are disqualified from judging of the
fitness of those who are proposed for their choice;
and take the way to displease that good Providence which
is essentially wanted to direct us on these occasions.

I wish, therefore, that such who are principally concerned in these elections,
might be disposed to set a good example to those who are in lower stations,
by their temperance and sobriety;
and also endeavour to prevent disorderly conduct in persons of all ranks,
during the time of their continuance,
and at the close of them.--The blessings of heaven will be upon such endeavour,
and upon the places in which such rules are observed;
and many crimes prevented which tend to bring ruin upon persons and families,
societies and nations.

In writing this short exhortation, I am inclined to mention,
it hath often been a cause of grief to me,
to see so much excessive drinking in houses of public entertainment,
where I have had occasion to be,
either in travelling or otherwise:-- As the taking immoderate
quantities of liquor which hath the quality to intoxicate,
is hurtful to the constitution,
as well as highly offensive to the Giver of the outward comforts we partake of,
I would advise all into whose hands this may come,
as they value their health and comfort in this life,
as also the happiness of their souls in a future state,
to be much upon their guard against this evil: Custom may insensibly lead into it,
and the practice of those with whom we converse;
but no practice or custom of others should lead us into
ways that are inconsistent with our duty and true interest;
to please others at the expense of our own health and peace, is going too far;
and such with whom we join in this intemperance can
never make us amends for the loss we sustain.

Though I am thus particular in my caution against this part of intemperance,
which is so hurtful to the morals and health of people,
I am sensible there are other practices no less offensive to the Almighty,
which bring trouble and disgrace on such who indulge themselves in them.

Let us therefore endeavour after a regularity of conduct, in all respects;
that whilst we refrain from some things, which other people are in the practice of,
to their hurt, we may not interrupt the harmony of our minds,
by any conduct either private or public,
which is contrary to the dictates of truth or justice: but that,
through a blessing from above on our endeavours, we may refrain from all manner of evil.

And thus, as the Apostle advises,
having our thoughts employed on whatsoever things are true, honest, just, pure, lovely,
and of good report, and striving to put them in practice,
we shall become ornaments of society, a blessing to our families;
and leave to posterity an example of piety and virtue,
fit for them who succeed us to imitate.

I conclude with the words of the apostle, "`As He who hath called you is holy,
so be ye holy in all manner of conversation,--and if ye call on the father,
(who without respect of persons judgeth according to every
man`'s work) pass the time of your sojourning here in fear.`"

In that love which hath been my inducement to writing this,
for the notice of my neighbours, and such whom it may concern,
I subscribe myself a well-wisher to all men, and their affectionate friend,

[.signed-section-signature]
J+++.+++ K.
