== Memoirs of My Life.

I was born in Colchester, in the year 1726, of parents religiously disposed.
My father`'s business being such as to occasion his frequent absence from home,
the principal care, as to the education of their children,
necessarily devolved on my mother, who was a pious woman,
and much concerned to check a disposition to hurtful practices,
which she perceived apt to prevail;
and though her endeavours had not the wished for success in all of them,
there was this consolation, that she had not failed to show them,
by her example and precept, the safe path for them to walk in.

About the twenty-first year of my age,
I was first concerned to express a few words by way
of testimony in a public meeting for worship;
and, in the year 1750, I accompanied my friend, Daniel Stanton,
in a religious visit to Friends in swine of the northern parts of England and Scotland.
We went by way of Norwich, Lynn, Gedney, Boston, Winteringham,
and across the Trent to Rawcliffe in Yorkshire; from there to York,
and so proceeded to Darlington, Durham, Newcastle, taking meetings in our way,
till we arrived at Edinburgh.
After spending about two weeks in Scotland, and being at the meetings there,
as far as Old Meldrum, we returned into England, by way of Aberdeen, Glasgow,
and Stirling; from there proceeded to Carlisle, through a very mountainous country,
to Kendal; from there to Monyash in Derbyshire, where I left my companion,
and in a few days reached home.

I experienced some difficulty in this journey, being young,
and not so able to bear the fatigue of travelling, as those of a strong constitution,
who had been inured to hardships.
There was this however to comfort me, that it was from a sense of duty,
and with the approbation of my friends, that I joined my friend in this service.
We travelled together in much harmony;
as fellow-labourers in the gospel of our Lord and Saviour Jesus Christ;
and there is room to think our service was acceptable to those we visited.
We found the meetings of Friends, in many parts, small as to number,
and in a low state as to the life of religion,
and concern for promoting the cause of truth.
Our predecessors left us the form of religion, which they found profitable,
and we have adopted it;
but it cannot give us that which brought them into the society in the early times;
which was the love of God,
and a concern to renew their acquaintance with him by humble walking in his fear.

After my return from this journey, I had to pass through many exercises,
both inward and outward.
In the early part of the 7th mo.
1752, I joined my friends William Brown and Samuel Neal, in a journey into Holland,
and some part of Germany;
with a view of visiting the few who remain of our society in that country.
We took ship at Yarmouth, and had a favourable passage to Rotterdam.
Here we made a short stay;
and after some discourse with persons who showed a friendly disposition towards us,
though not members of our society, we proceeded to Amsterdam,
where a few Friends resided.
We attended their public meetings, and visited them in their families,
which was in a good degree to satisfaction; we were also at Twisk in North Holland,
a village about thirty miles from Amsterdam, where a meeting is held.
Upon our return to Amsterdam,
being informed of a religious people at Osnabrug and some parts adjacent, in Germany,
who were convinced of our principles, we found it our concern to make them a visit.
In this journey we travelled part of the way by sea, and part by land,
in the whole about two hundred miles.
We were received with much affection, especially by a merchant at Osnabrug,
who expressed his satisfaction with our visit,
and we had much religious conversation with him, by means of an interpreter.
After spending about five days here, and visiting a serious people in the country,
we left them, and proceeded by way of Benthem, Deventer, and Naarden,
on our return to Amsterdam; where we arrived on the 31st of 7th month.
We now inclined to turn our faces homeward, and passing through Haarlem and Rotterdam,
(at which places we had meetings,) came to Helvoetsluys On the 22nd of 8th month.
Here, after waiting a few days,
(the wind not being favourable for sailing,) we took our
passage on board the packet which sailed for England,
and in about thirty-two hours arrived at Harwich; from there I proceeded to Colchester,
with the Friends, my companions.
There is room to be thankful for preservation from harms,
to which we were exposed in this journey, both by sea and land.
It may encourage us to enter into the Lord`'s service,
and put our trust in him for protection, when we venture at his call.

I had not been long returned home, when it pleased the Lord to remove my father by death,^
footnote:[From whom, when on the journey which has been last related,
the author received the following letter.
{footnote-paragraph-split}
Colchester, 18th 7 Mo. 1752.
{footnote-paragraph-split}
Dear Son,
{footnote-paragraph-split}
Yours of the 9th inst.
came duly to hand.
The preserving hand of Providence over you hitherto,
is cause of great bowedness in our minds upon your account;
with earnest desires for the continuance of its holy protection;
and that you may never swerve from its heavenly guidance, which, if closely adhered to,
you need not fear a return of peace and joy into your bosom.
{footnote-paragraph-split}
As to us, your parents,
our care on yours and other accounts is great; yet we can say at times,
our God (the inflowing of whose Divine presence is of greater value
than the whole world,) is not wholly departed from us,
blessed be his name therefore!
{footnote-paragraph-split}
Your uncle, Thomas Kendall,
to all appearance is not likely to remain in this life many days.
We shall, by soonest, expect advice from you which way you are going,
and when we may expect your return.
That your undertakings may be under the direction of the Lord,
who alone can make them prosperous, is the hearty prayer of your affectionate father,
{footnote-paragraph-split}
John Kendall
{footnote-paragraph-split}
To John Vanderwerf, Amsterdam. For J. K.]
which change in our family greatly affected my mother,
who was likely to feel a deep loss, as to her outward concerns, and otherwise:
my brothers being young, and not able to conduct the business,
it seemed to be my place to assist, and be helpful to her, as far as I was capable;
and a large share of encumbrance came necessarily upon me,
which continued for some years;
so that the weight of it was almost too much for me to bear.
But the Lord was pleased to make way for us; and only to his goodness,
and providential care, we owe our support, every way.
He is the helper of the widow and fatherless: well would it be for all,
if they regarded him, and placed their trust in his Providence:
for unless a blessing from him attends, the utmost of our endeavours,
and all the help we may receive from man,
will avail but little towards procuring the comfort and happiness we desire.

During the time of my attendance so closely to outward business,
I found my mind often deeply baptized, and in great affliction,
through lack of access to that spring of good, which affords Divine consolation.
My concern was, lest I should he obstructed in the work of my great Lord and Master,
and become as a vessel marred in the hand of the potter.
The advice of the apostle was often brought to my remembrance,
when he charges Archippus "`to take heed to the ministry
which he had received in the Lord.`"
And his exhortation to Timothy, "`to watch in all things, endure afflictions,
do the work of an evangelist, and make full proof of his ministry.`"
These considerations tended to stir me up to diligence; seeing, said I,
I am engaged in a warfare, if I would please him who has chosen me to be a soldier,
I must not entangle myself with the affairs of this life.
Great encumbrances of outward affairs,
appeared to me unsuitable for the exercise of a Christian life;
and in a particular manner,
I thought it unfit for the ministers of Christ to be loaded
with the cares which proceed from extensive trades,
and merchandize.
They have need to be disengaged from the world,
and rather aim at an increase of heavenly riches,
which will render acceptable in the sight of God,
and be available when outward comforts come to an end.
Many are obstructed in their religious progress,
by the increasing cares of this transitory life;
the faculties of the soul being impaired by a continual
pressure from that which is not its proper employ:
so that instead of rising from one degree of strength to another in Divine life,
there is a languidness, and inactivity.
We become more and more unfit for the business to which we are called,
and make not suitable improvement of our talents, because they remain unoccupied,
through the prevalence of worldly cares.
A constant watchfulness, and great self-denial,
are required in order to retain a proper liberty for the Lord`'s service.
I have seen, through Divine favour, the dangers to which I am exposed,
with the rest of my brethren, from the spirit of the world, which lies near to us,
and is not to be avoided but by a sincere application to the giver of heavenly wisdom.

During the many proving dispensations,
which it has pleased Providence I should pass through,
as I kept my eye single to the discharge of my duty, and abode under the cross,
I always found safety.
Popularity I have not aimed at; but, as far as was consistent with my peace,
preferred a life of retirement.
I could find no room for an intimate acquaintance with such whom the outward
concerns of this life made it necessary to converse with;
so that I have not sought their company with desire to propagate a friendship,
except it was from a desire to be helpful to them,
but have endeavoured to withdraw myself,
when nothing further detained me than the indifferent matters which made up the conversation.
There is an innocent cheerfulness, in the freedom which truth gives,
that I do not disapprove, but we must take care not to squander away the time,
which is so precious, but be still concerned to make the best use of it,
by a circumspect walking.

We are assured, from the testimony of Holy Scripture,
as well as from a certain evidence in our minds,
that there is a Providence in every event of our lives,
and an all-seeing eye which marks our ways, though in a manner we cannot comprehend.
At the same time we are not constrained to join with what is likely to be hurtful to us,
nor to accept of what is proposed for our good,
but have a certain degree of freedom in our minds to choose,
or refuse both the good and the evil,
(which constitutes our state in this life) as rational beings,
who are accountable to the great Author of our existence,
for the gifts he has bestowed upon us;
and He will reward each one according to his deeds.

If I have not pleased some,
by my declining to enter into a strict acquaintance and fellowship,
where it has seemed to be sought; yet, I trust,
my own peace and welfare have been promoted thereby.
Universal love, and benevolence, I hope will always so prevail in my mind,
as to beget a readiness to do whatever may appear to be my duty
towards promoting the happiness of my fellow creatures.
But alliances from bare views of interest, or personal respect,
have not been what I aimed at.
I have been rather seeking to feel that unity which
subsists between the children of a heavenly birth;
who are partakers of a lively hope of becoming heirs of a kingdom that is everlasting!
I consider no friendship to be permanent like that
which has its rise in the Divine power;
the power which operates to the cleansing from all impurity of flesh or spirit,
and brings into the liberty of God`'s people.
How little room this has to work, and produce its blessed effects in men`'s hearts,
appears by the general opposition it meets with.
Many of the professors of Christianity content themselves
with a bare literal knowledge of the truths of religion;
whereas the heart must be reached to, and affected, in order to make right improvement;
our knowledge of God can be no otherwise certain than by
an adherence to that inward instructor and teacher,
which is given as the promised blessing, Jesus Christ, the hope of glory!
I find as much occasion as ever to wait for this help;
my own incapacity being more and more evident, as I come to know myself!
The desire and love of earthly things is abated, and I wish to have it more abated,
that my affections may come to be placed on things above, that is, in heaven,
where are treasures which last always.

Thus I close these remarks,
and proceed to give some account of my second journey into Holland,
in the company of two Friends, whom I was willing to assist in their religious concern,
having some knowledge of the Dutch language.
On the 17th of 7th mo.
1757, I left home, and on the 21st took ship at Harwich with the said Friends,
in the packet for Holland, and after an agreeable passage arrived at Helvoetsluys;
from there we proceeded, as usual, to the Briel, Rotterdam, and Amsterdam.
On the 24th, being the first day of the week, we were at the meetings there,
which were pretty large, consisting of Friends, and persons not of our society.
After staying about a week in the city, we went to Twisk, and were at their meeting,
to which came some of the Baptists, with one of their preachers.
They appeared to be a sober, religious people.
After spending some time among Friends,
and having communicated such advice as we thought suitable to their state,
we committed them to the Divine protection, and returned, by way of Horn and Purmerent,
to Amsterdam.
Here we stayed a few days longer, and were at several of their meetings,
besides visiting them in their families, and then proceeded to Haarlem,
and had a meeting with some religious persons in that city.
The next day, being 22nd of 8th mo.
we went to Rotterdam, and attended a meeting there, to which many English people came,
(as there are many residing in this place,) as likewise Hollanders:
we took up our lodging at an inn, there being none of our society.
After visiting some families, we left Rotterdam,
and came by way of the Briel to Helvoetsluys, where we were detained about a week,
by contrary winds.
Being thus at a distance from our friends, and in a foreign country,
the time was tedious to us:
yet considering the occasion of our visit to this land--that it was from religious motives,
with a view to promote the best interests of our friends,
and those among whom our lot might be cast,
we were not easy without proposing to have a meeting with
such of the inhabitants as might incline to attend;
and notice being given of our intention, a considerable number came,
who understood English, especially of those who belonged to the ships;
and they were spoken to in the love of the gospel,
on subjects relating to their everlasting welfare: which appeared to be well received.
A few days after the ship sailed,
and we had an agreeable passage to Harwich of about twenty-four hours.
Next day we reached Colchester in good health.

Thus, through the goodness of the Lord, our journey was made prosperous,
his preservation being experienced in our going out and returning,
for which there is renewed cause of thankfulness.
May I always bear in mind the favours received, and be concerned to walk humbly,
as in the presence, and under the notice of my great Lord and Master Jesus Christ,
lest by any means I should miss of his favour.

About this time our family sustained a great loss, in the death of my mother`'s sister,
Ann Garritt, aged 47 years;
who departed this life in great peace and quietness on the 27th 3rd mo. 1757.
It may be said of her, that she was a religious, virtuous woman;
one that adorned the profession she made, by an unblameable life and conduct.
She chose a life of retirement;
her concern was to be acquainted with the substantial part of religion,
as appeared by the quiet frame of mind, and resignedness,
in which she was supported during the severe affliction which attended her.
There is no room to doubt but that her removal is from the troubles of this present life,
into everlasting peace and rest.

I spent my time after this mostly at home,
being engaged in some necessary concerns relating to our family, till the 4th mo.
1760; when finding an inclination to visit friends in some parts of Suffolk and Norfolk,
I took my journey by way of Ipswich, Woodbridge, Beccles, and various other places,
till I came to Norwich, where I stayed about ten days,
and was at several of their meetings, in some degree to my comfort and satisfaction.
I went from hence to Holt, Walsingham, Wells, Lynn, and Swafham.
Most of the meetings in these places were small.
From Swafham I went to Bury, and from there returned home, through mercy,
in bodily health, and favoured with peace of mind,
which is the reward I seek in my labour of love, among my brethren.

In the year 1763, having a view of changing my condition by marriage,
the following serious reflections attended my mind on the occasion.
Marriage is honourable, and in the frequent baptisms which I have had to experience,
a secret hope has remained, that the Lord`'s goodness would be still extended towards me,
as I kept near to him, by obedience and faithfulness to his requirings:
what I now meet with may be permitted,
in order to prepare for such trials as the alteration
in my outward condition may subject me to.
If affliction and suffering attend us,
it is no more than was the experience of the Captain of our salvation;
and has been the lot of the righteous in every age.
The apostle says,
"`All that will live godly in Christ Jesus shall suffer persecution:`"
which may relate to suffering inwardly from the powers of darkness,
as well as from enemies without: in both the exercise of patience is required,
and resignation to what is permitted to come upon us.
Though deliverance is not soon experienced,
we may depend upon the goodness of the Lord our God,
whose arm is not shortened that it cannot save, nor his ear heavy that it cannot hear.
His name is a strong tower, into which the righteous flee and are safe!

Having waited upon my dear friend some time, whom I intended to make my wife,
and gained her consent, our friends and relations also approving it,
on the 17th of 7th mo.
1764, we took each other marriage,
in a public meeting appointed for that purpose in Colchester,
at which a pretty many of our friends and neighbours were present.

Two years after I was concerned to visit friends in the counties of Kent, Sussex,
and Surry, in the company of my friend Edmund Gurney;
this was performed in a good degree to our comfort and satisfaction.

On the 10th of 7th mo.
1770, I left home in the company of my dear friends, Isaac Sharpies, William Fry,
John Eliot, and James Backhouse, with intention of visiting friends in Holland,
to which service we were appointed by the Yearly Meeting in London.
Next day we took ship at Harwich, in the packet,
and after a favourable passage of about twenty-four hours, arrived at Helvoetsluys.
From hence we proceeded to Rotterdam, Delft, Leyden, and Haarlem.
Not finding it necessary to make much stay in these places, we soon reached Amsterdam,
where we stayed some days, and were at their meetings for worship;
in speaking to the people it was found necessary to make use of an interpreter,
which is no small disadvantage both to speaker and hearers:
yet we have room to believe our visit to them was acceptable.
On the 17th, we went by way of Horn, to Twisk,
where a small number reside who bear the name of Quakers.
After having a meeting with them in an apartment hired for that purpose,
and conversing with them on their low state, we returned to Amsterdam,
and were at the public meetings on the First day.
Here it is usual for many people of other societies to attend Friends`' meeting,
especially when they hear of any of our ministers being likely to be present.
They were spoken to by means of an interpreter as usual,
and appeared willing to hear our testimony,
but not satisfied with our way of sitting in silence.

The friends in this city consist of about nine families, and sixteen persons.
We assisted them in looking into their church affairs.

On the 26th, we went to Haarlem, and held a meeting at the house of Pieter Leendaars,
a friend far advanced in years,
to which a pretty many of the inhabitants of the town came,
and behaved with great sobriety; so that the meeting was to our satisfaction and comfort:
at the close of it we presented some books to the people, on religious subjects.
A person with whom we had some conversation after the meeting,
mentioned the following remarkable circumstance which
lately occurred at the house of one of his acquaintance,
where he was at dinner.
While they were sitting at the table, a woman of the company was suddenly taken ill,
and without saying much, soon departed this life.
She had mentioned to him a dream which she had a few weeks before,
in which it was said to her, '`Prepare yourself for death,
for your time here is but short.`' I take notice of this, to show,
that we are not without secret intimations of what may befal us,
and that it is rot safe always to reject them, as things not deserving our notice.

On the 27th, we went to Leyden, and the Hague; and the next day to Rotterdam.
Here we attended the meeting, being the first-day of the week, to which many people came,
both Dutch and English, and the Truth was declared to them with much openness.
From Rotterdam we went by way of the Briel to Helvoetsluys,
where we took ship for England, and after a passage of about forty-four hours,
arrived at Harwich, from which place I proceeded with the Friends my companions,
to Colchester.
Being preserved in our journey, through the favour of the Almighty, in good health,
and with peace in our minds, as the reward of our labour of love,
in the gospel of our Lord and Saviour Jesus Christ.
This is more to us than the addition of earthly treasure,
or any advantages which we might receive from men.

On the 1st of Seventh month, 1771,
I left home with intention of visiting the meetings of Friends in Northamptonshire,
and Oxfordshire, in the company of my esteemed friend John Eliot.
We proceeded in our journey for the said counties, by the way of Hertford and Hitchin,
and after being at most, if not all the meetings, returned to London; and on the 31st,
I got home through mercy, in good health, and found my wife and relations well;
for which favour I desire to be thankful to the Author of all good,
having also witnessed a degree of inward help and strength, to discharge myself,
in what seemed to be required of me, to the peace of my mind.
The effect of these labours we desire to leave to him who
can give a blessing on the endeavours of his people;
putting up our requests in the name of our Lord Jesus Christ,
for help in all the concerns which may succeed in the future part of life.

We observed in various places a declension of the Society as to numbers,
and a decay of strength, for lack of adherence to the principle of Truth.
Hurt has likewise been sustained through the breach of that harmony,
which ought to subsist among brethren.
In some, I fear, there has been too great forwardness and activity in religious concerns,
their zeal not being accompanied with knowledge.
These, seeing an inconsistency of conduct In some of their friends,
have been disturbed at it, and shown their dissatisfaction in an improper manner;
by which means no help has been afforded to such as are out of the way,
but offence taken; and thus the enemy finds room to sow his evil seed,
to the hurt of individuals and disturbance of the church.
Such as have the affairs of the Society upon them
had need be clothed with heavenly wisdom,
and meekness; in which alone their endeavours to regulate disorders can prove successful.

I find it noted in my diary, about this time,
that in a certain opportunity I witnessed such enlargement
in prayer to the Almighty as afforded relief to my mind;
though through fear of enlarging beyond proper bounds,
was apprehensive I had obstructed the further openings of Divine love,
to intercede for my dear relations and friends,
who were brought to my remembrance in a manner I had but seldom experienced.

In the year 1773, I met with a great loss by the decease of my honoured mother,
Elizabeth Kendall, who departed this life on the 11th of 12th mo.
in the sixty-ninth year of her age,
and her remains were interred in Friends`' burial ground in Colchester on the 19th;
concerning whom I have these further remarks to make.
After a life of much exercise, and religious concern on account of her children,
and family; she rests from her labours, and is safely landed on that peaceful shore,
which is beyond the reach of troubles, such as are permitted to attend us here.
She has not lost the light, but is in the more secure enjoyment of it.
She is gone before to those peaceful mansions,
which our dear Lord and Saviour declared to his disciples
he was going to prepare for them,
and no doubt for all his faithful people in succeeding times.

Thus it pleased the supreme disposer of events.
Shall we not say, all his dispensations are in unsearchable wisdom and goodness?
Blessed be the name of the Lord!

In the three concluding months of the year 1774, I was engaged, with several friends,
in visiting the families of Friends in the town and country,
belonging to Colchester monthly meeting.
In these visits we had opportunity of communicating such advice and caution,
with regard to their religious conduct, as appeared suitable; and it may be said,
there is cause to be thankful,
in that the same favour which attended in the beginning of this concern,
was mercifully continued to the conclusion.
As we are concerned to wait for the opening of the Divine hand,
and are faithful to our great Master, in what he requires,
we need not fear but that he will support us in the work which he may call to.

Shortly after this, I went into Kent, in the company of my friend Joseph Ransome,
upon a religious visit to Friends of that county, and we were at most, if not all,
their meetings: we returned to Colchester in the First month, 1775.

On the 30th of 3rd mo.
1777, I left home,
with a view of joining some Friends in a visit to several of the midland counties:
Buckinghamshire, Oxfordshire, Bedfordshire and Hertfordshire;
being appointed to this service by the yearly meeting in London.
After attending the several monthly and quarterly meetings, in those counties,
I returned home in peace,
having renewed cause of thankfulness for preservation witnessed,
both as to body and mind.
It may be said we met with a kind reception in all the places where we came;
many of the meetings were large: and in the strength of love,
which we felt at times to clothe our minds, we had to labour both in word and doctrine,
for the help of our brethren.
And though the state of the society is such as calls for mourning,
through the prevalence of wrong things, and lack of concern in many, whose abilities,
if rightly improved, would make them useful members; yet we found a remnant,
with whom our spirits were united.
We desire that the work of reformation,
which through the Lord`'s goodness is begun in the hearts of some, may be carried on,
to his praise.
As to us, who were concerned in this visit, it has been no small comfort to us,
to feel our hearts united in the labour and fellowship of the gospel.
As we began, so we ended the service, to our mutual satisfaction.
For which, with the manifold favours received from the Lord`'s hand,
we have cause to be thankful;
and may be encouraged to continue our endeavours to promote the welfare of our friends,
and the society; hoping for a good conclusion, in the Lord`'s time.
We must expect to meet with difficulties,
and discouragements from the assaults of the enemy of all good,
as also from our natural weakness, and infirmity: but let us believe,
that all will work together for good to them that love and fear God.

After being at our quarterly meeting in the Third month, 1778,
I went in the company of Joseph Ransome to London,
having it in our minds to visit the meetings there, and in the parts adjacent.
Through Divine favour,
we were helped to perform this service so as to witness peace of mind;
the Lord`'s good presence was with us, to comfort and support,
in which we experienced a harmony of spirit,
and were made fellow-labourers in the gospel of our Lord Jesus Christ.
In the twelfth month of this year, I was engaged, with several Friends,
in visiting families in the compass of Coggeshall, and Colchester monthly meetings,
and it proved, in a good degree, to the peace and comfort of our minds;
though it was an occasion of grief to perceive the loss sustained by many,
through an indulgence of their fleshly appetites.
Our society will no longer remain in a safe state,
than while the members are concerned to adhere to the principle of Divine Grace,
which is manifest for our instruction and support.
If we go from this, we shall be in danger of falling into wrong practices;
and thus the bond of the society being lost, a declension will follow,
even as to numbers; and coldness and slackness in our religious duties:
as we became a society on a religious foundation, which is the love and fear of God,
how can we be supported any other way?
or how can it be otherwise than that the society must decline
if it goes from that from which it took its rise?

In the sixth month, 1780, with the concurrence of my friends,
(which always appears to me necessary in such a concern) I again joined
my friend Joseph Ransome in a visit to Friends in the west of England;
we went by way of London into Wiltshire,
taking the meetings pretty generally till we came to Bath and Bristol.
The number of Friends in some places is small;
yet it was a comfort to us to hear of the convincement of several,
who are likely to be useful members.
In one of the meetings which we attended, some trouble arose,
by means of a disagreement in sentiment (among the members),
and not enough bearing one with another:
we did not think it incumbent on us to enquire particularly into the cause of it;
but recommended an abiding in that love which bears all things,
and is the best remedy against the contradictions and oppositions of our Friends,
in matters not essential to our happiness hereafter: especially those relating to form?
of church government, which may vary, without any hurt to the whole.

From Bristol we took our journey into Worcestershire, Warwickshire, Northamptonshire,
and Bedfordshire, till we came to Walden in Essex, being the 27th of 7th month;
and the next day I reached home, through mercy, in good health,
and in the enjoyment of peace;
which is an abundant reward for the small pains I
may take in the service of my great Master.

In the year 1784, I accompanied my friend Samuel Spavold,
in visiting the families of Friends in most part of Essex;
we were much united in the service, our hearts being enlarged in love to our brethren,
though not without a sense of the absence of that enlivening
virtue which comes from Christ the head of the Church,
to them that are his true subjects, and wait upon him for direction.

About one month after this,
I joined several Friends in a visit to the few remaining of our society in Holland.
We passed the sea in about thirteen hours, from Harwich to Helvoetsluys;
and after being at several places in this country, as Rotterdam, Amsterdam,
etc. and having meetings among the people, we took ship for England,
and arrived in a few days at Colchester, in good health, and with peaceful minds;
for which there is cause of thankfulness to our Lord and Saviour,
who has done much for us, even beyond what we could ask, or think.
I have not much to remark concerning this journey, except that it was cause of sorrow,
as it has been in former times, to observe the declining state of things among them,
(whom we visited) and how few are left to support the good
testimonies we were called to publish in early times.
Yet I am ready to conclude,
from what I have seen at the different times of my being in Holland,
that there are many religious valuable persons in these countries,
whose minds are convinced of the truth, as it is in Jesus,
who being no longer contented with the forms, and ceremonies of religion,
are seeking after the substantial part of it.
We were desirous of visiting them,
but the interaction between us has been much obstructed,
through ignorance of their language.
The only means of communicating our thoughts has been by an interpreter,
which it has not been easy to procure to our comfort and satisfaction.

In the year 1791, I felt an inclination to go once more into Holland,
on a religious visit to Friends, being the fifth time of my being in that country;
and I was joined in this concern by my friend John Abbott.
We took ship on the 29th of 6th mo.
at Harwich, and after a favourable passage,
arrived at Helvoetsluys in the evening of next day; from hence we went to Amsterdam,
about forty miles, passing through Rotterdam, Delft, etc. as usual.
On the 3rd of 7th month, being First-day of the week,
we were at the meetings in Amsterdam, which were but small, as to the number of Friends;
but in the afternoon of the day, many of the inhabitants of the city came,
and behaved orderly, except the custom they have of going out,
and coming into the meeting, from time to time, during the continuance of it.
The occasion of this, we conclude, is, from our meeting being held,
at least some part of it, without any outward ministry:
which does not meet with the concurrence of those who are
not acquainted with the nature and benefit of silence.

Having now some more knowledge of the Dutch,
I endeavoured to speak to the people in their own language,
but my companion found greater occasion to be assisted by an interpreter.
We visited the Friends in their families, to some satisfaction;
though sensible of a lack of religious concern,
such as is necessary for the support of the testimonies we have to bear.
It must be allowed they are under great disadvantages, from their lonely situation,
as to help they might receive from the company of Friends from England;
by whom they are not often visited.

On the 9th we went into the country about twelve miles to a family,
consisting of a friendly man, and his two sisters, who received us with much kindness.
After staying a few days longer at Amsterdam, we left that city,
on our return to England, passing through Haarlem, Leyden, etc. to Rotterdam;
where we had a meeting, with some sober people of the city,
in the meetinghouse belonging to Friends.
We then pursued our journey to Helvoetsluys, where we took the pacquet,
and arrived at Harwich on the 17th, and the next day reached Colchester.

Being thus favoured through the Lord`'s goodness to return to my habitation in peace,
though attended with bodily weakness,
(and soon after my illness increased to a great degree,
and continued for some time,) yet in all I have renewed
cause to be thankful to the Author of all good,
and, in the enjoyment of many blessings, to say,
"`What shall I render to the Lord for all his benefits?`"

Since this journey my engagements have been chiefly
in the compass of the meeting to which I belong,
except attending the quarterly meetings of our county and the yearly meetings in London;
from which I have been seldom absent for fifty-five years;
and in that time I have seen great changes by the removal by death of many Friends,
with whom I was acquainted in the early part of my time:
the society now consisting of young and middle aged persons,
and in some places the number of Friends are much reduced.
Yet it may be said,
there is a revival of religious concern in the minds of many who remain;
so that meetings are better attended than in former years, and good order preserved.
The affairs of the society are also conducted in love, and brotherly affection;
which gives room to hope we are not far distant from better times.
However this may be, it behooves us to be attentive to our present concern,
and to renew our endeavours to come up in the discharge of our duty,
in our various allotments, in civil and religious society.
As this is our experience,
we shall first take care to have our life and conduct ordered in the fear of the Lord,
so as to be good examples to others;
and from the influence of that love which has produced good fruits in us,
we shall be inclined to help our neighbours and friends.
Far from saying, with one formerly, who slew his brother, "`Am I my brother`'s keeper?`"

Here I close (for the present) this short relation of some circumstances of my life,
being now in the seventy-sixth year of my age: continued, in much weakness,
beyond the years of many of my predecessors.
The remaining part of my sojourning in this land of sorrow, I desire to dedicate,
as far as my health and strength will admit, to the service of my great Lord and Master;
the remembrance of whose goodness often bows by mind,
and occasions thankfulness beyond what I have words to express.

[.centered]
=== Extract.

The state of the society, of which I am a member,
is often a subject of my serious consideration.
I fear for many among us,
that they are verging towards a conformity to the customs and manners of the times,
out of which our forefathers were led, especially as to speech and apparel.
I observe in many a compliance with the custom of speaking to a
single person in the plural number instead of the singular;
and of changing the colour and fashion of their clothes, as the times require,
so that they are not to be distinguished from their neighbours by an outward appearance:
this I fear will lead to a conformity in other customs which are not suitable to the
plainness and simplicity for which we were distinguished in the early times of our society.
I fear likewise for some,
that they will grow weary of that way of worship which has been adopted by us,
of allowing a great part of the time of our meeting to silence,
without having anyone appointed to speak at fixed times as a public preacher,
or to make use of prayer in a customary way.

When in our religious assemblies we are at times deprived of ministerial help,
there is this advantage in it, if rightly improved,
that it puts us upon enquiring into the ground of our religion;
what experience we have of Divine support, separate from all secondary means,
should they be withdrawn from us.
We are too apt to depend on the help we have been used to receive from
the labours of those who are employed as the ambassadors of Christ;
and when they have no longer a message to us, the time we spend together is unpleasant,
for lack of that self-employment, in which we might find,
through the gracious assistance of our Divine Instructor,
that which would prevent all tediousness, and bring us to say,
"`Lord let not man teach us, but you teach us.`"

Thus we might receive more lasting benefit,
and come to renew our acquaintance with him who is the minister of ministers,
and a never failing source of comfort to his depending people.

[.signed-section-context-close]
7th Mo. 23rd, 1802.

[.centered]
=== Extract.

It is something to be sustained for our daily work,
and to have our oil renewed daily as it wasteth.
The mill gets by going, says the Proverb, though it stir not from the place.

However you find your heart, be making use of the means afforded you to make it better,
and wait on God for the increase of grace.
What a dreadful thing it is for a man to come newly to the study of his soul,
as what he has been unacquainted with! when sickness is upon him, and death at hand,
to be then newly to ask, What am I? and what have I done?
and what will become of me forever?
is a most fearful state of folly.

If after much labour and thoughtfulness you find your heart, in your own apprehension,
not better, yet continue your labour;
it is not the last blow of the axe alone that cuts down the tree,
though it falls not till the last.
The growth of grace, as of plants, and fruits, and flowers,
is not perceived by immediate inspection.
There is much good obtained when we discern it not:
and nothing is more certain than that honest diligence
is never lost in the things of God and our salvation.

It is worth all our labour, if we grow no better,
to keep our spark from going out) and to see that we grow no worse.

1803+++.+++ Being now arrived, through divine favour, at the seventy-seventh year of my age,
there is room to expect,
that the days of my pilgrimage will not be much further extended.

It should therefore be my principal concern to prepare for this great change,
by a humble circumspect walking; and attention to my religious duty,
in what remains of the work and service which may be required of me,
by my great Lord and master Jesus Christ.

In the 3rd Mo. 1804, I count my seventy-eighth year to be completed.

[verse]
____
When all your mercies, O my God,
My thankful heart surveys,
Affected with the view, I`'m lost
In wonder, love, and praise.
____

[.signed-section-context-close]
Fourth of Seventh month, 1807.

From the time at which these short memoirs were closed, to the time above mentioned,
nothing has occurred as to my religious engagements that I am inclined to mention;
my health has been so favourably continued,
that I have been seldom hindered from attending meetings in the place of my residence,
and parts adjacent, for the purposes of religious worship,
and of transacting the affairs of the church,
besides attending the yearly meeting in London with but little if any intermission.
I am now in the 81st year of my life.
Upwards of fifty years have passed since I first
opened my mouth in a public testimony to the truth,
in our religious meetings; and though my strength will not admit of any long journeys,
as in years past, I have to consider it as a favour,
that my bodily faculties remain in a good degree, and that my love to the cause of truth,
and the friends of it, is not diminished.

The state of our society is often the subject of my thoughts.
When I perceive a declension among us, in many places, as to the life of religion,
I am led to fear lest the good testimonies we have had to bear, should be made light of,
or neglected and gradually lost.

From the most early times of the society we were distinguished
by a conduct in various respects different from our neighbours;
and our dissent was not from a view of singularity,
but from an apprehension that there was need of a further reformation
than had taken place among the various professors of the Christian name;
and that many customs of former times were retained,
not consistent with the spirituality of that holy religion,
which we are called to partake of.
When it was found we could not prevail to introduce better ways than had been adopted,
we thought it right to attend to our own conscientious scruples;
and by degrees formed a society of religiously disposed persons,
whose principles and practices were more agreeable to Christian simplicity,
and the nature of true religion.

This was the state of our society in early times,
and there must be the same spirit to animate us in the present time,
if our profession and character are properly supported.^
footnote:[_1807. Elapsus est annus octogesimus peregrinationis mea in hoc eremo;
Diei quot restant nescio; pauci forsan.
Fiat voluntas domini mei.
Mihi vivere est Christus (ita sit semper), et mori lucrum._]

In the year 1808, being the 83rd year of my life, I was at the yearly meeting in London;
which I had attended about sixty years, with little if any intermission.

This I mention to commemorate the Lord`'s merciful dealing with me,
in thus extending the days of my life to an age exceeding that of my relations and friends;
most of whom if not all have been removed at an earlier period.

In the midst of many blessings I have to experience a share of affliction,
with many of my dear friends,
which confirms to me the truth of what is expressed by the prophet,
"`That in the Lord`'s hand there is a cup, and the wine is red:
it is full of mixture and he pours out the same:
but the dregs thereof all the wicked of the earth shall wring them out,
and drink them.`" Isaiah 75:8.

30th of 6th Mo. 1809.
I consider it as a principal favour, in my far advanced years,
that I can adopt the language of a good man in former times,
who thus expressed himself to the people, among whom he had long resided,
and was about to take his leave of them: "`Whose ox have I taken?
or whose ass have I taken?
or whom have I defrauded?
or of whose hand have I received any bribe to blind my eyes
therewith?--and I will restore it you.`"

[.signed-section-signature]
John Kendall.

[.signed-section-context-close]
2nd Mo. 16th, 1810.

In the year 1810, I was again at the yearly meeting, where I met with many of my friends,
whose countenances denoted a religious disposition to have taken place in their minds,
though but few among them of my old acquaintance, the society now consisting,
in a great measure, of those who are young in years, and middle aged persons.

In the year 1811, I was not at the yearly meeting:
but felt a concern to send a few lines to my friends there assembled,
as a salutation of endeared love, as follows:

[.embedded-content-document.epistle]
--

[.blurb]
=== To my dear Friends who are met in London for the purpose of transacting the affairs of the society, and consider of what may tend to promote the welfare of it.

While, through age and weakness, I am prevented from giving my attendance,
as in years past,
there is a salutation of love in my mind which I am inclined to express, by a few lines,
if it should be thought proper to have them brought under your notice,
from an aged brother, and sincere well-wisher to all the concerns of the society,
to which I consider it as no small privilege to belong.

In the course of many years, from youth to age,
I have had opportunity of seeing great changes, as to the state of the society;
and am comforted in having to believe,
there is a revival of concern in the minds of many of the present time,
that the breaches which have been made for lack of attention, may be repaired; and,
as this good work is begun, let us hope it will be carried on, to the praise of Him,
who is the repairer of breaches, and the restorer of paths to dwell in.

I take this opportunity of advising my dear friends to avoid the great harm which
comes from unsuitable connections by marriage with persons of different persuasions,
both in a religious and civil capacity;
and as a true regard and love to my friends has occasioned
my taking this liberty in addressing them,
so I am induced to express my concern that the good esteem
which has been obtained by means of upright walking,
may not be lost by any unsuitable liberty taken, contrary to the profession we make.

[.signed-section-closing]
These from your affectionate friend,

[.signed-section-signature]
John Kendall.

[.signed-section-context-close]
24th 5th Mo. 1811.

[.signed-section-context-close]
By the indulgence of a kind Providence, in the 85th year of my life.

--

The Yearly Meeting thought proper to send me the following acknowledgment of my love.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Yearly Meeting, 1811.

A salutation of love,
contained in a few lines from our ancient friend John Kendall of Colchester,
was received, and being read in this meeting, is very acceptable.

[.signed-section-signature]
(Copy) William Manley.

--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Yearly Meeting, 1812.

A salutation of love, contained in a Letter from our ancient friend John Kendall,
of Colchester, was received, and being read in this meeting is truly acceptable:
it is sent to the Womens`' meeting, and is as follows:

[.signed-section-context-open]
Colchester, 23rd of 5th Mo. 1812.

[.blurb]
=== To my beloved and much esteemed friends who are met together in our annual assembly, for the caretaking and management of the concerns of the Society.

[.salutation]
Dear Friends,

When I took the liberty in a former year of sending a few
lines by way of address to my friends who were then met,
I did not expect it would be my concern in any future
time to express the love I have for them,
and the good cause in which they are engaged;
but as it has pleased the Divine Goodness to extend my days to another year,
I am again concerned to write a little matter for the notice
of those who may be met this year on the like occasion.

Though I am not qualified nor able to be assisting
in the various concerns which may come before you,
yet my desire and good wishes for your welfare remain without any abatement;
and when I consider of what is most likely to promote the interest of the society,
and support it on a good foundation, it appears to me to be love!
The love of our gracious Redeemer, and love one to another!
May it increase and abound among you to the preventing
any harm which might come from a variety of sentiment,
or different apprehension of things.
The last legacy of our Saviour to his followers remains to be fulfilled,
that they love one another.

As to the well ordering of the meetings which may be held,
I have only in particular to recommend, that by the most gentle means which can be used,
you may endeavour to prevent the inconvenience and interruption which is occasioned
by frequently going out and coming into the meetings while the business is transacting;
I have been witness to the hurt of it, which makes me give this advice.
I wish to encourage, rather than to prevent,
the young people from giving us their company;
but I desire they would consider it is not barely to gratify an
inclination we may have to see our dear relations and friends,
but to be instructed and comforted by their wise deliberations,
that we thus meet together,
and that it is no small privilege to sit with our friends on these occasions.

In the love and regard which takes place in my mind towards the youth among us,
and all my dear friends of every class,
I thus address them in my far advanced years (being
now in the eighty-seventh year of my life);
wishing their growth and establishment in that precious
Truth which they have been measurably made partakers of.

[.signed-section-closing]
I remain their affectionate friend,

[.signed-section-signature]
John Kendall.

--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Yearly Meeting, 1813.

The following affectionate and acceptable letter was received from our friend John Kendall;
and being read, was very cordial to this meeting.
It is sent to our Women Friends.

[.signed-section-signature]
Copy, William Manley.

[.blurb]
=== To the Yearly Meeting held in London 5th Mo. 1813.

[.salutation]
Dear Friends,

By means of increasing years and weakness, (being in the 88th year of my life),
much of my natural strength is gone; yet from the love and regard I have for my friends,
and the society of which I have been a member many years,
I am again inclined to send a salutation of love.

As that which first formed us to be a people was love,
so it will be the support of the society when all
other supports shall fail and come to an end.
We have therefore great occasion to desire this may be continued, and increase among us,
as a principal good.
There is nothing more precious and acceptable in the sight of our heavenly Father,
than the continuance of it among the Lord`'s people:
and nothing more desirable to our enemy than the breach of love.

May it be our concern to make use of every means afforded us to
maintain and support that which brings so much comfort to our minds,
and is attended with such great advantages.
This is the desire of my mind on behalf of my dear friends; that,
as they came together from a motive of love,
they may return to their several habitations freighted with this love,
and with a message of peace from the God of all peace,
to those who make it their concern to honour him in their lives and conversations.

In the degree of his love, which I feel to enlarge my heart, in writing these few lines,
I remain your affectionate friend,

[.signed-section-signature]
John Kendall.

[.signed-section-context-close]
(Without date).

[.postscript]
====

I here adopt the language of a pious man, who thus expresses himself in his Diary:

"`Firmly believing that my times are in the hands of God, I submit myself,
and all my affairs, for the ensuing year,
to the wise and gracious disposal of the Divine Providence;
whether God appoint for me health or sickness, peace or trouble, comforts or crosses,
life or death--his holy will be done.`"

====

--

[.signed-section-context-open]
5th Mo. 1815.

From this period it does not appear that our relative left any further account of himself;
indeed, from advanced age and increasing weakness, he was probably not able to do it.
It may be proper therefore for one of his near connections briefly to supply the defect.
In the summer of 1812 he met with a serious accident.
Having walked some distance to visit a friend, he fell in ascending the steps:
he did not perceive at the time that he had received any material hurt,
but on being conveyed home, he found he had not the use of his arm; which,
on examination, proved to be broken.
This occasioned a confinement of many weeks; yet he was favoured to recover,
and get frequently abroad again.
In 1813 he again fell in his own parlour, and sustained another severe injury,
which disabled him from walking, even into an adjoining room,
without the assistance of one or two persons;
indeed for the greater part of his remaining time, he was confined to his bed.
He was still in an eminent degree preserved in calmness and resignation; waiting,
as he often expressed, till his appointed change should come.
His mental faculties continued clear and lively to the last;
as appears in part by a letter he dictated, in the Seventh month, 1814,
to an endeared and intimate friend (now likewise deceased), which,
with the reply of that friend,
produced under circumstances equally disabling him to write,
will be found at the close of the collections of letters hereto annexed.
In a visit paid him in the autumn of this year,
it was both pleasing and instructive to the writer to behold him,
under great bodily weakness,
clothed (as indeed he had been in a great degree through
his whole life) with love and good will to every one.
He continued pretty much in the same state till the middle of the First month, 1815,
after which time he declined rapidly.
A short time before his decease, among many other religious expressions,
he uttered the following: "`Our lives are in the hand of a kind Providence,
to give or take away,
and I desire we may be helped to be thankful for all his dispensations.
I wonder my days are thus prolonged; but amidst afflictions,
I have cause to be thankful for many mercies; in the hand of the Lord there is a cup,
and the wine is red; it is full of mixture;
we have an unwearied enemy who seeks to draw us aside;
and if he cannot in great things he will by little ones;
but while I am speaking I feel great thankfulness in my mind,
that we are not left without one to help us; this is an unspeakable mercy.
I have had a great share of the Lord`'s goodness to me, both by sea and land;
and now my life is prolonged in a wonderful manner;
I can recommend nothing better to us than the love of God;
oh! this brings great sweetness with it!`"

On the 27th of the First month,
he requested his relations and those who attended on him to be quiet, adding,
"`I am quiet;`" and serenely breathed his last.
"`The work of righteousness shall be peace, and the effect of righteousness,
quietness and assurance forever.`"^
footnote:[Isaiah 32:17]

[.signed-section-signature]
J+++.+++ C.
