== Chapter 2

Dear Brother,

I am not free from troubles on my own account, and besides,
have the care of others upon me, as you are sensible.
Indeed we have no room to expect to be without them, in the present frail state of being!
I much desire we may be preserved from any unsuitable complaints,
and helped to keep our places;
learning to bear with patience all the cross occurrences of our lives;
in which there will be a great advantage, as a right disposition prevails.
I have found by long experience, that what is most painful is often the most profitable:
as we are not able, by our weak capacities, to judge of things rightly,
the best way for us is, to leave the event to the disposal of the all-wise Providence:
and be more concerned how we may keep our places in times of trouble,
than how we may be exempt from them:
much might be said in favour of a humble submission to the dispensations of Divine goodness,
which are ordered in great wisdom, often for our benefit when hid from our view.
May we always, and on all occasions,
endeavour to bear our exercises and trials cheerfully and quietly; avoiding a fretful,
uneasy disposition, which is too apt to prevail, and show itself in us, to our own hurt,
as also to the hurt of others: whereas,
when we bear the provocations with proper fortitude, by Divine assistance,
there is nothing rough or impatient appears,
but a mildness which is comfortable to ourselves and edifying to others.
This is the way to overcome our enemies, without strife or contention,
which must not have place in a religious mind; if we are injured,
and find it not in our power to obtain redress by gentle means, then to submit,
and suffer patiently the greatest injuries,
rather than have our minds tinctured with bitterness.
Considering how much it is against our interest to
indulge a disposition for strife and contention,
it is matter of wonder that it should so much prevail.
Let us seek for those influences of Divine love, which, as they have place,
will regulate the greatest disorders;
indeed nothing short of this is able to help us effectually.

I wish some instruction and help may be gathered from these hints,
and that by a steady perseverance in the way of Truth and Righteousness,
we may be a comfort to each other,
and that our outward relationship may be accompanied with that
unity of spirit which is more excellent than natural ties.

I remain your affectionate brother,

J+++.+++ K.

Colchester, 30th 12th Mo. 1763.

Dear Friend,

I am led to desire your prosperity and welfare;
and if I apprehend any danger attending you, it seems to be my duty to inform you of it,
in the best manner I am capable, least our common adversary should get the advantage,
to your hurt:
I trust you have had some experience of the advantages which come from a watchful,
circumspect walking in the fear of the Lord, and are desirous of being preserved in it;
but there is such a disposition in us to join in with what we like,
even though contrary to our best interest,
that we have need to use all things with caution,
rather giving up the most desirable comforts, than be, in the least degree,
obstructed in our progress towards everlasting rest.
Better is it to enter into heaven in the condition of Lazarus, who was poor,
and destitute of outward comforts, than to be in the rich man`'s condition,
having all things that his heart could desire.
The counsel of our great Lord is applicable to us: "`If your right eye offend you,
pluck it out; or if your right hand offend you, cut it off;`" this, no doubt,
is meant in a spiritual sense.

My advice to you is (which I hope to regard myself), not to aim at high things,
but be contented with the share of understanding you are favoured with:
nothing adorns us like the truth.
Happy are those who wait for its help, and depend upon it for instruction,
and witness an advancement in knowledge and understanding under its direction:
their improvement is such as will lay a foundation for everlasting happiness,
as well as stability here.
Human accomplishments, upon which we are apt to rely,
will fail to bring us the strength needed.
The power is in the cross, which must always accompany us,
if we continue to be true disciples of Christ.

I have found it necessary to refrain from things
towards which my inclination strongly led me,
and which seemed likely to tend to my improvement in desirable knowledge.
The work we are engaged in (which is the salvation of our souls) is an arduous work;
and in order to its going rightly forward, much must be forsaken,
many outward supports given up, and our life must be by faith,
this prayer often having place in our minds: "`Lord! not my will, but yours be done:
take from me all that is unsuitable for me,
or any way hinders me in my progress towards your kingdom.
I am weak and infirm, not able to distinguish the safest way for me to take;
but ready to embrace my enemies as friends; watch over me,
and permit me not to fall a prey to my enemy.
Favour me with secret intimations of his snares: let me always ask counsel of you,
and make me willing to follow you, wheresoever you lead.`"
Under this concern there is room to hope we shall be preserved, so as to hold on our way,
and experience a settlement upon the most sure foundation,
which is Christ the rock of ages.

I know of no other motive than true friendship, in writing to you after this manner.
I much desire it may prove useful to you:
and that you may be preserved from all hurtful things;
in order to it we must retain a sense of our own nothingness, need, and insufficiency;
having no confidence in our own strength,
but still waiting upon the Lord for the renewing of strength.
He is a sure defence to all them that put their trust in him.
To his protection I commit you, with myself, and remain your well-wishing friend,

J+++.+++ K.

Colchester, 9th of 8th Mo. 1764.

Respected Friend,

I was pleased to meet with you and your mother, at Woodbridge.
The esteem I have for you is such, as induces me to desire your welfare;
and for you in particular, I have felt an affectionate regard.
Considering your situation and the dangers surrounding you,
I have wished to feel some counsel in my heart towards you,
which might be proper to communicate and prove beneficial to you.

I see the great advantage likely to attend your faithful
adherence to what the best instructor of your mind,
as also the advice of your dear parents and relations,
may point out as the way for you to take: and the harm which is likely to come,
should you act contrary to it; the one will bring you peace and comfort,
and promote your happiness both inward and outward; the other occasion trouble, need,
and distress, inexpressibly great: such as no outward enjoyments,
however desirable and pleasing to the natural inclination, can make up.
Mayst you then be so happy, as to make choice of the better part,
and adhere to that counsel which tends to promote your good,
let it be ever so contrary to your inclination.
Consider what an advantage it is to have a religious parent, which you enjoy,
and I hope will prize;
but it is a still greater advantage to be favoured with the visitations of Divine goodness;
which, I believe have been extended to your mind, in order to keep you,
and preserve you from all hurtful things;
and to make you a partaker of the excellent privileges of the Lord`'s people.
This blessing we cannot command, but may procure a continuance of,
through our faithfulness; as we may occasion its being withdrawn,
through joining with that which displeases our great Benefactor.

If anything hurtful has obtained place in your mind, so as to obstruct your peace,
and hinder your progress in the way everlasting,
may you become concerned to have it removed,
that the Lord`'s favour may be renewed to you,
by which only you can experience preservation.

Be not discouraged if opposition is met with, and difficulties, to appearance,
insurmountable; that arm which has been extended for your deliverance,
is able to help you in all difficulties, and save you with an everlasting salvation;
as you seek for its help, in the depth of sincerity, you will be a sharer of that good,
which your mind is brought to seek after.
Remember, the crown is not to be obtained but by bearing the cross;
and that which we come at with greatest difficulty, is the most valuable to us;
when that which comes easily, and suits our will, is often greatly prejudicial.
I therefore advise you not to gratify your inclinations,
whether they may be after undue liberty, or whatever you may be drawn after,
by secret incitements of your mind, or by temptations from without,
by such as may profess friendship to you; but whose example is not fit for you to follow;
nor can you be their associate without great harm.
You must deny yourself of enjoyments which seem reasonable,
in order to get on your way with safety; there are many hidden dangers,
which you are not able to discern, but by a constant watchfulness,
and seeking to the Lord for direction and help.

In conclusion, I would say, keep near to your friends,
and highly esteem those who labour for your good; endeavouring to defend you,
as a tender plant, from the blasts and storms to which you are exposed.
Whatever tends to set you at a distance from them, is your enemy.
Follow their advice, accept of their help, which you greatly stand in need of;
be diffident of your own strength; here I have found there is safety;
and on the contrary, great danger in being confident of our own wisdom or strength.

You have a privilege above some others, I mean in a religious parent;
and therefore will be the more inexcusable should you take a wrong course.
Do not forget the obligations you are under to your dear mother,
whose peace and comfort depends upon your good conduct; if she lose you,
it may almost be said, she loses all this world can afford.
Consider how much it is your duty and interest to please her, whose troubles are great.

With tenders of true affection, I remain your friend,

J+++.+++ K.

Colchester, 11th 1 Mo. 1765.

Dear Friend J. V.

Oh! the greatness of that mercy we have been made sharers of! both
in the early visitations of Divine goodness to our minds,
and in the preservation through many dangers attending from that time;
how can it be expressed?
I desire we may remember it in deep humility,
and be making grateful acknowledgments to the Author of every good and perfect gift.
If all that we may wish for be not given to us, we must not complain,
nor by any means omit to improve the advantages we partake of, which are many,
if well considered.
It is those that are faithful in the little who are made rulers over more.
The increase of strength, in our religious progress,
depends upon our faithfulness to the Lord`'s requirings.
Thus you will find, that all the shakings you have to meet with,
both from within and without,
will tend to your further establishment in the ever blessed Truth, and way everlasting.

By shakings, I mean those changes and alterations attending our outward condition,
as well as experienced in the state of our minds: some of which are hard to account for,
and very trying and painful, yet productive of good, as we abide in the patience.
It is found true in the experience of the religious mind,
that nothing less than a Divine power, which comes by Jesus Christ,
can preserve us in the dangerous voyage of this life;
wherein many storms are to be endured, many rocks and sands avoided.
Even when, to appearance, we are most secure, there is danger of being lost,
for lack of watchfulness.
Our trials are in different ways; and there is no safety for us,
either in prosperity or adversity, but while under the Divine protection!

May it become our concern to witness preservation, and to pass on with safety,
rather than to seek after ease and pleasure, which are but transitory.

I remain your affectionate friend,

J+++.+++ K.

Colchester, 18th 1 Mo. 1765.

Dear Friend M. M.

It gives us great pleasure to hear of your welfare;
and I hope the correspondence between us will be continued, to our mutual comfort:
but there are times when we find lack of ability to communicate
anything which may be profitable to others,
having little for ourselves.
We are poor creatures,
and have need to learn more perfectly to be submissive to
all the dispensations of Divine goodness towards us,
which are in great wisdom, and for the benefit of such as love and fear God.
I much desire we may bear the correction of his hand,
that so we may be refined from the corruptions of nature,
and made fit vessels for his use!
There is occasion for frequent baptisms, in order to cleanse from defilements,
which we are still liable to; though we have experienced, in a good degree,
being cleansed from them.
Nothing short of watchfulness, in the light, can be depended on to preserve us.
When we are in a low state, and ready to think we are forsaken, let us exercise patience,
and wait for the renewing of Divine consolation;
and not be contented till we have found him whom our souls love:
whose presence more rejoices us, than the increase of corn, wine, or oil.
We often have to mourn because of his absence, and are ready to say,
Why have you forsaken me?
This is the day of trial, which none can abide but those whose foundation is upon Christ,
the rock of ages, the help of the righteous, in all generations.

We have room to consider that to be our good,
which tends to bring us into a humble state of mind, however unpleasant it may be.
An easy and pleasant path is not found to be the safe path for a religious mind;
it is not uncommon for some to grow, and advance in appearance;
but it is faster than they have root to support them: going on smoothly,
they are not aware of the dangers surrounding, and when times of great trial come,
they are not able to stand.
That we may not be of this number, is what I much desire;
if affliction is necessary to prepare us for trials which may be permitted to attend,
it is good for us to have it.

I conclude with remembrance of kind love to you and your wife, in which mine joins,
your affectionate friend and cousin,

J+++.+++ K.

Colchester, 9th 6 Mo. 1766.

Dear Cousin,

You are sensible, we are not always capable according to desire,
to express the sentiments of our hearts to each other,
though our good wishes may remain entire: for my part, I often feel a poverty of spirit,
which is hard to be expressed; and here is the trial of faith and patience,
which is so profitable to us.
I have thought it is necessary we should be thus tried for our own good;
and that we may be in a condition to help others, the most desirable thing is,
that we may be what the Lord would have us to be.
Whatever exercises may be met with, in our passing through this vale of tears,
it is best not to be much thoughtful about them;
if the Lord is our trust and confidence he will make way for us,
and withhold nothing that may be necessary for us to have, or our state may require:
thanksgiving and praises be rendered to him, a remnant,
who have passed through deep waters, in a spiritual sense,
can speak well of his great name!
May it become our care and concern to please him, and walk answerably to his requirings,
who has done so much for us; and so mercifully renewed his goodness,
when we have offended him, and had nothing,
that we could see to recommend us to his favour.
Yet he has been to us as a healer of breaches, and restorer of paths to walk in;
whereby our wounded spirits have been comforted, and fresh resolutions begotten,
that we would serve him more faithfully.
We thus are preserved, and helped, and can say measurably, as David:
"`O Lord! you have brought up my soul from the grave, you have kept me alive,
that I should not go down to the pit.
Sing unto the Lord, O you saints of his;
and give thanks at the remembrance of his holiness for his anger endures but a moment;
in his favour is life: weeping may endure for a night, but joy comes in the morning.`"

We have largely experienced of the Lord`'s goodness,
and no doubt he requires more of such as he thus favours with the knowledge of his ways;
and prepares by a variety of exercises for the manifestation of his will,
whom he would make vessels of honour in his house, to show forth his praise.
These must submit to his forming hand,
and be contented in the various dispensations of Divine goodness,
without desiring to have this, or that,
which they may see others are in the enjoyment of, or aiming to be what others are,
whom they may esteem.
All is in the hand of God, our Saviour;
who dispenses to the needs of his people in great wisdom,
though not in the way that we understand.
It is therefore needful for us to wait upon him, in submission; and say, "`Lord,
not my will, but your will be done on earth, as it is done in heaven.`"

I believe this is what we would willingly experience,
but many things are met with to hinder our coming to this state of resignation;
many infirmities to contend with,
which are to be overcome only in the name of the Lord Jesus: let us trust in him,
that as he has begun the work, he will complete it, to our joy,
as we believe and are obedient.

I close my letter with these thoughts on a religious subject,
and remain your affectionate cousin,

J+++.+++ K.

Colchester, 16th 2 Mo. 1767.

Dear Cousin,

It has been a sickly time with us;
several of our relations and friends have been removed, by death;
and I think your wife mentioned it had been the same with you.
We have many mementos of our weakness, and the uncertainty of earthly comforts,
which I desire we may make a proper use of; that whenever the time of our change comes,
we may have a comfortable hope of being received into the Divine favour.
Many are closely joined to the concerns of this present life,
and it is to be feared the care of their everlasting welfare,
is too little attended to or regarded.
The state of such is to be lamented.
I pray we may be preserved from it,
though it should be our lot to meet with exercise and trouble here;
the peace which attends a religious disposition makes amends for all.
If we have no great things to speak of, I trust we have this testimony to bear,
that God is no hard master, but a rich rewarder of those who diligently serve him:
that though he sees fitting to try his people, he never forsakes them.
There is good cause therefore to wait upon him for the renewing of his help,
when low times are experienced; we cannot safely conclude ourselves to be forgotten,
or excluded from his favour, on account of the barren condition of our minds,
but must exercise patience, in hope of his appearing,
who comes with healing under his wings,
and as a morning without clouds to his depending children;
when they have mourned in his absence, and their cry has been to him, in secret,
for help.

Though the times we live in are such as call for mourning,
and there is little room to look abroad for help, Truth is the same; that is,
Christ`'s spirit and power is the same, to support in all difficulties,
if we are concerned to live, and walk in it, choosing it for our portion;
let others think, or say of us as they will,
we shall not be hurt either by their frowns or smiles.
Great indeed are the privileges and benefits we become partakers of,
through a faithful adherence to the dictates of our heavenly teacher, and unerring guide,
of which you are not insensible.

With remembrance of kind love to you and your wife, in which my wife and mother unite,
I remain your affectionate cousin,

J+++.+++ K.

Colchester, 12th 3 Mo. 1767.

Dear Friend,

I cannot well forbear telling you that you have been much in my remembrance of late,
and it would afford me pleasure to receive a letter from you,
which the friendship subsisting between us I hope will admit of,
though no outward business should require it.
And lest a deficiency on my part should be any obstruction,
I now endeavour to do something which may tend to
promote a renewal of that love of our heavenly Father,
which is so comfortably felt by us,
as we are favoured to keep near to him who is the spring of all love,
the distinguishing mark of whose disciples, is to be, that they love one another.
Indeed the more nearly we are united to Christ our Saviour, and abide in his love,
the more will our love increase to each other;
and the more will that which is of a contrary nature be removed;
no room being left in the mind for discord, or variance,
but an ensign of peace is lifted up, and we come to engage under his banner,
who is the Prince of Peace, and who overcame by suffering,
thereby obtaining a crown most glorious,
which we shall become partakers of by following his example.

I write not thus because I think you are unacquainted with these truths;
but it is common for Friends to speak to each other of things which employ their thoughts,
and to tell our experience, in a religious sense.

I herewith send you assurances of my love and continued friendship,
and remain your affectionate friend,

J+++.+++ K.

Colchester, 30th 6 Mo. 1767.

Dear Friend, J. V.

I often think of you, with the rest of Friends in Amsterdam;
and it will afford me pleasure to be, in any degree, helpful to you,
in a religious sense; but you are sensible, when outward help fails,
the Lord is able to make up this, and all other deficiencies to us,
in our several situations, by the help of his good Spirit; to him, therefore,
the expectation of his people must be, and upon him they must wait for assistance.
He is no hard master, requiring things which it is not possible to perform,
through his assistance.
I desire it may become our concern to walk answerably to his requirings,
being devoted to his service,
and contented in the condition allotted us in his Providence.
Thus we may become partakers of an admittance into Divine favour,
when these few uncertain moments are gone.
If after using our best endeavours, we still have occasion to ask for mercy,
what will become of us then, should we be careless,
and admit of wrong things to have place in our minds.
These words of Holy Scripture should often be thought of,
"`If the righteous scarcely be saved, where shall the ungodly and sinner appear?`"

My dear friend, I much desire that peace may attend you, both here and hereafter;
as it has pleased the Lord to spare you to this time,
while many of your acquaintance have been removed by death,
may your mind be affected with a sense of the obligation there is upon you,
to do what you can to serve him,
who has so graciously vouchsafed to help and preserve you through a variety of exercises,
from youth to a pretty far advanced age.
Though you still labour under some difficulties, be not discouraged;
the hand which has supported is able to support you to the end,
and will undoubtedly support, as there is a suitable dependance upon it.

In my thus writing, though I address myself to you,
at the same time I think of your dear wife,
who I desire may become a sharer in the comfort, as she has to partake of the exercise,
attending a Christian life.
I believe she is one who rather chooses to suffer affliction with the Lord`'s people,
than to enjoy the pleasures of sin which are but for a season,
though it may seem as if she was left alone, without help from without.
This may be our comfort,
that the Lord is a rich rewarder of them that diligently serve him,
and will not forsake his people in their affliction, but will give beauty for ashes,
and the oil of joy for mourning, and in his own time relieve their needs.

We must not be dismayed at the variety of troubles which are permitted to attend us;
the gracious promise of Christ our Saviour, is, "`Be faithful unto death,
and I will give you a crown of life.`"

In conclusion, I remain with tenders of kind love to you and your wife,
your affectionate friend,

J+++.+++ K.

Colchester, 15th of 5 Mo. 1768.

Dear Friend, J. P--n, of Philadelphia.

I received your letter of 2nd mo.
last, which was very acceptable to me: I am sorry to hear of such troubles in our parts;
yet am ready to hope, that by the prudent conduct of some,
the dismal consequences which are apprehended will be avoided:
it is a sad thing to have such people as you mention come into your country.
Friends, and the sober part of the inhabitants,
had need to show the greater kindness to the Indians,
in order to make amends for the cruel treatment they meet with from these wicked men.
As you say, much confusion seems to attend affairs in our land,
and a gloomy prospect appears; there have been great disturbances in some places,
in choosing members of parliament:
great companies of dissolute people have assembled together in London;
some insisting on their wages being raised by their masters; others pretending liberty,
have attempted to force the prison where Wilkes was confined,
but were repulsed by the soldiers.
Many of the lower sort of people are got to a great height of wickedness,
and the present high price of provisions is made a plea for their tumultuous conduct.
There is great occasion for wise and good men to be at the helm of government,
in order to quiet the present uneasiness in the nation.

With regard to matters of a religious concern in our society,
I have not much to say which might afford you comfort;
a great declension appears in many places, as to number,
and a deviation from the plainness,
and simplicity of life and manners which distinguished our predecessors;
yet in some parts again, there is an increase; and a remnant scattered up and down,
who have kept their integrity to the Lord, and prefer his Truth to all other enjoyments.
May the number of these be increased, by the work of Divine grace in their minds:
and may we be concerned to keep near to that good power
by which we have been helped and preserved in times past,
that in our small measure, we may be instrumental to promote the work of reformation.
We have need to seek for renewed favour and help to our minds,
lest the same lukewarm spirit which so much prevails in the society,
should take hold of us, to our own great loss,
as likewise the loss of others who may be looking to us for example.

The domestic peace and happiness you speak of as attending you, is pleasing to hear;
I have cause to be thankful for the same favour:
my wife and mother desire their kind love to be mentioned to you and yours.
I am pleased to hear of my dear friends Daniel Stanton and William Brown;
I request you to give my love to them, as opportunity offers.

I am your affectionate friend,

J+++.+++ K.

Colchester, 26th 10 Mo. 1768.

Dear Cousin,

These are trying times, in which if we can find favour, to be helped in our necessity,
there will be cause of thankfulness: we must however go on in patience;
hoping for the resurrection of that life, which is our cause of rejoicing,
both in prosperity and adversity; we are not unacquainted with those exercises,
by means of which contentment is learnt, in the various conditions allotted us.

With regard to troubles; I sometimes think, if we were without them,
where would be the trial of our faith,
or how would those Christian virtues which the apostle speaks of, appear in us,
and abound to our growth and establishment in the truth?
It is true we have had our share of afflictions in times past;
but if there should be more for us to meet with,
I desire we may receive them with patience,
still having our dependance on Christ our Lord,
the Saviour of all those who put their trust in him.
How often are we driven to seek refuge in his arm of power, invisible as to human sight,
when outward dependencies fail, and hardly any visible help is known from man:
when the Aarons and Hurs are not to be found, what would become of us,
were not our hands supported by the God of everlasting strength;
when the archers shoot at us, how shall our bow abide in strength,
or our branches spread over the wall of opposition,
or the arms of our hands be made strong?
It is a great thing to experience this help, yet it must be waited for, and sought after:
in the Lord alone is our strength.

I remain in the fellowship of the gospel, your affectionate cousin,

J+++.+++ K.

Colchester, 6th of 11 Mo. 1768.

Dear Friends, J. V. and Son, (of Amsterdam,)

Though the number of friends, in the place of your residence, is now become small,
I hope you will not be discouraged from holding your meetings,
in the innocence and simplicity of the Truth.
And should it be frequently so, that there is no outward ministry among you,
you know the benefit of our religious meetings is not confined to that;
the Comforter of his people is near to those who wait upon him.
Though testimonies fail, and declarations come to an end,
the word of the Lord endures forever; upon this we can trust with safety,
as the stay of our minds, when outward help fails:
if what we have to experience leads us to a more full dependence on God,
it will prove to our advantage, however unpleasant it may be.
You know, my dear friends, it is not a bare profession of religion,
or an outward comprehension of the great truths of it,
that will be sufficient to administer to us an entrance into that kingdom,
which stands not in meats and drinks, forms and ceremonies,
but in peace and joy in the Holy Spirit.
There may be great shows of religion,
where true religion has had but little place in the mind;
our expectation or looking must not therefore be outward, where the uncertainty is,
but we must be concerned in the secret of our minds,
to witness the appearance of God`'s holy Spirit and power,
which helps to subdue every wrong affection and lust,
and by its operation makes us truly followers of Christ, who worship him in the spirit.

I much desire this may be your experience, amidst the various changes that attend,
during our earthly pilgrimage: that when time to you here shall be no more,
you may have to join the assembly of the righteous in heaven,
which no disturbances can reach, like those we meet with here;
and where we hope to meet with many of our dear relations and friends,
who are gone before us.
What can be so desirable as to attain this happiness,
and what is there that we can endure or deny ourselves of, in this life,
that is too great, so that we may become partakers of it?

I feel a concern for your welfare, which occasions my thus writing;
the other friends have also a share of my love and regard,
whom I consider as a small remnant, having little of the word`'s greatness,
or wisdom to recommend them; yet, as there is a faithful seeking of God, our Saviour,
who is strength in weakness, and riches in poverty,
they will be strengthened and supported: remember, the greater our exercise and trials,
the more weighty will be our reward.

I remain with tenders of unfeigned love, your affectionate friend,

J+++.+++ K.

Colchester, 23rd 1 Mo. 1770.

Dear Friend,

I thought it would not be unpleasing to you, if I expressed, by a few lines,
the sympathy I have with you, in the various trials which are permitted to attend.

Be not discouraged, but trust in the Lord, who is able to help you,
and make up all to your abundant comfort, as you are concerned to walk in his fear;
a remnant, who have experienced his goodness, in a variety of troubles,
have good cause to put their trust in him, and speak well of his name.

I heard of the death of your father and sister: the loss of both, about the same time,
must be very affecting to you; but what Providence sees fitting to permit,
we must endeavour to submit to, with Christian patience.
Though you are thus bereaved of your nearest relations,
and may be ready to think yourself in a lonely situation,
there is room to be thankful for many favours; and to prize, as the greatest blessing,
the visitation of Divine love, which you have been favoured to experience.
Let it be your concern to know an increase of heavenly treasure,
and a further establishment in the Truth,
which will stand you in stead beyond any outward enjoyments of this life.
Having put your hand to the plough, do not look back through discouragement; remember,
it is those who hold out to the end, that will be saved,
and that it is not enough to run well for a time.

I speak thus by way of caution; having found, by experience,
there is need of the same watchfulness and care in
the present time that there was in times past.
This is still the path of safety to us, as we are liable to many changes in this life;
and as no condition, or situation is free from danger,
there is great occasion to ask for heavenly wisdom to direct our steps with safety.
Such as have had the largest experience, in a religious sense,
are the most sensible of their own nothingness,
and need of direction in all their undertakings.
I much desire we may continue steadfast,
in our attention to the things which belong to our peace;
then we shall not be lifted up by prosperity, nor too much cast down by adversity,
but be preserved in the middle path, wherein there is safety.

I am your real friend,

J+++.+++ K.

Colchester, 22nd of 10 Mo. 1770.

Dear Brother,

Though we are so situated, as not to have frequent opportunities of seeing each other,
you are often in my remembrance, with desires for your welfare;
and nothing would give me greater pleasure concerning you,
than to perceive a disposition increasing in your mind,
to enquire after those things which make for your peace,
and tend to promote your comfort and reputation, always.
This disposition, I am sensible, we cannot give to ourselves; but it will be given to us,
as we sincerely seek for it, from the great author of our being,
who is mercifully pleased to regard those who look to him for help;
and does not leave us a prey to that enemy who is continually seeking our hurt.
How many instances are there brought into our view,
of distress and trouble attending such as gratify the evil inclinations of their minds,
and give way to the temptations of this enemy!
On the other hand, what benefit is there,
from our refusing to comply with the incitements, and calls,
which attend us daily and hourly,
to things that we know are contrary to our peace and welfare!

I speak not thus, my dear brother, from hearsay, but from experience.
The rewards of virtue are not uncertain; though at times they may be out of our sight,
they bring substantial good beyond what we can see;
we need only to persevere resolvedly in the practice of what we know to be right,
and the event will afford us unspeakable comfort; this is the fruit of our labour,
which none can deprive us of.
But so strong is our propensity to evil,
that there is occasion to cultivate the good in us, by all the means we can:
we must not be careless, in any matter which is likely to be of advantage to us,
even in a small degree; much less can we with safety neglect the important calls of duty;
such, in particular, as the attendance of religious meetings,
where we have suitable opportunity of serious reflection
upon what concerns our best interests,
as well as to manifest our regard to the Supreme
Power from whom we have received our being.

I much desire you may not neglect your duly in this respect, nor any other;
though the bare attendance of meetings, in a formal way, will not be sufficient;
yet I am well assured, none can neglect them, or be careless in the attendance of them,
and prosper.

These remarks, and cautions deserve your notice;
but after the best advice I might give you,
it is only your putting in practice what is recommended that will be of advantage to you.

I am your affectionate brother,

J+++.+++ K.

Colchester, 1st of 12 Mo. 1770.

Dear Friend,

I doubt not it will be pleasing to you to hear from me,
if but to renew that acquaintance and fellowship
we have been favoured to experience in times past;
the remembrance of which affords me comfort.
A friendship which has its ground in the Truth,
is more excellent than any outward connections, and will afford lasting advantage,
as we keep near to that good hand for direction, which was the moving cause of it:
distance of time or place does not easily impair it,
nor can storms of adversity destroy it.
I can taste the sweetness of it at times, when separated from those whom I love;
and my desire is, to witness an increase of nearness and unity with the Lord`'s servants,
that so I may be strengthened in the service which
may be pointed out to me by Divine goodness,
and encourage others in their service.

Though many things occur, which have a tendency to hinder our progress,
and disqualify for the more full discharge of our duty, let us not be discouraged,
but cast our care upon the Lord,
by whose providence trials and afflictions are permitted to attend;
but he will never leave those who put their trust in him.
We have cause to speak well of his name; he has dealt with us as a tender father,
by his gentle chastisements and corrections, keeping us in the way of safety,
and learning us to endure hardness, as good soldiers:
at the same time he has not left us comfortless in the exercise we have had to endure,
but has been saying, as he did formerly to his disciples,
"`In the world you shall have tribulation, but be of good cheer,
I have overcome the world.`"

I rest your affectionate friend,

J+++.+++ K.
