== Chapter 8

[.signed-section-context-open]
Colchester, 10th 5 Mo. 1793.

[.salutation]
Dear Friend E. T.

Since I read your Epistle to Friends of the county of York,
I have had an inclination to mention to you how much it meets with my approbation,
as it afforded me comfort to observe the salutary advice contained in it;
it tended likewise to strengthen the band of friendship between us,
which a similarity of concern has occasioned:
and l am led to desire that the same disposition
may continue to the end of our pilgrimage here;
that when we have done with the concerns of this present life,
having laboured in the ability received for the good of others,
as humble servants of the great Master, we may be admitted into his presence,
to receive the rewards of obedience, though in the lowest place in his kingdom.

It is true we seldom have opportunity of personal conversation,
and when we meet it is but for a little time, and we part again;
it may be never to see each other again in this transitory state of being.
What a comfort it is to feel our minds stayed on the Lord, our Redeemer,
who has been our support in many afflictions!
Thus the losses we have sustained by removal of our friends, or otherwise,
are made up to us; and we submit to the disposal of his hand,
who directs in unerring wisdom, and deals with us so as to promote our everlasting good,
though we often have to tread in a path which is unpleasant to the natural disposition;
yet if we exercise patience, it will not be without a reward.
There is no virtue we have more need to ask for the continuance of than patience,
as a companion, to go with us through time, and be our crown,
when time here shall be no more.

In the remembrance of former friendship, and a comfortable feeling of true regard,
I subscribe myself your friend and fellow-labourer
in the work and fellowship of the gospel,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 16th 6 Mo. 1793.

[.salutation]
Dear Friend L. S.

I know not how you are at present circumstanced,
with the few religiously disposed in the place of your residence,
but I feel a disposition to speak encouragingly to all who love the Truth in sincerity,
and think nothing too dear to part with for the purchase of it:
to these I desire to be united, as fellow travellers towards a heavenly inheritance;
though separated by large spaces of sea and land, and unknown to each other,
they are united in Christ, and constitute one church, of which he is the head.

[.signed-section-closing]
I am your affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 14th 7 Mo. 1793.

[.salutation]
Dear Friend J. A.

I hardly had opportunity of acknowledging the receipt
of your kind letter when I saw you in London,
at least it did not occur to me; however, where there is true friendship,
omissions of this kind are excused.
Even a long silence will not interrupt the harmony
of minds which have been once united in the Truth;
they look beyond the limits of a few months or years,
nor will any small deficiencies in conduct occasion a decay of love,
which is thus grounded.

The epistle of our much valued friend E. T. which you sent me a copy of,
meets with my approbation in every part of it;
it tends to revive the good esteem I had for her,
as a faithful labourer in the work and service of her great Master.
What a comfort it is to consider that there are some, and I hope many,
in the present time,
who are willing to go on the Lord`'s errand! being devoted to his service,
their greatest joy is to see his work prosper;
and though they have to take many weary steps,
and are often in trouble for the sake of others,
yet their reward is sure as they abide in patience,
being concerned to please him who has called them into his work.
May the number of these be increased in the present low state of the church; that,
through a blessing on their endeavours, the ancient paths may be restored,
and many brought to enquire after the way to Zion, with their faces thitherward!
This is lacking in our society,
as well as among the professors of Christ in other societies.
The profession we make before men, which has been delivered to us from our predecessors,
will do little towards obtaining an inheritance in the kingdom of Christ:
the same power must actuate our minds,
which raised up and qualified the Lord`'s faithful
messengers and servants in former times;
our capacity must come from this; however we may be endued with good natural capacities,
we shall not be fit for the Lord`'s service, nor be as stones in his spiritual building,
unless prepared by the renewed operation and work of his spirit upon our minds.

I am, with tenders of true love and esteem, your affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 10th 8 Mo. 1793.

[.salutation]
Dear Cousin,

Your letter of the 28th 5 Mo. last was very acceptable;
where true friendship remains we shall remember each other,
and be excited to renew tokens of love, in this manner:
but if it should happen that a long time passes without such intelligence,
the band of affection will not be broken, as we walk in the light,
which has been graciously afforded from the Father of light,
and are obedient to its requirings:
in the experience of this my mind has often been comforted,
when deprived of the company and conversation of my beloved friends.

Indeed our necessary avocations often prevent a personal interaction;
and it is well to be contented in such a separation, that we may learn, in retirement,
to renew our acquaintance with the best of friends, even Jesus Christ our Saviour,
and have our dependence on him for substantial comfort.

I am pleased to find you are not unacquainted with
the character and writings of my friend C. Phillips.
I have always retained a great respect for her, on account of her eminent qualifications,
as an instrument in the Lord`'s hand, to promote his cause;
and though much bodily infirmity has of late years attended her,
she is still disposed to appear as an advocate for the truth.

It is also pleasing to hear of the good disposition of your pupil;
I wish he may be kept from losing the savour of religion,
which he has been favoured with,
when exposed to the company of persons immersed in the cares of this life.
It is to be feared this has drawn many from the love
of Christ to the love of this present world,
which is making a sad exchange.
Great watchfulness is required to keep us from this harm.

[.signed-section-closing]
I remain your affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 13th 8 Mo. 1795.

[.salutation]
Esteemed Friend B. F.

I received your letter, with the address to masters and mistresses of parish apprentices.
Your sentiments concerning these poor children are agreeing with mine.
I am of opinion that much depends upon the treatment of children,
not only among the poor,
but people of all ranks and such parents or masters who endeavour,
by example and precept, to train up their children, and those under their care,
in a religious conduct, and in habits of industry, as you recommend,
are doing much towards promoting the good of society.

There are many good institutions,
and much pains has been taken of late to help the youth: let us hope these endeavours,
through the Divine blessing, may have a good effect,
and prove beneficial to succeeding times.
Those who have indulged themselves for a long time in wrong practices,
are not easily restrained; but there is room to hope for better success with the youth,
whose minds are more susceptible of good impressions.
I would readily have us do what we can in a matter of such importance;
if we should sometimes be disappointed in our expectation,
there will be a secret satisfaction, attending as a reward for our labour of love.

[.signed-section-closing]
I remain your sincere friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 16th 9 Mo. 1793.

[.salutation]
Esteemed Friend,

It gives us pleasure to hear of your granddaughter`'s recovery;
it is to be considered as a favour,
when our dear relations are restored to health after great bodily weakness;
and is like a fresh obligation upon us to renew our care,
to be making suitable returns of obedience and faithfulness to our great Lord and Master,
for such mercy, in sparing us and them a little longer,
that we may have an opportunity of further improvement
in those things which belong to our peace;
that when the summons for our removal from this uncertain state shall be sent,
we may be in a prepared state for this great change.

I am often led to desire for myself and friends,
that nothing might attract our love while we are passing through time,
so as to make us forget the better inheritance prepared
for us hereafter in those heavenly mansions,
where we may meet with our friends,
without that mixture of joy and sorrow which is experienced in earthly enjoyments.

I trust it will not be unpleasant to you to meet with such remarks:
there is a comfort in speaking of that which is of so great importance,
as well as in hearing it spoke of under a right concern.
When the love of God prevails in our minds,
we shall seek to promote the happiness and comfort one of another;
and that it may more and more increase in our minds,
is the desire of your affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 7th 12 Mo. 1793.

[.salutation]
Dear Friend P. S.

I have frequently thought of you since I was at your father`'s house;
there seems a danger of your being offended at his not complying with your request,
which will be unsafe for you, and quite improper,
considering the obligations you are under to him, not only as a parent,
who has brought you up and given you education, but as a friend,
who is willing to assist you in all your concerns as far as he is able.

There is need of much caution in our proceedings in business,
lest we should undertake too much, and meet with unexpected difficulties.
My advice is,
to avoid coming under engagements which there is
room to fear you will not be able to fulfill;
and to keep your business in as little compass as possible.
It has long been my judgment, that a little business, well managed,
is preferable to great concerns which neither a man`'s
capacity nor property are equal to.
I have observed several of my friends to be hurt by too much business; while others,
in a less way, have gone on with comfort and good reputation:
thus I would have it be with you, rather little in the beginning and great in the end,
than great in the beginning and small in the end; I mean as to outward circumstances.

It will give me pleasure to hear of your good success, and reputable conduct,
as a member of society; but there is need of caution in many respects,
particularly as to your acquaintance.
It will not be safe for you to join with persons, to whose company you may be exposed,
on account of business, in their behaviour and conduct; but you must often be singular,
especially as to excess in drinking, and other intemperance.
As to the diversion of hunting, which I hear you have practised,
I would advise you to decline it, as being attended with danger, and may prove hurtful,
if not through the neglect of business, yet by producing an acquaintance,
which is wholly improper for a religious young man.

I write thus from a desire that you may be preserved from
the harms to which young men are liable in the present time:
the hurts which many have received should be as warnings
to us who have the same temptations to contend with,
and shall fall by them in the same manner if we are
not preserved by a power superior to our own.
Let us remember, that as we need help we must be concerned to ask for it,
and be watchful against the appearance of evil,
often in the exercise of contradicting our inclinations;
our good depends upon self-denial, beyond what we can easily apprehend,
even in things which appear but small.

I am your truly affectionate and well-wishing friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 1st of 1 Mo. 1794.

[.salutation]
Dear Cousin,

Though I have not informed you of my receiving your kind letter of the 9th mo.
last, it has not been laid by unnoticed;
I am not apt to forgot the favours of my friends in this way,
especially if they come from those to whom I am united in the Truth,
as well as by outward relationship.
It is a comfort to us, when separated from each other, and no outward tokens appear,
that our love remains undiminished,
having its support in that which neither distance of time nor space can remove.
Thus I have found it with regard to several of my friends,
whom I often think of with much affection,
and whose company and conversation would be acceptable, if circumstances admitted;
but I find it best to be contented in the lack of this, and other things,
which may appear to me as desirable helps, in the exercise and concern attending,
both on my own account and for the sake of others:
but as former trials have been profitable, so will the present, if rightly improved,
however unpleasant, and tending to disappoint us in our views and expectations.
Our gracious Redeemer, who has begun the work of reformation in our minds,
will carry it on to his praise, and our everlasting good,
as we are concerned to serve him in simplicity and fear,
preferring his favour and friendship beyond the most desirable comforts of this life.

We have to expect our passage through life will be attended with sorrows,
as well as comforts; the cup we have to drink of is full of mixture;
through much tribulation, it is said, the righteous enter the kingdom:
but our troubles are not to destroy nor to hurt us, but are intended for our refinement,
which cannot be effected otherwise.

I write thus to my much valued cousin,
with a view to encourage her in the exercising path she has to tread in,
not to frighten her with approaching difficulties.
I would have her take courage in the name of the Lord, and cast her care upon him,
who cares for his depending children,
and is more propitious to their peace than they can easily apprehend.
We were affected to hear of our friend Job Scott`'s decease:
it may be considered as a loss to his family and the church; yet, in the midst of sorrow,
there is comfort,
when we have to believe that those who are thus taken
from us in the midst of their labours,
are in the enjoyment of uninterrupted rest and peace,
beyond all the exercises and conflicts of time.

With tenders of dear love to you and your husband, in which my wife joins,
I remain your affectionate cousin,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 4th 1 Mo. 1794

[.salutation]
Dear Friend J. P. of Philadelphia.

You have been frequently in my remembrance since we heard of the awful visitation,
by sickness in your city;^
footnote:[By which it is said 3000 died in a short time.]
some information concerning it will be acceptable to me.
I make no doubt you have been informed of the death of our much valued friend, Job Scott,
being upon his journey in Ireland:
thus we have a fresh instance of the uncertainty of our days,
and how liable we are to be prevented from performing what we may have in view,
even though it should be from the best motives,
and in devotedness of heart to the Lord`'s service.
He is pleased to cut short the work, and, in unsearchable wisdom, to dispose of us,
according to his good pleasure!

I expect it may be with you, as it is with us, a time of affliction.
Though we are favoured, as a society, with liberty,
and have not the restraints which were known in former times by our predecessors,
we have our trials from the snares of a delusive world;
as also from the insensibility and lukewarmness of many,
who are making the same profession with us,
and at the same time know but little of religion more than what they have by tradition.

It gives us concern to hear of the troubles which
at present attend in some neighbouring countries;
though we can take no share in the contests,
the love we feel in our hearts to all mankind, makes us grieved at their calamities;
and we pray for the return of peace,
that people might come to be engaged in war of a
different nature from that of destroying each other,
which is, with their lusts and evil inclinations.
Thus the kingdom of the wicked one would be weakened, and the kingdom of Christ exalted,
which is the happiness of nations and families!

[.signed-section-closing]
I remain your affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 9th 1 Mo. 1794;

[.salutation]
Dear Friend,

I have frequently thought of your proposal to decline the station of an elder,
(to which you are appointed) on account of some obstructions from your outward affairs,
and other difficulties.

I allow there are many discouragements met with by those who are in this station; and,
if they are not well concluded to persevere in endeavouring
to do what their office requires of them,
the cause will suffer, and the good work, which has been begun,
will not go on to the praise of him who has called them, and their own peace.
Those who have put their hand to the plough, had need to look upon the work as but begun.
And when the good we have to partake of from our obedience and faithfulness,
is beginning to appear, shall we then give up the contest,
because of difficulties that are met with?
I desire it may not be so with any of my dear friends;
but that we may look forward towards fulfilling our charge, in the time allotted us,
and may have to give up our account with joy.

Let me say,
this is not a time for those who have listed under Christ`'s banner to draw back,
lest the enemy of all good should gain an advantage and the peace of the church be destroyed.

I write thus to my esteemed friend, from a motive of true love and desire of his welfare,
that nothing might be allowed to interfere, which is of hurtful tendency.
I would have him not look at his own weakness, and unfitness for the service,
but look to the Lord for help, who can fit us for his service,
and without whose renewed assistance, none can rightly engage in his work.

I am, with true regard, your affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 14th 1 Mo. 1794.

[.salutation]
Dear Friend J. G.

Since I heard of the death of your sister,
you have had a large share of sympathy in my mind,
so as to make me wish to say something which might comfort you in your loss;
though the same considerations, and better, may have occurred to you on the occasion,
besides the help of your friends: yet I hope,
what is here added may help to reconcile this afflicting dispensation to you,
and strengthen a concern in your mind to be resigned
to the disposal of an all-wise Providence,
without whose permission nothing happens to us.
Whether he is pleased to lengthen our days,
or remove us from this state of probation at an early period, and in the prime of life;
we have occasion to praise him for his goodness, and to say,
in the loss of our dear relations, with one formerly, "`The Lord gave,
and the Lord has taken away, blessed be the name of the Lord.`"

The good I wish to my dear friend, with his offspring and family, is,
that they may choose the path of virtue, in which durable comforts are known; and peace,
which the world cannot give, nor take from them!
That their religion may be of that sort which influences the conduct to whatever is good,
and praiseworthy; that, as they increase in years, they may grow in grace,
and in the knowledge of the Truth, as it is in Jesus Christ,
and thus may succeed their worthy predecessors, as ornaments of the society,
and a blessing to the church in its low state.

I am also led to desire for your brothers,
and those who are most nearly concerned in the losses sustained,
that what they have known of the uncertainty of earthly comforts,
may tend to increase their concern to seek after a further interest
in that good which no changes of this life can deprive them of.
We should learn by the things we suffer, to be more humble, more circumspect,
more patient, more disengaged in our minds, as to a dependence on the things of time;
which pass away as a dream, and are soon forgotten.

Trouble is our portion, from youth to age: yet, as the good man says,
"`Affliction comes not forth of the dust, nor does trouble spring out of the ground!`"
All we meet with is by the permission of an over-ruling Providence.
And it is a comfort to consider, in our losses, that we mourn not as those without hope:
by the wounds we receive we are not destroyed, but healed, if they have a proper effect.

Having said thus much with a view to alleviate your grief, I subscribe myself,
your sincere friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 22nd 8 Mo. 1794.

[.salutation]
Dear Friend L. M.

The love and esteem which has been raised in our minds towards each other,
I consider as a sufficient motive to my writing you a few lines,
after returning from our late journey.
It is no small comfort to meet with those with whom we can join in a spiritual fellowship;
and though we may come short, as to some qualifications mentioned by the apostle,
I hope it may be said that we are of those who love the Truth, and such who walk in it;
and that it is our desire to be joined with them, as fellow travellers.

When minds are disposed the same way, and aiming at the same everlasting good,
it does not require much time to form an acquaintance.
When they meet, though there should be but few words spoken, there will be that felt,
in a communion of spirit, through the influence of Divine Truth,
which will more firmly unite than eloquent speech.
This, I trust, we measurably experienced in our visit to you and your dear wife,
to our mutual comfort! so that if we should not soon meet again,
it may be sufficient to remember we once met in that love,
which no time or space can deprive us of,
which will remain and increase as we walk in humility and fear before the Lord.
I am joined by my wife in tenders of kind love to you and yours,
from your affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 9th 11 Mo. 1794.

[.salutation]
Dear Friend J. P.

At the time of our last quarterly meeting,
I was informed of your being in Holland or Germany, and shown a letter or two from you:
since that,
I have felt an inclination to write you a few lines upon the bottom of true friendship;
and not without near sympathy with you in your present engagement.

I doubt not your company is very acceptable in the place where your lot is cast;
and though you have to experience many difficulties and discouragements,
both inward and outward, there is this to comfort,
that the work is not taken up in your own will or to procure any outward advantages,
but from an apprehension of duty, according to your measure,
to promote the cause of Truth in the earth, and enlargement of the kingdom of Christ,
in the hearts of men and women.

I join in wishing the work may be prospered in your hands, to the good of many,
and that the Lord may prosper you in it.
It is further my desire for the little society which you are concerned to visit,
that they may not only know the Truth, but may be established in it,
to their everlasting comfort,
and the praise of him who has favoured with a degree
of light beyond many of their fellow creatures;
and which will be increased,
as they abide faithful under the leadings of this good guide,
who does not commonly to put us in possession of what he has prepared for us suddenly,
but to lead us on by degrees, till we finally enter into the promised land.

My apprehension concerning the country which you are concerned to visit, is,
that there are many religiously disposed people among the
different professions in the low countries and Germany,
of whom it may be said, they are waiting for the consolation of Israel,
and need to have their minds turned to the good principle in them;
that when outward help fails,
the Lord Jesus may be their teacher and instructor in the way of peace and holiness:
these are often hid from the view of men,
mourning in secret for lack of the more full appearance of the beloved of their souls.

In that love, which induced me to tend you this brotherly salutation,
I remain your sincere friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 16th 12 Mo. 1794.

[.salutation]
Dear Friend J. V--f.

I received your letter of the 4th 11 mo.
which was acceptable to me,
on account of the information it gave of our valued friend John Pemberton;
since that I have heard nothing concerning him, but hope he is recovered of his illness.

As you mention nothing to the contrary,
I expect things are in the same state as to the meeting in Amsterdam.
The exercise of faith and patience, and a good resolution,
is required to continue steadfast in the support of our testimony;
which is so different from the way and manner of other professors,
as to religious worship: however, I would not have us discouraged; but count it a favour,
that we are convinced of the necessity of inward devotion,
and a spiritual worship beyond forms and ceremonies,
in order to find acceptance with the Lord our God, who sees not as men sees,
but looks at the heart.
It is best for us to keep steadfast in the way, though in the cross to our inclinations;
and if we happily experience an establishment in the way of Truth and holiness,
through the divine blessing on our endeavours, it will, in the end,
make amends for the pains we may take.
It remains true, that such who wait upon the Lord shall renew their strength.
It may comfort us to consider that we are not less
under the notice of the great helper of his people,
because our number is small,
and there is but little show or splendour to recommend
us to the notice and esteem of men.
When we decline the use of those rites and ceremonies which
many think necessary in the religion of our great Lord,
may we show by our lives and conversations that we
are not strangers to that inward and spiritual grace,
in which true religion consists.

I conclude with saying that your letters are always acceptable to me, and the more so,
as I have hardly any other correspondent in the parts where you reside.

[.signed-section-closing]
I am your sincere friend,

[.signed-section-signature]
J+++.+++ K.

[.salutation]
Dear Cousin,

Our thus writing to each other helps to make up the lack of personal conversation.
When strength of body does not admit of visiting my friends who are at a distance,
I consider it as a favour that I can communicate my thoughts to them by writing.

In my retirement I have to think of the good opportunities we have had together,
and when it is not in my power to help them otherwise, I feel desires for their welfare,
that if we should not be favoured to meet again in this transitory life,
we may meet in a more quiet habitation,
where all the Christian travellers who have been before, and may follow after,
may find rest.
But, this we must wait for, in the exercise of patience,
and a humble submission to the dispensations of Providence;
still using our endeavour to fill up the measure of labour allotted us,
till our great Master shall say, It is enough.
In the remembrance of past favours,
and belief that he will not forsake us in succeeding exercise,
let us take courage and trust in the Lord for help.

[.signed-section-closing]
I am your affectionate cousin,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 7th 1st Mo. 1795.

[.salutation]
Respected Friend,

Since being at your house, I have frequently thought of you and your family.
It was pleasing to have the opportunity of sitting
with some who are well disposed towards the society,
though not members of it;
and I wish they may be encouraged to persevere in the way which they see to be right;
not forming conclusions from what they see in the conduct of others.
We should remember that our peace and happiness depends upon a faithful
endeavour to practice what we are convinced of as the Truth,
however different the way may be, in which we have to walk,
from that of our neighbours and acquaintance.
We must keep steadfast in obedience to the good principle in our minds,
which is as a ray of light, small in its first appearance,
but as attended to and followed, increasing in brightness,
till we are able to see things in a clearer manner, as at noon-day.
This is the good man`'s experience, whose way is as a shining light,
which shines more and more unto the perfect day.

I wish this may be the experience of all those who, through the Lord`'s mercy,
have had their feet turned into the way of life and salvation.
If they have put their hand to the plough, let them not look back,
but use good resolution, through Divine assistance,
not to be hindered from discharging their duty,
according to the requirings of Truth in the secret of their minds,
which will be productive of peace that exceeds all earthly enjoyments.

I say this for the encouragement of any poor mind
which may be awakened to a sense of its state,
and the necessity of making the best use of time, to prepare for a happy eternity.
And now I have to mention to you, in much affection, and from a desire of your good,
that in the time which we spent at your house,
(which was on the First day of the week) I observed with concern,
you were in the practice of having the door of your shop open from morning to evening,
to serve customers with goods,
without paying a proper regard to the obligations
of piety to set apart the day to religious purposes;
not only for your own advantage and the advantage of your family,
but as a good example to your neighbours,
who may be too apt to give the preference to earthly gain;
neglecting the improvement of their minds, which is the most essential employ.
I would have you disposed to alter this custom,
and no longer conform to what is so unsuitable.

I sympathise with you in the difficulty attending,
from the lack of help by a religious conduct in your family;
but I would have you renew your endeavours to do right,
and who knows what good effect your conduct may have on your wife and children,
to their everlasting good?

I remain your sincere friend,

[.signed-section-signature]
J+++.+++ K.

[.letter-heading]
Letter to the Prince of Orange.

Upon the late Revolution in Holland, the Prince of Orange, with his wife and children,
found it necessary to leave their house at the Hague, and come to England;
where they were hospitably received.
In their way to London they passed through Colchester,
and were at an inn in the town some days;
during which time I took the liberty to make them a visit,
and had some conversation with the Prince and his son, on religious subjects;
I also presented them with some books in French and Dutch.
But not being quite satisfied with this opportunity, I wrote a few lines to the Prince,
expressing my regard to him and his family, as follows:

[.embedded-content-document.letter]
--

The respect and sympathy I felt in my mind towards the Prince of Orange and his family,
induced me to make them a visit;
and now the same love and good will inclines me to write
a few lines for their notice in this time of affliction.

I have to consider their safe arrival in this country as a favour of Providence,
after passing through the dangers of the sea,
and difficulties met with from the present inclement season.
My good wishes attend them, and prayers to the Almighty,
that he would continue his protection from harms of every kind;
and that the troubles which they have met with,
or may meet with in the future part of their lives,
may be so sanctified as to prove of lasting advantage to their minds,
by drawing them from all unsuitable dependence upon the comforts of this present life,
which are at best uncertain and transitory,
and can only accommodate us for a little time, and then come to an end,
and be as though they had never been;
but the joy and consolation which comes from a life of piety
and virtue in submission to the will of God,
is never failing; nor can any of our fellow mortals take it from us.
When they are disposed to trouble us,
we shall have that to flee to which is beyond the reach of their malice.

This I desire may be the experience of the illustrious strangers,
who have found this country as a place of refuge in the storm, which,
by the permission of Providence has arose in their native land;
to what height it may come we know not, but this we are assured of,
that all these events are under the control of an
Almighty Power which rules in heaven and on earth.

Wherever we reside, or whatever happens to us, in adversity or prosperity,
we are still under his notice.
He regards those who fear him, and work righteousness,
and will give them a crown of glory which fades not away,
when they are removed from the fluctuating scenes of this life.

Having used this freedom in writing to my esteemed friends,
I am inclined to address their beloved offspring,
to whom I wish happiness and prosperity, and above all,
that they may be preserved from the evils of a libertine age.
I wish that may accompany them,
which is the best preservative against the enticements and snares of youth;
by which they will obtain respect,
and become honourable in their station--and this is the fear of God;
which is truly said to be a fountain of life, to preserve from the snares of death.
As it takes place in their minds, it will make them a comfort to their parents,
and they will gain the favour of good men, and of him whose blessing makes truly rich,
and adds no sorrow with it.

I am sensible there are dangers in every condition of life;
but those in eminent stations are most especially
liable to be hurt by the flattery of some,
and bad example of others, whom they may be willing to please.

In conclusion I have to request the Prince will accept
this small token of love and esteem,
expressed in much plainness, from one who wishes the welfare of him and his family,
and subscribes himself their affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-close]
Colchester, 22nd 1 Mo. 1795.

--
