== Chapter 10

[.signed-section-context-open]
Colchester, 30th 7 Mo. 1799.

[.salutation]
Dear Friend,

I consider it as a favour that I am seldom hindered
from the attendance of meetings at home,
and sometimes can take a journey to visit my friends abroad, to our mutual comfort.
I was at the Yearly Meeting in London, and attended most of the sittings.
My health is continued as usual,
but there is room to expect bodily infirmities and weakness will attend,
at the age of seventy-three, to which I am now arrived;
exceeding the age of many of my relations and friends,
whose days closed at a much earlier period.
I am now surviving among; a few of my acquaintance, most of whom are of the younger sort,
upon whom the concerns of the society will devolve,
when those who have laboured in the good cause, from youth to age,
are gathered to their rest!
These have had no occasion to say, they served a hard master.
It is to be desired that their example may encourage
others to choose the same way to walk in,
which has been productive of many advantages,
beyond all the riches and greatness of this transitory world.

We have lived to see great alterations in the society of which we are members,
by a declension, as to number, in many places where friends formerly resided: and,
in some places, those who remain have little more than the form,
without the power of religion, by which the form can be rightly supported.
Yet it may be said there is a revival of concern in many minds;
and truth is precious to these,
producing the same good effects as in the times of our forefathers.
These are the testimony-bearers of the present time,
by whom the propriety of our profession can be shown to advantage.
Let us pray for an increase of such,
and especially that the Divine visitation may be extended to the youth among us,
for the benefit of this and the next generation.

[.signed-section-closing]
I remain your sincere friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 22nd 11 Mo. 1799.

[.salutation]
Dear Friend,

I expect you are frequently called upon to be assisting to your friends and neighbours,
both in a private and public capacity: and there is a pleasure in being useful,
which makes amends for the pains taken, without any other reward.
When we do any little office of love, we only wish to be able to do more,
and that our endeavours were more successful.
We shall not however be discouraged by the little appearance of success,
nor by ungrateful returns we have to meet with,
as that love which has been the moving cause of our conduct still prevails.

[.signed-section-closing]
I rest your affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 24th 12 Mo. 1799.

[.salutation]
Esteemed Friend A. F.

It may afford you some pleasure to receive this small token of love from an old acquaintance,
whose experience has been much like yours in this respect,
that we have sustained many losses by the removal of our friends,
whose company might have been a comfort and stay to us in our declining days.
But let us put our trust in that Almighty power,
which has been our support from the early part of life to the present time,
and will not leave destitute of his favour, when we are not able to bear an active part,
with our brethren, in the promotion of truth, at least to such a degree as we may wish,
through bodily weakness.
It may however be a comfort to look back on the former part of life,
with a humble hope that we have been attentive to our duty,
and willing to join with those who were engaged in the service of our great Master,
and to afford them help according to our ability:
and though we have done nothing in this respect, nor in any other,
which may be said to merit a reward,
yet we shall not be without a recompense from our gracious Redeemer,
who made us willing to consecrate our early days to his service,
in obedience to his call.
And now, having arrived at an age beyond many of our relations and friends,
we have cause to commemorate the Lord`'s goodness in thus sparing us,
till we may be more fitted for our great change.

Though we must expect to partake of the cup which is full of mixture,
yet all our troubles will become profitable, as we call upon him for help,
by whose permission they come.

Having thus enlarged my writing beyond what was expected,
I shall conclude with tenders of kind love from your sincere friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 8th 1st Mo. 1800.

[.salutation]
Dear Friend,

My mind is filled with sympathy in considering your present sad condition;
occasioned by admitting unreasonable fears and jealousies into your mind,
concerning your friends; not one of whom is unkindly disposed towards you;
but on the contrary, wishing your welfare in all respects.
My writing to you is not with a view to enter into
the circumstances which have occasioned your troubles,
but to say something which might be like a healing medicine, to alleviate your grief,
and help to bring nearer to him who is the healer of breaches,
and restorer of paths to dwell in: the good Samaritan,
who regards those who have fallen into the hands of robbers,
and are left wounded by the wayside, as is your present state, if I am not mistaken.

I would have you remember, that this help comes to us in different ways,
though from the same merciful Saviour.
Sometimes by means of friends, who see our danger,
and are concerned to help us from motives of true love,
without any private views of advantage; also by intimations in our minds,
that we are not in a good way, which should be regarded.

Who, that is sensible of his own frailty,
can but sympathize with those who have thus been hurt,
for lack of close attention to their duty; and having the armour of faith,
which is the only security in times of trial.
But it is often found true, that we are blind to the dangers attending us,
which another can clearly see; we should therefore have humble thoughts of ourselves,
and always fear, lest some cross occurrences should turn us out of the way,
into which it may be difficult, if not impossible, (humanly speaking) to return.

I have seen many of my friends hurt by that which was intended for their good,
and would have been profitable to them, if it had been made a right use of,
by keeping in that love which the apostle speaks of, that bears all things,
and hopes all things, and is not offended.

This I compare to turning water into wine.
I wish for you and for myself,
that we may be more and more instructed in this heavenly art,
and may receive the benefits of it, and being enriched by it ourselves,
we may impart it to others, not so much by words and expressions which might be used,
as by our patient, peaceable, and gentle demeanour;
always cautious of complaining of grievances, which unavoidably attend us,
or of being offended with what we meet with from others.
We shall be mistaken, if we expect to pass through life free from exercises and troubles,
but the good, or hurt which comes from them,
depends upon the manner in which they are received.
If they are borne with Christian patience and resignation,
good comes from them to us and our friends;
especially those to whom we are nearly allied by outward relationship;
but if we are uneasy and discontented under them, they will tend to hurt us; and,
the hurt we receive will reach to others.
When we are complaining of our difficulties,
we should fear lest we complain of the dispensations of Providence,
which permit trouble to come upon us.

Having thus expressed my concern for your welfare,
and given you some cautions which my own experience suggested,
and which I desire may be helpful to you,
towards removing the uneasiness which has taken place in your mind, I shall only add,
that my writing is not occasioned so much from what I have heard of the circumstance,
as from my apprehension of your state,
and the hurt which may come to your wife and children,
from your giving way to that which has a tendency to weaken your love to Friends.
I have seen that where the head of the family has failed in example,
whether it was in husband or wife,
the hurt has reached almost to the smallest branches of it:
therefore how careful had they need to be, who are in these important stations,
in every part of their conduct;
seeking for help from the Almighty to walk in the path of holiness and self-denial.
That this may be your happy experience in the future part of life,
as well for your own advantage,
as that you might be an instrument of good to your family,
is the desire of your affectionate friend,
who is interested in your welfare and restoration,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 5th 4 Mo. 1800.

[.salutation]
Dear Nephew,

I have often thought that the faith and practice of true Christians,
as to the essentials of religion,
are more alike than they are aware of which makes me afraid of censuring some,
who may have a different apprehension of things.
It is good for us not to be confident of our opinions,
but still to have low thoughts of ourselves, and consider, if we have any good qualities,
they are obtained through Divine grace; nor are we to claim any merit from them,
but ascribe all to him who died for us, to save from the wrath due to our sins;
who also gives, to those who ask in faith, the influence of his Spirit,
to help them to overcome the evil propensities of nature,
and suggestions of the wicked one, with which we are assaulted from time to time,
so as to be ready to say with the apostle, "`O wretched man that I am,
who shall deliver me from the body of this death?`"
To which it may be answered, Nothing short of God`'s grace can help and deliver us,
which is in, and through, the mediation of his beloved Son Jesus Christ.

At the same time we should remember that nothing which our great Lord has done,
or suffered for us, will take away the obligation there is upon us,
to use our endeavours, through his assistance, to devote ourselves,
by lives of piety and holiness, to his service.

To say we are continually offending God by our sins, would be sad indeed,
and derogatory to the grace and Spirit of Christ, which is a Christian`'s strength;
and so far as he is influenced and assisted by it,
no temptations of the enemy will be able to prevail against him.
It is the declaration of the apostle,
that there is "`no condemnation to them that are in Christ Jesus,
who walk not after the flesh, but after the Spirit.
For the law of the Spirit of life in Christ Jesus,
has made me free from the law of sin and death.`"

It is a great truth, that as in Adam all die, even so in Christ all are made alive.
If we were not fallen from a state of innocency, there would be no need of a Saviour;
yet in our fallen state, it has pleased the Almighty to take notice of us,
and give us help and comfort, in believing that,
through the merits and intercession of his Son, we have remission of sin: so that,
as the apostle says, the hand writing against us is blotted out,
and notwithstanding our unworthiness, we are received into his favour,
on condition that we show by our obedience, we are disposed to accept of so great mercy.

Thus I am led to express my thoughts on these important subjects,
with no view of objecting to what is said in your letter;
but rather from an apprehension that we agree in all things essential to our happiness;
and,
that it will be the great concern of our minds to experience
a further acquaintance with the benefits of religion.
This I also desire for my beloved niece,
and that you may be united in that bond of true love,
which no cross occurrences of this life, or temporal losses are able to dissolve.

I remain your affectionate relation and friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 3rd 5 Mo. 1800.

[.salutation]
Dear friend R. R--ds,

The correspondence between us has been so pleasant,
that I am unwilling anything should obstruct it but lack of health or ability.
At the same time, there is occasion to desire we may be helped to use this comfort,
with all other outward blessings, which we are in the enjoyment of,
with minds submissive to the dispensations of Providence.

Your information concerning some of our dear friends is very acceptable.
When we are not able to visit them, it affords pleasure to hear of their welfare.
At times we have to anticipate the comfort which
their bodily presence and conversation might give,
if favoured to meet in this transitory state.
This has been my experience with regard to many of my friends, to whom:
I am nearly united, if not by outward relationship,
yet in that love which prevails in those whom a harmony of spirit
and likeness of concern has brought into the same way.
So that we can salute each other as fellow travellers towards a city of rest,
into which such troubles as we meet with here cannot enter;
in which happy place we hope to meet with many of our relations and friends,
and to join the innumerable company of the blessed,
who are gone before us of all generations.
This is beyond human comprehension, yet certain to us, by an eye of faith,
as we continue faithful, and hold fast our integrity to the end.

I am your sincere friend, nearly united in the Truth,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 18th 8 Mo. 1800.

[.salutation]
Dear Friend T. B.

Though some months are passed since the receipt of your letter,
it has not been laid by unnoticed.
The regard and esteem which is continued in my mind towards you and your dear wife,
inclines me to send this fresh salutation of love.
As the number of my old acquaintance is brought into a narrow compass,
I feel myself more nearly united to those who remain;
so that not only their company is pleasant,
but the remembrance of them often affords comfort,
under the many difficulties and discouragements attending:
and though I am ready to think no one more stands in need of help than myself,
instead of attempting to help others,
yet I cannot easily forbear to drop a word of comfort to my friends,
in whose welfare I am concerned.
Thus I am inclined to say to myself, and to them, "`Let us take courage;
not doubting of the Lord`'s goodness towards us, who has been our support in times past;
and sanctified our affliction in such a manner,
as that we have gained experience from it:
and some Christian virtues have been increased in us, such as patience, resignation,
contentedness, and humility: with a desire to be more weaned from the love of this world,
and more prepared for the enjoyment of an inheritance in the heavenly kingdom,
whenever it shall please the Lord to remove us from the exercises and troubles of time.`"
With tenders of kind love, I remain your affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 10th 2 Mo. 1801.

[.salutation]
Dear Friend J. B.

In the love and friendship which subsists between us,
as also from the similarity of our concern and exercise, I am inclined to mention to you,
that it afforded me pleasure to hear of your being
engaged in visiting the meetings of friends in London,
and parts adjacent.
I have good hope it will prove to your own peace,
as also to the benefit of those whom you may be concerned to visit.
I consider it as a favour from our great and good Master,
that he should thus engage our minds; and give us strength in the declining part of life,
to appear among those who are concerned to advocate his cause, which remains to be,
as it always has been, the best of causes, and his service the best of services:
even the lowest office in his church, and among his people,
is better than to have a place among the greatest of those,
who dwell in the palaces of wickedness.

These are times in which we have not room to expect an exemption from trouble;
if we are favoured to get on our journey heavenward with safety,
it will be the greatest blessing we have to ask:
the present state of the church is such as calls for mourning,
which the living members are sensible of; and ready to say to those who call for joy,
in a land of captivity, "`How can we sing the Lord`'s song in a strange land?`"

Let us, however, exercise patience, and deliverance will come in the Lord`'s time: and,
we shall see,
that the affliction we meet with is not more than is necessary for our good:
we need much refinement; and,
it is not once being in the furnace will make us fit for our great master`'s use;
we must submit to further cleansing, till our will is subjected to the Lord`'s will;
and all is removed which has a tendency to hinder our more perfect obedience.

May the same heavenly guide be with us to direct our steps,
which has been our support and direction in time past;
that as the evening of our day approaches, we may know him, who was our morning light,
to be our evening song.

With desires for your good success and prosperity, through the Lord`'s blessing,
in this and all your undertakings, I remain your sincere friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 2nd 9 Mo. 1801.

[.salutation]
Dear Friend William Pluym of Haarlem.

I am not easy to suppress an inclination which has attended my mind for some time past,
to write you a few lines, upon a token of friendship which has long subsisted between us.

It has pleased the Divine goodness to lengthen my days, as also those of my dear wife,
beyond what we have had room to expect;
considering the many bodily ailments to which we are liable,
in common with our fellow sojourners in this vale of tears.
If what I write should come to your hands, and you are able to make reply,
it will give me pleasure to be informed of your, and your wife`'s welfare,
as also concerning your sisters.

The favourable opinion I have always had of the inhabitants
of the country where you reside,
makes it pleasant to hear of their prosperity, especially in a religious sense.

Though there are none of our society remaining among you,
to support the testimonies we have to bear, yet I trust there are many who fear God,
and place their hope of salvation in Jesus Christ, our Lord and Saviour.
This I consider as a fundamental principle of our religion;
with these I desire to be united, let their name,
as to religious profession be what it may.
If we love God, we shall love one another:
it is true that the strife of nations has a tendency to
obstruct the interaction which we may be desirous of;
but it cannot break the bond in which we are united,
by means of that inward principle of light and truth, which has taken place in our minds.

Thus, when far separated from each other by sea and land,
we become members of Christ`'s church militant on earth,
and shall help to constitute that assembly in heaven, which John speaks of,
that no man could number, of all nations, kindreds, and people, and tongues.
Let us comfort our minds with a hope of partaking of this good,
when time to us here shall be no more.

I trust some information concerning our society, in this nation,
will be acceptable to you; in some places our number is lessened,
yet in others there is an increase, as to number,
and a revival of religious concern in the minds of many;
so that our meetings are better attended, and good order preserved.
It must however be acknowledged, that we have those among us,
who are little better than bare nominal Christians;
unacquainted with the work of grace in their hearts,
to change them from a state of nature into the heavenly image.

I am informed the meeting of Friends at Pyrmont is increased.
A friend from America lately passed through Colchester, in his way to that country;
he had a view of extending his journey into the southern parts of France, where, we hear,
there is a little society of such who adhere to our principles.
Several of our friends who were in Holland a few years ago, are deceased:
such as I. Sharpless, Samuel Emlen, William Fry, Samuel Neal, Sarah Grub,
and her husband.

We have had many friends from America upon religious visits to this nation,
who are returned home.
I remain your sincere friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 21st 6 Mo. 1801.

[.salutation]
Dear Friend,

I conclude you are not without a share; of affliction, with others,
who have been persuaded to enter into the same service and warfare,
as good soldiers of Jesus Christ: though we are free from outward molestation,
yet our stations in the church subject us to much labour and exercise,
while we have the care of others upon us.
If our present condition is in the ordering of Divine wisdom,
and we are endeavouring to devote our time and talents to the service of our great Lord,
there will be no room for complaint; he is a rich rewarder of them that serve him.

I wish to have these lines received, as a token of love and esteem,
from your affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 27th 11 Mo. 1801.

[.salutation]
Dear Friend,

The treatment you have lately met with from the riotous people,
on account of your not complying with the custom of illuminating your house,
at the time of public rejoicing,
brings to my remembrance what we have repeatedly experienced on the like occasion:
though it is very unpleasant and alarming, to have our houses thus beset and damaged,
we have no cause to be dissatisfied with our conduct,
when we refuse to comply with this practice.

If we disapprove of the vain customs of the times,
and consider ourselves as raised up to bear testimony to the Truth,
and to be examples of moderation and temperance to our neighbours,
let us be cautious not to countenance them in their proceedings,
but rather suffer their displeasure,
than hurt our consciences by joining with what we disapprove.

It grieves me to hear of the sufferings of my friends,
yet it affords comfort to find there are those,
who will rather submit to loss of their property,
than give up the testimony they have to bear, whether in smaller or greater matters.
And, when we agree in our practice, it tends to bring us near to each other,
and confirms us in the hope that our religious scruples are upon a good bottom.

I thought a few lines might be acceptable to you on the occasion,
if but to express the friendship between us, from a similarity of our exercise.

I remain with tenders of kind love, your sincere friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 29th 11 Mo. 1801.

[.salutation]
Dear Friend,

Not seeing you, as I had expected, before my return to Colchester,
I am inclined to mention in this way, that since the conversation we had together,
you have been frequently in my remembrance; and though I took the liberty, at that time,
to drop some hints to you in regard to your conduct,
there seems to be something further in my mind to add, by way of caution,
in your present situation; which, as I apprehend, is dangerous,
not only from being exposed to the company and conduct
of those who are disposed for liberty,
such as religious young men cannot take with safety,
but from the sprightliness of your natural disposition,
which may lead you to a compliance with customs and ways of behaviour,
inconsistent with your safety, and the peace of your mind;
besides introducing an acquaintance which may be injurious to you.

There is no safety for us, whether young or old, in the perilous journey of this life,
but while we are watching against the assaults of powerful enemies, such as the world,
our natural inclinations, and Satan; these are going with us wherever we go,
endeavouring to get a place in our minds,
to the overthrow of the kingdom of righteousness and peace,
which God would establish in us, us we adhere to his law.
It would be difficult to tell the harms which come from relaxing the discipline,
which we are called upon to maintain against these enemies of our peace.

We should remember, that great harms often have but small beginnings; and,
that one liberty, from under the cross, leads to another liberty, greater than the first,
(which by reasoning we may make out to be small,) and thus,
many have lost their tenderness and fear;
which through the Divine blessing would have been their preservation.
I hope better things of you, and that the harms of others will be as warnings to you:
prevention is better than cure; yet if you have suffered loss,
by improper indulgence of any inclination to hurtful things,
and are sensible of your loss,
be not discouraged from renewing your endeavours
to regain the ground which has been lost.
We have a merciful Saviour to look to,
who never rejects those who apply to him in faith and repentance.

With desires for your preservation in the path which leads to peace and happiness,
in the present life, and in that which is to come, I remain your sincere friend,

[.signed-section-signature]
J+++.+++ K.

The good esteem I had for several of your relations, now deceased,
with whom I was acquainted, makes me the more interested in your welfare.

It is to be desired that the offspring of those who hare walked in the Truth,
and been honourable in their day, may walk in the same way,
that the reputation of our society may be preserved from one generation to another,
by the religious orderly conduct of its members.

[.signed-section-context-open]
Colchester, 18th 1 Mo. 1802.

[.salutation]
Dear Cousin,

The having so much the approbation of your friends in the intended connection,
makes me think favourably of it, though I have no knowledge of the person nor family.
I am of opinion that religion, if it has a due effect,
will do more towards promoting our happiness, than riches,
even if they should greatly increase.
I wish therefore for my friends, that their principal aim might be,
to have their minds enriched with those treasures which are of everlasting duration.

As it has been your choice to enter into the strait and narrow way,
which our great Lord and master speaks so favourably of;
I much desire it may be your concern to persevere in the same:
this I also desire for your intended companion,
who will find with those who have had experience of it,
that all the ways of piety and holiness, are ways of pleasantness,
and all her paths are peace.

[.signed-section-closing]
I remain your affectionate cousin,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 12th 4 Mo. 1802.

[.salutation]
Dear Friend,

When trouble attends my friends,
especially those to whom I am nearly united in the Truth,
I am ready to wish it might be in my power to afford them relief,
by personal conversation or otherwise, as there is opportunity.
This occasions my present writing;
having heard of some difficulty which you have met with,
for lack of the full concurrence of friends in your religious concern.

It brings to remembrance the disappointments it has been my lot to meet with,
which have proved to my advantage beyond what I had any expectation of;
so that I begin to be more reconciled to what is permitted
to attend in the dispensations of Divine goodness,
and to resign my concerns to the disposal of him who is more propitious
to my peace than I have any apprehension of.

When success does not attend our endeavours in the degree we may wish for,
then is the time to exercise patience; and this, I hope,
will be your experience in the present circumstance,
as likewise in all the future occurrences of your life:
let us get instruction from what is met with, and increase our stock of Christian graces,
which are needed to fit us for the trials of succeeding times.
The advantage of affliction is,
that it tends to prepare us for what we may have to meet with,
and thus we learn to endure hardness, as good soldiers of Jesus Christ.

While I am writing this, I feel true esteem for you,
in that love which unites the Lord`'s people beyond outward connections;
and have to say to you, be not discouraged by what is met with,
nor anxious to discover the cause of this difficulty:
it will prove beneficial to you in the end, as it becomes your concern to wait for help,
and instruction from your gracious Lord and Saviour; who, I doubt not,
has called you into his service, and will help your endeavours for the good of others,
and to your own spiritual advantage.

I may further say, that, considering how short sighted we are,
there is much room to acquiesce in the various events of life, with a pious submission:
and when we do not obtain that which we may desire to have,
we may obtain that which will be more profitable to us.

I would not repeat things with which you are well acquainted,
nor be tedious in my remarks.
My view is, to encourage you to lift up your head above all the waves of affliction.
Your submission to all these dispensations will be acceptable to him who marks our steps,
and tries us, in order to make us more acceptable; and, when the work is accomplished,
will receive us into the mansions of bliss.

I salute you, in much affection, as a fellow traveller in Zion`'s way,
and a fellow-labourer in the gospel of our Lord and Saviour Jesus Christ:
put your trust in him, and let nothing remove your confidence in him;
and he that has begun a good work in you,
will perfect it to his praise and your everlasting salvation.

[.signed-section-closing]
I am your sincere friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 12th 6 Mo. 1802.

[.salutation]
Dear Friend,

I am pleased in reading the small work which you kindly presented to me;
it shows how far the Truth is able to preserve in the midst of affluence,
and what great good comes from the natural abilities with which we are endued,
when sanctified to us, and made use of,
to promote the cause of righteousness in the earth.

It is an occasion of sorrow, in the present time,
to observe many deviations from the plainness and simplicity of our forefathers.
I have thought, that if we keep our places we shall be distinguished from most,
if not all other professors of the Christian name:
not that we are to think others are excluded from the Divine favour
because they do not agree with us as to an outward appearance,
or are in the use of some ceremonies in religion,
which we think not required in these gospel times.
Where we see a Christian-like behaviour, and circumspect walking,
in the fear of the Almighty, there is room to acknowledge such as brethren in Christ,
not being hindered from uniting with them, at least in spirit,
by the different modes which they are brought into by means of education.

Having thus a little deviated from the design of my writing, I shall only add,
that I wish a blessing may attend your labour of love in this work,
as well as other works, in which you may be engaged for the promotion of Truth: that,
as the time approaches in which you must bid adieu
to the enjoyments of this transitory life,
your hopes and expectations may be from those supports and comforts which are to be
known in the favour of him who is the everlasting Father and friend of his people!

My wife joins in kind respects to you, from your affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 17th 8 Mo. 1802.

[.blurb]
=== To the Friends Popplein, of Amsterdam, with other religiously disposed persons who meet together for the purpose of religious worship, in the way, wherein they experience edification and comfort to their minds.

[.salutation]
Dear Friends,

I have remembered you with much affection, and am inclined to write a few lines,
by way of encouragement to you, in your lonely condition.
I would not have you admit any fears concerning the way you are in,
from the singularity of it,
or because it is disapproved by other professors of the Christian name.
If the advantages of it were more fully known,
I have thought many sincere-hearted enquirers, of the different religious societies,
would choose it, as the way to be instructed and built up in our most holy faith;
not that we should be unkindly disposed towards those who differ from us,
as to the form of public worship, which we are led to approve of.

It is not for us to judge how far others may be acceptable
in their addresses to the Supreme Being:
if we are shown a more spiritual way,
and have to experience the benefits of waiting on the Lord
for renewed help and instruction to our minds,
let us attend to this good practice; considering it is the devotion of the heart,
and not the words we may use, which will render us acceptable to him,
who sees the most secret transactions of the mind.
Some may say we seek for higher attainments than our state of weakness will admit of,
but this is for lack of knowing the motives of our conduct.
We expect no greater revelations of the Divine will than are needful
for our instruction and help in the way of Our religious duty;
and this, we think, is most likely to be obtained in quietness,
when the mind is withdrawn from earthly concerns,
and we come to seek for help and counsel from the great head of the church,
and leader of his people, the Lord Jesus Christ.

Having said thus much concerning the way of holding our meetings,
I am inclined to mention my concern,
that your whole conduct may be such as to adorn the profession we make,
as a religious society;
that the prejudices of those who are unkindly disposed towards you may be removed,
by your inoffensive behaviour and friendly disposition towards all men.

In attending to the testimonies we have to bear,
it must be expected that we shall meet with difficulty:
but as we believe they are well grounded,
and the peace of our minds depends upon our observance of them,
we shall not do right to give them up.

When we are awakened to seek after that which may be a stay to our minds,
beyond what a bare outward profession of religion can give,
it is a means of uniting us one to another, and this, I hope, will be your experience:
that as you become convinced of the Truth, and are helped to walk in it,
you may have fellowship one with another,
in the strength of that love which is not produced by earthly motives.

In much affection, and with desires for your welfare, I remain your sincere friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 7th 7 Mo. 1803.

[.salutation]
Dear Nephew,

I have thought it will be no small favour to us, in these times of commotion,
to be preserved in quietness;
I mean so as not to be over much disturbed in our minds
by the reports and threatenings which are spread about.
The little good we can do will be by our prayers to a gracious Protector and Saviour,
that he will help and protect us from the mischief and harms with
which we are threatened by a nation disposed to hurt us.
If there is a concern to please God, by breaking off from the evil of our ways,
we shall have room to hope He will hear our prayers,
and send forth a deliverer in time of danger;
but if we should persist in ways that are displeasing to him,
we may expect chastisements from his hand, which our transgressions deserve.

I take notice of what you say concerning Luther and Melanchton;
they were eminent men in their time, and, I doubt not, instruments in the Lord`'s hand,
for the good of his church: but it has been the failing of good men, in different times,
to have unkind thoughts of the societies and people, who,
not being contented with forms and ceremonies in religion,
which they thought were too much rested in, sought for the more substantial part of it.
Such were the baptists in the time of Luther, and the people called Quakers,
of later times; some of whom being carried into extremes by a false zeal,
gave occasion for the whole society to be spoken against.

In some of the writings of pious men, I observe a great dislike to our society,
placing us among the worst sort of enthusiasts;
they form their judgment of us from the unfavourable
accounts they meet with in the writings of our adversaries,
and the misconduct of some which comes under their notice.
When we speak of others, who differ from us in their religious sentiments,
there is need of much caution,
lest the displeasure we feel should proceed from our own spirits,
rather than from the gentle spirit of our Redeemer.
Tenderness towards those who are not of the same judgment,
is becoming us in our state of weakness;
at the same time we must not favour any conduct or principles
which are inconsistent with the purity of the gospel.
When anything appears, which is contrary to this,
it is to be attributed to us in our natural state,
and not to the leadings of Christ`'s spirit.

Having thus increased my letter beyond what I expected,
shall only add that I am your affectionate uncle,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 30th 7 Mo. 1803.

[.salutation]
Dear Friend L. M--y.

I should think myself lacking in gratitude if I omitted
to acknowledge the receipt of your kind letter,
which came to my hands in London by our friend H. Tuke.
It was comfortable to me to receive such a token of your love,
when I had not expected to be so continued in your remembrance.
Though I find deficiency of strength to visit my friends at a distance,
I consider it as a favour,
that the friendship and love towards them remains as in time past.
I doubt not it will be pleasant to you to be informed,
that our health is continued in a good degree as usual.
My wife accompanied me to London,
and we attended most of the sittings of the yearly meeting.
Though the state of the society, as to its spiritual interest, is not as might be wished,
by the deviation of many from the path of safety, yet we have room to believe there are,
in most places, those in whose minds a right concern has taken place; by whom,
through the Divine blessing on their endeavours,
the precious cause of Truth may be supported.
As it was not by the wit and wisdom of man that we were formed to be a people,
neither shall we be preserved by it, to the praise of our Lord and Saviour,
but by a dependence upon him for the renewed help of his good spirit.
Not all the rules and orders we may have among us, even if they are according to Truth,
and have their rise in Truth, will be sufficient to support us to our own comfort,
and to the edification of the church, without the help of our Divine Master.
It is therefore to be desired that there may be a
revival of religious concern in the society,
lest the good esteem which was obtained by our forefathers, through their faithfulness,
should be lost; and the form, which was adopted by them upon good ground,
should become of no reputation.

I have not much further to add which may be as pleasing intelligence to you,
except that we have had several women friends visiting the meetings in our country,
whose labour in the gospel has been acceptable.
It is to be wished for, that this important concern might rest upon the men,
in a greater degree than has appeared of late.
Not that I would have any of my dear friends take this weighty business
of the ministry upon them without a suitable concern and qualification;
but if there was more liberty from the concerns of this life,
and a greater dedication of heart,
I am apt to think we should have a greater number engaged
in this sacred office to the further help of the church.

I subscribe myself, with tenders of kind love, your sincere friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 18th 11 Mo. 1803.

[.salutation]
Dear Friend,

Yours of the 29th 7 mo.
came to hand, and was acceptable to me, as I desired to be informed of your welfare,
after the losses you have sustained.

I sympathize with you in these afflicting dispensations,
and should be glad to say something which might tend to alleviate your grief.
The experience of many years has shown me,
that it is good to seek for resignedness to the Lord`'s will in all times of trouble.

However great your loss may be, it may not exceed that of some of your dear friends.
I can say for one,
that there has not any long time passed without meeting
with that which has occasioned grief to my mind.
But there is this to comfort us in the loss of our relations and friends,
who we have room to hope are gone well,
that they are removed in the ordering of Divine wisdom, from a state of trial,
into the realms of everlasting peace.
In looking towards this land, we are helped to bear the evils of life,
and to commit our cares and concerns into the hands of our merciful Saviour,
not questioning his goodness,
even if he should hand to us a cup which is full of bitterness.

Though you have not reached to my age, we may consider you as far advanced in years,
with my dear wife, who is now about sixty-eight, and I am near to nine years older.
When we look back upon time past, and think of the many changes we have seen,
it may fill our minds with wonder; also with thankfulness,
in that it has pleased the Almighty thus to give us an opportunity of improvement,
by the exercise of those good qualities which tend to fit us for our last change.

[.signed-section-closing]
From your affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.signed-section-context-open]
Colchester, 7th 2 Mo. 1805.

[.salutation]
Dear Friend R. C--r,

I have received your kind letter, with the account of subscriptions,
for the further help of the poor widows.
I consider myself much obliged to you for this fresh mark of your friendship,
as also for the concern and sympathy you express at the
loss I have met with in the death of my dear wife:
we had lived together about forty years, in great harmony,
so that the lack of her good company and help, in my far advanced years,
is sensibly felt.
I have this testimony to give concerning her, that she was a religiously disposed woman,
of exemplary conduct, and much beloved by her friends and neighbours,
whose welfare she was constantly using endeavours to promote:
the benevolence of her mind was increasing as she
drew near the conclusion of her time here.

Her removal was in about ten hours after being taken with a palsy,
which soon deprived her of speech, except saying to a relation, who was near,
"`Be not disturbed, I am quite easy;`" meaning, no doubt, as to the state of her mind.
She departed this life about ten at night, in great quietness and peace; and, I trust,
it may be said, rested sweetly in the Lord.
Her amiable disposition, which I well knew,
had endeared her to me beyond what words can express:
and there is a sweet memorial of her good qualities imprinted on my mind,
not easily to be erased.
As it has thus pleased the Lord to separate us,
by whose good Providence we were joined together, I desire to be resigned to his will,
without complaining of this or any other affliction, which he may permit to attend.
There is this hope, that, after a few fleeting moments,
we shall have to meet again in those mansions of rest and peace, where no troubles,
like them of this life, can reach us!

My cousin A. D. joins in kind love to you, from your affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.offset]
The following short character of my dear wife is
taken from the Ipswich Journal of January 19th,
1805.

[quote]
____
On the 5th Inst, died in Colchester, after a short illness, Ann Kendall,
the wife of John Kendall, aged about seventy, one of the people called Quakers,
sincerely lamented by the poor and a numerous acquaintance.
Those who knew her best are most sensible of the worth of her character!
She was a woman of a humble and retired turn of mind, of unfeigned piety,
one who sincerely regarded all who walked in the ways of Truth and Righteousness:
her house was always open for the reception of her friends,
especially those who came with a message of peace,
whom she esteemed for their work`'s sake; and who could say of her,
as the apostle said of Phebe, "`She has been a succourer of many, and of me also.`"

The benevolence of her mind appeared on every proper occasion; and, more especially,
in that well-known charity in the town of Colchester,
an alms-house for the benefit of poor widows, which she was the means of establishing.
____

[.signed-section-context-open]
Colchester, 11th 10 Mo. 1804.

[.salutation]
Dear Friend,

I have nothing in particular to inform you of, concerning your late publications,
except that I have endeavoured to make use of them, as there was occasion.
Many valuable works have been published of late,
tending to promote the cause of religion; and I hope they will be productive of good,
as a check to that undue liberty which has taken place in the minds of many,
and from which our society is not exempt.
I am often troubled to see the appearance of many
of the young people among us as to their dress,
so much unlike our friends in early times: it makes me fear,
that the good testimonies we have to bear to the world will come to be lost among us;
so that the Lord`'s complaint by the prophet, concerning Israel, may be taken up,
"`This people have I formed for myself, they will show forth my praise.
But you have not called upon me, O Jacob! but you have been weary of me, O Israel.`"

These thoughts have occurred to me, in writing to a friend, with whom I can be free:
at the same time I desire to be cautious,
not to lay an improper stress on the outward appearance; which, however plain and simple,
will not recommend us to the favour of him who judges not after the sight of the eye,
but looks at the heart.
I think, however, as religion takes place in the mind, it will lead us to much plainness,
and keep us from altering our dress, from time to time,
according to the fashions of the times; as also from a conformity to customs and ways,
which our forefathers were led to decline.

In the same love which has prevailed in our minds towards each other,
and likeness of disposition, for promoting the welfare of our friends,
and mankind in general, as ability was given, I remain your affectionate friend,

[.signed-section-signature]
J+++.+++ K.

[.salutation]
Dear Nephew,

My engagements are not such as to make me forget my old friends;
neither am I indifferent as to maintaining the friendship of those I love.
I desire we may be closely united in that precious
Truth which has been the means of our acquaintance.
The saying of the apostle frequently occurs to me; "`If you walk in the light,
as God is in the light, then you have the fellowship one with another.`"

Without this, I have thought, there is no true fellowship to be known,
however much we may agree in the observance of rites and ceremonies.
The church of Christ consists not of all those who are called by his name,
but of such who are united to him, in a spiritual relation,
by means of obedience to the dictates of his good spirit in their minds.

With regard to the difficulties of the present time, which you take notice of,
I have thought it will be a great advantage to us to be kept in quietness,
endeavouring to act, consistently with our profession, as peaceable subjects,
who pray for the welfare of the government under which we are placed.
If troubles should be permitted to attend, it will be good for us to exercise patience,
and say with pious Job, "`The Lord gave, and the Lord has taken away,
blessed be the name of the Lord.`"

It is a cause of comfort to consider, that there are among us many pious persons,
who are imploring the Divine favour as a remnant of that love, and fear of God;
for whose sake the judgments, which been threatened, may be averted.

I remain, with tenders of kind love, in which my wife joins, your affectionate uncle,

[.signed-section-signature]
J+++.+++ K.

[.postscript]
====

It may give you pleasure to hear that our charity
for poor widows has succeeded beyond expectation.
There are in the houses eight women,
the widows of poor men who died in the charity of Arthur Winsley.
A neighbour has left to it, by will, upwards of five hundred pounds,
and another neighbour two hundred pounds;
these bequests have enabled us to enlarge the weekly allowance to the widows.

====
