[short="Remarks on Attending Stage Entertainments"]
== Remarks on the Prevailing Custom of Attending Stage Entertainments; also on the Present Taste for Reading Romances and Novels; and on some other Customs

Submitted, with a heart overflowing with good-will,
to the notice and consideration of the Professors of the Christian name,
in the different religious Societies.

Vitarc peccatum, est vitare occasioncs peccati.

Reprinted from the Third Edition.

=== Remarks, etc.

It has often grieved me to observe a disposition in my neighbours and acquaintance,
to attend the plays and assemblies, and other places of public entertainment;
more especially at a time when we are called upon,
by the almost unparalleled afflictions which at present attend a neigbouring nation,
and the late visitation of Heaven by sickness,
among those who are more nearly allied to us,^
footnote:[The city of Philadelphia is here meant,
where upwards of 3000 of the inhabitants died by a sickness,
not much different from the plague, in the space of a few months.]
to be sober-minded, and amend our ways; as the like may be permitted to reach us,
if our transgressions should so increase as to require such chastisement.

I would have us disposed to seek the favour and blessing of the Almighty,
by breaking off from our sins; and ordering our lives, through his assistance,
in great sobriety and temperance; rather than indulging ourselves in vain shows,
which tend to unfit for the concerns of immortal spirits:
whose happiness consists in the practice of virtue,
and a near approach to that Sovereign Good,
without whose favour no happiness can be experienced.

Though the entertainments of the stage continue to be used,
as though they were necessary to the well-being of a people,
and are not disallowed by the law of the land, I can venture to say,
they are disallowed by the law of righteousness placed in our minds;
and are contrary to the nature of the religion we profess,
and the injunctions of those sacred records we so much place our dependance upon,
as a rule of our faith and practice.
We shall find nothing in the practice or precepts of Christ (the great example
and high-priest of our profession) or in the writings of his apostles,
to countenance these diversions; but instead of it, a constant watchfulness recommended.
So that it will not be easy to open any part of the New Testament,
without meeting with passages which tend to show us the necessity of using
our endeavours to be prepared for a removal from this scene of action;
in which, while we are doubtful concerning many things; and see only in part,
as to the wonderful productions of nature,
and the conduct of the great Author of our being, in the formation of man,
and the earth he inhabits; we are certain as to the testimony of our conscience;
which informs us of the way we should walk,
and what tends to promote the peace of our minds, and the favour of heaven:
as the prophet declares, "`God has showed you, O man, what is good:
and what does the Lord require of you, but to do justly, love mercy,
and walk humbly with your God.`"

Let us be awakened by the intimations of decay, which we feel, from time to time,
in ourselves, end the frequent objects of mortality placed before us.
They ought to be regarded as calls to prepare for our removal.
The time of sickness, and great bodily weakness,
is not the time to be depended upon for working out our salvation,
with fear and trembling, as the apostle advises;
but rather a time when our greatest comfort should
be to look back upon the former part of our lives;
and consider the sacrifices of love and obedience
we have made to the great Author of our being;
and how we have endeavoured to walk before him (through the assistance
of his good Spirit) in all holiness of life and conduct,
with a perfect heart.
Even then we have nothing to depend upon but the mercies of a gracious God,
through his Son Jesus Christ, who remembers our weakness, and has sent help to us;
if we are willing to receive it, and make use of it.

But what will become of those, who, neglecting this great salvation,
persist in the indulgence of vain inclinations,
being lovers of pleasure more than lovers of God; to whom seriousness,
and serious people, or serious thoughts, are burdensome; of whom it may be said,
too truly, they live as without God in the world?
What will be the end of these?
If the righteous scarcely are saved, where will the ungodly and sinner appear?^
footnote:[1 Pet. 4:8.]

To speak freely, I can see nothing in these assemblies,
or in the discourses of the stage, which has a tendency to promote the practice of piety,
or a good life; but, on the contrary, they are likely to weaken the best resolutions,
which may be formed to amend our ways, and reform our lives.
Meeting with many in these places, who are disposed for pleasure,
we are in danger of being brought to lay aside the restraints of religion,
by which only we can be kept in the bounds of Christian moderation.
I would, therefore, advise my neighbours and acquaintance,
and all into whose hands these may come, to decline the practice of attending them,
if they have at any time indulged themselves in it.
I think it most of all unsuitable for the ministers
of religion to countenance these entertainments,
by their presence, or in any other way.
I would warn them to keep at a distance, lest harms should come which they may not expect.
No example, however,
of others (in whatever station they may be) should draw us to a conformity,
in things which our conscience dictates not to be expedient nor safe for us.
If we should transgress the rule of virtue and holiness placed in our minds,
as a direction and help to us in our passage through life;
who knows but we may be left to follow the devices of a wicked heart,
till great mischief comes?
The contest with evil inclinations must be kept up,
or we shall soon be lost to what is good for us here,
and will prove of everlasting advantage hereafter.
If we indulge in the pleasures of this world,
we must part with the peace and inward complacency of a conduct ordered in God`'s fear:
which may be called his kingdom, here begun on earth,
in the hearts of those who follow him in the way of his leadings.

Another consideration makes me disapprove of the custom; which is, that few, if any,
attend the play-house from religious motives,
to be instructed and benefited as to their moral conduct;
but I am apprehensive people go, for the most part, with a view of being entertained,
and diverted by ludicrous shows and discourses,
and other performances which tend to enervate the mind.
If the advice of the apostle is regarded,
"`abstain from all appearance of evil,`" we shall keep away from these nurseries of vice,
and find a more rational and Christian-like way of spending our time.

I would further observe, that we cannot with safety conclude, that,
because these entertainments have been long in use, and are become general,
they are therefore allowable.
If any customs of those who lived before us appear to be
inconsistent with the religion we make profession of,
it will be right to lay them aside.
The frame of the human mind is such as to admit of improvement from age to age;
so that things which were practised in former times, are now seen to be improper,
and are no longer in use, as might be shown in many instances:
and we are ready to wonder how men could be so void of a right understanding,
as not to see the impropriety of such conduct.

Thus I trust it will be in some future time, with respect to stage entertainments;
if the inconsistency of them should not be seen by us of the present age.
As light and truth rise, like the sun, on the minds of people,
and they are obedient to them in succeeding times, these, with some other things,
will he removed from states and nations professing the Christian name,
and be no longer in use.
This is my belief; which affords me comfort,
in a prospect of the increasing happiness which may attend some future generations.

But however it may be in succeeding times,
we are to attend to the discoveries of truth in the present time;
and as any information or warning comes to us, it will not be safe hastily to reject it,
because it comes not in the way our reason may suggest;
or may be contrary to the sentiments we have of things,
from prejudices of education or otherwise.
We should remember, many discoveries of truth have been made by means of instruments,
weak in the sight of men, and of low condition in this world,
but favoured by heaven with wisdom, beyond many of their fellow creatures:
and much good would have come from their instructions, had they been regarded.

I speak this, that there may be a disposition to receive what is proposed for our good.
It is well known we must be removed from this state of trial,
and that it often happens in a way and time which are not expected.
We are also assured there is a future state,
in which the most excellent part of us will exist through unnumbered ages;
and that there are joys prepared, as the reward of virtuous conduct;
and unspeakable sorrow for those who err from the path of virtue;
according to the mercy and justice of the Great Ruler of the universe.
Such thoughts should make us desirous of spending our days in the fear of God; waiting,
with a humble hope of being admitted into his presence,
to join the assembly of the righteous of all generations.
But if the God who made us is not in our thoughts,
but rather an anxious pursuit after the perishing enjoyments and pleasures of this life;
what shall we have to depend upon, when they are taken from us?
How shall the void be filled up in our minds, when the world, and all that is in it,
sinks under our feet;
and leaves us without those comforts we have been used to draw our support from?

I am inclined to add the sentiments of some excellent
persons in times past on this subject,
in hopes their judgment may tend to check these indigences.

Archbishop Tillotson says of plays;

They are not fit to be admitted in a civilized, much less a Christian, nation.
They do most notoriously minister to vice and infidelity.
By their profaneness, they are apt to instil bad principles into the minds of men,
and to lessen that awe and reverence which all men ought to have of God and religion:
and by their lewdness, they teach vice, and are apt to infect the minds of men,
and dispose them to lewd and dissolute practices.

Another writer remarks, "`Those who think that plays make no ill impression on them,
because they do not find them excite any formed evil desire, deceive themselves greatly.
There are many degrees before one comes to an entire corruption of mind;
and it is always hurtful to the soul,
to destroy the ramparts which secured it from temptation.
One does not begin to fall when the fall becomes sensible.
The fallings of the soul are slow; they have progressions and preparations.
We may be overcome by a temptation,
only by having weakened ourselves in occasions which seemed of no importance:
he who despises small things shall fall by little and little.
Let not those who do not find that romances and plays excite in
their minds those passions which are apprehended from them,
think themselves, therefore, in safety;
and let them not imagine these books and sights have done them no hurt.

"`But supposing it true, that plays have no ill effect upon some persons, they cannot,
however, think themselves blameless in being present at them.
Plays are not acted for one person alone, they are exposed to all sorts,
of which the greater part are weak and corrupted; and to whom, by consequence,
they are extremely dangerous.
`'Tis their fault, you`'ll say, to go to them in that state.
That`'s true, but you authorize them by your example:
you contribute to make them look on plays as a thing indifferent:
the more regular you are in other actions,
the bolder they are to imitate you in this--You are accessory then to their sin;
and if plays give you no wounds of themselves,
you wound yourselves by those which others receive from your example;
and thus you are the most guilty.
Let it be considered.`'

Nothing better shows the danger of plays, and how much they are forbidden to Christians,
than their opposition to the state of mind in which
we ought to endeavour to establish ourselves,
by continual requests for preservation.
For temptations being in a manner continual, prayer, which is the remedy against them,
ought to be so too.

It appears by writings of the Christians in the first ages of the church,
that they considered the entertainments of the stage contrary to their profession,
and wholly unlawful for them.
It will be well for us to consider,
if they are any more allowable to us of the present time;
who are called by the same name,
and profess to be reformed from the superstition
and other gross practices of a degenerated church.

One of the early writers thus expresses himself:

Many imagine it is not certain there is any sin in going to the play; but,
whatever they may think of it, plays do certainly cause abundance of evil:
for the pleasure that is taken in them produces all sorts of debauchery.
We are not only obliged to avoid sin,
but we ought also to shun those things which do insensibly lead to it.

He adds,

It is not fit for us to pass our time in diversions and entertainments,
which are only fit for players.
This is by no means the spirit of those who are called to an eternal kingdom;
whose names are written in the celestial city, and profess a spiritual warfare.
It is Satan who has made an art of these diversions,
to draw away the soldiers of Jesus Christ to himself,
and to relax the vigour of their virtue.
For this end he has caused theatres to be erected in public places;
and makes use of them to infect, as with a plague, the whole city.
St. Paul has forbid foolish jesting, and whatever tends to vain diversion;
but Satan persuades us to love both the one and the other.

A writer of great note, and general esteem, of later times, says,

The hearts of men are so perverse and blind,
that they imagine the world to be in full felicity,
when the inhabitants of it think of nothing but adorning and embellishing their houses,
while they take no notice of the ruin of their souls;
when magnificent theatres are built, and the foundations of virtue thrown down;
when the abundance of the rich maintains the luxury of players,
while the poor lack what is necessary for their subsistence.
If God permits those disorders to prevail, and leaves these crimes unpunished,
`'tis then he may be said to punish them most severely;
but when by poverty he prevents the increase and excess of voluptuousness and dissipation,
however contrary to our desires, it is an effect of his mercy.

Having made these remarks on the stage entertainments,
which are so much attended to in the present time,
(in my apprehension to the great hurt of the nation,
both in its civil and religious capacity),
and eased my mind a little of the weight which I have felt on this account;
I shall proceed to say something concerning the disposition for reading Novels,
and other books calculated to afford diversion and entertainment;
the sale and hire of which make a considerable part of the business of a bookseller,
in most parts of the nation.
The hurt which attends the reading these books it like to be great,
to the youth in particular; who,
instead of being formed to the practice of religion and virtue,
and instructed in a Christian-like conduct, by frequently reading the Holy Scriptures,
and other excellent writings which may tend to form good principles,
have their minds filled with ideas of vanity and lightness,
and are ready to forget the obligation of a humble walking in the fear of God,
in a land from which they must soon be removed!

If Christian characters were exhibited in these compositions,
with a view to promote the interests of religion
and piety (which I fear is seldom the case),
there would be the less objection to them;
but when it appears they are intended merely for the purpose of amusement,
and rather to banish serious thoughts and reflections, than to strengthen them in us;
it gives room to fear great harm will come from this
method of spending our precious time:
much the same as by seeing and hearing the actions and speeches of the stage;
and it ought to be equally avoided by those who desire to
be helped in all the ways of promoting their best interests,
and to be preserved from the contaminating evils of a wicked world.

I would also caution against reading some publications of the present time, which,
under a specious appearance, tend to subvert the doctrines of Christianity;
by a presumptuous abuse of reason, and by vain disputations,
after the rudiments of the world, and not after Christ.

Having said thus much on some customs of the present time,
which have a tendency to lay waste the obligations of religion,
and lead from that humility and fear,
which are the ornaments of the Christian profession;
I am inclined to take notice of the great neglect which appears among us,
both in those of high and low degree, in attending places of worship,
on the day appointed by the laws of the land for this purpose.

If the number of servants who are employed to prepare our food, to ornament our persons,
and provide for our travelling from one place to another, on this day,
were rightly considered; it would fill our minds with sympathy,
for so many of our fellow creatures,
who are thus deprived of the opportunity of public instruction,
and it is to be feared have little, if any, afforded them at other times.
If it is true that we often need to be reminded of our duty, and that,
even with frequent instruction, we are apt to deviate from a virtuous conduct,
how is it like to be with this numerous class of the people,
who are left in a neglected state,
as if they had no other part to provide for than their perishing bodies,
nor any other concern than what relates to the present life and its enjoyments?
Whereas it is certainly known, they have souls to be saved or lost,
and are in the same awful state of trial with those they serve.
God has declared by his prophet the souls of men are his, '`As the soul of the Father,
so also the soul of the Son is mine; the soul that sins, it shall die.`'^
footnote:[Ezek. 18:4.]

Let us mourn for the condition of thousands of our fellow creatures,
who are left in a great measure destitute of outward instruction,
wallowing in the mire of sin and pollution without restraint;
unless they are stopped in their course by the immediate visitation of Heaven:
which must not be presumed upon,
but the means of help and instruction are to be made use of.

I consider the state of many,
who are employed in the different manufactories and trades of the nation, as workmen,
who are no further under the direction of their masters,
than to do the work appointed them, and receive their wages;
how they spend much of their time in public houses,
and contract habits of drinking strong liquors, to the great injury of their health:
so that numbers are brought to their graves, who might have lived many more years,
and been useful members of society,
had they conducted themselves by the rules of reason and religion,
and kept within the limits of temperance.
Having been in the practice of spending much of their time in these houses,
on other days of the week, they have no comfort in attending a place of public worship,
on the day appointed for this purpose;
but still resort to the place where they have been used to gratify their appetites,
to associate with such as are like-minded, to rejoice and be merry;
to the endangering their peace and happiness in the present life,
and in the life which is to come.

What words can be used to express the harm a which proceed from this conduct,
not only to themselves, but to all with whom they are connected:
and to the nation at large,
whose sins are accumulated by the undue liberties of individuals!
Have we not room to expect,
that after much long-suffering of the great Ruler of the universe,
and many warnings given to an offending people, great troubles may come,
as the chastisement of wickedness persisted in, and not repented of?
In the affection of a brother and friend,
I would request of those who are in the higher stations, of heads of families,
and rulers in the land, that they would come forward by their example,
to stop the increasing dissipation and undue liberties, which are taken in many respects,
to the great dishonour of the Christian name!

A certain writer says,

It is a sad consideration that the interest of the revenue
should be permitted to prevail over the good of the nation:
and the conduct of those servants of the public deserves severe animadversion,
who presume to grant licences to public houses in town and country,
contrary to the wish and opinion of gentlemen who reside near to them;
and are witnesses to their fatal consequences to the health and morals of the people.

This is indeed reversing the order of civil government,
and elevating inferior interests to the most important principles.

In speaking of the propriety and usefulness of having one day in the week,
most especially, appropriated to religious purposes,
I wish to bring into the view of those who may road these lines,
the example of a great man of the former age,^
footnote:[Sir Matthew Hale.]
who says, in the instruction to his children,
concerning their observation of the day called Sunday,

Opus Diei, in Die suo.

I have found, by long experience, that the due observance of this day,
and the duties of it, have been of singular comfort and advantage to me;
and I doubt not will prove so to you.

God Almighty is the Lord of our time, and lends it to us;
and it is but just we should consecrate this part of that time to him.
So I have found that a due attention to the duty of the day,
has ever had joined with it a blessing on the rest of my time;
and a week that has been so begun, has been blessed and prosperous to me;
and on the contrary, when I have been negligent of the concerns of this day,
the rest of the week has been unsuccessful to my own secular employments;
and this I do not mention inconsiderately, but upon long observation and experience.

It is said of this good man, in the account of his life,
that he was constant in his attendance on public worship, with very little intermission,
for near forty years.
And it is to be wished, that all of the present time, who are in eminent stations,
might be disposed to follow his example in this, as well as other parts of their conduct;
for though he was in affluent circumstances,
and could have indulged himself in many delights and pleasures,
which inclination leads to, he thought it best to keep within the bounds of moderation;
and so to conduct himself in the fear of Almighty God,
as to be fit for a removal from this state of trial,
whenever the summons might come to him from the great Ruler of the world!

Another writer on the subject, which I have met with, says,

The fourth commandment, which enjoins a certain day to be observed as a sabbath,
cannot be called moral in the first and highest sense;
for from the nature of things no reason can be assigned, why the seventh day,
rather than the sixth, or the eighth, or any other day,
should be separated from the common business of life, and applied to the service of God.

But it is moral that a man should pay homage to his Maker,
and acknowledge him in all his works and ways: and since our senses,
and sensible objects, are apt to wear better things out of our thoughts,
it is necessary that some time should be set apart,
for more full and copious meditation on these subjects: this should be universal,
lest if the time were not the same everywhere,
the business of some men might interfere with the devotion of others.

It ought to have such an eminent character on it (like a cessation from business),
which may occasion an inquiry into the reason of that stop,
and also may give opportunity for meditations and discourses on those subjects.

`'Tis true, we who are called to a state of freedom,
are not under such strictness as the Jews were, still the law stands,
for separating a day from the common business of life,
and applying it to a religious rest.

I may mention, however, with sorrow,
that in opposition to the general consent of the nation and laws of the land,
it is now become customary with us for people to travel in stage-coaches on this day,
in the same manner as on other days of the week.

Instead of making use of it to meet at places provided for public worship;
many are taking their journeys to different parts of the nation, some on business,
and others on pleasure;
so that it is not uncommon to see the coaches loaded with passengers this day,
to the grief of serious people of every society, who remember the uncertainty of time,
and aim to improve it in such a way as may tend to their everlasting good.

Another custom I wish might be avoided on this day, is that of reading newspapers.
There is a natural curiosity in the mind to be informed of the transactions of the times,
and very allowable in its proper place and time; but, if I am not mistaken,
it will be for our advantage to restrain our thoughts, as well as employ them,
on this day, to the more important concerns of our souls:
that we may not be encumbered with cares of this perishing world,
in the time which should be devoted to a better purpose.

We have had the offers of happiness and peace, as to our temporal condition,
as well as the things of everlasting concernment,
which I fear have been too little noticed.
And now, if the Almighty is pleased to visit the nations by his judgments,
what can we think is more likely to avert his displeasure, than our endeavouring,
through the assistance of his good Spirit, and by sincere repentance and amendment,
to walk in holiness of life and conduct before him; still having in view his omnipotency,
his knowledge of all our ways, and his just retributions to the sons of men?

Though his government is mysterious,
and many evils are permitted to take place in a disordered world;
yet it may be a comfort to them that fear God, to consider, that nothing happens,
either of a public or private nature, but what he sees, in our conduct,
from the king on the throne to his subject in the lowest condition.

I would not have it concluded, from what is said,
in favour of setting apart one day in the week more especially for religious purposes,
that I place so much stress upon it,
as to think the attending on public worship one day
will make amends for the misconduct of other days;
or that the observance of any rites or ceremonies
will be available to obtain the favour of heaven,
while we remain in a state of transgression,
and are violating the righteous law of heaven written in our hearts.

In conclusion, I would say, as my intention in the preceding remarks is,
to recommend the practice of that which will promote the
peace and prosperity of individuals as well as families,
both as to their temporal concerns,
and also those comforts which are of everlasting duration,
I am the more free to make them public, and the less afraid of giving offence.

And, my request to the Author of all good (whose favour is above all things to be sought for,
though it be with the loss of many sensual gratifications), is,
that his blessing may attend the weak endeavours of his servant,
to promote the cause of religion and virtue;
and that the attention of some inconsiderate minds may be turned to those concerns,
which have a tendency to prepare us for a removal
from this transient state to a happy eternity.

The following short reflections,
being met with since the first publication of this Tract,
are thought not unsuitable to be brought under the reader`'s notice;
as containing matters of great importance to all who desire
to pass the time of their continuance in this life,
so as to have a well-grounded hope and happiness hereafter.

There is nothing I ought to wish for so much,
as to have my heart clean in the sight of God, so that after I die,
my soul may be happy forever.
But how may I secure to myself this blessing?
By performing with the assistance of his grace, my duty to him, my duty to my neighbour,
and my duty to myself.

My duty to God, is to love, honour, and fear him, as my Maker, my Governor, and my Judge;
remembering that he knows all my thoughts, and sees all my most secret actions.
I must accept every dispensation of his providence
with thankfulness--I must also keep his commandments;
and pray to him to pardon and bless me for the sake of Jesus Christ,
who died to save the souls of all men, upon condition that they sincerely repent,
turn unto him in faith, and endeavour, by obedience to his will,
to live a virtuous and holy life.

My duty to my neighbour, is to love him as myself;
and to take care that all my actions be just and honest, my words true and sincere;
and all my thoughts charitable and kind; that so I may, in every respect,
do to all others, as I would they should do unto me.

My duty to myself, is to be sober, chaste, and temperate;
to spend my time prudently and profitably; to examine carefully the designs of my heart,
and to keep my conscience free from offence in the sight of God and man.

If I sincerely apply my heart to these duties,
I may humbly hope that the Almighty will continue unto me the assistance of his grace,
and, will thereby enable me to perform them: and then I shall be made happy in this life,
and eternally happy hereafter.
