[short="Testimony from Colchester Monthly Meeting"]
== A Testimony From Colchester Monthly Meeting, Concerning John Kendall, Deceased.

It having pleased Almighty goodness to remove from works
to rewards our ancient and beloved friend John Kendall,
we are concerned to bear testimony to his zeal in the cause of Truth,
during a long and honourable life; which is not only due from us as a tribute of love,
but as an incitement to those who are left behind, to follow him,
as he endeavoured to follow his great Lord and Master; that so, at the close of time,
we may also hope to obtain that unfading inheritance,
which we doubt not this our dear friend is the happy partaker of,
"`where the righteous shine forth as the sun in the kingdom of their Father.`"

He was born at Colchester in the year 1726, of parents religiously disposed,
and early in life became a zealous supporter of our Christian doctrine and discipline;
and about the 21st year of his age,
he came forth in a public testimony in a Meeting for Worship.
In the year 1750,
he accompanied Daniel Stanton in a religious visit
to Friends in the northern parts of England,
and into Scotland;
and two years after was concerned again to leave home in the service of the ministry,
and was frequently engaged during nearly forty years,
in visiting various parts of this kingdom, in company with various friends,
and once the midland counties by appointment of the Yearly Meeting.
He was five times engaged in religious visits to Holland,
one of which was also by appointment of the Yearly Meeting,
and once to some parts of Germany.
In the year 1764, he married Ann Havens, daughter of Philip and Ann Havens of this town,
who died in 1805, and of whom he has left the following short testimony:
"`She was a woman of great humility, never aiming at high things,
nor to be highly thought of;
one who from her youth upwards was preserved walking in the fear of the Lord:
the benevolence of her mind appeared in many instances,
especially in a Charity for the benefit of Poor Widows, in the town of Colchester;
which she was the means of instituting,
and contributed largely towards building a house for their accommodation.`"
Since the year 1791,
it does not appear that our dear friend was much engaged in travelling,
other than to his own Quarterly Meeting, and the Yearly Meeting in London,
which he attended with little intermission for the space of sixty years.
He was concerned through life, as well by example as precept,
to encourage all around him to the exercise both of civil and religious duties.
If the character of any individual was brought in question, he would,
if he could not excuse their failings, avoid the conversation;
thus evincing that charity which thinks no evil.
His latter years were much occupied in writing for the press,
either tracts of which he was himself the author,
or extracts from the writings of others.
Such was his concern for the good of all,
as led him frequently to call at the public houses in his native town,
to admonish those whom he found there, against the baneful evils of intemperance;
and twice he attended at the theatre, and at several times other public entertainments,
to warn those collected against such dissipation;
thus the tenor of his valuable life manifested a zeal for
the glory of God and the welfare of his fellow creatures.
On the 28th of 6 mo.
1812, he met with a fall, by which he fractured his arm,
and was in consequence confined to his chamber several weeks;
a friend the next morning observing to him,
that he had often recommended the exercise of patience, he said, yes;
and he now hoped he should himself put it in practice,
and that he had often imes experienced the blessed effects of it.
After a short pause, he said,
"`The longer I live the more I am confirmed in the preciousness of the principles, we,
as a Society profess.`"
A friend calling after meeting on a Fourth-day, he said,
"`it is trying to lie in so very weak a state of body,
but I hope it will all tend to my further preparation,
and fitness to meet my dear Saviour.`"
And then repeated several texts of scripture, and two or three verses,
which was his frequent practice, particularly the following:

My fears and cares and doubts are known, O Lord, to you;

If I am helped to do your will, it is enough for me.

Desiring his love to all his friends, he repeated these words of our Saviour,
"`Let not your heart be troubled, you believe in God, believe also in me.`"
He recovered strength after a while, and was able to walk to meeting,
and on First-day morning, 9 mo.
13th,
he earnestly advised Friends "`to use all diligence to make
their calling and "`election sure.`"--11th mo.
4th (First-day), at meeting, he again appeared, and said,
that the call to a people formerly had much affected his mind,
"`Prepare to meet your God, O Israel.`"
--11 mo.
7th, he reminded Friends of the prayer of Agur;
and in the evening said to one who called upon him,
"`My greatest comfort is to lie still in supplication to the Almighty.`"
At another time he said, "`O! if but one glance of my Saviour`'s presence,
it makes amends for all the pain I feel.`"--1813, 6 mo.
28th, he fell down in his parlour, and fractured his thigh,
after which he went no more out, but was confined upstairs.
--1814, 7 mo.
11th, he said, "`It is frequently the desire of my mind,
that no complaining may be heard in my streets,
but rather the voice of thanksgiving and praise,
to Him who has been my preserver and helper, all the days of my life.
I have not aimed at great things,
but have endeavoured to promote the cause of Truth
and Righteousness up to this day.`"--At another time,
in the course of his illness, he expressed a desire, that,
"`as our meetings are frequently held in silence, and much stripped of outward ministry,
Friends might be the more engaged to seek for that help and strength to their minds,
which would enable them to perform acceptable worship.`"-- 9 mo.
12th, two friends calling on him after meeting, he said,
"`I am pleased to find some of my dear friends are
concerned to a diligent attendance of their meetings,
and it is pleasant to believe that I shall leave behind those in this place,
who will support our testimonies,
and be as standard-bearers in the cause which I have so long advocated:
I have great consolation in reflecting,
that I have devoted a long life to the blessed cause of Truth,
and have supported it with my faculties and my substance.`"
At another time he said, "`Our lives are in the hand of a kind Providence,
to give or take away, and I desire we may be helped to be thankful for his dispensations:
I wonder my days are thus prolonged;
but amidst afflictions I have cause to be thankful for many mercies:
we have an unwearied enemy, who seeks to draw us aside,
and if he cannot by great things he will by little ones; but while I am speaking,
I feel great thankfulness in my mind, that we are not left without One to help us;
this is an unspeakable mercy.
I have had a great share of the Lord`'s goodness to me both by sea and land,
and now my life is spared in a wonderful manner.
I can recommend nothing better to us than the love of God.
O! this brings great sweetness with it.`"

The following; portions of Scripture were often repeated by him during his confinement,
"`The Lord is my Shepherd, I shall not want; he makes me to lie down in green pastures,
he leads me beside the still waters.`"
"`All the days of my appointed time will I wait till my change come.`"
"`There is a river the streams whereof make glad the city of God,`" saying
he was frequently favoured to partake of the streams of this river,
which he believed to be Divine love flowing from
the fountain and source of all goodness and perfection.
On being asked a few days before his departure how he felt his mind, he replied,
"`All sweetness:`" and soon after added, "`O Death, where is your sting?
O Grave, where is your victory?`"
The day before he died, he called his niece to his bedside, and said to her,
"`Dear Cousin, let us wait for the Spirit of Truth, the best instructor,
which will lead and guide us into all Truth.`"
During the night he said,
"`I love--I love all young people that love religion,`" which he repeated several times.--1815,
1st mo.
27th, about half an hour before his close, he said to a friend,
"`I am gradually going;--resignation slopes`"--but could not articulate more
than-- "`Farewell -- farewell!`" and in great quietness quitted this life,
in the 89th year of his age; evincing, by the calmness of his evening,
that his day had been blessed: a minister about 67 years.

His remains were interred in Friends`' burial ground
at Colchester the 3rd of the 2nd month,
attended by a large number of Friends and others.

Signed in Colchester Monthly Meeting, held by adjournment the 1st of the 3rd Mo. 1815.

Thomas Thorby, Clerk, Thomas Catchpool, John Gripper, Edw.
Upcher Brockway, John Dehorne, Joseph Catchpool, Isaac Kendall, Jonathan Powell,
Edward Gripper, Isaac Barrett, William Cross, Robert Dell, James Candler,
Thomas Catchpool, Jr., Peter Potter, James Barritt, Isaac Young, John W. Cross,
Charles Hicks, Robert Knight, John Barrett Young

Signed in the Women`'s Meeting held at same time, by

A+++.+++ E. Brockway, Clerk, Jane Catchpool, Elizabeth Gridley, Sarah Garritt, K. Catchpool,
Sr., Elizabeth Davison, Elizabeth Kendall, Emma E. Woodward, Mary Catchpool,
Mary Powell, Susanna Barrett, Mary Candler, Hannah Bass, Elizabeth Coe,
Katherine Catchpool, Eliza Kendall, Elizabeth Catchpool, Mary Kendall, Rebecca Barritt,
Elizabeth Powell, Emma Woodward, Matilda Brockway, Ann Cross, Eliza Thorby,
Rebecca Candler, Hannah Sewell, Hannah Cross, Elizabeth Wood

Read and approved in Essex Quarterly Meeting, held at Coggeshall 14th of 3rd Mo. 1815,
and signed in and on behalf thereof by

John Gripper, Clerk.

Read and signed in and on behalf of the Women`'s Quarterly Meeting by

Hannah Marriage, Clerk.
